import Flapjack.Misc.BinaryIeeeRound

/-!
Direct HOL oracle rows for the binary64 rounding constants
(`scripts/hol-probes/binary_ieee_round_constants_probe.out`, generated by
`binary_ieee_round_constants_probeScript.sml` from HOL's
`src/floating-point/binary_ieeeScript.sml:355-365`).  All three rows are
kernel-checked.
-/

namespace Flapjack.Test.BinaryIeeeRoundParity

open Flapjack

/-- `largest_fp64=…` -/
theorem largest_fp64 : holFloatLargest 52 11 =
    179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368 := by
  decide +kernel

/-- `threshold_fp64=…` -/
theorem threshold_fp64 : holFloatThreshold 52 11 =
    179769313486231580793728971405303415079934132710037826936173778980444968292764750946649017977587207096330286416692887910946555547851940402630657488671505820681908902000708383676273854845817711531764475730270069855571366959622842914819860834936475292719074168444365510704342711559699508093042880177904174497792 := by
  decide +kernel

/-- `top_is_largest=T` -/
theorem top_is_largest : holFloatToReal (holFloatTop 52 11) = holFloatLargest 52 11 := by
  decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS binary_ieee largest/threshold/float_top at binary64 match all 3 HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.BinaryIeeeRoundParity
