import Flapjack.Misc.BinaryIeeeRoundFp64
import Flapjack.Misc.MachineIeee

/-!
Direct HOL oracle rows for `float_round roundTiesToEven` at binary64
(`scripts/hol-probes/binary_ieee_round_fp64_probe.out`, generated by
`binary_ieee_round_fp64_probeScript.sml` from HOL
`src/floating-point/binary_ieeeScript.sml:411-515`).  Each row is a
kernel-checked theorem about the HOL rendering `holFloatRound` itself.  It is
proved by rewriting with the conformance theorem `holFloatRound_rte_fp64`
and evaluating the computable algorithm in the kernel.
-/

namespace Flapjack.Test.BinaryIeeeRoundFp64Parity

open Flapjack

/-- `third=0x3FD5555555555555w` -/
theorem third :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 / 3 : Rat) : HolFloat 52 11) = 0x3FD5555555555555 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `tenth=0x3FB999999999999Aw` -/
theorem tenth :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 / 10 : Rat) : HolFloat 52 11) = 0x3FB999999999999A := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `neg_third=0xBFD5555555555555w` -/
theorem negThird :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (-1 / 3 : Rat) : HolFloat 52 11) = 0xBFD5555555555555 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `one=0x3FF0000000000000w` -/
theorem one :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 : Rat) : HolFloat 52 11) = 0x3FF0000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `tie_down_even=0x3FF0000000000000w` -/
theorem tieDownEven :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 + 1 / 2 ^ 53 : Rat) : HolFloat 52 11) = 0x3FF0000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `tie_up_even=0x3FF0000000000002w` -/
theorem tieUpEven :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 + 3 / 2 ^ 53 : Rat) : HolFloat 52 11) = 0x3FF0000000000002 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `near_tie_up=0x3FF0000000000001w` -/
theorem nearTieUp :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 + 1 / 2 ^ 53 + 1 / 2 ^ 80 : Rat) : HolFloat 52 11) = 0x3FF0000000000001 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `sub_half_ulp=0w` -/
theorem subHalfUlp :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 / 2 ^ 1075 : Rat) : HolFloat 52 11) = 0 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `sub_half_ulp_neg=0x8000000000000000w` -/
theorem subHalfUlpNeg :
    holFloatToFp64 (holFloatRound .roundTiesToEven true (-1 / 2 ^ 1075 : Rat) : HolFloat 52 11) = 0x8000000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `sub_three_half=2w` -/
theorem subThreeHalf :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (3 / 2 ^ 1075 : Rat) : HolFloat 52 11) = 2 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `sub_tiny_neg=0w` -/
theorem subTinyNeg :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (-1 / 2 ^ 1100 : Rat) : HolFloat 52 11) = 0 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `zero_toneg=0x8000000000000000w` -/
theorem zeroToneg :
    holFloatToFp64 (holFloatRound .roundTiesToEven true (0 : Rat) : HolFloat 52 11) = 0x8000000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `zero_pos=0w` -/
theorem zeroPos :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (0 : Rat) : HolFloat 52 11) = 0 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `largest_exact=0x7FEFFFFFFFFFFFFFw` -/
theorem largestExact :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (holFloatLargest 52 11 : Rat) : HolFloat 52 11) = 0x7FEFFFFFFFFFFFFF := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `below_threshold=0x7FEFFFFFFFFFFFFFw` -/
theorem belowThreshold :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (holFloatThreshold 52 11 - 1 : Rat) : HolFloat 52 11) = 0x7FEFFFFFFFFFFFFF := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `at_threshold=0x7FF0000000000000w` -/
theorem atThreshold :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (holFloatThreshold 52 11 : Rat) : HolFloat 52 11) = 0x7FF0000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `neg_threshold=0xFFF0000000000000w` -/
theorem negThreshold :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (-holFloatThreshold 52 11 : Rat) : HolFloat 52 11) = 0xFFF0000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `min_normal=0x10000000000000w` -/
theorem minNormal :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 / 2 ^ 1022 : Rat) : HolFloat 52 11) = 0x10000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `max_subnormal_up=0x10000000000000w` -/
theorem maxSubnormalUp :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (1 / 2 ^ 1022 - 1 / 2 ^ 1076 : Rat) : HolFloat 52 11) = 0x10000000000000 := by
  rw [holFloatRound_rte_fp64]; decide +kernel
/-- `big_odd=0x43B0000000000001w` -/
theorem bigOdd :
    holFloatToFp64 (holFloatRound .roundTiesToEven false (2 ^ 60 + 2 ^ 7 + 1 : Rat) : HolFloat 52 11) = 0x43B0000000000001 := by
  rw [holFloatRound_rte_fp64]; decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS binary64 float_round roundTiesToEven matches all 20 HOL oracle rows (kernel-checked via the conformance theorem)"
  pure true

end Flapjack.Test.BinaryIeeeRoundFp64Parity
