import Flapjack.Pancake.Semantics.CrepSem.EvaluateHOL

/-!
Regression rows for the `Primitive` clause and the `Call` exception-handler
branch of HOL `crepSem$evaluate_def` (`crepSemScript.sml:248-259, 335-366`).
These are two arms of the tagged `evalCrepSemHOLProgExact_eq_evaluate_def` that
had no direct oracle row before.

The rows are transcribed from `scripts/hol-probes/crep_evaluate_def_arms_probe.out`
(generated by `crep_evaluate_def_arms_probeScript.sml` through
`scripts/hol-probes/regenerate.sh`). They run the exact recursive core
`evalCrepSemHOLProg`, which equals `evalCrepSemHOLProgExact` for any deciders
(`evalCrepSemHOLProgExact_eq_core`), on the probe's 64-bit state.
-/

namespace Flapjack.Test.CrepSemEvaluateDefArmsParity

open Flapjack
open Flapjack.Basis.Pure.MlString

private def w (n : Nat) : HolWordLab 64 := .word (BitVec.ofNat 64 n)

/-- The probe's `mkState code`: locals `0 ↦ 7`, `1 ↦ 3`, `2 ↦ 1`, clock 5,
    empty memory domains. -/
def mkState (code : HolFiniteMapExact MlString (List Nat × CrepProgHOL 64)) :
    CrepSemHOLState 64 Unit where
  locals := ((HolFiniteMapExact.empty.updateEq (0, w 7)).updateEq (1, w 3)).updateEq (2, w 1)
  globals := HolFiniteMapExact.empty
  code := code
  memory := fun _ => .word 0
  memaddrs := fun _ => False
  shMemaddrs := fun _ => False
  clock := 5
  be := false
  ffi := { oracle := fun _ _ _ _ => .final .failed, ffiState := (), ioEvents := [] }
  baseAddr := 0
  topAddr := BitVec.ofNat 64 100

def emptyCode : HolFiniteMapExact MlString (List Nat × CrepProgHOL 64) :=
  HolFiniteMapExact.empty

/-- The probe's `raiseCode`: `worker` has no parameters and raises `3w`. -/
def raiseCode : HolFiniteMapExact MlString (List Nat × CrepProgHOL 64) :=
  HolFiniteMapExact.empty.updateEq (ofString "worker", ([], .raise (BitVec.ofNat 64 3)))

def emptyState : CrepSemHOLState 64 Unit := mkState emptyCode
def raiseState : CrepSemHOLState 64 Unit := mkState raiseCode

/-- Run the exact core on `mkState code`, whose memory domains are empty. -/
def runIn (code : HolFiniteMapExact MlString (List Nat × CrepProgHOL 64))
    (program : CrepProgHOL 64) :
    Option (CrepResultHOLExact 64) × CrepSemHOLState 64 Unit :=
  evalCrepSemHOLProg (mkState code) (fun _ => isFalse (fun h => h))
    (fun _ => isFalse (fun h => h)) program

def isError : Option (CrepResultHOLExact 64) → Bool
  | some .error => true
  | _ => false

def isException (v : Nat) : Option (CrepResultHOLExact 64) → Bool
  | some (.exception e) => e == BitVec.ofNat 64 v
  | _ => false

/-- The state was returned unchanged (on the observable fields the probe
    compares: every local the probe binds, plus clock). -/
def unchanged (before after : CrepSemHOLState 64 Unit) : Bool :=
  [0, 1, 2, 9].all (fun n => after.locals.lookup n == before.locals.lookup n) &&
    after.clock == before.clock

def localsEmpty (state : CrepSemHOLState 64 Unit) : Bool :=
  [0, 1, 2, 9].all (fun n => state.locals.lookup n == none)

def prim (names args : List Nat) : CrepProgHOL 64 := .primitive names .addCarry args

/-- `primitive_add_carry=T`: `word_add_carry 7 3 1 = (11, 0)` is written to
    locals `0` and `1`. -/
def primitiveAddCarry : Bool :=
  match runIn emptyCode (prim [0, 1] [0, 1, 2]) with
  | (none, st) => st.locals.lookup 0 == some (w 11) && st.locals.lookup 1 == some (w 0) &&
      st.locals.lookup 2 == some (w 1) && st.clock == 5
  | _ => false

/-- `primitive_duplicate_lhs`, `primitive_missing_lhs`, `primitive_wrong_arity`,
    `primitive_missing_rhs` (all `=T`): `SOME Error` with the state unchanged. -/
def primitiveErrors : Bool :=
  [prim [0, 0] [0, 1, 2], prim [0, 9] [0, 1, 2], prim [0, 1] [0, 1],
    prim [0, 1] [0, 1, 9]].all fun program =>
    let (res, st) := runIn emptyCode program
    isError res && unchanged emptyState st

def callWith (handler : Option (BitVec 64 × CrepProgHOL 64)) (rts : List Nat) :
    CrepProgHOL 64 :=
  .call (some (rts, handler)) (ofString "worker") []

/-- `call_handler_catch=T`: the handler runs on the caller's locals. -/
def callHandlerCatch : Bool :=
  match runIn raiseCode
      (callWith (some (BitVec.ofNat 64 3, .assign 1 (.const (BitVec.ofNat 64 5))))
        [1]) with
  | (none, st) => st.locals.lookup 1 == some (w 5) && st.locals.lookup 0 == some (w 7) &&
      st.clock == 4
  | _ => false

/-- `call_handler_mismatch=T` and `call_handler_absent=T`: the exception
    propagates with empty locals. -/
def callHandlerPropagate : Bool :=
  [callWith (some (BitVec.ofNat 64 4, .assign 1 (.const (BitVec.ofNat 64 5)))) [1],
    callWith none [1]].all fun program =>
    let (res, st) := runIn raiseCode program
    isException 3 res && localsEmpty st && st.clock == 4

/-- `call_handler_duplicate_rts=T`: duplicate return destinations fail
    before the clock is spent. -/
def callHandlerDuplicateRts : Bool :=
  let (res, st) := runIn raiseCode (callWith (some (BitVec.ofNat 64 3, .skip)) [1, 1])
  isError res && unchanged raiseState st

def rowsMatch : Bool :=
  primitiveAddCarry && primitiveErrors && callHandlerCatch && callHandlerPropagate &&
    callHandlerDuplicateRts

def runChecks : IO Bool := do
  if rowsMatch then
    IO.println "PASS crepSem evaluate_def Primitive and Call-handler arms match direct crep_evaluate_def_arms_probe oracle"
  else
    IO.println "FAIL crepSem evaluate_def Primitive and Call-handler arms match direct crep_evaluate_def_arms_probe oracle"
  pure rowsMatch

end Flapjack.Test.CrepSemEvaluateDefArmsParity
