import Flapjack.Pancake.CrepToLoop.ContextExact
import Flapjack.Pancake.CrepToLoop.Optimise

/-!
# Direct HOL oracle parity for exact `crep_to_loop$comp_func_def`

Transcribes the direct HOL-EVAL rows in
`scripts/hol-probes/crep_to_loop_comp_func_probe.out`, generated by
`crep_to_loop_comp_func_probeScript.sml`:

* `comp_func_skip=Skip`
* `comp_func_return_var=Seq (Assign 1 (Var 0)) (Seq (Return [1]) Skip)`
* `comp_func_two_params=Seq (Assign 2 (Var 1)) (Seq (Return [2]) Skip)`

The Lean observations apply the exact port `compFuncHOLExact` (tagged
`comp_func_def`) over the exact `CrepProgHOL`/`HolLoopProg` carriers with an
empty `fs` finite map and the same `params` lists.
-/

namespace Flapjack.Test.CrepToLoopCompFuncParity

open Flapjack
open Flapjack.Pancake
open Flapjack.Compiler.Encoders.Asm

private abbrev fs : HolFiniteMapExact MlString (Nat × Nat) := HolFiniteMapExact.empty

/-- A byte-ranged source `skip` reaches the checked exact ocompile route and
projects to the same executable skip result as the direct HOL `comp_func`
row followed by `ocompile_def`. -/
example : loopProgExecRel
    (crepCompFuncThroughHOLExact (width := 8) .rv32i [] []
    (CrepProg.skip : CrepProg (BitVec 8))
    (by simp [CrepProgNameRanged])
    (by intro entry h; simp at h))
    (ocompileHOLExact (productionLoopContextToExact
      (crepMkCtxt (α := BitVec 8) .rv32i [] [] 0))
      (listToNumSetHOLExact []) (CrepProgHOL.skip : CrepProgHOL 8)) := by
  simpa [crepMakeVmap, crepProgToHOL] using
    (crepCompFuncThroughHOLExact_rel (width := 8) .rv32i [] []
    (CrepProg.skip : CrepProg (BitVec 8))
    (by simp [CrepProgNameRanged]) (by simp))

/-- `comp_func_skip` HOL row. -/
theorem compFunc_skip :
    compFuncHOLExact (width := 8) .riscv fs []
      (CrepProgHOL.skip : CrepProgHOL 8) = (HolLoopProg.skip : HolLoopProg 8) := by
  simp [compFuncHOLExact, compileHOLExact, makeVmapExact, mkCtxtExact,
    HolFiniteMapExact.empty]

/-- `comp_func_return_var` HOL row. -/
theorem compFunc_return_var :
    compFuncHOLExact (width := 8) .riscv fs [0]
      (CrepProgHOL.return [CrepExpHOL.var 0] : CrepProgHOL 8) =
        (HolLoopProg.seq (HolLoopProg.assign 1 (HolLoopExp.var 0))
          (HolLoopProg.seq (HolLoopProg.return [1]) HolLoopProg.skip) : HolLoopProg 8) := by
  simp [compFuncHOLExact, compileHOLExact, compileExpsHOLExact, compileExpHOLExact,
    makeVmapExact, mkCtxtExact, HolFiniteMapExact.empty, genTemps, loopNestedSeqHOL,
    List.range, List.range.loop, List.zipWith, List.map, FUPDATE_LIST_HOL, FUPDATE_HOL, genTemps]

/-- `comp_func_two_params` HOL row. -/
theorem compFunc_two_params :
    compFuncHOLExact (width := 8) .riscv fs [0, 1]
      (CrepProgHOL.return [CrepExpHOL.var 1] : CrepProgHOL 8) =
        (HolLoopProg.seq (HolLoopProg.assign 2 (HolLoopExp.var 1))
          (HolLoopProg.seq (HolLoopProg.return [2]) HolLoopProg.skip) : HolLoopProg 8) := by
  simp [compFuncHOLExact, compileHOLExact, compileExpsHOLExact, compileExpHOLExact,
    makeVmapExact, mkCtxtExact, HolFiniteMapExact.empty, genTemps, loopNestedSeqHOL,
    List.range, List.range.loop, List.zipWith, List.map, FUPDATE_LIST_HOL, FUPDATE_HOL, genTemps]

/-- `ltns_nil_0` HOL row: `list_to_num_set []` has no member `0`. -/
theorem listToNumSetHOLExact_nil_miss :
    sptLookup 0 (listToNumSetHOLExact ([] : List Nat)) = none := by decide +kernel

/-- `ltns_single_0` HOL row: `list_to_num_set [0]` contains `0`. -/
theorem listToNumSetHOLExact_single_hit :
    sptLookup 0 (listToNumSetHOLExact [0]) = some () := by decide +kernel

/-- `ltns_three_*` HOL rows: `list_to_num_set [0;1;2]` contains `0` and `2`,
    not `3`. -/
theorem listToNumSetHOLExact_three_hits :
    sptLookup 0 (listToNumSetHOLExact [0, 1, 2]) = some () ∧
      sptLookup 2 (listToNumSetHOLExact [0, 1, 2]) = some () ∧
      sptLookup 3 (listToNumSetHOLExact [0, 1, 2]) = none := by decide +kernel

/-- `ltns_unsorted_*` HOL rows: the unsorted `list_to_num_set [2;0;3]` contains
    `2`, `0` and `3`, not `4`. -/
theorem listToNumSetHOLExact_unsorted_hits :
    sptLookup 2 (listToNumSetHOLExact [2, 0, 3]) = some () ∧
      sptLookup 0 (listToNumSetHOLExact [2, 0, 3]) = some () ∧
      sptLookup 3 (listToNumSetHOLExact [2, 0, 3]) = some () ∧
      sptLookup 4 (listToNumSetHOLExact [2, 0, 3]) = none := by decide +kernel

/-- `ltns_cons_shape` HOL row: the right-recursive equation
    `list_to_num_set (n::ns) = insert n () (list_to_num_set ns)`. -/
theorem listToNumSetHOLExact_cons_shape :
    listToNumSetHOLExact (2 :: [0, 3]) =
      sptInsert 2 () (listToNumSetHOLExact [0, 3]) := rfl

def runChecks : IO Bool := do
  let ok := true
  IO.println "PASS crep_to_loop comp_func_def exact port matches direct HOL rows (skip / one param / two params)"
  IO.println "PASS listToNumSetHOLExact matches the direct HOL sptree$list_to_num_set_def rows (nil / single / [0;1;2] / [2;0;3] / cons-shape)"
  return ok

end Flapjack.Test.CrepToLoopCompFuncParity
