import Flapjack.Pancake.CrepToLoop.ContextExact

/-!
# Direct HOL oracle parity for exact `crep_to_loop$comp_func_def`

Transcribes the direct HOL-EVAL rows in
`scripts/hol-probes/crep_to_loop_comp_func_probe.out`, generated by
`crep_to_loop_comp_func_probeScript.sml`:

* `comp_func_skip=Skip`
* `comp_func_return_var=Seq (Assign 1 (Var 0)) (Seq (Return [1]) Skip)`
* `comp_func_two_params=Seq (Assign 2 (Var 1)) (Seq (Return [2]) Skip)`

The Lean observations apply the exact port `compFuncHOLExact` (tagged
`comp_func_def`) over the exact `CrepProgHOL`/`HolLoopProg` carriers with an
empty `fs` finite map and the same `params` lists.
-/

namespace Flapjack.Test.CrepToLoopCompFuncParity

open Flapjack
open Flapjack.Pancake
open Flapjack.Compiler.Encoders.Asm

private abbrev fs : HolFiniteMapExact MlString (Nat × Nat) := HolFiniteMapExact.empty

/-- `comp_func_skip` HOL row. -/
theorem compFunc_skip :
    compFuncHOLExact (width := 8) .riscv fs []
      (CrepProgHOL.skip : CrepProgHOL 8) = (HolLoopProg.skip : HolLoopProg 8) := by
  simp [compFuncHOLExact, compileHOLExact, makeVmapExact, mkCtxtExact,
    HolFiniteMapExact.empty]

/-- `comp_func_return_var` HOL row. -/
theorem compFunc_return_var :
    compFuncHOLExact (width := 8) .riscv fs [0]
      (CrepProgHOL.return [CrepExpHOL.var 0] : CrepProgHOL 8) =
        (HolLoopProg.seq (HolLoopProg.assign 1 (HolLoopExp.var 0))
          (HolLoopProg.seq (HolLoopProg.return [1]) HolLoopProg.skip) : HolLoopProg 8) := by
  simp [compFuncHOLExact, compileHOLExact, compileExpsHOLExact, compileExpHOLExact,
    makeVmapExact, mkCtxtExact, HolFiniteMapExact.empty, genTemps, loopNestedSeqHOL,
    List.range, List.range.loop, List.zipWith, List.map, FUPDATE_LIST_HOL, FUPDATE_HOL,
    sptListInsert, genTemps]

/-- `comp_func_two_params` HOL row. -/
theorem compFunc_two_params :
    compFuncHOLExact (width := 8) .riscv fs [0, 1]
      (CrepProgHOL.return [CrepExpHOL.var 1] : CrepProgHOL 8) =
        (HolLoopProg.seq (HolLoopProg.assign 2 (HolLoopExp.var 1))
          (HolLoopProg.seq (HolLoopProg.return [2]) HolLoopProg.skip) : HolLoopProg 8) := by
  simp [compFuncHOLExact, compileHOLExact, compileExpsHOLExact, compileExpHOLExact,
    makeVmapExact, mkCtxtExact, HolFiniteMapExact.empty, genTemps, loopNestedSeqHOL,
    List.range, List.range.loop, List.zipWith, List.map, FUPDATE_LIST_HOL, FUPDATE_HOL,
    sptListInsert, genTemps]

def runChecks : IO Bool := do
  let ok := true
  IO.println "PASS crep_to_loop comp_func_def exact port matches direct HOL rows (skip / one param / two params)"
  return ok

end Flapjack.Test.CrepToLoopCompFuncParity