import Flapjack.Compiler.Backend.DataToWord.MaxHeapLimit
namespace Flapjack.Test.DataMaxHeapLimit
open Flapjack.Compiler.Backend.DataToWord
example : maxHeapLimit 1 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 1 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 7 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 8 := by decide
example : maxHeapLimit 7 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 7 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 8 := by decide
example : maxHeapLimit 7 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 8 := by decide
example : maxHeapLimit 7 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 8 := by decide
example : maxHeapLimit 7 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 0 := by decide
example : maxHeapLimit 7 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 7 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 8 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 16 := by decide
example : maxHeapLimit 8 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 8 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 16 := by decide
example : maxHeapLimit 8 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 16 := by decide
example : maxHeapLimit 8 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 16 := by decide
example : maxHeapLimit 8 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 0 := by decide
example : maxHeapLimit 8 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 8 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 31 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 134217728 := by decide
example : maxHeapLimit 31 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 524288 := by decide
example : maxHeapLimit 31 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 134217728 := by decide
example : maxHeapLimit 31 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 134217728 := by decide
example : maxHeapLimit 31 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 134217728 := by decide
example : maxHeapLimit 31 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 16384 := by decide
example : maxHeapLimit 31 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 31 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 32 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 536870912 := by decide
example : maxHeapLimit 32 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 1048576 := by decide
example : maxHeapLimit 32 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 536870912 := by decide
example : maxHeapLimit 32 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 536870912 := by decide
example : maxHeapLimit 32 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 536870912 := by decide
example : maxHeapLimit 32 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 32768 := by decide
example : maxHeapLimit 32 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 32 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 33 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 536870912 := by decide
example : maxHeapLimit 33 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 2097152 := by decide
example : maxHeapLimit 33 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 536870912 := by decide
example : maxHeapLimit 33 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 536870912 := by decide
example : maxHeapLimit 33 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 536870912 := by decide
example : maxHeapLimit 33 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 65536 := by decide
example : maxHeapLimit 33 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 33 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 64 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 1152921504606846976 := by decide
example : maxHeapLimit 64 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 4503599627370496 := by decide
example : maxHeapLimit 64 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 1152921504606846976 := by decide
example : maxHeapLimit 64 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 1152921504606846976 := by decide
example : maxHeapLimit 64 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 1152921504606846976 := by decide
example : maxHeapLimit 64 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 140737488355328 := by decide
example : maxHeapLimit 64 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 64 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
example : maxHeapLimit 80 {tagBits := 0, lenBits := 0, padBits := 0, lenSize := 0, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 75557863725914323419136 := by decide
example : maxHeapLimit 80 {tagBits := 4, lenBits := 4, padBits := 2, lenSize := 32, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 295147905179352825856 := by decide
example : maxHeapLimit 80 {tagBits := 1, lenBits := 0, padBits := 0, lenSize := 2, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .generational [1,2]} = 75557863725914323419136 := by decide
example : maxHeapLimit 80 {tagBits := 0, lenBits := 1, padBits := 0, lenSize := 3, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .none} = 75557863725914323419136 := by decide
example : maxHeapLimit 80 {tagBits := 0, lenBits := 0, padBits := 1, lenSize := 4, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .simple} = 75557863725914323419136 := by decide
example : maxHeapLimit 80 {tagBits := 3, lenBits := 5, padBits := 7, lenSize := 5, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .generational [1,2]} = 9223372036854775808 := by decide
example : maxHeapLimit 80 {tagBits := 80, lenBits := 1, padBits := 2, lenSize := 6, hasDiv := false, hasLongdiv := false, hasFpOps := false, hasFpTern := false, be := false, callEmptyFfi := false, gcKind := .none} = 0 := by decide
example : maxHeapLimit 80 {tagBits := 0, lenBits := 64, padBits := 32, lenSize := 7, hasDiv := true, hasLongdiv := true, hasFpOps := true, hasFpTern := true, be := true, callEmptyFfi := true, gcKind := .simple} = 0 := by decide
end Flapjack.Test.DataMaxHeapLimit
