import Flapjack.Compiler.Backend.WordAlloc.HeuProg

namespace Flapjack.Test.HeuProgParity
open Flapjack Flapjack.WordAlloc
/-! Exact counter/call-tree kernel replay of fresh original program heuristic
observations. All clauses, same-input branches and source call-discard behavior
are covered. Finite observations do not establish cross-prover equivalence
or completion of the production allocator route. -/
-- hp_move=T
example : getHeu 5 (.move 91 [(1,2),(1,1)] : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 2 (0,0,0,1,0) (sptInsert 1 (0,2,0,1,0) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_inst=T
example : getHeu 5 (.inst (.const 3 7) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 3 (1,0,0,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_get=T
example : getHeu 5 (.get 1 .nextFree : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_set_var=T
example : getHeu 5 (.set .nextFree (.var 2) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 2 (0,0,0,0,1) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_set_other=T
example : getHeu 5 (.set .nextFree (.op .add [.var 2,.var 3]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    (.ln,(sptInsert 9 () .ln)) := by decide +kernel
-- hp_heap=T
example : getHeu 5 (.opCurrHeap .add 1 2 : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 2 (0,0,0,1,0) (sptInsert 1 (0,1,0,0,0) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_heap_alias=T
example : getHeu 5 (.opCurrHeap .add 1 1 : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,1,0,1,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_loc=T
example : getHeu 5 (.locValue 3 99 : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 3 (0,1,0,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_seq=T
example : getHeu 5 (.seq (.get 1 .nextFree) (.get 1 .nextFree) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,2,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_must=T
example : getHeu 5 (.mustTerminate (.get 1 .nextFree) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_loop=T
example : getHeu 5 (.loop (.ls ()) (.get 1 .nextFree) (sptInsert 99 () .ln) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_if_reg=T
example : getHeu 5 (.ite .equal 3 (.reg 2) (.seq (.get 1 .nextFree) (.get 1 .nextFree)) (.get 1 .nextFree) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 3 (0,0,0,1,0) (sptInsert 2 (0,0,0,1,0) (sptInsert 1 (0,0,2,0,0) .ln))),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_if_alias=T
example : getHeu 5 (.ite .equal 3 (.reg 3) (.seq (.get 1 .nextFree) (.get 1 .nextFree)) (.get 1 .nextFree) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 3 (0,0,0,2,0) (sptInsert 1 (0,0,2,0,0) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_if_imm=T
example : getHeu 5 (.ite .equal 3 (.imm 7) (.seq (.get 1 .nextFree) (.get 1 .nextFree)) (.get 1 .nextFree) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 3 (0,0,0,1,0) (sptInsert 1 (0,0,2,0,0) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_tail_indirect=T
example : getHeu 5 (.call none (none) [99] (some (1,.get 8 .nextFree,2,3)) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_tail_other=T
example : getHeu 5 (.call none (some 6) [99] (some (1,.get 8 .nextFree,2,3)) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_tail_self=T
example : getHeu 5 (.call none (some 5) [99] (some (1,.get 8 .nextFree,2,3)) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () (sptInsert 7 () .ln))) := by decide +kernel
-- hp_ret_indirect=T
example : getHeu 5 (.call (some ([99],(.ln,.ln),.get 8 .nextFree,1,2)) (none) [99] none : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ret_other=T
example : getHeu 5 (.call (some ([99],(.ln,.ln),.get 8 .nextFree,1,2)) (some 6) [99] none : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ret_self=T
example : getHeu 5 (.call (some ([99],(.ln,.ln),.get 8 .nextFree,1,2)) (some 5) [99] none : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln)),(sptInsert 9 () (sptInsert 7 () .ln))) := by decide +kernel
-- hp_ret_discard=T
example : getHeu 5 (.call (some ([],(.ln,.ln),.seq (.get 8 .nextFree) (.call none (some 5) [] none),1,2)) none [] none : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln)),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ret_self_discard=T
example : getHeu 5 (.call (some ([],(.ln,.ln),.seq (.get 8 .nextFree) (.call none (some 5) [] none),1,2)) (some 5) [] none : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln)),(sptInsert 9 () (sptInsert 7 () .ln))) := by decide +kernel
-- hp_ret_handler=T
example : getHeu 5 (.call (some ([],(.ln,.ln),.seq (.get 8 .nextFree) (.call none (some 5) [] none),1,2)) none [] (some (99,.seq (.get 10 .nextFree) (.call none (some 5) [] none),3,4)) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 10 (0,0,1,0,0) (sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln))),(sptInsert 10 () (sptInsert 9 () (sptInsert 8 () (sptInsert 7 () .ln))))) := by decide +kernel
-- hp_if_calls=T
example : getHeu 5 (.ite .equal 1 (.imm 0) (.seq (.get 8 .nextFree) (.call none (some 5) [] none)) (.seq (.get 10 .nextFree) (.call none (some 5) [] none)) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 10 (0,0,1,0,0) (sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) (sptInsert 1 (0,0,0,1,0) .ln)))),(sptInsert 10 () (sptInsert 9 () (sptInsert 8 () (sptInsert 7 () .ln))))) := by decide +kernel
-- hp_seq_calls=T
example : getHeu 5 (.seq (.get 8 .nextFree) (.call none (some 5) [] none) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 8 (0,0,1,0,0) (sptInsert 7 (2,3,5,7,11) .ln)),(sptInsert 9 () (sptInsert 8 () (sptInsert 7 () .ln)))) := by decide +kernel
-- hp_share_load=T
example : getHeu 5 (.shareInst .load 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_load8=T
example : getHeu 5 (.shareInst .load8 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_load16=T
example : getHeu 5 (.shareInst .load16 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_load32=T
example : getHeu 5 (.shareInst .load32 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_store=T
example : getHeu 5 (.shareInst .store 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,0,0,1) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_store8=T
example : getHeu 5 (.shareInst .store8 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,0,0,1) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_store16=T
example : getHeu 5 (.shareInst .store16 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,0,0,1) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_share_store32=T
example : getHeu 5 (.shareInst .store32 1 (.op .add [.var 99,.const 7]) : WordLangProgHOL (BitVec 64)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (0,0,0,0,1) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_skip=T
example : getHeu 5 (.skip : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_assign=T
example : getHeu 5 (.assign 1 (.var 2) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_store=T
example : getHeu 5 (.store (.var 2) 1 : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_alloc=T
example : getHeu 5 (.alloc 1 (.ls (),.ln) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_consts=T
example : getHeu 5 (.storeConsts 1 2 3 4 [(true,7)] : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_raise=T
example : getHeu 5 (.raise 1 : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_return=T
example : getHeu 5 (.return 1 [2,3] : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_break=T
example : getHeu 5 (.break 1 : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_continue=T
example : getHeu 5 (.continue 1 : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_tick=T
example : getHeu 5 (.tick : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_install=T
example : getHeu 5 (.install 1 2 3 4 (.ls (),.ln) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_code=T
example : getHeu 5 (.codeBufferWrite 1 2 : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_data=T
example : getHeu 5 (.dataBufferWrite 1 2 : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_ignore_ffi=T
example : getHeu 5 (.ffi (.implode [65]) 1 2 3 4 (.ls (),.ln) : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,5,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_width1=T
example : getHeu 5 (.inst (.const 1 1) : WordLangProgHOL (BitVec 1)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 1 (1,0,0,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_width128=T
example : getHeu 5 (.get 18446744073709551616 .nextFree : WordLangProgHOL (BitVec 128)) (.ln,(sptInsert 9 () .ln)) =
    ((sptInsert 18446744073709551616 (0,0,1,0,0) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_large_counter=T
example : getHeu 5 (.get 7 .nextFree : WordLangProgHOL (BitVec 64)) ((sptInsert 7 (2,3,18446744073709551616,7,11) .ln),(sptInsert 9 () .ln)) =
    ((sptInsert 7 (2,3,18446744073709551617,7,11) .ln),(sptInsert 9 () .ln)) := by decide +kernel
-- hp_raw_skip=T
example : getHeu 5 (.skip : WordLangProgHOL (BitVec 64))
    (.bs .ln (2,3,5,7,11) .ln, .bn .ln .ln) =
    (.bs .ln (2,3,5,7,11) .ln, .bn .ln .ln) := by decide +kernel
-- hp_raw_self=T
example : getHeu 5 (.call none (some 5) [] none : WordLangProgHOL (BitVec 64))
    (.bs .ln (2,3,5,7,11) .ln, .bn .ln .ln) =
    (.bs .ln (2,3,5,7,11) .ln, .bs .ln () .ln) := by decide +kernel

end Flapjack.Test.HeuProgParity
