import Flapjack.Pancake.LoopToWord.CompCases.Recursive

/-!
# Original HOL parity for recursive `loop_to_word$comp` clauses

The direct source oracle is
`scripts/hol-probes/loop_to_word_comp_recursive_probe.out`, generated by the
adjacent HOL script. These examples replay the Seq, If, Loop, and Mark rows over
the exact `HolLoopProg` and `WordLangProgHOL` carriers. -/

namespace Flapjack.Test.LoopToWordRecursiveParity

open Flapjack Flapjack.LoopToWord

def probeLabels : Nat × Nat := (7, 11)

def probeContext : Spt Nat :=
  sptInsert 14 28 (sptInsert 13 26 (sptInsert 12 24
    (sptInsert 11 22 (sptInsert 10 20 .ln))))

def probeLiveIn : Spt Unit := sptInsert 10 () .ln
def probeLiveOut : Spt Unit := sptInsert 11 () .ln

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.seq (.assign 10 (.var 11)) (.assign 12 (.const (5 : BitVec 8)))) =
      some (.seq (.assign 20 (.var 22)) (.assign 24 (.const (5 : BitVec 8))),
        probeLabels) := by
  simp [compRecursiveCasesHOL, compInitialHOL, compExpHOL, findVarHOL,
    probeContext, probeLabels, sptLookup_sptInsert_same,
    sptLookup_sptInsert_ne]

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.ite .equal 10 (.reg 11)
      (.assign 12 (.const (5 : BitVec 8)))
      (.assign 13 (.var 14)) (sptInsert 12 () .ln)) =
      some (.seq (.ite .equal 20 (.reg 22)
        (.assign 24 (.const (5 : BitVec 8))) (.assign 26 (.var 28))) .tick,
        probeLabels) := by
  simp [compRecursiveCasesHOL, compInitialHOL, compExpHOL, findVarHOL,
    probeContext, probeLabels, sptLookup_sptInsert_same,
    sptLookup_sptInsert_ne]

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.loop probeLiveIn (.assign 12 (.var 13)) probeLiveOut) =
      some (.seq .tick (.seq (.loop
        (mkNewCutsetHOL probeContext probeLiveIn)
        (.assign 24 (.var 26))
        (mkNewCutsetHOL probeContext probeLiveOut)) .tick), probeLabels) := by
  simp [compRecursiveCasesHOL, compInitialHOL, compExpHOL, findVarHOL,
    probeContext, probeLabels, probeLiveIn, probeLiveOut,
    sptLookup_sptInsert_same, sptLookup_sptInsert_ne]

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.mark (.assign 10 (.var 14))) =
      some (.assign 20 (.var 28), probeLabels) := by
  simp [compRecursiveCasesHOL, compInitialHOL, compExpHOL, findVarHOL,
    probeContext, probeLabels, sptLookup_sptInsert_same,
    sptLookup_sptInsert_ne]

/-- Recursive cases preserve the threaded pair in the observed HOL rows. -/
def recursiveProbeChecks : List Bool :=
  [ (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.seq (.assign 10 (.var 11)) (.assign 12 (.const (5 : BitVec 8)))) with
      | some (.seq (.assign 20 (.var 22)) (.assign 24 (.const value)), (7, 11)) =>
          value == (5 : BitVec 8)
      | _ => false),
    (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.ite .equal 10 (.reg 11) (.assign 12 (.const (5 : BitVec 8)))
          (.assign 13 (.var 14)) (sptInsert 12 () .ln)) with
      | some (.seq (.ite .equal 20 (.reg 22)
          (.assign 24 (.const value)) (.assign 26 (.var 28))) .tick, (7, 11)) =>
          value == (5 : BitVec 8)
      | _ => false),
    (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.loop probeLiveIn (.assign 12 (.var 13)) probeLiveOut) with
      | some (.seq .tick (.seq (.loop liveIn (.assign 24 (.var 26)) liveOut) .tick),
          (7, 11)) =>
          sptLookup 0 liveIn = some () && sptLookup 20 liveIn = some () &&
            sptLookup 0 liveOut = some () && sptLookup 22 liveOut = some ()
      | _ => false),
    (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.mark (.assign 10 (.var 14))) with
      | some (.assign 20 (.var 28), (7, 11)) => true
      | _ => false) ]

def runChecks : IO Bool := do
  let passed := recursiveProbeChecks.all id
  if passed then
    IO.println "PASS LoopToWord recursive comp_def HOL EVAL rows"
  else
    IO.println "FAIL LoopToWord recursive comp_def HOL EVAL rows"
  pure passed

end Flapjack.Test.LoopToWordRecursiveParity
