import Flapjack.Pancake.LoopToWord.CompCases.Recursive

/-!
# Original HOL parity for the `Call` clauses of `loop_to_word$comp`

The direct source oracle is
`scripts/hol-probes/loop_to_word_comp_call_probe.out`, generated by the adjacent
HOL script. These examples replay the tail-call, non-tail without handler, and
non-tail with handler rows over the exact `HolLoopProg` and `WordLangProgHOL`
carriers, checking link slot `0`, the computed live cutset, label threading, and
the trailing `Tick`.
-/

namespace Flapjack.Test.LoopToWordCallParity

open Flapjack Flapjack.LoopToWord

def probeLabels : Nat × Nat := (7, 11)

def probeContext : Spt Nat :=
  sptInsert 14 28 (sptInsert 13 26 (sptInsert 12 24
    (sptInsert 11 22 (sptInsert 10 20 .ln))))

def probeLive : Spt Unit := sptInsert 12 () .ln

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.call none (some 5) [10, 11] none) =
      some (.call none (some 5) [0, 20, 22] none, probeLabels) := by
  simp [compRecursiveCasesHOL, findVarHOL, probeContext, probeLabels,
    sptLookup_sptInsert_same, sptLookup_sptInsert_ne]

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.call (some ([12, 13], probeLive)) (some 5) [10, 11] none) =
      some (.call
        (some ([24, 26], (mkNewCutsetHOL probeContext probeLive, .ln), .skip,
          probeLabels))
        (some 5) [20, 22] none, (7, 12)) := by
  simp [compRecursiveCasesHOL, findVarHOL, probeContext, probeLabels, probeLive,
    sptLookup_sptInsert_same, sptLookup_sptInsert_ne]

example : compRecursiveCasesHOL (width := 8) probeContext probeLabels
    (.call (some ([12, 13], probeLive)) (some 5) [10, 11]
      (some (14, .assign 10 (.var 11), .assign 12 (.const (5 : BitVec 8)),
        sptInsert 13 () .ln))) =
      some (.seq
        (.call
          (some ([24, 26], (mkNewCutsetHOL probeContext probeLive, .ln),
            .assign 24 (.const (5 : BitVec 8)), probeLabels))
          (some 5) [20, 22] (some (28, .assign 20 (.var 22), (7, 12))))
        .tick, (7, 13)) := by
  simp [compRecursiveCasesHOL, compInitialHOL, compExpHOL, findVarHOL,
    probeContext, probeLabels, probeLive, sptLookup_sptInsert_same,
    sptLookup_sptInsert_ne]

/-- Call rows preserve link slot 0, the live cutset, and the threaded pair. -/
def callProbeChecks : List Bool :=
  [ (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.call none (some 5) [10, 11] none) with
      | some (.call none (some 5) [0, 20, 22] none, (7, 11)) => true
      | _ => false),
    (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.call (some ([12, 13], probeLive)) (some 5) [10, 11] none) with
      | some (.call (some ([24, 26], (cutset, .ln), .skip, (7, 11))) (some 5)
          [20, 22] none, (7, 12)) =>
          (sptLookup 0 cutset : Option Unit) == some () &&
            (sptLookup 24 cutset : Option Unit) == some ()
      | _ => false),
    (match compRecursiveCasesHOL (width := 8) probeContext probeLabels
        (.call (some ([12, 13], probeLive)) (some 5) [10, 11]
          (some (14, .assign 10 (.var 11), .assign 12 (.const (5 : BitVec 8)),
            sptInsert 13 () .ln))) with
      | some (.seq
          (.call (some ([24, 26], _cutset, .assign 24 (.const value), (7, 11)))
            (some 5) [20, 22] (some (28, .assign 20 (.var 22), (7, 12))))
          .tick, (7, 13)) =>
          value == (5 : BitVec 8)
      | _ => false) ]

def runChecks : IO Bool := do
  let passed := callProbeChecks.all id
  if passed then
    IO.println "PASS LoopToWord Call comp_def HOL EVAL rows"
  else
    IO.println "FAIL LoopToWord Call comp_def HOL EVAL rows"
  pure passed

end Flapjack.Test.LoopToWordCallParity
