import Flapjack.Misc.MachineIeee.ConvertInt

/-!
Direct HOL oracle rows for binary64 `fp64_to_int` and `int_to_fp64`
(`scripts/hol-probes/machine_ieee_fp64_convert_probe.out`, generated by
`machine_ieee_fp64_convert_probeScript.sml`).  Every row is a kernel-checked
theorem.  `int_to_fp64` rows go through `holIntToFp64_rte` and the
computable rounding.
-/

namespace Flapjack.Test.MachineIeeeConvertParity

open Flapjack

/-- `to_int_2_5=SOME 2` -/
theorem toInt25 : holFp64ToInt .roundTiesToEven 0x4004000000000000 = some (2) := by decide +kernel
/-- `to_int_3_5=SOME 4` -/
theorem toInt35 : holFp64ToInt .roundTiesToEven 0x400C000000000000 = some (4) := by decide +kernel
/-- `to_int_neg_2_5=SOME (-2)` -/
theorem toIntNeg25 : holFp64ToInt .roundTiesToEven 0xC004000000000000 = some (-2) := by decide +kernel
/-- `to_int_tenth=SOME 0` -/
theorem toIntTenth : holFp64ToInt .roundTiesToEven 0x3FB999999999999A = some (0) := by decide +kernel
/-- `to_int_neg_0_7=SOME (-1)` -/
theorem toIntNeg07 : holFp64ToInt .roundTiesToEven 0xBFE6666666666666 = some (-1) := by decide +kernel
/-- `to_int_1e20=SOME 100000000000000000000` -/
theorem toInt1e20 : holFp64ToInt .roundTiesToEven 0x4415AF1D78B58C40 = some (100000000000000000000) := by decide +kernel
/-- `to_int_nz=SOME 0` -/
theorem toIntNz : holFp64ToInt .roundTiesToEven 0x8000000000000000 = some (0) := by decide +kernel
/-- `to_int_nan=NONE` -/
theorem toIntNan : holFp64ToInt .roundTiesToEven 0x7FF8000000000000 = none := by decide +kernel
/-- `to_int_inf=NONE` -/
theorem toIntInf : holFp64ToInt .roundTiesToEven 0x7FF0000000000000 = none := by decide +kernel
/-- `to_int_rtz_neg_2_5=SOME (-2)` -/
theorem toIntRtzNeg25 : holFp64ToInt .roundTowardZero 0xC004000000000000 = some (-2) := by decide +kernel
/-- `to_int_rtp_2_1=SOME 3` -/
theorem toIntRtp21 : holFp64ToInt .roundTowardPositive 0x4000CCCCCCCCCCCD = some (3) := by decide +kernel
/-- `to_int_rtn_neg_2_1=SOME (-3)` -/
theorem toIntRtnNeg21 : holFp64ToInt .roundTowardNegative 0xC000CCCCCCCCCCCD = some (-3) := by decide +kernel
/-- `from_int_0=0w` -/
theorem fromInt0 : holIntToFp64 .roundTiesToEven (0) = 0 := by
  rw [holIntToFp64_rte]; decide +kernel
/-- `from_int_neg1=0xBFF0000000000000w` -/
theorem fromIntNeg1 : holIntToFp64 .roundTiesToEven (-1) = 0xBFF0000000000000 := by
  rw [holIntToFp64_rte]; decide +kernel
/-- `from_int_2p53_1=0x4340000000000000w` -/
theorem fromInt2p531 : holIntToFp64 .roundTiesToEven (9007199254740993) = 0x4340000000000000 := by
  rw [holIntToFp64_rte]; decide +kernel
/-- `from_int_2p53_3=0x4340000000000002w` -/
theorem fromInt2p533 : holIntToFp64 .roundTiesToEven (9007199254740995) = 0x4340000000000002 := by
  rw [holIntToFp64_rte]; decide +kernel
/-- `from_int_big=0x7FF0000000000000w` -/
theorem fromIntBig : holIntToFp64 .roundTiesToEven (2 ^ 1024) = 0x7FF0000000000000 := by
  rw [holIntToFp64_rte]; decide +kernel
/-- `from_int_neg_big=0xC3B0000000000000w` -/
theorem fromIntNegBig : holIntToFp64 .roundTiesToEven (-(2 ^ 60 + 1)) = 0xC3B0000000000000 := by
  rw [holIntToFp64_rte]; decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS binary64 fp64_to_int/int_to_fp64 match all 18 HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.MachineIeeeConvertParity
