import Flapjack.Misc.BinaryIeeeArithFp64

/-!
Direct HOL oracle rows for rounded finite results of binary64
`fp64_add`/`fp64_sub`/`fp64_mul`/`fp64_div` and the tagged `fpSem` `fpfma`
(`scripts/hol-probes/machine_ieee_fp64_arith_round_probe.out`, generated by
`machine_ieee_fp64_arith_round_probeScript.sml`).  Each row is a
kernel-checked theorem about the HOL renderings.  It is proved by rewriting
with the computable-rounding equivalences of `Flapjack.Misc.BinaryIeeeArithFp64`
and evaluating in the kernel.
-/

namespace Flapjack.Test.MachineIeeeArithRoundParity

open Flapjack

private def tenth : BitVec 64 := 0x3FB999999999999A
private def fifth : BitVec 64 := 0x3FC999999999999A
private def half : BitVec 64 := 0x3FE0000000000000
private def one : BitVec 64 := 0x3FF0000000000000
private def two : BitVec 64 := 0x4000000000000000
private def three : BitVec 64 := 0x4008000000000000
private def ten : BitVec 64 := 0x4024000000000000
private def negone : BitVec 64 := 0xBFF0000000000000
private def pz : BitVec 64 := 0x0
private def nz : BitVec 64 := 0x8000000000000000
private def sub1 : BitVec 64 := 0x1
private def maxfin : BitVec 64 := 0x7FEFFFFFFFFFFFFF
private def eps : BitVec 64 := 0x3CA0000000000000

/-- `add_tenth_fifth=0x3FD3333333333334w` -/
theorem addTenthFifth : holFp64Add .roundTiesToEven tenth fifth = 0x3FD3333333333334 := by
  rw [holFp64Add_rte]; decide +kernel
/-- `add_one_halfulp=0x3FF0000000000000w` -/
theorem addOneHalfulp : holFp64Add .roundTiesToEven one eps = 0x3FF0000000000000 := by
  rw [holFp64Add_rte]; decide +kernel
/-- `add_pz_nz=0w` -/
theorem addPzNz : holFp64Add .roundTiesToEven pz nz = 0 := by
  rw [holFp64Add_rte]; decide +kernel
/-- `add_nz_nz=0x8000000000000000w` -/
theorem addNzNz : holFp64Add .roundTiesToEven nz nz = 0x8000000000000000 := by
  rw [holFp64Add_rte]; decide +kernel
/-- `add_max_max=0x7FF0000000000000w` -/
theorem addMaxMax : holFp64Add .roundTiesToEven maxfin maxfin = 0x7FF0000000000000 := by
  rw [holFp64Add_rte]; decide +kernel
/-- `sub_one_one=0w` -/
theorem subOneOne : holFp64Sub .roundTiesToEven one one = 0 := by
  rw [holFp64Sub_rte]; decide +kernel
/-- `sub_nz_pz=0x8000000000000000w` -/
theorem subNzPz : holFp64Sub .roundTiesToEven nz pz = 0x8000000000000000 := by
  rw [holFp64Sub_rte]; decide +kernel
/-- `sub_three_tenth=0x4007333333333333w` -/
theorem subThreeTenth : holFp64Sub .roundTiesToEven three tenth = 0x4007333333333333 := by
  rw [holFp64Sub_rte]; decide +kernel
/-- `mul_tenth_three=0x3FD3333333333334w` -/
theorem mulTenthThree : holFp64Mul .roundTiesToEven tenth three = 0x3FD3333333333334 := by
  rw [holFp64Mul_rte]; decide +kernel
/-- `mul_negone_pz=0x8000000000000000w` -/
theorem mulNegonePz : holFp64Mul .roundTiesToEven negone pz = 0x8000000000000000 := by
  rw [holFp64Mul_rte]; decide +kernel
/-- `mul_max_two=0x7FF0000000000000w` -/
theorem mulMaxTwo : holFp64Mul .roundTiesToEven maxfin two = 0x7FF0000000000000 := by
  rw [holFp64Mul_rte]; decide +kernel
/-- `mul_sub1_half=0w` -/
theorem mulSub1Half : holFp64Mul .roundTiesToEven sub1 half = 0 := by
  rw [holFp64Mul_rte]; decide +kernel
/-- `div_one_three=0x3FD5555555555555w` -/
theorem divOneThree : holFp64Div .roundTiesToEven one three = 0x3FD5555555555555 := by
  rw [holFp64Div_rte]; decide +kernel
/-- `div_one_ten=0x3FB999999999999Aw` -/
theorem divOneTen : holFp64Div .roundTiesToEven one ten = 0x3FB999999999999A := by
  rw [holFp64Div_rte]; decide +kernel
/-- `div_negone_three=0xBFD5555555555555w` -/
theorem divNegoneThree : holFp64Div .roundTiesToEven negone three = 0xBFD5555555555555 := by
  rw [holFp64Div_rte]; decide +kernel
/-- `div_sub1_two=0w` -/
theorem divSub1Two : holFp64Div .roundTiesToEven sub1 two = 0 := by
  rw [holFp64Div_rte]; decide +kernel
/-- `fma_tenth_ten_negone=0x3C90000000000000w` -/
theorem fmaTenthTenNegone : fpSemFpfma negone tenth ten = 0x3C90000000000000 := by
  rw [fpSemFpfma_rte]; decide +kernel
/-- `fma_one_one_one=0x4000000000000000w` -/
theorem fmaOneOneOne : fpSemFpfma one one one = 0x4000000000000000 := by
  rw [fpSemFpfma_rte]; decide +kernel
/-- `fma_zero_sign=0w` -/
theorem fmaZeroSign : fpSemFpfma pz negone pz = 0 := by
  rw [fpSemFpfma_rte]; decide +kernel
/-- `fma_cancel=0w` -/
theorem fmaCancel : fpSemFpfma negone one one = 0 := by
  rw [fpSemFpfma_rte]; decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS binary64 add/sub/mul/div/fpfma rounded results match all 20 HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.MachineIeeeArithRoundParity
