import Flapjack.Misc.BinaryIeeeSqrt

/-!
Direct HOL oracle rows for the choice-free branches of binary64 `fp64_sqrt`
(`scripts/hol-probes/machine_ieee_fp64_sqrt_special_probe.out`, generated by
`machine_ieee_fp64_sqrt_special_probeScript.sml`).  Both rows are
kernel-checked.  Rounded results await the computable algorithm of bead
`flapjack-h29l.6.3.2.2`.
-/

namespace Flapjack.Test.MachineIeeeSqrtSpecialParity

open Flapjack

/-- `sqrt_pinf=0x7FF0000000000000w` -/
theorem sqrtPinf : holFp64Sqrt .roundTiesToEven 0x7FF0000000000000 = 0x7FF0000000000000 := by
  decide +kernel

/-- `sqrt_nz=0x8000000000000000w` -/
theorem sqrtNz : holFp64Sqrt .roundTiesToEven 0x8000000000000000 = 0x8000000000000000 := by
  decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS binary64 fp64_sqrt infinity and -0 branches match both HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.MachineIeeeSqrtSpecialParity
