import Flapjack.FpSemHOL

/-!
Direct HOL oracle rows for the non-rounding branches of the binary64 arithmetic
(`scripts/hol-probes/machine_ieee_fp64_arith_special_probe.out`, generated by
`machine_ieee_fp64_arith_special_probeScript.sml`).  They cover infinity operands, zero
divisors, and fused multiply-add with an infinite product or addend.  These
branches never reach the choice-based rounding or `float_some_qnan`, so each
row is a kernel-checked theorem about the (noncomputable) HOL renderings.
-/

namespace Flapjack.Test.MachineIeeeArithSpecialParity

open Flapjack

private def one : BitVec 64 := 0x3FF0000000000000
private def two : BitVec 64 := 0x4000000000000000
private def negone : BitVec 64 := 0xBFF0000000000000
private def pz : BitVec 64 := 0x0
private def nz : BitVec 64 := 0x8000000000000000
private def pinf : BitVec 64 := 0x7FF0000000000000
private def ninf : BitVec 64 := 0xFFF0000000000000

/-- `add_pinf_one=0x7FF0000000000000w` -/
theorem addPinfOne : holFp64Add .roundTiesToEven pinf one = 0x7FF0000000000000 := by decide +kernel
/-- `add_one_ninf=0xFFF0000000000000w` -/
theorem addOneNinf : holFp64Add .roundTiesToEven one ninf = 0xFFF0000000000000 := by decide +kernel
/-- `add_pinf_pinf=0x7FF0000000000000w` -/
theorem addPinfPinf : holFp64Add .roundTiesToEven pinf pinf = 0x7FF0000000000000 := by decide +kernel
/-- `sub_one_pinf=0xFFF0000000000000w` -/
theorem subOnePinf : holFp64Sub .roundTiesToEven one pinf = 0xFFF0000000000000 := by decide +kernel
/-- `sub_ninf_pinf=0xFFF0000000000000w` -/
theorem subNinfPinf : holFp64Sub .roundTiesToEven ninf pinf = 0xFFF0000000000000 := by decide +kernel
/-- `mul_pinf_negone=0xFFF0000000000000w` -/
theorem mulPinfNegone : holFp64Mul .roundTiesToEven pinf negone = 0xFFF0000000000000 := by decide +kernel
/-- `mul_ninf_ninf=0x7FF0000000000000w` -/
theorem mulNinfNinf : holFp64Mul .roundTiesToEven ninf ninf = 0x7FF0000000000000 := by decide +kernel
/-- `div_one_pinf=0w` -/
theorem divOnePinf : holFp64Div .roundTiesToEven one pinf = 0 := by decide +kernel
/-- `div_negone_pinf=0x8000000000000000w` -/
theorem divNegonePinf : holFp64Div .roundTiesToEven negone pinf = 0x8000000000000000 := by decide +kernel
/-- `div_pinf_negone=0xFFF0000000000000w` -/
theorem divPinfNegone : holFp64Div .roundTiesToEven pinf negone = 0xFFF0000000000000 := by decide +kernel
/-- `div_one_pz=0x7FF0000000000000w` -/
theorem divOnePz : holFp64Div .roundTiesToEven one pz = 0x7FF0000000000000 := by decide +kernel
/-- `div_negone_pz=0xFFF0000000000000w` -/
theorem divNegonePz : holFp64Div .roundTiesToEven negone pz = 0xFFF0000000000000 := by decide +kernel
/-- `div_one_nz=0xFFF0000000000000w` -/
theorem divOneNz : holFp64Div .roundTiesToEven one nz = 0xFFF0000000000000 := by decide +kernel
/-- `fma_pinf_product=0x7FF0000000000000w` -/
theorem fmaPinfProduct : fpSemFpfma one pinf two = 0x7FF0000000000000 := by decide +kernel
/-- `fma_ninf_addend=0xFFF0000000000000w` -/
theorem fmaNinfAddend : fpSemFpfma ninf one one = 0xFFF0000000000000 := by decide +kernel
/-- `fma_neg_inf_product=0xFFF0000000000000w` -/
theorem fmaNegInfProduct : fpSemFpfma one ninf two = 0xFFF0000000000000 := by decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS binary64 add/sub/mul/div/fpfma infinity and zero-divisor branches match all 16 HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.MachineIeeeArithSpecialParity
