import Flapjack.Misc.MachineIeee

/-!
Direct HOL oracle rows for the binary64 comparison and sign operations
(`scripts/hol-probes/machine_ieee_fp64_compare_probe.out`, generated by
`machine_ieee_fp64_compare_probeScript.sml` from HOL's
`src/floating-point/binary_ieeeScript.sml` and `machine_ieeeScript.sml`).
-/

namespace Flapjack.Test.MachineIeeeCompareParity

open Flapjack

private def one : BitVec 64 := 0x3FF0000000000000
private def two : BitVec 64 := 0x4000000000000000
private def negone : BitVec 64 := 0xBFF0000000000000
private def pz : BitVec 64 := 0x0
private def nz : BitVec 64 := 0x8000000000000000
private def sub1 : BitVec 64 := 0x1
private def sub2 : BitVec 64 := 0x2
private def maxsub : BitVec 64 := 0xFFFFFFFFFFFFF
private def minnorm : BitVec 64 := 0x10000000000000
private def maxfin : BitVec 64 := 0x7FEFFFFFFFFFFFFF
private def pinf : BitVec 64 := 0x7FF0000000000000
private def ninf : BitVec 64 := 0xFFF0000000000000
private def qnan : BitVec 64 := 0x7FF8000000000000
private def snan : BitVec 64 := 0x7FF0000000000001
private def nqnan : BitVec 64 := 0xFFF8000000000000

/-- All 32 rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("lt_one_two", holFp64LessThan one two == true),
   ("lt_two_one", holFp64LessThan two one == false),
   ("lt_pz_nz", holFp64LessThan pz nz == false),
   ("lt_nz_pz", holFp64LessThan nz pz == false),
   ("lt_sub1_sub2", holFp64LessThan sub1 sub2 == true),
   ("lt_maxsub_minnorm", holFp64LessThan maxsub minnorm == true),
   ("lt_ninf_sub1", holFp64LessThan ninf sub1 == true),
   ("lt_maxfin_pinf", holFp64LessThan maxfin pinf == true),
   ("lt_pinf_pinf", holFp64LessThan pinf pinf == false),
   ("lt_qnan_one", holFp64LessThan qnan one == false),
   ("lt_one_snan", holFp64LessThan one snan == false),
   ("lt_negone_pz", holFp64LessThan negone pz == true),
   ("lt_pinf_ninf", holFp64LessThan pinf ninf == false),
   ("le_pz_nz", holFp64LessEqual pz nz == true),
   ("le_pinf_pinf", holFp64LessEqual pinf pinf == true),
   ("le_qnan_qnan", holFp64LessEqual qnan qnan == false),
   ("le_two_one", holFp64LessEqual two one == false),
   ("le_ninf_ninf", holFp64LessEqual ninf ninf == true),
   ("le_sub1_one", holFp64LessEqual sub1 one == true),
   ("eq_pz_nz", holFp64Equal pz nz == true),
   ("eq_qnan_qnan", holFp64Equal qnan qnan == false),
   ("eq_one_one", holFp64Equal one one == true),
   ("eq_ninf_pinf", holFp64Equal ninf pinf == false),
   ("eq_sub1_sub2", holFp64Equal sub1 sub2 == false),
   ("abs_negone", holFp64Abs negone == 0x3FF0000000000000),
   ("abs_nz", holFp64Abs nz == 0),
   ("abs_nqnan", holFp64Abs nqnan == 0x7FF8000000000000),
   ("abs_ninf", holFp64Abs ninf == 0x7FF0000000000000),
   ("neg_one", holFp64Negate one == 0xBFF0000000000000),
   ("neg_pz", holFp64Negate pz == 0x8000000000000000),
   ("neg_qnan", holFp64Negate qnan == 0xFFF8000000000000),
   ("neg_sub1", holFp64Negate sub1 == 0x8000000000000001)]

#guard rows.all (·.2)

/-! Evaluated values of the `Rat` rendering of `float_to_real` at the binary64
landmarks: `1.0`, `2.0`, `-1.0`, the least subnormal `2^-1074`, and the least
normal `2^-1022`. -/

#guard holFloatValue (holFp64ToFloat one) == .float 1
#guard holFloatValue (holFp64ToFloat two) == .float 2
#guard holFloatValue (holFp64ToFloat negone) == .float (-1)
#guard holFloatValue (holFp64ToFloat sub1) == .float (1 / 2 ^ 1074)
#guard holFloatValue (holFp64ToFloat minnorm) == .float (1 / 2 ^ 1022)
#guard holFloatValue (holFp64ToFloat maxsub) == .float ((2 ^ 52 - 1) / 2 ^ 1074)
#guard holFloatValue (holFp64ToFloat pinf) == .infinity
#guard holFloatValue (holFp64ToFloat snan) == .nan

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 32 then
    IO.println "PASS machine_ieee fp64 lessThan/lessEqual/equal/abs/negate match all 32 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL machine_ieee fp64 comparison HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.MachineIeeeCompareParity
