import Flapjack.Pancake.PanGlobals.CompileTopExact
import Flapjack.Pancake.PanGlobalsByteRanged

/-! Executable replay of top_missing/top_function/top_global_exception in
scripts/hol-probes/pan_globals_compile_top_probe.out, generated by direct
original HOL EVAL. All inputs, metadata, words and output order match. -/

namespace Flapjack.Test.PanGlobalsCompileTopExactParity

open Flapjack Flapjack.Pancake.PanLang Flapjack.Basis.Pure.MlString

def main : FunDeclHOL 64 :=
  { name := ofString "main", inline := true, exported := true,
    params := [(ofString "x", .one)],
    body := .return (.var .global (ofString "g")), returnShape := .one }

example : compileTopExactHOL ([] : List (DeclHOL 64)) (ofString "main") = [] := by
  rfl

def functionGuard : Bool :=
  match compileTopExactHOL [.function main] (ofString "main") with
  | [.function entry, .function original] =>
      match entry.params, entry.body, original.params, original.body,
          entry.returnShape, original.returnShape with
      | [(x, .one)], .seq .skip (.call none target [.var .local y]),
          [(z, .one)], .return (.const value), .one, .one =>
          toStringOfBytes entry.name == "main" && !entry.inline && !entry.exported &&
          toStringOfBytes original.name == "main'" && original.inline && original.exported &&
          toStringOfBytes x == "x" && toStringOfBytes y == "x" &&
          toStringOfBytes z == "x" && toStringOfBytes target == "main'" &&
          value == 0
      | _, _, _, _, _, _ => false
  | _ => false

#guard functionGuard

def globalExceptionGuard : Bool :=
  match compileTopExactHOL
      [.function main, .decl .one (ofString "g") (.const 7), .exnDecl (ofString "E") .one]
      (ofString "main") with
  | [.exnDecl exception .one, .function entry, .function original] =>
      match entry.body, original.body, entry.params, original.params,
          entry.returnShape, original.returnShape with
      | .seq (.seq (.store (.op .sub [.topAddr, .const address]) (.const value)) .skip)
          (.call none target [.var .local parameter]),
          .return (.load .one (.op .sub [.topAddr, .const loaded])),
          [(x, .one)], [(y, .one)], .one, .one =>
          toStringOfBytes exception == "E" && toStringOfBytes entry.name == "main" &&
          !entry.inline && !entry.exported && toStringOfBytes original.name == "main'" &&
          original.inline && original.exported && toStringOfBytes target == "main'" &&
          toStringOfBytes parameter == "x" && toStringOfBytes x == "x" &&
          toStringOfBytes y == "x" && address == 8 && value == 7 && loaded == 8
      | _, _, _, _, _, _ => false
  | _ => false

#guard globalExceptionGuard

/-- The executed parser-path route `globalCompileTopCakeRouted` decodes
`compileTopExactHOL` on the encoded input (`compileTopExactHOL_decode`). These
guards replay the same three original HOL rows through that decode and compare
with the production `globalCompileTopCake`, including output order. -/
def routeGuard (declarations : List (DeclHOL 64)) (start : String) : Bool :=
  let production := declarations.map declOfHOL
  toString (repr ((compileTopExactHOL (production.map declToHOL) (ofString start)).map
      declOfHOL)) ==
    toString (repr (globalCompileTopCake production start))

#guard routeGuard [] "main"
#guard routeGuard [.function main] "main"
#guard routeGuard
  [.function main, .decl .one (ofString "g") (.const 7), .exnDecl (ofString "E") .one] "main"

def runChecks : IO Bool := do
  let result := functionGuard && globalExceptionGuard &&
    routeGuard [] "main" && routeGuard [.function main] "main" &&
    routeGuard [.function main, .decl .one (ofString "g") (.const 7),
      .exnDecl (ofString "E") .one] "main"
  IO.println (if result then "PASS exact PanGlobals compile_top original HOL rows"
    else "FAIL exact PanGlobals compile_top original HOL rows")
  pure result

end Flapjack.Test.PanGlobalsCompileTopExactParity
