import Flapjack.Pancake.Semantics.PanSemStateEval

/-!
# Store32 endianness parity (production and exact) against HOL `mem_store_32`

The expected cells come from `scripts/hol-probes/pan_store32_endian_probe.out`,
generated by `pan_store32_endian_probeScript.sml`, which evaluates CakeML's
`mem_store_32_def` (`pancake/semantics/panSemScript.sml`) on a 64-bit cell
`0x0807060504030201` at byte address 8, in both endiannesses. The exact Store32
clause passes `w2w w`, so the `be_w2w` row stores the 64-bit value
`0xAABBCCDD11223344` truncated to 32 bits.

Both the executed state-derived `store32`
(`panValueMemoryAccessOfModel panSemBitVec64WordModel`, used by
`panSemTotalStore32Clause` and the value evaluator) and the exact
`panMemStore32HOL` must match every row. Before bead
`flapjack-pxn.18.4.3.77.2.13.2.3.1` the executed store took big-endian bytes
from the 64-bit layout and wrote zeros for 32-bit values.
-/

namespace Flapjack.Test.PanStore32EndianParity

open Flapjack

def originalProbeSource : String :=
  "cakeml/pancake/semantics/panSemScript.sml (mem_store_32_def); scripts/hol-probes/pan_store32_endian_probeScript.sml"

def cell : RiscV.Word 64 := BitVec.ofNat 64 0x0807060504030201

/-- The executed state-derived `store32`, reading back the cell at address 8. -/
def production (domainAddr : Nat) (be : Bool) (addr : Nat) (value : Nat) : Option Nat :=
  let access := panValueMemoryAccessOfModel panSemBitVec64WordModel
    (fun a => a == BitVec.ofNat 64 domainAddr) (fun a => a == BitVec.ofNat 64 domainAddr) be
  match access.store32 access.domain (fun _ => some (.word cell)) panSemBitVec64BytesInWord
      (BitVec.ofNat 64 addr) (BitVec.ofNat 64 value) with
  | some m =>
      match m (BitVec.ofNat 64 8) with
      | some (.word x) => some x.toNat
      | _ => none
  | none => none

/-- The exact tagged `panMemStore32HOL` at the `w2w`-truncated value. -/
def exact (domainAddr : Nat) (be : Bool) (addr : Nat) (value : Nat) : Option Nat :=
  match @panMemStore32HOL 64 _ (fun _ => .word cell) (fun a => a = BitVec.ofNat 64 domainAddr)
      (fun _ => inferInstance) be (BitVec.ofNat 64 addr)
      (BitVec.ofNat 32 (BitVec.ofNat 64 value).toNat) with
  | some m =>
      match m (BitVec.ofNat 64 8) with
      | .word x => some x.toNat
  | none => none

-- HOL rows (pan_store32_endian_probe.out)
def storeLeLow : Option Nat := some 0x0807060511223344
def storeLeHigh : Option Nat := some 0x1122334404030201
def storeBeLow : Option Nat := some 0x1122334404030201
def storeBeHigh : Option Nat := some 0x0807060511223344
def storeBeW2w : Option Nat := some 0x1122334404030201
def storeBeUnaligned : Option Nat := none
def storeBeOutside : Option Nat := none

def rows : List (String × Option Nat × Option Nat × Option Nat) :=
  [("store32_le_low", production 8 false 8 0x11223344, exact 8 false 8 0x11223344, storeLeLow),
   ("store32_le_high", production 8 false 12 0x11223344, exact 8 false 12 0x11223344, storeLeHigh),
   ("store32_be_low", production 8 true 8 0x11223344, exact 8 true 8 0x11223344, storeBeLow),
   ("store32_be_high", production 8 true 12 0x11223344, exact 8 true 12 0x11223344, storeBeHigh),
   ("store32_be_w2w", production 8 true 8 0xAABBCCDD11223344,
      exact 8 true 8 0xAABBCCDD11223344, storeBeW2w),
   ("store32_be_unaligned", production 8 true 9 0x11223344, exact 8 true 9 0x11223344,
      storeBeUnaligned),
   ("store32_be_outside", production 16 true 8 0x11223344, exact 16 true 8 0x11223344,
      storeBeOutside)]

def rowsMatch : Bool :=
  rows.all fun (_, p, e, hol) => p == hol && e == hol

#guard rowsMatch

def runChecks : IO Bool := do
  if rowsMatch then
    IO.println "PASS executed and exact Store32 match HOL mem_store_32 in both endiannesses"
  else
    for (label, p, e, hol) in rows do
      if !(p == hol && e == hol) then
        IO.println s!"FAIL {label}: production={p} exact={e} hol={hol}"
  pure rowsMatch

end Flapjack.Test.PanStore32EndianParity
