import Flapjack.Pancake.Proofs.PanStructs.CompileCorrect

/-! Kernel-checked replay of the direct original-HOL EVAL rows in
`scripts/hol-probes/pan_structs_res_convert_probe.out`, generated by
`scripts/hol-probes/pan_structs_res_convert_probeScript.sml` from
`cakeml/pancake/proofs/pan_structsProofScript.sml:992-1009` and `:1028-1031`.

The rows are reproduced over the exact `PanSemResultExact`/`ValueHOL` carriers
through the tagged ports `convertResHOL`, `isContResHOL`,
`isContResHOL_eqDisj`, and `resVsHOL` at width 64. Each `example` is
kernel-checked, so a disagreeing row fails the build. -/

namespace Flapjack.Test.PanStructsResConvertParity

open Flapjack
open Flapjack.Pancake.PanLang (MlS)

private abbrev ml (s : String) : MlS := Flapjack.Basis.Pure.MlString.ofString s

/-- The concrete value replaying the HOL `ValWord w` rows. -/
private def valWord (w : Nat) : ValueHOL 64 := .val (.word (BitVec.ofNat 64 w))

private def returnSeven : Option (PanSemResultExact 64) := some (.returned (valWord 7))

private def exceptionFive : Option (PanSemResultExact 64) :=
  some (.exception (ml "e") (valWord 5))

private def finalFfiEvent : HolFinalEvent :=
  { name := .extCall (ml "x"), configuration := [], bytes := [], outcome := .failed }

private def finalFfiResult : Option (PanSemResultExact 64) :=
  some (.finalFfi finalFfiEvent)

/-! ## `convert_res` rows (`pan_structs_res_convert_probe.out:1-8`) -/

example : convertResHOL (width := 64) (some .break) = some .break := rfl

example : convertResHOL returnSeven = returnSeven := by
  simp [returnSeven, valWord, convertResHOL, convertV]

example : convertResHOL exceptionFive = exceptionFive := by
  simp [exceptionFive, valWord, convertResHOL, convertV]

example : convertResHOL (none : Option (PanSemResultExact 64)) = none := rfl

example : convertResHOL (width := 64) (some .error) = some .error := by
  simp [convertResHOL]

example : convertResHOL (width := 64) (some .timeOut) = some .timeOut := by
  simp [convertResHOL]

example : convertResHOL (width := 64) (some .continue) = some .continue := by
  simp [convertResHOL]

example : convertResHOL finalFfiResult = finalFfiResult := by
  simp [finalFfiResult, finalFfiEvent, convertResHOL]

/-! ## `is_cont_res` rows (`pan_structs_res_convert_probe.out:9-14`) -/

#guard (isContResHOL (none : Option (PanSemResultExact 64))) == true

#guard isContResHOL (some (.break : PanSemResultExact 64)) == true

#guard isContResHOL (some (.continue : PanSemResultExact 64)) == true

#guard isContResHOL (some (.error : PanSemResultExact 64)) == false

#guard isContResHOL (some (.timeOut : PanSemResultExact 64)) == false

#guard isContResHOL (some (.returned (valWord 1))) == false

/-! ## `is_cont_res_eq_disj` instances at the same concrete points

The theorem's `true` side is the exact row; the negated equality pins the
non-cont rows. -/

example :
    (isContResHOL (some (.break : PanSemResultExact 64)) = true) ↔
      (some (.break : PanSemResultExact 64) = none ∨
       some (.break : PanSemResultExact 64) = some .break ∨
       some (.break : PanSemResultExact 64) = some .continue) :=
  isContResHOL_eqDisj _

example :
    (isContResHOL (some (.continue : PanSemResultExact 64)) = true) ↔
      (some (.continue : PanSemResultExact 64) = none ∨
       some (.continue : PanSemResultExact 64) = some .break ∨
       some (.continue : PanSemResultExact 64) = some .continue) :=
  isContResHOL_eqDisj _

example :
    (isContResHOL (none : Option (PanSemResultExact 64)) = true) ↔
      ((none : Option (PanSemResultExact 64)) = none ∨
       (none : Option (PanSemResultExact 64)) = some .break ∨
       (none : Option (PanSemResultExact 64)) = some .continue) :=
  isContResHOL_eqDisj _

example : ¬ (isContResHOL (some (.error : PanSemResultExact 64)) = true) := by decide

example : ¬ (isContResHOL (some (.timeOut : PanSemResultExact 64)) = true) := by decide

example : ¬ (isContResHOL (some (.returned (valWord 1))) = true) := by decide

/-! ## `res_vs` rows (`pan_structs_res_convert_probe.out:15-19`) -/

example : resVsHOL returnSeven = [valWord 7] := rfl

example : resVsHOL exceptionFive = [valWord 5] := rfl

example : resVsHOL (some (.break : PanSemResultExact 64)) = [] := rfl

example : resVsHOL (none : Option (PanSemResultExact 64)) = [] := rfl

example : resVsHOL (some (.continue : PanSemResultExact 64)) = [] := rfl

end Flapjack.Test.PanStructsResConvertParity
