import Flapjack.Pancake.Semantics.PanSemStateEval

/-!
# Shared-store byte payload parity against HOL `sh_mem_store`

The expected payloads come from `scripts/hol-probes/pan_sh_mem_store_bytes_probe.out`,
generated by `pan_sh_mem_store_bytes_probeScript.sml`, which evaluates CakeML's
`sh_mem_store_def` (`pancake/semantics/panSemScript.sml:528-547`) on a
`(64, word8 list) panSem$state` whose FFI oracle echoes the payload back as the
new `ffi_state`. HOL builds the payload as
`TAKE nb (word_to_bytes w F) ++ word_to_bytes addr F` with `F` always
little-endian, and never writes source memory.

The legacy value evaluators model shared memory as ordinary cells, so the
faithful alignment claim is: the little-endian cell bytes written at
`address, address + 1, ...` equal the HOL payload prefix
`TAKE nb (word_to_bytes w F)`. Before bead
`flapjack-pxn.18.4.3.77.2.13.2.3.1.1` the op16/op32 shared store took
big-endian bytes from the 64-bit layout (e.g. under `be = true` it wrote the
top bytes `[0x11, 0x22]` for value `0x1122334455667788`).

Under a big-endian target the cell layout is target-endian (so it round-trips
with `sharedRead`, which decodes with `be`), while the narrow bytes selected
from the value are its little-endian bytes, exactly as the ordinary
`store16`/`store32` clauses do after bead
`flapjack-pxn.18.4.3.77.2.13.2.3.1`.
-/

namespace Flapjack.Test.PanShMemStoreBytesParity

open Flapjack

def originalProbeSource : String :=
  "cakeml/pancake/semantics/panSemScript.sml (sh_mem_store_def); scripts/hol-probes/pan_sh_mem_store_bytes_probeScript.sml"

def cell : RiscV.Word 64 := BitVec.ofNat 64 0x0807060504030201
def value : RiscV.Word 64 := BitVec.ofNat 64 0x1122334455667788

def memory : RiscV.Word 64 → Option (PanValue (RiscV.Word 64)) :=
  fun a => if a == BitVec.ofNat 64 8 then some (.word cell) else none

def access (be : Bool) : PanValueMemoryAccess (RiscV.Word 64) :=
  panValueMemoryAccessOfModel panSemBitVec64WordModel
    (fun a => a == BitVec.ofNat 64 8) (fun a => a == BitVec.ofNat 64 8) be

/-- The modelled cell after a shared store (the store is to the aligned cell at
address 8; op16/op32 also write `address + 1`, `address + 2`, `address + 3`). -/
def storedCell (be : Bool) (size : OpSize) : Option (RiscV.Word 64) :=
  match (access be).sharedStore memory panSemBitVec64BytesInWord size
      (BitVec.ofNat 64 8) (.word value) with
  | some m =>
      match m (BitVec.ofNat 64 8) with
      | some (.word x) => some x
      | _ => none
  | none => none

/-- Byte `offset` of `cell` read in the target endianness `be` (address order
`8, 9, ...`). -/
def readByte (be : Bool) (offset : Nat) (cell : RiscV.Word 64) : Nat :=
  (panSemBitVec64WordModel.getByte panSemBitVec64BytesInWord
      (BitVec.ofNat 64 (8 + offset)) cell be).toNat % 256

/-- The first `n` bytes of the stored cell in address order, read in the target
endianness `be`. -/
def cellBytes (be : Bool) (size : OpSize) (n : Nat) : Option (List Nat) :=
  (storedCell be size).map fun cell => (List.range n).map fun i => readByte be i cell

-- HOL payload prefixes (pan_sh_mem_store_bytes_probe.out).
def holPayload8 : List Nat := [0x88]
def holPayload16 : List Nat := [0x88, 0x77]
def holPayload32 : List Nat := [0x88, 0x77, 0x66, 0x55]
def holPayloadW : List Nat := [0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11]

/-- Little-endian cell bytes equal the HOL little-endian payload prefix. -/
def payloadRowsMatch : Bool :=
  cellBytes false .op8 1 == some holPayload8
    && cellBytes false .op16 2 == some holPayload16
    && cellBytes false .op32 4 == some holPayload32
    && cellBytes false .opW 8 == some holPayloadW

/-- Big-endian source targets place the value's little-endian bytes in
target-endian cell order (round-trippable with `sharedRead`). -/
def bigEndianRowsMatch : Bool :=
  cellBytes true .op16 2 == some [0x77, 0x88]
    && cellBytes true .op32 4 == some [0x55, 0x66, 0x77, 0x88]

def rowsMatch : Bool := payloadRowsMatch && bigEndianRowsMatch

#guard rowsMatch

def runChecks : IO Bool := do
  if rowsMatch then
    IO.println "PASS shared-store op16/op32 take little-endian value bytes matching HOL sh_mem_store payload"
  else
    IO.println s!"FAIL shared-store payload parity: le={cellBytes false .op16 2} be={cellBytes true .op16 2}"
  pure rowsMatch

end Flapjack.Test.PanShMemStoreBytesParity