import Flapjack.Compiler.Backend.Semantics.StackSem.Install

/-! Kernel replay of all six original HOL observations in
`scripts/hol-probes/stacksem_install_probe.out`, generated by
`stacksem_install_probeScript.sml` from
`cakeml/compiler/backend/semantics/stackSemScript.sml:893-921`.

The fixture fixes the 8-bit state of the probe: registers `1..5` hold the four
`Install` operands (`1 -> 0w`, `2 -> 2w`, `3 -> 0w`, `4 -> 2w`) plus `5 -> 0x55w`,
`ffi_save_regs = {1; 5}`, a one-word bitmap list, `code = insert 7 (Return 0) LN`,
a code buffer holding `[0x11; 0x22]` and a data buffer holding `[0xAA; 0xBB]`,
a concrete compiler oracle `n -> (n, [(3, Skip)], [0xAA; 0xBB])`, and a concrete
compiler `cfg -> ([0x11; 0x22], cfg + 1)`. The successful row observes the
bitmap append, the code union of keys 3 and 7, the `DRESTRICT` register
restriction followed by the `FUPDATE` at `1`, the emptied `fp_regs`, both
flushed buffer positions, and the advanced compile oracle; the remaining rows
observe the byte mismatch, empty `progs`, compiler `NONE`, the `use_stack = F`
arm (data buffer left unflushed), and a non-word operand. -/

namespace Flapjack.Test.StackSemInstallParity

open Flapjack Flapjack.StackSemInstall Flapjack.Compiler.Backend.StackLang

private abbrev W := WordLocW 8

private def w8 (n : Nat) : BitVec 8 := BitVec.ofNat 8 n
private def w64 (n : Nat) : BitVec 64 := BitVec.ofNat 64 n

/-- The oracle returns the two-byte bitmap `[0xAA; 0xBB]` and the single
    program `[(3, Skip)]` at every step, with the configuration equal to the
    step index. -/
private def orac : Nat → Nat × List (Nat × HolProg 8) × List (BitVec 8) :=
  fun n => (n, [(3, .skip)], [w8 0xAA, w8 0xBB])

/-- The empty-`progs` oracle for the error row. -/
private def oracEmpty : Nat → Nat × List (Nat × HolProg 8) × List (BitVec 8) :=
  fun n => (n, [], [w8 0xAA, w8 0xBB])

/-- The compiler returning the matching bytes and advancing the configuration. -/
private def compOk : Nat → List (Nat × HolProg 8) → Option (List (BitVec 8) × Nat) :=
  fun cfg _ => some ([w8 0x11, w8 0x22], cfg + 1)

/-- The compiler returning mismatching bytes for the bytes-mismatch row. -/
private def compBad : Nat → List (Nat × HolProg 8) → Option (List (BitVec 8) × Nat) :=
  fun cfg _ => some ([w8 0x12, w8 0x22], cfg + 1)

/-- The compiler returning `NONE` for the compile-`NONE` row. -/
private def compNone : Nat → List (Nat × HolProg 8) → Option (List (BitVec 8) × Nat) :=
  fun _ _ => none

private def ffi0 : HolFfiState Nat :=
  { oracle := fun _ _ _ _ => .final .diverged, ffiState := 0, ioEvents := [] }

/-- Probe registers `1 -> 0w`, `2 -> 2w`, `3 -> 0w`, `4 -> 2w`, `5 -> 0x55w`. -/
private def regs0 : HolFiniteMapExact Nat W :=
  let m0 : HolFiniteMapExact Nat W := HolFiniteMapExact.empty
  let m1 := m0.updateEq (1, .word (w8 0))
  let m2 := m1.updateEq (2, .word (w8 2))
  let m3 := m2.updateEq (3, .word (w8 0))
  let m4 := m3.updateEq (4, .word (w8 2))
  m4.updateEq (5, .word (w8 0x55))

private def cb0 : WordSemBuffer 8 8 :=
  { position := w8 0, buffer := [w8 0x11, w8 0x22], spaceLeft := 2 }

private def db0 : WordSemBuffer 8 8 :=
  { position := w8 0, buffer := [w8 0xAA, w8 0xBB], spaceLeft := 2 }

/-- Concrete base state of the probe. `ffi_save_regs = {1; 5}`, code holds key 7,
    and the compile oracle/compiler are the concrete closures above. -/
private def s0 : StackSemStateFiniteExact 8 Nat Nat where
  regs := regs0
  fpRegs := (HolFiniteMapExact.empty : HolFiniteMapExact Nat (BitVec 64)).updateEq
    (9, w64 0x66)
  store := HolFiniteMapExact.empty
  stack := []
  stackSpace := 0
  memory := fun _ => .word 0
  mdomain := fun _ => false
  shMdomain := fun _ => false
  bitmaps := [w8 0x01]
  compile := compOk
  compileOracle := orac
  codeBuffer := cb0
  dataBuffer := db0
  gcFun := fun _ => none
  useStack := true
  useStore := false
  useAlloc := false
  clock := 5
  code := sptInsert 7 (.ret 0) .ln
  ffi := ffi0
  ffiSaveRegs := fun r => r == 1 || r == 5
  be := false

/-- Result view: distinguishes the three observed result shapes. -/
private inductive RView where
  | none
  | error
  | other
  deriving DecidableEq

private def resView : Option (StackSemResult 8) → RView
  | none => .none
  | some .error => .error
  | some _ => .other

/-- Program view: distinguishes the two programs of the fixture. -/
private inductive GView where
  | skip
  | ret (n : Nat)
  | other
  deriving DecidableEq

private def gView : HolProg 8 → GView
  | .skip => .skip
  | .ret n => .ret n
  | _ => .other

/-- Execute the fragment and project the observed fields. The unhandled
    constructor `none` case is impossible for `.install` but is mapped through
    the option so the projection stays total. -/
private def proj
    (r : Option (Option (StackSemResult 8) × StackSemStateFiniteExact 8 Nat Nat)) :
    Option (RView × List (BitVec 8) × Option GView × Option GView ×
      Option W × Option W × Option W × Option (BitVec 64) ×
      BitVec 8 × BitVec 8 × Nat × Nat) :=
  r.map (fun p =>
    (resView p.1, p.2.bitmaps, (sptLookup 3 p.2.code).map gView,
     (sptLookup 7 p.2.code).map gView, p.2.regs.lookup 1, p.2.regs.lookup 2,
     p.2.regs.lookup 5, p.2.fpRegs.lookup 9, p.2.codeBuffer.position,
     p.2.dataBuffer.position, p.2.dataBuffer.buffer.length,
     (p.2.compileOracle 0).1))

private abbrev Expected :=
  RView × List (BitVec 8) × Option GView × Option GView ×
    Option W × Option W × Option W × Option (BitVec 64) ×
    BitVec 8 × BitVec 8 × Nat × Nat

/-- All six rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("install_success",
    proj (evaluateInstall (.install 1 2 3 4 5) s0) ==
      some (.none, [w8 0x01, w8 0xAA, w8 0xBB], some .skip, some (.ret 0),
        some (.loc 3 0), none, some (.word (w8 0x55)), none,
        w8 2, w8 2, 0, 1)),
   ("install_bytes_mismatch",
    proj (evaluateInstall (.install 1 2 3 4 5) { s0 with compile := compBad }) ==
      some (.error, [w8 0x01], none, some (.ret 0),
        some (.word (w8 0)), some (.word (w8 2)), some (.word (w8 0x55)),
        some (w64 0x66), w8 0, w8 0, 2, 0)),
   ("install_progs_empty",
    proj (evaluateInstall (.install 1 2 3 4 5) { s0 with compileOracle := oracEmpty }) ==
      some (.error, [w8 0x01], none, some (.ret 0),
        some (.word (w8 0)), some (.word (w8 2)), some (.word (w8 0x55)),
        some (w64 0x66), w8 0, w8 0, 2, 0)),
   ("install_compile_none",
    proj (evaluateInstall (.install 1 2 3 4 5) { s0 with compile := compNone }) ==
      some (.error, [w8 0x01], none, some (.ret 0),
        some (.word (w8 0)), some (.word (w8 2)), some (.word (w8 0x55)),
        some (w64 0x66), w8 0, w8 0, 2, 0)),
   ("install_use_stack_false",
    proj (evaluateInstall (.install 1 2 3 4 5) { s0 with useStack := false }) ==
      some (.none, [w8 0x01, w8 0xAA, w8 0xBB], some .skip, some (.ret 0),
        some (.loc 3 0), none, some (.word (w8 0x55)), none,
        w8 2, w8 0, 2, 1)),
   ("install_non_word_operand",
    proj (evaluateInstall (.install 1 2 3 4 5)
      { s0 with regs := s0.regs.updateEq (1, .loc 1 0) }) ==
      some (.error, [w8 0x01], none, some (.ret 0),
        some (.loc 1 0), some (.word (w8 2)), some (.word (w8 0x55)),
        some (w64 0x66), w8 0, w8 0, 2, 0))]

#guard rows.all (·.2)

/-- Kernel regression pin of the successful row, stated as a proof so the
    reducer checks the projection rather than only the boolean comparison. -/
example : proj (evaluateInstall (.install 1 2 3 4 5) s0) =
    some (.none, [w8 0x01, w8 0xAA, w8 0xBB], some .skip, some (.ret 0),
      some (.loc 3 0), none, some (.word (w8 0x55)), none, w8 2, w8 2, 0, 1) := by
  cbv

/-- Kernel regression pin of the `use_stack = F` row, whose data buffer is not
    flushed but whose oracle bitmap still satisfies the equality. -/
example : proj (evaluateInstall (.install 1 2 3 4 5) { s0 with useStack := false }) =
    some (.none, [w8 0x01, w8 0xAA, w8 0xBB], some .skip, some (.ret 0),
      some (.loc 3 0), none, some (.word (w8 0x55)), none, w8 2, w8 0, 2, 1) := by
  cbv

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 6 then
    IO.println "PASS exact StackSem Install fragment matches all 6 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL StackSem Install HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.StackSemInstallParity
