import Flapjack.Compiler.Backend.Semantics.StackSem.Ffi

/-! Kernel replay of all four original HOL observations in
`scripts/hol-probes/stacksem_ffi_probe.out`, generated by
`stacksem_ffi_probeScript.sml` from
`cakeml/compiler/backend/semantics/stackSemScript.sml:945-960`.

The fixture fixes the 64-bit state of the probe: seven registers including the
four FFI operands, a single-word memory (word 0) with `mdomain = {0w}`, the
`ffi_save_regs = {1; 6}` set, a populated `fp_regs`, and a `num`-state oracle
that returns three constant bytes and advances the host state. The successful
row observes the bytearray write-back, the HOL `DRESTRICT` register restriction,
the emptied `fp_regs`, and the replaced FFI state; the terminal row observes
`FinalFFI` with the state unchanged; the remaining rows observe `Error`. -/

namespace Flapjack.Test.StackSemFfiParity

open Flapjack Flapjack.StackSemFfi Flapjack.StackSemStateOps
open Flapjack.Compiler.Backend.StackLang

private abbrev W := WordLocW 64

private def w8 (n : Nat) : BitVec 8 := BitVec.ofNat 8 n
private def w64 (n : Nat) : BitVec 64 := BitVec.ofNat 64 n

/-- HOL `strlit "x"`: the single-character name of the probe's FFI index. -/
private def fName : Flapjack.Basis.Pure.MlString.MlString := .implode [w8 120]

/-- Oracle returning three constant bytes and advancing the host state, so the
    length check against the three-byte array read passes and `FFI_return` is
    taken. -/
private def retFfi : HolFfiState Nat :=
  { oracle := fun _ st _ _ => .ret (st + 1) [w8 0x11, w8 0x22, w8 0x33],
    ffiState := 0, ioEvents := [] }

/-- Oracle diverging immediately, producing `FFI_final`. -/
private def finalFfi : HolFfiState Nat :=
  { oracle := fun _ _ _ _ => .final .diverged, ffiState := 0, ioEvents := [] }

/-- Probe registers `1 -> 2w`, `2 -> 2w`, `3 -> 3w`, `4 -> 4w`, `6 -> 0x99w`,
    `7 -> 0x77w`, `8 -> 0x88w`. -/
private def regs0 : HolFiniteMapExact Nat W :=
  let m0 : HolFiniteMapExact Nat W := HolFiniteMapExact.empty
  let m1 := m0.updateEq (1, .word (w64 2))
  let m2 := m1.updateEq (2, .word (w64 2))
  let m3 := m2.updateEq (3, .word (w64 3))
  let m4 := m3.updateEq (4, .word (w64 4))
  let m5 := m4.updateEq (6, .word (w64 0x99))
  let m6 := m5.updateEq (7, .word (w64 0x77))
  m6.updateEq (8, .word (w64 0x88))

/-- Concrete base state of the probe. `ffi_save_regs = {1; 6}` and `mdomain =
    {0w}`. -/
private def s0 : StackSemStateFiniteExact 64 Unit Nat where
  regs := regs0
  fpRegs := (HolFiniteMapExact.empty : HolFiniteMapExact Nat (BitVec 64)).updateEq
    (9, w64 0x66)
  store := HolFiniteMapExact.empty
  stack := []
  stackSpace := 0
  memory := fun a => if a = 0 then .word (w64 0xAABBCCDDEEFF0011) else .word 0
  mdomain := fun a => a = 0
  shMdomain := fun _ => false
  bitmaps := []
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [], [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  useStack := false
  useStore := false
  useAlloc := false
  clock := 5
  code := .ln
  ffi := retFfi
  ffiSaveRegs := fun r => r == 1 || r == 6
  be := false

/-- The probe's observed result view: `NONE`, `SOME Error`, or
    `SOME (FinalFFI (Final_event name conf bytes outcome))`. -/
private inductive Res where
  | none
  | error
  | final (name : HolFfiName) (conf bytes : List (BitVec 8)) (outcome : HolFfiOutcome)
  | other
  deriving DecidableEq

private def resView : Option (StackSemResult 64) → Res
  | none => .none
  | some .error => .error
  | some (.finalFFI e) => .final e.name e.configuration e.bytes e.outcome
  | some _ => .other

/-- Execute the fragment, materialising the unhandled-constructor `none` case. -/
private def run (p : HolProg 64) (s : StackSemStateFiniteExact 64 Unit Nat) :
    Option (StackSemResult 64) × StackSemStateFiniteExact 64 Unit Nat :=
  match evaluateFfi (C := Unit) (F := Nat) p s with
  | some r => r
  | none => (none, s)

private def proj (r : Option (StackSemResult 64) × StackSemStateFiniteExact 64 Unit Nat) :
    Res × W × Option W × Option W × Option W × Option W × Option (BitVec 64) ×
      Nat × List HolIoEvent × Nat :=
  (resView r.1, r.2.memory 0, r.2.regs.lookup 1, r.2.regs.lookup 2, r.2.regs.lookup 6,
   r.2.regs.lookup 7, r.2.fpRegs.lookup 9, r.2.ffi.ffiState, r.2.ffi.ioEvents,
   r.2.clock)

/-- The program of the probe: `FFI (strlit "x") 2 1 4 3 5`. -/
private def prog : HolProg 64 := .ffi fName 2 1 4 3 5

/-- All four rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("ffi_return", proj (run prog s0) ==
      (.none, .word (w64 0xAA332211EEFF0011), some (.word (w64 2)), none,
       some (.word (w64 0x99)), none, none, 1,
       [{ name := .extCall fName, configuration := [w8 255, w8 238],
          bytes := [(w8 221, w8 17), (w8 204, w8 34), (w8 187, w8 51)] }], 5)),
   ("ffi_final", proj (run prog { s0 with ffi := finalFfi }) ==
      (.final (.extCall fName) [w8 255, w8 238] [w8 221, w8 204, w8 187] .diverged,
       .word (w64 0xAABBCCDDEEFF0011), some (.word (w64 2)), some (.word (w64 2)),
       some (.word (w64 0x99)), some (.word (w64 0x77)), some (w64 0x66), 0, [], 5)),
   ("ffi_read_failure", proj (run prog { s0 with mdomain := fun _ => false }) ==
      (.error, .word (w64 0xAABBCCDDEEFF0011), some (.word (w64 2)), some (.word (w64 2)),
       some (.word (w64 0x99)), some (.word (w64 0x77)), some (w64 0x66), 0, [], 5)),
   ("ffi_non_word_length", proj (run prog { s0 with regs := s0.regs.updateEq (1, .loc 1 0) }) ==
      (.error, .word (w64 0xAABBCCDDEEFF0011), some (.loc 1 0), some (.word (w64 2)),
       some (.word (w64 0x99)), some (.word (w64 0x77)), some (w64 0x66), 0, [], 5))]

#guard rows.all (·.2)

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 4 then
    IO.println "PASS exact StackSem FFI fragment matches all 4 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL StackSem FFI HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.StackSemFfiParity
