import Flapjack.Compiler.Backend.Semantics.StackSem.ControlCases

/-! Kernel replay of all eleven original HOL observations in
`scripts/hol-probes/stacksem_control_probe.out`, generated by
`stacksem_control_probeScript.sml` from the structured-control clauses
`Seq`, `If`, and `Loop` of
`cakeml/compiler/backend/semantics/stackSemScript.sml:811-837`.

The concrete `evaluateStub` reproduces the HOL sub-evaluations for the fixture
programs used by the probe (`Skip`, `Return`, `Raise`-free leaves, `Break`,
`Continue`, `Halt`, `Tick`); for the `Loop` re-entry it returns the exact
terminal `TimeOut`/emptied-environment observation of the fixture body, exactly
as the sibling `StackSemCallParity` stub reproduces the code sub-evaluations.
The replayed fragment then checks the `Seq` clock clamp, the `If` operand
lookup and option-valued `word_cmp` dispatch, and the `Loop` `cont_loop`/
`exit_loop`/timeout control flow. -/

namespace Flapjack.Test.StackSemControlCasesParity

open Flapjack.StackSemControlCases Flapjack.StackSemControl Flapjack.StackSemStateOps
open Flapjack.Compiler.Backend.StackLang Flapjack.Compiler.Encoders.Asm

private abbrev W := WordLocW 8

private def w8 (n : Nat) : BitVec 8 := BitVec.ofNat 8 n

/-- Concrete sub-evaluator reproducing the HOL `evaluate` results for the
fixture programs. The `.loop` arm returns the terminal timeout/empty
observation reached by the fixture `Loop (Continue 0)` body. -/
def evaluateStub {width : Nat} [NeZero width] {C F : Type}
    (prog : HolProg width) (s : StackSemStateFiniteExact width C F) :
    Option (StackSemResult width) × StackSemStateFiniteExact width C F :=
  match prog with
  | .skip => (none, s)
  | .ret n =>
      match StackSemStateOps.getVar n s with
      | some (.loc a b) => (some (.result (.loc a b)), s)
      | _ => (some .error, s)
  | .break n => (some (.break n), s)
  | .continue n => (some (.continue n), s)
  | .halt n =>
      match StackSemStateOps.getVar n s with
      | some w => (some (.halt w), StackSemStateOps.emptyEnv s)
      | none => (some .error, s)
  | .tick =>
      if s.clock = 0 then (some .timeOut, StackSemStateOps.emptyEnv s)
      else (none, StackSemStateOps.decClock s)
  | .loop _ => (some .timeOut, StackSemStateOps.emptyEnv s)
  | _ => (some .error, s)

/-- Probe fixture: register `1 -> Word 3w`, register `4 -> Loc 4 5`, one-word
stack, empty code, and the base state's other fields left arbitrary. -/
private def fixture {C F : Type} (s : StackSemStateFiniteExact 8 C F) :
    StackSemStateFiniteExact 8 C F :=
  { s with
    clock := 5
    regs := (((HolFiniteMapExact.empty : HolFiniteMapExact Nat W).updateEq
      (1, .word (w8 3))).updateEq (4, .loc 4 5))
    stack := [.word (w8 9)]
    code := .ln }

/-- Observed projection: result, clock, register 1, stack length. -/
private def observe {C F : Type}
    (result : Option (StackSemResult 8) × StackSemStateFiniteExact 8 C F) :
    Option (StackSemResult 8) × Nat × Option W × Nat :=
  (result.1, result.2.clock, result.2.regs.lookup 1, result.2.stack.length)

variable {C F : Type} (s : StackSemStateFiniteExact 8 C F)

-- seq_normal=(SOME (Result (Loc 4 5)),5,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateSeq (evaluateStub (C := C) (F := F)) (.ret 4) (.halt 1)
    (fixture s)) = (some (.result (.loc 4 5)), 5, some (.word (w8 3)), 1) := by cbv

-- seq_fallthrough=(SOME (Halt (Word 3w)),5,NONE,0)
example : observe (Flapjack.StackSemControlCases.evaluateSeq (evaluateStub (C := C) (F := F)) .skip (.halt 1)
    (fixture s)) = (some (.halt (.word (w8 3))), 5, none, 0) := by cbv

-- seq_tick_clamp=(SOME (Result (Loc 4 5)),4,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateSeq (evaluateStub (C := C) (F := F)) .tick (.ret 4)
    (fixture s)) = (some (.result (.loc 4 5)), 4, some (.word (w8 3)), 1) := by cbv

-- if_true=(SOME (Result (Loc 4 5)),5,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateIf (evaluateStub (C := C) (F := F)) .equal 1 (.imm (w8 3))
    (.ret 4) (.halt 1) (fixture s)) =
    (some (.result (.loc 4 5)), 5, some (.word (w8 3)), 1) := by cbv

-- if_false=(SOME (Halt (Word 3w)),5,NONE,0)
example : observe (Flapjack.StackSemControlCases.evaluateIf (evaluateStub (C := C) (F := F)) .equal 1 (.imm (w8 4))
    (.ret 4) (.halt 1) (fixture s)) = (some (.halt (.word (w8 3))), 5, none, 0) := by cbv

-- if_cmp_none=(SOME Error,5,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateIf (evaluateStub (C := C) (F := F)) .equal 4 (.imm (w8 3))
    (.ret 4) (.halt 1) (fixture s)) =
    (some .error, 5, some (.word (w8 3)), 1) := by cbv

-- if_operand_missing=(SOME Error,5,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateIf (evaluateStub (C := C) (F := F)) .equal 9 (.imm (w8 3))
    (.ret 4) (.halt 1) (fixture s)) =
    (some .error, 5, some (.word (w8 3)), 1) := by cbv

-- loop_recurse=(SOME TimeOut,0,NONE,0)
example : observe (Flapjack.StackSemControlCases.evaluateLoop (evaluateStub (C := C) (F := F)) (.continue 0)
    { fixture s with clock := 1 }) = (some .timeOut, 0, none, 0) := by cbv

-- loop_timeout=(SOME TimeOut,0,NONE,0)
example : observe (Flapjack.StackSemControlCases.evaluateLoop (evaluateStub (C := C) (F := F)) .skip
    { fixture s with clock := 0 }) = (some .timeOut, 0, none, 0) := by cbv

-- loop_exit_break=(SOME (Break 0),5,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateLoop (evaluateStub (C := C) (F := F)) (.break 1)
    (fixture s)) = (some (.break 0), 5, some (.word (w8 3)), 1) := by cbv

-- loop_exit_continue=(SOME (Continue 0),5,SOME (Word 3w),1)
example : observe (Flapjack.StackSemControlCases.evaluateLoop (evaluateStub (C := C) (F := F)) (.continue 1)
    (fixture s)) = (some (.continue 0), 5, some (.word (w8 3)), 1) := by cbv

/-- Result classifiers avoiding a `DecidableEq (StackSemResult 8)` instance. -/
private def isBreakZero : Option (StackSemResult 8) → Bool
  | some (.break 0) => true
  | _ => false

private def isContinueZero : Option (StackSemResult 8) → Bool
  | some (.continue 0) => true
  | _ => false

/-- Closed helper checks for the decrease certificate call sites and the
unfolding equations. -/
private def checks : Bool :=
  decide (Flapjack.StackSemControl.contLoop (some (.continue 0) : Option (StackSemResult 8)) = true) &&
  decide (Flapjack.StackSemControl.contLoop (some (.break 1) : Option (StackSemResult 8)) = false) &&
  isBreakZero (Flapjack.StackSemControl.exitLoop (some (.break 1) : Option (StackSemResult 8))) &&
  isContinueZero (Flapjack.StackSemControl.exitLoop (some (.continue 1) : Option (StackSemResult 8)))

#guard checks

def runChecks : IO Bool := do
  if checks then
    IO.println "PASS exact StackSem Seq/If/Loop control fragments match original HOL branches"
    pure true
  else
    IO.println "FAIL exact StackSem Seq/If/Loop control fragments differ from original HOL branches"
    pure false

end Flapjack.Test.StackSemControlCasesParity
