import Flapjack.Compiler.Backend.Semantics.StackSem.ShMem

/-!
Direct HOL oracle rows for the exact stackSem shared-memory helpers
(`scripts/hol-probes/stacksem_sh_mem_probe.out`, generated by
`stacksem_sh_mem_probeScript.sml` from
`cakeml/compiler/backend/semantics/stackSemScript.sml:194-308`).  The FFI
oracle increments every byte and counts calls, so each recorded `io_event`
pair list is `(b, b + 1)` over the literal payload bytes of the HOL row.  A
second oracle diverges.  The HOL probe updates fields of a free state `s`;
the Lean rows update the same fields of a concrete base state `s0`.
-/

namespace Flapjack.Test.StackSemShMemParity

open Flapjack
open Flapjack.StackSemShMem

private abbrev W := WordLocW 64

private def incFfi : HolFfiState Nat :=
  { oracle := fun _ st _ bytes => .ret (st + 1) (bytes.map (· + 1)), ffiState := 0,
    ioEvents := [] }

private def divFfi : HolFfiState Nat :=
  { oracle := fun _ _ _ _ => .final .diverged, ffiState := 0, ioEvents := [] }

private def s0 : StackSemStateFiniteExact 64 Unit Nat where
  regs := ((HolFiniteMapExact.empty : HolFiniteMapExact Nat W).updateEq
    (3, .word 0x1122)).updateEq (4, .loc 1 0)
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := []
  stackSpace := 0
  memory := fun _ => .word 0
  mdomain := fun _ => false
  shMdomain := fun a => a = 8
  bitmaps := []
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [], [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  useStack := false
  useStore := false
  useAlloc := false
  clock := 0
  code := .ln
  ffi := incFfi
  ffiSaveRegs := fun _ => false
  be := false

/-- The observed result: `none`, `SOME Error`, or `SOME (FinalFFI (Final_event
    name conf bytes outcome))`. -/
private inductive Res where
  | none
  | error
  | final (name : HolFfiName) (conf bytes : List (BitVec 8)) (outcome : HolFfiOutcome)
  | other
  deriving DecidableEq

private def resView : Option (StackSemResult 64) → Res
  | none => .none
  | some .error => .error
  | some (.finalFFI e) => .final e.name e.configuration e.bytes e.outcome
  | some _ => .other

private def proj (r : Option (StackSemResult 64) × StackSemStateFiniteExact 64 Unit Nat) :
    Res × Nat × List HolIoEvent × Option W × Option W × Option W × Nat :=
  (resView r.1, r.2.ffi.ffiState, r.2.ffi.ioEvents,
   r.2.regs.lookup 3, r.2.regs.lookup 4, r.2.regs.lookup 5, r.2.stack.length)

private def ev (op : HolShmemOp) (conf : BitVec 8) (bytes : List (BitVec 8)) : HolIoEvent :=
  { name := .sharedMem op, configuration := [conf], bytes := bytes.zip (bytes.map (· + 1)) }

private def z (n : Nat) : List (BitVec 8) := List.replicate n 0

private def r3 : Option W := some (.word 4386)
private def r4 : Option W := some (.loc 1 0)
private def miss : Res × Nat × List HolIoEvent × Option W × Option W × Option W × Nat :=
  (.error, 0, [], r3, r4, none, 0)

/-- All 15 rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("store", proj (shMemOp .store 3 8 s0) ==
      (.none, 1, [ev .mappedWrite 0 (([34, 17] ++ z 6) ++ [8] ++ z 7)], r3, r4, none, 0)),
   ("load", proj (shMemOp .load 5 8 s0) ==
      (.none, 1, [ev .mappedRead 0 ([8] ++ z 7)], r3, r4, some (.word 0x0101010101010109), 0)),
   ("store8", proj (shMemOp .store8 3 9 s0) ==
      (.none, 1, [ev .mappedWrite 1 ([34, 9] ++ z 7)], r3, r4, none, 0)),
   ("load8", proj (shMemOp .load8 5 9 s0) ==
      (.none, 1, [ev .mappedRead 1 ([9] ++ z 7)], r3, r4, some (.word 0x010101010101010A), 0)),
   ("store16", proj (shMemOp .store16 3 10 s0) ==
      (.none, 1, [ev .mappedWrite 2 ([34, 17, 10] ++ z 7)], r3, r4, none, 0)),
   ("load16", proj (shMemOp .load16 5 10 s0) ==
      (.none, 1, [ev .mappedRead 2 ([10] ++ z 7)], r3, r4, some (.word 0x010101010101010B), 0)),
   ("store32", proj (shMemOp .store32 3 12 s0) ==
      (.none, 1, [ev .mappedWrite 4 ([34, 17, 0, 0, 12] ++ z 7)], r3, r4, none, 0)),
   ("load32", proj (shMemOp .load32 5 12 s0) ==
      (.none, 1, [ev .mappedRead 4 ([12] ++ z 7)], r3, r4, some (.word 0x010101010101010D), 0)),
   ("load_outside", proj (shMemOp .load 5 16 s0) == miss),
   ("store8_outside", proj (shMemOp .store8 3 17 s0) == miss),
   ("load_word_unaligned", proj (shMemOp .load 5 9 s0) == miss),
   ("store_word_unaligned", proj (shMemOp .store 3 9 s0) == miss),
   ("load_final", proj (shMemOp .load 5 8 { s0 with ffi := divFfi }) ==
      (.final (.sharedMem .mappedRead) [0] ([8] ++ z 7) .diverged, 0, [], r3, r4, none, 0)),
   ("store_final", proj (shMemOp .store 3 8 { s0 with ffi := divFfi }) ==
      (.final (.sharedMem .mappedWrite) [0] (([34, 17] ++ z 6) ++ [8] ++ z 7) .diverged,
        0, [], r3, r4, none, 0)),
   ("store_loc", proj (shMemOp .store 4 8 s0) == miss)]

#guard rows.all (·.2)

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 15 then
    IO.println "PASS exact StackSem sh_mem_*/sh_mem_op match all 15 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL StackSem shared-memory HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.StackSemShMemParity
