import Flapjack.Compiler.Backend.Semantics.StackSem.StoreConsts

/-! Kernel replay of all five original HOL observations in
`scripts/hol-probes/stacksem_store_const_sem_probe.out`, generated by
`stacksem_store_const_sem_probeScript.sml` from
`cakeml/compiler/backend/semantics/stackSemScript.sml:729-741`.

The 64-bit fixture fixes registers `0 -> 0xAAw`, `1 -> 0w` (copy index),
`2 -> 0x100w` (destination), `3 -> 0x10w` (offset), `4 -> 0xDEADw`,
`5 -> 0xBEEFw`, `mdomain = UNIV`, memory default `Word 0w`, and the two-word
bitmap list `[0x03w; 0x55w]` with `use_alloc = T`. The successful rows observe
the copy of pattern `0x03` (relocating `0x100w` to `bitmaps[1] + off = 0x65w`
and returning `0x100w + bytes_in_word = 0x108w`), the stores of `1` into `t1`,
`t2` and register `1`, the returned address in register `2`, and the
`unset_var 0` arm (`use_alloc = T` removes register `0`; `use_alloc = F` keeps
it). The remaining rows observe the duplicate-register guard, a non-word
operand, and the `copy_words` `NONE` arm. -/

namespace Flapjack.Test.StackSemStoreConstSemParity

open Flapjack Flapjack.StackSemStoreConsts

private abbrev W := WordLocW 64

private def w64 (n : Nat) : BitVec 64 := BitVec.ofNat 64 n

private def ffi0 : HolFfiState Nat :=
  { oracle := fun _ _ _ _ => .final .diverged, ffiState := 0, ioEvents := [] }

/-- Probe registers `0 -> 0xAAw`, `1 -> 0w`, `2 -> 0x100w`, `3 -> 0x10w`,
    `4 -> 0xDEADw`, `5 -> 0xBEEFw`. -/
private def regs0 : HolFiniteMapExact Nat W :=
  let m0 : HolFiniteMapExact Nat W := HolFiniteMapExact.empty
  let m1 := m0.updateEq (0, .word (w64 0xAA))
  let m2 := m1.updateEq (1, .word (w64 0))
  let m3 := m2.updateEq (2, .word (w64 0x100))
  let m4 := m3.updateEq (3, .word (w64 0x10))
  let m5 := m4.updateEq (4, .word (w64 0xDEAD))
  m5.updateEq (5, .word (w64 0xBEEF))

/-- Concrete base state of the probe: `mdomain = UNIV`, memory default `Word 0w`,
    bitmaps `[0x03w; 0x55w]`, and `use_alloc = T`. -/
private def s0 : StackSemStateFiniteExact 64 Nat Nat where
  regs := regs0
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := []
  stackSpace := 0
  memory := fun _ => .word 0
  mdomain := fun _ => true
  shMdomain := fun _ => false
  bitmaps := [w64 0x03, w64 0x55]
  compile := fun _ _ => none
  compileOracle := fun _ => (0, [], [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  useStack := false
  useStore := false
  useAlloc := true
  clock := 5
  code := .ln
  ffi := ffi0
  ffiSaveRegs := fun _ => false
  be := false

/-- Result view: distinguishes the three observed result shapes. -/
private inductive RView where
  | none
  | error
  | other
  deriving DecidableEq

private def resView : Option (StackSemResult 64) → RView
  | none => .none
  | some .error => .error
  | some _ => .other

/-- Named projection of the observed result, registers, memory cells, and flag.
    A structure (not a wide tuple) keeps `DecidableEq` synthesis shallow. -/
private structure View where
  result : RView
  reg0 : Option W
  reg1 : Option W
  reg2 : Option W
  reg4 : Option W
  reg5 : Option W
  mem100 : W
  mem108 : W
  mem200 : W
  useAlloc : Bool
  deriving DecidableEq

private def viewOf (p : Option (StackSemResult 64) × StackSemStateFiniteExact 64 Nat Nat) : View where
  result := resView p.1
  reg0 := p.2.regs.lookup 0
  reg1 := p.2.regs.lookup 1
  reg2 := p.2.regs.lookup 2
  reg4 := p.2.regs.lookup 4
  reg5 := p.2.regs.lookup 5
  mem100 := p.2.memory (w64 0x100)
  mem108 := p.2.memory (w64 0x108)
  mem200 := p.2.memory (w64 0x200)
  useAlloc := p.2.useAlloc

/-- All five rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("guard_duplicate",
    viewOf (storeConstSem 1 5 s0) ==
      { result := .error, reg0 := some (.word (w64 0xAA)), reg1 := some (.word (w64 0)),
        reg2 := some (.word (w64 0x100)), reg4 := some (.word (w64 0xDEAD)),
        reg5 := some (.word (w64 0xBEEF)), mem100 := .word 0, mem108 := .word 0,
        mem200 := .word 0, useAlloc := true }),
   ("non_word_operand",
    viewOf (storeConstSem 4 5 { s0 with regs := s0.regs.updateEq (1, .loc 9 9) }) ==
      { result := .error, reg0 := some (.word (w64 0xAA)), reg1 := some (.loc 9 9),
        reg2 := some (.word (w64 0x100)), reg4 := some (.word (w64 0xDEAD)),
        reg5 := some (.word (w64 0xBEEF)), mem100 := .word 0, mem108 := .word 0,
        mem200 := .word 0, useAlloc := true }),
   ("copy_words_none",
    viewOf (storeConstSem 4 5 { s0 with bitmaps := [] }) ==
      { result := .error, reg0 := some (.word (w64 0xAA)), reg1 := some (.word (w64 0)),
        reg2 := some (.word (w64 0x100)), reg4 := some (.word (w64 0xDEAD)),
        reg5 := some (.word (w64 0xBEEF)), mem100 := .word 0, mem108 := .word 0,
        mem200 := .word 0, useAlloc := true }),
   ("success_use_alloc_true",
    viewOf (storeConstSem 4 5 s0) ==
      { result := .none, reg0 := none, reg1 := some (.word (w64 1)),
        reg2 := some (.word (w64 0x108)), reg4 := some (.word (w64 1)),
        reg5 := some (.word (w64 1)), mem100 := .word (w64 0x65), mem108 := .word 0,
        mem200 := .word 0, useAlloc := true }),
   ("success_use_alloc_false",
    viewOf (storeConstSem 4 5 { s0 with useAlloc := false }) ==
      { result := .none, reg0 := some (.word (w64 0xAA)), reg1 := some (.word (w64 1)),
        reg2 := some (.word (w64 0x108)), reg4 := some (.word (w64 1)),
        reg5 := some (.word (w64 1)), mem100 := .word (w64 0x65), mem108 := .word 0,
        mem200 := .word 0, useAlloc := false })]

#guard rows.all (·.2)

/-- Kernel regression pin of the `use_alloc = T` success row, stated as a proof
    so the reducer checks the projection rather than only the boolean compare. -/
example : viewOf (storeConstSem 4 5 s0) =
    { result := .none, reg0 := none, reg1 := some (.word (w64 1)),
      reg2 := some (.word (w64 0x108)), reg4 := some (.word (w64 1)),
      reg5 := some (.word (w64 1)), mem100 := .word (w64 0x65), mem108 := .word 0,
      mem200 := .word 0, useAlloc := true } := by
  decide +kernel

/-- Kernel regression pin of the `use_alloc = F` success row, whose register `0`
    survives the update. -/
example : viewOf (storeConstSem 4 5 { s0 with useAlloc := false }) =
    { result := .none, reg0 := some (.word (w64 0xAA)), reg1 := some (.word (w64 1)),
      reg2 := some (.word (w64 0x108)), reg4 := some (.word (w64 1)),
      reg5 := some (.word (w64 1)), mem100 := .word (w64 0x65), mem108 := .word 0,
      mem200 := .word 0, useAlloc := false } := by
  decide +kernel

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 5 then
    IO.println "PASS exact StackSem store_const_sem matches all 5 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL StackSem store_const_sem HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.StackSemStoreConstSemParity