import Flapjack.Compiler.Backend.StackRemove.CopyLoop

/-! Kernel replays of fully expanded original copy constructors; no extra HOL theorem port. -/

namespace Flapjack.Test.StackRemoveCopyLoop

open Flapjack.Compiler.Backend.StackRemove Flapjack.Compiler.Backend.StackLang

-- copy_each_1_0_0
example : copyEach (width := 1) 0 0 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0))) : HolProg 1) := by rfl

-- copy_loop_1_0_0
example : copyLoop (width := 1) 0 0 = ((.seq (.inst (.mem .load 1 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 1 0))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 0 0))) (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 1 0))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0)))))) : HolProg 1) := by rfl

-- copy_each_1_5_6
example : copyEach (width := 1) 5 6 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0))) : HolProg 1) := by rfl

-- copy_loop_1_5_6
example : copyLoop (width := 1) 5 6 = ((.seq (.inst (.mem .load 1 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 1 0))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 6 0))) (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 1 0))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0)))))) : HolProg 1) := by rfl

-- copy_each_1_1234_1234
example : copyEach (width := 1) 1234 1234 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0))) : HolProg 1) := by rfl

-- copy_loop_1_1234_1234
example : copyLoop (width := 1) 1234 1234 = ((.seq (.inst (.mem .load 1 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 1 0))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 1234 0))) (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 1 0))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 1 0))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 1 0)))))))))) (.break 0)))))) : HolProg 1) := by rfl

-- copy_each_8_0_0
example : copyEach (width := 8) 0 0 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0))) : HolProg 8) := by rfl

-- copy_loop_8_0_0
example : copyLoop (width := 8) 0 0 = ((.seq (.inst (.mem .load 1 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 8 1))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 0 0))) (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 8 1))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0)))))) : HolProg 8) := by rfl

-- copy_each_8_5_6
example : copyEach (width := 8) 5 6 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0))) : HolProg 8) := by rfl

-- copy_loop_8_5_6
example : copyLoop (width := 8) 5 6 = ((.seq (.inst (.mem .load 1 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 8 1))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 6 0))) (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 8 1))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0)))))) : HolProg 8) := by rfl

-- copy_each_8_1234_1234
example : copyEach (width := 8) 1234 1234 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0))) : HolProg 8) := by rfl

-- copy_loop_8_1234_1234
example : copyLoop (width := 8) 1234 1234 = ((.seq (.inst (.mem .load 1 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 8 1))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 1234 0))) (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 8 1))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 8 1))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 8 1)))))))))) (.break 0)))))) : HolProg 8) := by rfl

-- copy_each_32_0_0
example : copyEach (width := 32) 0 0 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0))) : HolProg 32) := by rfl

-- copy_loop_32_0_0
example : copyLoop (width := 32) 0 0 = ((.seq (.inst (.mem .load 1 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 32 4))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 0 0))) (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 32 4))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0)))))) : HolProg 32) := by rfl

-- copy_each_32_5_6
example : copyEach (width := 32) 5 6 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0))) : HolProg 32) := by rfl

-- copy_loop_32_5_6
example : copyLoop (width := 32) 5 6 = ((.seq (.inst (.mem .load 1 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 32 4))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 6 0))) (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 32 4))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0)))))) : HolProg 32) := by rfl

-- copy_each_32_1234_1234
example : copyEach (width := 32) 1234 1234 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0))) : HolProg 32) := by rfl

-- copy_loop_32_1234_1234
example : copyLoop (width := 32) 1234 1234 = ((.seq (.inst (.mem .load 1 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 32 4))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 1234 0))) (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 32 4))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 32 4))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 32 4)))))))))) (.break 0)))))) : HolProg 32) := by rfl

-- copy_each_64_0_0
example : copyEach (width := 64) 0 0 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0))) : HolProg 64) := by rfl

-- copy_loop_64_0_0
example : copyLoop (width := 64) 0 0 = ((.seq (.inst (.mem .load 1 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 64 8))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 0 0))) (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 64 8))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0)))))) : HolProg 64) := by rfl

-- copy_each_64_5_6
example : copyEach (width := 64) 5 6 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0))) : HolProg 64) := by rfl

-- copy_loop_64_5_6
example : copyLoop (width := 64) 5 6 = ((.seq (.inst (.mem .load 1 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 64 8))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 6 0))) (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 64 8))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0)))))) : HolProg 64) := by rfl

-- copy_each_64_1234_1234
example : copyEach (width := 64) 1234 1234 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0))) : HolProg 64) := by rfl

-- copy_loop_64_1234_1234
example : copyLoop (width := 64) 1234 1234 = ((.seq (.inst (.mem .load 1 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 64 8))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 1234 0))) (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 64 8))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 64 8))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 64 8)))))))))) (.break 0)))))) : HolProg 64) := by rfl

-- copy_each_80_0_0
example : copyEach (width := 80) 0 0 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0))) : HolProg 80) := by rfl

-- copy_loop_80_0_0
example : copyLoop (width := 80) 0 0 = ((.seq (.inst (.mem .load 1 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 80 10))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 0 0))) (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 80 10))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 0 (.addr 0 0))) (.seq (.inst (.arith (.binop .add 0 0 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 0 0 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 0 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0)))))) : HolProg 80) := by rfl

-- copy_each_80_5_6
example : copyEach (width := 80) 5 6 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0))) : HolProg 80) := by rfl

-- copy_loop_80_5_6
example : copyLoop (width := 80) 5 6 = ((.seq (.inst (.mem .load 1 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 80 10))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 6 0))) (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 80 10))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 5 (.addr 6 0))) (.seq (.inst (.arith (.binop .add 6 6 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 5 5 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 5 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0)))))) : HolProg 80) := by rfl

-- copy_each_80_1234_1234
example : copyEach (width := 80) 1234 1234 = ((.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0))) : HolProg 80) := by rfl

-- copy_loop_80_1234_1234
example : copyLoop (width := 80) 1234 1234 = ((.seq (.inst (.mem .load 1 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 80 10))))) (.seq (.loop (.ite .less 1 (.imm 0) (.seq (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0))) (.seq (.inst (.mem .load 1 (.addr 1234 0))) (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 80 10))))))) (.break 0))) (.loop (.ite .notEqual 1 (.imm 1) (.seq (.inst (.mem .load 1234 (.addr 1234 0))) (.seq (.inst (.arith (.binop .add 1234 1234 (.imm (BitVec.ofNat 80 10))))) (.seq (.ite .test 1 (.imm 1) .skip (.inst (.arith (.binop .add 1234 1234 (.reg 3))))) (.seq (.inst (.arith (.shift .lsr 1 1 (.imm 1)))) (.seq (.inst (.mem .store 1234 (.addr 2 0))) (.inst (.arith (.binop .add 2 2 (.imm (BitVec.ofNat 80 10)))))))))) (.break 0)))))) : HolProg 80) := by rfl

end Flapjack.Test.StackRemoveCopyLoop
