import Flapjack.Compiler.Backend.Semantics.WordSem.State

/-!
Direct HOL oracle rows for the exact wordSem carrier helpers
(`scripts/hol-probes/word_sem_carriers_probe.out`, generated by
`word_sem_carriers_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:15-37, 230-237`).
-/

namespace Flapjack.Test.WordSemCarriersParity

open Flapjack

private def cb : WordSemBuffer 64 8 := { position := 8, buffer := [1, 2], spaceLeft := 3 }

private def view (b : WordSemBuffer 64 8) : BitVec 64 × List (BitVec 8) × Nat :=
  (b.position, b.buffer, b.spaceLeft)

/-- `buffer_flush_hit=SOME ([1w; 2w],<|position := 10w; buffer := []; space_left := 3|>)` -/
def bufferFlushHit : Bool :=
  (wordSemBufferFlush cb 8 10).map (fun (l, b) => (l, view b)) == some ([1, 2], (10, [], 3))
/-- `buffer_flush_miss=NONE` -/
def bufferFlushMiss : Bool := (wordSemBufferFlush cb 8 11).isNone
/-- `buffer_write_hit=SOME <|position := 8w; buffer := [1w; 2w; 5w]; space_left := 2|>` -/
def bufferWriteHit : Bool := (wordSemBufferWrite cb 10 5).map view == some (8, [1, 2, 5], 2)
/-- `buffer_write_miss=NONE` -/
def bufferWriteMiss : Bool := (wordSemBufferWrite cb 9 5).isNone
/-- `stack_size_two=SOME 10` -/
def stackSizeTwo : Bool :=
  wordSemStackSize (width := 64)
    [.stackFrame (some 2) [] [] none, .stackFrame (some 4) [] [] (some (1, 2, 3))] == some 10
/-- `stack_size_unbounded=NONE` -/
def stackSizeUnbounded : Bool :=
  wordSemStackSize (width := 64)
    [.stackFrame (some 2) [] [] none, .stackFrame none [] [] none] == none

#guard bufferFlushHit
#guard bufferFlushMiss
#guard bufferWriteHit
#guard bufferWriteMiss
#guard stackSizeTwo
#guard stackSizeUnbounded

def runChecks : IO Bool := do
  let ok := bufferFlushHit && bufferFlushMiss && bufferWriteHit && bufferWriteMiss &&
    stackSizeTwo && stackSizeUnbounded
  if ok then
    IO.println "PASS wordSem buffer_flush/buffer_write/stack_size match all 6 HOL oracle rows"
  else
    IO.println "FAIL wordSem carrier helper HOL oracle rows"
  pure ok

end Flapjack.Test.WordSemCarriersParity
