import Flapjack.Compiler.Backend.Semantics.WordSem.Accessors

/-!
Direct HOL oracle rows for the exact wordSem state accessors
(`scripts/hol-probes/word_sem_accessors_probe.out`, generated by
`word_sem_accessors_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:37-68, 262-372, 707-714,
941-944`).  The HOL probe evaluates record updates of a free state `s`, so
each state row is a kernel-checked theorem over an arbitrary base state.
-/

namespace Flapjack.Test.WordSemAccessorsParity

open Flapjack
open Flapjack.WordSemStateFiniteExact

/-- Original theWord Word clauses at widths 1 and 64; no Loc oracle exists. -/
example : wordSemTheWord (.word (1 : BitVec 1)) = 1 := rfl
example : wordSemTheWord (.word (18446744073709551615 : BitVec 64)) =
    18446744073709551615 := rfl

/-- Original get_word Word clauses at widths 32 and 80. -/
example : wordSemGetWord (.word (2147483648 : BitVec 32)) = 2147483648 := rfl
example : wordSemGetWord (.word (1208925819614629174706175 : BitVec 80)) =
    1208925819614629174706175 := rfl

/-- The probe's `st`: `s` with the given `locals`, `store`, `fp_regs`,
    `memory` and `mdomain := {8w}`. -/
private def st {C : Type} {F : Type} (s : WordSemStateFiniteExact 64 C F) :
    WordSemStateFiniteExact 64 C F :=
  { s with
    locals := sptInsert 1 (.word 5) (sptInsert 2 (.loc 4 0) .ln)
    store := HolFiniteMapExact.empty.updateEq (.nextFree, .word 7)
    fpRegs := HolFiniteMapExact.empty.updateEq (3, 11)
    memory := fun a => if a = 8 then .word 9 else .loc 0 0
    mdomain := fun a => decide (a = 8) }

/-- `cmp_equal=SOME T` … `cmp_equal_loc=NONE` and `fwd_ptr_*`. -/
def pureRows : Bool :=
  wordSemWordCmp .equal (.word 3 : WordLocW 64) (.word 3) == some true &&
  wordSemWordCmp .less (.word (-1) : WordLocW 64) (.word 0) == some true &&
  wordSemWordCmp .lower (.word (-1) : WordLocW 64) (.word 0) == some false &&
  wordSemWordCmp .test (.loc 3 0 : WordLocW 64) (.word 1) == some true &&
  wordSemWordCmp .notTest (.loc 3 0 : WordLocW 64) (.word 1) == some false &&
  wordSemWordCmp .test (.loc 3 1 : WordLocW 64) (.word 1) == none &&
  wordSemWordCmp .test (.loc 3 0 : WordLocW 64) (.word 2) == none &&
  wordSemWordCmp .equal (.loc 1 2 : WordLocW 64) (.loc 1 2) == none &&
  wordSemIsFwdPtr (.word 8 : WordLocW 64) == true &&
  wordSemIsFwdPtr (.word 9 : WordLocW 64) == false &&
  wordSemIsFwdPtr (.loc 0 0 : WordLocW 64) == false

#guard pureRows

/-- Unfold the accessors and evaluate the concrete remainder. -/
local macro "wsa_simp" : tactic => `(tactic| simp (config := { decide := true }) [st, wordExp,
  getVar, WordSemStateFiniteExact.getVars, unsetVar, setVars, getStore, setStore, getFpVar,
  setFpVar, memLoad, memStore, flushState, WordSemStateFiniteExact.getVarImm, fixClock,
  sptLookup, sptInsert, sptDelete, sptMkBN, sptMkBS, LoopSemStateFiniteExact.sptAlistInsert,
  HolFiniteMapExact.updateEq, HolFiniteMapExact.empty, FUPDATE_HOL, theWords, wordOpHOL,
  wordOp, wordShiftHOL])

variable {C : Type} {F : Type} (s : WordSemStateFiniteExact 64 C F)

/-- `exp_op=SOME (Word 13w)` -/
theorem expOp : wordExp (st s) (.op .add [.var 1, .lookup .nextFree, .const 1]) =
    some (.word 13) := by
  wsa_simp
/-- `exp_op_loc=NONE` -/
theorem expOpLoc : wordExp (st s) (.op .add [.var 1, .var 2]) = none := by
  wsa_simp
/-- `exp_load_hit=SOME (Word 9w)` -/
theorem expLoadHit : wordExp (st s) (.load (.const 8)) = some (.word 9) := by
  wsa_simp
/-- `exp_load_miss=NONE` -/
theorem expLoadMiss : wordExp (st s) (.load (.const 16)) = none := by
  wsa_simp
/-- `exp_shift=SOME (Word 40w)` -/
theorem expShift : wordExp (st s) (.shift .lsl (.var 1) (.const 3)) = some (.word 40) := by
  wsa_simp
/-- `exp_shift_big=NONE` -/
theorem expShiftBig : wordExp (st s) (.shift .lsl (.var 1) (.const 64)) = none := by
  wsa_simp
/-- `get_vars_hit=SOME [Loc 4 0; Word 5w]` -/
theorem getVarsHit : WordSemStateFiniteExact.getVars [2, 1] (st s) = some [.loc 4 0, .word 5] := by wsa_simp
/-- `get_vars_miss=NONE` -/
theorem getVarsMiss : WordSemStateFiniteExact.getVars [1, 3] (st s) = none := by wsa_simp
/-- `unset_var=NONE` -/
theorem unsetVarRow : getVar 1 (unsetVar 1 (st s)) = none := by wsa_simp
/-- `set_vars=SOME [Word 3w; Word 2w]` -/
theorem setVarsRow : WordSemStateFiniteExact.getVars [1, 6] (setVars [6, 1] [.word 2, .word 3] (st s)) =
    some [.word 3, .word 2] := by wsa_simp
/-- `set_store=SOME (Word 4w)` -/
theorem setStoreRow : getStore .handler (setStore .handler (.word 4) (st s)) =
    some (.word 4) := by wsa_simp
/-- `flush_true=NONE` -/
theorem flushTrue : getStore .nextFree (flushState true (st s)) = none := by wsa_simp
/-- `flush_false=SOME (Word 7w)` -/
theorem flushFalse : getStore .nextFree (flushState false (st s)) = some (.word 7) := by wsa_simp
/-- `flush_locals=NONE` -/
theorem flushLocals : getVar 1 (flushState false (st s)) = none := by wsa_simp
/-- `fp_var=SOME 11w` -/
theorem fpVar : getFpVar 3 (setFpVar 4 12 (st s)) = some 11 := by wsa_simp
/-- `fix_clock=(5,3,7)` -/
theorem fixClockRow :
    (fun (p : Nat × WordSemStateFiniteExact 64 C F) => (p.1, p.2.clock, p.2.termdep))
      (fixClock { s with clock := 3, termdep := 7 } (5, { s with clock := 9, termdep := 2 })) =
    (5, 3, 7) := by wsa_simp
/-- `mem_store_miss=T` -/
theorem memStoreMiss : memStore 16 (.word 1) (st s) = none := by wsa_simp
/-- `mem_store_hit=SOME (Word 1w)` -/
theorem memStoreHit : (memStore 8 (.word 1) (st s)).map (fun t => t.memory 8) =
    some (.word 1) := by wsa_simp
/-- `var_imm=SOME (Word 4w)` -/
theorem varImm : WordSemStateFiniteExact.getVarImm (.imm 4) (st s) = some (.word 4) := by wsa_simp
/-- `var_imm_reg=SOME (Loc 4 0)` -/
theorem varImmReg : WordSemStateFiniteExact.getVarImm (.reg 2) (st s) = some (.loc 4 0) := by wsa_simp

def runChecks : IO Bool := do
  if pureRows then
    IO.println "PASS wordSem accessors match all 31 HOL oracle rows (20 kernel-checked over a free state)"
  else
    IO.println "FAIL wordSem accessor HOL oracle rows"
  pure pureRows

end Flapjack.Test.WordSemAccessorsParity
