import Flapjack.Compiler.Backend.Semantics.WordSem.Alloc

/-!
Direct HOL oracle rows for the exact wordSem code lookup, GC and allocation
helpers (`scripts/hol-probes/word_sem_alloc_probe.out`, generated by
`word_sem_alloc_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:614-705`).  The HOL
probe updates fields of a free state `s`; the Lean rows update the same
fields of a concrete base state `s0`, which is one instance of that `s`.
-/

namespace Flapjack.Test.WordSemAllocParity

open Flapjack
open Flapjack.WordSemStateFiniteExact

private abbrev W := WordLocW 64
private abbrev P := WordLangProgHOL (BitVec 64)

private def s0 : WordSemStateFiniteExact 64 Unit Unit where
  locals := .ln
  localsSize := none
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := []
  stackLimit := 0
  stackMax := none
  stackSize := .ln
  memory := fun _ => .word 0
  mdomain := fun _ => false
  shMdomain := fun _ => false
  permute := fun _ i => i
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  handler := 0
  clock := 0
  termdep := 0
  code := .ln
  be := false
  ffi := { oracle := fun _ state _ _ => .ret state [], ffiState := (), ioEvents := [] }

private def code : Spt (Nat × P) := sptInsert 5 (1, .skip) (sptInsert 3 (2, .tick) .ln)
private def ssize : Spt Nat := sptInsert 5 7 .ln

private def progView : P → Nat
  | .skip => 0
  | .tick => 1
  | _ => 2

private def fcView : Option (List W × P × Option Nat) → Option (List W × Nat × Option Nat)
  | some (a, p, n) => some (a, progView p, n)
  | none => none

private def frameView : WordSemStackFrame 64 →
    Option Nat × List (Nat × W) × List (Nat × W) × Option (Nat × Nat × Nat)
  | .stackFrame n l0 l h => (n, l0, l, h)

private def stk : List (WordSemStackFrame 64) :=
  [.stackFrame (some 1) [(9, .word 9)] [(2, .word 1), (4, .loc 1 0)] none,
   .stackFrame none [] [(6, .word 3)] (some (1, 2, 3))]

private def names (keys : List Nat) : WordLangNumSetHOL :=
  keys.foldr (fun k t => sptInsert k () t) .ln

private def store0 : HolFiniteMapExact WordStoreHOL W :=
  (HolFiniteMapExact.empty.updateEq (.nextFree, .word 8)).updateEq (.triggerGC, .word 24)

private def st : WordSemStateFiniteExact 64 Unit Unit := { s0 with store := store0 }

private def gcRev : WordSemGcFun 64 := fun (wl, m, _, store) => some (wl.reverse, m, store)
private def gcId : WordSemGcFun 64 := fun (wl, m, _, store) => some (wl, m, store)

private def ast : WordSemStateFiniteExact 64 Unit Unit :=
  { st with locals := sptInsert 2 (.word 5) (sptInsert 4 (.loc 1 0) .ln), stack := [],
            localsSize := some 3, stackMax := none, permute := fun _ i => i,
            gcFun := gcId }

private def proj (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Unit) :
    Option Nat × List (Nat × W) × Nat × Option W :=
  let tag : Option (WordSemResult 64) → Option Nat
    | none => none
    | some .notEnoughSpace => some 1
    | some .error => some 2
    | some _ => some 3
  (tag r.1, sptToAList r.2.locals, r.2.stack.length, getStore .allocSize r.2)

/-- All 24 rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("find_code_some", fcView (wordSemFindCode (some 3) [(.word 1 : W), .word 2] code ssize) ==
      some ([.word 1, .word 2], 1, none)),
   ("find_code_some_arity", (wordSemFindCode (some 3) [(.word 1 : W)] code ssize).isNone),
   ("find_code_some_missing", (wordSemFindCode (some 4) ([] : List W) code ssize).isNone),
   ("find_code_none_nil", (wordSemFindCode none ([] : List W) code ssize).isNone),
   ("find_code_none_loc", fcView (wordSemFindCode none [(.word 1 : W), .loc 5 0] code ssize) ==
      some ([.word 1], 0, some 7)),
   ("find_code_none_offset", (wordSemFindCode none [(.word 1 : W), .loc 5 1] code ssize).isNone),
   ("find_code_none_arity", (wordSemFindCode none [(.loc 5 0 : W)] code ssize).isNone),
   ("find_code_none_word", (wordSemFindCode none [(.word 5 : W)] code ssize).isNone),
   ("enc_stack", wordSemEncStack stk == [.word 1, .loc 1 0, .word 3]),
   ("dec_stack_hit", (wordSemDecStack [.word 7, .word 8, .loc 3 3] stk).map (·.map frameView) ==
      some [(some 1, [(9, .word 9)], [(2, .word 7), (4, .word 8)], none),
            (none, [], [(6, .loc 3 3)], some (1, 2, 3))]),
   ("dec_stack_short", (wordSemDecStack [.word 7, .word 8] stk).isNone),
   ("dec_stack_extra", (wordSemDecStack [.word 7, .word 8, .loc 3 3, .word 0] stk).isNone),
   ("gc_rev", (gc { s0 with stack := stk, gcFun := gcRev }).map (·.stack.map frameView) ==
      some [(some 1, [(9, .word 9)], [(2, .word 3), (4, .loc 1 0)], none),
            (none, [], [(6, .word 1)], some (1, 2, 3))]),
   ("gc_fail", (gc { s0 with stack := stk, gcFun := fun _ => none }).isNone),
   ("has_space_yes", hasSpace (.word 16) st == some true),
   ("has_space_no", hasSpace (.word 17) st == some false),
   ("has_space_loc", (hasSpace (.loc 0 0) st).isNone),
   ("has_space_missing", (hasSpace (.word 1) { s0 with store := HolFiniteMapExact.empty }).isNone),
   ("alloc_ok", proj (alloc 16 (names [2], names [4]) ast) ==
      (none, [(4, .loc 1 0), (2, .word 5)], 0, some (.word 16))),
   ("alloc_space", proj (alloc 17 (names [2], .ln) ast) == (some 1, [], 0, none)),
   ("alloc_cut", proj (alloc 16 (names [3], .ln) ast) == (some 2, [], 0, none)),
   ("alloc_gc", proj (alloc 16 (.ln, .ln) { ast with gcFun := fun _ => none }) ==
      (some 2, [], 0, none)),
   ("assign", (assign 1 (.op .add [.var 2, .const 3]) { s0 with locals := sptInsert 2 (.word 5) .ln }).map
      (fun t => sptToAList t.locals) == some [(1, .word 8), (2, .word 5)]),
   ("assign_fail", (assign 1 (.var 9) { s0 with locals := .ln }).isNone)]

#guard rows.all (·.2)

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 24 then
    IO.println "PASS wordSem find_code/enc_stack/dec_stack/gc/has_space/alloc/assign match all 24 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL wordSem code/GC/alloc HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.WordSemAllocParity
