import Flapjack.Misc.ShiftSeq
import Flapjack.Compiler.Backend.Semantics.WordSem.Domain

/-!
Direct HOL oracle rows for the wordSem `evaluate_def` prerequisites
(`scripts/hol-probes/word_sem_eval_prereq_probe.out`, generated by
`word_sem_eval_prereq_probeScript.sml`): `misc$shift_seq` and the `sptree`
domain set conditions.  All rows are kernel-checked.
-/

namespace Flapjack.Test.WordSemEvalPrereqParity

open Flapjack

private def units (keys : List Nat) : Spt Unit := keys.foldr (fun k t => sptInsert k () t) .ln

/-- `shift_seq=50` -/
theorem shiftSeq : holShiftSeq 2 (fun i => i * 10) 3 = 50 := by decide +kernel
/-- `shift_seq_zero=11` -/
theorem shiftSeqZero : holShiftSeq 0 (fun i => i + 7) 4 = 11 := by decide +kernel
/-- `dom_empty_ln=T` -/
theorem domEmptyLn : sptDomainEmpty (.ln : Spt Unit) := by decide +kernel
/-- `dom_empty_one=F` -/
theorem domEmptyOne : ¬ sptDomainEmpty (units [3]) := by decide +kernel
/-- `dom_union_eq=T` -/
theorem domUnionEq :
    sptDomainEqUnion (sptFromAList [(1, (5 : Nat)), (2, 6)]) (units [1]) (units [2]) := by
  decide +kernel
/-- `dom_union_extra=F` -/
theorem domUnionExtra :
    ¬ sptDomainEqUnion (sptFromAList [(1, (5 : Nat)), (2, 6), (4, 7)]) (units [1]) (units [2]) := by
  decide +kernel
/-- `dom_union_missing=F` -/
theorem domUnionMissing :
    ¬ sptDomainEqUnion (sptFromAList [(1, (5 : Nat))]) (units [1]) (units [2]) := by
  decide +kernel

def runChecks : IO Bool := do
  IO.println "PASS wordSem evaluate prerequisites shift_seq/domain predicates match all 7 HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.WordSemEvalPrereqParity
