import Flapjack.Compiler.Backend.Semantics.WordSem.Inst

/-!
Direct HOL oracle rows for wordSem `inst_def`
(`scripts/hol-probes/word_sem_inst_probe.out`, generated by
`word_sem_inst_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:716-939`).  The HOL probe
updates fields of a free state `s`; the Lean rows update the same fields of
a concrete base state `s0`.  Each row is a kernel-checked theorem about the
noncomputable `inst`.  It is proved by unfolding `inst`, rewriting the
binary64 operations through their proven computable `roundTiesToEven`
equivalences, and evaluating in the kernel.  HOL prints some results as
unreduced `n2w` literals (for example `0x10000000000000000w`, which is `0w` at
64 bits); the rows keep them verbatim as `BitVec.ofNat 64`.
-/

namespace Flapjack.Test.WordSemInstParity

open Flapjack
open Flapjack.WordSemStateFiniteExact

private def s0 : WordSemStateFiniteExact 64 Unit Unit where
  locals := sptFromAList [(2, .word 17), (3, .word 5), (4, .word 0),
    (10, .word 0xFFFFFFFFFFFFFFFF), (11, .word 1), (12, .word 0x7FFFFFFFFFFFFFFF),
    (13, .word 0x8000000000000000), (14, .word 0x8000000000000000), (15, .word 4),
    (20, .word 1), (21, .word 0), (22, .word 3), (23, .word 5),
    (30, .word 16), (31, .word 0xAB), (32, .loc 1 2)]
  localsSize := none
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := []
  stackLimit := 0
  stackMax := none
  stackSize := .ln
  memory := fun a => if a = 16 then .word 0x1122334455667788 else .loc 0 0
  mdomain := fun a => decide (a = 16)
  shMdomain := fun _ => false
  permute := fun _ i => i
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  handler := 0
  clock := 0
  termdep := 0
  code := .ln
  be := false
  ffi := { oracle := fun _ state _ _ => .ret state [], ffiState := (), ioEvents := [] }

/-- `div=SOME [SOME (Word 3w)]` -/
theorem div : (inst (.arith (.div 1 2 3)) s0).map (fun t => [1].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 3))] := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `div_zero=T` -/
theorem divZero : inst (.arith (.div 1 2 4)) s0 = none := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `add_carry=SOME [SOME (Word 0x10000000000000000w); SOME (Word 1w)]` -/
theorem addCarry : (inst (.arith (.addCarry 1 10 11 4)) s0).map (fun t => [1, 4].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0x10000000000000000)), some (.word (BitVec.ofNat 64 1))] := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `add_overflow=SOME [SOME (Word 0x8000000000000000w); SOME (Word 1w)]` -/
theorem addOverflow : (inst (.arith (.addOverflow 1 12 11 4)) s0).map (fun t => [1, 4].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0x8000000000000000)), some (.word (BitVec.ofNat 64 1))] := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `sub_overflow=SOME [SOME (Word 0x7FFFFFFFFFFFFFFFw); SOME (Word 1w)]` -/
theorem subOverflow : (inst (.arith (.subOverflow 1 13 11 4)) s0).map (fun t => [1, 4].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0x7FFFFFFFFFFFFFFF)), some (.word (BitVec.ofNat 64 1))] := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `long_mul=SOME [SOME (Word 2w); SOME (Word 0x20000000000000000w)]` -/
theorem longMul : (inst (.arith (.longMul 1 2 14 15)) s0).map (fun t => [1, 2].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 2)), some (.word (BitVec.ofNat 64 0x20000000000000000))] := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `long_div=SOME [SOME (Word 0x5555555555555555w); SOME (Word 1w)]` -/
theorem longDiv : (inst (.arith (.longDiv 1 2 20 21 22)) s0).map (fun t => [1, 2].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0x5555555555555555)), some (.word (BitVec.ofNat 64 1))] := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `long_div_big=T` -/
theorem longDivBig : inst (.arith (.longDiv 1 2 23 21 22)) s0 = none := by
  simp only [WordSemStateFiniteExact.inst]
  decide +kernel
/-- `binop_imm=SOME [SOME (Word 22w)]` -/
theorem binopImm : (inst (.arith (.binop .add 1 2 (.imm 5))) s0).map (fun t => [1].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 22))] := by
  simp only [WordSemStateFiniteExact.inst, assign, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `shift_reg=SOME [SOME (Word 0w)]` -/
theorem shiftReg : (inst (.arith (.shift .lsr 1 2 (.reg 3))) s0).map (fun t => [1].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0))] := by
  simp only [WordSemStateFiniteExact.inst, assign, wordExp]
  decide +kernel
/-- `const=SOME [SOME (Word 99w)]` -/
theorem const : (inst (.const 7 99) s0).map (fun t => [7].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 99))] := by
  simp only [WordSemStateFiniteExact.inst, assign, wordExp]
  decide +kernel
/-- `load=SOME [SOME (Word 0x1122334455667788w)]` -/
theorem load : (inst (.mem .load 1 (.addr 30 0)) s0).map (fun t => [1].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0x1122334455667788))] := by
  simp only [WordSemStateFiniteExact.inst, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `load8=SOME [SOME (Word 119w)]` -/
theorem load8 : (inst (.mem .load8 1 (.addr 30 1)) s0).map (fun t => [1].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 119))] := by
  simp only [WordSemStateFiniteExact.inst, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `load32=SOME [SOME (Word 0x11223344w)]` -/
theorem load32 : (inst (.mem .load32 1 (.addr 30 4)) s0).map (fun t => [1].map (fun k => sptLookup k t.locals)) =
    some [some (.word (BitVec.ofNat 64 0x11223344))] := by
  simp only [WordSemStateFiniteExact.inst, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `load_miss=T` -/
theorem loadMiss : inst (.mem .load 1 (.addr 30 8)) s0 = none := by
  simp only [WordSemStateFiniteExact.inst, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `load16=T` -/
theorem load16 : inst (.mem .load16 1 (.addr 30 0)) s0 = none := by
  simp only [WordSemStateFiniteExact.inst]
/-- `store8=SOME (Word 0x1122334455AB7788w)` -/
theorem store8 : (inst (.mem .store8 31 (.addr 30 2)) s0).map (fun t => t.memory 16) = some (.word (BitVec.ofNat 64 0x1122334455AB7788)) := by
  simp only [WordSemStateFiniteExact.inst, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `store=SOME (Loc 1 2)` -/
theorem store : (inst (.mem .store 32 (.addr 30 0)) s0).map (fun t => t.memory 16) = some (.loc 1 2) := by
  simp only [WordSemStateFiniteExact.inst, wordExp, List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  decide +kernel
/-- `store16=T` -/
theorem store16 : inst (.mem .store16 31 (.addr 30 0)) s0 = none := by
  simp only [WordSemStateFiniteExact.inst]
def runChecks : IO Bool := do
  IO.println "PASS wordSem inst_def matches integer HOL oracle rows (kernel-checked)"
  pure true

end Flapjack.Test.WordSemInstParity
