import Flapjack.Compiler.Backend.Semantics.WordSem.ShMem

/-!
Direct HOL oracle rows for the exact wordSem shared-memory helpers
(`scripts/hol-probes/word_sem_sh_mem_probe.out`, generated by
`word_sem_sh_mem_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:374-470`).  The FFI
oracle increments every byte and counts calls, so each recorded `io_event`
pair list is `(b, b + 1)` over the literal payload bytes of the HOL row.  A
second oracle diverges.  The HOL probe updates fields of a free state `s`;
the Lean rows update the same fields of a concrete base state `s0`.
-/

namespace Flapjack.Test.WordSemShMemParity

open Flapjack
open Flapjack.WordSemStateFiniteExact

private abbrev W := WordLocW 64

private def incFfi : HolFfiState Nat :=
  { oracle := fun _ st _ bytes => .ret (st + 1) (bytes.map (· + 1)), ffiState := 0,
    ioEvents := [] }

private def divFfi : HolFfiState Nat :=
  { oracle := fun _ _ _ _ => .final .diverged, ffiState := 0, ioEvents := [] }

private def s0 : WordSemStateFiniteExact 64 Unit Nat where
  locals := sptInsert 3 (.word 0x1122) (sptInsert 4 (.loc 1 0) .ln)
  localsSize := some 9
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := [.stackFrame none [] [] none]
  stackLimit := 0
  stackMax := none
  stackSize := .ln
  memory := fun _ => .word 0
  mdomain := fun _ => false
  shMdomain := fun a => a = 8
  permute := fun _ i => i
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  handler := 0
  clock := 0
  termdep := 0
  code := .ln
  be := false
  ffi := incFfi

/-- The observed result: `none`, `SOME Error`, or `SOME (FinalFFI (Final_event
    name conf bytes outcome))`. -/
private inductive Res where
  | none
  | error
  | final (name : HolFfiName) (conf bytes : List (BitVec 8)) (outcome : HolFfiOutcome)
  | other
  deriving DecidableEq

private def resView : Option (WordSemResult 64) → Res
  | none => .none
  | some .error => .error
  | some (.finalFfi e) => .final e.name e.configuration e.bytes e.outcome
  | some _ => .other

private def proj (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Nat) :
    Res × Nat × List HolIoEvent × List (Nat × W) × Nat :=
  (resView r.1, r.2.ffi.ffiState, r.2.ffi.ioEvents, sptToAList r.2.locals, r.2.stack.length)

private def ev (op : HolShmemOp) (conf : BitVec 8) (bytes : List (BitVec 8)) : HolIoEvent :=
  { name := .sharedMem op, configuration := [conf], bytes := bytes.zip (bytes.map (· + 1)) }

private def z (n : Nat) : List (BitVec 8) := List.replicate n 0

private def locs : List (Nat × W) := [(3, .word 4386), (4, .loc 1 0)]
private def unchanged : Res × Nat × List HolIoEvent × List (Nat × W) × Nat :=
  (.error, 0, [], locs, 1)
private def withV5 (w : BitVec 64) : List (Nat × W) := [(3, .word 4386), (5, .word w), (4, .loc 1 0)]

/-- All 17 rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("store", proj (shareInst .store 3 8 s0) ==
      (.none, 1, [ev .mappedWrite 0 ([34, 17] ++ z 6 ++ [8] ++ z 7)], locs, 1)),
   ("store_outside", proj (shareInst .store 3 16 s0) == unchanged),
   ("store_loc", proj (shareInst .store 4 8 s0) == unchanged),
   ("store_missing", proj (shareInst .store 7 8 s0) == unchanged),
   ("store_final", proj (shareInst .store 3 8 { s0 with ffi := divFfi }) ==
      (.final (.sharedMem .mappedWrite) [0] ([34, 17] ++ z 6 ++ [8] ++ z 7) .diverged,
        0, [], [], 0)),
   ("store8", proj (shareInst .store8 3 9 s0) ==
      (.none, 1, [ev .mappedWrite 1 ([34, 9] ++ z 7)], locs, 1)),
   ("store8_outside", proj (shareInst .store8 3 17 s0) == unchanged),
   ("store16", proj (shareInst .store16 3 10 s0) ==
      (.none, 1, [ev .mappedWrite 2 ([34, 17, 10] ++ z 7)], locs, 1)),
   ("store32", proj (shareInst .store32 3 12 s0) ==
      (.none, 1, [ev .mappedWrite 4 ([34, 17, 0, 0, 12] ++ z 7)], locs, 1)),
   ("store_unaligned", proj (shareInst .store 3 9 s0) == unchanged),
   ("load", proj (shareInst .load 5 8 s0) ==
      (.none, 1, [ev .mappedRead 0 ([8] ++ z 7)], withV5 0x101010101010109, 1)),
   ("load_outside", proj (shareInst .load 5 9 s0) == unchanged),
   ("load8", proj (shareInst .load8 5 9 s0) ==
      (.none, 1, [ev .mappedRead 1 ([9] ++ z 7)], withV5 0x10101010101010A, 1)),
   ("load16", proj (shareInst .load16 5 10 s0) ==
      (.none, 1, [ev .mappedRead 2 ([10] ++ z 7)], withV5 0x10101010101010B, 1)),
   ("load32", proj (shareInst .load32 5 12 s0) ==
      (.none, 1, [ev .mappedRead 4 ([12] ++ z 7)], withV5 0x10101010101010D, 1)),
   ("load_final", proj (shareInst .load 5 8 { s0 with ffi := divFfi }) ==
      (.final (.sharedMem .mappedRead) [0] ([8] ++ z 7) .diverged, 0, [], [], 0)),
   ("sh_mem_set_var_none", proj (shMemSetVar none 5 s0) == unchanged)]

#guard rows.all (·.2)

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty && rows.length == 17 then
    IO.println "PASS wordSem sh_mem_*/sh_mem_set_var/share_inst match all 17 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL wordSem shared-memory HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.WordSemShMemParity
