import Flapjack.Compiler.Backend.Semantics.WordSem.Evaluate

set_option linter.unusedSimpArgs false

/-!
Direct HOL oracle rows for wordSem `evaluate_def`
(`scripts/hol-probes/word_sem_evaluate_probe.out`, generated by
`word_sem_evaluate_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:1016-1260`).  The HOL probe
updates fields of a free state `s`; the Lean rows update the same fields of
a concrete base state `s0`.  Each row compares `(result, toAList locals,
clock)` and is a kernel-checked theorem about the noncomputable `evaluate`.
It is proved by rewriting `evaluate` with its equation lemmas, so that no
well-founded unfolding is left on the evaluated path, and then evaluating in
the kernel.  `Loop` iterations are stepped explicitly through `STOP`, which
stays folded as in HOL.
-/

namespace Flapjack.Test.WordSemEvaluateParity

attribute [local irreducible] Flapjack.wordSemSTOP

open Flapjack
open Flapjack.WordSemStateFiniteExact

private abbrev W := WordLocW 64

/-- A decidable view of `WordSemResult`. -/
private inductive RV where
  | none
  | result (v : W) (vs : List W)
  | exception (v p : W)
  | brk (n : Nat)
  | cont (n : Nat)
  | timeOut
  | notEnoughSpace
  | final
  | error
  deriving DecidableEq

private def rv : Option (WordSemResult 64) → RV
  | none => .none
  | some (.result v vs) => .result v vs
  | some (.exception v p) => .exception v p
  | some (.break n) => .brk n
  | some (.continue n) => .cont n
  | some .timeOut => .timeOut
  | some .notEnoughSpace => .notEnoughSpace
  | some (.finalFfi _) => .final
  | some .error => .error

private def units (keys : List Nat) : Spt Unit := keys.foldr (fun k t => sptInsert k () t) .ln

private def s0 : WordSemStateFiniteExact 64 Unit Nat where
  locals := sptFromAList [(2, .word 7), (3, .loc 5 0), (8, .word 16), (9, .word 1)]
  localsSize := some 0
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := []
  stackLimit := 0
  stackMax := some 0
  stackSize := .ln
  memory := fun _ => .word 0
  mdomain := fun a => decide (a = 16)
  shMdomain := fun _ => false
  permute := fun _ i => i
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  handler := 0
  clock := 3
  termdep := 2
  code := sptFromAList [(5, (1, WordLangProgHOL.return 0 [0])), (6, (2, WordLangProgHOL.return 0 [2]))]
  be := false
  ffi := { oracle := fun _ st _ bytes => .ret (st + 1) bytes, ffiState := 0, ioEvents := [] }

private def view (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Nat) :
    RV × List (Nat × W) × Nat :=
  (rv r.1, sptToAList r.2.locals, r.2.clock)

/-- Unfold `evaluate` through its equation lemmas, reducing the closed
    scrutinees (`ground`) that select each branch.  `STOP` stays folded, as in
    HOL, so each `Loop` iteration is unfolded only by an explicit
    `wordSemSTOP` step. -/
local macro "ev_simp" : tactic => `(tactic| (
  simp (config := { ground := true, decide := true }) only [evaluate]
  repeat (simp only [wordSemSTOP]; simp (config := { ground := true, decide := true }) only [evaluate])
  first | done | decide +kernel))

/-- The `Loop` and `MustTerminate` recipe: unfold `evaluate` with the helper
    definitions its guards need, without ground evaluation (which would try
    to evaluate `MustTerminate_limit`). -/
local macro "ev_simp_nonground" : tactic => `(tactic| (
  simp (config := { decide := true }) only [evaluate, fixClock, wordSemContLoop, wordSemExitLoop,
    cutState, wordSemCutEnv, wordSemCutEnvs, wordSemCutNames, decClock, s0, wordExp, setVar,
    List.attach_cons, List.attach_nil, List.map_cons, List.map_nil]
  repeat (simp only [wordSemSTOP]; simp (config := { decide := true }) only [evaluate, fixClock,
    wordSemContLoop, wordSemExitLoop, cutState, wordSemCutEnv, wordSemCutEnvs, wordSemCutNames,
    decClock])
  first | done | decide +kernel))

/-- `skip=(NONE,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem skip :
    view (evaluate (.skip) (s0)) = (.none, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `seq_tick=(NONE,[(3,Loc 5 0); (1,Word 5w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],2)` -/
theorem seqTick :
    view (evaluate (.seq (.assign 1 (.const 5)) .tick) (s0)) = (.none, [(3, .loc 5 0), (1, .word 5), (9, .word 1), (8, .word 16), (2, .word 7)], 2) := by
  ev_simp
/-- `tick_zero=(SOME TimeOut,[],0)` -/
theorem tickZero :
    view (evaluate (.tick) ({ s0 with clock := 0 })) = (.timeOut, [], 0) := by
  ev_simp
/-- `if_true=(NONE,[(3,Loc 5 0); (1,Word 1w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem ifTrue :
    view (evaluate (.ite .equal 2 (.imm 7) (.assign 1 (.const 1)) (.assign 1 (.const 0))) (s0)) = (.none, [(3, .loc 5 0), (1, .word 1), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `if_false=(NONE,[(3,Loc 5 0); (1,Word 0w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem ifFalse :
    view (evaluate (.ite .less 2 (.imm 7) (.assign 1 (.const 1)) (.assign 1 (.const 0))) (s0)) = (.none, [(3, .loc 5 0), (1, .word 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `if_error=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem ifError :
    view (evaluate (.ite .equal 3 (.imm 7) .skip .skip) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `loop_break=(NONE,[(2,Word 7w)],3)` -/
theorem loopBreak :
    view (evaluate (.loop (units [2]) (.break 0) (units [2])) (s0)) = (.none, [(2, .word 7)], 3) := by
  simp only [evaluate]
  decide +kernel
/-- `loop_timeout=(SOME TimeOut,[],0)` -/
theorem loopTimeout :
    view (evaluate (.loop .ln (.continue 0) .ln) (s0)) = (.timeOut, [], 0) := by
  simp only [evaluate]
  iterate 4 (simp only [wordSemSTOP]; simp only [evaluate])
  decide +kernel
/-- `loop_exit=(SOME (Break 0),[],3)` -/
theorem loopExit :
    view (evaluate (.loop .ln (.break 1) .ln) (s0)) = (.brk 0, [], 3) := by
  simp only [evaluate]
  decide +kernel
/-- `return=(SOME (Result (Loc 5 0) [Word 7w]),[],3)` -/
theorem returnRow :
    view (evaluate (WordLangProgHOL.return 3 [2]) (s0)) = (.result (.loc 5 0) [(.word 7)], [], 3) := by
  ev_simp
/-- `raise_nohandler=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem raiseNohandler :
    view (evaluate (.raise 2) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `raise_handler=(SOME (Exception (Loc 7 8) (Word 7w)),[(4,Word 1w); (6,Word 2w)],3)` -/
theorem raiseHandler :
    view (evaluate (.raise 2) ({ s0 with stack := [.stackFrame (some 1) [(4, .word 1)] [(6, .word 2)] (some (0, 7, 8))] })) = (.exception (.loc 7 8) (.word 7), [(4, .word 1), (6, .word 2)], 3) := by
  ev_simp
/-- `must_terminate_zero=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem mustTerminateZero :
    view (evaluate (.mustTerminate .skip) ({ s0 with termdep := 0 })) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp_nonground
/-- `must_terminate=(NONE,[(3,Loc 5 0); (1,Word 9w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem mustTerminate :
    view (evaluate (.mustTerminate (.assign 1 (.const 9))) (s0)) = (.none, [(3, .loc 5 0), (1, .word 9), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp_nonground
/-- `move=(NONE, [(3,Loc 5 0); (9,Word 1w); (5,Word 7w); (8,Word 16w); (2,Word 7w); (6,Loc 5 0)],3)` -/
theorem move :
    view (evaluate (.move 0 [(5, 2), (6, 3)]) (s0)) = (.none, [(3, .loc 5 0), (9, .word 1), (5, .word 7), (8, .word 16), (2, .word 7), (6, .loc 5 0)], 3) := by
  ev_simp
/-- `move_dup=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem moveDup :
    view (evaluate (.move 0 [(5, 2), (5, 3)]) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `set_get=(NONE,[(3,Loc 5 0); (1,Word 4w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem setGet :
    view (evaluate (.seq (.set .nextFree (.const 4)) (.get 1 .nextFree)) (s0)) = (.none, [(3, .loc 5 0), (1, .word 4), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `set_handler=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem setHandler :
    view (evaluate (.set .handler (.const 1)) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `loc_value=(NONE,[(3,Loc 5 0); (1,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem locValue :
    view (evaluate (.locValue 1 5) (s0)) = (.none, [(3, .loc 5 0), (1, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `loc_value_missing=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem locValueMissing :
    view (evaluate (.locValue 1 4) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `store_consts=(NONE,[(3,Loc 5 0); (9,Word 1w); (8,Word 24w); (2,Word 7w)],3)` -/
theorem storeConsts :
    view (evaluate (.storeConsts 20 21 8 9 [(true, 5)]) (s0)) = (.none, [(3, .loc 5 0), (9, .word 1), (8, .word 24), (2, .word 7)], 3) := by
  ev_simp
/-- `call_tail=(SOME (Result (Loc 5 0) [Loc 5 0]),[],2)` -/
theorem callTail :
    view (evaluate (.call none (some 5) [3] none) (s0)) = (.result (.loc 5 0) [(.loc 5 0)], [], 2) := by
  ev_simp
/-- `call_tail_timeout=(SOME TimeOut,[],0)` -/
theorem callTailTimeout :
    view (evaluate (.call none (some 5) [3] none) ({ s0 with clock := 0 })) = (.timeOut, [], 0) := by
  ev_simp
/-- `call_ret=(NONE,[(3,Loc 5 0); (4,Word 7w); (2,Word 7w)],2)` -/
theorem callRet :
    view (evaluate (.call (some ([4], (units [2], units [3]), .skip, 10, 11)) (some 6) [2] none) (s0)) = (.none, [(3, .loc 5 0), (4, .word 7), (2, .word 7)], 2) := by
  -- the callee is chosen by `find_code`, so its guards are rewritten explicitly
  have h1 : WordSemStateFiniteExact.getVars [2] s0 = some [.word 7] := by decide +kernel
  have h3 : wordSemFindCode (width := 64) (some 6) (wordSemAddRetLoc (some ([4], (units [2], units [3]), .skip, 10, 11))
      [.word 7]) s0.code s0.stackSize = some ([.loc 10 11, .word 7], WordLangProgHOL.return 0 [2], none) := by
    simp (config := { decide := true }) [wordSemFindCode, wordSemAddRetLoc, s0, sptFromAList, sptInsert,
      sptLookup]
  have h4 : wordSemCutEnvs (units [2], units [3]) s0.locals =
      some (.bn (.ls (.word 7)) .ln, .bn .ln (.bn .ln (.ls (.loc 5 0)))) := by decide +kernel
  simp only [evaluate]
  rw [h1]; dsimp only
  rw [if_neg (by decide), h3]; dsimp only
  rw [if_neg (by decide +kernel), h4]; dsimp only
  rw [dif_neg (by decide)]
  rw [evaluate.eq_def]; dsimp only
  decide +kernel
/-- `call_ret_empty_names=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem callRetEmptyNames :
    view (evaluate (.call (some ([4], (.ln, units [3]), .skip, 10, 11)) (some 6) [2] none) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `call_missing=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem callMissing :
    view (evaluate (.call none (some 7) [3] none) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `ffi_missing_len=(SOME Error,[(3,Loc 5 0); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem ffiMissingLen :
    view (evaluate (.ffi ⟨"f".toList.map (fun c => BitVec.ofNat 8 c.toNat)⟩ 8 21 8 21 (units [2], .ln)) (s0)) = (.error, [(3, .loc 5 0), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp
/-- `ffi_ok=(NONE,[(2,Word 7w)],3)` -/
theorem ffiOk :
    view (evaluate (.ffi ⟨"f".toList.map (fun c => BitVec.ofNat 8 c.toNat)⟩ 8 9 8 9 (units [2], .ln)) (s0)) = (.none, [(2, .word 7)], 3) := by
  ev_simp

/-! ## Additional `evaluate_def` clauses (probe rows `alloc_ok`, `store_ok`,
`op_curr_heap`, `share_inst_load`, `code_buffer_write`, `data_buffer_write`,
`install_ok`, `call_handler_exception`). -/

/-- A decidable view of `(result, memory at 16, memory at 17, clock)`. -/
private def viewStore (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Nat) :
    RV × W × W × Nat :=
  (rv r.1, r.2.memory 16, r.2.memory 17, r.2.clock)

/-- A decidable view of `(result, code-buffer position/buffer/space, clock)`. -/
private def viewCodeBuffer (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Nat) :
    RV × BitVec 64 × List (BitVec 8) × Nat × Nat :=
  (rv r.1, r.2.codeBuffer.position, r.2.codeBuffer.buffer, r.2.codeBuffer.spaceLeft, r.2.clock)

/-- A decidable view of `(result, data-buffer position/buffer/space, clock)`. -/
private def viewDataBuffer (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Nat) :
    RV × BitVec 64 × List (BitVec 64) × Nat × Nat :=
  (rv r.1, r.2.dataBuffer.position, r.2.dataBuffer.buffer, r.2.dataBuffer.spaceLeft, r.2.clock)

/-- A decidable view of the `Install` state fields the row observes. -/
private def viewInstall (r : Option (WordSemResult 64) × WordSemStateFiniteExact 64 Unit Nat) :
    RV × List (Nat × W) × BitVec 64 × List (BitVec 8) × BitVec 64 × List (BitVec 64) ×
      List (Nat × (Nat × WordLangProgHOL (BitVec 64))) × Option Nat × Spt Nat × Nat :=
  (rv r.1, sptToAList r.2.locals, r.2.codeBuffer.position, r.2.codeBuffer.buffer,
    r.2.dataBuffer.position, r.2.dataBuffer.buffer, sptToAList r.2.code,
    r.2.stackMax, r.2.stackSize, r.2.clock)

/-- `alloc_ok=(NONE,[(4,Loc 1 0); (2,Word 16w)],3)`: a GC-free successful
    allocation with an identity `gcFun` and `TriggerGC - NextFree = 16`. -/
private def sAlloc : WordSemStateFiniteExact 64 Unit Nat :=
  { s0 with
    locals := sptFromAList [(2, .word 16), (4, .loc 1 0)]
    stack := []
    localsSize := some 3
    stackMax := none
    store := (HolFiniteMapExact.empty.update (.nextFree, .word 8)).update (.triggerGC, .word 24)
    gcFun := fun x => some (x.1, x.2.1, x.2.2.2) }

/-- `alloc_ok=(NONE,[(4,Loc 1 0); (2,Word 16w)],3)` -/
theorem allocOk :
    view (evaluate (.alloc 2 (units [2], units [4])) sAlloc) =
      (.none, [(4, .loc 1 0), (2, .word 16)], 3) := by
  ev_simp

/-- `store_ok=(NONE,Word 7w,Word 0w,3)`: a successful store at 16 with a
    read-back of 16 and of the untouched cell 17. -/
theorem storeOk :
    viewStore (evaluate (.store (.const 16) 2) s0) = (.none, .word 7, .word 0, 3) := by
  ev_simp

/-- `op_curr_heap=(NONE,[(3,Loc 5 0); (1,Word 12w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem opCurrHeap :
    view (evaluate (.opCurrHeap .add 1 2)
      { s0 with store := HolFiniteMapExact.empty.update (.currHeap, .word 5) }) =
      (.none, [(3, .loc 5 0), (1, .word 12), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp

/-- `share_inst_load=(NONE,[(3,Loc 5 0); (1,Word 16w); (9,Word 1w); (8,Word 16w); (2,Word 7w)],3)` -/
theorem shareInstLoad :
    view (evaluate (.shareInst .load 1 (.const 16))
      { s0 with shMdomain := fun a => decide (a = 16) }) =
      (.none, [(3, .loc 5 0), (1, .word 16), (9, .word 1), (8, .word 16), (2, .word 7)], 3) := by
  ev_simp

/-- `code_buffer_write=(NONE,0w,[1w; 2w; 7w],4,3)` -/
theorem codeBufferWrite :
    viewCodeBuffer (evaluate (.codeBufferWrite 1 2)
      { s0 with
        codeBuffer := { position := 0, buffer := [1, 2], spaceLeft := 5 }
        locals := sptFromAList [(1, .word 2), (2, .word 7)] }) =
      (.none, 0, [1, 2, 7], 4, 3) := by
  ev_simp

/-- `data_buffer_write=(NONE,0w,[5w; 7w],1,3)` -/
theorem dataBufferWrite :
    viewDataBuffer (evaluate (.dataBufferWrite 1 2)
      { s0 with
        dataBuffer := { position := 0, buffer := [5], spaceLeft := 2 }
        locals := sptFromAList [(1, .word 8), (2, .word 7)] }) =
      (.none, 0, [5, 7], 1, 3) := by
  ev_simp

/-- A successful `Install` state: matching flushed buffers, a compile oracle
    whose next configuration matches, and installed code `42 -> (42, Skip)`. -/
private def sInstall : WordSemStateFiniteExact 64 Unit Nat :=
  { s0 with
    locals := sptFromAList [(1, .word 0), (2, .word 2), (3, .word 0), (4, .word 8)]
    compile := fun _ _ => some ([1, 2], [3], ())
    compileOracle := fun _ => ((), [(42, (42, WordLangProgHOL.skip))])
    codeBuffer := { position := 0, buffer := [1, 2], spaceLeft := 5 }
    dataBuffer := { position := 0, buffer := [3], spaceLeft := 5 }
    fpRegs := HolFiniteMapExact.empty
    code := sptFromAList [(5, (1, WordLangProgHOL.return 0 [0])), (6, (2, WordLangProgHOL.return 0 [2]))] }

/-- `install_ok=(NONE,[(1,Loc 42 0)],2w,[],8w,[],[(5,1,Return 0 [0]); (42,42,Skip); (6,2,Return 0 [2])],NONE,LN,3)` -/
theorem installOk :
    viewInstall (evaluate (.install 1 2 3 4 (.ln, .ln)) sInstall) =
      (.none, [(1, .loc 42 0)], 2, [], 8, [],
        [(5, (1, WordLangProgHOL.return 0 [0])), (42, (42, WordLangProgHOL.skip)),
         (6, (2, WordLangProgHOL.return 0 [2]))], none, .ln, 3) := by
  ev_simp

/-! `call_handler_exception=(NONE,[(3,Word 7w); (5,Word 99w); (2,Word 7w)],2)`
is captured in the HOL probe (`scripts/hol-probes/word_sem_evaluate_probe.out`) but
its kernel replay is still open: reducing the returning-`Call` caught-handler
`Exception` branch under `decide +kernel` does not terminate the kernel
reduction (the recursive `evaluate` on the callee `Raise` is not unfolded by
kernel whnf). The row is therefore not asserted here; the faithful kernel
replay is tracked by bead `flapjack-6m93.1`. -/

def runChecks : IO Bool := do
  IO.println "PASS wordSem evaluate_def matches 35/36 HOL oracle rows (kernel-checked); call_handler_exception probe-only pending flapjack-6m93.1"
  pure true

end Flapjack.Test.WordSemEvaluateParity
