import Flapjack.Compiler.Backend.Semantics.WordSem.Env

/-!
Direct HOL oracle rows for the exact wordSem environment and stack helpers
(`scripts/hol-probes/word_sem_env_probe.out`, generated by
`word_sem_env_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:472-612`, with
`misc$fromList2` and `mllist$sort`).  The HOL probe updates fields of a free
state `s`; the Lean rows update the same fields of a concrete base state
`s0`, which is one instance of that `s`.
-/

namespace Flapjack.Test.WordSemEnvParity

open Flapjack
open Flapjack.WordSemStateFiniteExact

private abbrev W := WordLocW 64

private def envT : Spt W := sptInsert 1 (.word 1) (sptInsert 2 (.loc 3 4) (sptInsert 5 (.word 9) .ln))

private def names (keys : List Nat) : WordLangNumSetHOL :=
  keys.foldr (fun k t => sptInsert k () t) .ln

/-- The 18 state-free rows `kvc_*`, `rearrange_*`, `from_list2`, `sort_kvc`,
    `env_to_list`, `env_to_list_perm`, `cut_names_*` and `cut_env_*`. -/
def pureRows : List (String × Bool) :=
  [("kvc_loc_loc", wordSemKeyValCompare (1, (.loc 3 4 : W)) (1, .loc 1 2) == true),
   ("kvc_loc_loc_eq", wordSemKeyValCompare (1, (.loc 3 4 : W)) (1, .loc 3 5) == false),
   ("kvc_word_signed", wordSemKeyValCompare (1, (.word (-1) : W)) (1, .word 0) == true),
   ("kvc_word_signed_rev", wordSemKeyValCompare (1, (.word 0 : W)) (1, .word (-1)) == false),
   ("kvc_key", wordSemKeyValCompare (2, (.loc 0 0 : W)) (1, .word 0) == true),
   ("kvc_loc_word", wordSemKeyValCompare (1, (.loc 0 0 : W)) (1, .word 0) == false),
   ("kvc_word_loc", wordSemKeyValCompare (1, (.word 5 : W)) (1, .loc 0 0) == true),
   ("rearrange_rev", wordSemListRearrange (fun i => 2 - i) [10, 20, 30] == [30, 20, 10]),
   ("rearrange_bad", wordSemListRearrange (fun _ => 0) [10, 20] == [10, 20]),
   ("rearrange_out", wordSemListRearrange (fun i => i + 1) [10, 20] == [10, 20]),
   ("from_list2", sptToAList (sptFromList2 [(.word 1 : W), .loc 2 3, .word 5]) ==
      [(0, .word 1), (4, .word 5), (2, .loc 2 3)]),
   ("sort_kvc", Basis.Pure.MlList.sort wordSemKeyValCompare
      [(3, (.word 1 : W)), (7, .loc 0 0), (1, .word 2), (5, .word 3), (2, .loc 1 1)] ==
      [(7, .loc 0 0), (5, .word 3), (3, .word 1), (2, .loc 1 1), (1, .word 2)]),
   ("env_to_list", (wordSemEnvToList (sptFromList2 [(.word 1 : W), .loc 2 3, .word 5])
      (fun n i => if n = 0 then (if i = 0 then 1 else if i = 1 then 0 else i) else i)).1 ==
      [(2, .loc 2 3), (4, .word 5), (0, .word 1)]),
   ("env_to_list_perm", (wordSemEnvToList (.ln : Spt W) (fun n i => n * 10 + i)).2 2 3 == 33),
   ("cut_names_hit", (wordSemCutNames (names [2, 5]) envT).map sptToAList ==
      some [(5, .word 9), (2, .loc 3 4)]),
   ("cut_names_miss", (wordSemCutNames (names [3]) envT).isNone),
   ("cut_env_hit", (wordSemCutEnv (names [1], names [5]) envT).map sptToAList ==
      some [(1, .word 1), (5, .word 9)]),
   ("cut_env_miss", (wordSemCutEnv (names [1], names [6]) envT).isNone)]

#guard pureRows.all (·.2)

/-- A concrete base state standing in for the probe's free `s`.  Every row
    below reads only fields that the row itself sets or that the helper
    computes. -/
private def s0 : WordSemStateFiniteExact 64 Unit Unit where
  locals := .ln
  localsSize := none
  fpRegs := HolFiniteMapExact.empty
  store := HolFiniteMapExact.empty
  stack := []
  stackLimit := 0
  stackMax := none
  stackSize := .ln
  memory := fun _ => .word 0
  mdomain := fun _ => false
  shMdomain := fun _ => false
  permute := fun _ i => i
  compile := fun _ _ => none
  compileOracle := fun _ => ((), [])
  codeBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  dataBuffer := { position := 0, buffer := [], spaceLeft := 0 }
  gcFun := fun _ => none
  handler := 0
  clock := 0
  termdep := 0
  code := .ln
  be := false
  ffi := { oracle := fun _ state _ _ => .ret state [], ffiState := (), ioEvents := [] }

private def frameView : WordSemStackFrame 64 →
    Option Nat × List (Nat × W) × List (Nat × W) × Option (Nat × Nat × Nat)
  | .stackFrame n l0 l h => (n, l0, l, h)

private def pushed : WordSemStateFiniteExact 64 Unit Unit :=
  pushEnv (sptFromList2 [(.word 1 : W)], sptInsert 3 (.loc 1 0) .ln) (some (0, .skip, 7, 8))
    { s0 with stack := [], localsSize := some 2, handler := 9, stackMax := some 1,
              permute := fun _ i => i }

private def excState (handler : Nat) (stack : List (WordSemStackFrame 64)) :
    WordSemStateFiniteExact 64 Unit Unit :=
  { s0 with handler := handler, stack := stack }

/-- The 11 state rows `call_env*`, `push_env_*`, `pop_env*`, `jump_exc*`,
    `cut_state` and `cut_state_opt_none`. -/
def stateRows : List (String × Bool) :=
  [("call_env",
      let t := WordSemStateFiniteExact.callEnv [.word 1, .word 2] (some 5)
        { s0 with stack := [.stackFrame (some 2) [] [] none], stackMax := some 4 }
      (sptToAList t.locals, t.localsSize, t.stackMax) ==
        ([(0, .word 1), (2, .word 2)], some 5, some 8)),
   ("call_env_none",
      (WordSemStateFiniteExact.callEnv [] none { s0 with stack := [], stackMax := some 4 }).stackMax
        == none),
   ("push_env_some",
      (pushed.stack.map frameView, pushed.stackMax, pushed.handler) ==
        ([(some 2, [(0, .word 1)], [(3, .loc 1 0)], some (9, 7, 8))], some 6, 0)),
   ("push_env_none",
      let t := pushEnv (.ln, sptInsert 3 (.loc 1 0) .ln) none
        { s0 with stack := [], localsSize := none, handler := 9, stackMax := some 1,
                  permute := fun _ i => i }
      (t.stack.map frameView, t.stackMax, t.handler) ==
        ([(none, [], [(3, .loc 1 0)], none)], none, 9)),
   ("pop_env",
      (popEnv pushed).map (fun t =>
          (sptToAList t.locals, t.localsSize, t.handler, t.stack.map frameView)) ==
        some ([(3, .loc 1 0), (0, .word 1)], some 2, 9, [])),
   ("pop_env_empty", (popEnv { s0 with stack := [] }).isNone),
   ("jump_exc",
      (jumpExc (excState 0 [.stackFrame none [] [] none,
          .stackFrame (some 4) [(2, .word 6)] [(4, .loc 1 1)] (some (5, 7, 8))])).map
        (fun (t, l1, l2) =>
          (sptToAList t.locals, t.localsSize, t.handler, t.stack.length, l1, l2)) ==
        some ([(4, .loc 1 1), (2, .word 6)], some 4, 5, 0, 7, 8)),
   ("jump_exc_nohandler",
      (jumpExc (excState 1 [.stackFrame none [] [] none,
          .stackFrame (some 4) [] [] (some (5, 7, 8))])).isNone),
   ("jump_exc_range", (jumpExc (excState 2 [.stackFrame none [] [] none])).isNone),
   ("cut_state",
      (cutState (names [2], .ln) { s0 with locals := envT }).map (fun t => sptToAList t.locals) ==
        some [(2, .loc 3 4)]),
   ("cut_state_opt_none",
      (cutStateOpt none { s0 with locals := envT }).map (fun t => sptToAList t.locals) ==
        some [(1, .word 1), (5, .word 9), (2, .loc 3 4)])]

#guard stateRows.all (·.2)

def runChecks : IO Bool := do
  let bad := (pureRows ++ stateRows).filter (fun r => !r.2)
  if bad.isEmpty then
    IO.println "PASS wordSem env/stack helpers match all 29 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL wordSem env/stack HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.WordSemEnvParity
