import Flapjack.Compiler.Backend.Semantics.WordSem.CallHelpers

/-!
Direct HOL oracle rows for the exact wordSem call and loop helpers
(`scripts/hol-probes/word_sem_call_helpers_probe.out`, generated by
`word_sem_call_helpers_probeScript.sml` from
`cakeml/compiler/backend/semantics/wordSemScript.sml:946-1014`).
-/

namespace Flapjack.Test.WordSemCallHelpersParity

open Flapjack

private abbrev W := WordLocW 64
private abbrev R := WordSemResult 64

private def isBreak : Option R → Option Nat
  | some (.break n) => some n
  | _ => none

private def isContinue : Option R → Option Nat
  | some (.continue n) => some n
  | _ => none

private def writes : W × W × W :=
  let m := wordSemConstWrites (8 : BitVec 64) 100 [(true, 1), (false, 2)] (fun _ => .loc 0 0)
  (m 8, m 16, m 24)

/-- Original independent-metadata carrier replay: three arbitrary metadata
fields, including a different word dimension from the argument list. -/
example : wordSemAddRetLoc
    (some (true, ((9 : Nat), (10 : Nat)), BitVec.ofNat 32 17, 5, 6))
    [(.word 7 : WordLocW 8)] = [.loc 5 6, .word 7] := rfl

/-- Original NONE replay retains its independent phantom metadata types. -/
example : wordSemAddRetLoc
    (none : Option (Bool × (Nat × Nat) × BitVec 32 × Nat × Nat))
    [(.word 7 : WordLocW 8)] = [.word 7] := rfl

/-- All 25 rows of the probe output, in order. -/
def rows : List (String × Bool) :=
  [("add_ret_loc_none", wordSemAddRetLoc (ReturnValue := Unit) (ReturnNames := Unit) (ReturnHandler := Unit) none [(.word 1 : W)] == [.word 1]),
   ("add_ret_loc_some", wordSemAddRetLoc (some ([1, 2], ((.ln, .ln) : WordLangCutsetsHOL), (.skip : WordLangProgHOL (BitVec 64)), 5, 6)) [(.word 1 : W)]
      == [.loc 5 6, .word 1]),
   ("bad_dest_args_nil", wordSemBadDestArgs none [] == true),
   ("bad_dest_args_dest", wordSemBadDestArgs (some 3) [] == false),
   ("bad_dest_args_args", wordSemBadDestArgs none [1] == false),
   ("const_addresses_hit", wordSemConstAddresses (8 : BitVec 64) [(true, 1), (false, 2)]
      (fun a => a = 8 || a = 16) == true),
   ("const_addresses_miss", wordSemConstAddresses (8 : BitVec 64) [(true, 1), (false, 2)]
      (fun a => a = 8) == false),
   ("const_addresses_nil", wordSemConstAddresses (8 : BitVec 64) [] (fun _ => false) == true),
   ("const_writes", writes == (.word 101, .word 2, .loc 0 0)),
   ("stop", wordSemSTOP (5 : Nat) == 5),
   ("bad_fun_return_none", wordSemBadFunReturn (none : Option R) == true),
   ("bad_fun_return_break", wordSemBadFunReturn (some (.break 1 : R)) == true),
   ("bad_fun_return_cont", wordSemBadFunReturn (some (.continue 0 : R)) == true),
   ("bad_fun_return_timeout", wordSemBadFunReturn (some (.timeOut : R)) == false),
   ("bad_fun_return_result", wordSemBadFunReturn (some (.result (.word 0) [] : R)) == false),
   ("cont_loop_none", wordSemContLoop (none : Option R) == true),
   ("cont_loop_zero", wordSemContLoop (some (.continue 0 : R)) == true),
   ("cont_loop_two", wordSemContLoop (some (.continue 2 : R)) == false),
   ("cont_loop_break", wordSemContLoop (some (.break 0 : R)) == false),
   ("exit_loop_break0", isBreak (wordSemExitLoop (some (.break 0 : R))) == some 0),
   ("exit_loop_break3", isBreak (wordSemExitLoop (some (.break 3 : R))) == some 2),
   ("exit_loop_cont1", isContinue (wordSemExitLoop (some (.continue 1 : R))) == some 0),
   ("exit_loop_timeout", (match wordSemExitLoop (some (.timeOut : R)) with
      | some .timeOut => true | _ => false)),
   ("exit_loop_none", (wordSemExitLoop (none : Option R)).isNone),
   ("must_terminate_limit_1", wordSemMustTerminateLimit 1 == 28)]

#guard rows.all (·.2)

def runChecks : IO Bool := do
  let bad := rows.filter (fun r => !r.2)
  if bad.isEmpty then
    IO.println "PASS wordSem call/loop helpers match all 25 HOL oracle rows"
    pure true
  else
    IO.println s!"FAIL wordSem call/loop helper HOL oracle rows: {bad.map (·.1)}"
    pure false

end Flapjack.Test.WordSemCallHelpersParity
