load "bossLib";
load "preamble";
load "parmoveTheory";
open bossLib HolKernel Parse preamble parmoveTheory;
val th = DB.fetch "parmove" "pmov_not_use_temp_before_assign";
val _ = (print "original_statement="; print_thm th; print "\n");
val vars = #1 (strip_forall (concl th));
val _ = List.app (fn v => (print_term v; print ":"; print_type (type_of v); print "\n")) vars;
fun out label q = (print (label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "self" ``let p = (([(SOME 1,SOME 1)],[],[]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "chain" ``let p = (([(SOME 1,SOME 2);(SOME 2,SOME 3)],[],[]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "cycle" ``let p = (([(SOME 1,SOME 2);(SOME 2,SOME 1)],[],[]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "active" ``let p = (([],[(SOME 1,SOME 2);(SOME 2,NONE)],[(NONE,SOME 1)]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "empty" ``let p = (([],[],[]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "initialized" ``let p = (([],[],[(NONE,SOME 7)]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "prior_scratch" ``let p = (([],[(SOME 1,NONE)],[(NONE,SOME 2)]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "unsafe_terminal" ``let p = (([],[],[(SOME 7,NONE)]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "pending_scratch" ``let p = (([(NONE,SOME 2);(SOME 1,NONE)],[],[]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "duplicate" ``let p = (([(SOME 1,SOME 2);(SOME 1,SOME 3)],[],[]):(num option # num option) list # (num option # num option) list # (num option # num option) list) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
val _ = out "bool" ``let p = ([(SOME T,SOME F)],[],[]) in (wf p,not_use_temp_before_assign(REVERSE(FST(SND p) ++ SND(SND p))),pmov p,not_use_temp_before_assign(REVERSE(FST(SND(pmov p)) ++ SND(SND(pmov p)))))``;
