load "bossLib"; load "preamble"; load "astTheory";
open bossLib HolKernel Parse preamble astTheory;
val _ = show_types := true;
val _ = print "word_size_case_def=";
val _ = print_term (concl (DB.fetch "ast" "word_size_case_def"));
val _ = print "\n";
val _ = print "word_size_nchotomy=";
val _ = print_term (concl (DB.fetch "ast" "word_size_nchotomy"));
val _ = print "\n";
val _ = print "thunk_mode_case_def=";
val _ = print_term (concl (DB.fetch "ast" "thunk_mode_case_def"));
val _ = print "\n";
val _ = print "thunk_mode_nchotomy=";
val _ = print_term (concl (DB.fetch "ast" "thunk_mode_nchotomy"));
val _ = print "\n";
val _ = print "thunk_op_case_def=";
val _ = print_term (concl (DB.fetch "ast" "thunk_op_case_def"));
val _ = print "\n";
val _ = print "thunk_op_nchotomy=";
val _ = print_term (concl (DB.fetch "ast" "thunk_op_nchotomy"));
val _ = print "\n";
val _ = print "test_case_def=";
val _ = print_term (concl (DB.fetch "ast" "test_case_def"));
val _ = print "\n";
val _ = print "test_nchotomy=";
val _ = print_term (concl (DB.fetch "ast" "test_nchotomy"));
val _ = print "\n";
