load "astTheory"; load "locationTheory";
open HolKernel Parse boolLib bossLib astTheory locationTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "lit_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:ast$lit``)); print "\n");
val _ = (print "arith_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:ast$arith``)); print "\n");
val _ = (print "prim_type_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:ast$prim_type``)); print "\n");
val _ = (print "op_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:ast$op``)); print "\n");
val _ = (print "op_class_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:ast$op_class``)); print "\n");
val _ = (print "lop_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:ast$lop``)); print "\n");
val _ = (print "modN_abbrev="; print (type_to_string ``:modN``); print "\n");
val _ = (print "varN_abbrev="; print (type_to_string ``:varN``); print "\n");
val _ = (print "conN_abbrev="; print (type_to_string ``:conN``); print "\n");
val _ = (print "typeN_abbrev="; print (type_to_string ``:typeN``); print "\n");
val _ = (print "tvarN_abbrev="; print (type_to_string ``:tvarN``); print "\n");
val _ = (print "locn_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:location$locn``)); print "\n");
val _ = (print "locs_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:location$locs``)); print "\n");
val _ = if null (hyp (getOpClass_def)) then () else raise Fail "hypotheses: getOpClass_def";
val _ = (print "getOpClass_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (getOpClass_def)); print "\n");
val _ = if null (hyp (default_loc_def)) then () else raise Fail "hypotheses: default_loc_def";
val _ = (print "default_loc_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (default_loc_def)); print "\n");
val _ = if null (hyp (start_locs_def)) then () else raise Fail "hypotheses: start_locs_def";
val _ = (print "start_locs_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (start_locs_def)); print "\n");
val _ = if null (hyp (unknown_loc_def)) then () else raise Fail "hypotheses: unknown_loc_def";
val _ = (print "unknown_loc_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (unknown_loc_def)); print "\n");
