load "bossLib"; load "preamble"; load "backend_commonTheory";
open bossLib HolKernel Parse preamble backend_commonTheory;
val th = DB.fetch "backend_common" "tra_case_def";
val _ = show_types := true;
val _ = print "tra_case=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "tra_case_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("tra_case_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "tra_case_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "backend_common" "orphan_trace_def";
val _ = show_types := true;
val _ = print "orphan_trace=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "orphan_trace_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("orphan_trace_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "orphan_trace_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "backend_common" "mk_cons_def";
val _ = show_types := true;
val _ = print "mk_cons=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "mk_cons_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("mk_cons_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "mk_cons_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val _ = print "tra_SourceLoc_type="; val _ = print (type_to_string (type_of ``backend_common$SourceLoc``)); val _ = print "\n";
val _ = print "tra_Cons_type="; val _ = print (type_to_string (type_of ``backend_common$Cons``)); val _ = print "\n";
val _ = print "tra_Union_type="; val _ = print (type_to_string (type_of ``backend_common$Union``)); val _ = print "\n";
val _ = print "tra_None_type="; val _ = print (type_to_string (type_of ``backend_common$None``)); val _ = print "\n";
