load "bossLib";
load "balanced_mapTheory";
open HolKernel Parse bossLib balanced_mapTheory;
val _ = Globals.linewidth := 10000;
val _ = Globals.show_types := true;
fun row label th = (if null(hyp th) then () else raise Fail "open definition hypotheses";
  print(label ^ "="); print_thm th; print "\n");
val _ = row "bmra_singleL" singleL_def;
val _ = row "bmra_singleR" singleR_def;
val _ = row "bmra_doubleL" doubleL_def;
val _ = row "bmra_doubleR" doubleR_def;
val _ = row "bmra_rotateL" rotateL_def;
val _ = row "bmra_rotateR" rotateR_def;
val _ = row "bmra_bal" bal_def;
val _ = row "bmra_balL" balL_def;
val _ = row "bmra_balR" balR_def;
val _ = Globals.show_types := false;
val _ = (print "bmra_single_right="; print_term(rand(concl(EVAL ``singleR 2 20 (Bin 999 1 10 Tip Tip) Tip``))); print "\n");
val _ = (print "bmra_single_left="; print_term(rand(concl(EVAL ``singleL 1 10 Tip (Bin 999 2 20 Tip Tip)``))); print "\n");
val _ = (print "bmra_unspecified_unreduced="; print_term(rand(concl(EVAL ``singleR 1 10 Tip Tip = doubleL 2 20 Tip Tip``))); print "\n");
val completed_singleR = DefnBase.one_line_ify NONE singleR_def;
val _ = (print "bmra_completed_singleR="; print_thm completed_singleR; print "\n");
val _ = (print "bmra_completion_hyp="; print_term(hd(hyp completed_singleR)); print "\n");
