load "balanced_mapTheory";
open HolKernel Parse bossLib balanced_mapTheory;
val _ = Globals.linewidth := 1000;
fun out label q = (print(label ^ "="); print_term(rand(concl(EVAL q))); print "\n");
val tree = ``Bin 0 10 100 (Bin 90 20 200 Tip Tip) (Bin 80 5 50 Tip Tip):(num,num)balanced_map``;
val _ = out "bm_size" ``size ^tree``;
val _ = out "bm_bin_size" ``size (bin 10 100 (Bin 90 20 200 Tip Tip) (Bin 80 5 50 Tip Tip):(num,num)balanced_map)``;
val _ = out "bm_nonnull" ``null ^tree``;
val _ = out "bm_empty_null" ``null (empty:(num,num)balanced_map)``;
val _ = out "bm_equal_lookup" ``lookup (\x y:num. Equal) 999 ^tree``;
val _ = out "bm_left_absent" ``lookup num_cmp 20 ^tree``;
val _ = out "bm_root" ``lookup num_cmp 10 ^tree``;
val _ = out "bm_right_absent" ``lookup num_cmp 5 ^tree``;
val _ = out "bm_equal_member" ``member (\x y:num. Equal) 999 ^tree``;
val _ = out "bm_left_member" ``member num_cmp 20 ^tree``;
val _ = out "bm_singleton_hit" ``lookup num_cmp 7 (singleton 7 70:(num,num)balanced_map)``;
val _ = out "bm_singleton_miss" ``lookup num_cmp 8 (singleton 7 70:(num,num)balanced_map)``;
val _ = (print "bm_lookup_definition="; print_thm lookup_def; print "\n");
val _ = (print "bm_member_definition="; print_thm member_def; print "\n");
