load "binary_ieeeTheory";
open HolKernel Parse boolLib binary_ieeeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
val _ = capture "float_to_real_def" float_to_real_def;
val _ = capture "float_value_def" float_value_def;
val _ = capture "float_is_nan_def" float_is_nan_def;
val _ = capture "float_is_signalling_def" float_is_signalling_def;
val _ = capture "float_is_infinite_def" float_is_infinite_def;
val _ = capture "float_is_normal_def" float_is_normal_def;
val _ = capture "float_is_subnormal_def" float_is_subnormal_def;
val _ = capture "float_is_zero_def" float_is_zero_def;
val _ = capture "float_is_finite_def" float_is_finite_def;
val _ = capture "float_negate_def" float_negate_def;
val _ = capture "float_abs_def" float_abs_def;
val _ = capture "float_plus_infinity_def" float_plus_infinity_def;
val _ = capture "float_plus_zero_def" float_plus_zero_def;
val _ = capture "float_top_def" float_top_def;
val _ = capture "float_plus_min_def" float_plus_min_def;
val _ = capture "float_minus_infinity_def" float_minus_infinity_def;
val _ = capture "float_minus_zero_def" float_minus_zero_def;
val _ = capture "float_bottom_def" float_bottom_def;
val _ = capture "float_minus_min_def" float_minus_min_def;
