"""Reject drift in original HOL Mul/Div (MUL/DIV/REM/REMU) step captures."""
from pathlib import Path

EXPECTED = [
    'mul_hypotheses=(rd :word5) ≠ (0w :word5)',
    "mul_statement=dfn'MUL ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then (0w :word64) else s.c_gpr s.procID rs1) *',
    '          (if rs2 = (0w :word5) then (0w :word64) else s.c_gpr s.procID rs2)',
    '      ⦈',
    '  ⦈',
    'div_hypotheses=(rd :word5) ≠ (0w :word5)',
    "div_statement=dfn'DIV ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if',
    '             if rs2 = (0w :word5) then T',
    '             else s.c_gpr s.procID rs2 = (0w :word64)',
    '           then',
    '             (0xFFFFFFFFFFFFFFFFw :word64)',
    '           else',
    '             (if rs1 = (0w :word5) then (0w :word64)',
    '              else s.c_gpr s.procID rs1) /',
    '             (if rs2 = (0w :word5) then (0w :word64)',
    '              else s.c_gpr s.procID rs2))',
    '      ⦈',
    '  ⦈',
    'rem_hypotheses=(rd :word5) ≠ (0w :word5)',
    "rem_statement=dfn'REM ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if',
    '             if rs2 = (0w :word5) then T',
    '             else s.c_gpr s.procID rs2 = (0w :word64)',
    '           then',
    '             if rs1 = (0w :word5) then (0w :word64) else s.c_gpr s.procID rs1',
    '           else',
    '             word_rem',
    '               (if rs1 = (0w :word5) then (0w :word64)',
    '                else s.c_gpr s.procID rs1)',
    '               (if rs2 = (0w :word5) then (0w :word64)',
    '                else s.c_gpr s.procID rs2))',
    '      ⦈',
    '  ⦈',
    'remu_hypotheses=(rd :word5) ≠ (0w :word5)',
    "remu_statement=dfn'REMU ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if',
    '             if rs2 = (0w :word5) then T',
    '             else s.c_gpr s.procID rs2 = (0w :word64)',
    '           then',
    '             if rs1 = (0w :word5) then (0w :word64) else s.c_gpr s.procID rs1',
    '           else',
    '             word_mod',
    '               (if rs1 = (0w :word5) then (0w :word64)',
    '                else s.c_gpr s.procID rs1)',
    '               (if rs2 = (0w :word5) then (0w :word64)',
    '                else s.c_gpr s.procID rs2))',
    '      ⦈',
    '  ⦈',
    'mul_nop_hypotheses=(rd :word5) = (0w :word5)',
    "mul_nop_statement=dfn'MUL ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) = s",
    'div_nop_hypotheses=(rd :word5) = (0w :word5)',
    "div_nop_statement=dfn'DIV ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) = s",
    'rem_nop_hypotheses=(rd :word5) = (0w :word5)',
    "rem_nop_statement=dfn'REM ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) = s",
    'remu_nop_hypotheses=(rd :word5) = (0w :word5)',
    "remu_nop_statement=dfn'REMU ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) = s",
    "source=HOL riscv_stepScript.sml:874-886 mul/div/rem = arithr [] over dfn'MUL/DIV/REM/REMU_def with the rd = 0w companion avoided; per-theorem Thm.hyp captured above; the MUL_NOP/DIV_NOP/REM_NOP/REMU_NOP companions add rd = 0w and conclude identity; DIVU (line 881) is ported separately in l3_step_divu_probe.out",
]


def check(text):
    if text.splitlines() != EXPECTED:
        raise ValueError("original HOL muldiv capture differs from reviewed statements")


if __name__ == "__main__":
    check(Path(__file__).with_name("l3_step_muldiv_probe.out").read_text())
    print("step_muldiv: exact original HOL statements, hypotheses and types PASS")
