"""Reject drift in original HOL immediate-ALU evaluated instruction captures."""
from pathlib import Path

EXPECTED = [
    'addi_hypotheses=(rd :word5) ≠ (0w :word5)',
    "addi_statement=dfn'ADDI ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then (sw2sw imm :word64)',
    '           else s.c_gpr s.procID rs1 + (sw2sw imm :word64))',
    '      ⦈',
    '  ⦈',
    "slti_statement=dfn'SLTI ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (v2w',
    '             [(if rs1 = (0w :word5) then (0w :word64)',
    '               else if (s.c_MCSR s.procID).mcpuid.ArchBase = (0w :word2) then',
    '                 (sw2sw',
    '                    (((31 :num) >< (0 :num)) (s.c_gpr s.procID rs1) :word32) :',
    '                  word64)',
    '               else s.c_gpr s.procID rs1) < (sw2sw imm :word64)] :word64)',
    '      ⦈',
    '  ⦈',
    "sltiu_statement=dfn'SLTIU ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (v2w',
    '             [(if rs1 = (0w :word5) then (0w :word64)',
    '               else if (s.c_MCSR s.procID).mcpuid.ArchBase = (0w :word2) then',
    '                 (sw2sw',
    '                    (((31 :num) >< (0 :num)) (s.c_gpr s.procID rs1) :word32) :',
    '                  word64)',
    '               else s.c_gpr s.procID rs1) <₊ (sw2sw imm :word64)] :word64)',
    '      ⦈',
    '  ⦈',
    "andi_statement=dfn'ANDI ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then (0w :word64)',
    '           else s.c_gpr s.procID rs1 && (sw2sw imm :word64))',
    '      ⦈',
    '  ⦈',
    "ori_statement=dfn'ORI ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then (sw2sw imm :word64)',
    '           else s.c_gpr s.procID rs1 ‖ (sw2sw imm :word64))',
    '      ⦈',
    '  ⦈',
    "xori_statement=dfn'XORI ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then (sw2sw imm :word64)',
    '           else s.c_gpr s.procID rs1 ⊕ (sw2sw imm :word64))',
    '      ⦈',
    '  ⦈',
    'imm12_type=:word12',
    "source=HOL riscv_stepScript.sml:837-843 class evaluator over dfn'ADDI/SLTI/SLTIU/ANDI/ORI/XORI_def; sole hypothesis rd <> 0w",
]


def check(text):
    if text.splitlines() != EXPECTED:
        raise ValueError("original HOL immediate-ALU capture differs from reviewed statements")


if __name__ == "__main__":
    check(Path(__file__).with_name("l3_step_arithi_probe.out").read_text())
    print("step_arithi: exact original HOL statements, hypothesis and types PASS")
