#!/usr/bin/env python3
"""Full original byte-memory theorem/proof/driver guard, not equivalence."""
from pathlib import Path
import re
import shlex
ROOT = Path(__file__).resolve().parents[2]
EXPECTED = ['bytes_in_memory_thm_statement=∀w s state a b c d. target_state_rel riscv_target s state ∧ bytes_in_memory s.pc [a; b; c; d] s.mem s.mem_domain ⇒ state.exception = NoException ∧ (state.c_MCSR state.procID).mstatus.VM = 0w ∧ (state.c_MCSR state.procID).mcpuid.ArchBase = 2w ∧ state.c_NextFetch state.procID = NONE ∧ aligned 2 (state.c_PC state.procID) ∧ state.MEM8 (state.c_PC state.procID) = a ∧ state.MEM8 (state.c_PC state.procID + 1w) = b ∧ state.MEM8 (state.c_PC state.procID + 2w) = c ∧ state.MEM8 (state.c_PC state.procID + 3w) = d ∧ state.c_PC state.procID + 3w ∈ s.mem_domain ∧ state.c_PC state.procID + 2w ∈ s.mem_domain ∧ state.c_PC state.procID + 1w ∈ s.mem_domain ∧ state.c_PC state.procID ∈ s.mem_domain', 'bytes_in_memory_thm_types=w : :α, s : :64 asm_state, state : :riscv_state, a : :word8, b : :word8, c : :word8, d : :word8', 'bytes_in_memory_thm_hypotheses=0', 'bytes_in_memory_thm_proved=T', 'bytes_in_memory_thm2_statement=∀w s state a b c d. target_state_rel riscv_target s state ∧ bytes_in_memory (s.pc + w) [a; b; c; d] s.mem s.mem_domain ⇒ state.MEM8 (state.c_PC state.procID + w) = a ∧ state.MEM8 (state.c_PC state.procID + w + 1w) = b ∧ state.MEM8 (state.c_PC state.procID + w + 2w) = c ∧ state.MEM8 (state.c_PC state.procID + w + 3w) = d ∧ state.c_PC state.procID + w + 3w ∈ s.mem_domain ∧ state.c_PC state.procID + w + 2w ∈ s.mem_domain ∧ state.c_PC state.procID + w + 1w ∈ s.mem_domain ∧ state.c_PC state.procID + w ∈ s.mem_domain', 'bytes_in_memory_thm2_types=w : :word64, s : :64 asm_state, state : :riscv_state, a : :word8, b : :word8, c : :word8, d : :word8', 'bytes_in_memory_thm2_hypotheses=0', 'bytes_in_memory_thm2_proved=T']
HOL = {'bytes_in_memory_thm': ('!w s state a b c d.\n      target_state_rel riscv_target s state /\\\n      bytes_in_memory s.pc [a; b; c; d] s.mem s.mem_domain ==>\n      (state.exception = NoException) /\\\n      ((state.c_MCSR state.procID).mstatus.VM = 0w) /\\\n      ((state.c_MCSR state.procID).mcpuid.ArchBase = 2w) /\\\n      (state.c_NextFetch state.procID = NONE) /\\\n      aligned 2 (state.c_PC state.procID) /\\\n      (state.MEM8 (state.c_PC state.procID) = a) /\\\n      (state.MEM8 (state.c_PC state.procID + 1w) = b) /\\\n      (state.MEM8 (state.c_PC state.procID + 2w) = c) /\\\n      (state.MEM8 (state.c_PC state.procID + 3w) = d) /\\\n      state.c_PC state.procID + 3w IN s.mem_domain /\\\n      state.c_PC state.procID + 2w IN s.mem_domain /\\\n      state.c_PC state.procID + 1w IN s.mem_domain /\\\n      state.c_PC state.procID IN s.mem_domain', 'rw [asmPropsTheory.target_state_rel_def, riscv_target_def, riscv_config_def,\n       riscv_ok_def, miscTheory.bytes_in_memory_def,\n       alignmentTheory.aligned_extract, set_sepTheory.fun2set_eq]\n   \\\\ fs []'), 'bytes_in_memory_thm2': ('!w s state a b c d.\n      target_state_rel riscv_target s state /\\\n      bytes_in_memory (s.pc + w) [a; b; c; d] s.mem s.mem_domain ==>\n      (state.MEM8 (state.c_PC state.procID + w) = a) /\\\n      (state.MEM8 (state.c_PC state.procID + w + 1w) = b) /\\\n      (state.MEM8 (state.c_PC state.procID + w + 2w) = c) /\\\n      (state.MEM8 (state.c_PC state.procID + w + 3w) = d) /\\\n      state.c_PC state.procID + w + 3w IN s.mem_domain /\\\n      state.c_PC state.procID + w + 2w IN s.mem_domain /\\\n      state.c_PC state.procID + w + 1w IN s.mem_domain /\\\n      state.c_PC state.procID + w IN s.mem_domain', 'rw [asmPropsTheory.target_state_rel_def, riscv_target_def, riscv_config_def,\n       riscv_ok_def, miscTheory.bytes_in_memory_def,\n       alignmentTheory.aligned_extract, set_sepTheory.fun2set_eq]\n   \\\\ fs []')}
LEAN = {'bytes_in_memory_thm': ' {α : Type} (_w : α) (s : AsmState 64) (state : riscv_state)\n    (a b c d : BitVec 8)\n    (h : targetStateRel riscvTarget s state ∧\n      bytesInMemoryHOL (s.pc) [a,b,c,d] s.mem s.memDomain) :\n    state.exception = exception.NoException ∧\n    (state.c_MCSR state.procID).mstatus.VM = 0 ∧\n    (state.c_MCSR state.procID).mcpuid.ArchBase = 2 ∧\n    state.c_NextFetch state.procID = none ∧\n    holAligned 2 (state.c_PC state.procID) = true ∧\n    state.MEM8 (state.c_PC state.procID) = a ∧\n    state.MEM8 (state.c_PC state.procID + 1) = b ∧\n    state.MEM8 (state.c_PC state.procID + 2) = c ∧\n    state.MEM8 (state.c_PC state.procID + 3) = d ∧\n    s.memDomain (state.c_PC state.procID + 3) ∧\n    s.memDomain (state.c_PC state.procID + 2) ∧\n    s.memDomain (state.c_PC state.procID + 1) ∧\n    s.memDomain (state.c_PC state.procID)', 'bytes_in_memory_thm2': ' (w : BitVec 64) (s : AsmState 64) (state : riscv_state)\n    (a b c d : BitVec 8)\n    (h : targetStateRel riscvTarget s state ∧\n      bytesInMemoryHOL (s.pc + w) [a,b,c,d] s.mem s.memDomain) :\n    state.MEM8 (state.c_PC state.procID + w) = a ∧\n    state.MEM8 (state.c_PC state.procID + w + 1) = b ∧\n    state.MEM8 (state.c_PC state.procID + w + 2) = c ∧\n    state.MEM8 (state.c_PC state.procID + w + 3) = d ∧\n    s.memDomain (state.c_PC state.procID + w + 3) ∧\n    s.memDomain (state.c_PC state.procID + w + 2) ∧\n    s.memDomain (state.c_PC state.procID + w + 1) ∧\n    s.memDomain (state.c_PC state.procID + w)'}
def check(output, original, probe, lean, driver):
    if output.splitlines() != EXPECTED: raise ValueError("complete byte theorem capture drift")
    for name, expected in HOL.items():
        source = re.search(r"Theorem " + name + r"\[local\]:\s*(.*?)\nProof\s*(.*?)\nQED", original, re.S)
        replay = re.search(r"val " + name + r" = prove \(``(.*?)``,\s*(.*?)\);\nval _", probe, re.S)
        for match in (source,replay):
            if not match or any("".join(a.split()) != "".join(b.split()) for a,b in zip(match.groups(),expected)):
                raise ValueError("full original byte theorem/proof drift: " + name)
        statement = re.search(r"theorem " + name + r"\b(.*?) := by", lean, re.S)
        if not statement or "".join(statement[1].split()) != "".join(LEAN[name].split()):
            raise ValueError("reviewed complete Lean byte statement drift: " + name)
    commands = [shlex.split(line) for line in driver.replace("\\\n", " ").splitlines()
                if line.startswith("run_probe riscv_target_bytes_probeScript.sml ")]
    expected = ["run_probe", "riscv_target_bytes_probeScript.sml", "riscv_target_bytes_probe.out"] + [
        row.split("=",1)[0] for row in EXPECTED] + [
        "$cake_dir/compiler/encoders/riscv/proofs/riscv_targetProofScript.sml", "$cake_dir/compiler/encoders/riscv/proofs"]
    if commands != [expected]: raise ValueError("complete byte proof driver drift")
if __name__ == "__main__":
    check(Path(__file__).with_name("riscv_target_bytes_probe.out").read_text(),
          (ROOT / "cakeml/compiler/encoders/riscv/proofs/riscv_targetProofScript.sml").read_text(),
          Path(__file__).with_name("riscv_target_bytes_probeScript.sml").read_text(),
          (ROOT / "Flapjack/RiscV/CorrectnessEncoding/BytesInMemory.lean").read_text(),
          Path(__file__).with_name("regenerate.sh").read_text())
    print("PASS both full original byte proofs, all13/8conjuncts/binders/carriers and driver")
