load "bossLib"; load "preamble"; load "clos_to_bvlTheory";
open bossLib HolKernel Parse preamble clos_to_bvlTheory;
val _ = show_types := true;
val _ = print "config_component_equality=";
val _ = print_term (concl (DB.fetch "clos_to_bvl" "config_component_equality"));
val _ = print "\n";
val _ = print "default_config_def=";
val _ = print_term (concl (DB.fetch "clos_to_bvl" "default_config_def"));
val _ = print "\n";
val _ = print "next_loc_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.next_loc``));
val _ = print "\n";
val _ = print "start_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.start``));
val _ = print "\n";
val _ = print "do_mti_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.do_mti``));
val _ = print "\n";
val _ = print "known_conf_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.known_conf``));
val _ = print "\n";
val _ = print "do_call_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.do_call``));
val _ = print "\n";
val _ = print "call_state_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.call_state``));
val _ = print "\n";
val _ = print "max_app_type=";
val _ = print (type_to_string (type_of ``\(c:clos_to_bvl$config). c.max_app``));
val _ = print "\n";
