load "bossLib"; load "preamble"; load "clos_knownTheory";
open bossLib HolKernel Parse preamble clos_knownTheory;
val _ = show_types := true;
val _ = print "val_approx_case_def=";
val _ = print_term (concl (DB.fetch "clos_known" "val_approx_case_def"));
val _ = print "\n";
val _ = print "val_approx_nchotomy=";
val _ = print_term (concl (DB.fetch "clos_known" "val_approx_nchotomy"));
val _ = print "\n";
val _ = print "inliningDecision_case_def=";
val _ = print_term (concl (DB.fetch "clos_known" "inliningDecision_case_def"));
val _ = print "\n";
val _ = print "inliningDecision_nchotomy=";
val _ = print_term (concl (DB.fetch "clos_known" "inliningDecision_nchotomy"));
val _ = print "\n";
val _ = print "config_component_equality=";
val _ = print_term (concl (DB.fetch "clos_known" "config_component_equality"));
val _ = print "\n";
val _ = print "default_inline_factor_def=";
val _ = print_term (concl (DB.fetch "clos_known" "default_inline_factor_def"));
val _ = print "\n";
val _ = print "default_max_body_size_def=";
val _ = print_term (concl (DB.fetch "clos_known" "default_max_body_size_def"));
val _ = print "\n";
val _ = print "mk_config_def=";
val _ = print_term (concl (DB.fetch "clos_known" "mk_config_def"));
val _ = print "\n";
val _ = print "default_config_def=";
val _ = print_term (concl (DB.fetch "clos_known" "default_config_def"));
val _ = print "\n";
val _ = print "dec_inline_factor_def=";
val _ = print_term (concl (DB.fetch "clos_known" "dec_inline_factor_def"));
val _ = print "\n";
val _ = print "reset_inline_factor_def=";
val _ = print_term (concl (DB.fetch "clos_known" "reset_inline_factor_def"));
val _ = print "\n";
val _ = print "inline_max_body_size_type=";
val _ = print (type_to_string (type_of ``\(c:clos_known$config). c.inline_max_body_size``));
val _ = print "\n";
val _ = print "inline_factor_type=";
val _ = print (type_to_string (type_of ``\(c:clos_known$config). c.inline_factor``));
val _ = print "\n";
val _ = print "initial_inline_factor_type=";
val _ = print (type_to_string (type_of ``\(c:clos_known$config). c.initial_inline_factor``));
val _ = print "\n";
val _ = print "val_approx_spt_type=";
val _ = print (type_to_string (type_of ``\(c:clos_known$config). c.val_approx_spt``));
val _ = print "\n";
