load "bossLib"; load "preamble"; load "closLangTheory";
open bossLib HolKernel Parse preamble closLangTheory;
val _ = show_types := true;
val _ = print "const_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "const_case_def"));
val _ = print "\n";
val _ = print "const_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "const_nchotomy"));
val _ = print "\n";
val _ = print "const_part_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "const_part_case_def"));
val _ = print "\n";
val _ = print "const_part_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "const_part_nchotomy"));
val _ = print "\n";
val _ = print "int_op_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "int_op_case_def"));
val _ = print "\n";
val _ = print "int_op_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "int_op_nchotomy"));
val _ = print "\n";
val _ = print "word_op_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "word_op_case_def"));
val _ = print "\n";
val _ = print "word_op_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "word_op_nchotomy"));
val _ = print "\n";
val _ = print "block_op_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "block_op_case_def"));
val _ = print "\n";
val _ = print "block_op_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "block_op_nchotomy"));
val _ = print "\n";
val _ = print "glob_op_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "glob_op_case_def"));
val _ = print "\n";
val _ = print "glob_op_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "glob_op_nchotomy"));
val _ = print "\n";
val _ = print "mem_op_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "mem_op_case_def"));
val _ = print "\n";
val _ = print "mem_op_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "mem_op_nchotomy"));
val _ = print "\n";
val _ = print "op_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "op_case_def"));
val _ = print "\n";
val _ = print "op_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "op_nchotomy"));
val _ = print "\n";
val _ = print "exp_case_def=";
val _ = print_term (concl (DB.fetch "closLang" "exp_case_def"));
val _ = print "\n";
val _ = print "exp_nchotomy=";
val _ = print_term (concl (DB.fetch "closLang" "exp_nchotomy"));
val _ = print "\n";
