(* Statement capture probe for crepSem$evaluate_ind.

   Reference: cakeml/pancake/semantics/crepSemScript.sml:440, the
   `[allow_rebind]` theorem
     Theorem evaluate_ind = REWRITE_RULE [fix_clock_evaluate] evaluate_ind
   The underlying `evaluate_ind` is auto-generated by HOL's `tdefn` from
   `evaluate_def` (crepSemScript.sml:240, termination at :380-390 with
   `inv_image (measure I LEX measure (prog_size (K 0))) (\(prog,s). (s.clock,prog))`),
   so its statement is not present verbatim in the source. This probe prints the
   conclusion of the rewritten theorem so the Lean port can be compared
   clause-for-clause (bead flapjack-2de.1.1 / flapjack-2de.1.1.1).

   Regenerate the `.out` fixture with scripts/hol-probes/regenerate.sh in a
   checkout with built CakeML HOL theories:
     (cd scripts/hol-probes && ./regenerate.sh) *)
load "bossLib";
load "preamble";
load "crepSemTheory";
open bossLib;
open HolKernel Parse;
open preamble;
open crepSemTheory;

val _ = (print "evaluate_ind=";
         print_term (concl evaluate_ind);
         print "\n");
