load "preamble"; load "data_to_wordTheory";
open HolKernel Parse bossLib preamble data_to_wordTheory;
val _ = Globals.linewidth := 100000;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = print("max_heap_limit_full_def=" ^ term_to_string(concl max_heap_limit_def) ^ "\n");
val _ = print("max_heap_limit_type=" ^ type_to_string(type_of ``max_heap_limit``) ^ "\n");
val _ = out "max_heap_limit_1_0" ``max_heap_limit (:1) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_1_1" ``max_heap_limit (:1) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_1_2" ``max_heap_limit (:1) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_1_3" ``max_heap_limit (:1) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_1_4" ``max_heap_limit (:1) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_1_5" ``max_heap_limit (:1) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_1_6" ``max_heap_limit (:1) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_1_7" ``max_heap_limit (:1) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_7_0" ``max_heap_limit (:7) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_7_1" ``max_heap_limit (:7) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_7_2" ``max_heap_limit (:7) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_7_3" ``max_heap_limit (:7) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_7_4" ``max_heap_limit (:7) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_7_5" ``max_heap_limit (:7) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_7_6" ``max_heap_limit (:7) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_7_7" ``max_heap_limit (:7) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_8_0" ``max_heap_limit (:8) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_8_1" ``max_heap_limit (:8) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_8_2" ``max_heap_limit (:8) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_8_3" ``max_heap_limit (:8) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_8_4" ``max_heap_limit (:8) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_8_5" ``max_heap_limit (:8) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_8_6" ``max_heap_limit (:8) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_8_7" ``max_heap_limit (:8) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_31_0" ``max_heap_limit (:31) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_31_1" ``max_heap_limit (:31) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_31_2" ``max_heap_limit (:31) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_31_3" ``max_heap_limit (:31) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_31_4" ``max_heap_limit (:31) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_31_5" ``max_heap_limit (:31) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_31_6" ``max_heap_limit (:31) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_31_7" ``max_heap_limit (:31) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_32_0" ``max_heap_limit (:32) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_32_1" ``max_heap_limit (:32) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_32_2" ``max_heap_limit (:32) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_32_3" ``max_heap_limit (:32) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_32_4" ``max_heap_limit (:32) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_32_5" ``max_heap_limit (:32) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_32_6" ``max_heap_limit (:32) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_32_7" ``max_heap_limit (:32) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_33_0" ``max_heap_limit (:33) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_33_1" ``max_heap_limit (:33) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_33_2" ``max_heap_limit (:33) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_33_3" ``max_heap_limit (:33) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_33_4" ``max_heap_limit (:33) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_33_5" ``max_heap_limit (:33) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_33_6" ``max_heap_limit (:33) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_33_7" ``max_heap_limit (:33) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_64_0" ``max_heap_limit (:64) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_64_1" ``max_heap_limit (:64) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_64_2" ``max_heap_limit (:64) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_64_3" ``max_heap_limit (:64) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_64_4" ``max_heap_limit (:64) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_64_5" ``max_heap_limit (:64) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_64_6" ``max_heap_limit (:64) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_64_7" ``max_heap_limit (:64) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_80_0" ``max_heap_limit (:80) <|tag_bits:=0;len_bits:=0;pad_bits:=0;len_size:=0;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_80_1" ``max_heap_limit (:80) <|tag_bits:=4;len_bits:=4;pad_bits:=2;len_size:=32;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_80_2" ``max_heap_limit (:80) <|tag_bits:=1;len_bits:=0;pad_bits:=0;len_size:=2;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_80_3" ``max_heap_limit (:80) <|tag_bits:=0;len_bits:=1;pad_bits:=0;len_size:=3;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=None|>``;
val _ = out "max_heap_limit_80_4" ``max_heap_limit (:80) <|tag_bits:=0;len_bits:=0;pad_bits:=1;len_size:=4;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=Simple|>``;
val _ = out "max_heap_limit_80_5" ``max_heap_limit (:80) <|tag_bits:=3;len_bits:=5;pad_bits:=7;len_size:=5;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Generational [1;2]|>``;
val _ = out "max_heap_limit_80_6" ``max_heap_limit (:80) <|tag_bits:=80;len_bits:=1;pad_bits:=2;len_size:=6;has_div:=F;has_longdiv:=F;has_fp_ops:=F;has_fp_tern:=F;be:=F;call_empty_ffi:=F;gc_kind:=None|>``;
val _ = out "max_heap_limit_80_7" ``max_heap_limit (:80) <|tag_bits:=0;len_bits:=64;pad_bits:=32;len_size:=7;has_div:=T;has_longdiv:=T;has_fp_ops:=T;has_fp_tern:=T;be:=T;call_empty_ffi:=T;gc_kind:=Simple|>``;
