load "flatLangTheory"; load "backend_commonTheory";
open HolKernel Parse boolLib bossLib flatLangTheory backend_commonTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "flat_op_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:flatLang$op``)); print "\n");
val _ = (print "flat_pat_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:flatLang$pat``)); print "\n");
val _ = (print "flat_exp_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:flatLang$exp``)); print "\n");
val _ = (print "ctor_id_abbrev="; print (type_to_string ``:flatLang$ctor_id``); print "\n");
val _ = (print "type_id_abbrev="; print (type_to_string ``:flatLang$type_id``); print "\n");
val _ = (print "type_group_id_abbrev="; print (type_to_string ``:flatLang$type_group_id``); print "\n");
val _ = if null (hyp (pat_bindings_def)) then () else raise Fail "hypotheses: pat_bindings_def";
val _ = (print "pat_bindings_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (pat_bindings_def)); print "\n");
val _ = if null (hyp (bool_id_def)) then () else raise Fail "hypotheses: bool_id_def";
val _ = (print "bool_id_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (bool_id_def)); print "\n");
val _ = if null (hyp (Bool_def)) then () else raise Fail "hypotheses: Bool_def";
val _ = (print "Bool_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (Bool_def)); print "\n");
val _ = if null (hyp (SmartIf_def)) then () else raise Fail "hypotheses: SmartIf_def";
val _ = (print "SmartIf_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (SmartIf_def)); print "\n");
val _ = if null (hyp (false_tag_def)) then () else raise Fail "hypotheses: false_tag_def";
val _ = (print "false_tag_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (false_tag_def)); print "\n");
val _ = if null (hyp (true_tag_def)) then () else raise Fail "hypotheses: true_tag_def";
val _ = (print "true_tag_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (true_tag_def)); print "\n");
val _ = if null (hyp (bool_to_tag_def)) then () else raise Fail "hypotheses: bool_to_tag_def";
val _ = (print "bool_to_tag_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (bool_to_tag_def)); print "\n");
