load "bossLib"; load "preamble"; load "flat_patternTheory";
open bossLib HolKernel Parse preamble flat_patternTheory;
val th = DB.fetch "flat_pattern" "init_config_def";
val _ = show_types := true;
val _ = print "init_config=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "init_config_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("init_config_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "init_config_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val _ = show_types := true;
val _ = print "init_config_type="; val _ = print (type_to_string (type_of ``flat_pattern$init_config``)); val _ = print "\n";
val _ = print "config_pat_heuristic_type="; val _ = print (type_to_string (type_of ``\(c:flat_pattern$config). c.pat_heuristic``)); val _ = print "\n";
val _ = print "config_component_equality="; val _ = print_term (concl (DB.fetch "flat_pattern" "config_component_equality")); val _ = print "\n";
