load "riscvTheory"; load "wordsLib";
open HolKernel Parse bossLib Tactical Tactic Conv riscvTheory;
val _ = Globals.linewidth := 100000;
fun out label q = let val th = (EVAL THENC SIMP_CONV (srw_ss()) []) q in if null(hyp th) then(print(label^"=");print_term(snd(dest_eq(concl th)));print "\n") else raise Fail "assumptions" end;
val d8 = DB.fetch "riscv" "boolify8_def";
val _ = computeLib.add_funs [d8];
val _ = (print "boolify8_definition="; print_term(concl d8); print "\n");
val _ = (print "boolify8_type="; print_type(type_of ``riscv$boolify8``); print "\n");
val _ = print ("boolify8_hypotheses=" ^ Int.toString(length(hyp d8)) ^ "\n");
val _ = out "boolify8_full_equation" ``!w:word8. riscv$boolify8 w = (word_bit 7 w,word_bit 6 w,word_bit 5 w,word_bit 4 w,word_bit 3 w,word_bit 2 w,word_bit 1 w,word_bit 0 w)``;
val d16 = DB.fetch "riscv" "boolify16_def";
val _ = computeLib.add_funs [d16];
val _ = (print "boolify16_definition="; print_term(concl d16); print "\n");
val _ = (print "boolify16_type="; print_type(type_of ``riscv$boolify16``); print "\n");
val _ = print ("boolify16_hypotheses=" ^ Int.toString(length(hyp d16)) ^ "\n");
val _ = out "boolify16_full_equation" ``!w:word16. riscv$boolify16 w = (word_bit 15 w,word_bit 14 w,word_bit 13 w,word_bit 12 w,word_bit 11 w,word_bit 10 w,word_bit 9 w,word_bit 8 w,word_bit 7 w,word_bit 6 w,word_bit 5 w,word_bit 4 w,word_bit 3 w,word_bit 2 w,word_bit 1 w,word_bit 0 w)``;
val d32 = DB.fetch "riscv" "boolify32_def";
val _ = computeLib.add_funs [d32];
val _ = (print "boolify32_definition="; print_term(concl d32); print "\n");
val _ = (print "boolify32_type="; print_type(type_of ``riscv$boolify32``); print "\n");
val _ = print ("boolify32_hypotheses=" ^ Int.toString(length(hyp d32)) ^ "\n");
val _ = out "boolify32_full_equation" ``!w:word32. riscv$boolify32 w = (word_bit 31 w,word_bit 30 w,word_bit 29 w,word_bit 28 w,word_bit 27 w,word_bit 26 w,word_bit 25 w,word_bit 24 w,word_bit 23 w,word_bit 22 w,word_bit 21 w,word_bit 20 w,word_bit 19 w,word_bit 18 w,word_bit 17 w,word_bit 16 w,word_bit 15 w,word_bit 14 w,word_bit 13 w,word_bit 12 w,word_bit 11 w,word_bit 10 w,word_bit 9 w,word_bit 8 w,word_bit 7 w,word_bit 6 w,word_bit 5 w,word_bit 4 w,word_bit 3 w,word_bit 2 w,word_bit 1 w,word_bit 0 w)``;
