load "riscvTheory"; load "wordsLib";
open HolKernel Parse bossLib Tactical Tactic Conv riscvTheory;
val _ = Globals.linewidth := 100000;
fun out label q = let val th = EVAL q in if null(hyp th) then(print(label^"=");print_term(snd(dest_eq(concl th)));print "\n") else raise Fail "assumptions" end;
val _ = computeLib.add_funs [CSRMap_def,write'CSRMap_def,raise'exception_def];
val _ = out "csr_unknown_read_0" ``(SND (CSRMap 0w (s with exception := NoException))).exception``;
val _ = out "csr_prior_read_0" ``(SND (CSRMap 0w (s with exception := INTERNAL_ERROR "prior"))) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_arb_0" ``FST (CSRMap 0w s) = (ARB:word64)``;
val _ = out "csr_unknown_write_0" ``(write'CSRMap (v,0w) (s with exception := NoException)).exception``;
val _ = out "csr_prior_write_0" ``(write'CSRMap (v,0w) (s with exception := INTERNAL_ERROR "prior")) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_unknown_read_773" ``(SND (CSRMap 773w (s with exception := NoException))).exception``;
val _ = out "csr_prior_read_773" ``(SND (CSRMap 773w (s with exception := INTERNAL_ERROR "prior"))) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_arb_773" ``FST (CSRMap 773w s) = (ARB:word64)``;
val _ = out "csr_unknown_write_773" ``(write'CSRMap (v,773w) (s with exception := NoException)).exception``;
val _ = out "csr_prior_write_773" ``(write'CSRMap (v,773w) (s with exception := INTERNAL_ERROR "prior")) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_unknown_read_1922" ``(SND (CSRMap 1922w (s with exception := NoException))).exception``;
val _ = out "csr_prior_read_1922" ``(SND (CSRMap 1922w (s with exception := INTERNAL_ERROR "prior"))) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_arb_1922" ``FST (CSRMap 1922w s) = (ARB:word64)``;
val _ = out "csr_unknown_write_1922" ``(write'CSRMap (v,1922w) (s with exception := NoException)).exception``;
val _ = out "csr_prior_write_1922" ``(write'CSRMap (v,1922w) (s with exception := INTERNAL_ERROR "prior")) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_unknown_read_4095" ``(SND (CSRMap 4095w (s with exception := NoException))).exception``;
val _ = out "csr_prior_read_4095" ``(SND (CSRMap 4095w (s with exception := INTERNAL_ERROR "prior"))) = (s with exception := INTERNAL_ERROR "prior")``;
val _ = out "csr_arb_4095" ``FST (CSRMap 4095w s) = (ARB:word64)``;
val _ = out "csr_unknown_write_4095" ``(write'CSRMap (v,4095w) (s with exception := NoException)).exception``;
val _ = out "csr_prior_write_4095" ``(write'CSRMap (v,4095w) (s with exception := INTERNAL_ERROR "prior")) = (s with exception := INTERNAL_ERROR "prior")``;
