load "riscvTheory"; load "wordsLib";
open HolKernel Parse bossLib Tactical Tactic Conv riscvTheory;
val _ = Globals.linewidth := 100000;
fun out label q = let val th = EVAL q in if null(hyp th) then(print(label^"=");print_term(snd(dest_eq(concl th)));print "\n") else raise Fail "assumptions" end;
val _ = computeLib.add_funs [CSRMap_def];
val _ = out "csr_read_value_1" ``CSRMap 1w s = ((w2w ((4 >< 0) (reg'FPCSR ((s.c_UCSR s.procID).fpcsr)):word5):word64),s)``;
val _ = out "csr_read_value_2" ``CSRMap 2w s = ((w2w ((s.c_UCSR s.procID).fpcsr.FRM):word64),s)``;
val _ = out "csr_read_value_3" ``CSRMap 3w s = ((w2w ((7 >< 0) (reg'FPCSR ((s.c_UCSR s.procID).fpcsr)):word8):word64),s)``;
val _ = out "csr_read_value_256" ``CSRMap 256w s = (reg'sstatus (lift_mstatus_sstatus ((s.c_MCSR s.procID).mstatus)),s)``;
val _ = out "csr_read_value_257" ``CSRMap 257w s = ((s.c_SCSR s.procID).stvec,s)``;
val _ = out "csr_read_value_260" ``CSRMap 260w s = (reg'sie (lift_mie_sie ((s.c_MCSR s.procID).mie)),s)``;
val _ = out "csr_read_value_289" ``CSRMap 289w s = ((s.c_SCSR s.procID).stimecmp,s)``;
val _ = out "csr_read_value_320" ``CSRMap 320w s = ((s.c_SCSR s.procID).sscratch,s)``;
val _ = out "csr_read_value_321" ``CSRMap 321w s = ((s.c_SCSR s.procID).sepc,s)``;
val _ = out "csr_read_value_324" ``CSRMap 324w s = (reg'sip (lift_mip_sip ((s.c_MCSR s.procID).mip)),s)``;
val _ = out "csr_read_value_384" ``CSRMap 384w s = ((s.c_SCSR s.procID).sptbr,s)``;
val _ = out "csr_read_value_385" ``CSRMap 385w s = ((s.c_SCSR s.procID).sasid,s)``;
val _ = out "csr_read_value_512" ``CSRMap 512w s = (reg'mstatus ((s.c_HCSR s.procID).hstatus),s)``;
val _ = out "csr_read_value_513" ``CSRMap 513w s = ((s.c_HCSR s.procID).htvec,s)``;
val _ = out "csr_read_value_514" ``CSRMap 514w s = (reg'mtdeleg ((s.c_HCSR s.procID).htdeleg),s)``;
val _ = out "csr_read_value_545" ``CSRMap 545w s = ((s.c_HCSR s.procID).htimecmp,s)``;
val _ = out "csr_read_value_576" ``CSRMap 576w s = ((s.c_HCSR s.procID).hscratch,s)``;
val _ = out "csr_read_value_577" ``CSRMap 577w s = ((s.c_HCSR s.procID).hepc,s)``;
val _ = out "csr_read_value_578" ``CSRMap 578w s = (reg'mcause ((s.c_HCSR s.procID).hcause),s)``;
val _ = out "csr_read_value_579" ``CSRMap 579w s = ((s.c_HCSR s.procID).hbadaddr,s)``;
val _ = out "csr_read_value_768" ``CSRMap 768w s = (reg'mstatus ((s.c_MCSR s.procID).mstatus),s)``;
val _ = out "csr_read_value_769" ``CSRMap 769w s = ((s.c_MCSR s.procID).mtvec,s)``;
val _ = out "csr_read_value_770" ``CSRMap 770w s = (reg'mtdeleg ((s.c_MCSR s.procID).mtdeleg),s)``;
val _ = out "csr_read_value_772" ``CSRMap 772w s = (reg'mie ((s.c_MCSR s.procID).mie),s)``;
val _ = out "csr_read_value_801" ``CSRMap 801w s = ((s.c_MCSR s.procID).mtimecmp,s)``;
val _ = out "csr_read_value_832" ``CSRMap 832w s = ((s.c_MCSR s.procID).mscratch,s)``;
val _ = out "csr_read_value_833" ``CSRMap 833w s = ((s.c_MCSR s.procID).mepc,s)``;
val _ = out "csr_read_value_834" ``CSRMap 834w s = (reg'mcause ((s.c_MCSR s.procID).mcause),s)``;
val _ = out "csr_read_value_835" ``CSRMap 835w s = ((s.c_MCSR s.procID).mbadaddr,s)``;
val _ = out "csr_read_value_836" ``CSRMap 836w s = (reg'mip ((s.c_MCSR s.procID).mip),s)``;
val _ = out "csr_read_value_896" ``CSRMap 896w s = ((s.c_MCSR s.procID).mbase,s)``;
val _ = out "csr_read_value_897" ``CSRMap 897w s = ((s.c_MCSR s.procID).mbound,s)``;
val _ = out "csr_read_value_898" ``CSRMap 898w s = ((s.c_MCSR s.procID).mibase,s)``;
val _ = out "csr_read_value_899" ``CSRMap 899w s = ((s.c_MCSR s.procID).mibound,s)``;
val _ = out "csr_read_value_900" ``CSRMap 900w s = ((s.c_MCSR s.procID).mdbase,s)``;
val _ = out "csr_read_value_901" ``CSRMap 901w s = ((s.c_MCSR s.procID).mdbound,s)``;
val _ = out "csr_read_value_1920" ``CSRMap 1920w s = ((s.c_MCSR s.procID).mtohost,s)``;
val _ = out "csr_read_value_1921" ``CSRMap 1921w s = ((s.c_MCSR s.procID).mfromhost,s)``;
val _ = out "csr_read_value_1923" ``CSRMap 1923w s = (0w,s)``;
val _ = out "csr_read_value_3394" ``CSRMap 3394w s = (reg'mcause ((s.c_SCSR s.procID).scause),s)``;
val _ = out "csr_read_value_3395" ``CSRMap 3395w s = ((s.c_SCSR s.procID).sbadaddr,s)``;
val _ = out "csr_read_value_3840" ``CSRMap 3840w s = (reg'mcpuid ((s.c_MCSR s.procID).mcpuid),s)``;
val _ = out "csr_read_value_3841" ``CSRMap 3841w s = (reg'mimpid ((s.c_MCSR s.procID).mimpid),s)``;
val _ = out "csr_read_value_3856" ``CSRMap 3856w s = ((s.c_MCSR s.procID).mhartid,s)``;
