load "riscvTheory"; load "wordsLib";
open HolKernel Parse bossLib Tactical Tactic Conv riscvTheory;
val _ = Globals.linewidth := 100000;
fun out label q = let val th = EVAL q in if null(hyp th) then(print(label^"=");print_term(snd(dest_eq(concl th)));print "\n") else raise Fail "assumptions" end;
val _ = computeLib.add_funs [write'CSRMap_def,sendIPI_def];
val _ = out "csr_special_write_321" ``write'CSRMap (v,321w) s = (s with c_SCSR := ((s.procID =+ ((s.c_SCSR s.procID) with sepc := v && 0xfffffffffffffffcw)) s.c_SCSR))``;
val _ = out "csr_special_write_833" ``write'CSRMap (v,833w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mepc := v && 0xfffffffffffffffcw)) s.c_MCSR))``;
val _ = out "csr_special_write_770" ``write'CSRMap (v,770w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mtdeleg := rec'mtdeleg v)) s.c_MCSR))``;
val _ = out "csr_special_write_772" ``write'CSRMap (v,772w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mie := rec'mie v)) s.c_MCSR))``;
val _ = out "csr_special_write_834" ``write'CSRMap (v,834w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mcause := rec'mcause v)) s.c_MCSR))``;
val _ = out "csr_special_write_836" ``write'CSRMap (v,836w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mip := rec'mip v)) s.c_MCSR))``;
val _ = out "csr_special_write_289" ``write'CSRMap (v,289w) s = (let t = (s with c_SCSR := ((s.procID =+ ((s.c_SCSR s.procID) with stimecmp := v)) s.c_SCSR)) in (t with c_MCSR := ((t.procID =+ ((t.c_MCSR t.procID) with mip := ((t.c_MCSR t.procID).mip with STIP := F))) t.c_MCSR)))``;
val _ = out "csr_special_write_801" ``write'CSRMap (v,801w) s = (let t = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mtimecmp := v)) s.c_MCSR)) in (t with c_MCSR := ((t.procID =+ ((t.c_MCSR t.procID) with mip := ((t.c_MCSR t.procID).mip with MTIP := F))) t.c_MCSR)))``;
val _ = out "csr_special_write_256" ``write'CSRMap (v,256w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mstatus := lower_sstatus_mstatus (rec'sstatus v,(s.c_MCSR s.procID).mstatus))) s.c_MCSR))``;
val _ = out "csr_special_write_260" ``write'CSRMap (v,260w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mie := lower_sie_mie (rec'sie v,(s.c_MCSR s.procID).mie))) s.c_MCSR))``;
val _ = out "csr_special_write_324" ``write'CSRMap (v,324w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mip := lower_sip_mip (rec'sip v,(s.c_MCSR s.procID).mip))) s.c_MCSR))``;
val _ = out "csr_special_write_768" ``write'CSRMap (v,768w) s = (s with c_MCSR := ((s.procID =+ ((s.c_MCSR s.procID) with mstatus := update_mstatus ((s.c_MCSR s.procID).mstatus,rec'mstatus v))) s.c_MCSR))``;
val _ = out "csr_ipi_equation" ``sendIPI core s = (let id = (w2w core:word8) in if w2n id < s.totalCore then s with c_MCSR := ((id =+ ((s.c_MCSR id) with mip := ((s.c_MCSR id).mip with MSIP := T))) s.c_MCSR) else s)``;
val _ = out "csr_ipi_write" ``write'CSRMap (core,1923w) s = sendIPI core s``;
val _ = out "csr_fp_write_1" ``write'CSRMap (v,1w) s = (let t = (s with c_UCSR := ((s.procID =+ ((s.c_UCSR s.procID) with fpcsr := (write'reg'FPCSR ((s.c_UCSR s.procID).fpcsr,bit_field_insert 4 0 ((4 >< 0) v:word5) (reg'FPCSR ((s.c_UCSR s.procID).fpcsr)))))) s.c_UCSR)) in let u = (t with c_MCSR := ((t.procID =+ ((t.c_MCSR t.procID) with mstatus := ((t.c_MCSR t.procID).mstatus with MFS := ext_status Dirty))) t.c_MCSR)) in (u with c_MCSR := ((u.procID =+ ((u.c_MCSR u.procID) with mstatus := ((u.c_MCSR u.procID).mstatus with MSD := T))) u.c_MCSR)))``;
val _ = out "csr_fp_write_2" ``write'CSRMap (v,2w) s = (let t = (s with c_UCSR := ((s.procID =+ ((s.c_UCSR s.procID) with fpcsr := ((s.c_UCSR s.procID).fpcsr with FRM := ((2 >< 0) v:word3)))) s.c_UCSR)) in let u = (t with c_MCSR := ((t.procID =+ ((t.c_MCSR t.procID) with mstatus := ((t.c_MCSR t.procID).mstatus with MFS := ext_status Dirty))) t.c_MCSR)) in (u with c_MCSR := ((u.procID =+ ((u.c_MCSR u.procID) with mstatus := ((u.c_MCSR u.procID).mstatus with MSD := T))) u.c_MCSR)))``;
val _ = out "csr_fp_write_3" ``write'CSRMap (v,3w) s = (let t = (s with c_UCSR := ((s.procID =+ ((s.c_UCSR s.procID) with fpcsr := (write'reg'FPCSR ((s.c_UCSR s.procID).fpcsr,((31 >< 0) v:word32))))) s.c_UCSR)) in let u = (t with c_MCSR := ((t.procID =+ ((t.c_MCSR t.procID) with mstatus := ((t.c_MCSR t.procID).mstatus with MFS := ext_status Dirty))) t.c_MCSR)) in (u with c_MCSR := ((u.procID =+ ((u.c_MCSR u.procID) with mstatus := ((u.c_MCSR u.procID).mstatus with MSD := T))) u.c_MCSR)))``;
val _ = out "csr_ipi_boundary_0_0" ``sendIPI 0w (s with totalCore := 0) = (s with totalCore := 0)``;
val _ = out "csr_ipi_boundary_0_1" ``sendIPI 0w (s with totalCore := 1) = (s with <|totalCore := 1; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_0_2" ``sendIPI 0w (s with totalCore := 2) = (s with <|totalCore := 2; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_0_255" ``sendIPI 0w (s with totalCore := 255) = (s with <|totalCore := 255; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_0_256" ``sendIPI 0w (s with totalCore := 256) = (s with <|totalCore := 256; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_1_0" ``sendIPI 1w (s with totalCore := 0) = (s with totalCore := 0)``;
val _ = out "csr_ipi_boundary_1_1" ``sendIPI 1w (s with totalCore := 1) = (s with totalCore := 1)``;
val _ = out "csr_ipi_boundary_1_2" ``sendIPI 1w (s with totalCore := 2) = (s with <|totalCore := 2; c_MCSR := ((1w =+ ((s.c_MCSR 1w) with mip := ((s.c_MCSR 1w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_1_255" ``sendIPI 1w (s with totalCore := 255) = (s with <|totalCore := 255; c_MCSR := ((1w =+ ((s.c_MCSR 1w) with mip := ((s.c_MCSR 1w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_1_256" ``sendIPI 1w (s with totalCore := 256) = (s with <|totalCore := 256; c_MCSR := ((1w =+ ((s.c_MCSR 1w) with mip := ((s.c_MCSR 1w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_255_0" ``sendIPI 255w (s with totalCore := 0) = (s with totalCore := 0)``;
val _ = out "csr_ipi_boundary_255_1" ``sendIPI 255w (s with totalCore := 1) = (s with totalCore := 1)``;
val _ = out "csr_ipi_boundary_255_2" ``sendIPI 255w (s with totalCore := 2) = (s with totalCore := 2)``;
val _ = out "csr_ipi_boundary_255_255" ``sendIPI 255w (s with totalCore := 255) = (s with totalCore := 255)``;
val _ = out "csr_ipi_boundary_255_256" ``sendIPI 255w (s with totalCore := 256) = (s with <|totalCore := 256; c_MCSR := ((255w =+ ((s.c_MCSR 255w) with mip := ((s.c_MCSR 255w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_256_0" ``sendIPI 256w (s with totalCore := 0) = (s with totalCore := 0)``;
val _ = out "csr_ipi_boundary_256_1" ``sendIPI 256w (s with totalCore := 1) = (s with <|totalCore := 1; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_256_2" ``sendIPI 256w (s with totalCore := 2) = (s with <|totalCore := 2; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_256_255" ``sendIPI 256w (s with totalCore := 255) = (s with <|totalCore := 255; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_256_256" ``sendIPI 256w (s with totalCore := 256) = (s with <|totalCore := 256; c_MCSR := ((0w =+ ((s.c_MCSR 0w) with mip := ((s.c_MCSR 0w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_257_0" ``sendIPI 257w (s with totalCore := 0) = (s with totalCore := 0)``;
val _ = out "csr_ipi_boundary_257_1" ``sendIPI 257w (s with totalCore := 1) = (s with totalCore := 1)``;
val _ = out "csr_ipi_boundary_257_2" ``sendIPI 257w (s with totalCore := 2) = (s with <|totalCore := 2; c_MCSR := ((1w =+ ((s.c_MCSR 1w) with mip := ((s.c_MCSR 1w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_257_255" ``sendIPI 257w (s with totalCore := 255) = (s with <|totalCore := 255; c_MCSR := ((1w =+ ((s.c_MCSR 1w) with mip := ((s.c_MCSR 1w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_257_256" ``sendIPI 257w (s with totalCore := 256) = (s with <|totalCore := 256; c_MCSR := ((1w =+ ((s.c_MCSR 1w) with mip := ((s.c_MCSR 1w).mip with MSIP := T))) s.c_MCSR)|>)``;
val _ = out "csr_ipi_boundary_18446744073709551615_0" ``sendIPI 18446744073709551615w (s with totalCore := 0) = (s with totalCore := 0)``;
val _ = out "csr_ipi_boundary_18446744073709551615_1" ``sendIPI 18446744073709551615w (s with totalCore := 1) = (s with totalCore := 1)``;
val _ = out "csr_ipi_boundary_18446744073709551615_2" ``sendIPI 18446744073709551615w (s with totalCore := 2) = (s with totalCore := 2)``;
val _ = out "csr_ipi_boundary_18446744073709551615_255" ``sendIPI 18446744073709551615w (s with totalCore := 255) = (s with totalCore := 255)``;
val _ = out "csr_ipi_boundary_18446744073709551615_256" ``sendIPI 18446744073709551615w (s with totalCore := 256) = (s with <|totalCore := 256; c_MCSR := ((255w =+ ((s.c_MCSR 255w) with mip := ((s.c_MCSR 255w).mip with MSIP := T))) s.c_MCSR)|>)``;
