load "riscvTheory";load "wordsLib";load "state_transformerTheory";
open HolKernel Parse bossLib Tactical boolSyntax Conv riscvTheory state_transformerTheory;
val _=Globals.linewidth:=100000;
val _=computeLib.add_funs [addToTLB_def,mkTLBEntry_def,TLBEntries_def,LEVEL_BITS_def,PAGESIZE_BITS_def,rec'SV_PTE_def,FOR_def];
fun out label q=let val th=(EVAL THENC wordsLib.WORD_EVAL_CONV THENC EVAL)q in
 if null(hyp th) then(print(label^"=");print_term(snd(dest_eq(concl th)));print "\n") else raise Fail "assumptions" end;
val _=out "insert_empty" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. NONE) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_holes" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. if j=2w \/ j=6w then NONE else SOME(e 5w)) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_last_hole" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. if j=15w then NONE else SOME(e 5w)) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_full_ascending" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. SOME(e (w2w j))) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_full_tie" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. SOME(e 4w)) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_full_max" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. SOME(e 0xFFFFFFFFFFFFFFFFw)) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_last_oldest" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. SOME(e (if j=15w then 0w else 5w))) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
val _=out "insert_early_oldest" ``let e = \tmAge. ((ARB:TLBEntry) with <|asid:=1w;age:=tmAge|>); t = addToTLB(63w,0w,0w,rec'SV_PTE 0w,0w,0,T,\j. SOME(e (if j=2w then 0w else 5w))) ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w)|>) in MAP (\j. OPTION_MAP (\e. (w2n e.asid,w2n e.age)) (t(n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15]``;
