load "riscvTheory"; load "wordsLib"; load "state_transformerTheory";
open HolKernel Parse bossLib Tactical boolSyntax Conv riscvTheory state_transformerTheory;
val _ = Globals.linewidth := 100000;
val _ = computeLib.add_funs [TLBEntry_fn_updates,SV_PTE_fn_updates,translate64_def,curASID_def,ASID_SIZE_def,SCSR_def,TLB_def,write'TLB_def,addToTLB_def,mkTLBEntry_def,lookupTLB_def,FOR_def,walk64_def,rawReadData_def,rawWriteData_def,MEM_def,write'MEM_def,rec'SV_Vaddr_def,rec'SV_PTE_def,reg'SV_PTE_def,checkMemPermission_def,isGlobal_def,LEVEL_BITS_def,PAGESIZE_BITS_def,TLBEntries_def];
fun out label q = let val th = (EVAL THENC wordsLib.WORD_EVAL_CONV THENC EVAL) q in
 if null(hyp th) then(print(label^"=");print_term(snd(dest_eq(concl th)));print "\n") else raise Fail "assumptions" end;
val _ = out "translate_hit_read" ``let e = ((ARB:TLBEntry) with <|asid:=63w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. if j=2w then SOME e else NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3079 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Read,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_hit_write" ``let e = ((ARB:TLBEntry) with <|asid:=63w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. if j=2w then SOME e else NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3079 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Write,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_hit_write_dirty" ``let e = ((ARB:TLBEntry) with <|asid:=63w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3143w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. if j=2w then SOME e else NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3143 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Write,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_hit_permission_denied" ``let e = ((ARB:TLBEntry) with <|asid:=63w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3077w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. if j=2w then SOME e else NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3077 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Write,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_miss_empty" ``let e = ((ARB:TLBEntry) with <|asid:=63w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3079 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Read,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_miss_invalid" ``let e = ((ARB:TLBEntry) with <|asid:=63w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(0 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Read,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_miss_asid" ``let e = ((ARB:TLBEntry) with <|asid:=1w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. if j=2w then SOME e else NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3079 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Read,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_hit_global" ``let e = ((ARB:TLBEntry) with <|asid:=1w;global:=T;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. if j=2w then SOME e else NONE));MEM8:=(\adr. if w2n adr < 8 then n2w(3079 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Read,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
val _ = out "translate_miss_full_replace" ``let e = ((ARB:TLBEntry) with <|asid:=1w;global:=F;vAddrMask:=4095w;vMatchMask:=0xFFFFFFFFFFFFF000w;vAddr:=0w;pAddr:=12288w;age:=3w;pteAddr:=0w;pte:=rec'SV_PTE 3079w|>); s = ((ARB:riscv_state) with <|procID:=7w;totalCore:=1;c_cycles:=(\id. 77w);c_SCSR:=(\id. (ARB:SupervisorCSR) with <|sasid:=63w;sptbr:=0w|>);c_tlb:=(\id. (\j. SOME e));MEM8:=(\adr. if w2n adr < 8 then n2w(3079 DIV (2 ** (8 * w2n adr))) else 0w)|>); r = translate64(1656w,Data,Read,User,0) s in (OPTION_MAP w2n (FST r), MAP (\j. OPTION_MAP (\e. (w2n e.asid,e.global,w2n e.vAddrMask,w2n e.vMatchMask,w2n e.vAddr,w2n e.pAddr,w2n e.age,w2n e.pteAddr,w2n(reg'SV_PTE e.pte))) ((SND r).c_tlb 7w (n2w j))) [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15], w2n(rawReadData 0w (SND r)))``;
