(* Original-HOL oracle for the L3 RISC-V model's Decode (HOL/examples/l3-machine-code/riscv/
   model/riscvScript.sml): HOL's own Encode of each listed instruction, and Decode of that word,
   evaluated with the riscv definitions added to the compset; plus two words outside the
   instruction encodings. *)
val _ = loadPath := (Globals.HOLDIR ^ "/examples/l3-machine-code/riscv/model") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/common") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/lib") :: !loadPath;
load "riscvTheory"; load "wordsLib"; load "bitstringLib";
open HolKernel Parse boolLib bossLib;
val _ = Globals.linewidth := 4000;
val () = computeLib.add_funs (map snd (DB.definitions "riscv"));
val conv = EVAL THENC DEPTH_CONV bitstringLib.v2w_n2w_CONV THENC EVAL;
fun ev tm = rhs (concl (conv tm));
fun observe label tm = (print (label ^ "="); print_term (ev tm); print "\n");
val w0 = ev ``riscv$Encode (ArithI (ADDI (1w,2w,3w)))``;
val _ = (print "enc0="; print_term w0; print "\n");
val _ = observe "dec0" ``riscv$Decode ^w0``;
val w1 = ev ``riscv$Encode (ArithI (ADDI (31w,0w,0xFFFw)))``;
val _ = (print "enc1="; print_term w1; print "\n");
val _ = observe "dec1" ``riscv$Decode ^w1``;
val w2 = ev ``riscv$Encode (ArithI (ADDIW (5w,6w,0x800w)))``;
val _ = (print "enc2="; print_term w2; print "\n");
val _ = observe "dec2" ``riscv$Decode ^w2``;
val w3 = ev ``riscv$Encode (ArithI (ANDI (7w,8w,0x7FFw)))``;
val _ = (print "enc3="; print_term w3; print "\n");
val _ = observe "dec3" ``riscv$Decode ^w3``;
val w4 = ev ``riscv$Encode (ArithI (ORI (9w,10w,1w)))``;
val _ = (print "enc4="; print_term w4; print "\n");
val _ = observe "dec4" ``riscv$Decode ^w4``;
val w5 = ev ``riscv$Encode (ArithI (XORI (11w,12w,0xABCw)))``;
val _ = (print "enc5="; print_term w5; print "\n");
val _ = observe "dec5" ``riscv$Decode ^w5``;
val w6 = ev ``riscv$Encode (ArithI (SLTI (13w,14w,5w)))``;
val _ = (print "enc6="; print_term w6; print "\n");
val _ = observe "dec6" ``riscv$Decode ^w6``;
val w7 = ev ``riscv$Encode (ArithI (SLTIU (15w,16w,6w)))``;
val _ = (print "enc7="; print_term w7; print "\n");
val _ = observe "dec7" ``riscv$Decode ^w7``;
val w8 = ev ``riscv$Encode (ArithI (LUI (17w,0xFFFFFw)))``;
val _ = (print "enc8="; print_term w8; print "\n");
val _ = observe "dec8" ``riscv$Decode ^w8``;
val w9 = ev ``riscv$Encode (ArithI (AUIPC (18w,0x12345w)))``;
val _ = (print "enc9="; print_term w9; print "\n");
val _ = observe "dec9" ``riscv$Decode ^w9``;
val w10 = ev ``riscv$Encode (ArithR (ADD (1w,2w,3w)))``;
val _ = (print "enc10="; print_term w10; print "\n");
val _ = observe "dec10" ``riscv$Decode ^w10``;
val w11 = ev ``riscv$Encode (ArithR (SUB (4w,5w,6w)))``;
val _ = (print "enc11="; print_term w11; print "\n");
val _ = observe "dec11" ``riscv$Decode ^w11``;
val w12 = ev ``riscv$Encode (ArithR (AND (7w,8w,9w)))``;
val _ = (print "enc12="; print_term w12; print "\n");
val _ = observe "dec12" ``riscv$Decode ^w12``;
val w13 = ev ``riscv$Encode (ArithR (OR (10w,11w,12w)))``;
val _ = (print "enc13="; print_term w13; print "\n");
val _ = observe "dec13" ``riscv$Decode ^w13``;
val w14 = ev ``riscv$Encode (ArithR (XOR (13w,14w,15w)))``;
val _ = (print "enc14="; print_term w14; print "\n");
val _ = observe "dec14" ``riscv$Decode ^w14``;
val w15 = ev ``riscv$Encode (ArithR (SLT (16w,17w,18w)))``;
val _ = (print "enc15="; print_term w15; print "\n");
val _ = observe "dec15" ``riscv$Decode ^w15``;
val w16 = ev ``riscv$Encode (ArithR (SLTU (19w,20w,21w)))``;
val _ = (print "enc16="; print_term w16; print "\n");
val _ = observe "dec16" ``riscv$Decode ^w16``;
val w17 = ev ``riscv$Encode (ArithR (ADDW (22w,23w,24w)))``;
val _ = (print "enc17="; print_term w17; print "\n");
val _ = observe "dec17" ``riscv$Decode ^w17``;
val w18 = ev ``riscv$Encode (ArithR (SUBW (25w,26w,27w)))``;
val _ = (print "enc18="; print_term w18; print "\n");
val _ = observe "dec18" ``riscv$Decode ^w18``;
val w19 = ev ``riscv$Encode (Shift (SLL (1w,2w,3w)))``;
val _ = (print "enc19="; print_term w19; print "\n");
val _ = observe "dec19" ``riscv$Decode ^w19``;
val w20 = ev ``riscv$Encode (Shift (SRL (4w,5w,6w)))``;
val _ = (print "enc20="; print_term w20; print "\n");
val _ = observe "dec20" ``riscv$Decode ^w20``;
val w21 = ev ``riscv$Encode (Shift (SRA (7w,8w,9w)))``;
val _ = (print "enc21="; print_term w21; print "\n");
val _ = observe "dec21" ``riscv$Decode ^w21``;
val w22 = ev ``riscv$Encode (Shift (SLLI (10w,11w,63w)))``;
val _ = (print "enc22="; print_term w22; print "\n");
val _ = observe "dec22" ``riscv$Decode ^w22``;
val w23 = ev ``riscv$Encode (Shift (SRLI (12w,13w,1w)))``;
val _ = (print "enc23="; print_term w23; print "\n");
val _ = observe "dec23" ``riscv$Decode ^w23``;
val w24 = ev ``riscv$Encode (Shift (SRAI (14w,15w,32w)))``;
val _ = (print "enc24="; print_term w24; print "\n");
val _ = observe "dec24" ``riscv$Decode ^w24``;
val w25 = ev ``riscv$Encode (Shift (SLLIW (16w,17w,31w)))``;
val _ = (print "enc25="; print_term w25; print "\n");
val _ = observe "dec25" ``riscv$Decode ^w25``;
val w26 = ev ``riscv$Encode (Shift (SRAW (18w,19w,20w)))``;
val _ = (print "enc26="; print_term w26; print "\n");
val _ = observe "dec26" ``riscv$Decode ^w26``;
val w27 = ev ``riscv$Encode (Branch (JAL (1w,0x80001w)))``;
val _ = (print "enc27="; print_term w27; print "\n");
val _ = observe "dec27" ``riscv$Decode ^w27``;
val w28 = ev ``riscv$Encode (Branch (JALR (2w,3w,0xFF0w)))``;
val _ = (print "enc28="; print_term w28; print "\n");
val _ = observe "dec28" ``riscv$Decode ^w28``;
val w29 = ev ``riscv$Encode (Branch (BEQ (4w,5w,0x800w)))``;
val _ = (print "enc29="; print_term w29; print "\n");
val _ = observe "dec29" ``riscv$Decode ^w29``;
val w30 = ev ``riscv$Encode (Branch (BNE (6w,7w,4w)))``;
val _ = (print "enc30="; print_term w30; print "\n");
val _ = observe "dec30" ``riscv$Decode ^w30``;
val w31 = ev ``riscv$Encode (Branch (BLT (8w,9w,0xFFEw)))``;
val _ = (print "enc31="; print_term w31; print "\n");
val _ = observe "dec31" ``riscv$Decode ^w31``;
val w32 = ev ``riscv$Encode (Branch (BGE (10w,11w,8w)))``;
val _ = (print "enc32="; print_term w32; print "\n");
val _ = observe "dec32" ``riscv$Decode ^w32``;
val w33 = ev ``riscv$Encode (Branch (BLTU (12w,13w,12w)))``;
val _ = (print "enc33="; print_term w33; print "\n");
val _ = observe "dec33" ``riscv$Decode ^w33``;
val w34 = ev ``riscv$Encode (Branch (BGEU (14w,15w,16w)))``;
val _ = (print "enc34="; print_term w34; print "\n");
val _ = observe "dec34" ``riscv$Decode ^w34``;
val w35 = ev ``riscv$Encode (Load (LD (1w,2w,8w)))``;
val _ = (print "enc35="; print_term w35; print "\n");
val _ = observe "dec35" ``riscv$Decode ^w35``;
val w36 = ev ``riscv$Encode (Load (LW (3w,4w,0xFFCw)))``;
val _ = (print "enc36="; print_term w36; print "\n");
val _ = observe "dec36" ``riscv$Decode ^w36``;
val w37 = ev ``riscv$Encode (Load (LWU (5w,6w,4w)))``;
val _ = (print "enc37="; print_term w37; print "\n");
val _ = observe "dec37" ``riscv$Decode ^w37``;
val w38 = ev ``riscv$Encode (Load (LH (7w,8w,2w)))``;
val _ = (print "enc38="; print_term w38; print "\n");
val _ = observe "dec38" ``riscv$Decode ^w38``;
val w39 = ev ``riscv$Encode (Load (LHU (9w,10w,6w)))``;
val _ = (print "enc39="; print_term w39; print "\n");
val _ = observe "dec39" ``riscv$Decode ^w39``;
val w40 = ev ``riscv$Encode (Load (LB (11w,12w,1w)))``;
val _ = (print "enc40="; print_term w40; print "\n");
val _ = observe "dec40" ``riscv$Decode ^w40``;
val w41 = ev ``riscv$Encode (Load (LBU (13w,14w,0x7FFw)))``;
val _ = (print "enc41="; print_term w41; print "\n");
val _ = observe "dec41" ``riscv$Decode ^w41``;
val w42 = ev ``riscv$Encode (Store (SD (1w,2w,16w)))``;
val _ = (print "enc42="; print_term w42; print "\n");
val _ = observe "dec42" ``riscv$Decode ^w42``;
val w43 = ev ``riscv$Encode (Store (SW (3w,4w,0x800w)))``;
val _ = (print "enc43="; print_term w43; print "\n");
val _ = observe "dec43" ``riscv$Decode ^w43``;
val w44 = ev ``riscv$Encode (Store (SH (5w,6w,2w)))``;
val _ = (print "enc44="; print_term w44; print "\n");
val _ = observe "dec44" ``riscv$Decode ^w44``;
val w45 = ev ``riscv$Encode (Store (SB (7w,8w,1w)))``;
val _ = (print "enc45="; print_term w45; print "\n");
val _ = observe "dec45" ``riscv$Decode ^w45``;
val w46 = ev ``riscv$Encode (MulDiv (MUL (1w,2w,3w)))``;
val _ = (print "enc46="; print_term w46; print "\n");
val _ = observe "dec46" ``riscv$Decode ^w46``;
val w47 = ev ``riscv$Encode (MulDiv (MULH (4w,5w,6w)))``;
val _ = (print "enc47="; print_term w47; print "\n");
val _ = observe "dec47" ``riscv$Decode ^w47``;
val w48 = ev ``riscv$Encode (MulDiv (MULHU (7w,8w,9w)))``;
val _ = (print "enc48="; print_term w48; print "\n");
val _ = observe "dec48" ``riscv$Decode ^w48``;
val w49 = ev ``riscv$Encode (MulDiv (riscv$DIV (10w,11w,12w)))``;
val _ = (print "enc49="; print_term w49; print "\n");
val _ = observe "dec49" ``riscv$Decode ^w49``;
val w50 = ev ``riscv$Encode (MulDiv (DIVU (13w,14w,15w)))``;
val _ = (print "enc50="; print_term w50; print "\n");
val _ = observe "dec50" ``riscv$Decode ^w50``;
val w51 = ev ``riscv$Encode (MulDiv (REM (16w,17w,18w)))``;
val _ = (print "enc51="; print_term w51; print "\n");
val _ = observe "dec51" ``riscv$Decode ^w51``;
val w52 = ev ``riscv$Encode (MulDiv (REMU (19w,20w,21w)))``;
val _ = (print "enc52="; print_term w52; print "\n");
val _ = observe "dec52" ``riscv$Decode ^w52``;
val w53 = ev ``riscv$Encode (MulDiv (MULW (22w,23w,24w)))``;
val _ = (print "enc53="; print_term w53; print "\n");
val _ = observe "dec53" ``riscv$Decode ^w53``;
val w54 = ev ``riscv$Encode (FPLoad (FLD (1w,2w,8w)))``;
val _ = (print "enc54="; print_term w54; print "\n");
val _ = observe "dec54" ``riscv$Decode ^w54``;
val w55 = ev ``riscv$Encode (FPStore (FSD (3w,4w,16w)))``;
val _ = (print "enc55="; print_term w55; print "\n");
val _ = observe "dec55" ``riscv$Decode ^w55``;
val w56 = ev ``riscv$Encode (FArith (FADD_D (1w,2w,3w,0w)))``;
val _ = (print "enc56="; print_term w56; print "\n");
val _ = observe "dec56" ``riscv$Decode ^w56``;
val w57 = ev ``riscv$Encode (FArith (FSQRT_D (4w,5w,7w)))``;
val _ = (print "enc57="; print_term w57; print "\n");
val _ = observe "dec57" ``riscv$Decode ^w57``;
val w58 = ev ``riscv$Encode (FConv (FMV_X_D (6w,7w)))``;
val _ = (print "enc58="; print_term w58; print "\n");
val _ = observe "dec58" ``riscv$Decode ^w58``;
val w59 = ev ``riscv$Encode (FConv (FMV_D_X (8w,9w)))``;
val _ = (print "enc59="; print_term w59; print "\n");
val _ = observe "dec59" ``riscv$Decode ^w59``;
val w60 = ev ``riscv$Encode (System ECALL)``;
val _ = (print "enc60="; print_term w60; print "\n");
val _ = observe "dec60" ``riscv$Decode ^w60``;
val w61 = ev ``riscv$Encode (System EBREAK)``;
val _ = (print "enc61="; print_term w61; print "\n");
val _ = observe "dec61" ``riscv$Decode ^w61``;
val _ = observe "dec_zero" ``riscv$Decode 0w``;
val _ = observe "dec_ones" ``riscv$Decode 0xFFFFFFFFw``;
