load "riscvTheory";
open HolKernel Parse bossLib Tactical Tactic Conv riscvTheory;
val _ = Globals.linewidth := 100000;
val _ = (print "Run_type=";print_type(type_of ``riscv$Run``); print "\n");
val _ = print("Run_hypotheses=" ^ Int.toString(length(hyp Run_def)) ^ "\n");
fun check label q = let val th = prove(q,SIMP_TAC (srw_ss()) [Run_def]) in if null(hyp th) andalso aconv (concl th) q then (print(label^"="); print_term(concl th); print "\n") else raise Fail "unexpected assumptions or equation" end;
val _ = check "Run_AMOADD_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOADD_D x)) s = riscv$dfn'AMOADD_D x s``;
val _ = print "Run_AMOADD_D_proof=T\n";
val _ = check "Run_AMOADD_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOADD_W x)) s = riscv$dfn'AMOADD_W x s``;
val _ = print "Run_AMOADD_W_proof=T\n";
val _ = check "Run_AMOAND_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOAND_D x)) s = riscv$dfn'AMOAND_D x s``;
val _ = print "Run_AMOAND_D_proof=T\n";
val _ = check "Run_AMOAND_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOAND_W x)) s = riscv$dfn'AMOAND_W x s``;
val _ = print "Run_AMOAND_W_proof=T\n";
val _ = check "Run_AMOMAXU_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMAXU_D x)) s = riscv$dfn'AMOMAXU_D x s``;
val _ = print "Run_AMOMAXU_D_proof=T\n";
val _ = check "Run_AMOMAXU_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMAXU_W x)) s = riscv$dfn'AMOMAXU_W x s``;
val _ = print "Run_AMOMAXU_W_proof=T\n";
val _ = check "Run_AMOMAX_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMAX_D x)) s = riscv$dfn'AMOMAX_D x s``;
val _ = print "Run_AMOMAX_D_proof=T\n";
val _ = check "Run_AMOMAX_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMAX_W x)) s = riscv$dfn'AMOMAX_W x s``;
val _ = print "Run_AMOMAX_W_proof=T\n";
val _ = check "Run_AMOMINU_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMINU_D x)) s = riscv$dfn'AMOMINU_D x s``;
val _ = print "Run_AMOMINU_D_proof=T\n";
val _ = check "Run_AMOMINU_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMINU_W x)) s = riscv$dfn'AMOMINU_W x s``;
val _ = print "Run_AMOMINU_W_proof=T\n";
val _ = check "Run_AMOMIN_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMIN_D x)) s = riscv$dfn'AMOMIN_D x s``;
val _ = print "Run_AMOMIN_D_proof=T\n";
val _ = check "Run_AMOMIN_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOMIN_W x)) s = riscv$dfn'AMOMIN_W x s``;
val _ = print "Run_AMOMIN_W_proof=T\n";
val _ = check "Run_AMOOR_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOOR_D x)) s = riscv$dfn'AMOOR_D x s``;
val _ = print "Run_AMOOR_D_proof=T\n";
val _ = check "Run_AMOOR_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOOR_W x)) s = riscv$dfn'AMOOR_W x s``;
val _ = print "Run_AMOOR_W_proof=T\n";
val _ = check "Run_AMOSWAP_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOSWAP_D x)) s = riscv$dfn'AMOSWAP_D x s``;
val _ = print "Run_AMOSWAP_D_proof=T\n";
val _ = check "Run_AMOSWAP_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOSWAP_W x)) s = riscv$dfn'AMOSWAP_W x s``;
val _ = print "Run_AMOSWAP_W_proof=T\n";
val _ = check "Run_AMOXOR_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOXOR_D x)) s = riscv$dfn'AMOXOR_D x s``;
val _ = print "Run_AMOXOR_D_proof=T\n";
val _ = check "Run_AMOXOR_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$AMOXOR_W x)) s = riscv$dfn'AMOXOR_W x s``;
val _ = print "Run_AMOXOR_W_proof=T\n";
val _ = check "Run_LR_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$LR_D x)) s = riscv$dfn'LR_D x s``;
val _ = print "Run_LR_D_proof=T\n";
val _ = check "Run_LR_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$LR_W x)) s = riscv$dfn'LR_W x s``;
val _ = print "Run_LR_W_proof=T\n";
val _ = check "Run_SC_D_equation" ``!x s. riscv$Run (riscv$AMO (riscv$SC_D x)) s = riscv$dfn'SC_D x s``;
val _ = print "Run_SC_D_proof=T\n";
val _ = check "Run_SC_W_equation" ``!x s. riscv$Run (riscv$AMO (riscv$SC_W x)) s = riscv$dfn'SC_W x s``;
val _ = print "Run_SC_W_proof=T\n";
val _ = check "Run_ADDI_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$ADDI x)) s = riscv$dfn'ADDI x s``;
val _ = print "Run_ADDI_proof=T\n";
val _ = check "Run_ADDIW_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$ADDIW x)) s = riscv$dfn'ADDIW x s``;
val _ = print "Run_ADDIW_proof=T\n";
val _ = check "Run_ANDI_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$ANDI x)) s = riscv$dfn'ANDI x s``;
val _ = print "Run_ANDI_proof=T\n";
val _ = check "Run_AUIPC_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$AUIPC x)) s = riscv$dfn'AUIPC x s``;
val _ = print "Run_AUIPC_proof=T\n";
val _ = check "Run_LUI_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$LUI x)) s = riscv$dfn'LUI x s``;
val _ = print "Run_LUI_proof=T\n";
val _ = check "Run_ORI_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$ORI x)) s = riscv$dfn'ORI x s``;
val _ = print "Run_ORI_proof=T\n";
val _ = check "Run_SLTI_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$SLTI x)) s = riscv$dfn'SLTI x s``;
val _ = print "Run_SLTI_proof=T\n";
val _ = check "Run_SLTIU_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$SLTIU x)) s = riscv$dfn'SLTIU x s``;
val _ = print "Run_SLTIU_proof=T\n";
val _ = check "Run_XORI_equation" ``!x s. riscv$Run (riscv$ArithI (riscv$XORI x)) s = riscv$dfn'XORI x s``;
val _ = print "Run_XORI_proof=T\n";
val _ = check "Run_ADD_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$ADD x)) s = riscv$dfn'ADD x s``;
val _ = print "Run_ADD_proof=T\n";
val _ = check "Run_ADDW_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$ADDW x)) s = riscv$dfn'ADDW x s``;
val _ = print "Run_ADDW_proof=T\n";
val _ = check "Run_AND_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$AND x)) s = riscv$dfn'AND x s``;
val _ = print "Run_AND_proof=T\n";
val _ = check "Run_OR_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$OR x)) s = riscv$dfn'OR x s``;
val _ = print "Run_OR_proof=T\n";
val _ = check "Run_SLT_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$SLT x)) s = riscv$dfn'SLT x s``;
val _ = print "Run_SLT_proof=T\n";
val _ = check "Run_SLTU_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$SLTU x)) s = riscv$dfn'SLTU x s``;
val _ = print "Run_SLTU_proof=T\n";
val _ = check "Run_SUB_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$SUB x)) s = riscv$dfn'SUB x s``;
val _ = print "Run_SUB_proof=T\n";
val _ = check "Run_SUBW_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$SUBW x)) s = riscv$dfn'SUBW x s``;
val _ = print "Run_SUBW_proof=T\n";
val _ = check "Run_XOR_equation" ``!x s. riscv$Run (riscv$ArithR (riscv$XOR x)) s = riscv$dfn'XOR x s``;
val _ = print "Run_XOR_proof=T\n";
val _ = check "Run_BEQ_equation" ``!x s. riscv$Run (riscv$Branch (riscv$BEQ x)) s = riscv$dfn'BEQ x s``;
val _ = print "Run_BEQ_proof=T\n";
val _ = check "Run_BGE_equation" ``!x s. riscv$Run (riscv$Branch (riscv$BGE x)) s = riscv$dfn'BGE x s``;
val _ = print "Run_BGE_proof=T\n";
val _ = check "Run_BGEU_equation" ``!x s. riscv$Run (riscv$Branch (riscv$BGEU x)) s = riscv$dfn'BGEU x s``;
val _ = print "Run_BGEU_proof=T\n";
val _ = check "Run_BLT_equation" ``!x s. riscv$Run (riscv$Branch (riscv$BLT x)) s = riscv$dfn'BLT x s``;
val _ = print "Run_BLT_proof=T\n";
val _ = check "Run_BLTU_equation" ``!x s. riscv$Run (riscv$Branch (riscv$BLTU x)) s = riscv$dfn'BLTU x s``;
val _ = print "Run_BLTU_proof=T\n";
val _ = check "Run_BNE_equation" ``!x s. riscv$Run (riscv$Branch (riscv$BNE x)) s = riscv$dfn'BNE x s``;
val _ = print "Run_BNE_proof=T\n";
val _ = check "Run_JAL_equation" ``!x s. riscv$Run (riscv$Branch (riscv$JAL x)) s = riscv$dfn'JAL x s``;
val _ = print "Run_JAL_proof=T\n";
val _ = check "Run_JALR_equation" ``!x s. riscv$Run (riscv$Branch (riscv$JALR x)) s = riscv$dfn'JALR x s``;
val _ = print "Run_JALR_proof=T\n";
val _ = check "Run_FADD_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FADD_D x)) s = riscv$dfn'FADD_D x s``;
val _ = print "Run_FADD_D_proof=T\n";
val _ = check "Run_FADD_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FADD_S x)) s = riscv$dfn'FADD_S x s``;
val _ = print "Run_FADD_S_proof=T\n";
val _ = check "Run_FDIV_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FDIV_D x)) s = riscv$dfn'FDIV_D x s``;
val _ = print "Run_FDIV_D_proof=T\n";
val _ = check "Run_FDIV_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FDIV_S x)) s = riscv$dfn'FDIV_S x s``;
val _ = print "Run_FDIV_S_proof=T\n";
val _ = check "Run_FEQ_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FEQ_D x)) s = riscv$dfn'FEQ_D x s``;
val _ = print "Run_FEQ_D_proof=T\n";
val _ = check "Run_FEQ_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FEQ_S x)) s = riscv$dfn'FEQ_S x s``;
val _ = print "Run_FEQ_S_proof=T\n";
val _ = check "Run_FLE_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FLE_D x)) s = riscv$dfn'FLE_D x s``;
val _ = print "Run_FLE_D_proof=T\n";
val _ = check "Run_FLE_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FLE_S x)) s = riscv$dfn'FLE_S x s``;
val _ = print "Run_FLE_S_proof=T\n";
val _ = check "Run_FLT_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FLT_D x)) s = riscv$dfn'FLT_D x s``;
val _ = print "Run_FLT_D_proof=T\n";
val _ = check "Run_FLT_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FLT_S x)) s = riscv$dfn'FLT_S x s``;
val _ = print "Run_FLT_S_proof=T\n";
val _ = check "Run_FMADD_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMADD_D x)) s = riscv$dfn'FMADD_D x s``;
val _ = print "Run_FMADD_D_proof=T\n";
val _ = check "Run_FMADD_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMADD_S x)) s = riscv$dfn'FMADD_S x s``;
val _ = print "Run_FMADD_S_proof=T\n";
val _ = check "Run_FMAX_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMAX_D x)) s = riscv$dfn'FMAX_D x s``;
val _ = print "Run_FMAX_D_proof=T\n";
val _ = check "Run_FMAX_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMAX_S x)) s = riscv$dfn'FMAX_S x s``;
val _ = print "Run_FMAX_S_proof=T\n";
val _ = check "Run_FMIN_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMIN_D x)) s = riscv$dfn'FMIN_D x s``;
val _ = print "Run_FMIN_D_proof=T\n";
val _ = check "Run_FMIN_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMIN_S x)) s = riscv$dfn'FMIN_S x s``;
val _ = print "Run_FMIN_S_proof=T\n";
val _ = check "Run_FMSUB_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMSUB_D x)) s = riscv$dfn'FMSUB_D x s``;
val _ = print "Run_FMSUB_D_proof=T\n";
val _ = check "Run_FMSUB_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMSUB_S x)) s = riscv$dfn'FMSUB_S x s``;
val _ = print "Run_FMSUB_S_proof=T\n";
val _ = check "Run_FMUL_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMUL_D x)) s = riscv$dfn'FMUL_D x s``;
val _ = print "Run_FMUL_D_proof=T\n";
val _ = check "Run_FMUL_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FMUL_S x)) s = riscv$dfn'FMUL_S x s``;
val _ = print "Run_FMUL_S_proof=T\n";
val _ = check "Run_FNMADD_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FNMADD_D x)) s = riscv$dfn'FNMADD_D x s``;
val _ = print "Run_FNMADD_D_proof=T\n";
val _ = check "Run_FNMADD_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FNMADD_S x)) s = riscv$dfn'FNMADD_S x s``;
val _ = print "Run_FNMADD_S_proof=T\n";
val _ = check "Run_FNMSUB_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FNMSUB_D x)) s = riscv$dfn'FNMSUB_D x s``;
val _ = print "Run_FNMSUB_D_proof=T\n";
val _ = check "Run_FNMSUB_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FNMSUB_S x)) s = riscv$dfn'FNMSUB_S x s``;
val _ = print "Run_FNMSUB_S_proof=T\n";
val _ = check "Run_FSQRT_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FSQRT_D x)) s = riscv$dfn'FSQRT_D x s``;
val _ = print "Run_FSQRT_D_proof=T\n";
val _ = check "Run_FSQRT_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FSQRT_S x)) s = riscv$dfn'FSQRT_S x s``;
val _ = print "Run_FSQRT_S_proof=T\n";
val _ = check "Run_FSUB_D_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FSUB_D x)) s = riscv$dfn'FSUB_D x s``;
val _ = print "Run_FSUB_D_proof=T\n";
val _ = check "Run_FSUB_S_equation" ``!x s. riscv$Run (riscv$FArith (riscv$FSUB_S x)) s = riscv$dfn'FSUB_S x s``;
val _ = print "Run_FSUB_S_proof=T\n";
val _ = check "Run_FCLASS_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCLASS_D x)) s = riscv$dfn'FCLASS_D x s``;
val _ = print "Run_FCLASS_D_proof=T\n";
val _ = check "Run_FCLASS_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCLASS_S x)) s = riscv$dfn'FCLASS_S x s``;
val _ = print "Run_FCLASS_S_proof=T\n";
val _ = check "Run_FCVT_D_L_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_D_L x)) s = riscv$dfn'FCVT_D_L x s``;
val _ = print "Run_FCVT_D_L_proof=T\n";
val _ = check "Run_FCVT_D_LU_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_D_LU x)) s = riscv$dfn'FCVT_D_LU x s``;
val _ = print "Run_FCVT_D_LU_proof=T\n";
val _ = check "Run_FCVT_D_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_D_S x)) s = riscv$dfn'FCVT_D_S x s``;
val _ = print "Run_FCVT_D_S_proof=T\n";
val _ = check "Run_FCVT_D_W_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_D_W x)) s = riscv$dfn'FCVT_D_W x s``;
val _ = print "Run_FCVT_D_W_proof=T\n";
val _ = check "Run_FCVT_D_WU_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_D_WU x)) s = riscv$dfn'FCVT_D_WU x s``;
val _ = print "Run_FCVT_D_WU_proof=T\n";
val _ = check "Run_FCVT_LU_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_LU_D x)) s = riscv$dfn'FCVT_LU_D x s``;
val _ = print "Run_FCVT_LU_D_proof=T\n";
val _ = check "Run_FCVT_LU_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_LU_S x)) s = riscv$dfn'FCVT_LU_S x s``;
val _ = print "Run_FCVT_LU_S_proof=T\n";
val _ = check "Run_FCVT_L_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_L_D x)) s = riscv$dfn'FCVT_L_D x s``;
val _ = print "Run_FCVT_L_D_proof=T\n";
val _ = check "Run_FCVT_L_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_L_S x)) s = riscv$dfn'FCVT_L_S x s``;
val _ = print "Run_FCVT_L_S_proof=T\n";
val _ = check "Run_FCVT_S_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_S_D x)) s = riscv$dfn'FCVT_S_D x s``;
val _ = print "Run_FCVT_S_D_proof=T\n";
val _ = check "Run_FCVT_S_L_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_S_L x)) s = riscv$dfn'FCVT_S_L x s``;
val _ = print "Run_FCVT_S_L_proof=T\n";
val _ = check "Run_FCVT_S_LU_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_S_LU x)) s = riscv$dfn'FCVT_S_LU x s``;
val _ = print "Run_FCVT_S_LU_proof=T\n";
val _ = check "Run_FCVT_S_W_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_S_W x)) s = riscv$dfn'FCVT_S_W x s``;
val _ = print "Run_FCVT_S_W_proof=T\n";
val _ = check "Run_FCVT_S_WU_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_S_WU x)) s = riscv$dfn'FCVT_S_WU x s``;
val _ = print "Run_FCVT_S_WU_proof=T\n";
val _ = check "Run_FCVT_WU_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_WU_D x)) s = riscv$dfn'FCVT_WU_D x s``;
val _ = print "Run_FCVT_WU_D_proof=T\n";
val _ = check "Run_FCVT_WU_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_WU_S x)) s = riscv$dfn'FCVT_WU_S x s``;
val _ = print "Run_FCVT_WU_S_proof=T\n";
val _ = check "Run_FCVT_W_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_W_D x)) s = riscv$dfn'FCVT_W_D x s``;
val _ = print "Run_FCVT_W_D_proof=T\n";
val _ = check "Run_FCVT_W_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FCVT_W_S x)) s = riscv$dfn'FCVT_W_S x s``;
val _ = print "Run_FCVT_W_S_proof=T\n";
val _ = check "Run_FMV_D_X_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FMV_D_X x)) s = riscv$dfn'FMV_D_X x s``;
val _ = print "Run_FMV_D_X_proof=T\n";
val _ = check "Run_FMV_S_X_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FMV_S_X x)) s = riscv$dfn'FMV_S_X x s``;
val _ = print "Run_FMV_S_X_proof=T\n";
val _ = check "Run_FMV_X_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FMV_X_D x)) s = riscv$dfn'FMV_X_D x s``;
val _ = print "Run_FMV_X_D_proof=T\n";
val _ = check "Run_FMV_X_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FMV_X_S x)) s = riscv$dfn'FMV_X_S x s``;
val _ = print "Run_FMV_X_S_proof=T\n";
val _ = check "Run_FSGNJN_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FSGNJN_D x)) s = riscv$dfn'FSGNJN_D x s``;
val _ = print "Run_FSGNJN_D_proof=T\n";
val _ = check "Run_FSGNJN_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FSGNJN_S x)) s = riscv$dfn'FSGNJN_S x s``;
val _ = print "Run_FSGNJN_S_proof=T\n";
val _ = check "Run_FSGNJX_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FSGNJX_D x)) s = riscv$dfn'FSGNJX_D x s``;
val _ = print "Run_FSGNJX_D_proof=T\n";
val _ = check "Run_FSGNJX_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FSGNJX_S x)) s = riscv$dfn'FSGNJX_S x s``;
val _ = print "Run_FSGNJX_S_proof=T\n";
val _ = check "Run_FSGNJ_D_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FSGNJ_D x)) s = riscv$dfn'FSGNJ_D x s``;
val _ = print "Run_FSGNJ_D_proof=T\n";
val _ = check "Run_FSGNJ_S_equation" ``!x s. riscv$Run (riscv$FConv (riscv$FSGNJ_S x)) s = riscv$dfn'FSGNJ_S x s``;
val _ = print "Run_FSGNJ_S_proof=T\n";
val _ = check "Run_FENCE_equation" ``!x s. riscv$Run (riscv$FENCE x) s = s``;
val _ = print "Run_FENCE_proof=T\n";
val _ = check "Run_FENCE_I_equation" ``!x s. riscv$Run (riscv$FENCE_I x) s = s``;
val _ = print "Run_FENCE_I_proof=T\n";
val _ = check "Run_FLD_equation" ``!x s. riscv$Run (riscv$FPLoad (riscv$FLD x)) s = riscv$dfn'FLD x s``;
val _ = print "Run_FLD_proof=T\n";
val _ = check "Run_FLW_equation" ``!x s. riscv$Run (riscv$FPLoad (riscv$FLW x)) s = riscv$dfn'FLW x s``;
val _ = print "Run_FLW_proof=T\n";
val _ = check "Run_FSD_equation" ``!x s. riscv$Run (riscv$FPStore (riscv$FSD x)) s = riscv$dfn'FSD x s``;
val _ = print "Run_FSD_proof=T\n";
val _ = check "Run_FSW_equation" ``!x s. riscv$Run (riscv$FPStore (riscv$FSW x)) s = riscv$dfn'FSW x s``;
val _ = print "Run_FSW_proof=T\n";
val _ = check "Run_FETCH_FAULT_equation" ``!x s. riscv$Run (riscv$Internal (riscv$FETCH_FAULT x)) s = riscv$dfn'FETCH_FAULT x s``;
val _ = print "Run_FETCH_FAULT_proof=T\n";
val _ = check "Run_FETCH_MISALIGNED_equation" ``!x s. riscv$Run (riscv$Internal (riscv$FETCH_MISALIGNED x)) s = riscv$dfn'FETCH_MISALIGNED x s``;
val _ = print "Run_FETCH_MISALIGNED_proof=T\n";
val _ = check "Run_LB_equation" ``!x s. riscv$Run (riscv$Load (riscv$LB x)) s = riscv$dfn'LB x s``;
val _ = print "Run_LB_proof=T\n";
val _ = check "Run_LBU_equation" ``!x s. riscv$Run (riscv$Load (riscv$LBU x)) s = riscv$dfn'LBU x s``;
val _ = print "Run_LBU_proof=T\n";
val _ = check "Run_LD_equation" ``!x s. riscv$Run (riscv$Load (riscv$LD x)) s = riscv$dfn'LD x s``;
val _ = print "Run_LD_proof=T\n";
val _ = check "Run_LH_equation" ``!x s. riscv$Run (riscv$Load (riscv$LH x)) s = riscv$dfn'LH x s``;
val _ = print "Run_LH_proof=T\n";
val _ = check "Run_LHU_equation" ``!x s. riscv$Run (riscv$Load (riscv$LHU x)) s = riscv$dfn'LHU x s``;
val _ = print "Run_LHU_proof=T\n";
val _ = check "Run_LW_equation" ``!x s. riscv$Run (riscv$Load (riscv$LW x)) s = riscv$dfn'LW x s``;
val _ = print "Run_LW_proof=T\n";
val _ = check "Run_LWU_equation" ``!x s. riscv$Run (riscv$Load (riscv$LWU x)) s = riscv$dfn'LWU x s``;
val _ = print "Run_LWU_proof=T\n";
val _ = check "Run_DIV_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$DIV x)) s = riscv$dfn'DIV x s``;
val _ = print "Run_DIV_proof=T\n";
val _ = check "Run_DIVU_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$DIVU x)) s = riscv$dfn'DIVU x s``;
val _ = print "Run_DIVU_proof=T\n";
val _ = check "Run_DIVUW_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$DIVUW x)) s = riscv$dfn'DIVUW x s``;
val _ = print "Run_DIVUW_proof=T\n";
val _ = check "Run_DIVW_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$DIVW x)) s = riscv$dfn'DIVW x s``;
val _ = print "Run_DIVW_proof=T\n";
val _ = check "Run_MUL_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$MUL x)) s = riscv$dfn'MUL x s``;
val _ = print "Run_MUL_proof=T\n";
val _ = check "Run_MULH_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$MULH x)) s = riscv$dfn'MULH x s``;
val _ = print "Run_MULH_proof=T\n";
val _ = check "Run_MULHSU_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$MULHSU x)) s = riscv$dfn'MULHSU x s``;
val _ = print "Run_MULHSU_proof=T\n";
val _ = check "Run_MULHU_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$MULHU x)) s = riscv$dfn'MULHU x s``;
val _ = print "Run_MULHU_proof=T\n";
val _ = check "Run_MULW_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$MULW x)) s = riscv$dfn'MULW x s``;
val _ = print "Run_MULW_proof=T\n";
val _ = check "Run_REM_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$REM x)) s = riscv$dfn'REM x s``;
val _ = print "Run_REM_proof=T\n";
val _ = check "Run_REMU_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$REMU x)) s = riscv$dfn'REMU x s``;
val _ = print "Run_REMU_proof=T\n";
val _ = check "Run_REMUW_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$REMUW x)) s = riscv$dfn'REMUW x s``;
val _ = print "Run_REMUW_proof=T\n";
val _ = check "Run_REMW_equation" ``!x s. riscv$Run (riscv$MulDiv (riscv$REMW x)) s = riscv$dfn'REMW x s``;
val _ = print "Run_REMW_proof=T\n";
val _ = check "Run_SLL_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SLL x)) s = riscv$dfn'SLL x s``;
val _ = print "Run_SLL_proof=T\n";
val _ = check "Run_SLLI_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SLLI x)) s = riscv$dfn'SLLI x s``;
val _ = print "Run_SLLI_proof=T\n";
val _ = check "Run_SLLIW_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SLLIW x)) s = riscv$dfn'SLLIW x s``;
val _ = print "Run_SLLIW_proof=T\n";
val _ = check "Run_SLLW_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SLLW x)) s = riscv$dfn'SLLW x s``;
val _ = print "Run_SLLW_proof=T\n";
val _ = check "Run_SRA_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRA x)) s = riscv$dfn'SRA x s``;
val _ = print "Run_SRA_proof=T\n";
val _ = check "Run_SRAI_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRAI x)) s = riscv$dfn'SRAI x s``;
val _ = print "Run_SRAI_proof=T\n";
val _ = check "Run_SRAIW_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRAIW x)) s = riscv$dfn'SRAIW x s``;
val _ = print "Run_SRAIW_proof=T\n";
val _ = check "Run_SRAW_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRAW x)) s = riscv$dfn'SRAW x s``;
val _ = print "Run_SRAW_proof=T\n";
val _ = check "Run_SRL_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRL x)) s = riscv$dfn'SRL x s``;
val _ = print "Run_SRL_proof=T\n";
val _ = check "Run_SRLI_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRLI x)) s = riscv$dfn'SRLI x s``;
val _ = print "Run_SRLI_proof=T\n";
val _ = check "Run_SRLIW_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRLIW x)) s = riscv$dfn'SRLIW x s``;
val _ = print "Run_SRLIW_proof=T\n";
val _ = check "Run_SRLW_equation" ``!x s. riscv$Run (riscv$Shift (riscv$SRLW x)) s = riscv$dfn'SRLW x s``;
val _ = print "Run_SRLW_proof=T\n";
val _ = check "Run_SB_equation" ``!x s. riscv$Run (riscv$Store (riscv$SB x)) s = riscv$dfn'SB x s``;
val _ = print "Run_SB_proof=T\n";
val _ = check "Run_SD_equation" ``!x s. riscv$Run (riscv$Store (riscv$SD x)) s = riscv$dfn'SD x s``;
val _ = print "Run_SD_proof=T\n";
val _ = check "Run_SH_equation" ``!x s. riscv$Run (riscv$Store (riscv$SH x)) s = riscv$dfn'SH x s``;
val _ = print "Run_SH_proof=T\n";
val _ = check "Run_SW_equation" ``!x s. riscv$Run (riscv$Store (riscv$SW x)) s = riscv$dfn'SW x s``;
val _ = print "Run_SW_proof=T\n";
val _ = check "Run_CSRRC_equation" ``!x s. riscv$Run (riscv$System (riscv$CSRRC x)) s = riscv$dfn'CSRRC x s``;
val _ = print "Run_CSRRC_proof=T\n";
val _ = check "Run_CSRRCI_equation" ``!x s. riscv$Run (riscv$System (riscv$CSRRCI x)) s = riscv$dfn'CSRRCI x s``;
val _ = print "Run_CSRRCI_proof=T\n";
val _ = check "Run_CSRRS_equation" ``!x s. riscv$Run (riscv$System (riscv$CSRRS x)) s = riscv$dfn'CSRRS x s``;
val _ = print "Run_CSRRS_proof=T\n";
val _ = check "Run_CSRRSI_equation" ``!x s. riscv$Run (riscv$System (riscv$CSRRSI x)) s = riscv$dfn'CSRRSI x s``;
val _ = print "Run_CSRRSI_proof=T\n";
val _ = check "Run_CSRRW_equation" ``!x s. riscv$Run (riscv$System (riscv$CSRRW x)) s = riscv$dfn'CSRRW x s``;
val _ = print "Run_CSRRW_proof=T\n";
val _ = check "Run_CSRRWI_equation" ``!x s. riscv$Run (riscv$System (riscv$CSRRWI x)) s = riscv$dfn'CSRRWI x s``;
val _ = print "Run_CSRRWI_proof=T\n";
val _ = check "Run_EBREAK_equation" ``!s. riscv$Run (riscv$System (riscv$EBREAK)) s = riscv$dfn'EBREAK s``;
val _ = print "Run_EBREAK_proof=T\n";
val _ = check "Run_ECALL_equation" ``!s. riscv$Run (riscv$System (riscv$ECALL)) s = riscv$dfn'ECALL s``;
val _ = print "Run_ECALL_proof=T\n";
val _ = check "Run_ERET_equation" ``!s. riscv$Run (riscv$System (riscv$ERET)) s = riscv$dfn'ERET s``;
val _ = print "Run_ERET_proof=T\n";
val _ = check "Run_MRTS_equation" ``!s. riscv$Run (riscv$System (riscv$MRTS)) s = riscv$dfn'MRTS s``;
val _ = print "Run_MRTS_proof=T\n";
val _ = check "Run_SFENCE_VM_equation" ``!x s. riscv$Run (riscv$System (riscv$SFENCE_VM x)) s = riscv$dfn'SFENCE_VM x s``;
val _ = print "Run_SFENCE_VM_proof=T\n";
val _ = check "Run_WFI_equation" ``!s. riscv$Run (riscv$System (riscv$WFI)) s = s``;
val _ = print "Run_WFI_proof=T\n";
val _ = check "Run_UnknownInstruction_equation" ``!s. riscv$Run (riscv$UnknownInstruction) s = riscv$dfn'UnknownInstruction s``;
val _ = print "Run_UnknownInstruction_proof=T\n";
