val _ = loadPath := (Globals.HOLDIR ^ "/examples/l3-machine-code/riscv/step") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/riscv/model") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/common") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/lib") :: !loadPath;
load "riscv_stepTheory"; load "binary_ieeeLib"; load "wordsLib"; load "bitstringLib";
open HolKernel Parse boolLib bossLib;
val _ = Globals.max_print_depth := 1000;
val _ = Parse.temp_remove_user_printer ("num.numeral_computations", mk_var("n", numSyntax.num));
val () = computeLib.add_funs (map snd (DB.definitions "riscv"));
val () = computeLib.add_funs (map snd (DB.definitions "riscv_step"));
val () = computeLib.add_funs [machine_ieeeTheory.fp32_compare_def,
 machine_ieeeTheory.fp64_compare_def, machine_ieeeTheory.fp32_to_float_def,
 machine_ieeeTheory.fp64_to_float_def, machine_ieeeTheory.float_to_fp32_def,
 machine_ieeeTheory.float_to_fp64_def, machine_ieeeTheory.fp32_posInf_def,
 machine_ieeeTheory.fp64_posInf_def];
val conv = EVAL THENC DEPTH_CONV bitstringLib.v2w_n2w_CONV THENC EVAL;
fun observe label tm = (print(label ^ "="); print_term(rhs(concl(conv tm))); print "\n");
val s = ``(ARB:riscv_state) with <| procID := 0w;
 c_gpr := (\_ r. if r = 3w then 99w else 0w);
 c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>);
 c_MCSR := (\_. (ARB:MachineCSR) with mstatus := (ARB:mstatus)) |>``;
val s_S_one_two = ``^s with c_fpr := (\_ r. if r = 1w then 0x3f800000w else if r = 2w then 0x40000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_one_two" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_one_two" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_one_two" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_one_two" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_one_two" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_signed_zero = ``^s with c_fpr := (\_ r. if r = 1w then 0x0w else if r = 2w then 0x80000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_signed_zero" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_signed_zero" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_signed_zero" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_signed_zero" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_signed_zero" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_qnan_one = ``^s with c_fpr := (\_ r. if r = 1w then 0x7fc00000w else if r = 2w then 0x3f800000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_qnan_one" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_qnan_one" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_qnan_one" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_qnan_one" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_qnan_one" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_snan_one = ``^s with c_fpr := (\_ r. if r = 1w then 0x7f800001w else if r = 2w then 0x3f800000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_snan_one" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_snan_one" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_snan_one" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_snan_one" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_snan_one" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_payload_nan_one = ``^s with c_fpr := (\_ r. if r = 1w then 0x7fc00001w else if r = 2w then 0x3f800000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_payload_nan_one" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_payload_nan_one" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_payload_nan_one" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_payload_nan_one" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_payload_nan_one" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_both_nan = ``^s with c_fpr := (\_ r. if r = 1w then 0x7fc00000w else if r = 2w then 0x7fc00000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_both_nan" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_both_nan" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_both_nan" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_both_nan" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_both_nan" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_infinities = ``^s with c_fpr := (\_ r. if r = 1w then 0x7f800000w else if r = 2w then 0xff800000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_infinities" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_infinities" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_infinities" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_infinities" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_infinities" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_S_subnormals = ``^s with c_fpr := (\_ r. if r = 1w then 0x1w else if r = 2w then 0x2w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_s_subnormals" ``let r = dfn'FMIN_S (3w,1w,2w) ^s_S_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_s_subnormals" ``let r = dfn'FMAX_S (3w,1w,2w) ^s_S_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_s_subnormals" ``let r = dfn'FLT_S (3w,1w,2w) ^s_S_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_s_subnormals" ``let r = dfn'FLE_S (3w,1w,2w) ^s_S_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_s_subnormals" ``let r = dfn'FEQ_S (3w,1w,2w) ^s_S_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_one_two = ``^s with c_fpr := (\_ r. if r = 1w then 0x3ff0000000000000w else if r = 2w then 0x4000000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_one_two" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_one_two" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_one_two" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_one_two" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_one_two" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_one_two in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_signed_zero = ``^s with c_fpr := (\_ r. if r = 1w then 0x0w else if r = 2w then 0x8000000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_signed_zero" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_signed_zero" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_signed_zero" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_signed_zero" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_signed_zero" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_signed_zero in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_qnan_one = ``^s with c_fpr := (\_ r. if r = 1w then 0x7ff8000000000000w else if r = 2w then 0x3ff0000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_qnan_one" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_qnan_one" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_qnan_one" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_qnan_one" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_qnan_one" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_qnan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_snan_one = ``^s with c_fpr := (\_ r. if r = 1w then 0x7ff0000000000001w else if r = 2w then 0x3ff0000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_snan_one" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_snan_one" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_snan_one" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_snan_one" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_snan_one" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_snan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_payload_nan_one = ``^s with c_fpr := (\_ r. if r = 1w then 0x7ff8000000000001w else if r = 2w then 0x3ff0000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_payload_nan_one" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_payload_nan_one" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_payload_nan_one" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_payload_nan_one" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_payload_nan_one" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_payload_nan_one in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_both_nan = ``^s with c_fpr := (\_ r. if r = 1w then 0x7ff8000000000000w else if r = 2w then 0x7ff8000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_both_nan" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_both_nan" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_both_nan" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_both_nan" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_both_nan" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_both_nan in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_infinities = ``^s with c_fpr := (\_ r. if r = 1w then 0x7ff0000000000000w else if r = 2w then 0xfff0000000000000w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_infinities" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_infinities" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_infinities" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_infinities" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_infinities" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_infinities in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val s_D_subnormals = ``^s with c_fpr := (\_ r. if r = 1w then 0x1w else if r = 2w then 0x2w else if r = 3w then 0xabc0000000000000w else 0w)``;
val _ = observe "fmin_d_subnormals" ``let r = dfn'FMIN_D (3w,1w,2w) ^s_D_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fmax_d_subnormals" ``let r = dfn'FMAX_D (3w,1w,2w) ^s_D_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "flt_d_subnormals" ``let r = dfn'FLT_D (3w,1w,2w) ^s_D_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "fle_d_subnormals" ``let r = dfn'FLE_D (3w,1w,2w) ^s_D_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "feq_d_subnormals" ``let r = dfn'FEQ_D (3w,1w,2w) ^s_D_subnormals in (GPR 3w r, FPRD 3w r, (fcsr r).NV)``;
val _ = observe "positive_infinities" ``(machine_ieee$fp32_posInf,machine_ieee$fp64_posInf)``;
val _ = observe "nan_classifications32" ``MAP machine_ieee$fp32_isNan [0w;0x7f800000w;0x7fc00000w;0x7f800001w;0x7fc00001w]``;
val _ = observe "nan_classifications64" ``MAP machine_ieee$fp64_isNan [0w;0x7ff0000000000000w;0x7ff8000000000000w;0x7ff0000000000001w;0x7ff8000000000001w]``;
val _ = OS.Process.exit OS.Process.success;
