val _ = loadPath := (Globals.HOLDIR ^ "/examples/l3-machine-code/riscv/step") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/riscv/model") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/common") ::
  (Globals.HOLDIR ^ "/examples/l3-machine-code/lib") :: !loadPath;
load "riscv_stepTheory"; load "binary_ieeeLib"; load "wordsLib"; load "bitstringLib";
open HolKernel Parse boolLib bossLib;
val _ = Globals.max_print_depth := 1000;
val _ = Parse.temp_remove_user_printer ("num.numeral_computations", mk_var("n", numSyntax.num));
val () = computeLib.add_funs (map snd (DB.definitions "riscv"));
val () = computeLib.add_funs (map snd (DB.definitions "riscv_step"));
val () = computeLib.add_funs [machine_ieeeTheory.fp32_compare_def,
 machine_ieeeTheory.fp64_compare_def, machine_ieeeTheory.fp32_to_float_def,
 machine_ieeeTheory.fp64_to_float_def, machine_ieeeTheory.float_to_fp32_def,
 machine_ieeeTheory.float_to_fp64_def, machine_ieeeTheory.fp32_posInf_def,
 machine_ieeeTheory.fp64_posInf_def, machine_ieeeTheory.fp32_negInf_def,
 machine_ieeeTheory.fp64_negInf_def, machine_ieeeTheory.fp32_to_int_def,
 machine_ieeeTheory.fp64_to_int_def, binary_ieeeTheory.float_to_int_def];
val conv = EVAL THENC DEPTH_CONV bitstringLib.v2w_n2w_CONV THENC EVAL;
fun observe label tm = (print(label ^ "="); print_term(rhs(concl(conv tm))); print "\n");
val s = ``(ARB:riscv_state) with <| procID := 0w;
 c_gpr := (\_ r. if r = 3w then 99w else 0w);
 c_NextFetch := (\_. NONE);
 c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>);
 c_MCSR := (\_. (ARB:MachineCSR) with mstatus := (ARB:mstatus)) |>``;
val s_S_tie_even = ``(^s with c_fpr := (\_ r. if r = 1w then 0x40200000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_tie_even" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_tie_even" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_tie_even" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_tie_even" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_tie_odd = ``(^s with c_fpr := (\_ r. if r = 1w then 0x40600000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_tie_odd" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_tie_odd" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_tie_odd" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_tie_odd" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_negative_zero = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc0200000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_negative_zero" ``let r = dfn'FCVT_W_S (3w,1w,1w) ^s_S_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_negative_zero" ``let r = dfn'FCVT_WU_S (3w,1w,1w) ^s_S_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_negative_zero" ``let r = dfn'FCVT_L_S (3w,1w,1w) ^s_S_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_negative_zero" ``let r = dfn'FCVT_LU_S (3w,1w,1w) ^s_S_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_negative_floor = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc0200000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_negative_floor" ``let r = dfn'FCVT_W_S (3w,1w,2w) ^s_S_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_negative_floor" ``let r = dfn'FCVT_WU_S (3w,1w,2w) ^s_S_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_negative_floor" ``let r = dfn'FCVT_L_S (3w,1w,2w) ^s_S_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_negative_floor" ``let r = dfn'FCVT_LU_S (3w,1w,2w) ^s_S_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_negative_ceil = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc0200000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_negative_ceil" ``let r = dfn'FCVT_W_S (3w,1w,3w) ^s_S_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_negative_ceil" ``let r = dfn'FCVT_WU_S (3w,1w,3w) ^s_S_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_negative_ceil" ``let r = dfn'FCVT_L_S (3w,1w,3w) ^s_S_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_negative_ceil" ``let r = dfn'FCVT_LU_S (3w,1w,3w) ^s_S_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_qnan = ``(^s with c_fpr := (\_ r. if r = 1w then 0x7fc00000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_qnan" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_qnan" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_qnan" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_qnan" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_posinf = ``(^s with c_fpr := (\_ r. if r = 1w then 0x7f800000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_posinf" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_posinf" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_posinf" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_posinf" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_neginf = ``(^s with c_fpr := (\_ r. if r = 1w then 0xff800000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_neginf" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_neginf" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_neginf" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_neginf" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_overflow = ``(^s with c_fpr := (\_ r. if r = 1w then 0x5f800000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_overflow" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_overflow" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_overflow" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_overflow" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_negative_range = ``(^s with c_fpr := (\_ r. if r = 1w then 0xdf800000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_negative_range" ``let r = dfn'FCVT_W_S (3w,1w,0w) ^s_S_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_negative_range" ``let r = dfn'FCVT_WU_S (3w,1w,0w) ^s_S_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_negative_range" ``let r = dfn'FCVT_L_S (3w,1w,0w) ^s_S_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_negative_range" ``let r = dfn'FCVT_LU_S (3w,1w,0w) ^s_S_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_dynamic_ceil = ``(^s with c_fpr := (\_ r. if r = 1w then 0x40200000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 3w |>)``;
val _ = observe "fcvt_w_s_dynamic_ceil" ``let r = dfn'FCVT_W_S (3w,1w,7w) ^s_S_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_dynamic_ceil" ``let r = dfn'FCVT_WU_S (3w,1w,7w) ^s_S_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_dynamic_ceil" ``let r = dfn'FCVT_L_S (3w,1w,7w) ^s_S_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_dynamic_ceil" ``let r = dfn'FCVT_LU_S (3w,1w,7w) ^s_S_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_S_invalid = ``(^s with c_fpr := (\_ r. if r = 1w then 0x3f800000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_s_invalid" ``let r = dfn'FCVT_W_S (3w,1w,4w) ^s_S_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_s_invalid" ``let r = dfn'FCVT_WU_S (3w,1w,4w) ^s_S_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_s_invalid" ``let r = dfn'FCVT_L_S (3w,1w,4w) ^s_S_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_s_invalid" ``let r = dfn'FCVT_LU_S (3w,1w,4w) ^s_S_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_tie_even = ``(^s with c_fpr := (\_ r. if r = 1w then 0x4004000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_tie_even" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_tie_even" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_tie_even" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_tie_even" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_tie_even in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_tie_odd = ``(^s with c_fpr := (\_ r. if r = 1w then 0x400c000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_tie_odd" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_tie_odd" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_tie_odd" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_tie_odd" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_tie_odd in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_negative_zero = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc004000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_negative_zero" ``let r = dfn'FCVT_W_D (3w,1w,1w) ^s_D_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_negative_zero" ``let r = dfn'FCVT_WU_D (3w,1w,1w) ^s_D_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_negative_zero" ``let r = dfn'FCVT_L_D (3w,1w,1w) ^s_D_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_negative_zero" ``let r = dfn'FCVT_LU_D (3w,1w,1w) ^s_D_negative_zero in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_negative_floor = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc004000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_negative_floor" ``let r = dfn'FCVT_W_D (3w,1w,2w) ^s_D_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_negative_floor" ``let r = dfn'FCVT_WU_D (3w,1w,2w) ^s_D_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_negative_floor" ``let r = dfn'FCVT_L_D (3w,1w,2w) ^s_D_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_negative_floor" ``let r = dfn'FCVT_LU_D (3w,1w,2w) ^s_D_negative_floor in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_negative_ceil = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc004000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_negative_ceil" ``let r = dfn'FCVT_W_D (3w,1w,3w) ^s_D_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_negative_ceil" ``let r = dfn'FCVT_WU_D (3w,1w,3w) ^s_D_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_negative_ceil" ``let r = dfn'FCVT_L_D (3w,1w,3w) ^s_D_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_negative_ceil" ``let r = dfn'FCVT_LU_D (3w,1w,3w) ^s_D_negative_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_qnan = ``(^s with c_fpr := (\_ r. if r = 1w then 0x7ff8000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_qnan" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_qnan" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_qnan" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_qnan" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_qnan in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_posinf = ``(^s with c_fpr := (\_ r. if r = 1w then 0x7ff0000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_posinf" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_posinf" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_posinf" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_posinf" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_posinf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_neginf = ``(^s with c_fpr := (\_ r. if r = 1w then 0xfff0000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_neginf" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_neginf" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_neginf" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_neginf" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_neginf in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_overflow = ``(^s with c_fpr := (\_ r. if r = 1w then 0x43f0000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_overflow" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_overflow" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_overflow" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_overflow" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_overflow in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_negative_range = ``(^s with c_fpr := (\_ r. if r = 1w then 0xc3f0000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_negative_range" ``let r = dfn'FCVT_W_D (3w,1w,0w) ^s_D_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_negative_range" ``let r = dfn'FCVT_WU_D (3w,1w,0w) ^s_D_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_negative_range" ``let r = dfn'FCVT_L_D (3w,1w,0w) ^s_D_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_negative_range" ``let r = dfn'FCVT_LU_D (3w,1w,0w) ^s_D_negative_range in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_dynamic_ceil = ``(^s with c_fpr := (\_ r. if r = 1w then 0x4004000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 3w |>)``;
val _ = observe "fcvt_w_d_dynamic_ceil" ``let r = dfn'FCVT_W_D (3w,1w,7w) ^s_D_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_dynamic_ceil" ``let r = dfn'FCVT_WU_D (3w,1w,7w) ^s_D_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_dynamic_ceil" ``let r = dfn'FCVT_L_D (3w,1w,7w) ^s_D_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_dynamic_ceil" ``let r = dfn'FCVT_LU_D (3w,1w,7w) ^s_D_dynamic_ceil in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val s_D_invalid = ``(^s with c_fpr := (\_ r. if r = 1w then 0x3ff0000000000000w else 0w)) with c_UCSR := (\_. (ARB:UserCSR) with fpcsr := (ARB:FPCSR) with <| NV := F; FRM := 0w |>)``;
val _ = observe "fcvt_w_d_invalid" ``let r = dfn'FCVT_W_D (3w,1w,4w) ^s_D_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_wu_d_invalid" ``let r = dfn'FCVT_WU_D (3w,1w,4w) ^s_D_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_l_d_invalid" ``let r = dfn'FCVT_L_D (3w,1w,4w) ^s_D_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
val _ = observe "fcvt_lu_d_invalid" ``let r = dfn'FCVT_LU_D (3w,1w,4w) ^s_D_invalid in (GPR 3w r, FPRD 1w r, (fcsr r).NV, case NextFetch r of SOME (Trap t) => t.trap = Illegal_Instr /\ t.badaddr = NONE | _ => F)``;
