load "riscvTheory";
open HolKernel Parse bossLib Tactical Tactic Conv riscvTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "writePC_type=";print_type(type_of ``riscv$write'PC``);print "\n");
val _ = print ("writePC_hypotheses=" ^ Int.toString(length(hyp write'PC_def)) ^ "\n");
fun check label q = let val th = prove(q,SIMP_TAC (srw_ss()) [write'PC_def, PC_def, combinTheory.UPDATE_def] THEN METIS_TAC []) in if null(hyp th) andalso aconv (concl th) q then (print(label^"=");print_term(concl th);print "\n") else raise Fail "unexpected hypotheses/equation" end;
val _ = check "writePC_fullRecord_equation" ``!v s. riscv$write'PC v s = s with c_PC := (s.procID =+ v) s.c_PC``;
val _ = print "writePC_fullRecord_proof=T\n";
val _ = check "writePC_allKeys_equation" ``!v s k. (riscv$write'PC v s).c_PC k = if k=s.procID then v else s.c_PC k``;
val _ = print "writePC_allKeys_proof=T\n";
val _ = check "writePC_current_equation" ``!v s. riscv$PC (riscv$write'PC v s) = v``;
val _ = print "writePC_current_proof=T\n";
