load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_enc_with_nop_pad_section01" lines_enc_with_nop_pad_section01;
val _ = types "lines_enc_with_nop_pad_section01_types" lines_enc_with_nop_pad_section01;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) []) (rconc(EVAL q)))); print "\n");
val enc = ``(λa:8 asm. case a of Jump w => [w;w] | JumpCmp c r i w => [w;w] | Loc r w => [w;w] | _ => [0w;0w])``;
val aux = ``[Label 1 2 0;Asm (Asmi (Inst Skip)) [0w;0w] 2]:8 labLang$line list``;
val code = ``[LabAsm (Jump (Lab 1 2)) 77w [249w;249w] 6;Label 1 9 0;LabAsm Halt 88w [227w;227w] 4]:8 labLang$line list``;
val _ = observe "multibyte_full_guards" ``0<LENGTH(^enc(Inst Skip)) /\ EVERY (line_aligned 2) ^code /\ lines_encd ^enc LN [] (5+SUM(MAP line_len ^aux)) ^code /\ lines_enc_with_nop ^enc LN [] 5 (REVERSE ^aux) /\ ~EVERY is_Label ^aux /\ EVERY label_zero ^code``;
val _ = observe "multibyte_padded_encoding" ``lines_enc_with_nop ^enc LN [] 5 (pad_section [0w;0w] ^code ^aux)``;
val _ = observe "multibyte_full_tuple" ``pad_section [0w;0w] ^code ^aux = [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 1 2 0;LabAsm (Jump (Lab 1 2)) 77w [249w;249w;0w;0w;0w;0w] 6;Label 1 9 0;LabAsm Halt 88w [227w;227w;0w;0w] 4]``;
val _ = observe "empty_code" ``lines_enc_with_nop ^enc LN [] 5 (pad_section [0w;0w] [] ^aux)``;
val shortenc = ``(λa:8 asm. case a of Inst Skip=>[0w;0w] | _=>[7w]):8 asm -> word8 list``;
val _ = observe "physical_alignment_guard_required" ``line_encd ^shortenc LN [] 7 (LabAsm Halt 77w [7w] 4) /\ ~line_aligned 2 (LabAsm Halt 77w [7w] 4) /\ ~line_enc_with_nop ^shortenc LN [] 7 (LabAsm Halt 77w (pad_bytes [7w] 4 [0w;0w]) 4)``;
val _ = observe "annotation_alignment_guard_required" ``line_encd ^enc LN [] 7 (LabAsm (Jump (Lab 1 2)) 77w [249w;249w] 3) /\ ~line_aligned 2 (LabAsm (Jump (Lab 1 2)) 77w [249w;249w] 3) /\ ~line_enc_with_nop ^enc LN [] 7 (LabAsm (Jump (Lab 1 2)) 77w (pad_bytes [249w;249w] 3 [0w;0w]) 3)``;
val _ = observe "jump_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (Jump (Lab 1 2)) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (Jump (Lab 1 2)) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (Jump (Lab 1 2)) 77w [0w;0w] 6] ^aux)``;
val _ = observe "jumpcmp_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (JumpCmp Equal 0 (Reg 1) (Lab 1 2)) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (JumpCmp Equal 0 (Reg 1) (Lab 1 2)) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (JumpCmp Equal 0 (Reg 1) (Lab 1 2)) 77w [0w;0w] 6] ^aux)``;
val _ = observe "locvalue_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (LocValue 0 (Lab 1 2)) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (LocValue 0 (Lab 1 2)) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (LocValue 0 (Lab 1 2)) 77w [0w;0w] 6] ^aux)``;
val _ = observe "call_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (Call (Lab 1 2)) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (Call (Lab 1 2)) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (Call (Lab 1 2)) 77w [0w;0w] 6] ^aux)``;
val _ = observe "ffi_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (CallFFI (strlit "")) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (CallFFI (strlit "")) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (CallFFI (strlit "")) 77w [0w;0w] 6] ^aux)``;
val _ = observe "install_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (Install) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (Install) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (Install) 77w [0w;0w] 6] ^aux)``;
val _ = observe "halt_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w;0w]) LN [] 7 [LabAsm (Halt) 77w [0w;0w] 6] /\ line_aligned 2 (LabAsm (Halt) 77w [0w;0w] 6) /\ lines_enc_with_nop (λa:8 asm.[0w;0w]) LN [] 5 (pad_section [0w;0w] [LabAsm (Halt) 77w [0w;0w] 6] ^aux)``;
