load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory labPropsTheory labSemTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun captureTypes label th = (print(label ^ "="); app (fn v =>
 print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))
 (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "label_zero_def" label_zero_def;
val _ = captureTypes "label_zero_def_types" label_zero_def;
val _ = capture "sec_label_zero_def" sec_label_zero_def;
val _ = captureTypes "sec_label_zero_def_types" sec_label_zero_def;
val _ = capture "sec_label_zero_pos_val_0" sec_label_zero_pos_val_0;
val _ = captureTypes "sec_label_zero_pos_val_0_types" sec_label_zero_pos_val_0;
val _ = capture "pos_val_append" pos_val_append;
val _ = captureTypes "pos_val_append_types" pos_val_append;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc((SIMP_CONV (srw_ss()) [] THENC EVAL THENC SIMP_CONV (srw_ss()) [] THENC EVAL) q)); print "\n");
val prefix = ``[Section 1 [Label 1 1 7; Asm (Cbw 1 2) [1w;2w] 99; Label 1 2 0; LabAsm Halt 0w [3w] 88; Label 1 3 9]] : 8 labLang$prog``;
val suffix = ``[Section 2 [Label 2 4 0; Asm (Cbw 3 4) [4w;5w;6w] 77; Label 2 5 0]; Section 3 []] : 8 labLang$prog``;
val labels = ``[Section 9 [Label 9 1 2; Label 9 2 99]] : 8 labLang$prog``;
val _ = observe "zero_label" ``label_zero (Label 1 2 0:1 labLang$line)``;
val _ = observe "nonzero_label" ``label_zero (Label 1 2 9:80 labLang$line) = F``;
val _ = observe "asm_annotation_ignored" ``label_zero (Asm (Cbw 1 2) [] 99:8 labLang$line)``;
val _ = observe "labasm_annotation_ignored" ``label_zero (LabAsm Halt 0w [] 88:8 labLang$line)``;
val _ = observe "suffix_valid" ``EVERY sec_label_zero ^suffix``;
val _ = observe "prefix_invalid" ``EVERY sec_label_zero ^prefix = F``;
val _ = observe "zero_suffix_position" ``pos_val 0 10 ^suffix = 10``;
val _ = observe "before_boundary" ``pos_val 1 10 (^prefix ++ ^suffix) = 13``;
val _ = observe "at_boundary" ``pos_val 2 10 (^prefix ++ ^suffix) = 15``;
val _ = observe "prefix_at_boundary" ``pos_val 2 10 ^prefix = 15``;
val _ = observe "suffix_at_boundary" ``pos_val 0 15 ^suffix = 15``;
val _ = observe "past_boundary" ``pos_val 3 10 (^prefix ++ ^suffix) = 18``;
val _ = observe "far_past_boundary" ``pos_val 99 10 (^prefix ++ ^suffix) = 18``;
val _ = observe "empty_prefix_zero" ``pos_val 0 10 (([]:8 labLang$prog) ++ ^suffix) = 10``;
val _ = observe "empty_suffix_past" ``pos_val 99 10 (^prefix ++ []) = 15``;
val _ = observe "label_only_prefix_boundary" ``pos_val 0 10 (^labels ++ ^suffix) = 12``;
val _ = observe "label_only_prefix_past" ``pos_val 1 10 (^labels ++ ^suffix) = 15``;
