load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_upd_lab_len_pos_ok" lines_upd_lab_len_pos_ok;
val _ = types "lines_upd_lab_len_pos_ok_types" lines_upd_lab_len_pos_ok;
val _ = capture "upd_lab_len_pos_ok" upd_lab_len_pos_ok;
val _ = types "upd_lab_len_pos_ok_types" upd_lab_len_pos_ok;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL q)))); print "\n");
val lines = ``[Label 1 2 97;Label 1 3 99;Asm(Asmi(Inst Skip)) [7w] 3;LabAsm(Call(Lab 1 2)) 77w [8w;9w] 2;Label 1 4 7]:8 labLang$line list``;
val code = ``[Section 7 ^lines;Section 8 [Label 1 9 99;Asm(Asmi(Inst Skip)) [] 1;Label 1 10 77];Section 9 []]:8 labLang$sec list``;
val _ = observe "mixed_odd_full_tuple" ``lines_upd_lab_len 1 ^lines [] = ([Label 1 2 1;Label 1 3 0;Asm(Asmi(Inst Skip)) [7w] 3;LabAsm(Call(Lab 1 2)) 77w [8w;9w] 2;Label 1 4 1],8)``;
val _ = observe "mixed_odd_pos_ok" ``lab_len_pos_ok 1 (FST(lines_upd_lab_len 1 ^lines []))``;
val _ = observe "mixed_even_full_tuple" ``lines_upd_lab_len 0 ^lines [] = ([Label 1 2 0;Label 1 3 0;Asm(Asmi(Inst Skip)) [7w] 3;LabAsm(Call(Lab 1 2)) 77w [8w;9w] 2;Label 1 4 1],6)``;
val _ = observe "mixed_even_pos_ok" ``lab_len_pos_ok 0 (FST(lines_upd_lab_len 0 ^lines []))``;
val _ = observe "odd_label_chain" ``lines_upd_lab_len 3 ([Label 1 2 97;Label 1 3 99;Label 1 4 123]:8 labLang$line list) [] = ([Label 1 2 1;Label 1 3 0;Label 1 4 0],4)``;
val _ = observe "nonlabels_unchanged" ``FST(lines_upd_lab_len 3 ([Asm(Asmi(Inst Skip)) [] 99;LabAsm Halt 77w [7w] 37]:8 labLang$line list) []) = [Asm(Asmi(Inst Skip)) [] 99;LabAsm Halt 77w [7w] 37]``;
val _ = observe "empty_list_width1" ``lines_upd_lab_len 99 ([]:1 labLang$line list) [] = ([],99)``;
val _ = observe "section_full_tuple" ``upd_lab_len 1 ^code = [Section 7 [Label 1 2 1;Label 1 3 0;Asm(Asmi(Inst Skip)) [7w] 3;LabAsm(Call(Lab 1 2)) 77w [8w;9w] 2;Label 1 4 1];Section 8 [Label 1 9 0;Asm(Asmi(Inst Skip)) [] 1;Label 1 10 1];Section 9 []]``;
val _ = observe "section_all_pos_ok" ``all_lab_len_pos_ok 1 (upd_lab_len 1 ^code)``;
val _ = observe "bad_input_repaired" ``~all_lab_len_pos_ok 1 ^code /\ all_lab_len_pos_ok 1 (upd_lab_len 1 ^code)``;
val _ = observe "empty_code" ``all_lab_len_pos_ok 17 (upd_lab_len 17 ([]:8 labLang$sec list))``;
val _ = observe "empty_sections" ``upd_lab_len 17 ([Section 7 [];Section 8 []]:8 labLang$sec list) = [Section 7 [];Section 8 []] /\ all_lab_len_pos_ok 17 (upd_lab_len 17 [Section 7 [];Section 8 []])``;
val _ = observe "large_width80_tuple" ``lines_upd_lab_len (2**80+1) ([LabAsm Halt (n2w(2**70+3)) [7w] 99;Label 1 2 97]:80 labLang$line list) [] = ([LabAsm Halt (n2w(2**70+3)) [7w] 99;Label 1 2 0],2**80+100)``;
val _ = observe "large_width80_pos_ok" ``lab_len_pos_ok (2**80+1) (FST(lines_upd_lab_len (2**80+1) ([LabAsm Halt (n2w(2**70+3)) [7w] 99;Label 1 2 97]:80 labLang$line list) []))``;
