load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_lab_len_pos_ok_def" line_lab_len_pos_ok_def;
val _ = types "line_lab_len_pos_ok_def_types" line_lab_len_pos_ok_def;
val _ = capture "lab_len_pos_ok_def" lab_len_pos_ok_def;
val _ = types "lab_len_pos_ok_def_types" lab_len_pos_ok_def;
val _ = capture "lab_len_pos_ok_append" lab_len_pos_ok_append;
val _ = types "lab_len_pos_ok_append_types" lab_len_pos_ok_append;
val _ = capture "all_lab_len_pos_ok_def" all_lab_len_pos_ok_def;
val _ = types "all_lab_len_pos_ok_def_types" all_lab_len_pos_ok_def;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL q)))); print "\n");
val _ = observe "even_label_zero" ``line_lab_len_pos_ok 8 (Label 1 2 0:8 labLang$line)``;
val _ = observe "odd_label_one" ``line_lab_len_pos_ok 9 (Label 1 2 1:8 labLang$line)``;
val _ = observe "even_wrong_one" ``~line_lab_len_pos_ok 8 (Label 1 2 1:8 labLang$line)``;
val _ = observe "odd_wrong_zero" ``~line_lab_len_pos_ok 9 (Label 1 2 0:8 labLang$line)``;
val _ = observe "other_annotation_rejected" ``~line_lab_len_pos_ok 8 (Label 1 2 2:8 labLang$line) /\ ~line_lab_len_pos_ok 9 (Label 1 2 2:8 labLang$line)``;
val _ = observe "asm_unconstrained" ``line_lab_len_pos_ok 9 (Asm (Asmi(Inst Skip)) [] 99:8 labLang$line)``;
val _ = observe "labasm_unconstrained_width80" ``line_lab_len_pos_ok (2**80+1) (LabAsm (Call(Lab 1 2)) (n2w(2**70+3)) [7w] 99:80 labLang$line)``;
val _ = observe "list_annotation_not_bytes" ``lab_len_pos_ok 1 ([Asm (Asmi(Inst Skip)) [7w] 2;Label 1 2 1]:8 labLang$line list) /\ ~lab_len_pos_ok 1 [Asm (Asmi(Inst Skip)) [7w] 2;Label 1 2 0]``;
val _ = observe "append_actual_both_sides" ``lab_len_pos_ok 1 (([Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3]:8 labLang$line list) ++ [Label 1 3 1]) /\ lab_len_pos_ok 1 [Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3] /\ lab_len_pos_ok (1+SUM(MAP line_len [Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3])) [Label 1 3 1]``;
val _ = observe "append_false_sides" ``~lab_len_pos_ok 1 (([Asm(Asmi(Inst Skip)) [] 1]:8 labLang$line list) ++ [Label 1 2 1]) /\ ~lab_len_pos_ok (1+SUM(MAP line_len [Asm(Asmi(Inst Skip)) [] 1])) [Label 1 2 1]``;
val _ = observe "empty_list_width1" ``lab_len_pos_ok 99 ([]:1 labLang$line list)``;
val _ = observe "empty_code" ``all_lab_len_pos_ok 99 ([]:8 labLang$sec list)``;
val _ = observe "empty_sections" ``all_lab_len_pos_ok 99 ([Section 0 [];Section 1 []]:8 labLang$sec list)``;
val _ = observe "section_annotation_not_bytes" ``all_lab_len_pos_ok 1 ([Section 0 [];Section 1 [Asm(Asmi(Inst Skip)) [] 1];Section 2 [Label 1 2 0];Section 3 []]:8 labLang$sec list)``;
val _ = observe "section_bad_parity" ``~all_lab_len_pos_ok 1 ([Section 1 [Asm(Asmi(Inst Skip)) [] 1];Section 2 [Label 1 2 1]]:8 labLang$sec list)``;
