load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val full = DB.fetch "lab_to_targetProof" "IMP_state_rel_make_init";
val _ = capture "IMP_state_rel_make_init" full;
val _ = types "IMP_state_rel_make_init_types" full;
val _ = print("IMP_state_rel_make_init_hypotheses=" ^ Int.toString(length(hyp full)) ^ "\n");
val guard = lhand(concl full);
val clauses = CONJUNCTS (REWRITE_RULE [state_rel_def] (UNDISCH full));
val _ = print("state_rel_conjuncts=" ^ Int.toString(length clauses) ^ "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th, ACCEPT_TAC th))))); print "\n");
val ISR1 = DISCH guard (List.nth(clauses,14));
val _ = capture "ISR1_statement" ISR1;
val _ = print("ISR1_hypotheses=" ^ Int.toString(length(hyp ISR1)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR1_proved" ISR1;
val _ = show_types := true;
val ISR12 = DISCH guard (List.nth(clauses,36));
val _ = capture "ISR12_statement" ISR12;
val _ = print("ISR12_hypotheses=" ^ Int.toString(length(hyp ISR12)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR12_proved" ISR12;
val _ = show_types := true;
