load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_upd_lab_len_label_prefix_zero" lines_upd_lab_len_label_prefix_zero;
val _ = types "lines_upd_lab_len_label_prefix_zero_types" lines_upd_lab_len_label_prefix_zero;
val _ = capture "upd_lab_len_label_prefix_zero" upd_lab_len_label_prefix_zero;
val _ = types "upd_lab_len_label_prefix_zero_types" upd_lab_len_label_prefix_zero;
val _ = capture "enc_lines_again_simp_label_prefix_zero" enc_lines_again_simp_label_prefix_zero;
val _ = types "enc_lines_again_simp_label_prefix_zero_types" enc_lines_again_simp_label_prefix_zero;
val _ = capture "enc_secs_again_label_prefix_zero" enc_secs_again_label_prefix_zero;
val _ = types "enc_secs_again_label_prefix_zero_types" enc_secs_again_label_prefix_zero;
val prefix_nil = prove (``label_prefix_zero []``, simp [label_prefix_zero_def]);
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
fun prefix label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[label_prefix_zero_cons,prefix_nil,sec_label_prefix_zero_def]) q)); print "\n");
val src = ``[Label 1 2 99;Asm (Asmi (Inst Skip)) [] 3;Label 1 3 88] : 8 labLang$line list``;
val dst = ``[Label 1 2 0;Asm (Asmi (Inst Skip)) [] 3;Label 1 3 1] : 8 labLang$line list``;
val _ = observe "even_update_full" ``lines_upd_lab_len 0 ^src [] = (^dst,4)``;
val _ = prefix "later_odd_label_allowed" ``label_prefix_zero ^dst``;
val _ = observe "odd_position_nonlabel_acc_full" ``lines_upd_lab_len 1 [Label 1 2 99] [Asm (Asmi (Inst Skip)) [] 3] = ([Asm (Asmi (Inst Skip)) [] 3;Label 1 2 1],2)``;
val _ = prefix "odd_position_nonlabel_acc_valid" ``label_prefix_zero ([Asm (Asmi (Inst Skip)) [] 3;Label 1 2 1] : 8 labLang$line list)``;
val _ = prefix "all_label_odd_guard_required" ``~label_prefix_zero ([Label 1 2 1] : 8 labLang$line list)``;
val _ = prefix "reverse_acc_guard_required" ``~label_prefix_zero ([Label 9 8 7;Label 1 2 0] : 8 labLang$line list)``;
val _ = observe "full_sections_update" ``upd_lab_len 0 [Section 1 ^src;Section 3 [Label 3 4 77]] = [Section 1 ^dst;Section 3 [Label 3 4 0]]``;
val _ = prefix "ending_guard_required" ``~EVERY sec_label_prefix_zero ([Section 1 [Asm (Asmi (Inst Skip)) [] 3];Section 3 [Label 3 4 1]] : 8 labLang$sec list)``;
val encsrc = ``[Label 3 4 0;LabAsm (Jump (Lab 3 4)) 77w [] 2;Label 3 5 99] : 8 labLang$line list``;
val encdst = ``[Label 3 4 0;LabAsm (Jump (Lab 3 4)) 0w [9w;9w;9w;9w] 4;Label 3 5 99] : 8 labLang$line list``;
val _ = observe "false_flag_full" ``enc_lines_again_simp LN [] 0 (K [9w;9w;9w;9w]) ^encsrc = (^encdst,F)``;
val _ = prefix "false_flag_prefix_preserved" ``label_prefix_zero ^encsrc /\ label_prefix_zero ^encdst``;
val _ = observe "false_flag_sections_full" ``enc_secs_again 0 LN [] (K [9w;9w;9w;9w]) [Section 3 ^encsrc;Section 7 []] = ([Section 3 ^encdst;Section 7 []],F)``;
