load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "pos_val_acc_sum" pos_val_acc_sum;
val _=types "pos_val_acc_sum_types" pos_val_acc_sum;
val _=print("pos_val_acc_sum_hypotheses="^Int.toString(length(hyp pos_val_acc_sum))^"\n");
val _=capture "pos_val_acc_0" pos_val_acc_0;
val _=types "pos_val_acc_0_types" pos_val_acc_0;
val _=print("pos_val_acc_0_hypotheses="^Int.toString(length(hyp pos_val_acc_0))^"\n");
val _=capture "pos_val_APPEND1" pos_val_APPEND1;
val _=types "pos_val_APPEND1_types" pos_val_APPEND1;
val _=print("pos_val_APPEND1_hypotheses="^Int.toString(length(hyp pos_val_APPEND1))^"\n");
val _=capture "pos_val_APPEND2" pos_val_APPEND2;
val _=types "pos_val_APPEND2_types" pos_val_APPEND2;
val _=print("pos_val_APPEND2_hypotheses="^Int.toString(length(hyp pos_val_APPEND2))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val jumpcode = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0]]:8 sec list``;
val asmcode = ``[Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0]]:8 sec list``;
val suffix = ``[Section 9 [Label 3 4 99;Asm (Asmi (Inst Skip)) [0w;0w;0w] 999]]:8 sec list``;
val prefix = ``[Section 6 [];Section 1 [Label 4 2 99;Asm (Asmi (Inst Skip)) [0w;0w] 999]]:8 sec list``;
val _=observe "acc_split" ``7 + pos_val 1 11 ^prefix = pos_val 1 18 ^prefix``;
val _=observe "acc_zero" ``101 + pos_val 1 0 ^prefix = pos_val 1 101 ^prefix``;
val _=observe "prefix_unrestricted" ``0 < num_pcs ^prefix /\ pos_val 0 0 (^prefix++ ^suffix)=pos_val 0 0 ^prefix /\ pos_val 0 0 ^prefix=1``;
val _=observe "prefix_boundary" ``pos_val 1 0 (^prefix++ ^suffix)=4 /\ pos_val 1 0 ^prefix=3``;
val _=observe "suffix_shift" ``all_enc_ok ^cfg ^old [] 18 ^jumpcode /\ pos_val (0+num_pcs ^jumpcode) 0 (^jumpcode++ ^suffix)=LENGTH(prog_to_bytes ^jumpcode)+pos_val 0 0 ^suffix /\ pos_val (0+num_pcs ^jumpcode) 0 (^jumpcode++ ^suffix)=3``;
val _=observe "past_end" ``pos_val (7+num_pcs ^jumpcode) 0 (^jumpcode++ ^suffix)=6``;
val _=observe "invalid_prefix" ``~all_enc_ok ^cfg ^old [] 18 ^prefix /\ LENGTH(prog_to_bytes ^prefix)=2``;
val _=observe "empty_prefix" ``pos_val (2+num_pcs ([]:8 sec list)) 0 ([]++ ^suffix)=pos_val 2 0 ^suffix``;
