load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_len_pad_section" line_len_pad_section;
val _ = types "line_len_pad_section_types" line_len_pad_section;
val _ = show_types := false;
val prefix_nil = prove(``label_prefix_zero ([]:α labLang$line list)``,simp[label_prefix_zero_def]);
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL (rconc(QCONV(REWRITE_CONV[label_prefix_zero_cons,prefix_nil]) q)))))); print "\n");
val xs = ``[Label 1 2 0;Asm(Asmi(Inst Skip)) [] 3;Label 1 3 1]:8 labLang$line list``;
val _ = observe "empty_aux_full_guard_sum" ``LENGTH ([0w]:word8 list)=1 /\ EVERY label_one ^xs /\ (EVERY is_Label ([]:8 labLang$line list) ==> label_prefix_zero ^xs) /\ SUM(MAP line_len(pad_section [0w] ^xs []))=SUM(MAP line_len ^xs)``;
val _ = observe "all_label_aux_full_guard_sum" ``EVERY label_one ^xs /\ (EVERY is_Label ([Label 1 8 17;Label 1 9 19]:8 labLang$line list) ==> label_prefix_zero ^xs) /\ SUM(MAP line_len(pad_section [0w] ^xs [Label 1 8 17;Label 1 9 19]))=SUM(MAP line_len ^xs)+36``;
val _ = observe "all_label_aux_full_tuple" ``pad_section [0w] ^xs [Label 1 8 17;Label 1 9 19] = [Label 1 9 19;Label 1 8 17;Label 1 2 0;Asm(Asmi(Inst Skip)) [0w;0w;0w;0w] 4;Label 1 3 0]``;
val _ = observe "nonlabel_guard_vacuous" ``~EVERY is_Label ([Asm(Asmi(Inst Skip)) [] 3]:8 labLang$line list) /\ SUM(MAP line_len(pad_section [0w] ([Label 1 2 1]:8 labLang$line list) [Asm(Asmi(Inst Skip)) [] 3]))=4``;
val _ = observe "prefix_guard_necessary" ``EVERY label_one ([Label 1 2 1]:8 labLang$line list) /\ ~label_prefix_zero ([Label 1 2 1]:8 labLang$line list) /\ SUM(MAP line_len(pad_section [0w] ([Label 1 2 1]:8 labLang$line list) []))<>SUM(MAP line_len ([Label 1 2 1]:8 labLang$line list))``;
val _ = observe "label_one_guard_necessary" ``~EVERY label_one ([Label 1 2 2]:8 labLang$line list) /\ SUM(MAP line_len(pad_section [0w] ([Label 1 2 2]:8 labLang$line list) [Asm(Asmi(Inst Skip)) [] 3]))<>5``;
val _ = observe "empty_source_width1" ``SUM(MAP line_len(pad_section [0w] ([]:1 labLang$line list) [Label 1 2 97]))=97``;
val _ = observe "large_width80_full_sum" ``SUM(MAP line_len(pad_section [7w] ([Label 1 2 0;LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 3 1]:80 labLang$line list) [Label 1 8 17]))=21``;
