load "bossLib";
load "preamble";
load "lab_filterTheory";
open bossLib HolKernel Parse preamble lab_filterTheory;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO(prove(concl th, ACCEPT_TAC th))))); print "\n");
val th0 = DB.fetch "lab_filter" "not_skip_def";
val _ = show_types := true;
val _ = capture "not_skip_def_statement" th0;
val _ = types "not_skip_def_types" th0;
val _ = print("not_skip_def_hypotheses=" ^ Int.toString(length(hyp th0)) ^ "\n");
val _ = show_types := false;
val _ = checked "not_skip_def_proved" th0;
val th1 = DB.fetch "lab_filter" "filter_skip_def";
val _ = show_types := true;
val _ = capture "filter_skip_def_statement" th1;
val _ = types "filter_skip_def_types" th1;
val _ = print("filter_skip_def_hypotheses=" ^ Int.toString(length(hyp th1)) ^ "\n");
val _ = show_types := false;
val _ = checked "filter_skip_def_proved" th1;
val th2 = DB.fetch "lab_filter" "filter_skip_MAP";
val _ = show_types := true;
val _ = capture "filter_skip_MAP_statement" th2;
val _ = types "filter_skip_MAP_types" th2;
val _ = print("filter_skip_MAP_hypotheses=" ^ Int.toString(length(hyp th2)) ^ "\n");
val _ = show_types := false;
val _ = checked "filter_skip_MAP_proved" th2;
