load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "remove_labels_thm" remove_labels_thm;
val _=types "remove_labels_thm_types" remove_labels_thm;
val _=print("hypotheses="^Int.toString(length(hyp remove_labels_thm))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg = template;
val _=observe "empty" ``remove_labels 0 ^cfg 18 LN [] [] = SOME ([],LN)``;
val _=observe "stale_asm" ``OPTION_MAP (λr.prog_to_bytes(FST r)) (remove_labels 0 ^cfg 18 LN [] [Section 1 [Asm (Asmi (Inst Skip)) [] 99;Label 1 7 0]]) = SOME [0w;0w]``;
val _=observe "labels_only" ``OPTION_MAP (λr.lab_lookup 1 7(SND r)) (remove_labels 0 ^cfg 18 LN [] [Section 1 [Label 1 7 99]]) = SOME(SOME 18)``;
val _=observe "halt" ``OPTION_MAP (λr.prog_to_bytes(FST r)) (remove_labels 0 ^cfg 18 LN [] [Section 1 [LabAsm Halt 99w [] 99;Label 1 7 0]]) = SOME [0w;0w]``;
val _=observe "call_reject" ``remove_labels 0 ^cfg 18 LN [] [Section 1 [LabAsm (Call (Lab 1 7)) 99w [] 99;Label 1 7 0]] = NONE``;
val _=observe "acc_preserve" ``OPTION_MAP (λr.lab_lookup 99 7(SND r)) (remove_labels 0 ^cfg 18 (fromAList[(99,fromAList[(7,24)])]) [] [Section 1 [Asm (Asmi (Inst Skip)) [] 99;Label 1 7 0]]) = SOME(SOME 24)``;
val cfg2 = ``^cfg with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val _=observe "two_byte" ``OPTION_MAP (λr.lab_lookup 1 7(SND r)) (remove_labels 0 ^cfg2 18 LN [] [Section 1 [Asm (Asmi (Inst Skip)) [] 99;Label 1 7 0]]) = SOME(SOME 20)``;
val cfg1 = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T)); addr_offset := (0w,1w); hw_offset := (0w,1w);
 byte_offset := (0w,1w); jump_offset := (0w,1w); cjump_offset := (0w,1w); loc_offset := (0w,1w) |> : 1 asm_config``;
val cfg80 = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T)); addr_offset := (128w,127w); hw_offset := (128w,127w);
 byte_offset := (128w,127w); jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w) |> : 80 asm_config``;
val _=observe "width1_large" ``OPTION_MAP (λr.lab_lookup 1 7(SND r)) (remove_labels 0 ^cfg1 1208925819614629174706176 LN [] [Section 1 [Label 1 7 99]]) = SOME(SOME 1208925819614629174706176)``;
val _=observe "width80_large" ``OPTION_MAP (λr.lab_lookup 1 7(SND r)) (remove_labels 0 ^cfg80 1208925819614629174706176 LN [] [Section 1 [Label 1 7 99]]) = SOME(SOME 1208925819614629174706176)``;
