load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "line_to_info_def" line_to_info_def;
val _=types "line_to_info_def_types" line_to_info_def;
val _=print("line_to_info_def_hypotheses="^Int.toString(length(hyp line_to_info_def))^"\n");
val _=capture "line_to_info_next" line_to_info_next;
val _=types "line_to_info_next_types" line_to_info_next;
val _=print("line_to_info_next_hypotheses="^Int.toString(length(hyp line_to_info_next))^"\n");
val _=capture "line_to_info_hd_empty" line_to_info_hd_empty;
val _=types "line_to_info_hd_empty_types" line_to_info_hd_empty;
val _=print("line_to_info_hd_empty_hypotheses="^Int.toString(length(hyp line_to_info_hd_empty))^"\n");
val _=capture "line_to_info_hd_Label" line_to_info_hd_Label;
val _=types "line_to_info_hd_Label_types" line_to_info_hd_Label;
val _=print("line_to_info_hd_Label_hypotheses="^Int.toString(length(hyp line_to_info_hd_Label))^"\n");
val _=capture "GENLIST_asm_fetch_aux_next" GENLIST_asm_fetch_aux_next;
val _=types "GENLIST_asm_fetch_aux_next_types" GENLIST_asm_fetch_aux_next;
val _=print("GENLIST_asm_fetch_aux_next_hypotheses="^Int.toString(length(hyp GENLIST_asm_fetch_aux_next))^"\n");
val _=show_types:=false;
fun observe label q = (print(label^"=");print_term(rconc(EVAL q));print "\n");
val code1=``[Section 10 [Label 10 1 99;Asm (Asmi (Inst Skip)) [7w;8w;9w] 999]]:1 sec list``;
val fetched80=``Asm (ShareMem Load32 7 (Addr 2 (-1w))) [11w;22w] 999:80 line``;
val _=observe "cross_width_first" ``line_to_info ^code1 13 (0,SOME ^fetched80)=[(SharedMem MappedRead,<|entry_pc:=14;nbytes:=4w;addr_reg:=2;addr_off:=1208925819614629174706175;reg:=7;exit_pc:=16|>)]``;
val _=observe "cross_width_boundary" ``line_to_info ^code1 13 (1,SOME ^fetched80)=[(SharedMem MappedRead,<|entry_pc:=17;nbytes:=4w;addr_reg:=2;addr_off:=1208925819614629174706175;reg:=7;exit_pc:=19|>)]``;
val _=observe "load" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Load 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedRead,<|entry_pc:=7;nbytes:=0w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "load32" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Load32 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedRead,<|entry_pc:=7;nbytes:=4w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "load16" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Load16 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedRead,<|entry_pc:=7;nbytes:=2w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "load8" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Load8 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedRead,<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "store" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Store 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedWrite,<|entry_pc:=7;nbytes:=0w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "store32" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Store32 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedWrite,<|entry_pc:=7;nbytes:=4w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "store16" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Store16 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedWrite,<|entry_pc:=7;nbytes:=2w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "store8" ``line_to_info ([]:1 sec list) 7 (99,SOME (Asm (ShareMem Store8 3 (Addr 2 255w)) [11w;22w;33w] 999:8 line))=[(SharedMem MappedWrite,<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=3;exit_pc:=10|>)]``;
val _=observe "none" ``line_to_info ^code1 13 (0,(NONE:80 line option))=[]``;
val _=observe "label" ``line_to_info ^code1 13 (0,(SOME (Label 1 2 99:80 line)))=[]``;
val _=observe "asmi" ``line_to_info ^code1 13 (0,(SOME (Asm (Asmi (Inst Skip)) [0w;0w] 2:80 line)))=[]``;
val _=observe "cbw" ``line_to_info ^code1 13 (0,(SOME (Asm (Cbw 1 2) [0w;0w] 2:80 line)))=[]``;
val _=observe "labasm" ``line_to_info ^code1 13 (0,(SOME (LabAsm Halt 0w [0w;0w] 2:80 line)))=[]``;
val _=observe "empty_section" ``line_to_info (Section 0 []::^code1) 13 (0,SOME ^fetched80)=line_to_info ^code1 13 (0,SOME ^fetched80)``;
val _=observe "zero_label" ``line_to_info (Section 0 [Label 1 2 0]::^code1) 13 (0,SOME ^fetched80)=line_to_info ^code1 13 (0,SOME ^fetched80)``;
val _=observe "four_dimensions" ``line_to_info (Section 1 [LabAsm Halt (0w:1 word) [0w;0w;0w] 999]::^code1) 13 (1,SOME ^fetched80)=line_to_info (Section 1 []::^code1) 16 (0,SOME ^fetched80) /\ line_to_info ([Section 2 [Asm (Asmi (Inst Skip)) [0w] 999]]:64 sec list) 100 (1,SOME (Asm (ShareMem Store8 3 (Addr 2 255w)) [11w;22w] 99:8 line))=line_to_info ([Section 2 []]:64 sec list) 101 (0,SOME (Asm (ShareMem Store8 3 (Addr 2 255w)) [11w;22w] 99:8 line))``;
val _=observe "enumeration_past_end" ``GENLIST (λi. (i,asm_fetch_aux i ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 999]]:8 sec list))) 4=[(0,SOME (Asm (Asmi (Inst Skip)) [0w] 999));(1,NONE);(2,NONE);(3,NONE)]``;
