load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "section_labels_line_get_code_labels" section_labels_line_get_code_labels;
val _=types "section_labels_line_get_code_labels_types" section_labels_line_get_code_labels;
val _=show_types:=false;
fun observe label q=(print(label ^ "=");print_term(rconc((QCONV(SIMP_CONV(srw_ss())[line_get_code_labels_def,pred_setTheory.IN_BIGUNION,pred_setTheory.IN_IMAGE]) THENC EVAL THENC QCONV(SIMP_CONV(srw_ss())[line_get_code_labels_def,pred_setTheory.IN_BIGUNION,pred_setTheory.IN_IMAGE]) THENC QCONV(SIMP_CONV(srw_ss())[pred_setTheory.EXTENSION,pred_setTheory.GSPECIFICATION,FORALL_PROD,EXISTS_PROD]) THENC EVAL THENC QCONV(SIMP_CONV(srw_ss())[line_get_code_labels_def,RIGHT_AND_OVER_OR,LEFT_AND_OVER_OR,EXISTS_OR_THM]) THENC EVAL) q));print "\n");
val aux=``[(0,999);(7,40);(7,80)]: (num#num) list``;
val lines=``[Label 1 2 0;Asm(Asmi(Inst Skip)) [] 3;Label 9 0 4;LabAsm Halt 99w [] 2;Label 88 2 1]:8 labLang$line list``;
val labs=``[(2,16);(2,6);(0,999);(7,40);(7,80)]: (num#num) list``;
val _=observe "mixed_full_tuple" ``section_labels 6 ^lines ^aux=(16,^labs)``;
val _=observe "mixed_full_set_equality" ``0 INSERT set(MAP FST ^labs)=(0 INSERT set(MAP FST ^aux)) UNION BIGUNION(IMAGE line_get_code_labels (set ^lines))``;
val _=observe "duplicate_zero_accumulator_retained" ``SND(section_labels 6 ^lines ^aux)=[(2,16);(2,6);(0,999);(7,40);(7,80)]``;
val _=observe "all_label_zero_skipped_nonzero_kept" ``section_labels 3 ([Label 9 0 5;Label 8 4 2]:8 labLang$line list) []=(10,[(4,10)])``;
val _=observe "both_zero_insertions_needed" ``let ls=[Label 9 0 5]:8 labLang$line list in section_labels 3 ls []=(8,[]) /\ set(MAP FST(SND(section_labels 3 ls []))) <> BIGUNION(IMAGE line_get_code_labels(set ls)) /\ 0 INSERT set(MAP FST(SND(section_labels 3 ls [])))=0 INSERT BIGUNION(IMAGE line_get_code_labels(set ls))``;
val _=observe "empty_accumulator_retained" ``section_labels 34 ([]:8 labLang$line list) ^aux=(34,^aux)``;
val _=observe "zero_accumulator_value_unconstrained" ``section_labels 0 ([Label 88 0 17]:8 labLang$line list) [(0,777)]=(17,[(0,777)])``;
val _=observe "nonlabel_bytes_not_annotation" ``section_labels 11 ([Asm(Asmi(Inst Skip)) [1w;2w;3w] 2;LabAsm Halt 99w [9w] 7]:8 labLang$line list) [(8,999)]=(20,[(8,999)])``;
val _=observe "all_seven_opcodes_no_definitions" ``let ls=[LabAsm(Jump(Lab 3 4)) 99w [] 1;LabAsm(JumpCmp Equal 2 (Imm 1w) (Lab 3 4)) 99w [] 1;LabAsm(LocValue 2 (Lab 3 4)) 99w [] 1;LabAsm(Call(Lab 99 88)) 99w [] 1;LabAsm(CallFFI(strlit "")) 99w [] 1;LabAsm Install 99w [] 1;LabAsm Halt 99w [] 1]:8 labLang$line list in section_labels 13 ls ^aux=(20,^aux) /\ BIGUNION(IMAGE line_get_code_labels(set ls))={} ``;
val _=observe "width1_empty" ``section_labels 17 ([]:1 labLang$line list) []=(17,[])``;
val _=observe "width80_large_position" ``section_labels (2**80) ([Label 999 0 1;Label 888 5 2]:80 labLang$line list) [(0,2**90)]=(2**80+3,[(5,2**80+3);(0,2**90)])``;
