load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "align_dm_def";
val _ = show_types := true;
val _ = print "align_dm_def=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_dm_def_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_dm_def_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_dm_def_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "align_dm_const";
val _ = show_types := true;
val _ = print "align_dm_const=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_dm_const_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_dm_const_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_dm_const_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "align_dm_with_clock";
val _ = show_types := true;
val _ = print "align_dm_with_clock=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_dm_with_clock_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_dm_with_clock_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_dm_with_clock_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "align_sdm_def";
val _ = show_types := true;
val _ = print "align_sdm_def=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_sdm_def_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_sdm_def_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_sdm_def_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "align_sdm_const";
val _ = show_types := true;
val _ = print "align_sdm_const=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_sdm_const_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_sdm_const_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_sdm_const_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "align_sdm_with_clock";
val _ = show_types := true;
val _ = print "align_sdm_with_clock=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_sdm_with_clock_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_sdm_with_clock_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_sdm_with_clock_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
