load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "upd_lab_len_ends_with_label" upd_lab_len_ends_with_label;
val _=types "upd_lab_len_ends_with_label_types" upd_lab_len_ends_with_label;
val _=capture "pad_code_ends_with_label" pad_code_ends_with_label;
val _=types "pad_code_ends_with_label_types" pad_code_ends_with_label;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _=observe "empty_update" ``EVERY sec_ends_with_label (upd_lab_len 3 ([]:8 sec list))``;
val _=observe "empty_padding" ``EVERY sec_ends_with_label (pad_code [] ([]:8 sec list))``;
val _=observe "updated_ending" ``EVERY sec_ends_with_label (upd_lab_len 3 ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 1; Label 1 7 0]]:8 sec list))``;
val _=observe "padded_one" ``EVERY sec_ends_with_label (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 1; Label 1 7 1]]:8 sec list))``;
val _=observe "padded_empty_nop" ``EVERY sec_ends_with_label (pad_code [] ([Section 1 [Label 1 7 0]]:8 sec list))``;
val _=observe "missing_ending_guard" ``~EVERY sec_ends_with_label (upd_lab_len 0 ([Section 1 [Asm (Asmi (Inst Skip)) [] 0]]:8 sec list)) /\ ~EVERY sec_ends_with_label (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 0]]:8 sec list))``;
val _=observe "width1" ``EVERY sec_ends_with_label (upd_lab_len 3 ([Section 1 [Label 1 7 2]]:1 sec list))``;
val _=observe "width80_large_pos" ``EVERY sec_ends_with_label (upd_lab_len 1208925819614629174706176 ([Section 1 [Label 1 7 2]]:80 sec list))``;
