load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "evaluate_align_sdm";
val _ = show_types := true;
val _ = print "evaluate_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "evaluate_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("evaluate_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "evaluate_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "implements_align_sdm";
val _ = show_types := true;
val _ = print "implements_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "implements_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("implements_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "implements_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
