load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "enc_lines_again_simp_offset_ok" enc_lines_again_simp_offset_ok;
val _ = types "enc_lines_again_simp_offset_ok_types" enc_lines_again_simp_offset_ok;
val _ = capture "enc_secs_again_offset_ok" enc_secs_again_offset_ok;
val _ = types "enc_secs_again_offset_ok_types" enc_secs_again_offset_ok;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL q)))); print "\n");
val labs = ``insert 3 (insert 4 10 LN) LN:num sptree$num_map sptree$num_map``;
val enc = ``(\a. [7w;8w]):8 asm -> word8 list``;
val lines = ``[Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3;LabAsm(Jump(Lab 3 4)) 99w [] 1;LabAsm Halt 99w [] 1]:8 labLang$line list``;
val result = ``[Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3;LabAsm(Jump(Lab 3 4)) 6w [7w;8w] 2;LabAsm Halt 234w [7w;8w] 2]:8 labLang$line list``;
val code = ``[Section 7 ^lines;Section 8 [LabAsm(Call(Lab 3 4)) 99w [] 1];Section 9 []]:8 labLang$sec list``;
val codeResult = ``[Section 7 ^result;Section 8 [LabAsm(Call(Lab 3 4)) 2w [7w;8w] 2];Section 9 []]:8 labLang$sec list``;
val _ = observe "growth_false_full_tuple" ``enc_lines_again_simp ^labs [] 0 ^enc ^lines = (^result,F)``;
val _ = observe "growth_false_offset_ok" ``lines_offset_ok ^labs [] 0 ^result``;
val _ = observe "bad_input_repaired" ``~lines_offset_ok ^labs [] 0 ^lines /\ lines_offset_ok ^labs [] 0 (FST(enc_lines_again_simp ^labs [] 0 ^enc ^lines))``;
val _ = observe "nongrowth_true_full_tuple" ``enc_lines_again_simp ^labs [] 4 ^enc ([LabAsm(Jump(Lab 3 4)) 99w [] 3]:8 labLang$line list) = ([LabAsm(Jump(Lab 3 4)) 6w [7w;8w] 3],T) /\ lines_offset_ok ^labs [] 4 (FST(enc_lines_again_simp ^labs [] 4 ^enc ([LabAsm(Jump(Lab 3 4)) 99w [] 3]:8 labLang$line list)))``;
val _ = observe "same_word_malformed_unchanged" ``enc_lines_again_simp ^labs [] 4 ^enc ([LabAsm(Jump(Lab 3 4)) 6w [] 0]:8 labLang$line list) = ([LabAsm(Jump(Lab 3 4)) 6w [] 0],T) /\ lines_offset_ok ^labs [] 4 ([LabAsm(Jump(Lab 3 4)) 6w [] 0]:8 labLang$line list)``;
val _ = observe "sections_false_full_tuple" ``enc_secs_again 0 ^labs [] ^enc ^code = (^codeResult,F)``;
val _ = observe "sections_false_offset_ok" ``offset_ok ^labs [] 0 ^codeResult``;
val _ = observe "bad_old_position" ``~offset_ok ^labs [] 0 ([Section 7 ^result;Section 8 [LabAsm(Call(Lab 3 4)) 4w [7w;8w] 2]]:8 labLang$sec list)``;
val _ = observe "empty_width1" ``enc_lines_again_simp LN [] 17 ((\a. []):1 asm -> word8 list) [] = ([],T) /\ lines_offset_ok LN [] 17 ([]:1 labLang$line list)``;
val _ = observe "empty_sections" ``enc_secs_again 17 ^labs [] ^enc ([Section 7 [];Section 8 []]:8 labLang$sec list) = ([Section 7 [];Section 8 []],T) /\ offset_ok ^labs [] 17 ([Section 7 [];Section 8 []]:8 labLang$sec list)``;
val _ = observe "all_opcodes_false_flag" ``let ls = [LabAsm(Jump(Lab 3 4)) 99w [] 1;LabAsm(JumpCmp Equal 2 (Imm 1w) (Lab 3 4)) 99w [] 1;LabAsm(LocValue 2 (Lab 3 4)) 99w [] 1;LabAsm(Call(Lab 3 4)) 99w [] 1;LabAsm(CallFFI(strlit "")) 99w [] 1;LabAsm Install 99w [] 1;LabAsm Halt 99w [] 1]:8 labLang$line list in let result = enc_lines_again_simp ^labs [ExtCall(strlit "a");ExtCall(strlit "");ExtCall(strlit "")] 0 ^enc ls in SND result=F /\ lines_offset_ok ^labs [ExtCall(strlit "a");ExtCall(strlit "");ExtCall(strlit "")] 0 (FST result)``;
val _ = observe "large_width80_false" ``enc_lines_again_simp LN [] (2**80+1) ((\a. [7w;8w]):80 asm -> word8 list) ([LabAsm Halt (n2w(2**70+3)) [] 1]:80 labLang$line list) = ([LabAsm Halt (n2w(2**80-17)) [7w;8w] 2],F) /\ lines_offset_ok LN [] (2**80+1) ([LabAsm Halt (n2w(2**80-17)) [7w;8w] 2]:80 labLang$line list)``;
