load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_enc_with_nop_pad_section" lines_enc_with_nop_pad_section;
val _ = types "lines_enc_with_nop_pad_section_types" lines_enc_with_nop_pad_section;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) []) (rconc(EVAL (rconc(QCONV (SIMP_CONV (srw_ss()) [label_prefix_zero_cons]) q)))))); print "\n");
val enc = ``(λa:8 asm. case a of Jump w => [w] | JumpCmp c r i w => [w] | Loc r w => [w] | _ => [0w])``;
val aux = ``[Label 1 2 0;Label 1 3 0]:8 labLang$line list``;
val code = ``[Label 1 9 0;LabAsm (Jump (Lab 1 2)) 77w [251w] 3;Label 1 10 1;Asm (Asmi (Inst Skip)) [0w] 1]:8 labLang$line list``;
val _ = observe "mixed_full_guards" ``LENGTH(^enc(Inst Skip))=1 /\ lines_encd ^enc LN [] (5+SUM(MAP line_len ^aux)) ^code /\ lines_enc_with_nop ^enc LN [] 5 (REVERSE ^aux) /\ EVERY is_Label ^aux /\ EVERY label_one ^code /\ label_prefix_zero ^code``;
val _ = observe "mixed_padded_encoding" ``lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] ^code ^aux)``;
val _ = observe "mixed_full_tuple" ``pad_section [0w] ^code ^aux = [Label 1 3 0;Label 1 2 0;Label 1 9 0;LabAsm (Jump (Lab 1 2)) 77w [251w;0w;0w;0w] 4;Label 1 10 0;Asm (Asmi (Inst Skip)) [0w] 1]``;
val _ = observe "prefix_guard_required" ``lines_encd ^enc LN [] 5 [Label 1 9 1;LabAsm (Jump (Lab 1 2)) 77w [250w] 1] /\ EVERY label_one [Label 1 9 1;LabAsm (Jump (Lab 1 2)) 77w [250w] 1] /\ ~label_prefix_zero [Label 1 9 1;LabAsm (Jump (Lab 1 2)) 77w [250w] 1] /\ ~lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] [Label 1 9 1;LabAsm (Jump (Lab 1 2)) 77w [250w] 1] ^aux)``;
val _ = observe "empty_accumulator" ``lines_encd ^enc LN [] 5 [Label 1 9 0;Asm (Asmi (Inst Skip)) [0w] 1] /\ lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] [Label 1 9 0;Asm (Asmi (Inst Skip)) [0w] 1] [])``;
val _ = observe "only_zero_labels" ``lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] [Label 1 9 0;Label 1 10 0] ^aux)``;
val _ = observe "empty_code" ``lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] [] ^aux)``;
val _ = observe "call_first" ``lines_encd ^enc LN [] 5 [LabAsm (Call (Lab 1 2)) 77w [0w] 3;Label 1 9 1;Asm (Asmi (Inst Skip)) [0w] 1] /\ label_prefix_zero [LabAsm (Call (Lab 1 2)) 77w [0w] 3;Label 1 9 1;Asm (Asmi (Inst Skip)) [0w] 1] /\ lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] [LabAsm (Call (Lab 1 2)) 77w [0w] 3;Label 1 9 1;Asm (Asmi (Inst Skip)) [0w] 1] ^aux)``;
