load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_enc_with_nop_def" line_enc_with_nop_def;
val _ = types "line_enc_with_nop_def_types" line_enc_with_nop_def;
val _ = capture "lines_enc_with_nop_def" lines_enc_with_nop_def;
val _ = types "lines_enc_with_nop_def_types" lines_enc_with_nop_def;
val _ = capture "lines_enc_with_nop_append" lines_enc_with_nop_append;
val _ = types "lines_enc_with_nop_append_types" lines_enc_with_nop_append;
val _ = capture "all_enc_with_nop_def" all_enc_with_nop_def;
val _ = types "all_enc_with_nop_def_types" all_enc_with_nop_def;
val _ = capture "all_enc_with_nop_alt" all_enc_with_nop_alt;
val _ = types "all_enc_with_nop_alt_types" all_enc_with_nop_alt;
val _ = capture "line_enc_with_nop_length_ok" line_enc_with_nop_length_ok;
val _ = types "line_enc_with_nop_length_ok_types" line_enc_with_nop_length_ok;
val _ = capture "lines_enc_with_nop_length_ok" lines_enc_with_nop_length_ok;
val _ = types "lines_enc_with_nop_length_ok_types" lines_enc_with_nop_length_ok;
val _ = capture "line_enc_with_nop_label_zero" line_enc_with_nop_label_zero;
val _ = types "line_enc_with_nop_label_zero_types" line_enc_with_nop_label_zero;
val _ = capture "lines_enc_with_nop_label_zero" lines_enc_with_nop_label_zero;
val _ = types "lines_enc_with_nop_label_zero_types" lines_enc_with_nop_label_zero;
val _ = capture "all_enc_with_nop_label_zero" all_enc_with_nop_label_zero;
val _ = types "all_enc_with_nop_label_zero_types" all_enc_with_nop_label_zero;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val enc = ``(λa:8 asm. case a of Jump w => [w] | JumpCmp c r i w => [w] | Loc r w => [w] | _ => [0w])``;
val _ = observe "asm_padded" ``line_enc_with_nop ^enc LN [] 5 (Asm (Asmi (Inst Skip)) [0w;0w] 2)``;
val _ = observe "halt_position" ``line_enc_with_nop ^enc LN [] 5 (LabAsm Halt 77w [235w;0w] 2)``;
val _ = observe "install_position" ``line_enc_with_nop ^enc LN [] 5 (LabAsm Install 77w [219w;0w] 2)``;
val _ = observe "ffi_position" ``line_enc_with_nop ^enc LN [] 5 (LabAsm (CallFFI (mlstring$implode [])) 77w [203w;0w] 2)``;
val _ = observe "jump_position" ``line_enc_with_nop ^enc LN [] 5 (LabAsm (Jump (Lab 1 2)) 77w [251w;0w] 2)``;
val _ = observe "jumpcmp_position" ``line_enc_with_nop ^enc LN [] 5 (LabAsm (JumpCmp Equal 1 (Imm 3w) (Lab 1 2)) 77w [251w;0w] 2)``;
val _ = observe "loc_position" ``line_enc_with_nop ^enc LN [] 5 (LabAsm (LocValue 1 (Lab 1 2)) 77w [251w;0w] 2)``;
val _ = observe "call_length_only" ``line_enc_with_nop ^enc LN [] 5 (LabAsm (Call (Lab 1 2)) 77w [99w] 1)``;
val _ = observe "label_zero" ``line_enc_with_nop ^enc LN [] 5 (Label 1 2 0)``;
val _ = observe "label_nonzero_rejected" ``~(line_enc_with_nop ^enc LN [] 5 (Label 1 2 1))``;
val _ = observe "bytes_length_rejected" ``~(line_enc_with_nop ^enc LN [] 5 (Asm (Asmi (Inst Skip)) [0w;0w] 3))``;
val _ = observe "physical_position_threading" ``lines_enc_with_nop ^enc LN [] 5 [Label 1 2 0;Asm (Asmi (Inst Skip)) [0w;0w] 2;LabAsm (Jump (Lab 1 2)) 77w [249w;0w] 2]``;
val _ = observe "sections_empty_and_position" ``all_enc_with_nop ^enc LN [] 5 [Section 0 [];Section 1 [Label 1 2 0;Asm (Asmi (Inst Skip)) [0w;0w] 2;LabAsm (Jump (Lab 1 2)) 77w [249w;0w] 2];Section 2 [];Section 3 [LabAsm (Jump (Lab 1 2)) 88w [247w] 1]]``;
val _ = observe "bad_padding_rejected" ``~(line_enc_with_nop ^enc LN [] 5 (LabAsm (Jump (Lab 1 2)) 77w [251w;1w] 2))``;
