load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "line_to_info_offset_FST_eq" line_to_info_offset_FST_eq;
val _=types "line_to_info_offset_FST_eq_types" line_to_info_offset_FST_eq;
val _=print("line_to_info_offset_FST_eq_hypotheses="^Int.toString(length(hyp line_to_info_offset_FST_eq))^"\n");
val _=capture "line_to_info_offset_SND_eq" line_to_info_offset_SND_eq;
val _=types "line_to_info_offset_SND_eq_types" line_to_info_offset_SND_eq;
val _=print("line_to_info_offset_SND_eq_hypotheses="^Int.toString(length(hyp line_to_info_offset_SND_eq))^"\n");
val _=capture "get_shmem_info_init_pc_offset" get_shmem_info_init_pc_offset;
val _=types "get_shmem_info_init_pc_offset_types" get_shmem_info_init_pc_offset;
val _=print("get_shmem_info_init_pc_offset_hypotheses="^Int.toString(length(hyp get_shmem_info_init_pc_offset))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (-128w,127w); hw_offset := (-128w,127w); byte_offset := (-128w,127w);
 jump_offset := (-128w,127w); cjump_offset := (-128w,127w); loc_offset := (-128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val code=``[Section 0 [];Section 1 [Label 1 7 0;Asm (ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 2;Asm (Cbw 1 2) [0w;0w] 2;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 2 [Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2;Asm (Asmi (Inst Skip)) [0w;0w] 2];Section 0 []]:8 sec list``;
val names=``[SharedMem MappedWrite]``;
val initial=``<|entry_pc:=100;nbytes:=3w;addr_reg:=99;addr_off:=42;reg:=77;exit_pc:=103|>``;
val loadinfo=``<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=5;reg:=3;exit_pc:=9|>``;
val storeinfo=``<|entry_pc:=13;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=4;exit_pc:=15|>``;
fun checked label th=(print(label^"=");print_term(rhs(concl(EQT_INTRO th)));print"\n");
fun observe label q=checked label (prove(q, simp [] >> EVAL_TAC >> simp []));
fun discharge th = MP th (prove(fst(dest_imp(concl th)), simp [] >> EVAL_TAC >> simp []));
val fetched=``SOME(Asm(ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2):80 line option``;
val _=observe "independent_names" ``MAP FST(line_to_info ^code 7 (3,^fetched)) = MAP FST(line_to_info ^code 0 (3,^fetched))``;
val _=observe "independent_records" ``MAP SND(line_to_info ^code 7 (3,^fetched)) = MAP(λx.SND x with <|entry_pc:=7+(SND x).entry_pc;exit_pc:=7+(SND x).exit_pc|>)(line_to_info ^code 0 (3,^fetched))``;
val _=observe "none" ``line_to_info ^code 7 (3,NONE:80 line option) = []``;
val _=observe "empty_offset" ``get_shmem_info ([]:8 sec list) 99 [] [] = ([],[])``;
val _=observe "actual_names" ``FST(get_shmem_info ^code 0 [] []) = FST(get_shmem_info ^code 7 [] [])``;
val _=observe "actual_records" ``MAP(λr.r with <|entry_pc:=7+r.entry_pc;exit_pc:=7+r.exit_pc|>)(SND(get_shmem_info ^code 0 [] [])) = SND(get_shmem_info ^code 7 [] [])``;
val _=observe "valid_guard" ``all_enc_ok ^cfg ^old [] 18 ^code``;
val _=observe "negative_length" ``~all_enc_ok ^cfg ^old [] 18 ([Section 0 [Asm(ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 99]]:8 sec list)``;
