load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "asm_fetch_SOME_IMP_LESS_num_pcs" asm_fetch_SOME_IMP_LESS_num_pcs;
val _=types "asm_fetch_SOME_IMP_LESS_num_pcs_types" asm_fetch_SOME_IMP_LESS_num_pcs;
val _=print("asm_fetch_SOME_IMP_LESS_num_pcs_hypotheses="^Int.toString(length(hyp asm_fetch_SOME_IMP_LESS_num_pcs))^"\n");
val _=capture "pos_val_GE_pc" pos_val_GE_pc;
val _=types "pos_val_GE_pc_types" pos_val_GE_pc;
val _=print("pos_val_GE_pc_hypotheses="^Int.toString(length(hyp pos_val_GE_pc))^"\n");
val _=capture "enc_ok_LENGTH_GT_0" enc_ok_LENGTH_GT_0;
val _=types "enc_ok_LENGTH_GT_0_types" enc_ok_LENGTH_GT_0;
val _=print("enc_ok_LENGTH_GT_0_hypotheses="^Int.toString(length(hyp enc_ok_LENGTH_GT_0))^"\n");
val _=capture "pos_val_mono" pos_val_mono;
val _=types "pos_val_mono_types" pos_val_mono;
val _=print("pos_val_mono_hypotheses="^Int.toString(length(hyp pos_val_mono))^"\n");
val _=capture "pos_val_mono_inv" pos_val_mono_inv;
val _=types "pos_val_mono_inv_types" pos_val_mono_inv;
val _=print("pos_val_mono_inv_hypotheses="^Int.toString(length(hyp pos_val_mono_inv))^"\n");
val _=capture "pos_val_inj" pos_val_inj;
val _=types "pos_val_inj_types" pos_val_inj;
val _=print("pos_val_inj_hypotheses="^Int.toString(length(hyp pos_val_inj))^"\n");
val _=capture "pos_val_num_pcs" pos_val_num_pcs;
val _=types "pos_val_num_pcs_types" pos_val_num_pcs;
val _=print("pos_val_num_pcs_hypotheses="^Int.toString(length(hyp pos_val_num_pcs))^"\n");
val _=capture "pos_val_GE_num_pcs" pos_val_GE_num_pcs;
val _=types "pos_val_GE_num_pcs_types" pos_val_GE_num_pcs;
val _=print("pos_val_GE_num_pcs_hypotheses="^Int.toString(length(hyp pos_val_GE_num_pcs))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV bool_ss []) (rconc(EVAL q)))); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val jumpcode = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0]]:8 sec list``;
val asmcode = ``[Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0]]:8 sec list``;
val code = ``[Section 0 [];Section 1 [Label 1 1 0;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 0 [];Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0];Section 0 []]:8 sec list``;
val jump = ``LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2:8 line``;
val asmi = ``Asm (Asmi (Inst Skip)) [0w;0w] 2:8 line``;
val bad = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 99]]:8 sec list``;
val _=observe "fetch_bound" ``asm_fetch_aux 1 ^code=SOME ^asmi /\ 1<num_pcs ^code``;
val _=observe "unrestricted_lower" ``101<=pos_val 1000 101 ^bad /\ pos_val 1000 101 ^bad=104``;
val _=observe "encoder_positive" ``enc_ok ^cfg /\ 0<LENGTH(^cfg.encode (Jump 99w))``;
val _=observe "strict_order" ``all_enc_ok ^cfg ^old [] 18 ^code /\ pos_val 0 101 ^code<pos_val 2 101 ^code``;
val _=observe "inverse_unbounded_second" ``pos_val 0 101 ^code<pos_val 1000 101 ^code /\ 0<=num_pcs ^code /\ (0:num)<1000``;
val _=observe "bounded_injective" ``pos_val 1 101 ^code=pos_val 1 101 ^code /\ 1<=num_pcs ^code``;
val _=observe "physical_boundary" ``pos_val (num_pcs ^code) 101 ^code=101+LENGTH(prog_to_bytes ^code) /\ LENGTH(prog_to_bytes ^code)=4``;
val _=observe "unrestricted_saturation" ``num_pcs ^bad<=1000 /\ pos_val (num_pcs ^bad) 101 ^bad=pos_val 1000 101 ^bad``;
val _=observe "empty" ``pos_val (num_pcs ([]:8 sec list)) 101 []=101 /\ pos_val 1000 101 ([]:8 sec list)=101``;
