load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th,ACCEPT_TAC th)))));print "\n");
val th = DB.fetch "lab_to_targetProof" "init_ok_def";
val _ = capture "init_ok_def" th;
val _ = types "init_ok_def_types" th;
val _ = print("init_ok_def_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "init_ok_def_proved" th;
val _ = show_types := true;
val th = DB.fetch "lab_to_targetProof" "oracle_tie_make_init";
val _ = capture "oracle_tie_make_init" th;
val _ = types "oracle_tie_make_init_types" th;
val _ = print("oracle_tie_make_init_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "oracle_tie_make_init_proved" th;
val _ = show_types := true;
val th = DB.fetch "lab_to_targetProof" "make_init_simp";
val _ = capture "make_init_simp" th;
val _ = types "make_init_simp_types" th;
val _ = print("make_init_simp_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "make_init_simp_proved" th;
val _ = show_types := true;
