load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "has_odd_inst_def" has_odd_inst_def;
val _=types "has_odd_inst_def_types" has_odd_inst_def;
val _=capture "line_ok_alignment" line_ok_alignment;
val _=types "line_ok_alignment_types" line_ok_alignment;
val _=capture "has_odd_inst_alignment" has_odd_inst_alignment;
val _=types "has_odd_inst_alignment_types" has_odd_inst_alignment;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc((SIMP_CONV (srw_ss()) [asmPropsTheory.enc_ok_def,asmPropsTheory.offset_monotonic_def] THENC EVAL THENC SIMP_CONV (srw_ss()) [] THENC EVAL) q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg0 = template;
val cfg1 = ``^template with <| code_alignment := 1; encode := (λa.[0w;0w]) |>``;
val bad = ``^template with code_alignment := 1``;
val _ = observe "contract_one_byte" ``enc_ok ^cfg0``;
val _ = observe "contract_two_byte" ``enc_ok ^cfg1``;
val _ = observe "contract_bad_alignment" ``~enc_ok ^bad``;
val _ = observe "odd_padded_line" ``line_ok ^cfg0 sptree$LN [] 0 (Asm (Asmi (Inst Skip)) [0w;0w;0w] 3) /\ ODD(line_length (Asm (Asmi (Inst Skip)) [0w;0w;0w] 3 : 8 line))``;
val _ = observe "odd_valid_code" ``all_enc_ok ^cfg0 sptree$LN [] 0 [Section 1 [Asm (Asmi (Inst Skip)) [0w] 1;Asm (Asmi (Inst Skip)) [0w] 1]] /\ has_odd_inst ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 1;Asm (Asmi (Inst Skip)) [0w] 1]]:8 sec list)``;
val _ = observe "even_padded_line" ``line_ok ^cfg1 sptree$LN [] 0 (Asm (Asmi (Inst Skip)) [0w;0w;0w;0w] 4) /\ ~has_odd_inst ([Section 1 [Asm (Asmi (Inst Skip)) [0w;0w;0w;0w] 4]]:8 sec list)``;
val _ = observe "validity_guard_needed" ``~line_ok ^cfg1 sptree$LN [] 0 (Asm (Asmi (Inst Skip)) [0w] 1) /\ has_odd_inst ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 1]]:8 sec list)``;
val _ = observe "encoder_guard_needed" ``line_ok ^bad sptree$LN [] 0 (Asm (Asmi (Inst Skip)) [0w] 1) /\ has_odd_inst ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 1]]:8 sec list)``;
val _ = observe "physical_not_annotation" ``has_odd_inst ([Section 1 [Label 1 7 2]]:8 sec list) /\ ~has_odd_inst ([Section 1 [Asm (Asmi (Inst Skip)) [0w;0w] 3]]:8 sec list) /\ has_odd_inst ([Section 1 [LabAsm (Call (Lab 1 7)) 0w [0w] 2]]:8 sec list)``;
val _ = observe "empty_zero_label" ``~has_odd_inst ([Section 1 [];Section 2 [Label 2 7 0]]:8 sec list)``;
val cfg1wide = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w) |> : 1 asm_config``;
val cfg80wide = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w) |> : 80 asm_config``;
val _ = observe "width1_odd_line" ``enc_ok ^cfg1wide /\ line_ok ^cfg1wide sptree$LN [] 0 (Asm (Asmi (Inst Skip)) [0w] 1) /\ ODD(line_length (Asm (Asmi (Inst Skip)) [0w] 1 : 1 line))``;
val _ = observe "width80_odd_code" ``enc_ok ^cfg80wide /\ all_enc_ok ^cfg80wide sptree$LN [] (2 ** 80) [Section 1 [Asm (Asmi (Inst Skip)) [0w] 1;Asm (Asmi (Inst Skip)) [0w] 1]] /\ has_odd_inst ([Section 1 [Asm (Asmi (Inst Skip)) [0w] 1;Asm (Asmi (Inst Skip)) [0w] 1]]:80 sec list)``;
