load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val t=DB.fetch "lab_to_targetProof" "genlist_line_to_info_entry_pc_max";
val _=capture "genlist_line_to_info_entry_pc_max" t;
val _=types "genlist_line_to_info_entry_pc_max_types" t;
val _=print("genlist_line_to_info_entry_pc_max_hypotheses="^Int.toString(length(hyp t))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (-128w,127w); hw_offset := (-128w,127w); byte_offset := (-128w,127w);
 jump_offset := (-128w,127w); cjump_offset := (-128w,127w); loc_offset := (-128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val code=``[Section 0 [];Section 1 [Label 1 7 0;Asm (ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 2;Asm (Cbw 1 2) [0w;0w] 2;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 2 [Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2;Asm (Asmi (Inst Skip)) [0w;0w] 2];Section 0 []]:8 sec list``;
val names=``[SharedMem MappedWrite]``;
val initial=``<|entry_pc:=100;nbytes:=3w;addr_reg:=99;addr_off:=42;reg:=77;exit_pc:=103|>``;
val loadinfo=``<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=5;reg:=3;exit_pc:=9|>``;
val storeinfo=``<|entry_pc:=13;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=4;exit_pc:=15|>``;
fun checked label th=(print(label^"=");print_term(rhs(concl(EQT_INTRO th)));print"\n");
fun observe label q=checked label (prove(q, simp [] >> EVAL_TAC >> simp []));
fun discharge th = MP th (prove(fst(dest_imp(concl th)), simp [] >> EVAL_TAC >> simp []));
val _=observe "actual_max" ``EVERY(λx.(SND x).entry_pc < pos_val(num_pcs ^code) 0 ^code)(FLAT(GENLIST(λi.line_to_info ^code 0(i,asm_fetch_aux i ^code))(num_pcs ^code)))``;
val _=observe "actual_entries" ``MAP(λx.(SND x).entry_pc)(FLAT(GENLIST(λi.line_to_info ^code 0(i,asm_fetch_aux i ^code))(num_pcs ^code))) = [0;6]``;
val _=observe "actual_end" ``pos_val(num_pcs ^code) 0 ^code = 10``;
val _=observe "empty" ``EVERY(λx.(SND x).entry_pc < pos_val 0 0 ([]:8 sec list)) ([]:(ffiname#shmem_info_num) list)``;
val _=observe "valid_guard" ``all_enc_ok ^cfg ^old [] 18 ^code``;
val _=observe "strict_failure" ``~(0 < pos_val 1 0 ([Section 0 [Asm(ShareMem Load8 3 (Addr 2 5w)) [] 0]]:8 sec list))``;
