load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "label_prefix_zero_def" label_prefix_zero_def;
val _ = types "label_prefix_zero_def_types" label_prefix_zero_def;
val _ = capture "sec_label_prefix_zero_def" sec_label_prefix_zero_def;
val _ = types "sec_label_prefix_zero_def_types" sec_label_prefix_zero_def;
val _ = capture "label_prefix_zero_cons" label_prefix_zero_cons;
val _ = types "label_prefix_zero_cons_types" label_prefix_zero_cons;
val _ = capture "label_prefix_zero_append_suff" label_prefix_zero_append_suff;
val _ = types "label_prefix_zero_append_suff_types" label_prefix_zero_append_suff;
val _ = capture "label_prefix_zero_append_suff2" label_prefix_zero_append_suff2;
val _ = types "label_prefix_zero_append_suff2_types" label_prefix_zero_append_suff2;
val prefix_nil = prove (``label_prefix_zero []``, simp [label_prefix_zero_def]);
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) [label_prefix_zero_cons,prefix_nil]) q)); print "\n");
val _ = observe "empty_prefix" ``label_prefix_zero ([] : 8 labLang$line list)``;
val _ = observe "initial_zero_labels" ``label_prefix_zero ([Label 1 2 0;Label 1 3 0] : 8 labLang$line list)``;
val _ = observe "initial_bad_label_rejected" ``~label_prefix_zero ([Label 1 2 0;Label 1 3 7;Asm (Asmi (Inst Skip)) [] 0] : 8 labLang$line list)``;
val _ = observe "nonlabel_masks_later_label" ``label_prefix_zero ([Asm (Asmi (Inst Skip)) [] 0;Label 1 2 99] : 8 labLang$line list)``;
val _ = observe "zero_prefix_then_nonlabel" ``label_prefix_zero ([Label 1 2 0;Asm (Asmi (Inst Skip)) [] 3;Label 1 3 99] : 8 labLang$line list)``;
val _ = observe "labasm_masks_later_label" ``label_prefix_zero ([LabAsm (Jump (Lab 1 2)) 77w [] 3;Label 1 2 99] : 8 labLang$line list)``;
val _ = observe "append_positive" ``label_prefix_zero (([Label 1 2 0] : 8 labLang$line list) ++ [Label 1 3 0])``;
val _ = observe "append_bad_right_guard_required" ``~label_prefix_zero (([Label 1 2 0] : 8 labLang$line list) ++ [Label 1 3 7])``;
val _ = observe "append_nonlabel_allows_bad_right" ``label_prefix_zero (([Label 1 2 0;Asm (Asmi (Inst Skip)) [] 3] : 8 labLang$line list) ++ [Label 1 3 7])``;
val _ = observe "append_nonlabel_guard_required" ``~label_prefix_zero (([] : 8 labLang$line list) ++ [Label 1 3 7])``;
