load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "enc_lines_again_line_labs_exist" enc_lines_again_line_labs_exist;
val _ = types "enc_lines_again_line_labs_exist_types" enc_lines_again_line_labs_exist;
val _ = capture "enc_secs_again_all_labs_exist" enc_secs_again_all_labs_exist;
val _ = types "enc_secs_again_all_labs_exist_types" enc_secs_again_all_labs_exist;
val _ = show_types := false;
fun observe label q = (print(label ^ "=");print_term(rconc(QCONV(SIMP_CONV(srw_ss())[sptreeTheory.lookup_insert,sptreeTheory.lookup_def]) (rconc(EVAL q))));print "\n");
val labs = ``sptree$insert 3 (sptree$insert 4 10 sptree$LN) sptree$LN:num sptree$num_map sptree$num_map``;
val exists = ``sptree$insert 3 (sptree$insert 4 F sptree$LN) sptree$LN:bool sptree$num_map sptree$num_map``;
val enc = ``(\a. [7w;8w]):8 asm -> word8 list``;
val acc = ``[LabAsm(LocValue 2 (Lab 3 4)) 77w [9w] 2;Label 7 8 4]:8 labLang$line list``;
val lines = ``[LabAsm(Jump(Lab 3 4)) 99w [] 1;LabAsm Halt 99w [] 1]:8 labLang$line list``;
val result = ``[Label 7 8 4;LabAsm(LocValue 2 (Lab 3 4)) 77w [9w] 2;LabAsm(Jump(Lab 3 4)) 4w [7w;8w] 2;LabAsm Halt 232w [7w;8w] 2]:8 labLang$line list``;
val code = ``[Section 7 [Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3;LabAsm(Jump(Lab 3 4)) 99w [] 1;LabAsm Halt 99w [] 1];Section 8 [LabAsm(Call(Lab 3 4)) 99w [] 1];Section 9 []]:8 labLang$sec list``;
val codeResult = ``[Section 7 [Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3;LabAsm(Jump(Lab 3 4)) 6w [7w;8w] 2;LabAsm Halt 234w [7w;8w] 2];Section 8 [LabAsm(Call(Lab 3 4)) 2w [7w;8w] 2];Section 9 []]:8 labLang$sec list``;
val _ = observe "original_acc_input_guards" ``EVERY (line_labs_exist ^exists) ^acc /\ EVERY (line_labs_exist ^exists) ^lines``;
val _ = observe "growth_false_full_tuple" ``enc_lines_again ^labs [] 6 ^enc ^lines (^acc,T) = (^result,10,F)``;
val _ = observe "false_initial_full_tuple" ``enc_lines_again ^labs [] 6 ^enc ^lines (^acc,F) = (^result,10,F)``;
val _ = observe "growth_false_output_exists" ``EVERY (line_labs_exist ^exists) (FST(enc_lines_again ^labs [] 6 ^enc ^lines (^acc,T)))``;
val _ = observe "nongrowth_true_tuple_exists" ``enc_lines_again ^labs [] 6 ^enc ([LabAsm(Jump(Lab 3 4)) 99w [] 3]:8 labLang$line list) (^acc,T) = ([Label 7 8 4;LabAsm(LocValue 2 (Lab 3 4)) 77w [9w] 2;LabAsm(Jump(Lab 3 4)) 4w [7w;8w] 3],9,T) /\ EVERY (line_labs_exist ^exists) (FST(enc_lines_again ^labs [] 6 ^enc ([LabAsm(Jump(Lab 3 4)) 99w [] 3]:8 labLang$line list) (^acc,T)))``;
val _ = observe "empty_input_reverse_accumulator" ``enc_lines_again ^labs [] 34 ^enc [] (^acc,F) = (REVERSE ^acc,34,F) /\ EVERY (line_labs_exist ^exists) (REVERSE ^acc)``;
val _ = observe "sections_false_tuple_exists" ``enc_secs_again 0 ^labs [] ^enc ^code = (^codeResult,F) /\ all_labs_exist ^exists ^code /\ all_labs_exist ^exists ^codeResult``;
val _ = observe "missing_map_not_established" ``~all_labs_exist (LN:bool sptree$num_map sptree$num_map) ^code /\ ~all_labs_exist (LN:bool sptree$num_map sptree$num_map) ^codeResult``;
val _ = observe "all_seven_opcodes_false" ``let ls = [LabAsm(Jump(Lab 3 4)) 99w [] 1;LabAsm(JumpCmp Equal 2 (Imm 1w) (Lab 3 4)) 99w [] 1;LabAsm(LocValue 2 (Lab 3 4)) 99w [] 1;LabAsm(Call(Lab 99 88)) 99w [] 1;LabAsm(CallFFI(strlit "")) 99w [] 1;LabAsm Install 99w [] 1;LabAsm Halt 99w [] 1]:8 labLang$line list in let r = enc_lines_again ^labs [ExtCall(strlit "a");ExtCall(strlit "");ExtCall(strlit "")] 0 ^enc ls ([],T) in SND(SND r)=F /\ EVERY (line_labs_exist ^exists) ls /\ EVERY (line_labs_exist ^exists) (FST r)``;
val _ = observe "width1_empty" ``enc_lines_again LN [] 17 ((\a. []):1 asm -> word8 list) [] ([],F) = ([],17,F) /\ all_labs_exist (LN:bool sptree$num_map sptree$num_map) ([]:1 labLang$sec list)``;
