load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_offset_ok_def" line_offset_ok_def;
val _ = types "line_offset_ok_def_types" line_offset_ok_def;
val _ = capture "lines_offset_ok_def" lines_offset_ok_def;
val _ = types "lines_offset_ok_def_types" lines_offset_ok_def;
val _ = capture "lines_offset_ok_append" lines_offset_ok_append;
val _ = types "lines_offset_ok_append_types" lines_offset_ok_append;
val _ = capture "offset_ok_def" offset_ok_def;
val _ = types "offset_ok_def_types" offset_ok_def;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL q)))); print "\n");
val labs = ``insert 3 (insert 4 10 LN) LN:num sptree$num_map sptree$num_map``;
val ffis = ``[ExtCall(strlit "a");ExtCall(strlit "");ExtCall(strlit "")]``;
val l1 = ``[Label 1 2 3;Asm(Asmi(Inst Skip)) [] 2]:8 labLang$line list``;
val l2 = ``[LabAsm(Jump(Lab 3 4)) 5w [] 3]:8 labLang$line list``;
val _ = observe "label_unconstrained" ``line_offset_ok ^labs ^ffis 5 (Label 1 2 999:8 labLang$line)``;
val _ = observe "asm_unconstrained" ``line_offset_ok ^labs ^ffis 5 (Asm(Asmi(Inst Skip)) [] 999:8 labLang$line)``;
val _ = observe "all_lab_opcodes" ``EVERY (line_offset_ok ^labs ^ffis 5) ([LabAsm(Jump(Lab 3 4)) 5w [] 99;LabAsm(JumpCmp Equal 2 (Imm 1w) (Lab 3 4)) 5w [7w] 99;LabAsm(LocValue 2 (Lab 3 4)) 5w [] 0;LabAsm(Call(Lab 3 4)) 5w [] 999;LabAsm(CallFFI(strlit "")) 187w [] 0;LabAsm Install 219w [] 0;LabAsm Halt 235w [] 0]:8 labLang$line list)``;
val _ = observe "wrong_stored_word" ``~line_offset_ok ^labs ^ffis 5 (LabAsm(Jump(Lab 3 4)) 99w [5w] 1:8 labLang$line)``;
val _ = observe "missing_label_default" ``line_offset_ok LN ^ffis 5 (LabAsm(Jump(Lab 3 4)) 251w [] 99:8 labLang$line)``;
val _ = observe "missing_ffi_default" ``line_offset_ok ^labs [] 5 (LabAsm(CallFFI(strlit "")) 203w [] 99:8 labLang$line)``;
val _ = observe "annotation_append" ``lines_offset_ok ^labs ^ffis 0 (^l1++^l2) /\ lines_offset_ok ^labs ^ffis 0 ^l1 /\ lines_offset_ok ^labs ^ffis (0+SUM(MAP line_len ^l1)) ^l2``;
val _ = observe "bad_append_position" ``~lines_offset_ok ^labs ^ffis 0 ^l2``;
val _ = observe "sections_advance" ``offset_ok ^labs ^ffis 0 [Section 7 ^l1;Section 8 ^l2;Section 9 []]``;
val _ = observe "bad_section_reset" ``~offset_ok ^labs ^ffis 0 ([Section 7 ^l1;Section 8 [LabAsm(Jump(Lab 3 4)) 10w [] 3]]:8 labLang$sec list)``;
val _ = observe "empty_width1" ``lines_offset_ok LN [] 17 ([]:1 labLang$line list) /\ offset_ok LN [] 17 ([Section 7 [];Section 8 []]:1 labLang$sec list) /\ line_offset_ok LN [] 0 (LabAsm Halt 0w [] 99:1 labLang$line)``;
val _ = observe "large_width80" ``line_offset_ok LN [] (2**80+1) (LabAsm Halt (n2w(2**80-17)) [7w] 99:80 labLang$line) /\ ~line_offset_ok LN [] (2**80+1) (LabAsm Halt (n2w(2**70+3)) [7w] 99:80 labLang$line)``;
