load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "dec_clock_align_sdm";
val _ = show_types := true;
val _ = print "dec_clock_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "dec_clock_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("dec_clock_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "dec_clock_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "inc_pc_align_sdm";
val _ = show_types := true;
val _ = print "inc_pc_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "inc_pc_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("inc_pc_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "inc_pc_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "upd_pc_align_sdm";
val _ = show_types := true;
val _ = print "upd_pc_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "upd_pc_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("upd_pc_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "upd_pc_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "get_pc_value_align_sdm";
val _ = show_types := true;
val _ = print "get_pc_value_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "get_pc_value_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("get_pc_value_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "get_pc_value_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "get_ret_Loc_align_sdm";
val _ = show_types := true;
val _ = print "get_ret_Loc_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "get_ret_Loc_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("get_ret_Loc_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "get_ret_Loc_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "read_bytearray_mem_load_byte_aux_align_sdm";
val _ = show_types := true;
val _ = print "read_bytearray_mem_load_byte_aux_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "read_bytearray_mem_load_byte_aux_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("read_bytearray_mem_load_byte_aux_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "read_bytearray_mem_load_byte_aux_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "write_bytearray_align_sdm";
val _ = show_types := true;
val _ = print "write_bytearray_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "write_bytearray_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("write_bytearray_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "write_bytearray_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
