load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "LENGTH_prog_to_bytes" LENGTH_prog_to_bytes;
val _=types "LENGTH_prog_to_bytes_types" LENGTH_prog_to_bytes;
val _=print("LENGTH_prog_to_bytes_hypotheses="^Int.toString(length(hyp LENGTH_prog_to_bytes))^"\n");
val _=capture "LENGTH_prog_to_bytes2" LENGTH_prog_to_bytes2;
val _=types "LENGTH_prog_to_bytes2_types" LENGTH_prog_to_bytes2;
val _=print("LENGTH_prog_to_bytes2_hypotheses="^Int.toString(length(hyp LENGTH_prog_to_bytes2))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val jumpcode = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0]]:8 sec list``;
val asmcode = ``[Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0]]:8 sec list``;
val code = ``^jumpcode ++ ^asmcode``;
val _=observe "physical_sum" ``all_enc_ok ^cfg ^old [] 18 ^code /\ SUM (MAP (SUM o MAP line_length o Section_lines) ^code) = LENGTH (prog_to_bytes ^code) /\ LENGTH (prog_to_bytes ^code)=4``;
val _=observe "independent_fold" ``FOLDL (λpos sec.sec_length (Section_lines sec) pos) 101 ^code = 105``;
val _=observe "label_zero" ``all_enc_ok ^cfg ^old [] 18 [Section 7 [Label 9 2 0]] /\ LENGTH (prog_to_bytes [Section 7 [Label 9 2 0]:8 sec])=0``;
val _=observe "bad_annotation" ``~all_enc_ok ^cfg ^old [] 18 [Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 99]]``;
val _=observe "bad_label" ``~all_enc_ok ^cfg ^old [] 18 [Section 7 [Label 9 2 3]]``;
val _=observe "empty" ``all_enc_ok ^cfg ^old [] 18 [] /\ FOLDL (λpos sec.sec_length (Section_lines sec) pos) 101 ([]:8 sec list)=101 /\ LENGTH (prog_to_bytes ([]:8 sec list))=0``;
