load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_length_pad_section1" line_length_pad_section1;
val _ = types "line_length_pad_section1_types" line_length_pad_section1;
val _ = capture "line_len_pad_section1" line_len_pad_section1;
val _ = types "line_len_pad_section1_types" line_len_pad_section1;
val _ = capture "line_len_pad_section0" line_len_pad_section0;
val _ = types "line_len_pad_section0_types" line_len_pad_section0;
val _ = capture "line_length_pad_section" line_length_pad_section;
val _ = types "line_length_pad_section_types" line_length_pad_section;
val _ = capture "label_zero_line_length_pad_section" label_zero_line_length_pad_section;
val _ = types "label_zero_line_length_pad_section_types" label_zero_line_length_pad_section;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = observe "nonlabel_physical" ``SUM(MAP line_length(pad_section [9w] [Label 1 2 1;Asm (Asmi (Inst Skip)) [2w] 3] [Asm (Asmi (Inst Skip)) [1w] 1] : 8 labLang$line list)) = 5``;
val _ = observe "nonlabel_annotated" ``SUM(MAP line_len(pad_section [9w] [Label 1 2 1;Asm (Asmi (Inst Skip)) [2w] 3] [Asm (Asmi (Inst Skip)) [1w] 1] : 8 labLang$line list)) = 5``;
val _ = observe "zero_empty_nop" ``SUM(MAP line_len(pad_section [] [Label 1 2 0;Asm (Asmi (Inst Skip)) [2w] 3] [Label 1 3 99] : 8 labLang$line list)) = 102``;
val _ = observe "zero_multibyte_map" ``MAP line_length(pad_section [9w;8w] [Label 1 2 0;LabAsm (Jump (Lab 1 2)) 77w [2w] 3] [Asm (Asmi (Inst Skip)) [1w] 1] : 8 labLang$line list) = [1;0;3]``;
val _ = observe "labels_prefix_physical" ``SUM(MAP line_length(pad_section [9w] [Label 1 2 0;Asm (Asmi (Inst Skip)) [2w] 3;Label 1 3 1] [Label 1 4 0] : 8 labLang$line list)) = 4``;
val _ = observe "prefix_guard_required" ``SUM(MAP line_length(pad_section [9w] [Label 1 2 1] [Label 1 4 0] : 8 labLang$line list)) <> 1``;
val _ = observe "one_byte_guard_required" ``SUM(MAP line_length(pad_section [9w;8w] [Label 1 2 1] [Asm (Asmi (Inst Skip)) [1w] 1] : 8 labLang$line list)) <> 2``;
val _ = observe "bounds_guard_required" ``MAP line_length(pad_section [9w] [Asm (Asmi (Inst Skip)) [1w;2w] 1] [] : 8 labLang$line list) <> [1]``;
