load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "labs_domain_compute_labels_alt" labs_domain_compute_labels_alt;
val _=types "labs_domain_compute_labels_alt_types" labs_domain_compute_labels_alt;
val _=show_types:=false;
fun observe label q=(print(label ^ "=");print_term(rconc((EVAL THENC QCONV(SIMP_CONV(srw_ss())[sptreeTheory.lookup_insert,sptreeTheory.lookup_def])) q));print "\n");
val initial=``sptree$insert 99 (sptree$fromAList [(0,777);(5,2**90)]) sptree$LN:num sptree$num_map sptree$num_map``;
val code=``[Section 7 [Label 1 2 0;Asm(Asmi(Inst Skip)) [] 3;Label 9 0 4;LabAsm Halt 99w [] 2;Label 88 2 1];Section 8 [];Section 9 [Label 888 5 2]]:8 labLang$sec list``;
val _=observe "mixed_full_nested_map" ``compute_labels_alt 6 ^code ^initial = sptree$insert 9 (sptree$fromAList [(0,16);(5,18)]) (sptree$insert 8 (sptree$fromAList [(0,16)]) (sptree$insert 7 (sptree$fromAList [(0,6);(2,16);(2,6)]) ^initial))``;
val _=observe "old_values_duplicate_priority_empty_entry" ``lab_lookup 99 5 (compute_labels_alt 6 ^code ^initial)=SOME(2**90) /\ lab_lookup 7 2 (compute_labels_alt 6 ^code ^initial)=SOME 16 /\ lab_lookup 8 0 (compute_labels_alt 6 ^code ^initial)=SOME 16``;
val _=observe "distinctness_counterexample" ``let code=[Section 7 [Label 7 4 1];Section 7 []]:8 labLang$sec list in ~ALL_DISTINCT(MAP Section_num code) /\ lab_lookup 7 4 (compute_labels_alt 0 code sptree$LN)=NONE``;
val _=observe "freshness_counterexample" ``let labs=sptree$insert 7 (sptree$fromAList [(8,99)]) sptree$LN in lab_lookup 7 8 labs=SOME 99 /\ lab_lookup 7 8 (compute_labels_alt 0 ([Section 7 []]:8 labLang$sec list) labs)=NONE``;
val _=observe "width1_empty_initial_retained" ``compute_labels_alt 17 ([]:1 labLang$sec list) ^initial=^initial``;
val _=observe "width80_large_position" ``compute_labels_alt (2**80) ([Section 9 [Label 999 0 1;Label 888 5 2]]:80 labLang$sec list) ^initial=sptree$insert 9 (sptree$fromAList [(0,2**80);(5,2**80+3)]) ^initial``;
