load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "SND_lines_upd_lab_len" SND_lines_upd_lab_len;
val _ = types "SND_lines_upd_lab_len_types" SND_lines_upd_lab_len;
val _ = capture "EVEN_sec_length_lines_upd_lab_len" EVEN_sec_length_lines_upd_lab_len;
val _ = types "EVEN_sec_length_lines_upd_lab_len_types" EVEN_sec_length_lines_upd_lab_len;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = observe "empty_position" ``lines_upd_lab_len 3 [] [Label 7 9 101] = ([Label 7 9 101],3)``;
val _ = observe "empty_even" ``EVEN(SUM(MAP line_len (FST(lines_upd_lab_len 2 [] [Label 7 9 100]))))``;
val _ = observe "nonempty_odd_pos_odd_acc" ``lines_upd_lab_len 3 [Label 1 2 77] [Label 7 9 101] = ([Label 7 9 101;Label 1 2 1],4)``;
val _ = observe "nonempty_even_output" ``EVEN(SUM(MAP line_len(FST(lines_upd_lab_len 3 [Label 1 2 77] [Label 7 9 101]))))``;
val _ = observe "guard_required" ``~EVEN(SUM(MAP line_len(FST(lines_upd_lab_len 3 [Label 1 2 77] []))))``;
val _ = observe "final_label_required" ``~EVEN(SUM(MAP line_len(FST(lines_upd_lab_len 0 [Asm (Asmi (Inst Skip)) [] 3] []))))``;
val _ = observe "full_position_subtraction" ``SND(lines_upd_lab_len 3 [Label 1 2 77;Asm (Asmi (Inst Skip)) [] 3;Label 1 3 99] [Label 7 9 101]) = 3 + SUM(MAP line_len(FST(lines_upd_lab_len 3 [Label 1 2 77;Asm (Asmi (Inst Skip)) [] 3;Label 1 3 99] [Label 7 9 101]))) - 101``;
