load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_enc_with_nop_pad_section1" lines_enc_with_nop_pad_section1;
val _ = types "lines_enc_with_nop_pad_section1_types" lines_enc_with_nop_pad_section1;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) []) (rconc(EVAL q)))); print "\n");
val enc = ``(λa:8 asm. case a of Jump w => [w] | JumpCmp c r i w => [w] | Loc r w => [w] | _ => [0w])``;
val aux = ``[Label 1 2 0;Asm (Asmi (Inst Skip)) [0w] 1] : 8 labLang$line list``;
val code = ``[Label 1 9 1;LabAsm (Jump (Lab 1 2)) 77w [249w] 3;Label 1 10 0;Asm (Asmi (Inst Skip)) [0w] 1;LabAsm Halt 88w [229w] 2;LabAsm (Call (Lab 1 2)) 99w [0w] 2] : 8 labLang$line list``;
val _ = observe "mixed_source_guards" ``LENGTH(^enc(Inst Skip))=1 /\ lines_encd ^enc LN [] (5+SUM(MAP line_len ^aux)) ^code /\ lines_enc_with_nop ^enc LN [] 5 (REVERSE ^aux) /\ ~EVERY is_Label ^aux /\ EVERY label_one ^code``;
val _ = observe "mixed_padded_encoding" ``lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] ^code ^aux)``;
val _ = observe "mixed_full_tuple" ``pad_section [0w] ^code ^aux = [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 1 2 0;Label 1 9 0;LabAsm (Jump (Lab 1 2)) 77w [249w;0w;0w] 3;Label 1 10 0;Asm (Asmi (Inst Skip)) [0w] 1;LabAsm Halt 88w [229w;0w] 2;LabAsm (Call (Lab 1 2)) 99w [0w;0w] 2]``;
val _ = observe "repeated_one_labels" ``pad_section [0w] ([Label 1 9 1;Label 1 10 1]:8 labLang$line list) ^aux = [Asm (Asmi (Inst Skip)) [0w;0w;0w] 3;Label 1 2 0;Label 1 9 0;Label 1 10 0] /\ lines_enc_with_nop ^enc LN [] 5 (pad_section [0w] [Label 1 9 1;Label 1 10 1] ^aux)``;
val _ = observe "zero_label_unchanged" ``pad_section [0w] ([Label 1 9 0]:8 labLang$line list) ^aux = REVERSE ^aux ++ [Label 1 9 0]``;
val _ = observe "empty_code" ``pad_section [0w] ([]:8 labLang$line list) ^aux = REVERSE ^aux``;
val _ = observe "jump_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (Jump (Lab 1 2)) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (Jump (Lab 1 2)) 77w [0w] 3] ^aux)``;
val _ = observe "jumpcmp_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (JumpCmp Equal 0 (Reg 1) (Lab 1 2)) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (JumpCmp Equal 0 (Reg 1) (Lab 1 2)) 77w [0w] 3] ^aux)``;
val _ = observe "locvalue_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (LocValue 0 (Lab 1 2)) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (LocValue 0 (Lab 1 2)) 77w [0w] 3] ^aux)``;
val _ = observe "call_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (Call (Lab 1 2)) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (Call (Lab 1 2)) 77w [0w] 3] ^aux)``;
val _ = observe "ffi_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (CallFFI (strlit "")) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (CallFFI (strlit "")) 77w [0w] 3] ^aux)``;
val _ = observe "install_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (Install) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (Install) 77w [0w] 3] ^aux)``;
val _ = observe "halt_actual_guard_and_result" ``lines_encd (λa:8 asm.[0w]) LN [] 6 [LabAsm (Halt) 77w [0w] 3] /\ lines_enc_with_nop (λa:8 asm.[0w]) LN [] 5 (pad_section [0w] [LabAsm (Halt) 77w [0w] 3] ^aux)``;
