load "bossLib";
load "preamble";
load "lab_filterProofTheory";
open bossLib HolKernel Parse preamble labSemTheory lab_filterTheory lab_filterProofTheory;
(* Exact temporary simplifier setup from original script lines10/12. *)
val _ = temp_delsimps ["lift_disj_eq", "lift_imp_disj"];
val _ = temp_delsimps ["NORMEQ_CONV"];
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th,ACCEPT_TAC th)))));print "\n");
val th = DB.fetch "labSem" "next_label_def";
val _ = show_types := true;
val _ = capture "next_label_def" th;
val _ = types "next_label_def_types" th;
val _ = print("next_label_def_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "next_label_def_proved" th;
val th = DB.fetch "labSem" "get_lab_after_def";
val _ = show_types := true;
val _ = capture "get_lab_after_def" th;
val _ = types "get_lab_after_def_types" th;
val _ = print("get_lab_after_def_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "get_lab_after_def_proved" th;
val th = DB.fetch "labSem" "get_ret_Loc_def";
val _ = show_types := true;
val _ = capture "get_ret_Loc_def" th;
val _ = types "get_ret_Loc_def_types" th;
val _ = print("get_ret_Loc_def_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "get_ret_Loc_def_proved" th;
