load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "asm_fetch_align_dm";
val _ = show_types := true;
val _ = print "asm_fetch_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "asm_fetch_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("asm_fetch_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "asm_fetch_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "read_reg_align_dm";
val _ = show_types := true;
val _ = print "read_reg_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "read_reg_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("read_reg_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "read_reg_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "upd_reg_align_dm";
val _ = show_types := true;
val _ = print "upd_reg_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "upd_reg_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("upd_reg_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "upd_reg_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "upd_mem_align_dm";
val _ = show_types := true;
val _ = print "upd_mem_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "upd_mem_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("upd_mem_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "upd_mem_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "binop_upd_align_dm";
val _ = show_types := true;
val _ = print "binop_upd_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "binop_upd_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("binop_upd_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "binop_upd_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "reg_imm_align_dm";
val _ = show_types := true;
val _ = print "reg_imm_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "reg_imm_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("reg_imm_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "reg_imm_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "assert_align_dm";
val _ = show_types := true;
val _ = print "assert_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "assert_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("assert_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "assert_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "asm_fetch_align_sdm";
val _ = show_types := true;
val _ = print "asm_fetch_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "asm_fetch_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("asm_fetch_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "asm_fetch_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "read_reg_align_sdm";
val _ = show_types := true;
val _ = print "read_reg_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "read_reg_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("read_reg_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "read_reg_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "upd_reg_align_sdm";
val _ = show_types := true;
val _ = print "upd_reg_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "upd_reg_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("upd_reg_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "upd_reg_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "upd_mem_align_sdm";
val _ = show_types := true;
val _ = print "upd_mem_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "upd_mem_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("upd_mem_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "upd_mem_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "binop_upd_align_sdm";
val _ = show_types := true;
val _ = print "binop_upd_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "binop_upd_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("binop_upd_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "binop_upd_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "reg_imm_align_sdm";
val _ = show_types := true;
val _ = print "reg_imm_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "reg_imm_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("reg_imm_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "reg_imm_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "assert_align_sdm";
val _ = show_types := true;
val _ = print "assert_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "assert_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("assert_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "assert_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
