load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory;
val th = DB.fetch "lab_to_targetProof" "list_subset_TAKE";
val _ = show_types := true;
val _ = print "list_subset_TAKE=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "list_subset_TAKE_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("list_subset_TAKE_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "list_subset_TAKE_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "lab_to_targetProof" "list_subset_trans";
val _ = show_types := true;
val _ = print "list_subset_trans=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "list_subset_trans_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("list_subset_trans_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "list_subset_trans_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "lab_to_targetProof" "list_subset_refl";
val _ = show_types := true;
val _ = print "list_subset_refl=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "list_subset_refl_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("list_subset_refl_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "list_subset_refl_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
