load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "label_zero_pos_ok_lines_even_labels" label_zero_pos_ok_lines_even_labels;
val _=types "label_zero_pos_ok_lines_even_labels_types" label_zero_pos_ok_lines_even_labels;
val _=capture "label_zero_pos_ok_even_labels" label_zero_pos_ok_even_labels;
val _=types "label_zero_pos_ok_even_labels_types" label_zero_pos_ok_even_labels;
val _=show_types:=false;
fun observe label q=(print(label ^ "=");print_term(rconc(EVAL q));print "\n");
val _=observe "mixed_both_guards" ``let ls=[Asm(Asmi(Inst Skip)) [1w;2w;3w] 1;Label 999 4 0;LabAsm Halt 99w [] 2;Label 9 0 0]:8 labLang$line list in EVERY label_zero ls /\ lab_len_pos_ok 3 ls /\ lines_even_labels 3 ls``;
val _=observe "zero_guard_needed" ``lab_len_pos_ok 3 ([Label 99 4 1]:8 labLang$line list) /\ ~label_zero (Label 99 4 1:8 labLang$line) /\ ~lines_even_labels 3 ([Label 99 4 1]:8 labLang$line list)``;
val _=observe "position_guard_needed" ``label_zero (Label 99 4 0:8 labLang$line) /\ ~lab_len_pos_ok 3 ([Label 99 4 0]:8 labLang$line list) /\ ~lines_even_labels 3 ([Label 99 4 0]:8 labLang$line list)``;
val _=observe "odd_empty_section_valid" ``even_labels 3 ([Section 7 []]:8 labLang$sec list) /\ all_lab_len_pos_ok 3 ([Section 7 []]:8 labLang$sec list)``;
val _=observe "multiple_sections_annotation" ``even_labels 3 ([Section 7 [Asm(Asmi(Inst Skip)) [1w;2w;3w] 1;Label 999 4 0;LabAsm Halt 99w [] 2;Label 9 0 0];Section 8 [];Section 9 [Label 888 5 0]]:8 labLang$sec list)``;
val _=observe "width1_empty" ``lines_even_labels 17 ([]:1 labLang$line list)``;
val _=observe "width80_large_position" ``lines_even_labels (2**80) ([Label 999 5 0]:80 labLang$line list)``;
