load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "ALOOKUP_section_labels_ignore" ALOOKUP_section_labels_ignore;
val _=types "ALOOKUP_section_labels_ignore_types" ALOOKUP_section_labels_ignore;
val _=print "ALOOKUP_section_labels_ignore_hypotheses=";
val _=print(Int.toString(length(hyp ALOOKUP_section_labels_ignore)) ^ "\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _=observe "empty_duplicate_acc" ``ALOOKUP (SND (section_labels 7 ([]:8 line list) [(9,4);(9,6)])) 9 = SOME 4``;
val _=observe "missing_key" ``ALOOKUP (SND (section_labels 7 ([Label 1 2 99;Label 1 2 0]:8 line list) [(9,4)])) 3 = NONE``;
val _=observe "arbitrary_annotations" ``ALOOKUP (SND (section_labels 7 ([Label 1 2 99;Asm (Asmi (Inst Skip)) [] 123;LabAsm Halt 0w [] 456]:8 line list) [(9,4)])) 9 = SOME 4``;
val _=observe "guard_needed" ``ALOOKUP (SND (section_labels 7 ([Label 1 9 2]:8 line list) [(9,4)])) 9 = SOME 9``;
val _=observe "zero_query" ``ALOOKUP (SND (section_labels 7 ([Label 1 0 99]:8 line list) [(0,4)])) 0 = SOME 4``;
val _=observe "width1" ``ALOOKUP (SND (section_labels 1208925819614629174706176 ([Label 1 2 99]:1 line list) [(9,4)])) 9 = SOME 4``;
val _=observe "width80" ``ALOOKUP (SND (section_labels 1208925819614629174706176 ([Label 1 2 99]:80 line list) [(9,4)])) 9 = SOME 4``;
