load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "align_sdm_aligned";
val _ = show_types := true;
val _ = print "align_sdm_aligned=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "align_sdm_aligned_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("align_sdm_aligned_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "align_sdm_aligned_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "share_mem_load_align_sdm";
val _ = show_types := true;
val _ = print "share_mem_load_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "share_mem_load_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("share_mem_load_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "share_mem_load_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "share_mem_store_align_sdm";
val _ = show_types := true;
val _ = print "share_mem_store_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "share_mem_store_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("share_mem_store_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "share_mem_store_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "share_mem_op_align_sdm_simp";
val _ = show_types := true;
val _ = print "share_mem_op_align_sdm_simp=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "share_mem_op_align_sdm_simp_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("share_mem_op_align_sdm_simp_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "share_mem_op_align_sdm_simp_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
