load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "offset_ok_pad_code" offset_ok_pad_code;
val _ = types "offset_ok_pad_code_types" offset_ok_pad_code;
val _ = show_types := false;
val prefix_nil = prove(``label_prefix_zero ([]:8 labLang$line list)``,simp[label_prefix_zero_def]);
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL(rconc(QCONV(SIMP_CONV(srw_ss())[sec_label_prefix_zero_def,label_prefix_zero_cons,prefix_nil]) q)))))); print "\n");
val labs = ``insert 3 (insert 4 10 LN) LN:num sptree$num_map sptree$num_map``;
val code = ``[Section 7 [Label 1 2 0;LabAsm Halt 240w [] 3;Label 1 3 1];Section 8 [Label 1 4 0;LabAsm(Call(Lab 3 4)) 6w [] 3;Label 1 5 1];Section 9 []]:8 labLang$sec list``;
val zero = ``[Section 7 [Label 1 2 0;LabAsm Halt 240w [] 2;Label 1 3 0];Section 8 [Label 1 4 0;LabAsm(Jump(Lab 3 4)) 8w [] 2;Label 1 5 0];Section 9 []]:8 labLang$sec list``;
val _ = observe "original_five_guards" ``(LENGTH ([0w]:word8 list) <> 1 ==> EVERY sec_label_zero ^code) /\ EVERY sec_label_one ^code /\ EVERY sec_label_prefix_zero ^code /\ all_lab_len_pos_ok 0 ^code /\ offset_ok ^labs [] 0 ^code``;
val _ = observe "mixed_full_tuple" ``pad_code [0w] ^code = [Section 7 [Label 1 2 0;LabAsm Halt 240w [0w;0w;0w;0w] 4;Label 1 3 0];Section 8 [Label 1 4 0;LabAsm(Call(Lab 3 4)) 6w [0w;0w;0w;0w] 4;Label 1 5 0];Section 9 []]``;
val _ = observe "mixed_output_offsets" ``offset_ok ^labs [] 0 (pad_code [0w] ^code)``;
val _ = observe "zero_original_guards" ``EVERY sec_label_zero ^zero /\ EVERY sec_label_one ^zero /\ EVERY sec_label_prefix_zero ^zero /\ all_lab_len_pos_ok 0 ^zero /\ offset_ok ^labs [] 0 ^zero``;
val _ = observe "empty_nop_offsets" ``pad_code [] ^zero = ^zero /\ offset_ok ^labs [] 0 (pad_code [] ^zero)``;
val _ = observe "multibyte_nop_offsets" ``offset_ok ^labs [] 0 (pad_code [7w;8w] ^zero)``;
val _ = observe "prefix_guard_necessary" ``~offset_ok LN [] 1 (pad_code [0w] ([Section 7 [Label 1 2 1;LabAsm Halt 238w [] 0]]:8 labLang$sec list))``;
val _ = observe "input_offset_necessary" ``~offset_ok LN [] 0 (pad_code [0w] ([Section 7 [LabAsm Halt 99w [] 2]]:8 labLang$sec list))``;
val _ = observe "empty_width1" ``offset_ok LN [] 17 (pad_code [0w] ([]:1 labLang$sec list))``;
