load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_upd_lab_len_encd0_label_zero" lines_upd_lab_len_encd0_label_zero;
val _ = types "lines_upd_lab_len_encd0_label_zero_types" lines_upd_lab_len_encd0_label_zero;
val _ = capture "upd_lab_len_encd0_label_zero" upd_lab_len_encd0_label_zero;
val _ = types "upd_lab_len_encd0_label_zero_types" upd_lab_len_encd0_label_zero;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) []) (rconc(EVAL q)))); print "\n");
val lines = ``[Label 1 2 999;Asm (Asmi (Inst Skip)) [0w;0w] 2;LabAsm (Jump (Lab 1 2)) 77w [0w;0w] 2;Label 1 3 777] : 8 labLang$line list``;
val out = ``[Label 1 2 0;Asm (Asmi (Inst Skip)) [0w;0w] 2;LabAsm (Jump (Lab 1 2)) 77w [0w;0w] 2;Label 1 3 0] : 8 labLang$line list``;
val _ = observe "full_even_update" ``lines_upd_lab_len 2 ^lines [] = (^out,6)``;
val _ = observe "mixed_source_encd0" ``EVERY (line_encd0 (K [0w;0w])) ^lines``;
val _ = observe "all_updated_labels_zero" ``EVERY label_zero ^out``;
val _ = observe "zero_accumulator_preserved" ``FST(lines_upd_lab_len 2 ^lines [Label 9 8 0]) = Label 9 8 0 :: ^out``;
val _ = observe "full_two_sections" ``upd_lab_len 2 [Section 1 ^lines;Section 3 [Label 3 4 88]] = [Section 1 ^out;Section 3 [Label 3 4 0]]``;
val _ = observe "odd_position_guard_required" ``~EVERY label_zero(FST(lines_upd_lab_len 1 [Label 1 2 77] []))``;
val _ = observe "nonzero_alignment_guard_required" ``~EVERY label_zero(FST(lines_upd_lab_len 0 [Asm (Asmi (Inst Skip)) [0w] 1;Label 1 2 77] []))``;
val _ = observe "bad_accumulator_guard_required" ``~EVERY label_zero(FST(lines_upd_lab_len 2 ^lines [Label 9 8 1]))``;
