load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "even_labels_def" even_labels_def;
val _=types "even_labels_def_types" even_labels_def;
val _=capture "lines_even_labels_def" lines_even_labels_def;
val _=types "lines_even_labels_def_types" lines_even_labels_def;
val _=capture "even_labels_alt" even_labels_alt;
val _=types "even_labels_alt_types" even_labels_alt;
val _=capture "even_labels_strong_def" even_labels_strong_def;
val _=types "even_labels_strong_def_types" even_labels_strong_def;
val _=capture "lines_even_labels_append" lines_even_labels_append;
val _=types "lines_even_labels_append_types" lines_even_labels_append;
val _=show_types:=false;
fun observe label q=(print(label ^ "=");print_term(rconc(EVAL q));print "\n");
val _=observe "odd_empty_weak_not_strong" ``even_labels 3 ([Section 7 []]:8 labLang$sec list) /\ ~even_labels_strong 3 ([Section 7 []]:8 labLang$sec list)``;
val _=observe "even_empty_duplicates_strong" ``even_labels_strong 4 ([Section 7 [];Section 7 []]:8 labLang$sec list)``;
val _=observe "annotation_advances_to_even" ``lines_even_labels 3 ([Asm(Asmi(Inst Skip)) [1w;2w;3w] 1;Label 99 4 2]:8 labLang$line list)``;
val _=observe "physical_bytes_do_not_advance" ``~lines_even_labels 3 ([Asm(Asmi(Inst Skip)) [1w] 2;Label 99 4 2]:8 labLang$line list)``;
val _=observe "nonlabel_unrestricted" ``lines_even_labels 3 ([LabAsm Halt 99w [1w;2w] 7]:8 labLang$line list)``;
val _=observe "odd_section_end_weak_not_strong" ``even_labels 4 ([Section 7 [Label 999 4 1]]:8 labLang$sec list) /\ ~even_labels_strong 4 ([Section 7 [Label 999 4 1]]:8 labLang$sec list)``;
val _=observe "zero_label_still_requires_even" ``~even_labels 3 ([Section 7 [Label 999 0 0]]:8 labLang$sec list)``;
val _=observe "width1_empty_code" ``even_labels 17 ([]:1 labLang$sec list) /\ even_labels_strong 17 ([]:1 labLang$sec list)``;
val _=observe "width80_large_position" ``even_labels_strong (2**80) ([Section 9 [Label 999 5 2]]:80 labLang$sec list)``;
