load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_length_leq_def" line_length_leq_def;
val _ = types "line_length_leq_def_types" line_length_leq_def;
val _ = capture "sec_length_leq_def" sec_length_leq_def;
val _ = types "sec_length_leq_def_types" sec_length_leq_def;
val _ = capture "line_encd_def" line_encd_def;
val _ = types "line_encd_def_types" line_encd_def;
val _ = capture "lines_encd_def" lines_encd_def;
val _ = types "lines_encd_def_types" lines_encd_def;
val _ = capture "all_encd_def" all_encd_def;
val _ = types "all_encd_def_types" all_encd_def;
val _ = capture "line_encd_length_leq" line_encd_length_leq;
val _ = types "line_encd_length_leq_types" line_encd_length_leq;
val _ = capture "lines_encd_length_leq" lines_encd_length_leq;
val _ = types "lines_encd_length_leq_types" lines_encd_length_leq;
val _ = capture "all_encd_length_leq" all_encd_length_leq;
val _ = types "all_encd_length_leq_types" all_encd_length_leq;
val _ = capture "enc_lines_again_simp_encd" enc_lines_again_simp_encd;
val _ = types "enc_lines_again_simp_encd_types" enc_lines_again_simp_encd;
val _ = capture "enc_secs_again_encd" enc_secs_again_encd;
val _ = types "enc_secs_again_encd_types" enc_secs_again_encd;
val _ = temp_clear_overloads_on "all_length_leq";
val all_length_leq_term = ``(λss:'a labLang$sec list. EVERY sec_length_leq ss)``;
val _ = (print "all_length_leq="; print_term all_length_leq_term; print "\n");
val _ = (print "all_length_leq_type="; print(type_to_string(type_of all_length_leq_term)); print "\n");
val _ = temp_overload_on("all_length_leq",all_length_leq_term);
val _ = (print "line_length_leq_signature="; print(type_to_string(type_of ``line_length_leq``)); print "\n");
val _ = (print "sec_length_leq_signature="; print(type_to_string(type_of ``sec_length_leq``)); print "\n");
val _ = (print "line_encd_signature="; print(type_to_string(type_of ``line_encd``)); print "\n");
val _ = (print "lines_encd_signature="; print(type_to_string(type_of ``lines_encd``)); print "\n");
val _ = (print "all_encd_signature="; print(type_to_string(type_of ``all_encd``)); print "\n");
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val enc = ``(λa:8 asm. case a of Jump w => [w] | JumpCmp c r ri w => [7w;w] | Loc r w => [8w;w] | Call w => [9w;w] | Inst Skip => [42w] | _ => []) : 8 asm -> word8 list``;
val labs = ``insert 3 (insert 4 10 LN) LN : num num_map num_map``;
val ffis = ``[ExtCall (strlit "a");ExtCall (strlit "");ExtCall (strlit "")]``;
val _ = observe "label_any_annotation" ``line_encd ^enc ^labs ^ffis 5 (Label 7 8 999)``;
val _ = observe "asm_exact" ``line_encd ^enc ^labs ^ffis 5 (Asm (Asmi (Inst Skip)) [42w] 1)``;
val _ = observe "asm_extra_length_rejected" ``¬line_encd ^enc ^labs ^ffis 5 (Asm (Asmi (Inst Skip)) [42w] 2)``;
val _ = observe "asm_lower_bound_weaker" ``line_length_leq (Asm (Asmi (Inst Skip)) [42w] 2 : 8 labLang$line)``;
val _ = observe "halt_offset" ``line_encd ^enc ^labs ^ffis 5 (LabAsm Halt 99w [235w] 1)``;
val _ = observe "install_offset" ``line_encd ^enc ^labs ^ffis 5 (LabAsm Install 99w [219w] 1)``;
val _ = observe "ffi_first_index" ``line_encd ^enc ^labs ^ffis 5 (LabAsm (CallFFI (strlit "")) 99w [187w] 1)``;
val _ = observe "ffi_absent_default" ``line_encd ^enc ^labs [] 5 (LabAsm (CallFFI (strlit "")) 99w [203w] 1)``;
val _ = observe "jump_offset" ``line_encd ^enc ^labs ^ffis 5 (LabAsm (Jump (Lab 3 4)) 99w [5w] 1)``;
val _ = observe "cmp_offset" ``line_encd ^enc ^labs ^ffis 5 (LabAsm (JumpCmp Equal 2 (Imm 1w) (Lab 3 4)) 99w [7w;5w] 2)``;
val _ = observe "loc_offset" ``line_encd ^enc ^labs ^ffis 5 (LabAsm (LocValue 2 (Lab 3 4)) 99w [8w;5w] 2)``;
val _ = observe "call_offset" ``line_encd ^enc ^labs ^ffis 5 (LabAsm (Call (Lab 3 4)) 99w [9w;5w] 2)``;
val _ = observe "wrong_position_rejected" ``¬line_encd ^enc ^labs ^ffis 4 (LabAsm (Jump (Lab 3 4)) 99w [5w] 1)``;
val _ = observe "short_annotation_rejected" ``¬line_encd ^enc ^labs ^ffis 5 (LabAsm (Jump (Lab 3 4)) 99w [5w] 0)``;
val _ = observe "missing_label_zero" ``line_encd ^enc LN ^ffis 5 (LabAsm (Jump (Lab 3 4)) 99w [251w] 1)``;
val _ = observe "word_wrap_position" ``line_encd ^enc ^labs ^ffis 260 (LabAsm (Jump (Lab 3 4)) 99w [6w] 1)``;
val _ = observe "line_position_threading" ``lines_encd ^enc ^labs ^ffis 4 [Label 3 0 1;Asm (Asmi (Inst Skip)) [42w] 1;LabAsm (Jump (Lab 3 4)) 99w [4w] 1]``;
val _ = observe "section_position_threading" ``all_encd ^enc ^labs ^ffis 4 [Section 3 [Label 3 0 1;Asm (Asmi (Inst Skip)) [42w] 1];Section 4 [LabAsm (Jump (Lab 3 4)) 99w [4w] 1]]``;
val _ = observe "section_wrong_position_rejected" ``¬all_encd ^enc ^labs ^ffis 4 [Section 3 [Label 3 0 1;Asm (Asmi (Inst Skip)) [42w] 1];Section 4 [LabAsm (Jump (Lab 3 4)) 99w [5w] 1]]``;
val _ = observe "simple_success_full" ``enc_lines_again_simp ^labs ^ffis 0 ^enc [LabAsm (Jump (Lab 3 4)) 0w [0w] 1;Label 3 0 1] = ([LabAsm (Jump (Lab 3 4)) 10w [10w] 1;Label 3 0 1],T)``;
val _ = observe "sections_success_full" ``enc_secs_again 0 ^labs ^ffis ^enc [Section 3 [LabAsm (Jump (Lab 3 4)) 0w [0w] 1;Label 3 0 1];Section 4 [LabAsm (Jump (Lab 3 4)) 0w [0w] 1]] = ([Section 3 [LabAsm (Jump (Lab 3 4)) 10w [10w] 1;Label 3 0 1];Section 4 [LabAsm (Jump (Lab 3 4)) 8w [8w] 1]],T)``;
