load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "pos_val_0_aux" pos_val_0_aux;
val _=types "pos_val_0_aux_types" pos_val_0_aux;
val _=print("pos_val_0_aux_hypotheses="^Int.toString(length(hyp pos_val_0_aux))^"\n");
val _=capture "asm_fetch_aux_pos_val_SUC" asm_fetch_aux_pos_val_SUC;
val _=types "asm_fetch_aux_pos_val_SUC_types" asm_fetch_aux_pos_val_SUC;
val _=print("asm_fetch_aux_pos_val_SUC_hypotheses="^Int.toString(length(hyp asm_fetch_aux_pos_val_SUC))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val jumpcode = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0]]:8 sec list``;
val asmcode = ``[Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0]]:8 sec list``;
val code = ``[Section 0 [];Section 1 [Label 1 1 0;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 0 [];Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0];Section 0 []]:8 sec list``;
val jump = ``LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2:8 line``;
val asmi = ``Asm (Asmi (Inst Skip)) [0w;0w] 2:8 line``;
val bad = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 99]]:8 sec list``;
val _=observe "independent_zero" ``all_enc_ok ^cfg ^old [] 18 ^code /\ pos_val 0 101 ^code=101``;
val _=observe "first_successor" ``asm_fetch_aux 0 ^code=SOME ^jump /\ LENGTH(line_bytes ^jump)+pos_val 0 101 ^code=pos_val 1 101 ^code /\ pos_val 1 101 ^code=103``;
val _=observe "last_successor" ``asm_fetch_aux 1 ^code=SOME ^asmi /\ LENGTH(line_bytes ^asmi)+pos_val 1 101 ^code=pos_val 2 101 ^code /\ pos_val 2 101 ^code=105``;
val _=observe "missing_fetch" ``asm_fetch_aux 2 ^code=NONE``;
val _=observe "labels_only" ``all_enc_ok ^cfg ^old [] 18 [Section 9 [Label 8 7 0];Section 0 []] /\ pos_val 0 101 [Section 9 [Label 8 7 0];Section 0 []]=101``;
val _=observe "invalid_suffix" ``~all_enc_ok ^cfg ^old [] 18 ^bad /\ asm_fetch_aux 0 ^bad=SOME ^jump /\ pos_val 1 101 ^bad=104``;
val _=observe "empty_code" ``all_enc_ok ^cfg ^old [] 18 ([]:8 sec list) /\ pos_val 0 101 ([]:8 sec list)=101 /\ asm_fetch_aux 0 ([]:8 sec list)=NONE``;
