load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_aligned_def" line_aligned_def;
val _ = types "line_aligned_def_types" line_aligned_def;
val _ = capture "sec_aligned_def" sec_aligned_def;
val _ = types "sec_aligned_def_types" sec_aligned_def;
val _ = capture "all_encd0_aligned" all_encd0_aligned;
val _ = types "all_encd0_aligned_types" all_encd0_aligned;
val _ = capture "enc_lines_again_simp_aligned" enc_lines_again_simp_aligned;
val _ = types "enc_lines_again_simp_aligned_types" enc_lines_again_simp_aligned;
val _ = capture "enc_secs_again_aligned" enc_secs_again_aligned;
val _ = types "enc_secs_again_aligned_types" enc_secs_again_aligned;
val _ = capture "MOD_0_source" arithmeticTheory.MOD_0;
val _ = types "MOD_0_source_types" arithmeticTheory.MOD_0;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) [arithmeticTheory.MOD_0]) (rconc(EVAL q)))); print "\n");
val src = ``[Label 3 4 0;LabAsm (Jump (Lab 3 4)) 77w [1w;2w] 2] : 8 labLang$line list``;
val dst = ``[Label 3 4 0;LabAsm (Jump (Lab 3 4)) 0w [9w;9w;9w;9w] 4] : 8 labLang$line list``;
val _ = observe "zero_label_aligned" ``line_aligned 2 (Label 3 4 0 : 8 labLang$line)``;
val _ = observe "nonzero_label_not_aligned" ``~line_aligned 2 (Label 3 4 2 : 8 labLang$line)``;
val _ = observe "both_lengths_required" ``~line_aligned 4 (Asm (Asmi (Inst Skip)) [1w;2w] 4 : 8 labLang$line)``;
val _ = observe "annotation_required" ``~line_aligned 2 (Asm (Asmi (Inst Skip)) [1w;2w] 3 : 8 labLang$line)``;
val _ = observe "empty_section_aligned" ``sec_aligned 0 (Section 1 [] : 8 labLang$sec)``;
val _ = observe "modulus_zero_empty_line" ``line_aligned 0 (LabAsm (Jump (Lab 1 2)) 77w [] 0 : 8 labLang$line)``;
val _ = observe "modulus_zero_nonempty_rejected" ``~line_aligned 0 (Asm (Asmi (Inst Skip)) [1w;2w] 2 : 8 labLang$line)``;
val _ = observe "false_flag_full" ``enc_lines_again_simp LN [] 0 (K [9w;9w;9w;9w]) ^src = (^dst,F)``;
val _ = observe "false_flag_both_aligned" ``EVERY (line_aligned 2) ^src /\ EVERY (line_aligned 2) ^dst``;
val _ = observe "full_sections_false" ``enc_secs_again 0 LN [] (K [9w;9w;9w;9w]) [Section 3 ^src;Section 7 []] = ([Section 3 ^dst;Section 7 []],F)``;
val _ = observe "modulus_zero_actual_update" ``enc_lines_again_simp LN [] 0 (K []) ([LabAsm (Jump (Lab 1 2)) 77w [] 0] : 8 labLang$line list) = ([LabAsm (Jump (Lab 1 2)) 0w [] 0],T)``;
