load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_labs_exist_def" line_labs_exist_def;
val _ = types "line_labs_exist_def_types" line_labs_exist_def;
val _ = capture "sec_labs_exist_def" sec_labs_exist_def;
val _ = types "sec_labs_exist_def_types" sec_labs_exist_def;
val _ = capture "line_similar_line_labs_exist" line_similar_line_labs_exist;
val _ = types "line_similar_line_labs_exist_types" line_similar_line_labs_exist;
val _ = capture "code_similar_all_labs_exist" code_similar_all_labs_exist;
val _ = types "code_similar_all_labs_exist_types" code_similar_all_labs_exist;
val _ = capture "all_labs_exist_pad_code" all_labs_exist_pad_code;
val _ = types "all_labs_exist_pad_code_types" all_labs_exist_pad_code;
val _ = capture "upd_lab_len_all_labs_exist" upd_lab_len_all_labs_exist;
val _ = types "upd_lab_len_all_labs_exist_types" upd_lab_len_all_labs_exist;
val _ = capture "all_labs_exist" (REFL ``all_labs_exist``);
val _ = show_types := false;
fun observe label q = (print(label ^ "=");print_term(rconc(QCONV(SIMP_CONV(srw_ss())[sptreeTheory.lookup_insert,sptreeTheory.lookup_def]) (rconc(EVAL q))));print "\n");
val labs = ``sptree$insert 3 (sptree$insert 4 T sptree$LN) sptree$LN:bool sptree$num_map sptree$num_map``;
val c1 = ``[Section 7 [Label 1 2 9;LabAsm(Jump(Lab 3 4)) 99w [] 3];Section 8 []]:8 labLang$sec list``;
val c2 = ``[Section 7 [Label 1 2 0;LabAsm(Jump(Lab 3 4)) 1w [7w;8w] 12];Section 8 []]:8 labLang$sec list``;
val _ = observe "bool_map_jump_present" ``line_labs_exist ^labs (LabAsm(Jump(Lab 3 4)) 99w [] 3:8 labLang$line)``;
val _ = observe "missing_outer" ``~line_labs_exist ^labs (LabAsm(Jump(Lab 5 4)) 99w [] 3:8 labLang$line)``;
val _ = observe "missing_inner" ``~line_labs_exist ^labs (LabAsm(JumpCmp Equal 2 (Imm 1w) (Lab 3 5)) 99w [] 3:8 labLang$line)``;
val _ = observe "false_value_present" ``line_labs_exist (sptree$insert 3 (sptree$insert 4 F sptree$LN) sptree$LN) (LabAsm(LocValue 2 (Lab 3 4)) 99w [] 3:8 labLang$line)``;
val _ = observe "call_not_reference" ``line_labs_exist (LN:bool sptree$num_map sptree$num_map) (LabAsm(Call(Lab 99 88)) 99w [] 3:8 labLang$line)``;
val _ = observe "unconstrained_nonlabels" ``line_labs_exist ^labs (Label 1 2 99:8 labLang$line) /\ line_labs_exist ^labs (Asm(Asmi(Inst Skip)) [7w] 3:8 labLang$line)``;
val _ = observe "similar_changed_metadata" ``code_similar ^c1 ^c2 /\ all_labs_exist ^labs ^c1 /\ all_labs_exist ^labs ^c2``;
val _ = observe "padding_preserves" ``all_labs_exist ^labs (pad_code [] ^c1) /\ all_labs_exist ^labs (pad_code [7w;8w] ^c1)``;
val _ = observe "updater_preserves" ``all_labs_exist ^labs (upd_lab_len 17 ^c1)``;
val _ = observe "width1_empty" ``all_labs_exist (LN:bool sptree$num_map sptree$num_map) ([]:1 labLang$sec list)``;
