load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val t=DB.fetch "lab_to_targetProof" "make_init_def";
val _=capture "make_init_def" t;
val _=types "make_init_def_types" t;
val _=print("make_init_def_hypotheses="^Int.toString(length(hyp t))^"\n");
val _=show_types:=false;
fun checked label th=(print(label^"=");print_term(rhs(concl(EQT_INTRO th)));print"\n");
val (left,right)=dest_eq(concl(SPEC_ALL t));
val _=checked "regs" (prove(``^left.regs = ^right.regs``, simp [make_init_def]));
val _=checked "fp_regs" (prove(``^left.fp_regs = ^right.fp_regs``, simp [make_init_def]));
val _=checked "mem" (prove(``^left.mem = ^right.mem``, simp [make_init_def]));
val _=checked "mem_domain" (prove(``^left.mem_domain = ^right.mem_domain``, simp [make_init_def]));
val _=checked "shared_mem_domain" (prove(``^left.shared_mem_domain = ^right.shared_mem_domain``, simp [make_init_def]));
val _=checked "pc" (prove(``^left.pc = ^right.pc``, simp [make_init_def]));
val _=checked "be" (prove(``^left.be = ^right.be``, simp [make_init_def]));
val _=checked "ffi" (prove(``^left.ffi = ^right.ffi``, simp [make_init_def]));
val _=checked "io_regs" (prove(``^left.io_regs = ^right.io_regs``, simp [make_init_def]));
val _=checked "io_fp_regs" (prove(``^left.io_fp_regs = ^right.io_fp_regs``, simp [make_init_def]));
val _=checked "cc_regs" (prove(``^left.cc_regs = ^right.cc_regs``, simp [make_init_def]));
val _=checked "cc_fp_regs" (prove(``^left.cc_fp_regs = ^right.cc_fp_regs``, simp [make_init_def]));
val _=checked "code" (prove(``^left.code = ^right.code``, simp [make_init_def]));
val _=checked "clock" (prove(``^left.clock = ^right.clock``, simp [make_init_def]));
val _=checked "failed" (prove(``^left.failed = ^right.failed``, simp [make_init_def]));
val _=checked "ptr_reg" (prove(``^left.ptr_reg = ^right.ptr_reg``, simp [make_init_def]));
val _=checked "len_reg" (prove(``^left.len_reg = ^right.len_reg``, simp [make_init_def]));
val _=checked "ptr2_reg" (prove(``^left.ptr2_reg = ^right.ptr2_reg``, simp [make_init_def]));
val _=checked "len2_reg" (prove(``^left.len2_reg = ^right.len2_reg``, simp [make_init_def]));
val _=checked "link_reg" (prove(``^left.link_reg = ^right.link_reg``, simp [make_init_def]));
val _=checked "compile" (prove(``^left.compile = ^right.compile``, simp [make_init_def]));
val _=checked "code_buffer" (prove(``^left.code_buffer = ^right.code_buffer``, simp [make_init_def]));
val _=checked "compile_oracle" (prove(``^left.compile_oracle = ^right.compile_oracle``, simp [make_init_def]));
