load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "pad_code_compute_labels" pad_code_compute_labels;
val _=types "pad_code_compute_labels_types" pad_code_compute_labels;
val _=print "pad_code_compute_labels_hypotheses=";
val _=print(Int.toString(length(hyp pad_code_compute_labels)) ^ "\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc((SIMP_CONV (srw_ss()) [sec_label_prefix_zero_def,label_prefix_zero_cons] THENC EVAL) q)); print "\n");
val _=observe "empty_accumulator" ``compute_labels_alt 3 (pad_code [] ([]:8 sec list)) (sptree$insert 42 (sptree$insert 7 99 sptree$LN) sptree$LN) = sptree$insert 42 (sptree$insert 7 99 sptree$LN) sptree$LN``;
val _=observe "one_byte_full_map" ``compute_labels_alt 0 (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]]:8 sec list)) (sptree$insert 42 (sptree$insert 7 99 sptree$LN) sptree$LN) = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]] (sptree$insert 42 (sptree$insert 7 99 sptree$LN) sptree$LN)``;
val _=observe "wide_nop_zero_labels" ``compute_labels_alt 0 (pad_code [0w;1w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 2;Label 1 7 0]]:8 sec list)) sptree$LN = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 2;Label 1 7 0]] sptree$LN``;
val _=observe "empty_nop_zero_labels" ``compute_labels_alt 0 (pad_code [] ([Section 1 [Asm (Asmi (Inst Skip)) [] 2;Label 1 7 0]]:8 sec list)) sptree$LN = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 2;Label 1 7 0]] sptree$LN``;
val _=observe "successive_sections" ``compute_labels_alt 0 (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1];Section 2 [Label 2 9 0;Asm (Asmi (Inst Skip)) [] 1;Label 2 5 1]]:8 sec list)) sptree$LN = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1];Section 2 [Label 2 9 0;Asm (Asmi (Inst Skip)) [] 1;Label 2 5 1]] sptree$LN``;
val _=observe "duplicate_section_overwrite" ``compute_labels_alt 0 (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1];Section 1 [Asm (Asmi (Inst Skip)) [] 2;Label 1 9 0]]:8 sec list)) (sptree$insert 1 (sptree$insert 7 99 sptree$LN) sptree$LN) = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1];Section 1 [Asm (Asmi (Inst Skip)) [] 2;Label 1 9 0]] (sptree$insert 1 (sptree$insert 7 99 sptree$LN) sptree$LN)``;
val _=observe "zero_id" ``compute_labels_alt 0 (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 0 1]]:8 sec list)) sptree$LN = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 0 1]] sptree$LN``;
val _=observe "prefix_guard_needed" ``~EVERY sec_label_prefix_zero ([Section 1 [Label 1 7 1]]:8 sec list) /\ ~(compute_labels_alt 1 (pad_code [0w] ([Section 1 [Label 1 7 1]]:8 sec list)) sptree$LN = compute_labels_alt 1 [Section 1 [Label 1 7 1]] sptree$LN)``;
val _=observe "conditional_zero_guard_false" ``~EVERY sec_label_zero ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]]:8 sec list)``;
val _=observe "width1" ``compute_labels_alt 0 (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]]:1 sec list)) sptree$LN = compute_labels_alt 0 [Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]] sptree$LN``;
val _=observe "width80_large_position" ``compute_labels_alt 1208925819614629174706176 (pad_code [0w] ([Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]]:80 sec list)) (sptree$insert 42 (sptree$insert 7 1208925819614629174706177 sptree$LN) sptree$LN) = compute_labels_alt 1208925819614629174706176 [Section 1 [Asm (Asmi (Inst Skip)) [] 1;Label 1 7 1]] (sptree$insert 42 (sptree$insert 7 1208925819614629174706177 sptree$LN) sptree$LN)``;
