load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "all_enc_with_nop_pad_code" all_enc_with_nop_pad_code;
val _ = types "all_enc_with_nop_pad_code_types" all_enc_with_nop_pad_code;
val prefix_nil = prove (``label_prefix_zero []``, simp [label_prefix_zero_def]);
val _ = show_types := false;
fun observe label q = let val simplified = rconc(QCONV(SIMP_CONV(srw_ss())[sec_label_prefix_zero_def,label_prefix_zero_cons,prefix_nil]) q) in print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL simplified)))); print "\n" end;
val enc1 = ``(λa:8 asm. case a of Jump w=>[w] | JumpCmp c r i w=>[w] | Loc r w=>[w] | _=>[0w])``;
val enc2 = ``(λa:8 asm. case a of Jump w=>[w;w] | JumpCmp c r i w=>[w;w] | Loc r w=>[w;w] | _=>[0w;0w])``;
val code1 = ``[Section 0 [];Section 3 [Label 3 1 0;LabAsm (Jump(Lab 3 1)) 77w [251w] 3;Label 3 2 1;Asm (Asmi(Inst Skip)) [0w] 1];Section 4 [LabAsm Halt 88w [230w] 2;LabAsm (Call(Lab 3 1)) 99w [0w] 3];Section 5 []]:8 labLang$sec list``;
val code2 = ``[Section 0 [];Section 3 [Label 3 1 0;LabAsm (Jump(Lab 3 1)) 77w [251w;251w] 6];Section 4 [LabAsm Halt 88w [229w;229w] 4;LabAsm (Call(Lab 3 1)) 99w [0w;0w] 6];Section 5 []]:8 labLang$sec list``;
val _ = observe "singlebyte_full_guards" ``0<LENGTH(^enc1(Inst Skip)) /\ (LENGTH(^enc1(Inst Skip))<>1 ==> EVERY(sec_aligned(LENGTH(^enc1(Inst Skip)))) ^code1 /\ EVERY sec_label_zero ^code1) /\ EVERY sec_label_one ^code1 /\ all_length_leq ^code1 /\ EVERY sec_label_prefix_zero ^code1 /\ all_encd ^enc1 LN [] 5 ^code1``;
val _ = observe "singlebyte_full_encoding" ``all_enc_with_nop ^enc1 LN [] 5 (pad_code [0w] ^code1)``;
val _ = observe "singlebyte_full_tuple" ``pad_code [0w] ^code1 = [Section 0 [];Section 3 [Label 3 1 0;LabAsm (Jump(Lab 3 1)) 77w [251w;0w;0w;0w] 4;Label 3 2 0;Asm (Asmi(Inst Skip)) [0w] 1];Section 4 [LabAsm Halt 88w [230w;0w] 2;LabAsm (Call(Lab 3 1)) 99w [0w;0w;0w] 3];Section 5 []]``;
val _ = observe "singlebyte_section_lengths" ``MAP(λs.SUM(MAP line_length(Section_lines s)))(pad_code [0w] ^code1)=[0;5;5;0]``;
val _ = observe "multibyte_full_guards" ``0<LENGTH(^enc2(Inst Skip)) /\ (LENGTH(^enc2(Inst Skip))<>1 ==> EVERY(sec_aligned(LENGTH(^enc2(Inst Skip)))) ^code2 /\ EVERY sec_label_zero ^code2) /\ EVERY sec_label_one ^code2 /\ all_length_leq ^code2 /\ EVERY sec_label_prefix_zero ^code2 /\ all_encd ^enc2 LN [] 5 ^code2``;
val _ = observe "multibyte_full_encoding" ``all_enc_with_nop ^enc2 LN [] 5 (pad_code [0w;0w] ^code2)``;
val _ = observe "multibyte_full_tuple" ``pad_code [0w;0w] ^code2 = [Section 0 [];Section 3 [Label 3 1 0;LabAsm (Jump(Lab 3 1)) 77w [251w;251w;0w;0w;0w;0w] 6];Section 4 [LabAsm Halt 88w [229w;229w;0w;0w] 4;LabAsm (Call(Lab 3 1)) 99w [0w;0w;0w;0w;0w;0w] 6];Section 5 []]``;
val _ = observe "multibyte_section_lengths" ``MAP(λs.SUM(MAP line_length(Section_lines s)))(pad_code [0w;0w] ^code2)=[0;6;10;0]``;
val _ = observe "empty_code" ``all_enc_with_nop ^enc2 LN [] 17 (pad_code [0w;0w] ([]:8 labLang$sec list))``;
val _ = observe "only_empty_sections" ``all_enc_with_nop ^enc2 LN [] 17 (pad_code [0w;0w] ([Section 7 [];Section 8 []]:8 labLang$sec list))``;
