load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "get_shmem_info_MappedRead_or_MappedWrite" get_shmem_info_MappedRead_or_MappedWrite;
val _=types "get_shmem_info_MappedRead_or_MappedWrite_types" get_shmem_info_MappedRead_or_MappedWrite;
val _=print("get_shmem_info_MappedRead_or_MappedWrite_hypotheses="^Int.toString(length(hyp get_shmem_info_MappedRead_or_MappedWrite))^"\n");
val _=show_types:=false;
fun observe label q=(print(label^"=");print_term(rconc(EVAL q));print"\n");
val code=``[Section 0 [];Section 1 [Label 1 7 99;Asm (ShareMem Load8 3 (Addr 2 5w)) [] 0;Asm (Cbw 1 2) [0w;0w] 42;LabAsm (Jump(Lab 1 7)) 99w [0w] 10;Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2]]:8 sec list``;
val initial=``<|entry_pc:=100;nbytes:=3w;addr_reg:=99;addr_off:=42;reg:=77;exit_pc:=103|>``;
val names=``[SharedMem MappedWrite]``;
val result=``get_shmem_info ^code 7 ^names [^initial]``;
val _=observe "word8_names" ``FST(get_shmem_info ^code 7 [] [])=[SharedMem MappedRead;SharedMem MappedWrite]``;
val one=``[Section 1 [Label 1 7 99;Asm(ShareMem Load8 3 (Addr 2 5w))[]0;Asm(Cbw 1 2)[0w;0w]42;LabAsm(Jump(Lab 1 7))99w[0w]10;Asm(ShareMem Store8 4 (Addr 2 (-1w)))[0w;0w]2]]:1 sec list``;
val _=observe "narrow_names" ``FST(get_shmem_info ^one 7 [] [])=[SharedMem MappedRead;SharedMem MappedWrite]``;
val wide=``[Section 1 [Label 1 7 99;Asm (ShareMem Load8 3 (Addr 2 5w)) [] 0;Asm(Cbw 1 2)[0w;0w]42;LabAsm(Jump(Lab 1 7))99w[0w]10;Asm(ShareMem Store8 4 (Addr 2 (-1w)))[0w;0w]2]]:80 sec list``;
val _=observe "wide_names" ``FST(get_shmem_info ^wide 7 [] [])=[SharedMem MappedRead;SharedMem MappedWrite]``;
val _=observe "extcall_prefix" ``FST(get_shmem_info ^code 7 [ExtCall(strlit "guest")] [^initial])=[ExtCall(strlit "guest");SharedMem MappedRead;SharedMem MappedWrite]``;
val ops=``[Load;Load32;Load16;Load8;Store;Store32;Store16;Store8]``;
val allcode=``[Section 1 (MAP(λop.Asm(ShareMem op 3 (Addr 2 5w)) [] 0) ^ops)]:8 sec list``;
val _=observe "all_ops" ``FST(get_shmem_info ^allcode 7 [] [])=[SharedMem MappedRead;SharedMem MappedRead;SharedMem MappedRead;SharedMem MappedRead;SharedMem MappedWrite;SharedMem MappedWrite;SharedMem MappedWrite;SharedMem MappedWrite]``;
val _=observe "ffi_only" ``get_shmem_info ([Section 1 [LabAsm(CallFFI(strlit "guest"))99w[0w]42]]:8 sec list) 7 [] []=([],[])``;
val _=observe "empty" ``get_shmem_info ([]:8 sec list) 7 ^names [^initial]=(^names,[^initial])``;
