load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th,ACCEPT_TAC th)))));print "\n");
val th = DB.fetch "lab_to_targetProof" "find_ffi_names_filter_skip";
val _ = show_types := true;
val _ = capture "find_ffi_names_filter_skip" th;
val _ = types "find_ffi_names_filter_skip_types" th;
val _ = print("find_ffi_names_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "find_ffi_names_filter_skip_proved" th;
val th = DB.fetch "lab_to_targetProof" "MAP_Section_num_filter_skip";
val _ = show_types := true;
val _ = capture "MAP_Section_num_filter_skip" th;
val _ = types "MAP_Section_num_filter_skip_types" th;
val _ = print("MAP_Section_num_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "MAP_Section_num_filter_skip_proved" th;
val th = DB.fetch "lab_to_targetProof" "filter_skip_extract_labels";
val _ = show_types := true;
val _ = capture "filter_skip_extract_labels" th;
val _ = types "filter_skip_extract_labels_types" th;
val _ = print("filter_skip_extract_labels_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "filter_skip_extract_labels_proved" th;
val th = DB.fetch "lab_to_targetProof" "get_code_labels_filter_skip";
val _ = show_types := true;
val _ = capture "get_code_labels_filter_skip" th;
val _ = types "get_code_labels_filter_skip_types" th;
val _ = print("get_code_labels_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "get_code_labels_filter_skip_proved" th;
val th = DB.fetch "lab_to_targetProof" "get_labels_filter_skip";
val _ = show_types := true;
val _ = capture "get_labels_filter_skip" th;
val _ = types "get_labels_filter_skip_types" th;
val _ = print("get_labels_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "get_labels_filter_skip_proved" th;
(* Original local theorem is not exported: replay its unchanged source proof. *)
val th = prove (``~not_skip inst' ==> ?l n. inst' = Asm (Asmi (Inst Skip)) l n``,
  gvs[DefnBase.one_line_ify NONE lab_filterTheory.not_skip_def] >> rpt TOP_CASE_TAC);
val _ = show_types := true;
val _ = capture "not_not_skip_IMP_Skip" th;
val _ = types "not_not_skip_IMP_Skip_types" th;
val _ = print("not_not_skip_IMP_Skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "not_not_skip_IMP_Skip_proved" th;
val th = DB.fetch "lab_to_targetProof" "asm_fetch_aux_filter_skip";
val _ = show_types := true;
val _ = capture "asm_fetch_aux_filter_skip" th;
val _ = types "asm_fetch_aux_filter_skip_types" th;
val _ = print("asm_fetch_aux_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "asm_fetch_aux_filter_skip_proved" th;
val th = DB.fetch "lab_to_targetProof" "IMP_asm_fetch_aux_filter_skip";
val _ = show_types := true;
val _ = capture "IMP_asm_fetch_aux_filter_skip" th;
val _ = types "IMP_asm_fetch_aux_filter_skip_types" th;
val _ = print("IMP_asm_fetch_aux_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "IMP_asm_fetch_aux_filter_skip_proved" th;
val th = DB.fetch "lab_to_targetProof" "no_share_mem_filter_skip";
val _ = show_types := true;
val _ = capture "no_share_mem_filter_skip" th;
val _ = types "no_share_mem_filter_skip_types" th;
val _ = print("no_share_mem_filter_skip_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "no_share_mem_filter_skip_proved" th;
