load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val full = DB.fetch "lab_to_targetProof" "IMP_state_rel_make_init";
val _ = capture "IMP_state_rel_make_init" full;
val _ = types "IMP_state_rel_make_init_types" full;
val _ = print("IMP_state_rel_make_init_hypotheses=" ^ Int.toString(length(hyp full)) ^ "\n");
val guard = lhand(concl full);
val clauses = CONJUNCTS (REWRITE_RULE [state_rel_def] (UNDISCH full));
val _ = print("state_rel_conjuncts=" ^ Int.toString(length clauses) ^ "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th, ACCEPT_TAC th))))); print "\n");
val ISR2 = DISCH guard (List.nth(clauses,15));
val _ = capture "ISR2_statement" ISR2;
val _ = print("ISR2_hypotheses=" ^ Int.toString(length(hyp ISR2)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR2_proved" ISR2;
val _ = show_types := true;
val ISR3 = DISCH guard (List.nth(clauses,16));
val _ = capture "ISR3_statement" ISR3;
val _ = print("ISR3_hypotheses=" ^ Int.toString(length(hyp ISR3)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR3_proved" ISR3;
val _ = show_types := true;
val ISR8 = DISCH guard (List.nth(clauses,23));
val _ = capture "ISR8_statement" ISR8;
val _ = print("ISR8_hypotheses=" ^ Int.toString(length(hyp ISR8)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR8_proved" ISR8;
val _ = show_types := true;
val ISR15 = DISCH guard (List.nth(clauses,49));
val _ = capture "ISR15_statement" ISR15;
val _ = print("ISR15_hypotheses=" ^ Int.toString(length(hyp ISR15)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR15_proved" ISR15;
val _ = show_types := true;
