load "preamble";
load "lab_to_targetProofTheory";
open HolKernel Parse preamble lab_to_targetProofTheory;
val _ = Globals.max_print_depth := 1000;
val _ = Parse.temp_remove_user_printer ("num.numeral_computations", mk_var("n", numSyntax.num));
fun emit label th = if null(hyp th) then (print(label ^ "="); print_term(concl th); print "\n") else raise Fail(label ^ " has hypotheses");
val _ = emit "oracle_tie_clock_full" oracle_tie_clock;
val _ = show_types := true;
val _ = emit "oracle_tie_clock_types" oracle_tie_clock;
val _ = show_types := false;
val _ = emit "state_rel_clock_full" state_rel_clock;
val _ = show_types := true;
val _ = emit "state_rel_clock_types" state_rel_clock;
val _ = show_types := false;
val _ = emit "share_mem_state_rel_shift_interfer_full" share_mem_state_rel_shift_interfer;
val _ = show_types := true;
val _ = emit "share_mem_state_rel_shift_interfer_types" share_mem_state_rel_shift_interfer;
val _ = show_types := false;
val _ = emit "share_mem_domain_code_rel_shift_interfer_full" share_mem_domain_code_rel_shift_interfer;
val _ = show_types := true;
val _ = emit "share_mem_domain_code_rel_shift_interfer_types" share_mem_domain_code_rel_shift_interfer;
val _ = show_types := false;
val _ = emit "state_rel_shift_interfer_full" state_rel_shift_interfer;
val _ = show_types := true;
val _ = emit "state_rel_shift_interfer_types" state_rel_shift_interfer;
val _ = show_types := false;
val _ = OS.Process.exit OS.Process.success;
