load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val full = DB.fetch "lab_to_targetProof" "IMP_state_rel_make_init";
val _ = capture "IMP_state_rel_make_init" full;
val _ = types "IMP_state_rel_make_init_types" full;
val _ = print("IMP_state_rel_make_init_hypotheses=" ^ Int.toString(length(hyp full)) ^ "\n");
val guard = lhand(concl full);
val clauses = CONJUNCTS (REWRITE_RULE [state_rel_def] (UNDISCH full));
val _ = print("state_rel_conjuncts=" ^ Int.toString(length clauses) ^ "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th, ACCEPT_TAC th))))); print "\n");
val ISR4 = DISCH guard (List.nth(clauses,18));
val _ = capture "ISR4_statement" ISR4;
val _ = print("ISR4_hypotheses=" ^ Int.toString(length(hyp ISR4)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR4_proved" ISR4;
val _ = show_types := true;
val ISR5 = DISCH guard (List.nth(clauses,19));
val _ = capture "ISR5_statement" ISR5;
val _ = print("ISR5_hypotheses=" ^ Int.toString(length(hyp ISR5)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR5_proved" ISR5;
val _ = show_types := true;
val ISR6 = DISCH guard (List.nth(clauses,21));
val _ = capture "ISR6_statement" ISR6;
val _ = print("ISR6_hypotheses=" ^ Int.toString(length(hyp ISR6)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR6_proved" ISR6;
val _ = show_types := true;
val ISR7 = DISCH guard (List.nth(clauses,22));
val _ = capture "ISR7_statement" ISR7;
val _ = print("ISR7_hypotheses=" ^ Int.toString(length(hyp ISR7)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR7_proved" ISR7;
val _ = show_types := true;
val ISR9 = DISCH guard (List.nth(clauses,30));
val _ = capture "ISR9_statement" ISR9;
val _ = print("ISR9_hypotheses=" ^ Int.toString(length(hyp ISR9)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR9_proved" ISR9;
val _ = show_types := true;
val ISR10 = DISCH guard (List.nth(clauses,33));
val _ = capture "ISR10_statement" ISR10;
val _ = print("ISR10_hypotheses=" ^ Int.toString(length(hyp ISR10)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR10_proved" ISR10;
val _ = show_types := true;
val ISR11 = DISCH guard (List.nth(clauses,34));
val _ = capture "ISR11_statement" ISR11;
val _ = print("ISR11_hypotheses=" ^ Int.toString(length(hyp ISR11)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR11_proved" ISR11;
val _ = show_types := true;
val ISR13 = DISCH guard (List.nth(clauses,40));
val _ = capture "ISR13_statement" ISR13;
val _ = print("ISR13_hypotheses=" ^ Int.toString(length(hyp ISR13)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR13_proved" ISR13;
val _ = show_types := true;
val ISR14 = DISCH guard (List.nth(clauses,47));
val _ = capture "ISR14_statement" ISR14;
val _ = print("ISR14_hypotheses=" ^ Int.toString(length(hyp ISR14)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR14_proved" ISR14;
val _ = show_types := true;
val ISR17 = DISCH guard (List.nth(clauses,52));
val _ = capture "ISR17_statement" ISR17;
val _ = print("ISR17_hypotheses=" ^ Int.toString(length(hyp ISR17)) ^ "\n");
val _ = show_types := false;
val _ = checked "ISR17_proved" ISR17;
val _ = show_types := true;
