load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_length_ok_def" line_length_ok_def;
val _ = types "line_length_ok_def_types" line_length_ok_def;
val _ = capture "sec_length_ok_def" sec_length_ok_def;
val _ = types "sec_length_ok_def_types" sec_length_ok_def;
val _ = capture "sec_length_sum_line_length" sec_length_sum_line_length;
val _ = types "sec_length_sum_line_length_types" sec_length_sum_line_length;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = observe "zero_label_ok" ``line_length_ok (Label 1 2 0 : 8 labLang$line)``;
val _ = observe "nonzero_label_rejected" ``~line_length_ok (Label 1 2 1 : 8 labLang$line)``;
val _ = observe "asm_exact_ok" ``line_length_ok (Asm (Asmi (Inst Skip)) [1w;2w] 2 : 8 labLang$line)``;
val _ = observe "asm_mismatch_rejected" ``~line_length_ok (Asm (Asmi (Inst Skip)) [1w;2w] 3 : 8 labLang$line)``;
val _ = observe "labasm_exact_ok" ``line_length_ok (LabAsm (Jump (Lab 1 2)) 77w [1w;2w] 2 : 8 labLang$line)``;
val _ = observe "section_full_ok" ``sec_length_ok (Section 7 [Label 1 2 0;Asm (Asmi (Inst Skip)) [1w;2w] 2;LabAsm (Jump (Lab 1 2)) 77w [3w] 1] : 8 labLang$sec)``;
val _ = observe "section_sum_position" ``sec_length ([Label 1 2 0;Asm (Asmi (Inst Skip)) [1w;2w] 2;LabAsm (Jump (Lab 1 2)) 77w [3w] 1] : 8 labLang$line list) 17 = 20``;
val _ = observe "guard_required" ``sec_length ([Asm (Asmi (Inst Skip)) [1w] 3] : 8 labLang$line list) 17 <> SUM(MAP line_length ([Asm (Asmi (Inst Skip)) [1w] 3] : 8 labLang$line list)) + 17``;
