load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "mem_load32_align_dm";
val _ = show_types := true;
val _ = print "mem_load32_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "mem_load32_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("mem_load32_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "mem_load32_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "mem_load_byte_align_dm";
val _ = show_types := true;
val _ = print "mem_load_byte_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "mem_load_byte_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("mem_load_byte_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "mem_load_byte_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "mem_store32_align_dm";
val _ = show_types := true;
val _ = print "mem_store32_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "mem_store32_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("mem_store32_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "mem_store32_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "mem_store_byte_align_dm";
val _ = show_types := true;
val _ = print "mem_store_byte_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "mem_store_byte_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("mem_store_byte_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "mem_store_byte_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "mem_op_align_dm";
val _ = show_types := true;
val _ = print "mem_op_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "mem_op_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("mem_op_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "mem_op_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "asm_inst_align_dm";
val _ = show_types := true;
val _ = print "asm_inst_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "asm_inst_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("asm_inst_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "asm_inst_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
