load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "all_enc_ok_append" all_enc_ok_append;
val _=types "all_enc_ok_append_types" all_enc_ok_append;
val _=print("all_enc_ok_append_hypotheses="^Int.toString(length(hyp all_enc_ok_append))^"\n");
val _=capture "all_enc_ok_labs_mono" all_enc_ok_labs_mono;
val _=types "all_enc_ok_labs_mono_types" all_enc_ok_labs_mono;
val _=print("all_enc_ok_labs_mono_hypotheses="^Int.toString(length(hyp all_enc_ok_labs_mono))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (128w,127w); hw_offset := (128w,127w); byte_offset := (128w,127w);
 jump_offset := (128w,127w); cjump_offset := (128w,127w); loc_offset := (128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val jumpcode = ``[Section 1 [LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0]]:8 sec list``;
val asmcode = ``[Section 2 [Asm (Asmi (Inst Skip)) [0w;0w] 2;Label 2 8 0]]:8 sec list``;
val _=observe "append" ``all_enc_ok ^cfg ^old [] 18 ^jumpcode /\ all_enc_ok ^cfg ^old [] 20 ^asmcode /\ all_enc_ok ^cfg ^old [] 18 (^jumpcode++ ^asmcode)``;
val _=observe "extended" ``all_enc_ok ^cfg ^extra [] 18 ^jumpcode``;
val _=observe "dropped_lookup" ``~all_enc_ok ^cfg LN [] 18 ^jumpcode``;
val _=observe "wrong_position" ``~all_enc_ok ^cfg ^old [] 19 ^asmcode``;
val _=observe "owner_not_guard" ``all_enc_ok ^cfg ^old [] 18 [Section 1 [Label 2 7 0]]``;
val _=observe "new_and_preserved" ``lab_lookup 99 8 ^old = NONE /\ lab_lookup 99 8 ^extra = SOME 24 /\ lab_lookup 1 7 ^old = SOME 20 /\ lab_lookup 1 7 ^extra = SOME 20``;
