load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "get_shmem_info_thm" get_shmem_info_thm;
val _=types "get_shmem_info_thm_types" get_shmem_info_thm;
val _=print("get_shmem_info_thm_hypotheses="^Int.toString(length(hyp get_shmem_info_thm))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (-128w,127w); hw_offset := (-128w,127w); byte_offset := (-128w,127w);
 jump_offset := (-128w,127w); cjump_offset := (-128w,127w); loc_offset := (-128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val code=``[Section 0 [];Section 1 [Label 1 7 0;Asm (ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 2;Asm (Cbw 1 2) [0w;0w] 2;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 2 [Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2;Asm (Asmi (Inst Skip)) [0w;0w] 2];Section 0 []]:8 sec list``;
val names=``[SharedMem MappedWrite]``;
val initial=``<|entry_pc:=100;nbytes:=3w;addr_reg:=99;addr_off:=42;reg:=77;exit_pc:=103|>``;
val loadinfo=``<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=5;reg:=3;exit_pc:=9|>``;
val storeinfo=``<|entry_pc:=13;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=4;exit_pc:=15|>``;
val _=observe "independent_validity" ``all_enc_ok ^cfg ^old [] 18 ^code``;
val _=observe "full_prefix_output" ``get_shmem_info ^code 7 ^names [^initial]=(^names++[SharedMem MappedRead;SharedMem MappedWrite],[^initial;^loadinfo;^storeinfo])``;
val _=observe "full_extraction" ``get_shmem_info ^code 7 [] []=UNZIP(FLAT(MAP (line_to_info ^code 7) (GENLIST (λi.(i,asm_fetch_aux i ^code)) (num_pcs ^code))))``;
val _=observe "empty_preserves_prefixes" ``get_shmem_info ([]:8 sec list) 1000 ^names [^initial]=(^names,[^initial])``;
val _=observe "zero_labels" ``get_shmem_info ([Section 0 [];Section 1 [Label 1 2 0]]:8 sec list) 7 ^names [^initial]=(^names,[^initial])``;
val widecfg=``<|ISA:=RISC_V;encode:=(λa.[0w;0w]);big_endian:=F;code_alignment:=1;link_reg:=SOME 7;avoid_regs:=[];reg_count:=8;fp_reg_count:=4;two_reg_arith:=F;valid_imm:=(K(K T));addr_offset:=(-128w,127w);hw_offset:=(-128w,127w);byte_offset:=(-128w,127w);jump_offset:=(-128w,127w);cjump_offset:=(-128w,127w);loc_offset:=(-128w,127w)|> :80 asm_config``;
val wide=``[Section 1 [Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2]]:80 sec list``;
val _=observe "wide_unsigned" ``all_enc_ok ^widecfg ^old [] 18 ^wide /\ get_shmem_info ^wide 1000 [] []=([SharedMem MappedWrite],[<|entry_pc:=1000;nbytes:=1w;addr_reg:=2;addr_off:=1208925819614629174706175;reg:=4;exit_pc:=1002|>])``;
val bad=``[Section 1 [Label 1 7 99;Asm (ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 2]]:8 sec list``;
val _=observe "nonzero_label_guard" ``~all_enc_ok ^cfg ^old [] 18 ^bad /\ get_shmem_info ^bad 7 [] []<>UNZIP(FLAT(MAP (line_to_info ^bad 7) (GENLIST (λi.(i,asm_fetch_aux i ^bad)) (num_pcs ^bad))))``;
