load "bossLib"; load "preamble"; load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val th = DB.fetch "labProps" "arith_upd_align_dm";
val _ = show_types := true;
val _ = print "arith_upd_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "arith_upd_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("arith_upd_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "arith_upd_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "fp_upd_align_dm";
val _ = show_types := true;
val _ = print "fp_upd_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "fp_upd_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("fp_upd_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "fp_upd_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "addr_align_dm";
val _ = show_types := true;
val _ = print "addr_align_dm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "addr_align_dm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("addr_align_dm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "addr_align_dm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "arith_upd_align_sdm";
val _ = show_types := true;
val _ = print "arith_upd_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "arith_upd_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("arith_upd_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "arith_upd_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "fp_upd_align_sdm";
val _ = show_types := true;
val _ = print "fp_upd_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "fp_upd_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("fp_upd_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "fp_upd_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val th = DB.fetch "labProps" "addr_align_sdm";
val _ = show_types := true;
val _ = print "addr_align_sdm=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "addr_align_sdm_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("addr_align_sdm_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "addr_align_sdm_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
