load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "pad_section_pos_ok" pad_section_pos_ok;
val _ = types "pad_section_pos_ok_types" pad_section_pos_ok;
val _ = show_types := false;
val prefix_nil = prove(``label_prefix_zero ([]:α labLang$line list)``,simp[label_prefix_zero_def]);
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL (rconc(QCONV(REWRITE_CONV[label_prefix_zero_cons,prefix_nil]) q)))))); print "\n");
val aux = ``[Asm(Asmi(Inst Skip)) [9w] 3]:8 labLang$line list``;
val lines = ``[Label 1 2 1;Label 1 3 0;LabAsm Halt 77w [5w;6w] 3;Label 1 4 1]:8 labLang$line list``;
val result = ``[Asm(Asmi(Inst Skip)) [9w;0w] 4;Label 1 2 0;Label 1 3 0;LabAsm Halt 77w [5w;6w;0w;0w] 4;Label 1 4 0]:8 labLang$line list``;
val _ = observe "mixed_original_four_guards" ``lab_len_pos_ok (0+SUM(MAP line_len ^aux)) ^lines /\ lab_len_pos_ok 0 (REVERSE ^aux) /\ EVERY label_zero ^aux /\ ((NULL ^aux \/ is_Label(HD ^aux)) ==> label_prefix_zero ^lines)``;
val _ = observe "mixed_full_tuple" ``pad_section [0w] ^lines ^aux = ^result``;
val _ = observe "mixed_output_parity" ``lab_len_pos_ok 0 (pad_section [0w] ^lines ^aux)``;
val _ = observe "empty_nop_allowed" ``pad_section [] ^lines ^aux = [Asm(Asmi(Inst Skip)) [9w] 4;Label 1 2 0;Label 1 3 0;LabAsm Halt 77w [5w;6w] 4;Label 1 4 0] /\ lab_len_pos_ok 0 (pad_section [] ^lines ^aux)``;
val _ = observe "multibyte_nop_allowed" ``pad_section [7w;8w] ^lines ^aux = [Asm(Asmi(Inst Skip)) [9w;7w;8w] 4;Label 1 2 0;Label 1 3 0;LabAsm Halt 77w [5w;6w;7w;7w;8w] 4;Label 1 4 0] /\ lab_len_pos_ok 0 (pad_section [7w;8w] ^lines ^aux)``;
val _ = observe "empty_aux_masked_guard" ``((NULL ([]:8 labLang$line list) \/ is_Label(HD ([]:8 labLang$line list))) ==> label_prefix_zero ([Label 1 2 0]:8 labLang$line list)) /\ lab_len_pos_ok 0 (pad_section [0w] ([Label 1 2 0;Asm(Asmi(Inst Skip)) [] 3;Label 1 3 1]:8 labLang$line list) [])``;
val _ = observe "label_head_guard" ``lab_len_pos_ok 0 (pad_section [0w] ([Label 1 3 0]:8 labLang$line list) [Label 1 2 0;Asm(Asmi(Inst Skip)) [] 2])``;
val _ = observe "prefix_guard_necessary" ``lab_len_pos_ok 1 ([Label 1 2 1]:8 labLang$line list) /\ ~label_prefix_zero ([Label 1 2 1]:8 labLang$line list) /\ ~lab_len_pos_ok 1 (pad_section [0w] ([Label 1 2 1]:8 labLang$line list) [])``;
val _ = observe "input_parity_guard_necessary" ``label_prefix_zero ([Label 1 2 0]:8 labLang$line list) /\ ~lab_len_pos_ok 1 ([Label 1 2 0]:8 labLang$line list) /\ ~lab_len_pos_ok 1 (pad_section [0w] ([Label 1 2 0]:8 labLang$line list) [])``;
val _ = observe "acc_parity_guard_necessary" ``EVERY label_zero ([Label 1 2 0]:8 labLang$line list) /\ ~lab_len_pos_ok 1 (REVERSE ([Label 1 2 0]:8 labLang$line list)) /\ ~lab_len_pos_ok 1 (pad_section [0w] ([]:8 labLang$line list) [Label 1 2 0])``;
val _ = observe "empty_width1" ``pad_section [0w] ([]:1 labLang$line list) [] = [] /\ lab_len_pos_ok 17 (pad_section [0w] ([]:1 labLang$line list) [])``;
val _ = observe "large_width80" ``pad_section [7w;8w] ([LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 2 1]:80 labLang$line list) [] = [LabAsm Halt (n2w(2**70+3)) [7w;8w;7w;7w;8w] 4;Label 1 2 0] /\ lab_len_pos_ok (2**80) (pad_section [7w;8w] ([LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 2 1]:80 labLang$line list) [])``;
