load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "enc_lines_again_simp_pos_ok" enc_lines_again_simp_pos_ok;
val _ = types "enc_lines_again_simp_pos_ok_types" enc_lines_again_simp_pos_ok;
val _ = capture "enc_secs_again_pos_ok" enc_secs_again_pos_ok;
val _ = types "enc_secs_again_pos_ok_types" enc_secs_again_pos_ok;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL q)))); print "\n");
val enc = ``(\a. [7w;8w]):8 asm -> word8 list``;
val grow = ``(\a. [7w;8w;9w;10w]):8 asm -> word8 list``;
val lines = ``[Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3;LabAsm Halt 77w [9w] 3;Label 1 4 0]:8 labLang$line list``;
val result = ``[Label 1 2 1;Asm(Asmi(Inst Skip)) [] 3;LabAsm Halt (get_jump_offset Halt [] LN 5) [7w;8w] 3;Label 1 4 0]:8 labLang$line list``;
val code = ``[Section 7 ^lines;Section 8 [Label 1 9 0];Section 9 []]:8 labLang$sec list``;
val codeResult = ``[Section 7 ^result;Section 8 [Label 1 9 0];Section 9 []]:8 labLang$sec list``;
val _ = observe "changed_full_tuple" ``enc_lines_again_simp LN [] 1 ^enc ^lines = (^result,T)``;
val _ = observe "changed_parity" ``lab_len_pos_ok 1 ^lines /\ lab_len_pos_ok 1 ^result``;
val _ = observe "growth_flag_false" ``SND(enc_lines_again_simp LN [] 1 ^grow ^lines) = F``;
val _ = observe "growth_breaks_parity" ``~lab_len_pos_ok 1 (FST(enc_lines_again_simp LN [] 1 ^grow ^lines))``;
val _ = observe "unchanged_full_tuple" ``enc_lines_again_simp LN [] 1 ^enc ^result = (^result,T)``;
val _ = observe "invalid_input_not_repaired" ``enc_lines_again_simp LN [] 0 ^enc ([Label 1 2 99]:8 labLang$line list) = ([Label 1 2 99],T) /\ ~lab_len_pos_ok 0 ([Label 1 2 99]:8 labLang$line list)``;
val _ = observe "sections_full_tuple" ``enc_secs_again 1 LN [] ^enc ^code = (^codeResult,T)``;
val _ = observe "sections_parity" ``all_lab_len_pos_ok 1 ^code /\ all_lab_len_pos_ok 1 ^codeResult``;
val _ = observe "empty_list_width1" ``enc_lines_again_simp LN [] 17 ((\a. []):1 asm -> word8 list) [] = ([],T)``;
val _ = observe "empty_sections" ``enc_secs_again 17 LN [] ^enc ([Section 7 [];Section 8 []]:8 labLang$sec list) = ([Section 7 [];Section 8 []],T)``;
val _ = observe "large_width80" ``enc_lines_again_simp LN [] (2**80+1) ((\a. [7w;8w]):80 asm -> word8 list) ([Label 1 2 1;LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 4 1]:80 labLang$line list) = ([Label 1 2 1;LabAsm Halt (get_jump_offset Halt [] LN (2**80+2)) [7w;8w] 3;Label 1 4 1],T)``;
val _ = observe "large_width80_parity" ``lab_len_pos_ok (2**80+1) (FST(enc_lines_again_simp LN [] (2**80+1) ((\a. [7w;8w]):80 asm -> word8 list) ([Label 1 2 1;LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 4 1]:80 labLang$line list)))``;
