load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "enc_with_nop_pad_bytes_length" enc_with_nop_pad_bytes_length;
val _ = types "enc_with_nop_pad_bytes_length_types" enc_with_nop_pad_bytes_length;
val _ = capture "enc_with_nop_pad_bytes" enc_with_nop_pad_bytes;
val _ = types "enc_with_nop_pad_bytes_types" enc_with_nop_pad_bytes;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV (SIMP_CONV (srw_ss()) []) (rconc(EVAL q)))); print "\n");
val enc = ``(λa:8 asm. case a of Inst Skip => [9;8] | _ => [1;2])``;
val encBool = ``(λa:8 asm. case a of Inst Skip => [F;T] | _ => [T;T])``;
val encEmpty = ``(λa:8 asm. case a of Inst Skip => ([]:num list) | _ => [7])``;
val encOdd = ``(λa:8 asm. case a of Inst Skip => [9;8] | _ => [1])``;
val encZero = ``(λa:8 asm. case a of Inst Skip => [9;8] | _ => ([]:num list))``;
val _ = observe "base_multibyte" ``pad_bytes (^enc (Jump 3w)) 2 (^enc (Inst Skip)) = [1;2] /\ enc_with_nop ^enc (Jump 3w) (pad_bytes (^enc (Jump 3w)) 2 (^enc (Inst Skip)))``;
val _ = observe "base_empty_nop" ``pad_bytes (^encEmpty (Jump 3w)) 1 (^encEmpty (Inst Skip)) = [7] /\ enc_with_nop ^encEmpty (Jump 3w) (pad_bytes (^encEmpty (Jump 3w)) 1 (^encEmpty (Inst Skip)))``;
val _ = observe "generic_nat_padding" ``pad_bytes (^enc (Jump 3w)) 8 [9;8] = [1;2;9;8;9;8;9;8] /\ enc_with_nop ^enc (Jump 3w) (pad_bytes (^enc (Jump 3w)) 8 [9;8])``;
val _ = observe "generic_bool_padding" ``pad_bytes (^encBool (Jump 3w)) 6 [F;T] = [T;T;F;T;F;T] /\ enc_with_nop ^encBool (Jump 3w) (pad_bytes (^encBool (Jump 3w)) 6 [F;T])``;
val _ = observe "zero_target" ``enc_with_nop ^encZero (Jump 3w) (pad_bytes (^encZero (Jump 3w)) 0 [9;8])``;
val _ = observe "empty_initial_extended" ``pad_bytes (^encZero (Jump 3w)) 4 [9;8] = [9;8;9;8] /\ enc_with_nop ^encZero (Jump 3w) (pad_bytes (^encZero (Jump 3w)) 4 [9;8])``;
val _ = observe "target_mod_guard_required" ``~enc_with_nop ^enc (Jump 3w) (pad_bytes (^enc (Jump 3w)) 5 [9;8])``;
val _ = observe "initial_mod_guard_required" ``~enc_with_nop ^encOdd (Jump 3w) (pad_bytes (^encOdd (Jump 3w)) 4 [9;8])``;
val _ = observe "nop_identity_guard_required" ``~enc_with_nop ^enc (Jump 3w) (pad_bytes (^enc (Jump 3w)) 4 [9;7])``;
