load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "lines_offset_ok_pad_section" lines_offset_ok_pad_section;
val _ = types "lines_offset_ok_pad_section_types" lines_offset_ok_pad_section;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL q)))); print "\n");
val aux = ``[Asm(Asmi(Inst Skip)) [9w] 3]:8 labLang$line list``;
val lines = ``[Label 1 2 1;Label 1 3 0;LabAsm Halt 236w [5w;6w] 3;Label 1 4 1]:8 labLang$line list``;
val result = ``[Asm(Asmi(Inst Skip)) [9w;0w] 4;Label 1 2 0;Label 1 3 0;LabAsm Halt 236w [5w;6w;0w;0w] 4;Label 1 4 0]:8 labLang$line list``;
val _ = observe "mixed_original_five_guards" ``lab_len_pos_ok (0+SUM(MAP line_len ^aux)) ^lines /\ lab_len_pos_ok 0 (REVERSE ^aux) /\ EVERY label_zero ^aux /\ (~NULL ^lines /\ is_Label(HD ^lines) /\ line_len(HD ^lines)=1 ==> ~NULL ^aux /\ ~is_Label(HD ^aux)) /\ lines_offset_ok LN [] 0 (REVERSE ^aux++^lines)``;
val _ = observe "mixed_full_tuple" ``pad_section [0w] ^lines ^aux = ^result``;
val _ = observe "mixed_output_offsets" ``lines_offset_ok LN [] 0 (pad_section [0w] ^lines ^aux)``;
val _ = observe "empty_nop_offsets" ``pad_section [] ^lines ^aux = [Asm(Asmi(Inst Skip)) [9w] 4;Label 1 2 0;Label 1 3 0;LabAsm Halt 236w [5w;6w] 4;Label 1 4 0] /\ lines_offset_ok LN [] 0 (pad_section [] ^lines ^aux)``;
val _ = observe "multibyte_nop_offsets" ``pad_section [7w;8w] ^lines ^aux = [Asm(Asmi(Inst Skip)) [9w;7w;8w] 4;Label 1 2 0;Label 1 3 0;LabAsm Halt 236w [5w;6w;7w;7w;8w] 4;Label 1 4 0] /\ lines_offset_ok LN [] 0 (pad_section [7w;8w] ^lines ^aux)``;
val _ = observe "zero_label_head_accumulator" ``lines_offset_ok LN [] 0 (pad_section [0w] ([Label 1 3 0;LabAsm Halt 238w [] 2]:8 labLang$line list) [Label 1 2 0;Asm(Asmi(Inst Skip)) [] 2])``;
val _ = observe "empty_accumulator_mask" ``lines_offset_ok LN [] 0 (pad_section [0w] ([LabAsm Halt 240w [] 3;Label 1 2 1]:8 labLang$line list) [])``;
val _ = observe "head_guard_necessary" ``lab_len_pos_ok 1 ([Label 1 2 1;LabAsm Halt 238w [] 0]:8 labLang$line list) /\ lines_offset_ok LN [] 1 ([Label 1 2 1;LabAsm Halt 238w [] 0]:8 labLang$line list) /\ ~lines_offset_ok LN [] 1 (pad_section [0w] ([Label 1 2 1;LabAsm Halt 238w [] 0]:8 labLang$line list) [])``;
val _ = observe "input_parity_necessary" ``~lab_len_pos_ok 2 ([Label 1 2 2;LabAsm Halt 236w [] 0]:8 labLang$line list) /\ lines_offset_ok LN [] 0 ([Asm(Asmi(Inst Skip)) [] 2;Label 1 2 2;LabAsm Halt 236w [] 0]:8 labLang$line list) /\ ~lines_offset_ok LN [] 0 (pad_section [0w] ([Label 1 2 2;LabAsm Halt 236w [] 0]:8 labLang$line list) [Asm(Asmi(Inst Skip)) [] 2])``;
val _ = observe "all_seven_opcodes" ``let labs = insert 3 (insert 4 10 LN) LN in let ffis = [ExtCall(strlit "a");ExtCall(strlit "");ExtCall(strlit "")] in EVERY (\a. lines_offset_ok labs ffis 0 (pad_section [0w] [LabAsm a (get_jump_offset a ffis labs 0) [] 3;Label 1 2 1] [])) ([Jump(Lab 3 4);JumpCmp Equal 2 (Imm 1w) (Lab 3 4);LocValue 2 (Lab 3 4);Call(Lab 3 4);CallFFI(strlit "");Install;Halt]:8 asm_with_lab list)``;
val _ = observe "empty_width1" ``lines_offset_ok LN [] 17 (pad_section [0w] ([]:1 labLang$line list) [])``;
val _ = observe "large_width80" ``pad_section [7w] ([LabAsm Halt (n2w(2**80-16)) [] 3;Label 1 2 1]:80 labLang$line list) [] = [LabAsm Halt (n2w(2**80-16)) [7w;7w;7w;7w] 4;Label 1 2 0] /\ lines_offset_ok LN [] (2**80) (pad_section [7w] ([LabAsm Halt (n2w(2**80-16)) [] 3;Label 1 2 1]:80 labLang$line list) [])``;
