load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "all_lab_len_pos_ok_pad_code" all_lab_len_pos_ok_pad_code;
val _ = types "all_lab_len_pos_ok_pad_code_types" all_lab_len_pos_ok_pad_code;
val _ = show_types := false;
val prefix_nil = prove(``label_prefix_zero ([]:α labLang$line list)``,simp[label_prefix_zero_def]);
fun observe label q = (print(label ^ "="); print_term(rconc(QCONV(SIMP_CONV(srw_ss())[]) (rconc(EVAL (rconc(QCONV(SIMP_CONV(srw_ss())[sec_label_prefix_zero_def,label_prefix_zero_cons,prefix_nil]) q)))))); print "\n");
val code = ``[Section 7 [Label 1 2 0;Asm(Asmi(Inst Skip)) [] 3;Label 1 3 1];Section 8 [Label 1 4 0;LabAsm Halt 77w [] 3;Label 1 5 1];Section 9 []]:8 labLang$sec list``;
val zero = ``[Section 7 [Label 1 2 0;Asm(Asmi(Inst Skip)) [] 2;Label 1 3 0];Section 8 [Label 1 4 0;LabAsm Halt 77w [] 2;Label 1 5 0];Section 9 []]:8 labLang$sec list``;
val _ = observe "one_byte_original_four_guards" ``all_lab_len_pos_ok 0 ^code /\ (LENGTH ([0w]:word8 list)<>1 ==> EVERY sec_label_zero ^code) /\ EVERY sec_label_one ^code /\ EVERY sec_label_prefix_zero ^code``;
val _ = observe "one_byte_full_tuple" ``pad_code [0w] ^code = [Section 7 [Label 1 2 0;Asm(Asmi(Inst Skip)) [0w;0w;0w;0w] 4;Label 1 3 0];Section 8 [Label 1 4 0;LabAsm Halt 77w [0w;0w;0w;0w] 4;Label 1 5 0];Section 9 []]``;
val _ = observe "one_byte_output_parity" ``all_lab_len_pos_ok 0 (pad_code [0w] ^code)``;
val _ = observe "empty_nop_zero_guard" ``EVERY sec_label_zero ^zero /\ all_lab_len_pos_ok 0 ^zero /\ pad_code [] ^zero = ^zero /\ all_lab_len_pos_ok 0 (pad_code [] ^zero)``;
val _ = observe "multibyte_full_tuple_parity" ``pad_code [7w;8w] ^zero = [Section 7 [Label 1 2 0;Asm(Asmi(Inst Skip)) [7w;8w] 2;Label 1 3 0];Section 8 [Label 1 4 0;LabAsm Halt 77w [7w;8w] 2;Label 1 5 0];Section 9 []] /\ all_lab_len_pos_ok 0 (pad_code [7w;8w] ^zero)``;
val _ = observe "prefix_guard_necessary" ``all_lab_len_pos_ok 1 ([Section 7 [Label 1 2 1]]:8 labLang$sec list) /\ ~EVERY sec_label_prefix_zero ([Section 7 [Label 1 2 1]]:8 labLang$sec list) /\ ~all_lab_len_pos_ok 1 (pad_code [0w] ([Section 7 [Label 1 2 1]]:8 labLang$sec list))``;
val _ = observe "input_parity_guard_necessary" ``EVERY sec_label_prefix_zero ([Section 7 [Label 1 2 0]]:8 labLang$sec list) /\ ~all_lab_len_pos_ok 1 ([Section 7 [Label 1 2 0]]:8 labLang$sec list) /\ ~all_lab_len_pos_ok 1 (pad_code [0w] ([Section 7 [Label 1 2 0]]:8 labLang$sec list))``;
val _ = observe "empty_code_width1" ``all_lab_len_pos_ok 17 (pad_code [0w] ([]:1 labLang$sec list))``;
val _ = observe "empty_sections" ``pad_code [0w] ([Section 7 [];Section 8 []]:8 labLang$sec list) = [Section 7 [];Section 8 []] /\ all_lab_len_pos_ok 17 (pad_code [0w] ([Section 7 [];Section 8 []]:8 labLang$sec list))``;
val _ = observe "large_width80" ``pad_code [7w] ([Section 7 [LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 2 1];Section 8 [Label 1 3 0]]:80 labLang$sec list) = [Section 7 [LabAsm Halt (n2w(2**70+3)) [7w;7w;7w;7w] 4;Label 1 2 0];Section 8 [Label 1 3 0]] /\ all_lab_len_pos_ok (2**80) (pad_code [7w] ([Section 7 [LabAsm Halt (n2w(2**70+3)) [] 3;Label 1 2 1];Section 8 [Label 1 3 0]]:80 labLang$sec list))``;
