load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "get_shmem_info_ALL_DISTINCT" get_shmem_info_ALL_DISTINCT;
val _=types "get_shmem_info_ALL_DISTINCT_types" get_shmem_info_ALL_DISTINCT;
val _=print("get_shmem_info_ALL_DISTINCT_hypotheses="^Int.toString(length(hyp get_shmem_info_ALL_DISTINCT))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc((EVAL THENC QCONV(SIMP_CONV bool_ss [])) q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (-128w,127w); hw_offset := (-128w,127w); byte_offset := (-128w,127w);
 jump_offset := (-128w,127w); cjump_offset := (-128w,127w); loc_offset := (-128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val code=``[Section 0 [];Section 1 [Label 1 7 0;Asm (ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 2;Asm (Cbw 1 2) [0w;0w] 2;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 2 [Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2;Asm (Asmi (Inst Skip)) [0w;0w] 2];Section 0 []]:8 sec list``;
val names=``[SharedMem MappedWrite]``;
val initial=``<|entry_pc:=100;nbytes:=3w;addr_reg:=99;addr_off:=42;reg:=77;exit_pc:=103|>``;
val loadinfo=``<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=5;reg:=3;exit_pc:=9|>``;
val storeinfo=``<|entry_pc:=13;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=4;exit_pc:=15|>``;
val _=observe "full_guards" ``LENGTH(prog_to_bytes ^code)<dimword(:8) /\ enc_ok ^cfg /\ all_enc_ok ^cfg ^old [] 18 ^code``;
val _=observe "entry_values" ``MAP (λr.r.entry_pc) (SND(get_shmem_info ^code 7 [] []))=[7;13]``;
val _=observe "distinct" ``ALL_DISTINCT(MAP (λr.r.entry_pc) (SND(get_shmem_info ^code 7 [] [])))``;
val _=observe "independent_query" ``ALL_DISTINCT(MAP (λr.r.entry_pc) (SND(get_shmem_info ^code 1000 [] [])))``;
val _=observe "empty" ``ALL_DISTINCT(MAP (λr.r.entry_pc) (SND(get_shmem_info ([]:8 sec list) 7 [] [])))``;
val zero=``[Section 1 [Asm (ShareMem Load8 3 (Addr 2 5w)) [] 0;Asm (ShareMem Store8 4 (Addr 2 5w)) [] 0]]:8 sec list``;
val zerocfg=``^cfg with encode:=(λa.[])``;
val _=observe "zero_validity" ``all_enc_ok ^zerocfg ^old [] 18 ^zero``;
val _=observe "encoding_guard" ``~enc_ok ^zerocfg``;
val _=observe "zero_duplicate" ``~ALL_DISTINCT(MAP (λr.r.entry_pc) (SND(get_shmem_info ^zero 7 [] [])))``;
