load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "line_length_add_nop1" line_length_add_nop1;
val _ = types "line_length_add_nop1_types" line_length_add_nop1;
val _ = capture "line_length_add_nop" line_length_add_nop;
val _ = types "line_length_add_nop_types" line_length_add_nop;
val _ = capture "line_len_add_nop1" line_len_add_nop1;
val _ = types "line_len_add_nop1_types" line_len_add_nop1;
val _ = capture "line_len_add_nop" line_len_add_nop;
val _ = types "line_len_add_nop_types" line_len_add_nop;
val _ = capture "add_nop_append" add_nop_append;
val _ = types "add_nop_append_types" add_nop_append;
val _ = capture "EXISTS_not_Label_add_nop" EXISTS_not_Label_add_nop;
val _ = types "EXISTS_not_Label_add_nop_types" EXISTS_not_Label_add_nop;
val _ = capture "EVERY_is_Label_add_nop_preserved" EVERY_is_Label_add_nop_preserved;
val _ = types "EVERY_is_Label_add_nop_preserved_types" EVERY_is_Label_add_nop_preserved;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val mixed = ``[Label 1 2 0;Asm (Asmi (Inst Skip)) [1w] 2;LabAsm (Jump (Lab 1 2)) 77w [2w] 3;Label 1 3 99] : 8 labLang$line list``;
val _ = observe "first_nonlabel_full" ``add_nop [9w;8w] ^mixed = [Label 1 2 0;Asm (Asmi (Inst Skip)) [1w;9w;8w] 3;LabAsm (Jump (Lab 1 2)) 77w [2w] 3;Label 1 3 99]``;
val _ = observe "physical_increment_two" ``SUM(MAP line_length(add_nop [9w;8w] ^mixed)) = SUM(MAP line_length ^mixed) + 2``;
val _ = observe "annotation_increment_one" ``SUM(MAP line_len(add_nop [9w;8w] ^mixed)) = SUM(MAP line_len ^mixed) + 1``;
val _ = observe "empty_nop_annotation_changes" ``add_nop [] ^mixed = [Label 1 2 0;Asm (Asmi (Inst Skip)) [1w] 3;LabAsm (Jump (Lab 1 2)) 77w [2w] 3;Label 1 3 99]``;
val _ = observe "all_labels_unchanged" ``add_nop [9w;8w] ([Label 1 2 0;Label 1 3 99] : 8 labLang$line list) = [Label 1 2 0;Label 1 3 99]``;
val _ = observe "empty_input_unchanged" ``add_nop [9w;8w] ([] : 8 labLang$line list) = []``;
val _ = observe "first_labasm_full" ``add_nop [9w;8w] ([LabAsm (Jump (Lab 1 2)) 77w [2w] 3;Asm (Asmi (Inst Skip)) [1w] 2] : 8 labLang$line list) = [LabAsm (Jump (Lab 1 2)) 77w [2w;9w;8w] 4;Asm (Asmi (Inst Skip)) [1w] 2]``;
val _ = observe "append_labels_inserts_right" ``add_nop [9w] (([Label 1 2 0] : 8 labLang$line list) ++ [Asm (Asmi (Inst Skip)) [1w] 2]) = [Label 1 2 0;Asm (Asmi (Inst Skip)) [1w;9w] 3]``;
val _ = observe "append_nonlabel_stops_left" ``add_nop [9w] (([Asm (Asmi (Inst Skip)) [1w] 2] : 8 labLang$line list) ++ [Asm (Asmi (Inst Skip)) [2w] 3]) = [Asm (Asmi (Inst Skip)) [1w;9w] 3;Asm (Asmi (Inst Skip)) [2w] 3]``;
val _ = observe "classifiers_preserved" ``~EVERY is_Label(add_nop [9w] ^mixed) /\ EXISTS ($~ o is_Label)(add_nop [9w] ^mixed)``;
val _ = observe "nonlabel_guard_required" ``SUM(MAP line_length(add_nop [9w;8w] ([Label 1 2 0] : 8 labLang$line list))) <> SUM(MAP line_length ([Label 1 2 0] : 8 labLang$line list)) + 2``;
