load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _=capture "sec_label_ok_extract_labels" sec_label_ok_extract_labels;
val _=types "sec_label_ok_extract_labels_types" sec_label_ok_extract_labels;
val _=print "sec_label_ok_extract_labels_hypotheses=";
val _=print(Int.toString(length(hyp sec_label_ok_extract_labels)) ^ "\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _=observe "empty" ``extract_labels ([]:8 line list) = []``;
val _=observe "mixed" ``EVERY (sec_label_ok 1) ([Label 1 2 99;Asm (Asmi (Inst Skip)) [] 123;LabAsm Halt 0w [] 456;Label 1 2 0]:8 line list) /\ extract_labels [Label 1 2 99;Asm (Asmi (Inst Skip)) [] 123;LabAsm Halt 0w [] 456;Label 1 2 0] = [(1,2);(1,2)]``;
val _=observe "wrong_owner" ``~EVERY (sec_label_ok 1) ([Label 2 3 0]:8 line list)``;
val _=observe "zero_rejected" ``~EVERY (sec_label_ok 1) ([Label 1 0 0]:8 line list)``;
val _=observe "width1" ``EVERY (sec_label_ok 1208925819614629174706176) ([Label 1208925819614629174706176 2 99]:1 line list)``;
val _=observe "width80" ``EVERY (sec_label_ok 1) ([Label 1 1208925819614629174706176 99]:80 line list)``;
