load "bossLib";
load "preamble";
load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory lab_to_targetTheory labSemTheory asmTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun captureTypes label th = (print(label ^ "="); app (fn v =>
 print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))
 (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val _ = capture "extract_labels_def" extract_labels_def;
val _ = captureTypes "extract_labels_def_types" extract_labels_def;
val _ = capture "extract_labels_append" extract_labels_append;
val _ = captureTypes "extract_labels_append_types" extract_labels_append;
val _ = capture "labs_of_def" labs_of_def;
val _ = captureTypes "labs_of_def_types" labs_of_def;
val _ = capture "line_get_labels_def" line_get_labels_def;
val _ = captureTypes "line_get_labels_def_types" line_get_labels_def;
val _ = capture "sec_get_labels_def" sec_get_labels_def;
val _ = captureTypes "sec_get_labels_def_types" sec_get_labels_def;
val _ = capture "get_labels_def" get_labels_def;
val _ = captureTypes "get_labels_def_types" get_labels_def;
val _ = capture "get_labels_cons" get_labels_cons;
val _ = captureTypes "get_labels_cons_types" get_labels_cons;
val _ = capture "line_get_code_labels_def" line_get_code_labels_def;
val _ = captureTypes "line_get_code_labels_def_types" line_get_code_labels_def;
val _ = capture "sec_get_code_labels_def" sec_get_code_labels_def;
val _ = captureTypes "sec_get_code_labels_def_types" sec_get_code_labels_def;
val _ = capture "get_code_labels_def" get_code_labels_def;
val _ = captureTypes "get_code_labels_def_types" get_code_labels_def;
val _ = capture "get_code_labels_nil" get_code_labels_nil;
val _ = captureTypes "get_code_labels_nil_types" get_code_labels_nil;
val _ = capture "get_code_labels_cons" get_code_labels_cons;
val _ = captureTypes "get_code_labels_cons_types" get_code_labels_cons;
val _ = show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc((SIMP_CONV (srw_ss()) [get_labels_def, sec_get_labels_def, get_code_labels_def, sec_get_code_labels_def, line_get_labels_def, line_get_code_labels_def, labs_of_def] THENC EVAL THENC SIMP_CONV (srw_ss()) [get_labels_def, sec_get_labels_def, get_code_labels_def, sec_get_code_labels_def, line_get_labels_def, line_get_code_labels_def, labs_of_def] THENC EVAL) q)); print "\n");
val code = ``[Section 10 [Label 99 7 5; LabAsm (Jump (Lab 3 4)) 123w [] 0;
 LabAsm (Call (Lab 8 9)) 0w [] 0; Label 10 7 0]; Section 20 []] : 8 labLang$prog``;
val _ = observe "extract_empty" ``extract_labels ([]:8 line list) = []``;
val _ = observe "extract_duplicates" ``extract_labels [Label 99 7 5; LabAsm (Jump (Lab 3 4)) (123w:word8) [] 0; LabAsm (Call (Lab 8 9)) 0w [] 0; Label 10 7 0] = [(99,7);(10,7)]``;
val _ = observe "jump_ref" ``(3,4) IN labs_of (Jump (Lab 3 4):8 asm_with_lab)``;
val _ = observe "loc_ref" ``(3,4) IN labs_of (LocValue 2 (Lab 3 4):8 asm_with_lab)``;
val _ = observe "cmp_ref" ``(3,4) IN labs_of (JumpCmp Equal 2 (Imm 1w) (Lab 3 4):8 asm_with_lab)``;
val _ = observe "call_ignored" ``labs_of (Call (Lab 8 9):8 asm_with_lab) = {}``;
val _ = observe "ffi_ignored" ``labs_of (CallFFI (implode "a"):8 asm_with_lab) = {}``;
val _ = observe "install_ignored" ``labs_of (Install:8 asm_with_lab) = {}``;
val _ = observe "halt_ignored" ``labs_of (Halt:8 asm_with_lab) = {}``;
val _ = observe "label_not_ref" ``line_get_labels (Label 99 7 5:8 line) = {}``;
val _ = observe "code_reference" ``(3,4) IN get_labels ^code``;
val _ = observe "code_call_ignored" ``(8,9) NOTIN get_labels ^code``;
val _ = observe "code_label" ``(10,7) IN get_code_labels ^code``;
val _ = observe "implicit_zero" ``(10,0) IN get_code_labels ^code``;
val _ = observe "empty_section_zero" ``(20,0) IN get_code_labels ^code``;
val _ = observe "section_id_owns_label" ``(99,7) NOTIN get_code_labels ^code``;
val _ = observe "reference_empty" ``get_labels ([]:8 labLang$prog) = {}``;
val _ = observe "code_labels_empty" ``get_code_labels ([]:8 labLang$prog) = {}``;
