load "bossLib";
load "preamble";
load "labPropsTheory";
open bossLib HolKernel Parse preamble labPropsTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th,ACCEPT_TAC th)))));print "\n");
val th = DB.fetch "labProps" "reg_imm_with_clock";
val _ = show_types := true;
val _ = capture "reg_imm_with_clock" th;
val _ = types "reg_imm_with_clock_types" th;
val _ = print("reg_imm_with_clock_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "reg_imm_with_clock_proved" th;
val th = DB.fetch "labProps" "asm_inst_with_clock";
val _ = show_types := true;
val _ = capture "asm_inst_with_clock" th;
val _ = types "asm_inst_with_clock_types" th;
val _ = print("asm_inst_with_clock_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "asm_inst_with_clock_proved" th;
val th = DB.fetch "labProps" "addr_add_clock_eq";
val _ = show_types := true;
val _ = capture "addr_add_clock_eq" th;
val _ = types "addr_add_clock_eq_types" th;
val _ = print("addr_add_clock_eq_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "addr_add_clock_eq_proved" th;
val th = DB.fetch "labProps" "share_mem_op_add_clock_same";
val _ = show_types := true;
val _ = capture "share_mem_op_add_clock_same" th;
val _ = types "share_mem_op_add_clock_same_types" th;
val _ = print("share_mem_op_add_clock_same_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "share_mem_op_add_clock_same_proved" th;
