load "bossLib";
load "preamble";
load "labSemTheory";
open bossLib HolKernel Parse preamble labSemTheory;
fun print_eval label q = let val th = (SIMP_CONV (srw_ss()) [loc_to_pc_def] THENC EVAL THENC SIMP_CONV (srw_ss()) [] THENC EVAL) q in
  (print (label ^ "="); print_term (rconc th); print "\n") end;
val code = ``[Section 9 []; Section 1 [Label 1 0 91; Asm (Asmi (Inst (Const 2 (11w:8 word)))) [] 31; Label 1 5 92; LabAsm (Jump (Lab 2 0)) 0w [] 32; Label 1 7 93; Asm (Cbw 3 4) [] 33]; Section 8 []; Section 2 [Label 2 0 94; Asm (Asmi (Inst Skip)) [] 34; Label 2 4 95; LabAsm Halt 0w [] 35]] : 8 labLang$prog``;
val _ = print_eval "nav_fetch0" ``labSem$asm_fetch_aux 0 ^code = SOME (Asm (Asmi (Inst (Const 2 (11w:8 word)))) [] 31)``;
val _ = print_eval "nav_fetch1" ``labSem$asm_fetch_aux 1 ^code = SOME (LabAsm (Jump (Lab 2 0)) 0w [] 32)``;
val _ = print_eval "nav_fetch2" ``labSem$asm_fetch_aux 2 ^code = SOME (Asm (Cbw 3 4) [] 33)``;
val _ = print_eval "nav_fetch3" ``labSem$asm_fetch_aux 3 ^code = SOME (Asm (Asmi (Inst Skip)) [] 34)``;
val _ = print_eval "nav_fetch4" ``labSem$asm_fetch_aux 4 ^code = SOME (LabAsm Halt 0w [] 35)``;
val _ = print_eval "nav_fetch_end" ``labSem$asm_fetch_aux 5 ^code = NONE``;
val _ = print_eval "nav_length" ``labSem$asm_code_length ^code = 5``;
val _ = print_eval "nav_entry1" ``labSem$loc_to_pc 1 0 ^code = SOME 0``;
val _ = print_eval "nav_entry2" ``labSem$loc_to_pc 2 0 ^code = SOME 3``;
val _ = print_eval "nav_empty9" ``labSem$loc_to_pc 9 0 ^code = SOME 0``;
val _ = print_eval "nav_empty8" ``labSem$loc_to_pc 8 0 ^code = SOME 3``;
val _ = print_eval "nav_label5" ``labSem$loc_to_pc 1 5 ^code = SOME 1``;
val _ = print_eval "nav_label7" ``labSem$loc_to_pc 1 7 ^code = SOME 2``;
val _ = print_eval "nav_label4" ``labSem$loc_to_pc 2 4 ^code = SOME 4``;
val _ = print_eval "nav_missing" ``labSem$loc_to_pc 1 99 ^code = NONE``;
val _ = print_eval "nav_missingsection" ``labSem$loc_to_pc 77 0 ^code = NONE``;
val _ = print_eval "nav_return0" ``labSem$get_lab_after 0 ^code = SOME (Loc 1 5)``;
val _ = print_eval "nav_return1" ``labSem$get_lab_after 1 ^code = SOME (Loc 1 7)``;
val _ = print_eval "nav_return2" ``labSem$get_lab_after 2 ^code = SOME (Loc 2 0)``;
val _ = print_eval "nav_return3" ``labSem$get_lab_after 3 ^code = SOME (Loc 2 4)``;
val _ = print_eval "nav_return4" ``labSem$get_lab_after 4 ^code = NONE``;
val _ = print_eval "nav_return5" ``labSem$get_lab_after 5 ^code = NONE``;
val _ = print_eval "nav_first_label" ``labSem$next_label ^code = SOME (Loc 1 0)``;
