load "preamble";
load "labSemTheory";
open bossLib HolKernel Parse preamble labSemTheory asmTheory;
fun print_eval label q = (print label; print "="; print_term (rconc (EVAL q)); print "\n");
val s = ``(s : (8,unit,unit) labSem$state)``;
val _ = print_eval "lab_updates_pc_overwrite" ``(labSem$upd_pc 9 ^s).pc = 9``;
val _ = print_eval "lab_updates_pc_increment" ``(labSem$inc_pc (^s with pc := 9)).pc = 10``;
val _ = print_eval "lab_updates_clock_zero" ``(labSem$dec_clock (^s with clock := 0)).clock = 0``;
val _ = print_eval "lab_updates_clock_positive" ``(labSem$dec_clock (^s with clock := 7)).clock = 6``;
val _ = print_eval "lab_updates_reg_hit" ``(labSem$upd_reg 2 (Word 99w) (^s with regs := K (Word 17w))).regs 2 = Word 99w``;
val _ = print_eval "lab_updates_reg_other" ``(labSem$upd_reg 2 (Word 99w) (^s with regs := K (Word 17w))).regs 3 = Word 17w``;
val _ = print_eval "lab_updates_reg_loc" ``(labSem$upd_reg 2 (Loc 4 5) ^s).regs 2 = Loc 4 5``;
val _ = print_eval "lab_updates_mem_hit" ``(labSem$upd_mem 1w (Loc 4 5) (^s with mem := K (Word 17w))).mem 1w = Loc 4 5``;
val _ = print_eval "lab_updates_mem_other" ``(labSem$upd_mem 1w (Loc 4 5) (^s with mem := K (Word 17w))).mem 2w = Word 17w``;
val _ = print_eval "lab_updates_assert_sticky" ``(labSem$assert T (^s with failed := T)).failed``;
val _ = print_eval "lab_updates_assert_false" ``(labSem$assert F (^s with failed := F)).failed``;
val _ = print_eval "lab_updates_failed_reg_write" ``(labSem$assert F (labSem$upd_reg 2 (Loc 4 5) ^s)).regs 2 = Loc 4 5``;
val _ = print_eval "lab_updates_failed_mem_write" ``(labSem$assert F (labSem$upd_mem 1w (Loc 4 5) ^s)).mem 1w = Loc 4 5``;
val _ = print_eval "lab_updates_reg_imm_loc" ``labSem$reg_imm (Reg 2) (labSem$upd_reg 2 (Loc 4 5) ^s) = Loc 4 5``;
val _ = print_eval "lab_updates_reg_imm_word" ``labSem$reg_imm (Imm 255w) ^s = Word 255w``;
val _ = print_eval "lab_updates_fp_hit" ``labSem$read_fp_reg 2 (labSem$upd_fp_reg 2 0x7ff8000000000001w ^s) = 0x7ff8000000000001w``;
val _ = print_eval "lab_updates_fp_other" ``labSem$read_fp_reg 3 (labSem$upd_fp_reg 2 0x7ff8000000000001w (^s with fp_regs := K 17w)) = 17w``;
