load "bossLib";
load "preamble";
load "lprefix_lubTheory";
open bossLib HolKernel Parse preamble lprefix_lubTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
fun checked label th = (print(label ^ "="); print_term(rhs(concl(EQT_INTRO (prove(concl th,ACCEPT_TAC th)))));print "\n");
val th = DB.fetch "lprefix_lub" "prefix_chain_def";
val _ = capture "prefix_chain_def" th;
val _ = types "prefix_chain_def_types" th;
val _ = print("prefix_chain_def_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "prefix_chain_def_proved" th;
val _ = show_types := true;
val th = DB.fetch "lprefix_lub" "prefix_chain_lprefix_chain";
val _ = capture "prefix_chain_lprefix_chain" th;
val _ = types "prefix_chain_lprefix_chain_types" th;
val _ = print("prefix_chain_lprefix_chain_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "prefix_chain_lprefix_chain_proved" th;
val _ = show_types := true;
val th = DB.fetch "lprefix_lub" "prefix_chain_FILTER";
val _ = capture "prefix_chain_FILTER" th;
val _ = types "prefix_chain_FILTER_types" th;
val _ = print("prefix_chain_FILTER_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val _ = show_types := false;
val _ = checked "prefix_chain_FILTER_proved" th;
val _ = show_types := true;
