load "machine_ieeeTheory";
open HolKernel Parse boolLib machine_ieeeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
val _ = capture "fp64_to_float_def" fp64_to_float_def;
val _ = capture "float_to_fp64_def" float_to_fp64_def;
val _ = capture "fp64_abs_def" fp64_abs_def;
val _ = capture "fp64_negate_def" fp64_negate_def;
val _ = capture "fp64_lessThan_def" fp64_lessThan_def;
val _ = capture "fp64_lessEqual_def" fp64_lessEqual_def;
val _ = capture "fp64_greaterThan_def" fp64_greaterThan_def;
val _ = capture "fp64_greaterEqual_def" fp64_greaterEqual_def;
val _ = capture "fp64_equal_def" fp64_equal_def;
val _ = capture "fp64_add_def" fp64_add_def;
val _ = capture "fp64_sub_def" fp64_sub_def;
val _ = capture "fp64_mul_def" fp64_mul_def;
val _ = capture "fp64_div_def" fp64_div_def;
val _ = capture "fp64_mul_add_def" fp64_mul_add_def;
val _ = capture "fp64_to_int_def" fp64_to_int_def;
val _ = capture "real_to_fp64_def" real_to_fp64_def;
val _ = capture "int_to_fp64_def" int_to_fp64_def;
val _ = capture "fp64_isNan_def" fp64_isNan_def;
val _ = capture "fp64_isSignallingNan_def" fp64_isSignallingNan_def;
