load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val original=DB.fetch "misc" "find_index_ALL_DISTINCT_EL_eq";
val _=capture "find_index_ALL_DISTINCT_EL_eq" original;
val _=types "find_index_ALL_DISTINCT_EL_eq_types" original;
val _=print("find_index_ALL_DISTINCT_EL_eq_hypotheses="^Int.toString(length(hyp original))^"\n");
val _=show_types := false;
fun observe label q = (print(label ^ "="); print_term(rconc((EVAL THENC QCONV(SIMP_CONV bool_ss [])) q)); print "\n");
val template = ``<| ISA := RISC_V; encode := (λa.[0w]); big_endian := F; code_alignment := 0;
 link_reg := SOME 7; avoid_regs := []; reg_count := 8; fp_reg_count := 4;
 two_reg_arith := F; valid_imm := (K (K T));
 addr_offset := (-128w,127w); hw_offset := (-128w,127w); byte_offset := (-128w,127w);
 jump_offset := (-128w,127w); cjump_offset := (-128w,127w); loc_offset := (-128w,127w)
 |> : 8 asm_config``;
val cfg = ``^template with <|code_alignment:=1;encode:=(λa.[0w;0w])|>``;
val old = ``fromAList [(1,fromAList [(7,20:num)])]``;
val extra = ``insert 99 (fromAList [(8,24:num)]) ^old``;
val code=``[Section 0 [];Section 1 [Label 1 7 0;Asm (ShareMem Load8 3 (Addr 2 5w)) [0w;0w] 2;Asm (Cbw 1 2) [0w;0w] 2;LabAsm (Jump (Lab 1 7)) 99w [0w;0w] 2;Label 1 7 0];Section 2 [Asm (ShareMem Store8 4 (Addr 2 (-1w))) [0w;0w] 2;Asm (Asmi (Inst Skip)) [0w;0w] 2];Section 0 []]:8 sec list``;
val names=``[SharedMem MappedWrite]``;
val initial=``<|entry_pc:=100;nbytes:=3w;addr_reg:=99;addr_off:=42;reg:=77;exit_pc:=103|>``;
val loadinfo=``<|entry_pc:=7;nbytes:=1w;addr_reg:=2;addr_off:=5;reg:=3;exit_pc:=9|>``;
val storeinfo=``<|entry_pc:=13;nbytes:=1w;addr_reg:=2;addr_off:=255;reg:=4;exit_pc:=15|>``;
val _=observe "first" ``find_index (7:num) [7;13] 0=SOME 0``;
val _=observe "last" ``find_index (13:num) [7;13] 0=SOME 1``;
val _=observe "offset" ``find_index (13:num) [7;13] 10=SOME 11``;
val _=observe "large_offset" ``find_index (13:num) [7;13] 1208925819614629174706176=SOME 1208925819614629174706177``;
val _=observe "missing" ``find_index (8:num) [7;13] 10=NONE``;
val _=observe "duplicate_guard" ``find_index (7:num) [7;7] 0<>SOME 1 /\ ~ALL_DISTINCT [7:num;7] /\ EL 1 [7:num;7]=7``;
val _=observe "empty" ``find_index (7:num) [] 1000=NONE``;
val pcs=``MAP (λrec.rec.entry_pc) (SND(get_shmem_info ^code 7 [] []))``;
val _=observe "actual_extracted_pcs" ``^pcs=[7;13] /\ find_index (13:num) ^pcs 10=SOME 11``;
