load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val t=DB.fetch "misc" "bytes_in_mem_IMP";
val _=capture "bytes_in_mem_IMP" t;
val _=types "bytes_in_mem_IMP_types" t;
val _=print("bytes_in_mem_IMP_hypotheses="^Int.toString(length(hyp t))^"\n");
val _=show_types:=false;
fun observe label q=(print(label^"=");print_term(rconc((EVAL THENC QCONV(SIMP_CONV bool_ss [])) q));print"\n");
val _=observe "empty" ``bytes_in_mem (255w:8 word) [] (K (7w:word8)) {} UNIV /\ bytes_in_memory (255w:8 word) [] (K (7w:word8)) {}``;
val _=observe "singleton" ``bytes_in_mem (7w:8 word) [3w] (K (3w:word8)) UNIV {} /\ bytes_in_memory (7w:8 word) [3w] (K (3w:word8)) UNIV``;
val _=observe "wrap" ``bytes_in_mem (255w:8 word) [3w;3w] (K (3w:word8)) {255w;0w} {} /\ bytes_in_memory (255w:8 word) [3w;3w] (K (3w:word8)) {255w;0w}``;
val _=observe "excluded" ``~bytes_in_mem (7w:8 word) [3w] (K (3w:word8)) UNIV {7w}``;
val _=observe "missing_domain" ``~bytes_in_mem (7w:8 word) [3w] (K (3w:word8)) {} {}``;
val _=observe "wrong_value" ``~bytes_in_mem (7w:8 word) [3w] (K (4w:word8)) UNIV {}``;
val _=observe "one_bit" ``bytes_in_mem (1w:1 word) [3w;3w] (K (3w:word8)) UNIV {} /\ bytes_in_memory (1w:1 word) [3w;3w] (K (3w:word8)) UNIV``;
