load "bossLib";
load "preamble";
load "lab_to_targetProofTheory";
open bossLib HolKernel Parse preamble lab_to_targetProofTheory lab_to_targetTheory labLangTheory labPropsTheory labSemTheory sptreeTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "="); print_term(concl th); print "\n");
fun types label th = (print(label ^ "="); app (fn v => print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";")) (fst(strip_forall(concl th)) @ free_vars(concl th)); print "\n");
val t=DB.fetch "misc" "find_index_shift";
val _=capture "find_index_shift" t;
val _=types "find_index_shift_types" t;
val _=print("find_index_shift_hypotheses="^Int.toString(length(hyp t))^"\n");
val _=show_types:=false;
fun observe label q=(print(label^"=");print_term(rconc((EVAL THENC QCONV(SIMP_CONV bool_ss [])) q));print"\n");
val _=observe "first" ``find_index (7:num) [7;13] 0 = SOME 0``;
val _=observe "nonzero" ``find_index (13:num) [7;13] 10 = SOME 11``;
val _=observe "shift" ``find_index (13:num) [7;13] 99 = SOME (11-10+99)``;
val _=observe "duplicate" ``find_index (7:num) [7;7] 10 = SOME 10 /\ find_index (7:num) [7;7] 99 = SOME 99``;
val _=observe "empty" ``find_index (7:num) [] 10 = NONE``;
val _=observe "missing" ``find_index (8:num) [7;13] 10 = NONE``;
val _=observe "large" ``find_index (13:num) [7;13] (2**80) = SOME (2**80+1)``;
val _=observe "strings" ``find_index "b" ["a";"b";"b"] 10 = SOME 11 /\ find_index "b" ["a";"b";"b"] 99 = SOME 100``;
