load "bossLib";
load "preamble";
load "ml_monadBaseTheory";
open bossLib HolKernel Parse preamble ml_monadBaseTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = observe "lp_sub_empty" ``Msub (F:bool) 0 ([]:num list) = M_failure F``;
val _ = observe "lp_sub_empty_bound" ``0 >= LENGTH ([]:num list) ==> Msub (F:bool) 0 ([]:num list) = M_failure F``;
val _ = observe "lp_sub_head" ``Msub (F:bool) 0 ([2;3;5]:num list) = M_success 2``;
val _ = observe "lp_sub_middle" ``Msub (F:bool) 1 ([2;3;5]:num list) = M_success 3``;
val _ = observe "lp_sub_last" ``Msub (F:bool) 2 ([2;3;5]:num list) = M_success 5``;
val _ = observe "lp_sub_length" ``Msub (F:bool) 3 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_sub_length_bound" ``3 >= LENGTH ([2;3;5]:num list) ==> Msub (F:bool) 3 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_sub_large" ``Msub (F:bool) 18446744073709551616 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_sub_large_bound" ``18446744073709551616 >= LENGTH ([2;3;5]:num list) ==> Msub (F:bool) 18446744073709551616 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_sub_duplicate" ``Msub (F:bool) 1 ([2;2;5]:num list) = M_success 2``;
val _ = observe "lp_update_empty" ``Mupdate (F:bool) 7 0 ([]:num list) = M_failure F``;
val _ = observe "lp_update_empty_bound" ``0 >= LENGTH ([]:num list) ==> Mupdate (F:bool) 7 0 ([]:num list) = M_failure F``;
val _ = observe "lp_update_head" ``Mupdate (F:bool) 7 0 ([2;3;5]:num list) = M_success [7;3;5]``;
val _ = observe "lp_update_middle" ``Mupdate (F:bool) 7 1 ([2;3;5]:num list) = M_success [2;7;5]``;
val _ = observe "lp_update_last" ``Mupdate (F:bool) 7 2 ([2;3;5]:num list) = M_success [2;3;7]``;
val _ = observe "lp_update_length" ``Mupdate (F:bool) 7 3 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_update_length_bound" ``3 >= LENGTH ([2;3;5]:num list) ==> Mupdate (F:bool) 7 3 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_update_large" ``Mupdate (F:bool) 7 18446744073709551616 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_update_large_bound" ``18446744073709551616 >= LENGTH ([2;3;5]:num list) ==> Mupdate (F:bool) 7 18446744073709551616 ([2;3;5]:num list) = M_failure F``;
val _ = observe "lp_update_duplicate" ``Mupdate (F:bool) 7 1 ([2;2;5]:num list) = M_success [2;7;5]``;
val _ = observe "lp_bool_sub" ``Msub (13:num) 1 [T;F;T] = M_success F``;
val _ = observe "lp_bool_update" ``Mupdate (13:num) F 2 [T;F;T] = M_success [T;F;F]``;
val _ = observe "lp_bool_fail" ``Mupdate (13:num) F 3 [T;F;T] = M_failure 13``;
val _ = observe "lp_tuple_error" ``Msub ((F,7):bool#num) 2 [T] = M_failure (F,7)``;
val _ = observe "lp_tuple_value" ``Mupdate (T:bool) ((11:num),F) 1 [(2,T);(3,T)] = M_success [(2,T);(11,F)]``;
