load "namespaceTheory";
open HolKernel Parse bossLib namespaceTheory;
val _ = Globals.linewidth := 1000000;
fun pr_stmt label th = (print (label ^ "="); print_term (concl th); print "\n");
fun pr_typed label th = (print (label ^ "="); Lib.with_flag (Globals.show_types, true) print_term (concl th); print "\n");
val _ = print "id_type="; val _ = print (type_to_string ``:('n,'m) id``); val _ = print "\n";
val _ = pr_typed "id_constructors_typed" (TypeBase.case_def_of ``:('n,'m) id``);
val _ = pr_stmt "mk_id_def_statement" mk_id_def;
val _ = pr_typed "mk_id_def_typed" mk_id_def;
val _ = pr_stmt "nsLookup_def_statement" nsLookup_def;
val _ = pr_typed "nsLookup_def_typed" nsLookup_def;
val _ = pr_stmt "nsEmpty_def_statement" nsEmpty_def;
val _ = pr_typed "nsEmpty_def_typed" nsEmpty_def;
val _ = pr_stmt "nsAppend_def_statement" nsAppend_def;
val _ = pr_typed "nsAppend_def_typed" nsAppend_def;
val _ = pr_stmt "nsLift_def_statement" nsLift_def;
val _ = pr_typed "nsLift_def_typed" nsLift_def;
val _ = pr_stmt "alist_to_ns_def_statement" alist_to_ns_def;
val _ = pr_typed "alist_to_ns_def_typed" alist_to_ns_def;
val _ = pr_stmt "nsBind_def_statement" nsBind_def;
val _ = pr_typed "nsBind_def_typed" nsBind_def;
val _ = pr_stmt "nsBindList_def_statement" nsBindList_def;
val _ = pr_typed "nsBindList_def_typed" nsBindList_def;
val _ = pr_stmt "nsSing_def_statement" nsSing_def;
val _ = pr_typed "nsSing_def_typed" nsSing_def;
val _ = pr_stmt "nsMap_def_statement" nsMap_def;
val _ = pr_typed "nsMap_def_typed" nsMap_def;
