load "namespaceTheory";
open HolKernel Parse boolLib bossLib namespaceTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "id_datatype_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (TypeBase.case_def_of ``:(α,β) id``)); print "\n");
val _ = if null (hyp (mk_id_def)) then () else raise Fail "hypotheses: mk_id_def";
val _ = (print "mk_id_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (mk_id_def)); print "\n");
val _ = if null (hyp (id_to_n_def)) then () else raise Fail "hypotheses: id_to_n_def";
val _ = (print "id_to_n_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (id_to_n_def)); print "\n");
val _ = if null (hyp (id_to_mods_def)) then () else raise Fail "hypotheses: id_to_mods_def";
val _ = (print "id_to_mods_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (id_to_mods_def)); print "\n");
val _ = if null (hyp (nsLookup_def)) then () else raise Fail "hypotheses: nsLookup_def";
val _ = (print "nsLookup_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsLookup_def)); print "\n");
val _ = if null (hyp (nsLookupMod_def)) then () else raise Fail "hypotheses: nsLookupMod_def";
val _ = (print "nsLookupMod_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsLookupMod_def)); print "\n");
val _ = if null (hyp (nsEmpty_def)) then () else raise Fail "hypotheses: nsEmpty_def";
val _ = (print "nsEmpty_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsEmpty_def)); print "\n");
val _ = if null (hyp (nsAppend_def)) then () else raise Fail "hypotheses: nsAppend_def";
val _ = (print "nsAppend_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsAppend_def)); print "\n");
val _ = if null (hyp (nsLift_def)) then () else raise Fail "hypotheses: nsLift_def";
val _ = (print "nsLift_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsLift_def)); print "\n");
val _ = if null (hyp (alist_to_ns_def)) then () else raise Fail "hypotheses: alist_to_ns_def";
val _ = (print "alist_to_ns_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (alist_to_ns_def)); print "\n");
val _ = if null (hyp (nsBind_def)) then () else raise Fail "hypotheses: nsBind_def";
val _ = (print "nsBind_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsBind_def)); print "\n");
val _ = if null (hyp (nsBindList_def)) then () else raise Fail "hypotheses: nsBindList_def";
val _ = (print "nsBindList_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsBindList_def)); print "\n");
val _ = if null (hyp (nsOptBind_def)) then () else raise Fail "hypotheses: nsOptBind_def";
val _ = (print "nsOptBind_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsOptBind_def)); print "\n");
val _ = if null (hyp (nsSing_def)) then () else raise Fail "hypotheses: nsSing_def";
val _ = (print "nsSing_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsSing_def)); print "\n");
val _ = if null (hyp (nsSub_def)) then () else raise Fail "hypotheses: nsSub_def";
val _ = (print "nsSub_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsSub_def)); print "\n");
val _ = if null (hyp (nsAll_def)) then () else raise Fail "hypotheses: nsAll_def";
val _ = (print "nsAll_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsAll_def)); print "\n");
val _ = if null (hyp (nsAll2_def)) then () else raise Fail "hypotheses: nsAll2_def";
val _ = (print "nsAll2_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsAll2_def)); print "\n");
val _ = if null (hyp (nsDom_def)) then () else raise Fail "hypotheses: nsDom_def";
val _ = (print "nsDom_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsDom_def)); print "\n");
val _ = if null (hyp (nsDomMod_def)) then () else raise Fail "hypotheses: nsDomMod_def";
val _ = (print "nsDomMod_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsDomMod_def)); print "\n");
val _ = if null (hyp (nsMap_def)) then () else raise Fail "hypotheses: nsMap_def";
val _ = (print "nsMap_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (nsMap_def)); print "\n");
