load "bossLib";
load "preamble";
load "pan_to_wordProofTheory";
open bossLib HolKernel Parse preamble pan_to_wordProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
val _ = capture "get_eids_pan_simp_compile_eq" (DB.fetch "pan_to_wordProof" "get_eids_pan_simp_compile_eq");
val _ = capture "FDOM_get_eids_pan_globals_compile_eq" (DB.fetch "pan_to_wordProof" "FDOM_get_eids_pan_globals_compile_eq");
val _ = capture "lookup_first_name_compile_prog_main" (DB.fetch "pan_to_wordProof" "lookup_first_name_compile_prog_main");
val _ = capture "FLOOKUP_make_funcs_main" (DB.fetch "pan_to_wordProof" "FLOOKUP_make_funcs_main");
val _ = capture "pan_to_word_compile_shape_no_name" (DB.fetch "pan_to_wordProof" "compile_shape_no_name");
val _ = capture "size_decs_stcnames_compile_decs_structs" (DB.fetch "pan_to_wordProof" "size_decs_stcnames_compile_decs_structs");
val _ = capture "semantics_size_decs_stcnames_compile_structs" (DB.fetch "pan_to_wordProof" "semantics_size_decs_stcnames_compile_structs");
val _ = capture "size_of_eids_compile_top" (DB.fetch "pan_to_wordProof" "size_of_eids_compile_top");
