load "preamble";
load "pan_to_wordProofTheory";
open HolKernel Parse bossLib preamble pan_to_wordProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = if null (hyp (every_inst_ok_less_pan_globals_compile_exp)) then () else raise Fail "hypotheses: every_inst_ok_less_pan_globals_compile_exp";
val _ = (print "every_inst_ok_less_pan_globals_compile_exp_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_pan_globals_compile_exp)); print "\n");
val _ = if null (hyp (every_inst_ok_less_shape_val)) then () else raise Fail "hypotheses: every_inst_ok_less_shape_val";
val _ = (print "every_inst_ok_less_shape_val_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_shape_val)); print "\n");
val _ = if null (hyp (every_inst_ok_less_pan_globals_compile)) then () else raise Fail "hypotheses: every_inst_ok_less_pan_globals_compile";
val _ = (print "every_inst_ok_less_pan_globals_compile_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_pan_globals_compile)); print "\n");
val _ = if null (hyp (every_inst_ok_less_pan_globals_compile_decs)) then () else raise Fail "hypotheses: every_inst_ok_less_pan_globals_compile_decs";
val _ = (print "every_inst_ok_less_pan_globals_compile_decs_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_pan_globals_compile_decs)); print "\n");
val _ = if null (hyp (every_inst_ok_less_pan_globals_compile_decs_init)) then () else raise Fail "hypotheses: every_inst_ok_less_pan_globals_compile_decs_init";
val _ = (print "every_inst_ok_less_pan_globals_compile_decs_init_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_pan_globals_compile_decs_init)); print "\n");
val _ = if null (hyp (every_inst_ok_less_fperm)) then () else raise Fail "hypotheses: every_inst_ok_less_fperm";
val _ = (print "every_inst_ok_less_fperm_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_fperm)); print "\n");
val _ = if null (hyp (every_inst_ok_less_fperm_decs)) then () else raise Fail "hypotheses: every_inst_ok_less_fperm_decs";
val _ = (print "every_inst_ok_less_fperm_decs_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_fperm_decs)); print "\n");
val _ = if null (hyp (every_inst_ok_less_pan_globals_compile_top)) then () else raise Fail "hypotheses: every_inst_ok_less_pan_globals_compile_top";
val _ = (print "every_inst_ok_less_pan_globals_compile_top_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (every_inst_ok_less_pan_globals_compile_top)); print "\n");
