load "bossLib";
load "preamble";
load "pan_structsProofTheory";
open bossLib HolKernel Parse preamble pan_structsProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
val _ = capture "compile_shape_n_def" (DB.fetch "pan_structsProof" "compile_shape_n_def");
val _ = capture "compile_shape_n_no_name" (DB.fetch "pan_structsProof" "compile_shape_n_no_name");
val _ = capture "compile_shape_n_eq" (DB.fetch "pan_structsProof" "compile_shape_n_eq");
val _ = capture "compile_shape_no_name" (DB.fetch "pan_structsProof" "compile_shape_no_name");
val _ = capture "size_of_compile_shape" (DB.fetch "pan_structsProof" "size_of_compile_shape");
val _ = capture "compile_top_no_names" (DB.fetch "pan_structsProof" "compile_top_no_names");
val _ = capture "decs_stcnames_to_get_names" (DB.fetch "pan_structsProof" "decs_stcnames_to_get_names");
val _ = types "decs_stcnames_to_get_names_types" (DB.fetch "pan_structsProof" "decs_stcnames_to_get_names");
val _ = capture "decs_stcnames_infos_ok" (DB.fetch "pan_structsProof" "decs_stcnames_infos_ok");
val _ = types "decs_stcnames_infos_ok_types" (DB.fetch "pan_structsProof" "decs_stcnames_infos_ok");
val _ = capture "size_of_shape_compile_pass_eq" (DB.fetch "pan_structsProof" "size_of_shape_compile_pass_eq");
val _ = types "size_of_shape_compile_pass_eq_types" (DB.fetch "pan_structsProof" "size_of_shape_compile_pass_eq");
