load "bossLib";
load "preamble";
load "pan_simpProofTheory";
open bossLib HolKernel Parse preamble pan_simpProofTheory;
val _ = show_types := true;
fun capture label th = (print(label ^ "=");print_term(concl th);print "\n");
fun types label th = (print(label ^ "=");app(fn v=>print(term_to_string v ^ ":" ^ type_to_string(type_of v) ^ ";"))(fst(strip_forall(concl th)) @ free_vars(concl th));print "\n");
val th = DB.fetch "pan_simpProof" "compile_correct";
val _ = capture "compile_correct" th;
val _ = types "compile_correct_types" th;
val _ = print("compile_correct_hypotheses=" ^ Int.toString(length(hyp th)) ^ "\n");
val th = DB.fetch "pan_simpProof" "state_rel_def";
val _ = capture "state_rel_def" th;
val _ = types "state_rel_def_types" th;
val th = DB.fetch "pan_simpProof" "state_rel_imp_semantics";
val _ = capture "state_rel_imp_semantics" th;
val _ = types "state_rel_imp_semantics_types" th;
val th = DB.fetch "pan_simpProof" "state_rel_imp_evaluate_decls";
val _ = capture "state_rel_imp_evaluate_decls" th;
val _ = types "state_rel_imp_evaluate_decls_types" th;
val th = DB.fetch "pan_simpProof" "state_rel_imp_semantics_decls";
val _ = capture "state_rel_imp_semantics_decls" th;
val _ = types "state_rel_imp_semantics_decls_types" th;
