load "bossLib";
load "preamble";
load "parmoveTheory";
open bossLib HolKernel Parse preamble parmoveTheory;
fun print_eval label q = let val th = EVAL q in
 (print (label ^ "="); print_term (rconc th); print "\n") end;
val env = ``\x:num option. case x of NONE => 99n | SOME k => 10*k+7``;
print_eval "pv_head_history_pre_1" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 1)``;
print_eval "pv_head_history_pre_2" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 2)``;
print_eval "pv_head_history_pre_3" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 3)``;
print_eval "pv_head_history_pre_4" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 4)``;
print_eval "pv_head_history_pre_5" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 5)``;
print_eval "pv_head_history_post_1" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 1)``;
print_eval "pv_head_history_post_2" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 2)``;
print_eval "pv_head_history_post_3" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 3)``;
print_eval "pv_head_history_post_4" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 4)``;
print_eval "pv_head_history_post_5" ``parmove$sem ([(SOME 4,SOME 2);(SOME 5,SOME 4)],[(SOME 2,SOME 3);(SOME 3,SOME 6)],[(SOME 1,SOME 2);(SOME 2,SOME 3);(SOME 3,SOME 6)]) ^env (SOME 5)``;
print_eval "pv_head_none_pre_1" ``parmove$sem ([(SOME 4,SOME 2)],[(SOME 1,SOME 2);(SOME 2,NONE)],[]) ^env (SOME 1)``;
print_eval "pv_head_none_pre_2" ``parmove$sem ([(SOME 4,SOME 2)],[(SOME 1,SOME 2);(SOME 2,NONE)],[]) ^env (SOME 2)``;
print_eval "pv_head_none_pre_4" ``parmove$sem ([(SOME 4,SOME 2)],[(SOME 1,SOME 2);(SOME 2,NONE)],[]) ^env (SOME 4)``;
print_eval "pv_head_none_post_1" ``parmove$sem ([(SOME 4,SOME 2)],[(SOME 2,NONE)],[(SOME 1,SOME 2)]) ^env (SOME 1)``;
print_eval "pv_head_none_post_2" ``parmove$sem ([(SOME 4,SOME 2)],[(SOME 2,NONE)],[(SOME 1,SOME 2)]) ^env (SOME 2)``;
print_eval "pv_head_none_post_4" ``parmove$sem ([(SOME 4,SOME 2)],[(SOME 2,NONE)],[(SOME 1,SOME 2)]) ^env (SOME 4)``;
print_eval "pv_head_bad_endpoint_pre_1" ``parmove$sem ([],[(SOME 1,SOME 2);(SOME 2,SOME 1)],[]) ^env (SOME 1)``;
print_eval "pv_head_bad_endpoint_pre_2" ``parmove$sem ([],[(SOME 1,SOME 2);(SOME 2,SOME 1)],[]) ^env (SOME 2)``;
print_eval "pv_head_bad_endpoint_post_1" ``parmove$sem ([],[(SOME 2,SOME 1)],[(SOME 1,SOME 2)]) ^env (SOME 1)``;
print_eval "pv_head_bad_endpoint_post_2" ``parmove$sem ([],[(SOME 2,SOME 1)],[(SOME 1,SOME 2)]) ^env (SOME 2)``;
print_eval "pv_head_bad_pending_pre_1" ``parmove$sem ([(SOME 4,SOME 1)],[(SOME 1,SOME 2);(SOME 2,SOME 3)],[]) ^env (SOME 1)``;
print_eval "pv_head_bad_pending_pre_2" ``parmove$sem ([(SOME 4,SOME 1)],[(SOME 1,SOME 2);(SOME 2,SOME 3)],[]) ^env (SOME 2)``;
print_eval "pv_head_bad_pending_pre_4" ``parmove$sem ([(SOME 4,SOME 1)],[(SOME 1,SOME 2);(SOME 2,SOME 3)],[]) ^env (SOME 4)``;
print_eval "pv_head_bad_pending_post_1" ``parmove$sem ([(SOME 4,SOME 1)],[(SOME 2,SOME 3)],[(SOME 1,SOME 2)]) ^env (SOME 1)``;
print_eval "pv_head_bad_pending_post_2" ``parmove$sem ([(SOME 4,SOME 1)],[(SOME 2,SOME 3)],[(SOME 1,SOME 2)]) ^env (SOME 2)``;
print_eval "pv_head_bad_pending_post_4" ``parmove$sem ([(SOME 4,SOME 1)],[(SOME 2,SOME 3)],[(SOME 1,SOME 2)]) ^env (SOME 4)``;
