load "bossLib";
load "preamble";
load "reg_allocProofTheory";
open bossLib HolKernel Parse preamble reg_allocTheory reg_allocProofTheory;
fun observe label term = let val th = (SIMP_CONV (srw_ss()) [in_clash_tree_def, domain_lookup] THENC EVAL) term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
fun observe_eval label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = observe "ict_delta_write" ``in_clash_tree (Delta [1;2] [3]) 2``;
val _ = observe "ict_delta_read" ``in_clash_tree (Delta [1;2] [3]) 3``;
val _ = observe "ict_delta_miss" ``in_clash_tree (Delta [1;2] [3]) 4``;
val _ = observe "ict_set" ``in_clash_tree (Set (insert 5 () LN)) 5``;
val _ = observe "ict_set_miss" ``in_clash_tree (Set (insert 5 () LN)) 6``;
val _ = observe "ict_set_raw" ``in_clash_tree (Set (BS LN () LN)) 0``;
val _ = observe "ict_branch_left" ``in_clash_tree (Branch NONE (Delta [1] []) (Delta [2] [])) 1``;
val _ = observe "ict_branch_right" ``in_clash_tree (Branch NONE (Delta [1] []) (Delta [2] [])) 2``;
val _ = observe "ict_branch_none_miss" ``in_clash_tree (Branch NONE (Delta [1] []) (Delta [2] [])) 9``;
val _ = observe "ict_branch_some" ``in_clash_tree (Branch (SOME (insert 9 () LN)) (Delta [1] []) (Delta [2] [])) 9``;
val _ = observe "ict_branch_some_miss" ``in_clash_tree (Branch (SOME (insert 9 () LN)) (Delta [1] []) (Delta [2] [])) 8``;
val _ = observe "ict_seq_left" ``in_clash_tree (Seq (Delta [1] []) (Set (insert 4 () LN))) 1``;
val _ = observe "ict_seq_right" ``in_clash_tree (Seq (Delta [1] []) (Set (insert 4 () LN))) 4``;
val _ = observe "ict_large" ``in_clash_tree (Delta [36893488147419103232] []) 36893488147419103232``;
val _ = observe_eval "cct_ok_f" ``OPTION_MAP (\(a,b). (toAList a, toAList b)) (check_clash_tree (\x. x + 1) (Seq (Delta [1] [2]) (Set (insert 2 () LN))) LN LN)``;
val _ = observe_eval "cct_ok_gf" ``OPTION_MAP (\(a,b). (toAList a, toAList b)) (check_clash_tree ((\x. 2 * x) o (\x. x + 1)) (Seq (Delta [1] [2]) (Set (insert 2 () LN))) LN LN)``;
val _ = observe_eval "cct_collision_f" ``OPTION_MAP (\(a,b). (toAList a, toAList b)) (check_clash_tree (\x. 0) (Delta [] [1;2]) LN LN)``;
val _ = observe_eval "cct_collision_gf" ``OPTION_MAP (\(a,b). (toAList a, toAList b)) (check_clash_tree ((\x. 2 * x) o (\x. 0)) (Delta [] [1;2]) LN LN)``;
