load "bossLib";
load "preamble";
load "reg_allocTheory";
open bossLib HolKernel Parse preamble reg_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
fun observe_type label ty = (print (label ^ "="); print_type ty; print "\n");
observe_type "sp_type" (type_of ``reg_alloc$st_ex_PARTITION``);
observe "sp_empty" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [] [90] [80;81] 42 = (M_success ([90],[80;81]),42)``;
observe "sp_singleton_true" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [2] [90] [80] 5 = (M_success ([2;90],[80]),52)``;
observe "sp_singleton_false" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [3] [90] [80] 5 = (M_success ([90],[3;80]),53)``;
observe "sp_all_true" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [2;4;6] [] [] 0 = (M_success ([6;4;2],[]),246)``;
observe "sp_all_false" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [1;3;5] [] [] 0 = (M_success ([],[5;3;1]),135)``;
observe "sp_mixed" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [1;2;3;4] [90;91] [80] 0 = (M_success ([4;2;90;91],[3;1;80]),1234)``;
observe "sp_reverse" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [4;3;2;1] [] [] 0 = (M_success ([2;4],[1;3]),4321)``;
observe "sp_duplicates" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [2;2;3] [2] [3] 0 = (M_success ([2;2;2],[3;3]),223)``;
observe "sp_large" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [18446744073709551616;3] [] [] 0 = (M_success ([18446744073709551616],[3]),184467440737095516163)``;
observe "sp_fail_empty" ``st_ex_PARTITION (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [] [90] [80] 5 = (M_success ([90],[80]),5)``;
observe "sp_fail_first" ``st_ex_PARTITION (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [0;2;3] [90] [80] 5 = (M_failure 17,12)``;
observe "sp_fail_middle" ``st_ex_PARTITION (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [2;0;3] [90] [80] 5 = (M_failure 17,14)``;
observe "sp_fail_last" ``st_ex_PARTITION (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [2;3;0] [90] [80] 5 = (M_failure 17,17)``;
observe "sp_fail_duplicate" ``st_ex_PARTITION (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [2;2;0;9] [90] [80] 5 = (M_failure 17,16)``;
observe "sp_state_predicate" ``st_ex_PARTITION (\(x:num) (s:num). ((M_success (s MOD 2=0)):(bool,bool)exc,s+1)) [10;20;30;40] [] [] 0 = (M_success ([30;10],[40;20]),4)``;
observe "sp_state_failure" ``st_ex_PARTITION (\(x:num) (s:num). if s>=10 then ((M_failure s):(bool,num)exc,s+100) else (M_success (x MOD 2=0),s+x)) [2;3;5;7] [] [] 0 = (M_failure 10,110)``;
observe "sp_bool_value" ``st_ex_PARTITION (\(x:bool) (s:num). ((M_success (~x)):(bool,bool)exc,s+1)) [T;F;T;F] [T] [F] 5 = (M_success ([F;F;T],[T;T;F]),9)``;
observe "sp_bool_state" ``st_ex_PARTITION (\(x:num) (s:bool). ((M_success s):(bool,num)exc,~s)) [2;3;5] [] [] T = (M_success ([5;2],[3]),F)``;
observe "sp_list_state" ``st_ex_PARTITION (\(x:num) (s:num list). ((M_success (x MOD 2=0)):(bool,num list)exc,s++[x])) [2;3;5] [] [] [99] = (M_success ([2],[5;3]),[99;2;3;5])``;
observe "sp_list_error" ``st_ex_PARTITION (\(x:num) (s:num list). if x=0 then ((M_failure [7;11]):(bool,num list)exc,s++[x]) else (M_success (x MOD 2=0),s++[x])) [2;0;5] [] [] [99] = (M_failure [7;11],[99;2;0])``;
observe "sp_tuple_state" ``st_ex_PARTITION (\(x:bool) (a:num,b:bool). ((M_success (x /\ b)):(bool,bool)exc,(a+2,~b))) [T;F;T] [] [] (5,T) = (M_success ([T;T],[F]),(11,F))``;
observe "sp_empty_always_failure" ``st_ex_PARTITION (\(x:bool) (s:num). ((M_failure x):(bool,bool)exc,s+100)) [] [T] [F] 7 = (M_success ([T],[F]),7)``;
