load "bossLib";
load "preamble";
load "reg_allocTheory";
open bossLib HolKernel Parse preamble reg_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val s0 = ``<| adj_ls := [[1];[0]]; node_tag := [Fixed 0; Atemp]; degrees := [1;1]; dim := 2;
  simp_wl := []; spill_wl := []; freeze_wl := []; avail_moves_wl := []; unavail_moves_wl := [];
  coalesced := [0;1]; move_related := [F;F]; stack := [] |>``;
fun s t = subst [``S0:ra_state`` |-> s0] t;
val _ = observe "ef_raise_fail" (s ``(raise_Fail "x" (S0:ra_state) : (num, state_exn) exc # ra_state) = (M_failure (Fail "x"), S0)``);
val _ = observe "ef_raise_sub" (s ``(raise_Subscript (S0:ra_state) : (num, state_exn) exc # ra_state) = (M_failure Subscript, S0)``);
val _ = observe "ef_hs_success" (s ``FST (handle_Subscript (\s. (M_success (5:num), s)) (\s. (M_success 9, s)) (S0:ra_state))``);
val _ = observe "ef_hs_catch" (s ``FST (handle_Subscript raise_Subscript (\s. (M_success (9:num), s)) (S0:ra_state))``);
val _ = observe "ef_hs_pass_fail" (s ``FST (handle_Subscript (raise_Fail "x") (\s. (M_success (9:num), s)) (S0:ra_state))``);
val _ = observe "ef_hs_failing_state" (s ``FST (handle_Subscript (\s. (M_failure Subscript, s with dim := 7)) (\s. (M_success s.dim, s)) (S0:ra_state))``);
val _ = observe "ef_hs_accessor" (s ``FST (handle_Subscript (node_tag_sub 9) (\s. (M_success Atemp, s)) (S0:ra_state))``);
val _ = observe "ef_hf_catch" (s ``FST (handle_Fail (raise_Fail "ab") (\e s. (M_success (LENGTH e), s)) (S0:ra_state))``);
val _ = observe "ef_hf_pass_sub" (s ``FST (handle_Fail raise_Subscript (\e s. (M_success (0:num), s)) (S0:ra_state))``);
val _ = observe "ef_hf_success" (s ``FST (handle_Fail (\s. (M_success (4:num), s)) (\e s. (M_success 0, s)) (S0:ra_state))``);
val _ = observe "ef_hf_failing_state" (s ``FST (handle_Fail (\s. (M_failure (Fail "q"), s with dim := 5)) (\e s. (M_success (s.dim + LENGTH e), s)) (S0:ra_state))``);
