load "bossLib";
load "preamble";
load "reg_allocTheory";
open bossLib HolKernel Parse preamble reg_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = print ("sm_type=" ^ type_to_string (type_of ``reg_alloc$st_ex_MAP``) ^ "\n");
val _ = observe "sm_bool_state" ``st_ex_MAP (\(x:num) (s:bool). ((M_success (x+1)):(num,num)exc,~s)) [2;3] T = (M_success [3;4],T)``;
val _ = observe "sm_num_state" ``st_ex_MAP (\(x:bool) (s:num). ((M_success (~x)):(bool,bool)exc,s+1)) [T;F] 5 = (M_success [F;T],7)``;
val _ = observe "sm_empty" ``st_ex_MAP (\(x:num) (s:num). ((M_success (s*10+x)):(num,bool)exc,s*10+x)) [] 42 = (M_success [],42)``;
val _ = observe "sm_one" ``st_ex_MAP (\(x:num) (s:num). ((M_success (s*10+x)):(num,bool)exc,s*10+x)) [2] 5 = (M_success [52],52)``;
val _ = observe "sm_order" ``st_ex_MAP (\(x:num) (s:num). ((M_success (s*10+x)):(num,bool)exc,s*10+x)) [2;3;5] 0 = (M_success [2;23;235],235)``;
val _ = observe "sm_reverse" ``st_ex_MAP (\(x:num) (s:num). ((M_success (s*10+x)):(num,bool)exc,s*10+x)) [5;3;2] 0 = (M_success [5;53;532],532)``;
val _ = observe "sm_duplicates" ``st_ex_MAP (\(x:num) (s:num). ((M_success (s*10+x)):(num,bool)exc,s*10+x)) [2;2;3] 0 = (M_success [2;22;223],223)``;
val _ = observe "sm_large" ``st_ex_MAP (\(x:num) (s:num). ((M_success (s*10+x)):(num,bool)exc,s*10+x)) [18446744073709551616;3] 0 = (M_success [18446744073709551616;184467440737095516163],184467440737095516163)``;
val _ = observe "sm_fail_empty" ``st_ex_MAP (\(x:num) (s:num). if x=0 then ((M_failure 17):(num,num)exc,s+7) else (M_success x,s+x)) [] 5 = (M_success [],5)``;
val _ = observe "sm_fail_first" ``st_ex_MAP (\(x:num) (s:num). if x=0 then ((M_failure 17):(num,num)exc,s+7) else (M_success x,s+x)) [0;2;3] 5 = (M_failure 17,12)``;
val _ = observe "sm_fail_middle" ``st_ex_MAP (\(x:num) (s:num). if x=0 then ((M_failure 17):(num,num)exc,s+7) else (M_success x,s+x)) [2;0;3] 5 = (M_failure 17,14)``;
val _ = observe "sm_fail_last" ``st_ex_MAP (\(x:num) (s:num). if x=0 then ((M_failure 17):(num,num)exc,s+7) else (M_success x,s+x)) [2;3;0] 5 = (M_failure 17,17)``;
val _ = observe "sm_fail_duplicates" ``st_ex_MAP (\(x:num) (s:num). if x=0 then ((M_failure 17):(num,num)exc,s+7) else (M_success x,s+x)) [2;2;0;9] 5 = (M_failure 17,16)``;
val _ = observe "sm_success" ``st_ex_MAP (\(x:num) (s:num). if x=0 then ((M_failure 17):(num,num)exc,s+7) else (M_success x,s+x)) [2;3;5] 5 = (M_success [2;3;5],15)``;
val _ = observe "sm_state_failure" ``st_ex_MAP (\(x:num) (s:num). if s>=10 then ((M_failure s):(bool,num)exc,s+100) else (M_success (x MOD 2=0),s+x)) [2;3;5;7] 0 = (M_failure 10,110)``;
val _ = observe "sm_list_state" ``st_ex_MAP (\(x:num) (s:num list). ((M_success (x MOD 2=0)):(bool,num list)exc,s++[x])) [2;3;5] [99] = (M_success [T;F;F],[99;2;3;5])``;
val _ = observe "sm_list_error" ``st_ex_MAP (\(x:num) (s:num list). if x=0 then ((M_failure [7;11]):(bool,num list)exc,s++[x]) else (M_success (x MOD 2=0),s++[x])) [2;0;5] [99] = (M_failure [7;11],[99;2;0])``;
val _ = observe "sm_tuple_state" ``st_ex_MAP (\(x:bool) (a:num,b:bool). ((M_success (if x then a else a+1)):(num,bool)exc,(a+2,~b))) [T;F;T] (5,F) = (M_success [5;8;9],(11,T))``;
val _ = observe "sm_empty_failure_callback" ``st_ex_MAP (\(x:num) (s:num). ((M_failure x):(bool,num)exc,s+100)) [] 7 = (M_success [],7)``;
