load "bossLib";
load "preamble";
load "reg_allocTheory";
open bossLib HolKernel Parse preamble reg_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val s0 = ``<| adj_ls := [[1];[0;2];[1]]; node_tag := [Fixed 0; Atemp; Stemp]; degrees := [1;2;1]; dim := 3;
  simp_wl := [0]; spill_wl := [1]; freeze_wl := [2]; avail_moves_wl := [(5,0,1)]; unavail_moves_wl := [(6,1,2)];
  coalesced := [0;1;2]; move_related := [T;F;T]; stack := [2;0] |>``;
fun s t = subst [``S0:ra_state`` |-> s0] t;
val _ = observe "acc_get_dim" (s ``FST (get_dim (S0:ra_state) : (num, state_exn) exc # ra_state)``);
val _ = observe "acc_get_stack" (s ``FST (get_stack (S0:ra_state) : (num list, state_exn) exc # ra_state)``);
val _ = observe "acc_get_avail" (s ``FST (get_avail_moves_wl (S0:ra_state) : ((num # num # num) list, state_exn) exc # ra_state)``);
val _ = observe "acc_set_dim" (s ``(SND (set_dim 7 (S0:ra_state) : (unit, state_exn) exc # ra_state)).dim``);
val _ = observe "acc_set_keeps" (s ``(SND (set_simp_wl [9;8] (S0:ra_state) : (unit, state_exn) exc # ra_state)).spill_wl``);
val _ = observe "acc_adj_length" (s ``FST (adj_ls_length (S0:ra_state) : (num, state_exn) exc # ra_state)``);
val _ = observe "acc_tag_sub" (s ``FST (node_tag_sub 1 (S0:ra_state))``);
val _ = observe "acc_tag_sub_oob" (s ``FST (node_tag_sub 3 (S0:ra_state))``);
val _ = observe "acc_adj_sub" (s ``FST (adj_ls_sub 1 (S0:ra_state))``);
val _ = observe "acc_large_oob" (s ``FST (degrees_sub 36893488147419103232 (S0:ra_state))``);
val _ = observe "acc_update_deg" (s ``(FST (update_degrees 2 9 (S0:ra_state)), (SND (update_degrees 2 9 (S0:ra_state))).degrees)``);
val _ = observe "acc_update_oob" (s ``(FST (update_degrees 3 9 (S0:ra_state)), (SND (update_degrees 3 9 (S0:ra_state))).degrees)``);
val _ = observe "acc_update_mr" (s ``(SND (update_move_related 1 T (S0:ra_state))).move_related``);
val _ = observe "acc_update_tag" (s ``(SND (update_node_tag 0 Stemp (S0:ra_state))).node_tag``);
val _ = observe "acc_coalesced_sub" (s ``FST (coalesced_sub 2 (S0:ra_state))``);
val _ = observe "acc_map_sub" (s ``FST (st_ex_MAP adj_ls_sub [2;0] (S0:ra_state))``);
val _ = observe "acc_map_oob" (s ``FST (st_ex_MAP node_tag_sub [0;5;1] (S0:ra_state))``);
val _ = observe "acc_mupdate" ``Mupdate Subscript (7:num) 1 [1;2;3]``;
