load "bossLib";
load "preamble";
load "reg_allocTheory";
open bossLib HolKernel Parse preamble reg_allocTheory;
val _ = Globals.linewidth := 1000;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
fun observe_type label ty = (print (label ^ "="); print_type ty; print "\n");
observe_type "fi_type" (type_of ``reg_alloc$st_ex_FILTER``);
observe_type "si_type" (type_of ``reg_alloc$sorted_insert``);
observe "fi_empty" ``st_ex_FILTER (\(x:num) (s:num). ((M_failure 9):(bool,num)exc,s+100)) [] [8;9] 7``;
observe "fi_mixed" ``st_ex_FILTER (\(x:num) (s:num). ((M_success (x MOD 2=0)):(bool,num)exc,s*10+x)) [1;2;3;4] [90] 0``;
observe "fi_all_true" ``st_ex_FILTER (\(x:num) (s:num). ((M_success T):(bool,num)exc,s+1)) [5;6;7] [] 0``;
observe "fi_all_false" ``st_ex_FILTER (\(x:num) (s:num). ((M_success F):(bool,num)exc,s+1)) [5;6;7] [1] 0``;
observe "fi_duplicates" ``st_ex_FILTER (\(x:num) (s:num). ((M_success (x > 1)):(bool,num)exc,s+x)) [2;2;1;2] [2] 0``;
observe "fi_state_pred" ``st_ex_FILTER (\(x:num) (s:num). ((M_success (s MOD 2=0)):(bool,num)exc,s+1)) [10;20;30;40] [] 0``;
observe "fi_fail_first" ``st_ex_FILTER (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [0;2;3] [90] 5``;
observe "fi_fail_middle" ``st_ex_FILTER (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [2;0;3] [90] 5``;
observe "fi_fail_last" ``st_ex_FILTER (\(x:num) (s:num). if x=0 then ((M_failure 17):(bool,num)exc,s+7) else (M_success (x MOD 2=0),s+x)) [2;3;0] [90] 5``;
observe "fi_bool_value" ``st_ex_FILTER (\(x:bool) (s:num). ((M_success (~x)):(bool,bool)exc,s+1)) [T;F;T;F] [T] 5``;
observe "fi_large" ``st_ex_FILTER (\(x:num) (s:num). ((M_success (x > 3)):(bool,num)exc,s+1)) [18446744073709551616;3] [] 0``;
observe "si_empty" ``sorted_insert 6 [] []``;
observe "si_empty_acc" ``sorted_insert 6 [9;8] []``;
observe "si_middle" ``sorted_insert 5 [] [7;4;2]``;
observe "si_dup" ``sorted_insert 4 [] [7;4;2]``;
observe "si_end" ``sorted_insert 1 [] [7;4;2]``;
observe "si_front" ``sorted_insert 9 [] [7;4;2]``;
observe "si_acc" ``sorted_insert 5 [12;10] [7;4;2]``;
observe "si_acc_dup" ``sorted_insert 7 [12;10] [7;4;2]``;
observe "si_unsorted" ``sorted_insert 5 [] [3;9;5]``;
observe "si_unsorted_dup_later" ``sorted_insert 9 [] [3;9;5]``;
observe "si_zero" ``sorted_insert 0 [] [0]``;
observe "si_large" ``sorted_insert 18446744073709551616 [] [18446744073709551617;2]``;
