load "preamble"; load "riscv_targetProofTheory"; load "blastLib";
open HolKernel Parse bossLib preamble riscv_targetTheory riscv_targetProofTheory alignmentTheory;
val _ = Globals.linewidth := 1000000;
val _ = Globals.show_types := true;
val near0 = Q.prove (`!a:word64. -4092w <= a /\ a <= 4095w /\ aligned 2 a ==> ((sw2sw ((w2w (a >>> 1):word12) - 0w):word64) << 1) = a - 0w`, rpt gen_tac >> simp [aligned_def,align_def] >> blastLib.BBLAST_TAC);
val _ = (print "near0_statement="; print_term (concl near0); print "\n");
val _ = print ("near0_types=" ^ String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string (type_of v)) (#1 (strip_forall (concl near0)))) ^ "\n");
val _ = print ("near0_hypotheses=" ^ Int.toString (length (hyp near0)) ^ "\n");
val _ = (print "near0_proved="; print_term (rhs (concl (EQT_INTRO near0))); print "\n");
val near0_boundary0 = EVAL ``((sw2sw ((w2w ((-4092w:word64) >>> 1):word12) - 0w):word64) << 1) = (-4092w:word64) - 0w``;
val _ = if null(hyp near0_boundary0) andalso aconv (rhs(concl near0_boundary0)) T then () else raise Fail "near0_boundary0";
val _ = (print "near0_boundary0="; print_term (rhs(concl near0_boundary0)); print "\n");
val near0_boundary1 = EVAL ``((sw2sw ((w2w ((-4w:word64) >>> 1):word12) - 0w):word64) << 1) = (-4w:word64) - 0w``;
val _ = if null(hyp near0_boundary1) andalso aconv (rhs(concl near0_boundary1)) T then () else raise Fail "near0_boundary1";
val _ = (print "near0_boundary1="; print_term (rhs(concl near0_boundary1)); print "\n");
val near0_boundary2 = EVAL ``((sw2sw ((w2w ((0w:word64) >>> 1):word12) - 0w):word64) << 1) = (0w:word64) - 0w``;
val _ = if null(hyp near0_boundary2) andalso aconv (rhs(concl near0_boundary2)) T then () else raise Fail "near0_boundary2";
val _ = (print "near0_boundary2="; print_term (rhs(concl near0_boundary2)); print "\n");
val near0_boundary3 = EVAL ``((sw2sw ((w2w ((4w:word64) >>> 1):word12) - 0w):word64) << 1) = (4w:word64) - 0w``;
val _ = if null(hyp near0_boundary3) andalso aconv (rhs(concl near0_boundary3)) T then () else raise Fail "near0_boundary3";
val _ = (print "near0_boundary3="; print_term (rhs(concl near0_boundary3)); print "\n");
val near0_boundary4 = EVAL ``((sw2sw ((w2w ((4092w:word64) >>> 1):word12) - 0w):word64) << 1) = (4092w:word64) - 0w``;
val _ = if null(hyp near0_boundary4) andalso aconv (rhs(concl near0_boundary4)) T then () else raise Fail "near0_boundary4";
val _ = (print "near0_boundary4="; print_term (rhs(concl near0_boundary4)); print "\n");
val near4 = Q.prove (`!a:word64. -4092w <= a /\ a <= 4095w /\ aligned 2 a ==> ((sw2sw ((w2w (a >>> 1):word12) - 2w):word64) << 1) = a - 4w`, rpt gen_tac >> simp [aligned_def,align_def] >> blastLib.BBLAST_TAC);
val _ = (print "near4_statement="; print_term (concl near4); print "\n");
val _ = print ("near4_types=" ^ String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string (type_of v)) (#1 (strip_forall (concl near4)))) ^ "\n");
val _ = print ("near4_hypotheses=" ^ Int.toString (length (hyp near4)) ^ "\n");
val _ = (print "near4_proved="; print_term (rhs (concl (EQT_INTRO near4))); print "\n");
val near4_boundary0 = EVAL ``((sw2sw ((w2w ((-4092w:word64) >>> 1):word12) - 2w):word64) << 1) = (-4092w:word64) - 4w``;
val _ = if null(hyp near4_boundary0) andalso aconv (rhs(concl near4_boundary0)) T then () else raise Fail "near4_boundary0";
val _ = (print "near4_boundary0="; print_term (rhs(concl near4_boundary0)); print "\n");
val near4_boundary1 = EVAL ``((sw2sw ((w2w ((-4w:word64) >>> 1):word12) - 2w):word64) << 1) = (-4w:word64) - 4w``;
val _ = if null(hyp near4_boundary1) andalso aconv (rhs(concl near4_boundary1)) T then () else raise Fail "near4_boundary1";
val _ = (print "near4_boundary1="; print_term (rhs(concl near4_boundary1)); print "\n");
val near4_boundary2 = EVAL ``((sw2sw ((w2w ((0w:word64) >>> 1):word12) - 2w):word64) << 1) = (0w:word64) - 4w``;
val _ = if null(hyp near4_boundary2) andalso aconv (rhs(concl near4_boundary2)) T then () else raise Fail "near4_boundary2";
val _ = (print "near4_boundary2="; print_term (rhs(concl near4_boundary2)); print "\n");
val near4_boundary3 = EVAL ``((sw2sw ((w2w ((4w:word64) >>> 1):word12) - 2w):word64) << 1) = (4w:word64) - 4w``;
val _ = if null(hyp near4_boundary3) andalso aconv (rhs(concl near4_boundary3)) T then () else raise Fail "near4_boundary3";
val _ = (print "near4_boundary3="; print_term (rhs(concl near4_boundary3)); print "\n");
val near4_boundary4 = EVAL ``((sw2sw ((w2w ((4092w:word64) >>> 1):word12) - 2w):word64) << 1) = (4092w:word64) - 4w``;
val _ = if null(hyp near4_boundary4) andalso aconv (rhs(concl near4_boundary4)) T then () else raise Fail "near4_boundary4";
val _ = (print "near4_boundary4="; print_term (rhs(concl near4_boundary4)); print "\n");
val far4 = Q.prove (`!a:word64. -1048568w <= a /\ a <= 1048579w /\ aligned 2 a ==> ((sw2sw ((w2w (a >>> 1):word20) - 2w):word64) << 1) = a - 4w`, rpt gen_tac >> simp [aligned_def,align_def] >> blastLib.BBLAST_TAC);
val _ = (print "far4_statement="; print_term (concl far4); print "\n");
val _ = print ("far4_types=" ^ String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string (type_of v)) (#1 (strip_forall (concl far4)))) ^ "\n");
val _ = print ("far4_hypotheses=" ^ Int.toString (length (hyp far4)) ^ "\n");
val _ = (print "far4_proved="; print_term (rhs (concl (EQT_INTRO far4))); print "\n");
val far4_boundary0 = EVAL ``((sw2sw ((w2w ((-1048568w:word64) >>> 1):word20) - 2w):word64) << 1) = (-1048568w:word64) - 4w``;
val _ = if null(hyp far4_boundary0) andalso aconv (rhs(concl far4_boundary0)) T then () else raise Fail "far4_boundary0";
val _ = (print "far4_boundary0="; print_term (rhs(concl far4_boundary0)); print "\n");
val far4_boundary1 = EVAL ``((sw2sw ((w2w ((-4096w:word64) >>> 1):word20) - 2w):word64) << 1) = (-4096w:word64) - 4w``;
val _ = if null(hyp far4_boundary1) andalso aconv (rhs(concl far4_boundary1)) T then () else raise Fail "far4_boundary1";
val _ = (print "far4_boundary1="; print_term (rhs(concl far4_boundary1)); print "\n");
val far4_boundary2 = EVAL ``((sw2sw ((w2w ((0w:word64) >>> 1):word20) - 2w):word64) << 1) = (0w:word64) - 4w``;
val _ = if null(hyp far4_boundary2) andalso aconv (rhs(concl far4_boundary2)) T then () else raise Fail "far4_boundary2";
val _ = (print "far4_boundary2="; print_term (rhs(concl far4_boundary2)); print "\n");
val far4_boundary3 = EVAL ``((sw2sw ((w2w ((4096w:word64) >>> 1):word20) - 2w):word64) << 1) = (4096w:word64) - 4w``;
val _ = if null(hyp far4_boundary3) andalso aconv (rhs(concl far4_boundary3)) T then () else raise Fail "far4_boundary3";
val _ = (print "far4_boundary3="; print_term (rhs(concl far4_boundary3)); print "\n");
val far4_boundary4 = EVAL ``((sw2sw ((w2w ((1048576w:word64) >>> 1):word20) - 2w):word64) << 1) = (1048576w:word64) - 4w``;
val _ = if null(hyp far4_boundary4) andalso aconv (rhs(concl far4_boundary4)) T then () else raise Fail "far4_boundary4";
val _ = (print "far4_boundary4="; print_term (rhs(concl far4_boundary4)); print "\n");
val far8 = Q.prove (`!a:word64. -1048568w <= a /\ a <= 1048579w /\ aligned 2 a ==> ((sw2sw ((w2w (a >>> 1):word20) - 4w):word64) << 1) = a - 8w`, rpt gen_tac >> simp [aligned_def,align_def] >> blastLib.BBLAST_TAC);
val _ = (print "far8_statement="; print_term (concl far8); print "\n");
val _ = print ("far8_types=" ^ String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string (type_of v)) (#1 (strip_forall (concl far8)))) ^ "\n");
val _ = print ("far8_hypotheses=" ^ Int.toString (length (hyp far8)) ^ "\n");
val _ = (print "far8_proved="; print_term (rhs (concl (EQT_INTRO far8))); print "\n");
val far8_boundary0 = EVAL ``((sw2sw ((w2w ((-1048568w:word64) >>> 1):word20) - 4w):word64) << 1) = (-1048568w:word64) - 8w``;
val _ = if null(hyp far8_boundary0) andalso aconv (rhs(concl far8_boundary0)) T then () else raise Fail "far8_boundary0";
val _ = (print "far8_boundary0="; print_term (rhs(concl far8_boundary0)); print "\n");
val far8_boundary1 = EVAL ``((sw2sw ((w2w ((-4096w:word64) >>> 1):word20) - 4w):word64) << 1) = (-4096w:word64) - 8w``;
val _ = if null(hyp far8_boundary1) andalso aconv (rhs(concl far8_boundary1)) T then () else raise Fail "far8_boundary1";
val _ = (print "far8_boundary1="; print_term (rhs(concl far8_boundary1)); print "\n");
val far8_boundary2 = EVAL ``((sw2sw ((w2w ((0w:word64) >>> 1):word20) - 4w):word64) << 1) = (0w:word64) - 8w``;
val _ = if null(hyp far8_boundary2) andalso aconv (rhs(concl far8_boundary2)) T then () else raise Fail "far8_boundary2";
val _ = (print "far8_boundary2="; print_term (rhs(concl far8_boundary2)); print "\n");
val far8_boundary3 = EVAL ``((sw2sw ((w2w ((4096w:word64) >>> 1):word20) - 4w):word64) << 1) = (4096w:word64) - 8w``;
val _ = if null(hyp far8_boundary3) andalso aconv (rhs(concl far8_boundary3)) T then () else raise Fail "far8_boundary3";
val _ = (print "far8_boundary3="; print_term (rhs(concl far8_boundary3)); print "\n");
val far8_boundary4 = EVAL ``((sw2sw ((w2w ((1048576w:word64) >>> 1):word20) - 4w):word64) << 1) = (1048576w:word64) - 8w``;
val _ = if null(hyp far8_boundary4) andalso aconv (rhs(concl far8_boundary4)) T then () else raise Fail "far8_boundary4";
val _ = (print "far8_boundary4="; print_term (rhs(concl far8_boundary4)); print "\n");
val pc_bias = Q.prove (`!pc a bias:word64. pc + bias + (a - bias) = pc + a`, blastLib.BBLAST_TAC);
val _ = (print "pc_bias_statement="; print_term (concl pc_bias); print "\n");
val _ = print ("pc_bias_hypotheses=" ^ Int.toString(length(hyp pc_bias)) ^ "\n");
val _ = (print "pc_bias_proved="; print_term(rhs(concl(EQT_INTRO pc_bias))); print "\n");
val reg_equal_source = SIMP_CONV (srw_ss()) [riscv_ast_def] ``riscv_ast (JumpCmp Equal r1 (Reg r2) a)``;
val _ = (print "reg_equal_source="; print_term(concl reg_equal_source); print "\n");
val _ = print ("reg_equal_hypotheses=" ^ Int.toString(length(hyp reg_equal_source)) ^ "\n");
val reg_test_source = SIMP_CONV (srw_ss()) [riscv_ast_def] ``riscv_ast (JumpCmp Test r1 (Reg r2) a)``;
val _ = (print "reg_test_source="; print_term(concl reg_test_source); print "\n");
val _ = print ("reg_test_hypotheses=" ^ Int.toString(length(hyp reg_test_source)) ^ "\n");
val imm_equal_source = SIMP_CONV (srw_ss()) [riscv_ast_def] ``riscv_ast (JumpCmp Equal r1 (Imm i) a)``;
val _ = (print "imm_equal_source="; print_term(concl imm_equal_source); print "\n");
val _ = print ("imm_equal_hypotheses=" ^ Int.toString(length(hyp imm_equal_source)) ^ "\n");
val imm_test_source = SIMP_CONV (srw_ss()) [riscv_ast_def] ``riscv_ast (JumpCmp Test r1 (Imm i) a)``;
val _ = (print "imm_test_source="; print_term(concl imm_test_source); print "\n");
val _ = print ("imm_test_hypotheses=" ^ Int.toString(length(hyp imm_test_source)) ^ "\n");
