load "preamble"; load "riscvTheory";
open HolKernel Parse bossLib preamble riscvTheory;
val _ = computeLib.add_funs [Encode_def,Itype_def,Stype_def,opc_def,Decode_def,boolify32_def,asSImm12_def];
val _ = Globals.linewidth := 1000000;
val _ = (print "ld_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LD (0w,0w,0w)))) = Load (riscv$LD (0w,0w,0w))``))); print "\n");
val _ = (print "ld_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LD (31w,31w,4095w)))) = Load (riscv$LD (31w,31w,4095w))``))); print "\n");
val _ = (print "ld_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LD (1w,16w,2048w)))) = Load (riscv$LD (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Load (riscv$LD (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "ld_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "ld_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "ld_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "lwu_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LWU (0w,0w,0w)))) = Load (riscv$LWU (0w,0w,0w))``))); print "\n");
val _ = (print "lwu_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LWU (31w,31w,4095w)))) = Load (riscv$LWU (31w,31w,4095w))``))); print "\n");
val _ = (print "lwu_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LWU (1w,16w,2048w)))) = Load (riscv$LWU (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Load (riscv$LWU (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "lwu_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "lwu_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "lwu_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "lhu_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LHU (0w,0w,0w)))) = Load (riscv$LHU (0w,0w,0w))``))); print "\n");
val _ = (print "lhu_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LHU (31w,31w,4095w)))) = Load (riscv$LHU (31w,31w,4095w))``))); print "\n");
val _ = (print "lhu_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LHU (1w,16w,2048w)))) = Load (riscv$LHU (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Load (riscv$LHU (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "lhu_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "lhu_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "lhu_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "lbu_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LBU (0w,0w,0w)))) = Load (riscv$LBU (0w,0w,0w))``))); print "\n");
val _ = (print "lbu_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LBU (31w,31w,4095w)))) = Load (riscv$LBU (31w,31w,4095w))``))); print "\n");
val _ = (print "lbu_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Load (riscv$LBU (1w,16w,2048w)))) = Load (riscv$LBU (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Load (riscv$LBU (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "lbu_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "lbu_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "lbu_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "sd_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SD (0w,0w,0w)))) = Store (riscv$SD (0w,0w,0w))``))); print "\n");
val _ = (print "sd_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SD (31w,31w,4095w)))) = Store (riscv$SD (31w,31w,4095w))``))); print "\n");
val _ = (print "sd_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SD (1w,16w,2048w)))) = Store (riscv$SD (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Store (riscv$SD (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "sd_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "sd_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "sd_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "sw_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SW (0w,0w,0w)))) = Store (riscv$SW (0w,0w,0w))``))); print "\n");
val _ = (print "sw_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SW (31w,31w,4095w)))) = Store (riscv$SW (31w,31w,4095w))``))); print "\n");
val _ = (print "sw_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SW (1w,16w,2048w)))) = Store (riscv$SW (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Store (riscv$SW (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "sw_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "sw_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "sw_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "sh_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SH (0w,0w,0w)))) = Store (riscv$SH (0w,0w,0w))``))); print "\n");
val _ = (print "sh_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SH (31w,31w,4095w)))) = Store (riscv$SH (31w,31w,4095w))``))); print "\n");
val _ = (print "sh_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SH (1w,16w,2048w)))) = Store (riscv$SH (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Store (riscv$SH (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "sh_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "sh_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "sh_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = (print "sb_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SB (0w,0w,0w)))) = Store (riscv$SB (0w,0w,0w))``))); print "\n");
val _ = (print "sb_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SB (31w,31w,4095w)))) = Store (riscv$SB (31w,31w,4095w))``))); print "\n");
val _ = (print "sb_decode_mixed_sign="; print_term(rhs(concl(EVAL ``Decode (Encode (Store (riscv$SB (1w,16w,2048w)))) = Store (riscv$SB (1w,16w,2048w))``))); print "\n");
val term = ``Encode (Store (riscv$SB (r1v,r2v,immv)))``;
val source = SIMP_CONV (srw_ss()) [Encode_def] term;
val _ = (print "sb_encode_source_clause="; (print_term(concl source); print "\n"));
val _ = (print "sb_encode_source_hypotheses="; print (Int.toString(length(hyp source)) ^ "\n"));
val _ = (print "sb_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars term)) ^ "\n"));
val _ = OS.Process.exit OS.Process.success;
