load "bossLib"; load "preamble"; load "source_to_flatTheory";
open bossLib HolKernel Parse preamble source_to_flatTheory;
val _ = show_types := true;
val _ = print "var_name_shape=";
val _ = print_term (concl (DB.fetch "source_to_flat" "var_name_case_def"));
val _ = print "\n";
val _ = print "environment_shape=";
val _ = print_term (concl (DB.fetch "source_to_flat" "environment_component_equality"));
val _ = print "\n";
val _ = print "environment_generation_store_shape=";
val _ = print_term (concl (DB.fetch "source_to_flat" "environment_generation_store_component_equality"));
val _ = print "\n";
val _ = print "environment_store_shape=";
val _ = print_term (concl (DB.fetch "source_to_flat" "environment_store_component_equality"));
val _ = print "\n";
val _ = print "next_indices_shape=";
val _ = print_term (concl (DB.fetch "source_to_flat" "next_indices_component_equality"));
val _ = print "\n";
val _ = print "config_shape=";
val _ = print_term (concl (DB.fetch "source_to_flat" "config_component_equality"));
val _ = print "\n";
val _ = print "Glob_type=";
val _ = print (type_to_string (type_of ``source_to_flat$Glob``));
val _ = print "\n";
val _ = print "Local_type=";
val _ = print (type_to_string (type_of ``source_to_flat$Local``));
val _ = print "\n";
val _ = print "environment_c_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment). x.c``));
val _ = print "\n";
val _ = print "environment_v_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment). x.v``));
val _ = print "\n";
val _ = print "environment_generation_store_next_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment_generation_store). x.next``));
val _ = print "\n";
val _ = print "environment_generation_store_generation_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment_generation_store). x.generation``));
val _ = print "\n";
val _ = print "environment_generation_store_envs_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment_generation_store). x.envs``));
val _ = print "\n";
val _ = print "environment_store_next_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment_store). x.next``));
val _ = print "\n";
val _ = print "environment_store_env_gens_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$environment_store). x.env_gens``));
val _ = print "\n";
val _ = print "next_indices_vidx_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$next_indices). x.vidx``));
val _ = print "\n";
val _ = print "next_indices_tidx_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$next_indices). x.tidx``));
val _ = print "\n";
val _ = print "next_indices_eidx_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$next_indices). x.eidx``));
val _ = print "\n";
val _ = print "config_next_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$config). x.next``));
val _ = print "\n";
val _ = print "config_mod_env_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$config). x.mod_env``));
val _ = print "\n";
val _ = print "config_pattern_cfg_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$config). x.pattern_cfg``));
val _ = print "\n";
val _ = print "config_envs_type=";
val _ = print (type_to_string (type_of ``\(x:source_to_flat$config). x.envs``));
val _ = print "\n";
