load "source_to_flatTheory"; load "mlstringTheory";
open HolKernel Parse boolLib bossLib source_to_flatTheory mlstringTheory;
val _ = Globals.linewidth := 1000000;
val _ = if null (hyp (compile_var_def)) then () else raise Fail "hypotheses: compile_var_def";
val _ = (print "compile_var_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (compile_var_def)); print "\n");
val _ = if null (hyp (compile_pat_def)) then () else raise Fail "hypotheses: compile_pat_def";
val _ = (print "compile_pat_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (compile_pat_def)); print "\n");
val _ = if null (hyp (pat_tups_def)) then () else raise Fail "hypotheses: pat_tups_def";
val _ = (print "pat_tups_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (pat_tups_def)); print "\n");
val _ = if null (hyp (astOp_to_flatOp_def)) then () else raise Fail "hypotheses: astOp_to_flatOp_def";
val _ = (print "astOp_to_flatOp_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (astOp_to_flatOp_def)); print "\n");
val _ = if null (hyp (type_group_id_type_def)) then () else raise Fail "hypotheses: type_group_id_type_def";
val _ = (print "type_group_id_type_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (type_group_id_type_def)); print "\n");
val _ = if null (hyp (str_sep_def)) then () else raise Fail "hypotheses: str_sep_def";
val _ = (print "str_sep_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (str_sep_def)); print "\n");
val _ = if null (hyp (join_all_names_aux_def)) then () else raise Fail "hypotheses: join_all_names_aux_def";
val _ = (print "join_all_names_aux_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (join_all_names_aux_def)); print "\n");
val _ = if null (hyp (join_all_names_def)) then () else raise Fail "hypotheses: join_all_names_def";
val _ = (print "join_all_names_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (join_all_names_def)); print "\n");
val _ = if null (hyp (om_tra_def)) then () else raise Fail "hypotheses: om_tra_def";
val _ = (print "om_tra_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (om_tra_def)); print "\n");
val _ = if null (hyp (alloc_defs_def)) then () else raise Fail "hypotheses: alloc_defs_def";
val _ = (print "alloc_defs_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (alloc_defs_def)); print "\n");
val _ = if null (hyp (make_varls_def)) then () else raise Fail "hypotheses: make_varls_def";
val _ = (print "make_varls_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (make_varls_def)); print "\n");
val _ = if null (hyp (empty_env_def)) then () else raise Fail "hypotheses: empty_env_def";
val _ = (print "empty_env_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (empty_env_def)); print "\n");
val _ = if null (hyp (extend_env_def)) then () else raise Fail "hypotheses: extend_env_def";
val _ = (print "extend_env_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (extend_env_def)); print "\n");
val _ = if null (hyp (lift_env_def)) then () else raise Fail "hypotheses: lift_env_def";
val _ = (print "lift_env_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (lift_env_def)); print "\n");
val _ = if null (hyp (lookup_inc_def)) then () else raise Fail "hypotheses: lookup_inc_def";
val _ = (print "lookup_inc_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (lookup_inc_def)); print "\n");
val _ = if null (hyp (alloc_tags1_def)) then () else raise Fail "hypotheses: alloc_tags1_def";
val _ = (print "alloc_tags1_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (alloc_tags1_def)); print "\n");
val _ = if null (hyp (alloc_tags_def)) then () else raise Fail "hypotheses: alloc_tags_def";
val _ = (print "alloc_tags_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (alloc_tags_def)); print "\n");
val _ = if null (hyp (env_id_tuple_def)) then () else raise Fail "hypotheses: env_id_tuple_def";
val _ = (print "env_id_tuple_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (env_id_tuple_def)); print "\n");
val _ = if null (hyp (simple_dlet_def)) then () else raise Fail "hypotheses: simple_dlet_def";
val _ = (print "simple_dlet_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (simple_dlet_def)); print "\n");
val _ = if null (hyp (concat_def)) then () else raise Fail "hypotheses: concat_def";
val _ = (print "concat_def_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl (concat_def)); print "\n");
