load "preamble";
load "sptreeTheory";
open bossLib HolKernel Parse preamble sptreeTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
fun out_proved label q th = (print (label ^ "="); print_term (rconc (EQT_INTRO (prove(q, ACCEPT_TAC th)))); print "\n");

val _ = out_proved "spt_union_insert_all" ``!k v (s:'a spt). insert k v s = union (insert k v LN) s`` insert_union;
val _ = out_proved "spt_union_assoc_all" ``!(t1:'a spt) t2 t3. union t1 (union t2 t3) = union (union t1 t2) t3`` union_assoc;
val _ = out_proved "spt_union_unit_sym_all" ``!(t1:unit spt) t2. union t1 t2 = union t2 t1`` union_num_set_sym;
val _ = out_proved "spt_union_singleton_all" ``!x y (t2:'a spt). union (insert x y LN) t2 = insert x y t2`` union_insert_LN;
val _ = out "spt_union_insert_empty_0" ``(insert 0 (42:num) LN = union (insert 0 (42:num) LN) LN)``;
val _ = out "spt_union_insert_empty_1" ``(insert 1 (42:num) LN = union (insert 1 (42:num) LN) LN)``;
val _ = out "spt_union_insert_empty_2" ``(insert 2 (42:num) LN = union (insert 2 (42:num) LN) LN)``;
val _ = out "spt_union_insert_empty_17" ``(insert 17 (42:num) LN = union (insert 17 (42:num) LN) LN)``;
val _ = out "spt_union_insert_leaf_0" ``(insert 0 (42:num) (LS 5) = union (insert 0 (42:num) LN) (LS 5))``;
val _ = out "spt_union_insert_leaf_1" ``(insert 1 (42:num) (LS 5) = union (insert 1 (42:num) LN) (LS 5))``;
val _ = out "spt_union_insert_leaf_2" ``(insert 2 (42:num) (LS 5) = union (insert 2 (42:num) LN) (LS 5))``;
val _ = out "spt_union_insert_leaf_17" ``(insert 17 (42:num) (LS 5) = union (insert 17 (42:num) LN) (LS 5))``;
val _ = out "spt_union_insert_empty_internal_0" ``(insert 0 (42:num) (BN LN LN) = union (insert 0 (42:num) LN) (BN LN LN))``;
val _ = out "spt_union_insert_empty_internal_1" ``(insert 1 (42:num) (BN LN LN) = union (insert 1 (42:num) LN) (BN LN LN))``;
val _ = out "spt_union_insert_empty_internal_2" ``(insert 2 (42:num) (BN LN LN) = union (insert 2 (42:num) LN) (BN LN LN))``;
val _ = out "spt_union_insert_empty_internal_17" ``(insert 17 (42:num) (BN LN LN) = union (insert 17 (42:num) LN) (BN LN LN))``;
val _ = out "spt_union_insert_branch_0" ``(insert 0 (42:num) (BN (LS 7) (LS 8)) = union (insert 0 (42:num) LN) (BN (LS 7) (LS 8)))``;
val _ = out "spt_union_insert_branch_1" ``(insert 1 (42:num) (BN (LS 7) (LS 8)) = union (insert 1 (42:num) LN) (BN (LS 7) (LS 8)))``;
val _ = out "spt_union_insert_branch_2" ``(insert 2 (42:num) (BN (LS 7) (LS 8)) = union (insert 2 (42:num) LN) (BN (LS 7) (LS 8)))``;
val _ = out "spt_union_insert_branch_17" ``(insert 17 (42:num) (BN (LS 7) (LS 8)) = union (insert 17 (42:num) LN) (BN (LS 7) (LS 8)))``;
val _ = out "spt_union_insert_root_0" ``(insert 0 (42:num) (BS (LS 7) 5 (LS 8)) = union (insert 0 (42:num) LN) (BS (LS 7) 5 (LS 8)))``;
val _ = out "spt_union_insert_root_1" ``(insert 1 (42:num) (BS (LS 7) 5 (LS 8)) = union (insert 1 (42:num) LN) (BS (LS 7) 5 (LS 8)))``;
val _ = out "spt_union_insert_root_2" ``(insert 2 (42:num) (BS (LS 7) 5 (LS 8)) = union (insert 2 (42:num) LN) (BS (LS 7) 5 (LS 8)))``;
val _ = out "spt_union_insert_root_17" ``(insert 17 (42:num) (BS (LS 7) 5 (LS 8)) = union (insert 17 (42:num) LN) (BS (LS 7) 5 (LS 8)))``;
val _ = out "spt_union_insert_malformed_nested_0" ``(insert 0 (42:num) (BS (BN LN LN) 5 (BN (LS 8) LN)) = union (insert 0 (42:num) LN) (BS (BN LN LN) 5 (BN (LS 8) LN)))``;
val _ = out "spt_union_insert_malformed_nested_1" ``(insert 1 (42:num) (BS (BN LN LN) 5 (BN (LS 8) LN)) = union (insert 1 (42:num) LN) (BS (BN LN LN) 5 (BN (LS 8) LN)))``;
val _ = out "spt_union_insert_malformed_nested_2" ``(insert 2 (42:num) (BS (BN LN LN) 5 (BN (LS 8) LN)) = union (insert 2 (42:num) LN) (BS (BN LN LN) 5 (BN (LS 8) LN)))``;
val _ = out "spt_union_insert_malformed_nested_17" ``(insert 17 (42:num) (BS (BN LN LN) 5 (BN (LS 8) LN)) = union (insert 17 (42:num) LN) (BS (BN LN LN) 5 (BN (LS 8) LN)))``;
val _ = out "spt_union_left_bias" ``union (LS (11:num)) (LS 22) = LS (11:num)``;
val _ = out "spt_union_nat_noncomm" ``union (LS (11:num)) (LS 22) <> union (LS 22) (LS (11:num))``;
val _ = out "spt_union_malformed_retained" ``union (BN LN LN) LN = (BN LN LN:num spt)``;
val _ = out "spt_union_unit_malformed" ``union (BN LN LN) (LS ()) = union (LS ()) (BN LN LN)``;
