load "preamble";
load "word_allocProofTheory";
open bossLib HolKernel Parse preamble word_allocProofTheory word_allocTheory wordSemTheory wordPropsTheory wordLangTheory sptreeTheory reg_allocTheory;
val _ = Globals.linewidth := 1000;
(* Capture original kernel theorem constructor specializations. No standalone
   tactic replay is claimed; original FP opcode proof8174-8222 is compared. *)
fun out label th = (print(label ^ "="); print_thm th; print "\n");
fun ty label name th = let val v=valOf(List.find(fn t => fst(dest_var t)=name)(free_vars(concl(SPEC_ALL th)))) in print(label ^ "="); print_type(type_of v); print "\n" end;
val sqrt_case = Q.SPEC `Inst (FP (FPSqrt n n0))` ssa_cc_trans_correct;
val _ = out "fp_sqrt_full" sqrt_case;
val _ = ty "fp_sqrt_type_st" "st" sqrt_case;
val _ = ty "fp_sqrt_type_cst" "cst" sqrt_case;
val _ = ty "fp_sqrt_type_dst" "n" sqrt_case;
val _ = ty "fp_sqrt_type_arg" "n0" sqrt_case;
val _ = ty "fp_sqrt_type_ssa" "ssa" sqrt_case;
val _ = ty "fp_sqrt_type_next" "na" sqrt_case;
val _ = ty "fp_sqrt_type_tables" "lt" sqrt_case;
val add_case = Q.SPEC `Inst (FP (FPAdd n n0 n1))` ssa_cc_trans_correct;
val _ = out "fp_add_full" add_case;
val _ = ty "fp_add_type_st" "st" add_case;
val _ = ty "fp_add_type_cst" "cst" add_case;
val _ = ty "fp_add_type_dst" "n" add_case;
val _ = ty "fp_add_type_arg" "n0" add_case;
val _ = ty "fp_add_type_other" "n1" add_case;
val _ = ty "fp_add_type_ssa" "ssa" add_case;
val _ = ty "fp_add_type_next" "na" add_case;
val _ = ty "fp_add_type_tables" "lt" add_case;
val sub_case = Q.SPEC `Inst (FP (FPSub n n0 n1))` ssa_cc_trans_correct;
val _ = out "fp_sub_full" sub_case;
val _ = ty "fp_sub_type_st" "st" sub_case;
val _ = ty "fp_sub_type_cst" "cst" sub_case;
val _ = ty "fp_sub_type_dst" "n" sub_case;
val _ = ty "fp_sub_type_arg" "n0" sub_case;
val _ = ty "fp_sub_type_other" "n1" sub_case;
val _ = ty "fp_sub_type_ssa" "ssa" sub_case;
val _ = ty "fp_sub_type_next" "na" sub_case;
val _ = ty "fp_sub_type_tables" "lt" sub_case;
val mul_case = Q.SPEC `Inst (FP (FPMul n n0 n1))` ssa_cc_trans_correct;
val _ = out "fp_mul_full" mul_case;
val _ = ty "fp_mul_type_st" "st" mul_case;
val _ = ty "fp_mul_type_cst" "cst" mul_case;
val _ = ty "fp_mul_type_dst" "n" mul_case;
val _ = ty "fp_mul_type_arg" "n0" mul_case;
val _ = ty "fp_mul_type_other" "n1" mul_case;
val _ = ty "fp_mul_type_ssa" "ssa" mul_case;
val _ = ty "fp_mul_type_next" "na" mul_case;
val _ = ty "fp_mul_type_tables" "lt" mul_case;
val div_case = Q.SPEC `Inst (FP (FPDiv n n0 n1))` ssa_cc_trans_correct;
val _ = out "fp_div_full" div_case;
val _ = ty "fp_div_type_st" "st" div_case;
val _ = ty "fp_div_type_cst" "cst" div_case;
val _ = ty "fp_div_type_dst" "n" div_case;
val _ = ty "fp_div_type_arg" "n0" div_case;
val _ = ty "fp_div_type_other" "n1" div_case;
val _ = ty "fp_div_type_ssa" "ssa" div_case;
val _ = ty "fp_div_type_next" "na" div_case;
val _ = ty "fp_div_type_tables" "lt" div_case;
val fma_case = Q.SPEC `Inst (FP (FPFma n n0 n1))` ssa_cc_trans_correct;
val _ = out "fp_fma_full" fma_case;
val _ = ty "fp_fma_type_st" "st" fma_case;
val _ = ty "fp_fma_type_cst" "cst" fma_case;
val _ = ty "fp_fma_type_dst" "n" fma_case;
val _ = ty "fp_fma_type_arg" "n0" fma_case;
val _ = ty "fp_fma_type_other" "n1" fma_case;
val _ = ty "fp_fma_type_ssa" "ssa" fma_case;
val _ = ty "fp_fma_type_next" "na" fma_case;
val _ = ty "fp_fma_type_tables" "lt" fma_case;
