load "preamble";
load "word_allocTheory";
open bossLib HolKernel Parse preamble word_allocTheory wordLangTheory sptreeTheory;
fun out label q = (print(label ^ "=");print_term(rconc(EVAL q));print "\n");
val _ = out "ss_even" ``(even_list 0,even_list 1,even_list 5)``;
val _ = out "ss_empty" ``let (ns,t,n) = list_next_var_rename [] (fromAList [(9,99)]) 5 in (ns,MAP (\k.lookup k t) [0;1;2;9],n)``;
val _ = out "ss_duplicates" ``let (ns,t,n) = list_next_var_rename [1;2;1] (fromAList [(9,99);(1,88)]) 5 in (ns,MAP (\k.lookup k t) [0;1;2;9],n)``;
val _ = out "ss_invalid" ``let (ns,t,n) = list_next_var_rename [0;4] (BN LN LN) 0 in (ns,MAP (\k.lookup k t) [0;1;4],n)``;
val _ = out "ss_one" ``let (v,t,n) = next_var_rename 9 (fromAList [(9,99);(1,88)]) 101 in (v,MAP (\k.lookup k t) [1;9],n)``;
val _ = out "ss_setup0" ``let (p,t,n) = setup_ssa 0 7 (Skip:1 wordLang$prog) in (p,MAP (\k.lookup k t) [0;2;4;6],n)``;
val _ = out "ss_setup1" ``let (p,t,n) = setup_ssa 1 0 (Assign 999 (Var 999):32 wordLang$prog) in (p,MAP (\k.lookup k t) [0;2;4;6],n)``;
val _ = out "ss_setup3" ``let (p,t,n) = setup_ssa 3 5 (Skip:64 wordLang$prog) in (p,MAP (\k.lookup k t) [0;2;4;6],n)``;
val _ = out "ss_setup80" ``let (p,t,n) = setup_ssa 3 101 (Assign 999 (Var 999):80 wordLang$prog) in (p,MAP (\k.lookup k t) [0;2;4;6],n)``;
val _ = (print "even_list_def=";print_thm(DB.fetch "word_alloc" "even_list_def");print "\n");
val _ = (print "next_var_rename_def=";print_thm(DB.fetch "word_alloc" "next_var_rename_def");print "\n");
val _ = (print "list_next_var_rename_def=";print_thm(DB.fetch "word_alloc" "list_next_var_rename_def");print "\n");
val _ = (print "setup_ssa_def=";print_thm(DB.fetch "word_alloc" "setup_ssa_def");print "\n");
