load "preamble";
load "word_allocProofTheory";
open bossLib HolKernel Parse preamble word_allocProofTheory word_allocTheory wordSemTheory wordPropsTheory wordLangTheory sptreeTheory reg_allocTheory;
val _ = Globals.linewidth := 1000;
(* Capture original kernel theorem constructor specializations. No standalone
   tactic replay is claimed; original FP opcode proof8174-8222 is compared. *)
fun out label th = (print(label ^ "="); print_thm th; print "\n");
fun ty label name th = let val v=valOf(List.find(fn t => fst(dest_var t)=name)(free_vars(concl(SPEC_ALL th)))) in print(label ^ "="); print_type(type_of v); print "\n" end;
val mov_case = Q.SPEC `Inst (FP (FPMov n n0))` ssa_cc_trans_correct;
val _ = out "fp_mov_full" mov_case;
val _ = ty "fp_mov_type_st" "st" mov_case;
val _ = ty "fp_mov_type_cst" "cst" mov_case;
val _ = ty "fp_mov_type_dst" "n" mov_case;
val _ = ty "fp_mov_type_left" "n0" mov_case;
val _ = ty "fp_mov_type_ssa" "ssa" mov_case;
val _ = ty "fp_mov_type_next" "na" mov_case;
val _ = ty "fp_mov_type_tables" "lt" mov_case;
val abs_case = Q.SPEC `Inst (FP (FPAbs n n0))` ssa_cc_trans_correct;
val _ = out "fp_abs_full" abs_case;
val _ = ty "fp_abs_type_st" "st" abs_case;
val _ = ty "fp_abs_type_cst" "cst" abs_case;
val _ = ty "fp_abs_type_dst" "n" abs_case;
val _ = ty "fp_abs_type_left" "n0" abs_case;
val _ = ty "fp_abs_type_ssa" "ssa" abs_case;
val _ = ty "fp_abs_type_next" "na" abs_case;
val _ = ty "fp_abs_type_tables" "lt" abs_case;
val neg_case = Q.SPEC `Inst (FP (FPNeg n n0))` ssa_cc_trans_correct;
val _ = out "fp_neg_full" neg_case;
val _ = ty "fp_neg_type_st" "st" neg_case;
val _ = ty "fp_neg_type_cst" "cst" neg_case;
val _ = ty "fp_neg_type_dst" "n" neg_case;
val _ = ty "fp_neg_type_left" "n0" neg_case;
val _ = ty "fp_neg_type_ssa" "ssa" neg_case;
val _ = ty "fp_neg_type_next" "na" neg_case;
val _ = ty "fp_neg_type_tables" "lt" neg_case;
