load "preamble";
load "word_allocProofTheory";
open bossLib HolKernel Parse preamble word_allocProofTheory word_allocTheory sptreeTheory;
val _ = Globals.linewidth := 1000;
fun out label th = (print(label ^ "="); print_thm th; print "\n");
fun ty label name th = let val v=valOf(List.find(fn t => fst(dest_var t)=name)(free_vars(concl(SPEC_ALL th)))) in print(label ^ "="); print_type(type_of v); print "\n" end;
val _ = out "force_locals_full" ssa_locals_rel_force_rename;
val _ = ty "force_locals_type_source" "st1" ssa_locals_rel_force_rename;
val _ = ty "force_locals_type_target" "st2" ssa_locals_rel_force_rename;
val _ = ty "force_locals_type_ssa" "ssa" ssa_locals_rel_force_rename;
val _ = ty "force_locals_type_pairs" "ls" ssa_locals_rel_force_rename;
val _ = ty "force_locals_type_next" "na" ssa_locals_rel_force_rename;
