load "bossLib"; load "preamble"; load "stackPropsTheory";
open bossLib HolKernel Parse preamble stackPropsTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "inst_good" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Inst (Const 5 0w) : 8 stackLang$prog)``;
val _ = out "inst_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Inst (Const 6 0w) : 8 stackLang$prog)``;
val _ = out "heap_alias" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (OpCurrHeap Add 1 1 : 8 stackLang$prog)``;
val _ = out "heap_distinct" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (OpCurrHeap Add 1 2 : 8 stackLang$prog)``;
val _ = out "code_good" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (CodeBufferWrite 1 5 : 8 stackLang$prog)``;
val _ = out "code_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (CodeBufferWrite 6 1 : 8 stackLang$prog)``;
val _ = out "data_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (DataBufferWrite 1 6 : 8 stackLang$prog)``;
val _ = out "seq_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Seq Skip (Return 6) : 8 stackLang$prog)``;
val _ = out "if_ignored" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (If Equal 99 (Reg 99) Skip Skip : 8 stackLang$prog)``;
val _ = out "loop_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Loop (Raise 6) : 8 stackLang$prog)``;
val _ = out "raise_good" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Raise 5 : 8 stackLang$prog)``;
val _ = out "return_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Return 6 : 8 stackLang$prog)``;
val _ = out "call_direct" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Call NONE (INL 99) NONE : 8 stackLang$prog)``;
val _ = out "call_indirect_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Call NONE (INR 6) NONE : 8 stackLang$prog)``;
val _ = out "call_none_handler_ignored" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Call NONE (INR 5) (SOME (Return 6,3,4)) : 8 stackLang$prog)``;
val _ = out "call_body_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Call (SOME (Return 6,99,1,2)) (INL 99) NONE : 8 stackLang$prog)``;
val _ = out "call_handler_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Call (SOME (Skip,99,1,2)) (INR 5) (SOME (Raise 6,3,4)) : 8 stackLang$prog)``;
val _ = out "call_good" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Call (SOME (Return 5,99,1,2)) (INR 5) (SOME (Raise 5,3,4)) : 8 stackLang$prog)``;
val _ = out "alloc_default" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; two_reg_arith:=T|>) (Alloc 99 : 8 stackLang$prog)``;
val _ = out "shared_good" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; byte_offset:=(0w,0w)|>) (ShMemOp Load8 1 (Addr 1 0w) : 8 stackLang$prog)``;
val _ = out "shared_register_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; byte_offset:=(0w,0w)|>) (ShMemOp Load8 6 (Addr 1 0w) : 8 stackLang$prog)``;
val _ = out "shared_base_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; byte_offset:=(0w,0w)|>) (ShMemOp Load8 1 (Addr 6 0w) : 8 stackLang$prog)``;
val _ = out "shared_offset_bad" ``stack_asm_name ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]; byte_offset:=(0w,0w)|>) (ShMemOp Load8 1 (Addr 1 1w) : 8 stackLang$prog)``;
