load "bossLib";
load "preamble";
load "stackSemTheory";
open bossLib HolKernel Parse preamble stackSemTheory;
fun observe label q = let val th = EVAL q in
  (print (label ^ "="); print_term (rconc th); print "\n") end;
val _ = observe "get_word" ``let (r,s) = stackSem$evaluate (stackLang$Get 3 CurrHeap,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "get_loc" ``let (r,s) = stackSem$evaluate (stackLang$Get 3 Handler,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "get_missing" ``let (r,s) = stackSem$evaluate (stackLang$Get 3 Globals,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "get_disabled" ``let (r,s) = stackSem$evaluate (stackLang$Get 3 CurrHeap,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := F;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "set_word" ``let (r,s) = stackSem$evaluate (stackLang$Set CurrHeap 1,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "set_loc" ``let (r,s) = stackSem$evaluate (stackLang$Set CurrHeap 2,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "set_missing" ``let (r,s) = stackSem$evaluate (stackLang$Set CurrHeap 4,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "set_disabled" ``let (r,s) = stackSem$evaluate (stackLang$Set CurrHeap 1,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := F;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "op_add" ``let (r,s) = stackSem$evaluate (stackLang$OpCurrHeap Add 3 1,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "op_sub" ``let (r,s) = stackSem$evaluate (stackLang$OpCurrHeap Sub 3 1,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "op_loc" ``let (r,s) = stackSem$evaluate (stackLang$OpCurrHeap Add 3 2,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "op_missing" ``let (r,s) = stackSem$evaluate (stackLang$OpCurrHeap Add 3 4,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := T;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
val _ = observe "op_disabled" ``let (r,s) = stackSem$evaluate (stackLang$OpCurrHeap Add 3 1,((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (CurrHeap,Word 10w) |+ (Handler,Loc 8 9);use_store := F;clock := 6|>)) in (r,s.clock,FLOOKUP s.regs 3,FLOOKUP s.store CurrHeap)``;
