load "preamble"; load "stack_namesTheory";
open bossLib HolKernel Parse preamble stack_namesTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val names = ``sptree$insert 3 7 sptree$LN : num num_map``;
val _ = out "skip" ``inst_find_name ^names (Skip : 8 asm$inst)``;
val _ = out "const" ``inst_find_name ^names (Const 3 255w : 8 asm$inst)``;
val _ = out "binop" ``inst_find_name ^names (Arith (Binop Add 3 4 (Reg 3)) : 8 asm$inst)``;
val _ = out "shift" ``inst_find_name ^names (Arith (Shift Lsl 3 4 (Imm 2w)) : 8 asm$inst)``;
val _ = out "div" ``inst_find_name ^names (Arith (Div 3 4 3) : 8 asm$inst)``;
val _ = out "longmul" ``inst_find_name ^names (Arith (LongMul 3 4 3 4) : 8 asm$inst)``;
val _ = out "longdiv" ``inst_find_name ^names (Arith (LongDiv 3 4 3 4 3) : 8 asm$inst)``;
val _ = out "addcarry" ``inst_find_name ^names (Arith (AddCarry 3 4 3 4) : 8 asm$inst)``;
val _ = out "addoverflow" ``inst_find_name ^names (Arith (AddOverflow 3 4 3 4) : 8 asm$inst)``;
val _ = out "suboverflow" ``inst_find_name ^names (Arith (SubOverflow 3 4 3 4) : 8 asm$inst)``;
val _ = out "mem" ``inst_find_name ^names (Mem Load 3 (Addr 3 255w) : 8 asm$inst)``;
val _ = out "fpless" ``inst_find_name ^names (FP (FPLess 3 3 4) : 8 asm$inst)``;
val _ = out "fplesseq" ``inst_find_name ^names (FP (FPLessEqual 3 3 4) : 8 asm$inst)``;
val _ = out "fpeq" ``inst_find_name ^names (FP (FPEqual 3 3 4) : 8 asm$inst)``;
val _ = out "fptoreg" ``inst_find_name ^names (FP (FPMovToReg 3 4 3) : 8 asm$inst)``;
val _ = out "fpfromreg" ``inst_find_name ^names (FP (FPMovFromReg 3 3 4) : 8 asm$inst)``;
val _ = out "fpdefault" ``inst_find_name ^names (FP (FPAdd 3 3 4) : 8 asm$inst)``;
