load "preamble";
load "stackLangTheory";
open bossLib HolKernel Parse preamble stackLangTheory;
val _ = Globals.linewidth := 10000;
fun emit label q = print (label ^ "=" ^ term_to_string (rconc (EVAL q)) ^ "\n");
val saved_While = ``While``;
val _ = print ("While_term=" ^ term_to_string ``While`` ^ "\n");
val _ = print ("While_type=" ^ type_to_string (type_of ``While``) ^ "\n");
val saved_move = ``move``;
val _ = print ("move_term=" ^ term_to_string ``move`` ^ "\n");
val _ = print ("move_type=" ^ type_to_string (type_of ``move``) ^ "\n");
val saved_sub_inst = ``sub_inst``;
val _ = print ("sub_inst_term=" ^ term_to_string ``sub_inst`` ^ "\n");
val _ = print ("sub_inst_type=" ^ type_to_string (type_of ``sub_inst``) ^ "\n");
val saved_add_inst = ``add_inst``;
val _ = print ("add_inst_term=" ^ term_to_string ``add_inst`` ^ "\n");
val _ = print ("add_inst_type=" ^ type_to_string (type_of ``add_inst``) ^ "\n");
val saved_add_bytes_in_word_inst = ``add_bytes_in_word_inst``;
val _ = print ("add_bytes_in_word_inst_term=" ^ term_to_string ``add_bytes_in_word_inst`` ^ "\n");
val _ = print ("add_bytes_in_word_inst_type=" ^ type_to_string (type_of ``add_bytes_in_word_inst``) ^ "\n");
val _ = print ("list_Seq_full_def=" ^ term_to_string (concl list_Seq_def) ^ "\n");
val _ = print ("list_Seq_type=" ^ type_to_string (type_of ``list_Seq``) ^ "\n");
val _ = emit "move_1" ``move 1234 42 : 1 stackLang$prog``;
val _ = emit "sub_inst_1" ``sub_inst 1234 42 : 1 stackLang$prog``;
val _ = emit "add_inst_1" ``add_inst 1234 42 : 1 stackLang$prog``;
val _ = emit "bytes_1" ``add_bytes_in_word_inst 1234 : 1 stackLang$prog``;
val _ = emit "while_1" ``While NotEqual 1234 (Imm 1w) (Halt 42) : 1 stackLang$prog``;
val _ = emit "seq_1_0" ``list_Seq [] : 1 stackLang$prog``;
val _ = emit "seq_1_1" ``list_Seq [Halt 42] : 1 stackLang$prog``;
val _ = emit "seq_1_2" ``list_Seq [Halt 42; Skip] : 1 stackLang$prog``;
val _ = emit "seq_1_3" ``list_Seq [Halt 42; Skip; Break 7] : 1 stackLang$prog``;
val _ = emit "move_8" ``move 1234 42 : 8 stackLang$prog``;
val _ = emit "sub_inst_8" ``sub_inst 1234 42 : 8 stackLang$prog``;
val _ = emit "add_inst_8" ``add_inst 1234 42 : 8 stackLang$prog``;
val _ = emit "bytes_8" ``add_bytes_in_word_inst 1234 : 8 stackLang$prog``;
val _ = emit "while_8" ``While NotEqual 1234 (Imm 1w) (Halt 42) : 8 stackLang$prog``;
val _ = emit "seq_8_0" ``list_Seq [] : 8 stackLang$prog``;
val _ = emit "seq_8_1" ``list_Seq [Halt 42] : 8 stackLang$prog``;
val _ = emit "seq_8_2" ``list_Seq [Halt 42; Skip] : 8 stackLang$prog``;
val _ = emit "seq_8_3" ``list_Seq [Halt 42; Skip; Break 7] : 8 stackLang$prog``;
val _ = emit "move_32" ``move 1234 42 : 32 stackLang$prog``;
val _ = emit "sub_inst_32" ``sub_inst 1234 42 : 32 stackLang$prog``;
val _ = emit "add_inst_32" ``add_inst 1234 42 : 32 stackLang$prog``;
val _ = emit "bytes_32" ``add_bytes_in_word_inst 1234 : 32 stackLang$prog``;
val _ = emit "while_32" ``While NotEqual 1234 (Imm 1w) (Halt 42) : 32 stackLang$prog``;
val _ = emit "seq_32_0" ``list_Seq [] : 32 stackLang$prog``;
val _ = emit "seq_32_1" ``list_Seq [Halt 42] : 32 stackLang$prog``;
val _ = emit "seq_32_2" ``list_Seq [Halt 42; Skip] : 32 stackLang$prog``;
val _ = emit "seq_32_3" ``list_Seq [Halt 42; Skip; Break 7] : 32 stackLang$prog``;
val _ = emit "move_64" ``move 1234 42 : 64 stackLang$prog``;
val _ = emit "sub_inst_64" ``sub_inst 1234 42 : 64 stackLang$prog``;
val _ = emit "add_inst_64" ``add_inst 1234 42 : 64 stackLang$prog``;
val _ = emit "bytes_64" ``add_bytes_in_word_inst 1234 : 64 stackLang$prog``;
val _ = emit "while_64" ``While NotEqual 1234 (Imm 1w) (Halt 42) : 64 stackLang$prog``;
val _ = emit "seq_64_0" ``list_Seq [] : 64 stackLang$prog``;
val _ = emit "seq_64_1" ``list_Seq [Halt 42] : 64 stackLang$prog``;
val _ = emit "seq_64_2" ``list_Seq [Halt 42; Skip] : 64 stackLang$prog``;
val _ = emit "seq_64_3" ``list_Seq [Halt 42; Skip; Break 7] : 64 stackLang$prog``;
val _ = emit "move_80" ``move 1234 42 : 80 stackLang$prog``;
val _ = emit "sub_inst_80" ``sub_inst 1234 42 : 80 stackLang$prog``;
val _ = emit "add_inst_80" ``add_inst 1234 42 : 80 stackLang$prog``;
val _ = emit "bytes_80" ``add_bytes_in_word_inst 1234 : 80 stackLang$prog``;
val _ = emit "while_80" ``While NotEqual 1234 (Imm 1w) (Halt 42) : 80 stackLang$prog``;
val _ = emit "seq_80_0" ``list_Seq [] : 80 stackLang$prog``;
val _ = emit "seq_80_1" ``list_Seq [Halt 42] : 80 stackLang$prog``;
val _ = emit "seq_80_2" ``list_Seq [Halt 42; Skip] : 80 stackLang$prog``;
val _ = emit "seq_80_3" ``list_Seq [Halt 42; Skip; Break 7] : 80 stackLang$prog``;

val _ = temp_clear_overloads_on "While";
val _ = temp_clear_overloads_on "move";
val _ = temp_clear_overloads_on "sub_inst";
val _ = temp_clear_overloads_on "add_inst";
val _ = temp_clear_overloads_on "add_bytes_in_word_inst";
val _ = print ("While_expanded=" ^ term_to_string saved_While ^ "\n");
val _ = print ("move_expanded=" ^ term_to_string saved_move ^ "\n");
val _ = print ("sub_inst_expanded=" ^ term_to_string saved_sub_inst ^ "\n");
val _ = print ("add_inst_expanded=" ^ term_to_string saved_add_inst ^ "\n");
val _ = print ("add_bytes_in_word_inst_expanded=" ^ term_to_string saved_add_bytes_in_word_inst ^ "\n");
