(* Direct original StackSem expression/assignment observations. *)
load "bossLib";
load "preamble";
load "stackSemTheory";
open bossLib HolKernel Parse preamble stackSemTheory;
fun observe label q = let val th = EVAL q in
  (print (label ^ "="); print_term (rconc th); print "\n") end;
val _ = observe "const" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Const 255w)``;
val _ = observe "var_word" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Var 1)``;
val _ = observe "var_loc" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Var 2)``;
val _ = observe "var_missing" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Var 3)``;
val _ = observe "lookup_word" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Lookup AllocSize)``;
val _ = observe "lookup_loc" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Lookup NextFree)``;
val _ = observe "lookup_missing" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Lookup TriggerGC)``;
val _ = observe "load_word" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Load (Const 0w))``;
val _ = observe "load_loc" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Load (Const 1w))``;
val _ = observe "load_oob" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Load (Const 2w))``;
val _ = observe "load_bad_address" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Load (Var 2))``;
val _ = observe "op_empty_and" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Op And [])``;
val _ = observe "op_add_wrap" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Op Add [Const 255w;Const 2w])``;
val _ = observe "op_sub_bad_arity" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Op Sub [Const 1w])``;
val _ = observe "op_bad_operand" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Op Add [Const 1w;Var 2])``;
val _ = observe "shift_valid" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Shift Lsl (Const 3w) (Const 2w))``;
val _ = observe "shift_oob" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Shift Lsl (Const 3w) (Const 8w))``;
val _ = observe "shift_bad_right" ``stackSem$word_exp ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>) (Shift Lsr (Const 3w) (Var 2))``;
val _ = observe "assign_success" ``OPTION_MAP (λs. (FLOOKUP s.regs 1,FLOOKUP s.regs 2)) (stackSem$assign 1 (Const 12w) ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>))``;
val _ = observe "assign_failure" ``OPTION_MAP (λs. (FLOOKUP s.regs 1,FLOOKUP s.regs 2)) (stackSem$assign 1 (Var 2) ((ARB : (8,unit,unit) stackSem$state) with <|regs := FEMPTY |+ (1,Word 7w) |+ (2,Loc 4 5);store := FEMPTY |+ (AllocSize,Word 9w) |+ (NextFree,Loc 2 3);memory := (λa. if a = 0w then Word 11w else Loc 8 9);mdomain := {0w;1w}|>))``;
