(* Complete original native output trees; no flatten-to-list summary. *)
load "bossLib";
load "preamble";
load "stack_to_labTheory";
open bossLib HolKernel Parse preamble;
val _ = Globals.linewidth := 10000;
fun emit label tm = print (label ^ "=" ^ term_to_string (rconc (EVAL tm)) ^ "\n");
val _ = print ("native_flatten_definition=" ^ term_to_string (concl stack_to_labTheory.flatten_def) ^ "\n");
val _ = emit "native_seq_tail_tree" ``stack_to_lab$flatten T (stackLang$Seq Tick Skip : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_if_left_skip_tree" ``stack_to_lab$flatten F (stackLang$If Less 3 (Reg 4) Skip Tick : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_if_right_skip_tree" ``stack_to_lab$flatten F (stackLang$If Less 3 (Reg 4) Tick Skip : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_if_left_noreturn_tree" ``stack_to_lab$flatten F (stackLang$If Less 3 (Reg 4) (Halt 5) Tick : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_if_right_noreturn_tree" ``stack_to_lab$flatten F (stackLang$If Less 3 (Reg 4) Tick (Halt 5) : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_if_fallthrough_tree" ``stack_to_lab$flatten F (stackLang$If Less 3 (Reg 4) Tick Tick : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_loop_tree" ``stack_to_lab$flatten F (stackLang$Loop (Break 0) : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_call_handler_tree" ``stack_to_lab$flatten F (stackLang$Call (SOME (Tick,3,8,9)) (INL 4) (SOME (Tick,10,11)) : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_section_seq" ``stack_to_lab$prog_to_section (7,stackLang$Seq Tick Skip : 64 stackLang$prog)``;
val _ = emit "native_tick" ``stack_to_lab$flatten F (Tick : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_inst" ``stack_to_lab$flatten F (Inst Skip : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_halt" ``stack_to_lab$flatten F (Halt 99 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_raise" ``stack_to_lab$flatten F (Raise 999 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_return" ``stack_to_lab$flatten F (Return 999 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_break_missing" ``stack_to_lab$flatten F (Break 100 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_continue_missing" ``stack_to_lab$flatten F (Continue 100 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_rawcall" ``stack_to_lab$flatten F (RawCall 999 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_tailcall_label" ``stack_to_lab$flatten F (Call NONE (INL 999) NONE : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_tailcall_register" ``stack_to_lab$flatten F (Call NONE (INR 999) (SOME (Tick,8,9)) : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_lower" ``stack_to_lab$flatten F (JumpLower 3 4 999 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_location" ``stack_to_lab$flatten F (LocValue 3 999 1000 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_install" ``stack_to_lab$flatten F (Install 1 2 3 4 5 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_shared" ``stack_to_lab$flatten F (ShMemOp Load 3 (Addr 4 0w) : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_buffer" ``stack_to_lab$flatten F (CodeBufferWrite 3 4 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback" ``stack_to_lab$flatten F (DataBufferWrite 3 4 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_width1" ``stack_to_lab$flatten F (Inst (Const 999 1w) : 1 stackLang$prog) 7 2 [] []``;
val _ = emit "native_width80" ``stack_to_lab$flatten F (Inst (Const 999 1208925819614629174706175w) : 80 stackLang$prog) 7 2 [] []``;
val _ = emit "native_ffi" ``stack_to_lab$flatten F (FFI (strlit "ffi") 1 2 3 4 5 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_01" ``stack_to_lab$flatten F (Skip : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_02" ``stack_to_lab$flatten F (Get 1 Globals : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_03" ``stack_to_lab$flatten F (Set Globals 1 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_04" ``stack_to_lab$flatten F (OpCurrHeap Add 1 2 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_05" ``stack_to_lab$flatten F (Alloc 1 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_06" ``stack_to_lab$flatten F (StoreConsts 1 2 NONE : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_07" ``stack_to_lab$flatten F (StackAlloc 1 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_08" ``stack_to_lab$flatten F (StackFree 1 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_09" ``stack_to_lab$flatten F (StackStore 1 2 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_10" ``stack_to_lab$flatten F (StackStoreAny 1 2 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_11" ``stack_to_lab$flatten F (StackLoad 1 2 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_12" ``stack_to_lab$flatten F (StackLoadAny 1 2 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_13" ``stack_to_lab$flatten F (StackGetSize 1 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_14" ``stack_to_lab$flatten F (StackSetSize 1 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_fallback_15" ``stack_to_lab$flatten F (BitmapLoad 1 2 : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_if_both_skip" ``stack_to_lab$flatten F (If Less 3 (Reg 4) Skip Skip : 64 stackLang$prog) 7 2 [] []``;
val _ = emit "native_call_return_only" ``stack_to_lab$flatten F (Call (SOME (Tick,3,8,9)) (INR 4) NONE : 64 stackLang$prog) 7 2 [] []``;
