load "preamble";
load "stackPropsTheory";
open bossLib HolKernel Parse preamble stackPropsTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "forbid_skip" ``let p = (Skip : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_inst" ``let p = (Inst (Const 0 1w) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_get" ``let p = (Get 0 Handler : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_set" ``let p = (Set Handler 0 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_heap" ``let p = (OpCurrHeap Add 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_call_empty" ``let p = (Call NONE (INL 7) NONE : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_seq" ``let p = (Seq Skip Tick : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_if" ``let p = (If Equal 0 (Reg 1) Skip Tick : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_loop" ``let p = (Loop Skip : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_jump" ``let p = (JumpLower 0 1 7 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_alloc" ``let p = (Alloc 3 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_store_consts" ``let p = (StoreConsts 0 1 (SOME 7) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_raise" ``let p = (Raise 0 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_return" ``let p = (Return 0 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_break" ``let p = (Break 7 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_continue" ``let p = (Continue 7 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_ffi" ``let p = (FFI (mlstring$implode "abc") 0 1 2 3 4 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_tick" ``let p = (Tick : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_loc" ``let p = (LocValue 0 7 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_install" ``let p = (Install 0 1 2 3 4 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,T)``;
val _ = out "forbid_shmem" ``let p = (ShMemOp Load 0 (Addr 1 0w) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,F)``;
val _ = out "forbid_code_write" ``let p = (CodeBufferWrite 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_data_write" ``let p = (DataBufferWrite 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_raw_call" ``let p = (RawCall 7 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_alloc" ``let p = (StackAlloc 2 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_free" ``let p = (StackFree 2 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_store" ``let p = (StackStore 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_store_any" ``let p = (StackStoreAny 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_load" ``let p = (StackLoad 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_load_any" ``let p = (StackLoadAny 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_get_size" ``let p = (StackGetSize 0 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_stack_set_size" ``let p = (StackSetSize 0 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_bitmap_load" ``let p = (BitmapLoad 0 1 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_halt" ``let p = (Halt 0 : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_call_handler_install" ``let p = (Call NONE (INR 0) (SOME (Install 0 1 2 3 4,7,5)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,T)``;
val _ = out "forbid_call_handler_shmem" ``let p = (Call NONE (INL 7) (SOME (ShMemOp Store16 0 (Addr 1 0w),7,5)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,F)``;
val _ = out "forbid_call_return_install" ``let p = (Call (SOME (Install 0 1 2 3 4,0,7,1)) (INR 0) NONE : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,T)``;
val _ = out "forbid_call_return_shmem" ``let p = (Call (SOME (ShMemOp Store16 0 (Addr 1 0w),0,7,1)) (INL 7) NONE : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,F)``;
val _ = out "forbid_call_both" ``let p = (Call (SOME (Install 0 1 2 3 4,0,7,1)) (INL 7) (SOME (ShMemOp Store16 0 (Addr 1 0w),7,5)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,F)``;
val _ = out "forbid_call_safe" ``let p = (Call (SOME (Skip,0,7,1)) (INL 7) (SOME (Tick,9,5)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,T)``;
val _ = out "forbid_seq_left" ``let p = (Seq (Install 0 1 2 3 4) Skip : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,T)``;
val _ = out "forbid_seq_right" ``let p = (Seq Skip (ShMemOp Store16 0 (Addr 1 0w)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,F)``;
val _ = out "forbid_if_left" ``let p = (If Equal 0 (Imm 0w) (Install 0 1 2 3 4) Skip : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,T)``;
val _ = out "forbid_if_right" ``let p = (If Equal 0 (Imm 0w) Skip (ShMemOp Store16 0 (Addr 1 0w)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,F)``;
val _ = out "forbid_loop_install" ``let p = (Loop (Install 0 1 2 3 4) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (F,T)``;
val _ = out "forbid_loop_shmem" ``let p = (Loop (ShMemOp Store16 0 (Addr 1 0w)) : 64 stackLang$prog) in (no_install p,no_shmemop p) = (T,F)``;
