load "bossLib"; load "preamble"; load "stackPropsTheory";
open bossLib HolKernel Parse preamble stackPropsTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "get_last" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Get 5 CurrHeap : 8 stackLang$prog)``;
val _ = out "get_bound" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Get 6 CurrHeap : 8 stackLang$prog)``;
val _ = out "set" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Set CurrHeap 1 : 8 stackLang$prog)``;
val _ = out "store_ignored_second" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackStore 1 99 : 8 stackLang$prog)``;
val _ = out "store_first_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackStore 6 1 : 8 stackLang$prog)``;
val _ = out "load_ignored_second" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackLoad 1 99 : 8 stackLang$prog)``;
val _ = out "load_first_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackLoad 6 1 : 8 stackLang$prog)``;
val _ = out "get_size" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackGetSize 1 : 8 stackLang$prog)``;
val _ = out "set_size_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackSetSize 6 : 8 stackLang$prog)``;
val _ = out "heap" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (OpCurrHeap Add 1 2 : 8 stackLang$prog)``;
val _ = out "store_any_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackStoreAny 1 6 : 8 stackLang$prog)``;
val _ = out "load_any" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StackLoadAny 1 2 : 8 stackLang$prog)``;
val _ = out "bitmap_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (BitmapLoad 6 1 : 8 stackLang$prog)``;
val _ = out "consts" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (StoreConsts 1 2 (SOME 99) : 8 stackLang$prog)``;
val _ = out "seq_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Seq (Get 1 CurrHeap) (Get 6 CurrHeap) : 8 stackLang$prog)``;
val _ = out "if_ignored_condition" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (If Equal 99 (Reg 99) Skip Skip : 8 stackLang$prog)``;
val _ = out "loop_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Loop (Get 6 CurrHeap) : 8 stackLang$prog)``;
val _ = out "call_none_ignored" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Call NONE (INR 99) (SOME (Get 6 CurrHeap,3,4)) : 8 stackLang$prog)``;
val _ = out "call_body_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Call (SOME (Get 6 CurrHeap,99,1,2)) (INR 99) NONE : 8 stackLang$prog)``;
val _ = out "call_handler_bad" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Call (SOME (Skip,99,1,2)) (INR 99) (SOME (Get 6 CurrHeap,3,4)) : 8 stackLang$prog)``;
val _ = out "call_both_good" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Call (SOME (Get 1 CurrHeap,99,1,2)) (INR 99) (SOME (Get 2 CurrHeap,3,4)) : 8 stackLang$prog)``;
val _ = out "inst_ignored" ``stack_asm_remove ((c:8 asm$asm_config) with <|reg_count:=8; avoid_regs:=[0;1]|>) (Inst (Const 99 0w) : 8 stackLang$prog)``;
