load "preamble"; load "stack_rawcallProofTheory";
open HolKernel Parse bossLib preamble stack_rawcallProofTheory;
val _ = Globals.linewidth := 1000000;
fun row label theorem = (print(label ^ "="); print_term(concl theorem));
val _ = row "code_info_domain_statement" domain_fromAList_compile;
val _ = print("code_info_domain_hypotheses=" ^ Int.toString(length(hyp domain_fromAList_compile)) ^ "\n");
val _ = row "code_info_domain_case64" (ISPEC ``(codeRows:(num # 64 stackLang$prog) list)`` (GEN_ALL domain_fromAList_compile));
val _ = row "code_info_domain_case80" (ISPEC ``(codeRows:(num # 80 stackLang$prog) list)`` (GEN_ALL domain_fromAList_compile));
val _ = row "code_info_lookup_statement" lookup_collect_info;
val _ = print("code_info_lookup_hypotheses=" ^ Int.toString(length(hyp lookup_collect_info)) ^ "\n");
val _ = row "code_info_lookup_case64" (ISPEC ``(codeRows:(num # 64 stackLang$prog) list)`` (GEN_ALL lookup_collect_info));
val _ = row "code_info_lookup_case80" (ISPEC ``(codeRows:(num # 80 stackLang$prog) list)`` (GEN_ALL lookup_collect_info));
val _ = row "code_info_frames_statement" state_ok_collect_info;
val _ = print("code_info_frames_hypotheses=" ^ Int.toString(length(hyp state_ok_collect_info)) ^ "\n");
val _ = row "code_info_frames_case64" (ISPEC ``(codeRows:(num # 64 stackLang$prog) list)`` (GEN_ALL state_ok_collect_info));
val _ = row "code_info_frames_case80" (ISPEC ``(codeRows:(num # 80 stackLang$prog) list)`` (GEN_ALL state_ok_collect_info));
val _ = row "code_info_duplicate_keys64" (EVAL ``MAP FST (stack_rawcall$compile ([(3,Skip);(5,Skip);(3,StackAlloc 0)]:(num # 64 stackLang$prog) list)) = [3;5;3]``);
val _ = row "code_info_lookup_absent64" (EVAL ``lookup 77 (collect_info ([]:(num # 64 stackLang$prog) list) (insert 3 99 LN)) = NONE``);
val _ = row "code_info_lookup_bare_rest64" (EVAL ``lookup 3 (collect_info ([(3,StackAlloc 4)]:(num # 64 stackLang$prog) list) (insert 3 99 LN)) = SOME 99``);
val _ = row "code_info_lookup_zero64" (EVAL ``lookup 3 (collect_info ([(3,Seq (StackAlloc 0) Skip)]:(num # 64 stackLang$prog) list) (insert 3 99 LN)) = SOME 0``);
val _ = row "code_info_lookup_large64" (EVAL ``lookup 6 (collect_info ([(3,StackAlloc 4);(6,Seq (StackAlloc (2 EXP 70)) Skip)]:(num # 64 stackLang$prog) list) (insert 3 99 LN)) = SOME (2 EXP 70)``);
val frame_result64 = MP (ISPEC ``([(3,Seq (StackAlloc 0) Skip);(5,StackAlloc 4)]:(num # 64 stackLang$prog) list)`` (GEN_ALL state_ok_collect_info)) (EQT_ELIM(EVAL ``ALL_DISTINCT (MAP FST ([(3,Seq (StackAlloc 0) Skip);(5,StackAlloc 4)]:(num # 64 stackLang$prog) list))``));
val _ = row "code_info_frame_application64" frame_result64;
val _ = print("code_info_frame_hypotheses64=" ^ Int.toString(length(hyp frame_result64)) ^ "\n");
val _ = row "code_info_duplicate_keys80" (EVAL ``MAP FST (stack_rawcall$compile ([(3,Skip);(5,Skip);(3,StackAlloc 0)]:(num # 80 stackLang$prog) list)) = [3;5;3]``);
val _ = row "code_info_lookup_absent80" (EVAL ``lookup 77 (collect_info ([]:(num # 80 stackLang$prog) list) (insert 3 99 LN)) = NONE``);
val _ = row "code_info_lookup_bare_rest80" (EVAL ``lookup 3 (collect_info ([(3,StackAlloc 4)]:(num # 80 stackLang$prog) list) (insert 3 99 LN)) = SOME 99``);
val _ = row "code_info_lookup_zero80" (EVAL ``lookup 3 (collect_info ([(3,Seq (StackAlloc 0) Skip)]:(num # 80 stackLang$prog) list) (insert 3 99 LN)) = SOME 0``);
val _ = row "code_info_lookup_large80" (EVAL ``lookup 6 (collect_info ([(3,StackAlloc 4);(6,Seq (StackAlloc (2 EXP 70)) Skip)]:(num # 80 stackLang$prog) list) (insert 3 99 LN)) = SOME (2 EXP 70)``);
val frame_result80 = MP (ISPEC ``([(3,Seq (StackAlloc 0) Skip);(5,StackAlloc 4)]:(num # 80 stackLang$prog) list)`` (GEN_ALL state_ok_collect_info)) (EQT_ELIM(EVAL ``ALL_DISTINCT (MAP FST ([(3,Seq (StackAlloc 0) Skip);(5,StackAlloc 4)]:(num # 80 stackLang$prog) list))``));
val _ = row "code_info_frame_application80" frame_result80;
val _ = print("code_info_frame_hypotheses80=" ^ Int.toString(length(hyp frame_result80)) ^ "\n");
