load "bossLib"; load "preamble"; load "stackPropsTheory";
open bossLib HolKernel Parse preamble stackPropsTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "fpLess" ``fp_name (FPLess 1 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpLessEqual" ``fp_name (FPLessEqual 1 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpEqual" ``fp_name (FPEqual 1 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpAbs" ``fp_name (FPAbs 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpAbs_alias" ``fp_name (FPAbs 0 0) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpNeg" ``fp_name (FPNeg 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpNeg_alias" ``fp_name (FPNeg 0 0) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpSqrt" ``fp_name (FPSqrt 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpMov" ``fp_name (FPMov 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpToInt" ``fp_name (FPToInt 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpFromInt" ``fp_name (FPFromInt 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpAdd" ``fp_name (FPAdd 0 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpSub" ``fp_name (FPSub 0 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpMul" ``fp_name (FPMul 0 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpDiv" ``fp_name (FPDiv 0 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "binary_mismatch" ``fp_name (FPAdd 0 1 2) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "binary_three_reg" ``fp_name (FPAdd 0 1 2) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := F|>)``;
val _ = out "fma_arm" ``fp_name (FPFma 0 1 2) ((c:64 asm$asm_config) with <|ISA := asm$ARMv7; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fma_riscv" ``fp_name (FPFma 0 1 2) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fma_count2" ``fp_name (FPFma 0 1 1) ((c:64 asm$asm_config) with <|ISA := asm$ARMv7; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 2; two_reg_arith := T|>)``;
val _ = out "fpMovToReg_32" ``fp_name (FPMovToReg 1 2 0) ((c:32 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fpMovFromReg_32" ``fp_name (FPMovFromReg 0 1 2) ((c:32 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "move32_alias" ``fp_name (FPMovToReg 1 1 0) ((c:32 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "move32_bound" ``fp_name (FPMovFromReg 0 1 6) ((c:32 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "move64_ignored" ``fp_name (FPMovToReg 1 99 0) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "fp_bound" ``fp_name (FPSqrt 0 4) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
val _ = out "logical_bound" ``fp_name (FPLess 6 0 1) ((c:64 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := [0;1]; fp_reg_count := 4; two_reg_arith := T|>)``;
