load "preamble";
load "stack_removeTheory";
open bossLib HolKernel Parse preamble stack_removeTheory;
val _ = Globals.linewidth := 10000;
val _ = print ("prog_comp_full_def=" ^ term_to_string (concl prog_comp_def) ^ "\n");
val _ = print ("prog_comp_type=" ^ type_to_string (type_of ``prog_comp``) ^ "\n");
fun emit label q = print (label ^ "=" ^ term_to_string (rconc (EVAL q)) ^ "\n");
val _ = emit "wrapper_1_bool" ``prog_comp T (0w,0w) 24 (T,StackFree 256) : bool # 1 stackLang$prog``;
val _ = emit "wrapper_1_list" ``prog_comp T (0w,0w) 24 (([T;F] : bool list),StackFree 256) : bool list # 1 stackLang$prog``;
val _ = emit "wrapper_1_nat" ``prog_comp T (0w,0w) 24 (1234,StackFree 256) : num # 1 stackLang$prog``;
val _ = emit "wrapper_8_bool" ``prog_comp T (0w,0w) 24 (T,StackFree 256) : bool # 8 stackLang$prog``;
val _ = emit "wrapper_8_list" ``prog_comp T (0w,0w) 24 (([T;F] : bool list),StackFree 256) : bool list # 8 stackLang$prog``;
val _ = emit "wrapper_8_nat" ``prog_comp T (0w,0w) 24 (1234,StackFree 256) : num # 8 stackLang$prog``;
val _ = emit "wrapper_32_bool" ``prog_comp T (0w,0w) 24 (T,StackFree 256) : bool # 32 stackLang$prog``;
val _ = emit "wrapper_32_list" ``prog_comp T (0w,0w) 24 (([T;F] : bool list),StackFree 256) : bool list # 32 stackLang$prog``;
val _ = emit "wrapper_32_nat" ``prog_comp T (0w,0w) 24 (1234,StackFree 256) : num # 32 stackLang$prog``;
val _ = emit "wrapper_64_bool" ``prog_comp T (0w,0w) 24 (T,StackFree 256) : bool # 64 stackLang$prog``;
val _ = emit "wrapper_64_list" ``prog_comp T (0w,0w) 24 (([T;F] : bool list),StackFree 256) : bool list # 64 stackLang$prog``;
val _ = emit "wrapper_64_nat" ``prog_comp T (0w,0w) 24 (1234,StackFree 256) : num # 64 stackLang$prog``;
val _ = emit "wrapper_80_bool" ``prog_comp T (0w,0w) 24 (T,StackFree 256) : bool # 80 stackLang$prog``;
val _ = emit "wrapper_80_list" ``prog_comp T (0w,0w) 24 (([T;F] : bool list),StackFree 256) : bool list # 80 stackLang$prog``;
val _ = emit "wrapper_80_nat" ``prog_comp T (0w,0w) 24 (1234,StackFree 256) : num # 80 stackLang$prog``;
