load "preamble"; load "stack_namesTheory";
open bossLib HolKernel Parse preamble stack_namesTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val names = ``sptree$insert 3 7 sptree$LN : num num_map``;
val _ = out "seq" ``comp ^names (Seq (Halt 3) (Return 4) : 8 stackLang$prog)``;
val _ = out "if" ``comp ^names (If Equal 3 (Reg 3) (Raise 3) (Break 3) : 8 stackLang$prog)``;
val _ = out "loop" ``comp ^names (Loop (Inst (Const 3 255w)) : 8 stackLang$prog)``;
val _ = out "call_none" ``comp ^names (Call NONE (INR 3) NONE : 8 stackLang$prog)``;
val _ = out "call_ret" ``comp ^names (Call (SOME (Return 3,3,8,9)) (INL 3) NONE : 8 stackLang$prog)``;
val _ = out "call_exc" ``comp ^names (Call NONE (INR 4) (SOME (Raise 3,8,9)) : 8 stackLang$prog)``;
val _ = out "call_both" ``comp ^names (Call (SOME (Return 3,3,8,9)) (INR 3) (SOME (Raise 3,6,7)) : 8 stackLang$prog)``;
val _ = out "install" ``comp ^names (Install 3 4 3 4 3 : 8 stackLang$prog)``;
val _ = out "shared" ``comp ^names (ShMemOp Load 3 (Addr 3 255w) : 8 stackLang$prog)``;
val _ = out "buffer" ``comp ^names (CodeBufferWrite 3 4 : 8 stackLang$prog)``;
val _ = out "jump" ``comp ^names (JumpLower 3 4 3 : 8 stackLang$prog)``;
val _ = out "loc" ``comp ^names (LocValue 3 3 4 : 8 stackLang$prog)``;
val _ = out "continue" ``comp ^names (Continue 3 : 8 stackLang$prog)``;
val _ = out "default" ``comp ^names (Tick : 8 stackLang$prog)``;
val _ = out "compile" ``compile ^names [(8,Halt 3);(9,Return 4)] : (num # 8 stackLang$prog) list``;
