load "preamble";
load "stack_removeTheory";
open bossLib HolKernel Parse preamble stack_removeTheory;
val _ = Globals.linewidth := 10000;
fun emit label q = print (label ^ "=" ^ term_to_string (rconc (EVAL q)) ^ "\n");
val _ = print ("store_pos_full_def=" ^ term_to_string (concl store_pos_def) ^ "\n");
val _ = print ("store_pos_type=" ^ type_to_string (type_of ``store_pos``) ^ "\n");
val _ = print ("store_offset_full_def=" ^ term_to_string (concl store_offset_def) ^ "\n");
val _ = print ("store_offset_type=" ^ type_to_string (type_of ``store_offset``) ^ "\n");
val _ = emit "position_0" ``store_pos (NextFree)``;
val _ = emit "position_1" ``store_pos (EndOfHeap)``;
val _ = emit "position_2" ``store_pos (HeapLength)``;
val _ = emit "position_3" ``store_pos (OtherHeap)``;
val _ = emit "position_4" ``store_pos (TriggerGC)``;
val _ = emit "position_5" ``store_pos (AllocSize)``;
val _ = emit "position_6" ``store_pos (Handler)``;
val _ = emit "position_7" ``store_pos (Globals)``;
val _ = emit "position_8" ``store_pos (GlobReal)``;
val _ = emit "position_9" ``store_pos (ProgStart)``;
val _ = emit "position_10" ``store_pos (BitmapBase)``;
val _ = emit "position_11" ``store_pos (GenStart)``;
val _ = emit "position_12" ``store_pos (CodeBuffer)``;
val _ = emit "position_13" ``store_pos (CodeBufferEnd)``;
val _ = emit "position_14" ``store_pos (BitmapBuffer)``;
val _ = emit "position_15" ``store_pos (BitmapBufferEnd)``;
val _ = emit "position_16" ``store_pos (Temp 0w)``;
val _ = emit "position_17" ``store_pos (Temp 1w)``;
val _ = emit "position_18" ``store_pos (Temp 2w)``;
val _ = emit "position_19" ``store_pos (Temp 3w)``;
val _ = emit "position_20" ``store_pos (Temp 4w)``;
val _ = emit "position_21" ``store_pos (Temp 5w)``;
val _ = emit "position_22" ``store_pos (Temp 6w)``;
val _ = emit "position_23" ``store_pos (Temp 7w)``;
val _ = emit "position_24" ``store_pos (Temp 8w)``;
val _ = emit "position_25" ``store_pos (Temp 9w)``;
val _ = emit "position_26" ``store_pos (Temp 10w)``;
val _ = emit "position_27" ``store_pos (Temp 11w)``;
val _ = emit "position_28" ``store_pos (Temp 12w)``;
val _ = emit "position_29" ``store_pos (Temp 13w)``;
val _ = emit "position_30" ``store_pos (Temp 14w)``;
val _ = emit "position_31" ``store_pos (Temp 15w)``;
val _ = emit "position_32" ``store_pos (Temp 16w)``;
val _ = emit "position_33" ``store_pos (Temp 17w)``;
val _ = emit "position_34" ``store_pos (Temp 18w)``;
val _ = emit "position_35" ``store_pos (Temp 19w)``;
val _ = emit "position_36" ``store_pos (Temp 20w)``;
val _ = emit "position_37" ``store_pos (Temp 21w)``;
val _ = emit "position_38" ``store_pos (Temp 22w)``;
val _ = emit "position_39" ``store_pos (Temp 23w)``;
val _ = emit "position_40" ``store_pos (Temp 24w)``;
val _ = emit "position_41" ``store_pos (Temp 25w)``;
val _ = emit "position_42" ``store_pos (Temp 26w)``;
val _ = emit "position_43" ``store_pos (Temp 27w)``;
val _ = emit "position_44" ``store_pos (Temp 28w)``;
val _ = emit "position_45" ``store_pos (Temp 29w)``;
val _ = emit "position_46" ``store_pos (Temp 30w)``;
val _ = emit "position_47" ``store_pos (Temp 31w)``;
val _ = emit "position_48" ``store_pos (CurrHeap)``;
val _ = emit "offset_1_0" ``store_offset (NextFree) : 1 word``;
val _ = emit "offset_1_10" ``store_offset (BitmapBase) : 1 word``;
val _ = emit "offset_1_15" ``store_offset (BitmapBufferEnd) : 1 word``;
val _ = emit "offset_1_16" ``store_offset (Temp 0w) : 1 word``;
val _ = emit "offset_1_47" ``store_offset (Temp 31w) : 1 word``;
val _ = emit "offset_1_48" ``store_offset (CurrHeap) : 1 word``;
val _ = emit "offset_8_0" ``store_offset (NextFree) : 8 word``;
val _ = emit "offset_8_10" ``store_offset (BitmapBase) : 8 word``;
val _ = emit "offset_8_15" ``store_offset (BitmapBufferEnd) : 8 word``;
val _ = emit "offset_8_16" ``store_offset (Temp 0w) : 8 word``;
val _ = emit "offset_8_47" ``store_offset (Temp 31w) : 8 word``;
val _ = emit "offset_8_48" ``store_offset (CurrHeap) : 8 word``;
val _ = emit "offset_32_0" ``store_offset (NextFree) : 32 word``;
val _ = emit "offset_32_10" ``store_offset (BitmapBase) : 32 word``;
val _ = emit "offset_32_15" ``store_offset (BitmapBufferEnd) : 32 word``;
val _ = emit "offset_32_16" ``store_offset (Temp 0w) : 32 word``;
val _ = emit "offset_32_47" ``store_offset (Temp 31w) : 32 word``;
val _ = emit "offset_32_48" ``store_offset (CurrHeap) : 32 word``;
val _ = emit "offset_64_0" ``store_offset (NextFree) : 64 word``;
val _ = emit "offset_64_10" ``store_offset (BitmapBase) : 64 word``;
val _ = emit "offset_64_15" ``store_offset (BitmapBufferEnd) : 64 word``;
val _ = emit "offset_64_16" ``store_offset (Temp 0w) : 64 word``;
val _ = emit "offset_64_47" ``store_offset (Temp 31w) : 64 word``;
val _ = emit "offset_64_48" ``store_offset (CurrHeap) : 64 word``;
val _ = emit "offset_80_0" ``store_offset (NextFree) : 80 word``;
val _ = emit "offset_80_10" ``store_offset (BitmapBase) : 80 word``;
val _ = emit "offset_80_15" ``store_offset (BitmapBufferEnd) : 80 word``;
val _ = emit "offset_80_16" ``store_offset (Temp 0w) : 80 word``;
val _ = emit "offset_80_47" ``store_offset (Temp 31w) : 80 word``;
val _ = emit "offset_80_48" ``store_offset (CurrHeap) : 80 word``;
