load "bossLib"; load "preamble"; load "stackPropsTheory";
open bossLib HolKernel Parse preamble stackPropsTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "or_exception" ``arith_name (Binop Or 1 2 (Reg 2) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "or_wrong" ``arith_name (Binop Or 1 2 (Reg 3) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "binop_two" ``arith_name (Binop Add 1 2 (Reg 2) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "binop_same" ``arith_name (Binop Add 1 1 (Reg 2) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "imm_valid" ``arith_name (Binop Add 1 1 (Imm 7w) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "shift_zero_lsl" ``arith_name (Shift Lsl 1 1 (Imm 0w) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "shift_zero_lsr" ``arith_name (Shift Lsr 1 1 (Imm 0w) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "shift_width" ``arith_name (Shift Lsl 1 1 (Imm 8w) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "shift_x86_4" ``arith_name (Shift Lsl 1 1 (Reg 4) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "shift_x86_1" ``arith_name (Shift Lsl 1 1 (Reg 1) : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := T; valid_imm := (\op w. T)|>)``;
val _ = out "div_riscv" ``arith_name (Div 1 2 3 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "div_x86" ``arith_name (Div 1 2 3 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "mul_x86_3" ``arith_name (LongMul 3 0 0 4 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "mul_x86_2" ``arith_name (LongMul 2 0 0 4 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "mul_arm_alias" ``arith_name (LongMul 1 1 2 3 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$ARMv7; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "mul_riscv_alias" ``arith_name (LongMul 1 2 1 3 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "longdiv_3" ``arith_name (LongDiv 0 3 3 0 4 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "longdiv_2" ``arith_name (LongDiv 0 2 2 0 4 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$x86_64; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "carry_good" ``arith_name (AddCarry 1 2 3 4 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "carry_alias" ``arith_name (AddCarry 1 2 3 1 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "addoverflow_right_alias" ``arith_name (AddOverflow 1 2 3 1 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
val _ = out "suboverflow_left_alias" ``arith_name (SubOverflow 1 2 1 3 : 8 asm$arith) ((c:8 asm$asm_config) with <|ISA := asm$RISC_V; reg_count := 8; avoid_regs := []; two_reg_arith := F; valid_imm := (\op w. T)|>)``;
