load "preamble";
load "targetPropsTheory";
open simpLib boolLib bossLib HolKernel Parse preamble targetSemTheory targetPropsTheory;
fun out label q = let val th = CONV_RULE (RAND_CONV (SIMP_CONV (srw_ss()) [pred_setTheory.IN_APP])) (EVAL q) in
 if aconv(rconc th) ``T`` andalso null(hyp th) then print(label ^ "=T\n")
 else (print_thm th; raise Fail label) end;
val _ = print ("search_type=" ^ type_to_string(type_of ``find_next_interference``) ^ "\n");
val _ = if null(hyp find_next_interference_def) then
 (print "search_full_definition="; print_term(concl find_next_interference_def); print "\n")
 else raise Fail "definition hypotheses";
val _ = out "search_unknown" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[];halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = out "search_halt_success" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[];halt_pc:=0w;ccache_pc:=2w;target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = out "search_halt_resource" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[];halt_pc:=0w;ccache_pc:=2w;target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 9w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = out "search_shared_missing" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedRead];mmio_info:=[];halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = out "search_external_mmio" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[ExtCall «x»];mmio_info:=[(0,1w,Addr 0 0w,0,0w)];halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = out "search_normal_priority_encoding_fail" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=UNIV;ffi_entry_pcs:=[];halt_pc:=0w;ccache_pc:=2w;target:=(mc.target with <|config:=mc.target.config with encode:=(\i. []);get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val encoded_zero = prove (
  ``encoded_bytes_in_mem ((c:8 asm_config) with <|encode:=(\i. [0w]);code_alignment:=0|>) 0w (\a. 0w) UNIV``,
  REWRITE_TAC [encoded_bytes_in_mem_def] >> qexists_tac `Inst Skip` >> qexists_tac `0` >> EVAL_TAC);
val encoded_zero_norm = CONV_RULE EVAL encoded_zero;
fun normalOut label q = (print(label ^ "="); print_term(rconc(CONV_RULE (RAND_CONV (SIMP_CONV (srw_ss()) [encoded_zero_norm, pred_setTheory.IN_APP])) (EVAL q))); print "\n");
val _ = normalOut "search_normal_success" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=UNIV;ffi_entry_pcs:=[];halt_pc:=0w;next_interfer:=(\n ms. ms+n+10);ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with <|encode:=(\i. [0w]);code_alignment:=0|>);get_byte:=(\ms a. 0w);next:=(\ms. ms+1);state_ok:=(\ms. T);get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = normalOut "search_normal_shift" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=UNIV;ffi_entry_pcs:=[];halt_pc:=0w;next_interfer:=(\n ms. ms+n+10);ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with <|encode:=(\i. [0w]);code_alignment:=0|>);get_byte:=(\ms a. 0w);next:=(\ms. ms+1);state_ok:=(\ms. T);get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 2 7 = NONE``;
val _ = normalOut "search_normal_guard_rollback" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=UNIV;ffi_entry_pcs:=[];halt_pc:=0w;next_interfer:=(\n ms. ms+n+10);ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with <|encode:=(\i. [0w]);code_alignment:=0|>);get_byte:=(\ms a. 0w);next:=(\ms. ms+1);state_ok:=(\ms. ms<>18);get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (ffi:num ffi_state) 1 7 = NONE``;
val _ = out "search_mm_unshared" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedRead];mmio_info:=[(0,0w,Addr 0 0w,0,0w)];shared_addresses:=EMPTY;ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with encode:=(\i. []));get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (((ffi:num ffi_state) with <|oracle:=(\name st conf bytes. Oracle_return (st+1) bytes);ffi_state:=9;io_events:=[]|>)) 1 7 = NONE``;
val _ = out "search_mm_invalid_size" ``find_next_interference (((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedRead];mmio_info:=[(0,3w,Addr 0 0w,0,0w)];shared_addresses:=UNIV;ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with encode:=(\i. []));get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>)) (((ffi:num ffi_state) with <|oracle:=(\name st conf bytes. Oracle_return (st+1) bytes);ffi_state:=9;io_events:=[]|>)) 1 7 = NONE``;
val _ = out "search_cache_full" ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[];halt_pc:=1w;ccache_pc:=0w;ccache_interfer:=(\n (p,l,ms). ms+n+10);target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>) in find_next_interference c (ffi:num ffi_state) 1 7 = SOME(CcApp 0w 0w 7 17, c with ccache_interfer := shift_seq 1 c.ccache_interfer, ffi)``;
val _ = out "search_zero" ``find_next_interference (mc:(8,num,num)machine_config) (ffi:num ffi_state) 0 7 = NONE``;
val _ = out "search_mm_read_full" ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedRead];mmio_info:=[(0,0w,Addr 0 0w,0,0w)];shared_addresses:=UNIV;ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with encode:=(\i. []));get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>); f = ((ffi:num ffi_state) with <|oracle:=(\name st conf bytes. Oracle_return (st+1) bytes);ffi_state:=9;io_events:=[]|>) in find_next_interference c f 1 7 = SOME(FfiApp 0 [0w] 7 17, c with ffi_interfer := shift_seq 1 c.ffi_interfer, f with <|ffi_state:=10;io_events:=[IO_event (SharedMem MappedRead) [0w] (ZIP([0w],[0w]))]|>)``;
val _ = out "search_mm_final" ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedRead];mmio_info:=[(0,0w,Addr 0 0w,0,0w)];shared_addresses:=UNIV;ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with encode:=(\i. []));get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>); f = ((ffi:num ffi_state) with <|oracle:=(\name st conf bytes. Oracle_final FFI_failed);ffi_state:=9;io_events:=[]|>) in find_next_interference c f 1 7 = NONE``;
val _ = out "search_mm_write_full" ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedWrite];mmio_info:=[(0,0w,Addr 0 0w,0,0w)];shared_addresses:=UNIV;ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with encode:=(\i. []));get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>); f = ((ffi:num ffi_state) with <|oracle:=(\name st conf bytes. Oracle_return (st+1) bytes);ffi_state:=9;io_events:=[]|>) in find_next_interference c f 1 7 = SOME(FfiApp 0 [0w;0w] 7 17, c with ffi_interfer := shift_seq 1 c.ffi_interfer, f with <|ffi_state:=10;io_events:=[IO_event (SharedMem MappedWrite) [0w] (ZIP([0w;0w],[0w;0w]))]|>)``;
val _ = out "search_mm_write_narrow_full" ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[SharedMem MappedWrite];mmio_info:=[(0,1w,Addr 0 0w,0,0w)];shared_addresses:=UNIV;ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|config:=(mc.target.config with encode:=(\i. []));get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>); f = ((ffi:num ffi_state) with <|oracle:=(\name st conf bytes. Oracle_return (st+1) bytes);ffi_state:=9;io_events:=[]|>) in find_next_interference c f 1 7 = SOME(FfiApp 0 [0w;0w] 7 17, c with ffi_interfer := shift_seq 1 c.ffi_interfer, f with <|ffi_state:=10;io_events:=[IO_event (SharedMem MappedWrite) [1w] (ZIP([0w;0w],[0w;0w]))]|>)``;
val _ = out "search_empty_external_full" ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:=EMPTY;ffi_entry_pcs:=[0w];ffi_names:=[ExtCall «»];mmio_info:=[];ffi_interfer:=(\n (i,b,ms). ms+n+10);halt_pc:=1w;ccache_pc:=2w;target:=(mc.target with <|get_pc:=(\ms. 0w);get_reg:=(\ms r. 0w)|>)|>) in find_next_interference c (ffi:num ffi_state) 1 7 = SOME(FfiApp 0 [] 7 17, c with ffi_interfer := shift_seq 1 c.ffi_interfer, ffi)``;
val encoded_singleton = prove (``encoded_bytes_in_mem ((c:8 asm_config) with <|encode:=(\i. [0w]);code_alignment:=0|>) 0w (\a. 0w) {0w}``, REWRITE_TAC [encoded_bytes_in_mem_def] >> qexists_tac `Inst Skip` >> qexists_tac `0` >> EVAL_TAC);
val encoded_singleton_norm = CONV_RULE EVAL encoded_singleton;
val _ = let val th = CONV_RULE (RAND_CONV (SIMP_CONV (srw_ss()) [encoded_singleton_norm,pred_setTheory.IN_APP])) (EVAL ``let c = ((mc:(8,num,num)machine_config) with <|prog_addresses:={0w};ffi_entry_pcs:=[];halt_pc:=1w;next_interfer:=(\n ms. ms+n+10);ccache_pc:=2w;ccache_interfer:=(\n (p,l,ms). ms+n+10);target:=(mc.target with <|config:=(mc.target.config with <|encode:=(\i. [0w]);code_alignment:=0|>);get_byte:=(\ms a. 0w);next:=(\ms. ms+1);state_ok:=(\ms. T);get_pc:=(\ms. if ms < 10 then 0w else 2w);get_reg:=(\ms r. 0w)|>)|>) in find_next_interference c (ffi:num ffi_state) 2 7 = SOME(CcApp 0w 0w 18 28, c with <|next_interfer := shift_seq 1 c.next_interfer; ccache_interfer := shift_seq 1 c.ccache_interfer|>, ffi)``) in
 if aconv(rconc th) ``T`` andalso null(hyp th) then print "search_normal_to_cache_full=T\n" else (print_thm th; raise Fail "normal_to_cache") end;
val _ = OS.Process.exit OS.Process.success;
