load "preamble";
load "word_allocProofTheory";
open bossLib HolKernel Parse preamble word_allocTheory word_allocProofTheory wordLangTheory reg_allocTheory sptreeTheory;
val _ = Globals.linewidth := 1000;
val _ = (print "lv_original_definition="; print_thm (DB.fetch "word_alloc" "limit_var_def"); print "\n");
val _ = print ("lv_original_type=" ^ type_to_string(type_of ``limit_var``) ^ "\n");
fun out label q = (print(label ^ "=");print_term(rconc(EVAL q));print "\n");
val _ = out "lv_residue0" ``let p = (Assign 0 (Const 0w):32 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_residue1" ``let p = (Assign 1 (Const 0w):32 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_residue2" ``let p = (Assign 2 (Const 0w):32 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_residue3" ``let p = (Assign 3 (Const 0w):32 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_residue4" ``let p = (Assign 4 (Const 0w):32 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_skip1" ``let p = (Skip:1 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_seven" ``let p = (Assign 7 (Const 0w):64 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_eight" ``let p = (Assign 8 (Const 0w):80 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_ignored16" ``let p = (Inst (Mem Load16 999 (Addr 777 3w)):64 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_tail_handler" ``let p = (Call NONE (SOME 999) [] (SOME (1000,Assign 1001 (Var 1002),1003,1004)):32 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_call_body" ``let p = (Call (SOME ([1],(LN,LN),Assign 26 (Const 0w),7,8)) (SOME 0) [] NONE:64 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
val _ = out "lv_huge" ``let p = (Assign 1208925819614629174706176 (Var 7):1 wordLang$prog) in (max_var p,limit_var p,is_alloc_var (limit_var p),every_var (\x.x<limit_var p) p)``;
