load "preamble";
load "word_to_stackProofTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory word_to_stackProofTheory stackPropsTheory wordConvsTheory;
val _ = Globals.linewidth := 1000;
val _ = (print "pl_full=";print_thm compile_word_to_stack_no_share_inst;print "\n");
fun typ label t = (print(label ^ "=");print_type(type_of t);print "\n");
val _ = typ "pl_conf_type" ``(ac:'a asm$asm_config)``;
val _ = typ "pl_perf_type" ``(perf:bool)``;
val _ = typ "pl_register_type" ``(k:num)``;
val _ = typ "pl_source_type" ``(prog:('b # num # 'a wordLang$prog) list)``;
val _ = typ "pl_bitmap_type" ``(bs:'a word app_list # num)``;
val _ = typ "pl_outputs_type" ``(prog':('b # 'a stackLang$prog) list)``;
val _ = typ "pl_frames_type" ``(fs':num list)``;
val _ = typ "pl_residual_type" ``(bs':'a word app_list # num)``;
fun out label q = (print(label ^ "=");print_term(rconc(EVAL q));print "\n");
val _ = out "pl_empty_1" ``let ps = ([]:(bool # num # 1 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:1 asm$asm_config) F 0 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_safe_1" ``let ps = ([(T,0,wordLang$Skip);(T,999,Seq (Alloc 999 (BS LN () LN,BN LN LN)) (StoreConsts 0 1 2 3 [(T,7w);(F,8w)]));(F,7,wordLang$Return 0 [2;4])]:(bool # num # 1 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:1 asm$asm_config) F 0 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_ignored_1" ``let ps = ([(F,17,wordLang$Call NONE NONE [999] (SOME (999,ShareInst Load 0 (Var 3),7,9)))]:(bool # num # 1 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:1 asm$asm_config) F 0 ps (Append (List [4w]) (List [7w]),17)))) = (F,T)``;
val _ = out "pl_shared_1" ``let ps = ([(T,0,ShareInst Load 0 (Var 3))]:(bool # num # 1 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:1 asm$asm_config) F 0 ps (Append (List [4w]) (List [7w]),17)))) = (F,F)``;
val _ = out "pl_empty_32" ``let ps = ([]:(bool # num # 32 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:32 asm$asm_config) T 2 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_safe_32" ``let ps = ([(T,0,wordLang$Skip);(T,999,Seq (Alloc 999 (BS LN () LN,BN LN LN)) (StoreConsts 0 1 2 3 [(T,7w);(F,8w)]));(F,7,wordLang$Return 0 [2;4])]:(bool # num # 32 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:32 asm$asm_config) T 2 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_ignored_32" ``let ps = ([(F,17,wordLang$Call NONE NONE [999] (SOME (999,ShareInst Load 0 (Var 3),7,9)))]:(bool # num # 32 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:32 asm$asm_config) T 2 ps (Append (List [4w]) (List [7w]),17)))) = (F,T)``;
val _ = out "pl_shared_32" ``let ps = ([(T,0,ShareInst Load 0 (Var 3))]:(bool # num # 32 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:32 asm$asm_config) T 2 ps (Append (List [4w]) (List [7w]),17)))) = (F,F)``;
val _ = out "pl_empty_64" ``let ps = ([]:(bool # num # 64 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:64 asm$asm_config) F 64 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_safe_64" ``let ps = ([(T,0,wordLang$Skip);(T,999,Seq (Alloc 999 (BS LN () LN,BN LN LN)) (StoreConsts 0 1 2 3 [(T,7w);(F,8w)]));(F,7,wordLang$Return 0 [2;4])]:(bool # num # 64 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:64 asm$asm_config) F 64 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_ignored_64" ``let ps = ([(F,17,wordLang$Call NONE NONE [999] (SOME (999,ShareInst Load 0 (Var 3),7,9)))]:(bool # num # 64 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:64 asm$asm_config) F 64 ps (Append (List [4w]) (List [7w]),17)))) = (F,T)``;
val _ = out "pl_shared_64" ``let ps = ([(T,0,ShareInst Load 0 (Var 3))]:(bool # num # 64 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:64 asm$asm_config) F 64 ps (Append (List [4w]) (List [7w]),17)))) = (F,F)``;
val _ = out "pl_empty_80" ``let ps = ([]:(bool # num # 80 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:80 asm$asm_config) T 999 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_safe_80" ``let ps = ([(T,0,wordLang$Skip);(T,999,Seq (Alloc 999 (BS LN () LN,BN LN LN)) (StoreConsts 0 1 2 3 [(T,7w);(F,8w)]));(F,7,wordLang$Return 0 [2;4])]:(bool # num # 80 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:80 asm$asm_config) T 999 ps (Append (List [4w]) (List [7w]),17)))) = (T,T)``;
val _ = out "pl_ignored_80" ``let ps = ([(F,17,wordLang$Call NONE NONE [999] (SOME (999,ShareInst Load 0 (Var 3),7,9)))]:(bool # num # 80 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:80 asm$asm_config) T 999 ps (Append (List [4w]) (List [7w]),17)))) = (F,T)``;
val _ = out "pl_shared_80" ``let ps = ([(T,0,ShareInst Load 0 (Var 3))]:(bool # num # 80 wordLang$prog) list) in (EVERY (\(n,m,p). no_share_inst p) ps,EVERY (\(n,p). no_shmemop p) (FST (compile_word_to_stack (c:80 asm$asm_config) T 999 ps (Append (List [4w]) (List [7w]),17)))) = (F,F)``;
