load "bossLib"; load "preamble"; load "word_allocTheory";
open HolKernel Parse bossLib preamble word_allocTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val f = ``\n:num. n + 10``;
val l16 = ``wordLang$Inst (Mem Load16 3 (Addr 5 7w)) : 8 wordLang$prog``;
val s16 = ``wordLang$Inst (Mem Store16 3 (Addr 5 7w)) : 8 wordLang$prog``;
val _ = out "cd_load16" ``apply_colour ^f ^l16 = ^l16``;
val _ = out "cd_store16" ``apply_colour ^f ^s16 = ^s16``;
val _ = out "cd_load8" ``apply_colour ^f (wordLang$Inst (Mem Load8 3 (Addr 5 7w)) : 8 wordLang$prog) = wordLang$Inst (Mem Load8 13 (Addr 15 7w))``;
val _ = out "cd_store32" ``apply_colour ^f (wordLang$Inst (Mem Store32 3 (Addr 5 7w)) : 8 wordLang$prog) = wordLang$Inst (Mem Store32 13 (Addr 15 7w))``;
val _ = out "cd_carry" ``apply_colour ^f (wordLang$Inst (Arith (AddCarry 1 2 3 4)) : 8 wordLang$prog) = wordLang$Inst (Arith (AddCarry 11 12 13 14))``;
val _ = out "cd_collision" ``apply_colour (\n:num. 0) (wordLang$Inst (Const 3 7w) : 8 wordLang$prog) = wordLang$Inst (Const 0 7w)``;
val _ = out "cd_seq" ``apply_colour ^f (wordLang$Seq (wordLang$Inst (Const 3 7w)) (wordLang$Raise 5) : 8 wordLang$prog) = wordLang$Seq (wordLang$Inst (Const 13 7w)) (wordLang$Raise 15)``;
val _ = out "cd_must" ``apply_colour ^f (wordLang$MustTerminate ^l16) = wordLang$MustTerminate ^l16``;
val _ = out "cd_if" ``apply_colour ^f (wordLang$If Equal 3 (Reg 5) ^l16 (wordLang$Inst (Const 2 7w))) = wordLang$If Equal 13 (Reg 15) ^l16 (wordLang$Inst (Const 12 7w))``;
val _ = out "cd_loop" ``apply_colour ^f (wordLang$Loop LN ^l16 LN) = wordLang$Loop LN ^l16 LN``;
val _ = out "cd_tail_handler" ``apply_colour ^f (wordLang$Call NONE NONE [3] (SOME (5,^l16,7,9))) = wordLang$Call NONE NONE [13] (SOME (15,^l16,7,9))``;
val _ = out "cd_both" ``apply_colour ^f (wordLang$Call (SOME ([3],(LN,LN),wordLang$Inst (Const 2 7w),19,23)) (SOME 17) [5] (SOME (7,^s16,29,31))) = wordLang$Call (SOME ([13],(LN,LN),wordLang$Inst (Const 12 7w),19,23)) (SOME 17) [15] (SOME (17,^s16,29,31))``;
val _ = out "cd_large" ``apply_colour (\n:num. 1208925819614629174706176 + n) (wordLang$Inst (Const 3 7w) : 8 wordLang$prog) = wordLang$Inst (Const 1208925819614629174706179 7w)``;
