load "wordConvsProofTheory";
open HolKernel Parse bossLib wordConvsProofTheory;
val _ = Globals.linewidth := 1000000;
fun pr_stmt label th = (print (label ^ "="); print_term (concl th); print "\n");
fun pr_hyps label th = (print (label ^ "="); print (Int.toString (length (hyp th))); print "\n");
fun pr_typed label th = (print (label ^ "="); Lib.with_flag (Globals.show_types, true) print_term (concl th); print "\n");
val _ = pr_stmt "word_good_handlers_word_to_word_incr_statement" word_good_handlers_word_to_word_incr;
val _ = pr_hyps "word_good_handlers_word_to_word_incr_hypotheses" word_good_handlers_word_to_word_incr;
val _ = pr_typed "word_good_handlers_word_to_word_incr_typed" word_good_handlers_word_to_word_incr;
val _ = pr_stmt "word_good_handlers_word_to_word_statement" word_good_handlers_word_to_word;
val _ = pr_hyps "word_good_handlers_word_to_word_hypotheses" word_good_handlers_word_to_word;
val _ = pr_typed "word_good_handlers_word_to_word_typed" word_good_handlers_word_to_word;
