load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory word_to_stackTheory arithmeticTheory listTheory;
val _ = Globals.linewidth := 4000;
val DIV_ADD_1 = prove(``0 < d ==> (m DIV d + 1 = (m + d) DIV d)``,   rpt strip_tac
  \\ ASSUME_TAC (ADD_DIV_ADD_DIV |> Q.SPECL [`d`] |> UNDISCH
      |> Q.SPECL [`1`,`m`] |> ONCE_REWRITE_RULE [ADD_COMM]) \\ fs []);
val _ = (if null(hyp DIV_ADD_1) then () else raise Fail "open premise"; print "wl_full_DIV_ADD_1="; print_thm DIV_ADD_1; print "\n");
val LENGTH_word_list_lemma = prove(``!xs d. 0 < d ==> (LENGTH (word_list xs d) = (LENGTH xs - 1) DIV d + 1)``,   recInduct word_list_ind
  \\ rpt strip_tac \\ fsrw_tac[] []
  \\ once_rewrite_tac [word_list_def] \\ fsrw_tac[] [] \\ rw []
  \\ imp_res_tac ZERO_DIV \\ fsrw_tac[] [] \\ res_tac
  \\ imp_res_tac LESS_DIV_EQ_ZERO \\ fsrw_tac[] []
  \\ fsrw_tac[] [ADD1] \\ fsrw_tac[] [NOT_LESS]
  \\ imp_res_tac (ONCE_REWRITE_RULE [ADD_COMM] LESS_EQ_EXISTS)
  THEN1 (`LENGTH xs - 1 < d` by decide_tac
         \\ imp_res_tac LESS_DIV_EQ_ZERO \\ fsrw_tac[] [])
  \\ imp_res_tac DIV_ADD_1 \\ fsrw_tac[] []
  \\ AP_THM_TAC \\ AP_TERM_TAC \\ decide_tac);
val _ = (if null(hyp LENGTH_word_list_lemma) then () else raise Fail "open premise"; print "wl_full_LENGTH_word_list_lemma="; print_thm LENGTH_word_list_lemma; print "\n");
val LENGTH_word_list = prove(``!xs d. LENGTH (word_list xs d) =
           if d = 0 then 1 else (LENGTH xs - 1) DIV d + 1``,   rw [] THEN1 (once_rewrite_tac [word_list_def] \\ fs [])
  \\ match_mp_tac LENGTH_word_list_lemma \\ decide_tac);
val _ = (if null(hyp LENGTH_word_list) then () else raise Fail "open premise"; print "wl_full_LENGTH_word_list="; print_thm LENGTH_word_list; print "\n");
fun emit label q = let val th = EVAL q in print(label ^ "="); print_thm th; print "\n" end;
val _ = emit "wl_length_1_0_0" ``LENGTH ((word_list [] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_0_1" ``LENGTH ((word_list [] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_0_2" ``LENGTH ((word_list [] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_0_7" ``LENGTH ((word_list [] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_0_80" ``LENGTH ((word_list [] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_0_99" ``LENGTH ((word_list [] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_1_1_0" ``LENGTH ((word_list [T] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_1_1" ``LENGTH ((word_list [T] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_1_2" ``LENGTH ((word_list [T] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_1_7" ``LENGTH ((word_list [T] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_1_80" ``LENGTH ((word_list [T] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_1_99" ``LENGTH ((word_list [T] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_1_2_0" ``LENGTH ((word_list [F] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_2_1" ``LENGTH ((word_list [F] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_2_2" ``LENGTH ((word_list [F] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_2_7" ``LENGTH ((word_list [F] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_2_80" ``LENGTH ((word_list [F] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_2_99" ``LENGTH ((word_list [F] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_1_3_0" ``LENGTH ((word_list [T;F;T] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_3_1" ``LENGTH ((word_list [T;F;T] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_3_2" ``LENGTH ((word_list [T;F;T] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_3_7" ``LENGTH ((word_list [T;F;T] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_3_80" ``LENGTH ((word_list [T;F;T] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_3_99" ``LENGTH ((word_list [T;F;T] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_1_4_0" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_4_1" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_4_2" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_4_7" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_4_80" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_4_99" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_1_5_0" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_5_1" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_5_2" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_5_7" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_5_80" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_5_99" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_1_6_0" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 0):1 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_1_6_1" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 1):1 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_1_6_2" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 2):1 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_1_6_7" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 7):1 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_1_6_80" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 80):1 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_1_6_99" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 99):1 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_0_0" ``LENGTH ((word_list [] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_0_1" ``LENGTH ((word_list [] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_0_2" ``LENGTH ((word_list [] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_0_7" ``LENGTH ((word_list [] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_0_80" ``LENGTH ((word_list [] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_0_99" ``LENGTH ((word_list [] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_1_0" ``LENGTH ((word_list [T] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_1_1" ``LENGTH ((word_list [T] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_1_2" ``LENGTH ((word_list [T] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_1_7" ``LENGTH ((word_list [T] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_1_80" ``LENGTH ((word_list [T] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_1_99" ``LENGTH ((word_list [T] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_2_0" ``LENGTH ((word_list [F] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_2_1" ``LENGTH ((word_list [F] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_2_2" ``LENGTH ((word_list [F] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_2_7" ``LENGTH ((word_list [F] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_2_80" ``LENGTH ((word_list [F] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_2_99" ``LENGTH ((word_list [F] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_3_0" ``LENGTH ((word_list [T;F;T] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_3_1" ``LENGTH ((word_list [T;F;T] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_3_2" ``LENGTH ((word_list [T;F;T] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_3_7" ``LENGTH ((word_list [T;F;T] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_3_80" ``LENGTH ((word_list [T;F;T] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_3_99" ``LENGTH ((word_list [T;F;T] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_4_0" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_4_1" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_4_2" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_4_7" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_4_80" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_4_99" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_5_0" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_5_1" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_5_2" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_5_7" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_5_80" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_5_99" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_2_6_0" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 0):2 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_2_6_1" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 1):2 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_2_6_2" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 2):2 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_2_6_7" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 7):2 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_2_6_80" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 80):2 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_2_6_99" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 99):2 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_0_0" ``LENGTH ((word_list [] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_0_1" ``LENGTH ((word_list [] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_0_2" ``LENGTH ((word_list [] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_0_7" ``LENGTH ((word_list [] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_0_80" ``LENGTH ((word_list [] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_0_99" ``LENGTH ((word_list [] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_1_0" ``LENGTH ((word_list [T] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_1_1" ``LENGTH ((word_list [T] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_1_2" ``LENGTH ((word_list [T] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_1_7" ``LENGTH ((word_list [T] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_1_80" ``LENGTH ((word_list [T] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_1_99" ``LENGTH ((word_list [T] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_2_0" ``LENGTH ((word_list [F] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_2_1" ``LENGTH ((word_list [F] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_2_2" ``LENGTH ((word_list [F] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_2_7" ``LENGTH ((word_list [F] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_2_80" ``LENGTH ((word_list [F] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_2_99" ``LENGTH ((word_list [F] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_3_0" ``LENGTH ((word_list [T;F;T] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_3_1" ``LENGTH ((word_list [T;F;T] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_3_2" ``LENGTH ((word_list [T;F;T] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_3_7" ``LENGTH ((word_list [T;F;T] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_3_80" ``LENGTH ((word_list [T;F;T] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_3_99" ``LENGTH ((word_list [T;F;T] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_4_0" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_4_1" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_4_2" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_4_7" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_4_80" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_4_99" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_5_0" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_5_1" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_5_2" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_5_7" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_5_80" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_5_99" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_8_6_0" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 0):8 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_8_6_1" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 1):8 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_8_6_2" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 2):8 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_8_6_7" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 7):8 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_8_6_80" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 80):8 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_8_6_99" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 99):8 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_0_0" ``LENGTH ((word_list [] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_0_1" ``LENGTH ((word_list [] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_0_2" ``LENGTH ((word_list [] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_0_7" ``LENGTH ((word_list [] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_0_80" ``LENGTH ((word_list [] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_0_99" ``LENGTH ((word_list [] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_1_0" ``LENGTH ((word_list [T] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_1_1" ``LENGTH ((word_list [T] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_1_2" ``LENGTH ((word_list [T] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_1_7" ``LENGTH ((word_list [T] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_1_80" ``LENGTH ((word_list [T] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_1_99" ``LENGTH ((word_list [T] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_2_0" ``LENGTH ((word_list [F] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_2_1" ``LENGTH ((word_list [F] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_2_2" ``LENGTH ((word_list [F] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_2_7" ``LENGTH ((word_list [F] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_2_80" ``LENGTH ((word_list [F] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_2_99" ``LENGTH ((word_list [F] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_3_0" ``LENGTH ((word_list [T;F;T] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_3_1" ``LENGTH ((word_list [T;F;T] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_3_2" ``LENGTH ((word_list [T;F;T] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_3_7" ``LENGTH ((word_list [T;F;T] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_3_80" ``LENGTH ((word_list [T;F;T] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_3_99" ``LENGTH ((word_list [T;F;T] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_4_0" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_4_1" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_4_2" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_4_7" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_4_80" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_4_99" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_5_0" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_5_1" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_5_2" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_5_7" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_5_80" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_5_99" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_64_6_0" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 0):64 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_64_6_1" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 1):64 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_64_6_2" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 2):64 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_64_6_7" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 7):64 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_64_6_80" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 80):64 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_64_6_99" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 99):64 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_0_0" ``LENGTH ((word_list [] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_0_1" ``LENGTH ((word_list [] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_0_2" ``LENGTH ((word_list [] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_0_7" ``LENGTH ((word_list [] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_0_80" ``LENGTH ((word_list [] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_0_99" ``LENGTH ((word_list [] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_1_0" ``LENGTH ((word_list [T] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_1_1" ``LENGTH ((word_list [T] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_1_2" ``LENGTH ((word_list [T] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_1_7" ``LENGTH ((word_list [T] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_1_80" ``LENGTH ((word_list [T] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_1_99" ``LENGTH ((word_list [T] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_2_0" ``LENGTH ((word_list [F] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_2_1" ``LENGTH ((word_list [F] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_2_2" ``LENGTH ((word_list [F] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_2_7" ``LENGTH ((word_list [F] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_2_80" ``LENGTH ((word_list [F] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_2_99" ``LENGTH ((word_list [F] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_3_0" ``LENGTH ((word_list [T;F;T] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_3_1" ``LENGTH ((word_list [T;F;T] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_3_2" ``LENGTH ((word_list [T;F;T] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_3_7" ``LENGTH ((word_list [T;F;T] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_3_80" ``LENGTH ((word_list [T;F;T] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_3_99" ``LENGTH ((word_list [T;F;T] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_4_0" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_4_1" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_4_2" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_4_7" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_4_80" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_4_99" ``LENGTH ((word_list [F;F;F;F;F;F;F;F] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [F;F;F;F;F;F;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_5_0" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_5_1" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_5_2" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_5_7" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_5_80" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_5_99" ``LENGTH ((word_list [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] - 1) DIV 99 + 1)``;
val _ = emit "wl_length_80_6_0" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 0):80 word list) = (if (0:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 0 + 1)``;
val _ = emit "wl_length_80_6_1" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 1):80 word list) = (if (1:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 1 + 1)``;
val _ = emit "wl_length_80_6_2" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 2):80 word list) = (if (2:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 2 + 1)``;
val _ = emit "wl_length_80_6_7" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 7):80 word list) = (if (7:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 7 + 1)``;
val _ = emit "wl_length_80_6_80" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 80):80 word list) = (if (80:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 80 + 1)``;
val _ = emit "wl_length_80_6_99" ``LENGTH ((word_list [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] 99):80 word list) = (if (99:num) = 0 then 1 else (LENGTH [T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F;T;F;F] - 1) DIV 99 + 1)``;
val _ = emit "wl_div_0_0" ``0 < (0:num) ==> (0:num) DIV 0 + 1 = (0 + 0) DIV 0``;
val _ = emit "wl_div_0_1" ``0 < (1:num) ==> (0:num) DIV 1 + 1 = (0 + 1) DIV 1``;
val _ = emit "wl_div_0_2" ``0 < (2:num) ==> (0:num) DIV 2 + 1 = (0 + 2) DIV 2``;
val _ = emit "wl_div_0_7" ``0 < (7:num) ==> (0:num) DIV 7 + 1 = (0 + 7) DIV 7``;
val _ = emit "wl_div_0_80" ``0 < (80:num) ==> (0:num) DIV 80 + 1 = (0 + 80) DIV 80``;
val _ = emit "wl_div_0_99" ``0 < (99:num) ==> (0:num) DIV 99 + 1 = (0 + 99) DIV 99``;
val _ = emit "wl_div_1_0" ``0 < (0:num) ==> (1:num) DIV 0 + 1 = (1 + 0) DIV 0``;
val _ = emit "wl_div_1_1" ``0 < (1:num) ==> (1:num) DIV 1 + 1 = (1 + 1) DIV 1``;
val _ = emit "wl_div_1_2" ``0 < (2:num) ==> (1:num) DIV 2 + 1 = (1 + 2) DIV 2``;
val _ = emit "wl_div_1_7" ``0 < (7:num) ==> (1:num) DIV 7 + 1 = (1 + 7) DIV 7``;
val _ = emit "wl_div_1_80" ``0 < (80:num) ==> (1:num) DIV 80 + 1 = (1 + 80) DIV 80``;
val _ = emit "wl_div_1_99" ``0 < (99:num) ==> (1:num) DIV 99 + 1 = (1 + 99) DIV 99``;
val _ = emit "wl_div_2_0" ``0 < (0:num) ==> (2:num) DIV 0 + 1 = (2 + 0) DIV 0``;
val _ = emit "wl_div_2_1" ``0 < (1:num) ==> (2:num) DIV 1 + 1 = (2 + 1) DIV 1``;
val _ = emit "wl_div_2_2" ``0 < (2:num) ==> (2:num) DIV 2 + 1 = (2 + 2) DIV 2``;
val _ = emit "wl_div_2_7" ``0 < (7:num) ==> (2:num) DIV 7 + 1 = (2 + 7) DIV 7``;
val _ = emit "wl_div_2_80" ``0 < (80:num) ==> (2:num) DIV 80 + 1 = (2 + 80) DIV 80``;
val _ = emit "wl_div_2_99" ``0 < (99:num) ==> (2:num) DIV 99 + 1 = (2 + 99) DIV 99``;
val _ = emit "wl_div_3_0" ``0 < (0:num) ==> (7:num) DIV 0 + 1 = (7 + 0) DIV 0``;
val _ = emit "wl_div_3_1" ``0 < (1:num) ==> (7:num) DIV 1 + 1 = (7 + 1) DIV 1``;
val _ = emit "wl_div_3_2" ``0 < (2:num) ==> (7:num) DIV 2 + 1 = (7 + 2) DIV 2``;
val _ = emit "wl_div_3_7" ``0 < (7:num) ==> (7:num) DIV 7 + 1 = (7 + 7) DIV 7``;
val _ = emit "wl_div_3_80" ``0 < (80:num) ==> (7:num) DIV 80 + 1 = (7 + 80) DIV 80``;
val _ = emit "wl_div_3_99" ``0 < (99:num) ==> (7:num) DIV 99 + 1 = (7 + 99) DIV 99``;
val _ = emit "wl_div_4_0" ``0 < (0:num) ==> (1208925819614629174706176:num) DIV 0 + 1 = (1208925819614629174706176 + 0) DIV 0``;
val _ = emit "wl_div_4_1" ``0 < (1:num) ==> (1208925819614629174706176:num) DIV 1 + 1 = (1208925819614629174706176 + 1) DIV 1``;
val _ = emit "wl_div_4_2" ``0 < (2:num) ==> (1208925819614629174706176:num) DIV 2 + 1 = (1208925819614629174706176 + 2) DIV 2``;
val _ = emit "wl_div_4_7" ``0 < (7:num) ==> (1208925819614629174706176:num) DIV 7 + 1 = (1208925819614629174706176 + 7) DIV 7``;
val _ = emit "wl_div_4_80" ``0 < (80:num) ==> (1208925819614629174706176:num) DIV 80 + 1 = (1208925819614629174706176 + 80) DIV 80``;
val _ = emit "wl_div_4_99" ``0 < (99:num) ==> (1208925819614629174706176:num) DIV 99 + 1 = (1208925819614629174706176 + 99) DIV 99``;
val _ = emit "wl_div_5_0" ``0 < (0:num) ==> (1208925819614629174706177:num) DIV 0 + 1 = (1208925819614629174706177 + 0) DIV 0``;
val _ = emit "wl_div_5_1" ``0 < (1:num) ==> (1208925819614629174706177:num) DIV 1 + 1 = (1208925819614629174706177 + 1) DIV 1``;
val _ = emit "wl_div_5_2" ``0 < (2:num) ==> (1208925819614629174706177:num) DIV 2 + 1 = (1208925819614629174706177 + 2) DIV 2``;
val _ = emit "wl_div_5_7" ``0 < (7:num) ==> (1208925819614629174706177:num) DIV 7 + 1 = (1208925819614629174706177 + 7) DIV 7``;
val _ = emit "wl_div_5_80" ``0 < (80:num) ==> (1208925819614629174706177:num) DIV 80 + 1 = (1208925819614629174706177 + 80) DIV 80``;
val _ = emit "wl_div_5_99" ``0 < (99:num) ==> (1208925819614629174706177:num) DIV 99 + 1 = (1208925819614629174706177 + 99) DIV 99``;
