load "bossLib"; load "preamble"; load "word_simpTheory";
open HolKernel Parse bossLib preamble word_simpTheory;
val _ = Globals.linewidth := 1000;
fun out label acc p = (print (label ^ "=");
  print_term (rhs (concl (EVAL ``Seq_assoc ^acc ^p``))); print "\n");
val skip = ``(Skip:64 wordLang$prog)``;
val a = ``(Assign 1 (Const 7w):64 wordLang$prog)``;
val b = ``(Assign 2 (Const 9w):64 wordLang$prog)``;
val _ = out "assoc_skip" skip skip;
val _ = out "assoc_prefix_skip" a skip;
val _ = out "assoc_trailing_skip" skip ``(Seq Tick Skip:64 wordLang$prog)``;
val _ = out "assoc_interior_skip" skip ``(Seq (Seq Tick Skip) Tick:64 wordLang$prog)``;
val _ = out "assoc_all_skip" skip ``(Seq (Seq Skip Skip) (Seq Skip Skip):64 wordLang$prog)``;
val _ = out "assoc_middle_skip" skip ``Seq ^a (Seq Skip ^b)``;
val _ = out "assoc_right_spine" skip ``(Seq Tick (Seq (Raise 3) (Return 1 [2])):64 wordLang$prog)``;
val _ = out "assoc_if" skip ``(If Equal 1 (Imm 0w) (Seq Skip Tick) (Seq (Raise 3) Skip):64 wordLang$prog)``;
val _ = out "assoc_loop" skip ``(Loop LN (Seq (Seq Skip Tick) Skip) LN:64 wordLang$prog)``;
val _ = out "assoc_must" skip ``(MustTerminate (Seq (Seq Skip Tick) Skip):64 wordLang$prog)``;
val _ = out "assoc_tail_handler" skip ``(Call NONE (SOME 7) [1] (SOME(1,Seq Tick Skip,3,4)):64 wordLang$prog)``;
val _ = out "assoc_return" skip ``(Call (SOME([], (LN,LN),Seq Skip Tick,3,4)) (SOME 7) [1] NONE:64 wordLang$prog)``;
val _ = out "assoc_both" skip ``(Call (SOME([], (LN,LN),Seq Tick Skip,3,4)) (SOME 7) [1] (SOME(1,Seq Skip (Seq (Raise 3) Skip),5,6)):64 wordLang$prog)``;
val _ = out "assoc_prefix_unchanged" ``(Seq Tick Skip:64 wordLang$prog)`` skip;
val _ = out "assoc_inst" skip ``(Inst (Const 2 9w):64 wordLang$prog)``;
val _ = (print "assoc_pre_ssa=";
  print_term (rhs (concl (EVAL ``compile_exp (Seq (If Less 1 (Reg 2) (Assign 3 (Const 1w)) (Assign 3 (Const 0w))) (Seq (Assign 4 (Var 3)) (If NotEqual 4 (Imm 0w) (Assign 5 (Const 7w)) Skip)):64 wordLang$prog)``)));
  print "\n");
