load "bossLib";
load "preamble";
load "word_allocTheory";
open bossLib HolKernel Parse preamble word_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = observe "gso_skip" ``get_stack_only_aux (LS (),BN LN LN) (Skip:64 word wordLang$prog) = (LS (),BN LN LN)``;
val _ = observe "gso_move" ``get_stack_only_aux (LN,LN) (Move 0 [(3,1)]:64 word wordLang$prog) = (insert 1 () LN,LN)``;
val _ = observe "gso_foldr" ``get_stack_only_aux (LN,LN) (Move 0 [(1,5);(3,1)]:64 word wordLang$prog) = (insert 5 () (insert 1 () LN),insert 1 () LN)``;
val _ = observe "gso_seq" ``get_stack_only_aux (LN,LN) (Seq (Move 0 [(1,5)]) (Move 0 [(3,1)]):64 word wordLang$prog) = (insert 5 () (insert 1 () LN),insert 1 () LN)``;
val _ = observe "gso_must" ``get_stack_only_aux (LN,LN) (MustTerminate (Move 0 [(3,1)]):64 word wordLang$prog) = (insert 1 () LN,LN)``;
val _ = observe "gso_loop" ``get_stack_only_aux (LN,LN) (Loop LN (Move 0 [(3,1)]) LN:64 word wordLang$prog) = (insert 1 () LN,LN)``;
val _ = observe "gso_call_none" ``get_stack_only_aux (LS (),BN LN LN) (Call NONE NONE [] (SOME (0,Move 0 [(3,1)],0,0)):64 word wordLang$prog) = (LS (),BN LN LN)``;
val _ = observe "gso_call_return" ``get_stack_only_aux (LN,LN) (Call (SOME ([],(LN,LN),Move 0 [(3,1)],0,0)) NONE [] NONE:64 word wordLang$prog) = (insert 1 () LN,LN)``;
val _ = observe "gso_tick" ``get_stack_only_aux (LS (),BN LN LN) (Tick:64 word wordLang$prog) = (LS (),BN LN LN)``;
val _ = observe "gso_return" ``get_stack_only_aux (LS (),BN LN LN) (Return 0 []:64 word wordLang$prog) = (LN,BN LN LN)``;
val _ = observe "gso_alloc_nondelta" ``get_stack_only_aux (LS (),BN LN LN) (Alloc 0 (LN,LN):64 word wordLang$prog) = (LS (),BN LN LN)``;
val _ = observe "gso_entry" ``get_stack_only (Seq (Move 0 [(1,5)]) (Move 0 [(3,1)]):64 word wordLang$prog) = insert 1 () LN``;
val _ = observe "gso_if_reg" ``get_stack_only_aux (LN,LN) (If Equal 1 (Reg 1) (Move 0 [(3,1)]) (Move 0 [(3,1)]):64 word wordLang$prog) = (LN,LN)``;
val _ = observe "gso_if_imm" ``get_stack_only_aux (LN,LN) (If Equal 0 (Imm 0w) (Move 0 [(3,1)]) (Move 0 [(3,1)]):64 word wordLang$prog) = (insert 1 () LN,LN)``;
val _ = observe "gso_call_both" ``get_stack_only_aux (LN,LN) (Call (SOME ([],(LN,LN),Move 0 [(3,1)],0,0)) NONE [] (SOME (0,Move 0 [(3,1)],0,0)):64 word wordLang$prog) = (insert 1 () LN,LN)``;
