load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory word_to_stackTheory stackPropsTheory;
val _ = Globals.linewidth := 1000000;
val _ = numLib.temp_prefer_num();
fun theoremRow label th = (if null(hyp th) then () else raise Fail "open premise"; print(label ^ "="); print_thm th; print "\n");
val case_MustTerminate = prove(``!c perf body bs frame. perf=F ==> alloc_arg (FST (comp c perf (MustTerminate body) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_MustTerminate" case_MustTerminate;
val case_Loop = prove(``!c perf liveIn body liveOut bs frame. perf=F ==> alloc_arg (FST (comp c perf (Loop liveIn body liveOut) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_Loop" case_Loop;
val case_Seq = prove(``!c perf first second bs frame. perf=F ==> alloc_arg (FST (comp c perf (Seq first second) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_Seq" case_Seq;
val case_If = prove(``!c perf cmp reg ri first second bs frame. perf=F ==> alloc_arg (FST (comp c perf (If cmp reg ri first second) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_If" case_If;
val case_CallTail = prove(``!c perf dest args handler bs frame. perf=F ==> alloc_arg (FST (comp c perf (Call NONE dest args handler) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_CallTail" case_CallTail;
val case_CallReturn = prove(``!c perf values live retCode l1 l2 dest args bs frame. perf=F ==> alloc_arg (FST (comp c perf (Call (SOME(values,live,retCode,l1,l2)) dest args NONE) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_CallReturn" case_CallReturn;
val case_CallHandler = prove(``!c perf values live retCode l1 l2 dest args handleValue handleCode h1 h2 bs frame. perf=F ==> alloc_arg (FST (comp c perf (Call (SOME(values,live,retCode,l1,l2)) dest args (SOME(handleValue,handleCode,h1,h2))) bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aar_full_CallHandler" case_CallHandler;
