load "preamble";
load "word_to_stackTheory";
load "stackPropsTheory";
load "wordConvsTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory stackPropsTheory wordConvsTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "tc_direct0_1" ``let p = (Call NONE (SOME 777) [] NONE : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "tc_directmany_1" ``let p = (Call NONE (SOME 777) [2;4;999] NONE : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "tc_indirect0_1" ``let p = (Call NONE NONE [] NONE : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "tc_indirectsmall_1" ``let p = (Call NONE NONE [0] NONE : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "tc_indirectlarge_1" ``let p = (Call NONE NONE [2;4;999] NONE : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "tc_direct0_32" ``let p = (Call NONE (SOME 777) [] NONE : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "tc_directmany_32" ``let p = (Call NONE (SOME 777) [2;4;999] NONE : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "tc_indirect0_32" ``let p = (Call NONE NONE [] NONE : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "tc_indirectsmall_32" ``let p = (Call NONE NONE [0] NONE : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "tc_indirectlarge_32" ``let p = (Call NONE NONE [2;4;999] NONE : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "tc_direct0_64" ``let p = (Call NONE (SOME 777) [] NONE : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "tc_directmany_64" ``let p = (Call NONE (SOME 777) [2;4;999] NONE : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "tc_indirect0_64" ``let p = (Call NONE NONE [] NONE : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "tc_indirectsmall_64" ``let p = (Call NONE NONE [0] NONE : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "tc_indirectlarge_64" ``let p = (Call NONE NONE [2;4;999] NONE : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "tc_direct0_80" ``let p = (Call NONE (SOME 777) [] NONE : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "tc_directmany_80" ``let p = (Call NONE (SOME 777) [2;4;999] NONE : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "tc_indirect0_80" ``let p = (Call NONE NONE [] NONE : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "tc_indirectsmall_80" ``let p = (Call NONE NONE [0] NONE : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "tc_indirectlarge_80" ``let p = (Call NONE NONE [2;4;999] NONE : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "tc_ignored_safe" ``let p = (Call NONE NONE [999] (SOME (99,wordLang$Return 999 [2;4],7,9)) : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "tc_ignored_shared" ``let p = (Call NONE NONE [999] (SOME (99,wordLang$ShareInst Load 0 (Var 3),7,9)) : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (F,T)``;
