load "preamble";
load "word_to_stackTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory;
fun typ label t = (print (label ^ "="); print_type (type_of t); print "\n");
val _ = typ "hcf_push_type" ``PushHandler``;
val _ = typ "hcf_pop_type" ``PopHandler``;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "hcf_push_64_F" ``(PushHandler F 7 9 (2,T,"ignored") : 64 stackLang$prog) = PushHandler F 7 9 (2,0,0)``;
val _ = out "hcf_pop_64_F_skip" ``(PopHandler F (2,T,"ignored") (Skip) : 64 stackLang$prog) = PopHandler F (2,0,0) (Skip)``;
val _ = out "hcf_pop_64_F_forbidden" ``(PopHandler F (2,T,"ignored") (ShMemOp Load 0 (Addr 1 0w)) : 64 stackLang$prog) = PopHandler F (2,0,0) (ShMemOp Load 0 (Addr 1 0w))``;
val _ = out "hcf_push_64_T" ``(PushHandler T 7 9 (2,T,"ignored") : 64 stackLang$prog) = PushHandler T 7 9 (2,0,0)``;
val _ = out "hcf_pop_64_T_skip" ``(PopHandler T (2,T,"ignored") (Skip) : 64 stackLang$prog) = PopHandler T (2,0,0) (Skip)``;
val _ = out "hcf_pop_64_T_forbidden" ``(PopHandler T (2,T,"ignored") (ShMemOp Load 0 (Addr 1 0w)) : 64 stackLang$prog) = PopHandler T (2,0,0) (ShMemOp Load 0 (Addr 1 0w))``;
val _ = out "hcf_push_1_F" ``(PushHandler F 7 9 (0,[1;2;3],F) : 1 stackLang$prog) = PushHandler F 7 9 (0,0,0)``;
val _ = out "hcf_pop_1_F_skip" ``(PopHandler F (0,[1;2;3],F) (Skip) : 1 stackLang$prog) = PopHandler F (0,0,0) (Skip)``;
val _ = out "hcf_pop_1_F_forbidden" ``(PopHandler F (0,[1;2;3],F) (ShMemOp Load 0 (Addr 1 0w)) : 1 stackLang$prog) = PopHandler F (0,0,0) (ShMemOp Load 0 (Addr 1 0w))``;
val _ = out "hcf_push_1_T" ``(PushHandler T 7 9 (0,[1;2;3],F) : 1 stackLang$prog) = PushHandler T 7 9 (0,0,0)``;
val _ = out "hcf_pop_1_T_skip" ``(PopHandler T (0,[1;2;3],F) (Skip) : 1 stackLang$prog) = PopHandler T (0,0,0) (Skip)``;
val _ = out "hcf_pop_1_T_forbidden" ``(PopHandler T (0,[1;2;3],F) (ShMemOp Load 0 (Addr 1 0w)) : 1 stackLang$prog) = PopHandler T (0,0,0) (ShMemOp Load 0 (Addr 1 0w))``;
