load "preamble";
load "word_to_stackTheory";
load "stackPropsTheory";
load "wordConvsTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory stackPropsTheory wordConvsTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "cp_skip_1" ``let p = (wordLang$Skip : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_assign_1" ``let p = (wordLang$Assign 999 (Op Add [Var 999;Const 9w]) : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_store_1" ``let p = (wordLang$Store (Load (Var 999)) 777 : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_raise_1" ``let p = (wordLang$Raise 999 : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_break_1" ``let p = (wordLang$Break 999 : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_continue_1" ``let p = (wordLang$Continue 999 : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_tick_1" ``let p = (wordLang$Tick : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (T,T)``;
val _ = out "cp_skip_32" ``let p = (wordLang$Skip : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_assign_32" ``let p = (wordLang$Assign 999 (Op Add [Var 999;Const 9w]) : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_store_32" ``let p = (wordLang$Store (Load (Var 999)) 777 : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_raise_32" ``let p = (wordLang$Raise 999 : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_break_32" ``let p = (wordLang$Break 999 : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_continue_32" ``let p = (wordLang$Continue 999 : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_tick_32" ``let p = (wordLang$Tick : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (T,T)``;
val _ = out "cp_skip_64" ``let p = (wordLang$Skip : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_assign_64" ``let p = (wordLang$Assign 999 (Op Add [Var 999;Const 9w]) : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_store_64" ``let p = (wordLang$Store (Load (Var 999)) 777 : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_raise_64" ``let p = (wordLang$Raise 999 : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_break_64" ``let p = (wordLang$Break 999 : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_continue_64" ``let p = (wordLang$Continue 999 : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_tick_64" ``let p = (wordLang$Tick : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (T,T)``;
val _ = out "cp_skip_80" ``let p = (wordLang$Skip : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_assign_80" ``let p = (wordLang$Assign 999 (Op Add [Var 999;Const 9w]) : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_store_80" ``let p = (wordLang$Store (Load (Var 999)) 777 : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_raise_80" ``let p = (wordLang$Raise 999 : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_break_80" ``let p = (wordLang$Break 999 : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_continue_80" ``let p = (wordLang$Continue 999 : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_tick_80" ``let p = (wordLang$Tick : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (T,T)``;
val _ = out "cp_load_valid" ``let p = (wordLang$ShareInst Load 999 (Var 3) : 1 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))) = (F,F)``;
val _ = out "cp_load_invalid" ``let p = (wordLang$ShareInst Load 999 (Const 9w) : 32 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))) = (F,T)``;
val _ = out "cp_store_valid" ``let p = (wordLang$ShareInst Store 999 (Var 3) : 64 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))) = (F,F)``;
val _ = out "cp_store_invalid" ``let p = (wordLang$ShareInst Store 999 (Const 9w) : 80 wordLang$prog) in (no_share_inst p,no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))) = (F,T)``;
