load "bossLib"; load "preamble"; load "wordConvsTheory";
open bossLib HolKernel Parse preamble wordConvsTheory wordLangTheory asmTheory;
val _ = print "im_original_theorem=";
val _ = print_thm (DB.fetch "wordConvs" "every_var_inst_mono");
val _ = print "\n";
fun observe label term = (print (label ^ "="); print_term (rconc (EVAL term)); print "\n");
val _ = observe "im_skip" ``(every_var_inst (\x. x < 5) (Skip : 1 asm$inst), every_var_inst (\x. x < 9) (Skip : 1 asm$inst))``;
val _ = observe "im_const" ``(every_var_inst (\x. x < 5) (Const 4 123w : 80 asm$inst), every_var_inst (\x. x < 9) (Const 4 123w : 80 asm$inst))``;
val _ = observe "im_binreg" ``(every_var_inst (\x. x < 5) (Arith (Binop Add 1 2 (Reg 4)) : 8 asm$inst), every_var_inst (\x. x < 9) (Arith (Binop Add 1 2 (Reg 4)) : 8 asm$inst))``;
val _ = observe "im_binimm" ``(every_var_inst (\x. x < 5) (Arith (Binop Add 1 2 (Imm 99w)) : 8 asm$inst), every_var_inst (\x. x < 9) (Arith (Binop Add 1 2 (Imm 99w)) : 8 asm$inst))``;
val _ = observe "im_shift" ``(every_var_inst (\x. x < 5) (Arith (Shift Lsl 1 2 (Reg 4)) : 32 asm$inst), every_var_inst (\x. x < 9) (Arith (Shift Lsl 1 2 (Reg 4)) : 32 asm$inst))``;
val _ = observe "im_div" ``(every_var_inst (\x. x < 5) (Arith (Div 1 2 3) : 8 asm$inst), every_var_inst (\x. x < 9) (Arith (Div 1 2 3) : 8 asm$inst))``;
val _ = observe "im_longdiv" ``(every_var_inst (\x. x < 5) (Arith (LongDiv 0 1 2 3 4) : 80 asm$inst), every_var_inst (\x. x < 9) (Arith (LongDiv 0 1 2 3 4) : 80 asm$inst))``;
val _ = observe "im_load8" ``(every_var_inst (\x. x < 5) (Mem Load8 1 (Addr 2 99w) : 64 asm$inst), every_var_inst (\x. x < 9) (Mem Load8 1 (Addr 2 99w) : 64 asm$inst))``;
val _ = observe "im_load16_ignored" ``(every_var_inst (\x. x < 5) (Mem Load16 99 (Addr 98 0w) : 1 asm$inst), every_var_inst (\x. x < 9) (Mem Load16 99 (Addr 98 0w) : 1 asm$inst))``;
val _ = observe "im_fpless" ``(every_var_inst (\x. x < 5) (FP (FPLess 4 99 100) : 8 asm$inst), every_var_inst (\x. x < 9) (FP (FPLess 4 99 100) : 8 asm$inst))``;
val _ = observe "im_fp64_to" ``(every_var_inst (\x. x < 5) (FP (FPMovToReg 2 99 100) : 64 asm$inst), every_var_inst (\x. x < 9) (FP (FPMovToReg 2 99 100) : 64 asm$inst))``;
val _ = observe "im_fp32_to" ``(every_var_inst (\x. x < 5) (FP (FPMovToReg 2 4 100) : 32 asm$inst), every_var_inst (\x. x < 9) (FP (FPMovToReg 2 4 100) : 32 asm$inst))``;
val _ = observe "im_fp80_from" ``(every_var_inst (\x. x < 5) (FP (FPMovFromReg 100 2 4) : 80 asm$inst), every_var_inst (\x. x < 9) (FP (FPMovFromReg 100 2 4) : 80 asm$inst))``;
val _ = observe "im_fpignored" ``(every_var_inst (\x. x < 5) (FP (FPAbs 99 100) : 80 asm$inst), every_var_inst (\x. x < 9) (FP (FPAbs 99 100) : 80 asm$inst))``;
val _ = observe "im_fp32_reject" ``(every_var_inst (\x. x < 5) (FP (FPMovToReg 2 99 100) : 32 asm$inst), every_var_inst (\x. x < 9) (FP (FPMovToReg 2 99 100) : 32 asm$inst))``;
