(* Fresh direct original complete max_var observations. *)
load "bossLib";
load "preamble";
load "wordLangTheory";
open bossLib HolKernel Parse preamble wordLangTheory;
fun out label q = let val th = EVAL q in
  (print (label ^ "="); print_term (rconc th); print "\n") end;
val _ = out "mv_skip" ``max_var (Skip: 64 wordLang$prog) = 0``;
val _ = out "mv_move" ``max_var (Move 99 [(3,17);(23,5)]: 64 wordLang$prog) = 23``;
val _ = out "mv_move_empty" ``max_var (Move 99 []: 64 wordLang$prog) = 0``;
val _ = out "mv_inst64" ``max_var (Inst (FP (FPMovToReg 3 17 99)): 64 wordLang$prog) = 3``;
val _ = out "mv_inst32" ``max_var (Inst (FP (FPMovToReg 3 17 99)): 32 wordLang$prog) = 17``;
val _ = out "mv_assign" ``max_var (Assign 11 (Load (Var 17)): 64 wordLang$prog) = 17``;
val _ = out "mv_get" ``max_var (Get 7 Handler: 64 wordLang$prog) = 7``;
val _ = out "mv_store" ``max_var (Store (Shift Lsl (Var 5) (Var 17)) 3: 64 wordLang$prog) = 17``;
val _ = out "mv_tail_ignored" ``max_var (Call NONE (SOME 99) [5;17] (SOME (101,Raise 103,7,8)): 64 wordLang$prog) = 17``;
val _ = out "mv_tail_empty" ``max_var (Call NONE NONE [] (SOME (101,Raise 103,7,8)): 64 wordLang$prog) = 0``;
val _ = out "mv_call_body" ``max_var (Call (SOME ([5],(insert 17 () LN,LN),Raise 23,7,8)) NONE [11] NONE: 64 wordLang$prog) = 23``;
val _ = out "mv_call_cutset" ``max_var (Call (SOME ([5],(LN,insert 47 () LN),Raise 23,7,8)) NONE [11] NONE: 64 wordLang$prog) = 47``;
val _ = out "mv_call_values" ``max_var (Call (SOME ([53],(LN,insert 47 () LN),Raise 23,7,8)) NONE [11] NONE: 64 wordLang$prog) = 53``;
val _ = out "mv_handler_value" ``max_var (Call (SOME ([5],(insert 17 () LN,LN),Raise 23,7,8)) NONE [11] (SOME (37,Raise 29,9,10)): 64 wordLang$prog) = 37``;
val _ = out "mv_handler_body" ``max_var (Call (SOME ([5],(insert 17 () LN,LN),Raise 23,7,8)) NONE [11] (SOME (37,Raise 61,9,10)): 64 wordLang$prog) = 61``;
val _ = out "mv_seq" ``max_var (Seq (Raise 5) (Raise 17): 64 wordLang$prog) = 17``;
val _ = out "mv_must" ``max_var (MustTerminate (Raise 17): 64 wordLang$prog) = 17``;
val _ = out "mv_if_reg" ``max_var (If Equal 5 (Reg 23) (Raise 17) (Raise 11): 64 wordLang$prog) = 23``;
val _ = out "mv_if_imm" ``max_var (If Equal 5 (Imm 99w) (Raise 17) (Raise 11): 64 wordLang$prog) = 17``;
val _ = out "mv_alloc" ``max_var (Alloc 7 (insert 17 () LN,insert 23 () LN): 64 wordLang$prog) = 23``;
val _ = out "mv_consts" ``max_var (StoreConsts 3 17 23 5 [(T,99w)]: 64 wordLang$prog) = 23``;
val _ = out "mv_install" ``max_var (Install 3 5 7 11 (LN,insert 23 () LN): 64 wordLang$prog) = 23``;
val _ = out "mv_codewrite" ``max_var (CodeBufferWrite 3 17: 64 wordLang$prog) = 17``;
val _ = out "mv_datawrite" ``max_var (DataBufferWrite 23 5: 64 wordLang$prog) = 23``;
val _ = out "mv_ffi" ``max_var (FFI (implode "x") 3 5 7 11 (insert 17 () LN,insert 23 () LN): 64 wordLang$prog) = 23``;
val _ = out "mv_raise" ``max_var (Raise 17: 64 wordLang$prog) = 17``;
val _ = out "mv_heap" ``max_var (OpCurrHeap Add 3 17: 64 wordLang$prog) = 17``;
val _ = out "mv_return" ``max_var (Return 3 [5;17]: 64 wordLang$prog) = 17``;
val _ = out "mv_return_empty" ``max_var (Return 0 []: 64 wordLang$prog) = 0``;
val _ = out "mv_tick" ``max_var (Tick: 64 wordLang$prog) = 0``;
val _ = out "mv_loc" ``max_var (LocValue 7 99: 64 wordLang$prog) = 7``;
val _ = out "mv_set" ``max_var (Set CurrHeap (Load (Var 17)): 64 wordLang$prog) = 17``;
val _ = out "mv_share" ``max_var (ShareInst Load8 3 (Op Add [Var 5;Const 99w]): 64 wordLang$prog) = 5``;
val _ = out "mv_loop_exit" ``max_var (Loop (insert 17 () LN) (Raise 23) (insert 29 () LN): 64 wordLang$prog) = 29``;
val _ = out "mv_loop_body" ``max_var (Loop (insert 17 () LN) (Raise 31) (insert 29 () LN): 64 wordLang$prog) = 31``;
val _ = out "mv_break" ``max_var (Break 99: 64 wordLang$prog) = 0``;
val _ = out "mv_continue" ``max_var (Continue 99: 64 wordLang$prog) = 0``;
