load "wordPropsTheory";
open HolKernel Parse bossLib wordPropsTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "PAIR_MAP_EQ_PAIR_statement="; print_term(concl PAIR_MAP_EQ_PAIR));
val _ = print("PAIR_MAP_EQ_PAIR_hypotheses=" ^ Int.toString(length(hyp PAIR_MAP_EQ_PAIR)) ^ "\n");
val _ = (print "OPTION_CASE_OPTION_MAP_statement="; print_term(concl OPTION_CASE_OPTION_MAP));
val _ = print("OPTION_CASE_OPTION_MAP_hypotheses=" ^ Int.toString(length(hyp OPTION_CASE_OPTION_MAP)) ^ "\n");
val _ = (print "OPTION_CASE_MAP_statement="; print_term(concl OPTION_CASE_MAP));
val _ = print("OPTION_CASE_MAP_hypotheses=" ^ Int.toString(length(hyp OPTION_CASE_MAP)) ^ "\n");
val _ = (print "get_var_with_const_statement="; print_term(concl get_var_with_const));
val _ = print("get_var_with_const_hypotheses=" ^ Int.toString(length(hyp get_var_with_const)) ^ "\n");
val _ = (print "get_vars_with_const_statement="; print_term(concl get_vars_with_const));
val _ = print("get_vars_with_const_hypotheses=" ^ Int.toString(length(hyp get_vars_with_const)) ^ "\n");
val _ = (print "unset_var_with_const_statement="; print_term(concl unset_var_with_const));
val _ = print("unset_var_with_const_hypotheses=" ^ Int.toString(length(hyp unset_var_with_const)) ^ "\n");
val _ = (print "set_vars_with_const_statement="; print_term(concl set_vars_with_const));
val _ = print("set_vars_with_const_hypotheses=" ^ Int.toString(length(hyp set_vars_with_const)) ^ "\n");
val _ = (print "get_store_with_const_statement="; print_term(concl get_store_with_const));
val _ = print("get_store_with_const_hypotheses=" ^ Int.toString(length(hyp get_store_with_const)) ^ "\n");
val _ = (print "set_store_with_const_statement="; print_term(concl set_store_with_const));
val _ = print("set_store_with_const_hypotheses=" ^ Int.toString(length(hyp set_store_with_const)) ^ "\n");
val _ = (print "push_env_with_const_statement="; print_term(concl push_env_with_const));
val _ = print("push_env_with_const_hypotheses=" ^ Int.toString(length(hyp push_env_with_const)) ^ "\n");
val _ = (print "pop_env_with_const_statement="; print_term(concl pop_env_with_const));
val _ = print("pop_env_with_const_hypotheses=" ^ Int.toString(length(hyp pop_env_with_const)) ^ "\n");
val _ = (print "call_env_with_const_statement="; print_term(concl call_env_with_const));
val _ = print("call_env_with_const_hypotheses=" ^ Int.toString(length(hyp call_env_with_const)) ^ "\n");
val _ = (print "flush_state_with_const_statement="; print_term(concl flush_state_with_const));
val _ = print("flush_state_with_const_hypotheses=" ^ Int.toString(length(hyp flush_state_with_const)) ^ "\n");
val _ = (print "has_space_with_const_statement="; print_term(concl has_space_with_const));
val _ = print("has_space_with_const_hypotheses=" ^ Int.toString(length(hyp has_space_with_const)) ^ "\n");
val _ = (print "gc_with_const_statement="; print_term(concl gc_with_const));
val _ = print("gc_with_const_hypotheses=" ^ Int.toString(length(hyp gc_with_const)) ^ "\n");
val _ = (print "alloc_with_const_statement="; print_term(concl alloc_with_const));
val _ = print("alloc_with_const_hypotheses=" ^ Int.toString(length(hyp alloc_with_const)) ^ "\n");
val _ = (print "get_fp_var_with_const_statement="; print_term(concl get_fp_var_with_const));
val _ = print("get_fp_var_with_const_hypotheses=" ^ Int.toString(length(hyp get_fp_var_with_const)) ^ "\n");
val _ = (print "set_fp_var_with_const_statement="; print_term(concl set_fp_var_with_const));
val _ = print("set_fp_var_with_const_hypotheses=" ^ Int.toString(length(hyp set_fp_var_with_const)) ^ "\n");
val _ = (print "mem_load_with_const_statement="; print_term(concl mem_load_with_const));
val _ = print("mem_load_with_const_hypotheses=" ^ Int.toString(length(hyp mem_load_with_const)) ^ "\n");
val _ = (print "mem_store_with_const_statement="; print_term(concl mem_store_with_const));
val _ = print("mem_store_with_const_hypotheses=" ^ Int.toString(length(hyp mem_store_with_const)) ^ "\n");
val _ = (print "word_exp_with_const_statement="; print_term(concl word_exp_with_const));
val _ = print("word_exp_with_const_hypotheses=" ^ Int.toString(length(hyp word_exp_with_const)) ^ "\n");
val _ = (print "assign_with_const_statement="; print_term(concl assign_with_const));
val _ = print("assign_with_const_hypotheses=" ^ Int.toString(length(hyp assign_with_const)) ^ "\n");
val _ = (print "inst_with_const_statement="; print_term(concl inst_with_const));
val _ = print("inst_with_const_hypotheses=" ^ Int.toString(length(hyp inst_with_const)) ^ "\n");
val _ = (print "jump_exc_with_const_statement="; print_term(concl jump_exc_with_const));
val _ = print("jump_exc_with_const_hypotheses=" ^ Int.toString(length(hyp jump_exc_with_const)) ^ "\n");
val _ = (print "get_var_imm_with_const_statement="; print_term(concl get_var_imm_with_const));
val _ = print("get_var_imm_with_const_hypotheses=" ^ Int.toString(length(hyp get_var_imm_with_const)) ^ "\n");
val _ = (print "sh_mem_set_var_with_const_statement="; print_term(concl sh_mem_set_var_with_const));
val _ = print("sh_mem_set_var_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_set_var_with_const)) ^ "\n");
val _ = (print "sh_mem_load_with_const_statement="; print_term(concl sh_mem_load_with_const));
val _ = print("sh_mem_load_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_load_with_const)) ^ "\n");
val _ = (print "sh_mem_load_byte_with_const_statement="; print_term(concl sh_mem_load_byte_with_const));
val _ = print("sh_mem_load_byte_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_load_byte_with_const)) ^ "\n");
val _ = (print "sh_mem_load16_with_const_statement="; print_term(concl sh_mem_load16_with_const));
val _ = print("sh_mem_load16_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_load16_with_const)) ^ "\n");
val _ = (print "sh_mem_load32_with_const_statement="; print_term(concl sh_mem_load32_with_const));
val _ = print("sh_mem_load32_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_load32_with_const)) ^ "\n");
val _ = (print "sh_mem_store_with_const_statement="; print_term(concl sh_mem_store_with_const));
val _ = print("sh_mem_store_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store_with_const)) ^ "\n");
val _ = (print "sh_mem_store_byte_with_const_statement="; print_term(concl sh_mem_store_byte_with_const));
val _ = print("sh_mem_store_byte_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store_byte_with_const)) ^ "\n");
val _ = (print "sh_mem_store16_with_const_statement="; print_term(concl sh_mem_store16_with_const));
val _ = print("sh_mem_store16_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store16_with_const)) ^ "\n");
val _ = (print "sh_mem_store32_with_const_statement="; print_term(concl sh_mem_store32_with_const));
val _ = print("sh_mem_store32_with_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store32_with_const)) ^ "\n");
val _ = (print "share_inst_with_const_statement="; print_term(concl share_inst_with_const));
val _ = print("share_inst_with_const_hypotheses=" ^ Int.toString(length(hyp share_inst_with_const)) ^ "\n");
val _ = (print "cut_state_with_const_statement="; print_term(concl cut_state_with_const));
val _ = print("cut_state_with_const_hypotheses=" ^ Int.toString(length(hyp cut_state_with_const)) ^ "\n");
val _ = (print "unset_var_const_statement="; print_term(concl unset_var_const));
val _ = print("unset_var_const_hypotheses=" ^ Int.toString(length(hyp unset_var_const)) ^ "\n");
val _ = (print "set_vars_const_statement="; print_term(concl set_vars_const));
val _ = print("set_vars_const_hypotheses=" ^ Int.toString(length(hyp set_vars_const)) ^ "\n");
val _ = (print "push_env_const_statement="; print_term(concl push_env_const));
val _ = print("push_env_const_hypotheses=" ^ Int.toString(length(hyp push_env_const)) ^ "\n");
val _ = (print "call_env_const_statement="; print_term(concl call_env_const));
val _ = print("call_env_const_hypotheses=" ^ Int.toString(length(hyp call_env_const)) ^ "\n");
val _ = (print "flush_state_const_statement="; print_term(concl flush_state_const));
val _ = print("flush_state_const_hypotheses=" ^ Int.toString(length(hyp flush_state_const)) ^ "\n");
val _ = (print "set_fp_var_const_statement="; print_term(concl set_fp_var_const));
val _ = print("set_fp_var_const_hypotheses=" ^ Int.toString(length(hyp set_fp_var_const)) ^ "\n");
val _ = (print "state_const_statement="; print_term(concl state_const));
val _ = print("state_const_hypotheses=" ^ Int.toString(length(hyp state_const)) ^ "\n");
val _ = (print "dec_clock_const_statement="; print_term(concl dec_clock_const));
val _ = print("dec_clock_const_hypotheses=" ^ Int.toString(length(hyp dec_clock_const)) ^ "\n");
val _ = (print "assign_const_full_statement="; print_term(concl assign_const_full));
val _ = print("assign_const_full_hypotheses=" ^ Int.toString(length(hyp assign_const_full)) ^ "\n");
val _ = (print "assign_const_statement="; print_term(concl assign_const));
val _ = print("assign_const_hypotheses=" ^ Int.toString(length(hyp assign_const)) ^ "\n");
val _ = (print "sh_mem_set_var_const_statement="; print_term(concl sh_mem_set_var_const));
val _ = print("sh_mem_set_var_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_set_var_const)) ^ "\n");
val _ = (print "sh_mem_store_const_statement="; print_term(concl sh_mem_store_const));
val _ = print("sh_mem_store_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store_const)) ^ "\n");
val _ = (print "sh_mem_store_byte_const_statement="; print_term(concl sh_mem_store_byte_const));
val _ = print("sh_mem_store_byte_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store_byte_const)) ^ "\n");
val _ = (print "sh_mem_store16_const_statement="; print_term(concl sh_mem_store16_const));
val _ = print("sh_mem_store16_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store16_const)) ^ "\n");
val _ = (print "sh_mem_store32_const_statement="; print_term(concl sh_mem_store32_const));
val _ = print("sh_mem_store32_const_hypotheses=" ^ Int.toString(length(hyp sh_mem_store32_const)) ^ "\n");
val _ = (print "get_var_set_store_statement="; print_term(concl get_var_set_store));
val _ = print("get_var_set_store_hypotheses=" ^ Int.toString(length(hyp get_var_set_store)) ^ "\n");
val _ = (print "get_var_set_fp_var_statement="; print_term(concl get_var_set_fp_var));
val _ = print("get_var_set_fp_var_hypotheses=" ^ Int.toString(length(hyp get_var_set_fp_var)) ^ "\n");
val _ = (print "get_store_set_store_statement="; print_term(concl get_store_set_store));
val _ = print("get_store_set_store_hypotheses=" ^ Int.toString(length(hyp get_store_set_store)) ^ "\n");
val _ = (print "get_fp_var_set_fp_var_statement="; print_term(concl get_fp_var_set_fp_var));
val _ = print("get_fp_var_set_fp_var_hypotheses=" ^ Int.toString(length(hyp get_fp_var_set_fp_var)) ^ "\n");
val _ = (print "inst_const_statement="; print_term(concl inst_const));
val _ = print("inst_const_hypotheses=" ^ Int.toString(length(hyp inst_const)) ^ "\n");
val _ = (print "get_var_with_const_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl get_var_with_const));
val _ = (print "sh_mem_set_var_const_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl sh_mem_set_var_const));
