load "bossLib"; load "preamble"; load "word_unreachTheory";
open HolKernel Parse bossLib preamble word_unreachTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "uc_skip" ``remove_unreach (Skip:8 wordLang$prog) = Skip``;
val _ = out "uc_skip_seq" ``remove_unreach (Seq Skip Tick:8 wordLang$prog) = Tick``;
val _ = out "uc_raise" ``remove_unreach (Seq (Raise 1) (Inst (Const 2 7w)):8 wordLang$prog) = Raise 1``;
val _ = out "uc_return" ``remove_unreach (Seq (Return 1 [2]) Tick:8 wordLang$prog) = Return 1 [2]``;
val _ = out "uc_break" ``remove_unreach (Seq (Break 0) Tick:8 wordLang$prog) = Break 0``;
val _ = out "uc_continue" ``remove_unreach (Seq (Continue 0) Tick:8 wordLang$prog) = Continue 0``;
val _ = out "uc_tail" ``remove_unreach (Seq (Call NONE (SOME 7) [] NONE) Tick:8 wordLang$prog) = Call NONE (SOME 7) [] NONE``;
val _ = out "uc_merge" ``remove_unreach (Seq (Move 1 [(1,2)]) (Move 0 [(3,1)]):8 wordLang$prog) = Move 1 [(3,2);(1,2)]``;
val _ = out "uc_overlap" ``remove_unreach (Seq (Move 0 [(1,2)]) (Move 1 [(1,3)]):8 wordLang$prog) = Move 1 [(1,3)]``;
val _ = out "uc_rest" ``remove_unreach (Seq (Move 1 [(1,2)]) (Seq (Move 0 [(3,1)]) Tick):8 wordLang$prog) = Seq (Move 1 [(3,2);(1,2)]) Tick``;
val _ = out "uc_assoc" ``remove_unreach (Seq (Seq Tick Tick) Tick:8 wordLang$prog) = Seq Tick (Seq Tick Tick)``;
val _ = out "uc_loop" ``remove_unreach (Loop LN (Seq (Raise 1) Tick) LN:8 wordLang$prog) = Loop LN (Raise 1) LN``;
val _ = out "uc_must" ``remove_unreach (MustTerminate (Seq (Return 1 []) Tick):8 wordLang$prog) = MustTerminate (Return 1 [])``;
val _ = out "uc_if" ``remove_unreach (If Equal 1 (Imm 0w) (Seq (Raise 2) Tick) (Seq Skip Tick):8 wordLang$prog) = If Equal 1 (Imm 0w) (Raise 2) Tick``;
val _ = out "uc_tail_handler" ``remove_unreach (Call NONE (SOME 7) [] (SOME(1,Seq (Raise 2) Tick,3,4)):8 wordLang$prog) = Call NONE (SOME 7) [] (SOME(1,Seq (Raise 2) Tick,3,4))``;
val _ = out "uc_both" ``remove_unreach (Call (SOME([], (LN,LN),Seq (Raise 2) Tick,3,4)) (SOME 7) [] (SOME(1,Seq (Break 0) Tick,5,6)):8 wordLang$prog) = Call (SOME([], (LN,LN),Raise 2,3,4)) (SOME 7) [] (SOME(1,Break 0,5,6))``;
