load "preamble"; load "word_cseProofTheory";
open HolKernel Parse bossLib preamble word_cseTheory word_cseProofTheory;
val _ = Globals.linewidth := 2000;
val _ = (print "rk_statement_firstRegOfArith="; print_thm firstRegOfArith_def; print "\n");
val _ = (print "rk_statement_arithWrites="; print_thm arithWrites_def; print "\n");
val _ = (print "rk_statement_arithReads="; print_thm arithReads_def; print "\n");
val _ = (print "rk_statement_fpWrites="; print_thm fpWrites_def; print "\n");
val _ = (print "rk_statement_can_mem_arith="; print_thm can_mem_arith_def; print "\n");
val _ = (print "rk_statement_is_store="; print_thm is_store_def; print "\n");
val _ = (print "rk_statement_wordToNum_unique="; print_thm wordToNum_unique; print "\n");
val _ = (print "rk_statement_arithOpToNum_eq="; print_thm arithOpToNum_eq; print "\n");
val _ = (print "rk_statement_memOpToNum_eq="; print_thm memOpToNum_eq; print "\n");
val _ = (print "rk_statement_shiftToNum_eq="; print_thm shiftToNum_eq; print "\n");
fun typ label q = (print(label ^ "="); print_type(type_of q); print "\n");
val _ = typ "rk_type_firstRegOfArith" ``firstRegOfArith``;
val _ = typ "rk_type_arithWrites" ``arithWrites``;
val _ = typ "rk_type_arithReads" ``arithReads``;
val _ = typ "rk_type_fpWrites" ``fpWrites``;
val _ = typ "rk_type_can_mem_arith" ``can_mem_arith``;
val _ = typ "rk_type_is_store" ``is_store``;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "rk_a0_firstRegOfArith_8" ``firstRegOfArith (Binop Add 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a0_arithWrites_8" ``arithWrites (Binop Add 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a0_arithReads_8" ``arithReads (Binop Add 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a0_can_mem_arith_8" ``can_mem_arith (Binop Add 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a1_firstRegOfArith_8" ``firstRegOfArith (Binop Sub 99 4 (Imm 255w):8 arith)``;
val _ = out "rk_a1_arithWrites_8" ``arithWrites (Binop Sub 99 4 (Imm 255w):8 arith)``;
val _ = out "rk_a1_arithReads_8" ``arithReads (Binop Sub 99 4 (Imm 255w):8 arith)``;
val _ = out "rk_a1_can_mem_arith_8" ``can_mem_arith (Binop Sub 99 4 (Imm 255w):8 arith)``;
val _ = out "rk_a2_firstRegOfArith_8" ``firstRegOfArith (Shift Ror 99 3 (Imm 255w):8 arith)``;
val _ = out "rk_a2_arithWrites_8" ``arithWrites (Shift Ror 99 3 (Imm 255w):8 arith)``;
val _ = out "rk_a2_arithReads_8" ``arithReads (Shift Ror 99 3 (Imm 255w):8 arith)``;
val _ = out "rk_a2_can_mem_arith_8" ``can_mem_arith (Shift Ror 99 3 (Imm 255w):8 arith)``;
val _ = out "rk_a3_firstRegOfArith_8" ``firstRegOfArith (Shift Lsl 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a3_arithWrites_8" ``arithWrites (Shift Lsl 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a3_arithReads_8" ``arithReads (Shift Lsl 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a3_can_mem_arith_8" ``can_mem_arith (Shift Lsl 99 3 (Reg 5):8 arith)``;
val _ = out "rk_a4_firstRegOfArith_8" ``firstRegOfArith (Div 99 3 5:8 arith)``;
val _ = out "rk_a4_arithWrites_8" ``arithWrites (Div 99 3 5:8 arith)``;
val _ = out "rk_a4_arithReads_8" ``arithReads (Div 99 3 5:8 arith)``;
val _ = out "rk_a4_can_mem_arith_8" ``can_mem_arith (Div 99 3 5:8 arith)``;
val _ = out "rk_a5_firstRegOfArith_8" ``firstRegOfArith (LongMul 99 98 3 5:8 arith)``;
val _ = out "rk_a5_arithWrites_8" ``arithWrites (LongMul 99 98 3 5:8 arith)``;
val _ = out "rk_a5_arithReads_8" ``arithReads (LongMul 99 98 3 5:8 arith)``;
val _ = out "rk_a5_can_mem_arith_8" ``can_mem_arith (LongMul 99 98 3 5:8 arith)``;
val _ = out "rk_a6_firstRegOfArith_8" ``firstRegOfArith (LongDiv 99 98 3 5 7:8 arith)``;
val _ = out "rk_a6_arithWrites_8" ``arithWrites (LongDiv 99 98 3 5 7:8 arith)``;
val _ = out "rk_a6_arithReads_8" ``arithReads (LongDiv 99 98 3 5 7:8 arith)``;
val _ = out "rk_a6_can_mem_arith_8" ``can_mem_arith (LongDiv 99 98 3 5 7:8 arith)``;
val _ = out "rk_a7_firstRegOfArith_8" ``firstRegOfArith (AddCarry 99 3 5 98:8 arith)``;
val _ = out "rk_a7_arithWrites_8" ``arithWrites (AddCarry 99 3 5 98:8 arith)``;
val _ = out "rk_a7_arithReads_8" ``arithReads (AddCarry 99 3 5 98:8 arith)``;
val _ = out "rk_a7_can_mem_arith_8" ``can_mem_arith (AddCarry 99 3 5 98:8 arith)``;
val _ = out "rk_a8_firstRegOfArith_8" ``firstRegOfArith (AddOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a8_arithWrites_8" ``arithWrites (AddOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a8_arithReads_8" ``arithReads (AddOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a8_can_mem_arith_8" ``can_mem_arith (AddOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a9_firstRegOfArith_8" ``firstRegOfArith (SubOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a9_arithWrites_8" ``arithWrites (SubOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a9_arithReads_8" ``arithReads (SubOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a9_can_mem_arith_8" ``can_mem_arith (SubOverflow 99 3 5 98:8 arith)``;
val _ = out "rk_a0_firstRegOfArith_80" ``firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a0_arithWrites_80" ``arithWrites (Binop Add 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a0_arithReads_80" ``arithReads (Binop Add 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a0_can_mem_arith_80" ``can_mem_arith (Binop Add 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a1_firstRegOfArith_80" ``firstRegOfArith (Binop Sub 99 4 (Imm 255w):80 arith)``;
val _ = out "rk_a1_arithWrites_80" ``arithWrites (Binop Sub 99 4 (Imm 255w):80 arith)``;
val _ = out "rk_a1_arithReads_80" ``arithReads (Binop Sub 99 4 (Imm 255w):80 arith)``;
val _ = out "rk_a1_can_mem_arith_80" ``can_mem_arith (Binop Sub 99 4 (Imm 255w):80 arith)``;
val _ = out "rk_a2_firstRegOfArith_80" ``firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)``;
val _ = out "rk_a2_arithWrites_80" ``arithWrites (Shift Ror 99 3 (Imm 255w):80 arith)``;
val _ = out "rk_a2_arithReads_80" ``arithReads (Shift Ror 99 3 (Imm 255w):80 arith)``;
val _ = out "rk_a2_can_mem_arith_80" ``can_mem_arith (Shift Ror 99 3 (Imm 255w):80 arith)``;
val _ = out "rk_a3_firstRegOfArith_80" ``firstRegOfArith (Shift Lsl 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a3_arithWrites_80" ``arithWrites (Shift Lsl 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a3_arithReads_80" ``arithReads (Shift Lsl 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a3_can_mem_arith_80" ``can_mem_arith (Shift Lsl 99 3 (Reg 5):80 arith)``;
val _ = out "rk_a4_firstRegOfArith_80" ``firstRegOfArith (Div 99 3 5:80 arith)``;
val _ = out "rk_a4_arithWrites_80" ``arithWrites (Div 99 3 5:80 arith)``;
val _ = out "rk_a4_arithReads_80" ``arithReads (Div 99 3 5:80 arith)``;
val _ = out "rk_a4_can_mem_arith_80" ``can_mem_arith (Div 99 3 5:80 arith)``;
val _ = out "rk_a5_firstRegOfArith_80" ``firstRegOfArith (LongMul 99 98 3 5:80 arith)``;
val _ = out "rk_a5_arithWrites_80" ``arithWrites (LongMul 99 98 3 5:80 arith)``;
val _ = out "rk_a5_arithReads_80" ``arithReads (LongMul 99 98 3 5:80 arith)``;
val _ = out "rk_a5_can_mem_arith_80" ``can_mem_arith (LongMul 99 98 3 5:80 arith)``;
val _ = out "rk_a6_firstRegOfArith_80" ``firstRegOfArith (LongDiv 99 98 3 5 7:80 arith)``;
val _ = out "rk_a6_arithWrites_80" ``arithWrites (LongDiv 99 98 3 5 7:80 arith)``;
val _ = out "rk_a6_arithReads_80" ``arithReads (LongDiv 99 98 3 5 7:80 arith)``;
val _ = out "rk_a6_can_mem_arith_80" ``can_mem_arith (LongDiv 99 98 3 5 7:80 arith)``;
val _ = out "rk_a7_firstRegOfArith_80" ``firstRegOfArith (AddCarry 99 3 5 98:80 arith)``;
val _ = out "rk_a7_arithWrites_80" ``arithWrites (AddCarry 99 3 5 98:80 arith)``;
val _ = out "rk_a7_arithReads_80" ``arithReads (AddCarry 99 3 5 98:80 arith)``;
val _ = out "rk_a7_can_mem_arith_80" ``can_mem_arith (AddCarry 99 3 5 98:80 arith)``;
val _ = out "rk_a8_firstRegOfArith_80" ``firstRegOfArith (AddOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a8_arithWrites_80" ``arithWrites (AddOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a8_arithReads_80" ``arithReads (AddOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a8_can_mem_arith_80" ``can_mem_arith (AddOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a9_firstRegOfArith_80" ``firstRegOfArith (SubOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a9_arithWrites_80" ``arithWrites (SubOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a9_arithReads_80" ``arithReads (SubOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_a9_can_mem_arith_80" ``can_mem_arith (SubOverflow 99 3 5 98:80 arith)``;
val _ = out "rk_fp_fpLess" ``fpWrites (FPLess 99 98 3)``;
val _ = out "rk_fp_fpLessEqual" ``fpWrites (FPLessEqual 99 98 3)``;
val _ = out "rk_fp_fpEqual" ``fpWrites (FPEqual 99 98 3)``;
val _ = out "rk_fp_fpAbs" ``fpWrites (FPAbs 99 98)``;
val _ = out "rk_fp_fpNeg" ``fpWrites (FPNeg 99 98)``;
val _ = out "rk_fp_fpSqrt" ``fpWrites (FPSqrt 99 98)``;
val _ = out "rk_fp_fpAdd" ``fpWrites (FPAdd 99 98 3)``;
val _ = out "rk_fp_fpSub" ``fpWrites (FPSub 99 98 3)``;
val _ = out "rk_fp_fpMul" ``fpWrites (FPMul 99 98 3)``;
val _ = out "rk_fp_fpDiv" ``fpWrites (FPDiv 99 98 3)``;
val _ = out "rk_fp_fpFma" ``fpWrites (FPFma 99 98 3)``;
val _ = out "rk_fp_fpMov" ``fpWrites (FPMov 99 98)``;
val _ = out "rk_fp_fpMovToReg" ``fpWrites (FPMovToReg 99 98 3)``;
val _ = out "rk_fp_fpMovFromReg" ``fpWrites (FPMovFromReg 99 98 3)``;
val _ = out "rk_fp_fpToInt" ``fpWrites (FPToInt 99 98)``;
val _ = out "rk_fp_fpFromInt" ``fpWrites (FPFromInt 99 98)``;
val _ = out "rk_store_load" ``is_store Load``;
val _ = out "rk_store_load8" ``is_store Load8``;
val _ = out "rk_store_load16" ``is_store Load16``;
val _ = out "rk_store_load32" ``is_store Load32``;
val _ = out "rk_store_store" ``is_store Store``;
val _ = out "rk_store_store8" ``is_store Store8``;
val _ = out "rk_store_store16" ``is_store Store16``;
val _ = out "rk_store_store32" ``is_store Store32``;
val replay_wordToNum_unique = prove(concl wordToNum_unique, gvs [wordToNum_def]);
val _ = (if null(hyp replay_wordToNum_unique) then () else raise Fail "open premise"; print "rk_replay_wordToNum_unique="; print_thm replay_wordToNum_unique; print "\n");
val replay_arithOpToNum_eq = prove(concl arithOpToNum_eq, strip_tac >> Cases_on `op1` >> Cases_on `op2` >> gvs [arithOpToNum_def]);
val _ = (if null(hyp replay_arithOpToNum_eq) then () else raise Fail "open premise"; print "rk_replay_arithOpToNum_eq="; print_thm replay_arithOpToNum_eq; print "\n");
val replay_memOpToNum_eq = prove(concl memOpToNum_eq, strip_tac >> Cases_on `op1` >> Cases_on `op2` >> gvs [memOpToNum_def]);
val _ = (if null(hyp replay_memOpToNum_eq) then () else raise Fail "open premise"; print "rk_replay_memOpToNum_eq="; print_thm replay_memOpToNum_eq; print "\n");
val replay_shiftToNum_eq = prove(concl shiftToNum_eq, Cases >> Cases >> gvs [shiftToNum_def]);
val _ = (if null(hyp replay_shiftToNum_eq) then () else raise Fail "open premise"; print "rk_replay_shiftToNum_eq="; print_thm replay_shiftToNum_eq; print "\n");
