load "bossLib"; load "preamble"; load "word_to_wordTheory";
open bossLib HolKernel Parse preamble word_to_wordTheory;
val th = DB.fetch "word_to_word" "next_n_oracle_def";
val _ = show_types := true;
val _ = print "next_n_oracle=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print "next_n_oracle_types=";
val _ = app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";")) (fst (strip_forall (concl th)) @ free_vars (concl th));
val _ = print "\n";
val _ = print ("next_n_oracle_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val _ = show_types := false;
val _ = print "next_n_oracle_proved=";
val _ = print_term (rhs (concl (EQT_INTRO (prove (concl th, ACCEPT_TAC th)))));
val _ = print "\n";
val _ = show_types := true;
val _ = print "config_reg_alg_type="; val _ = print (type_to_string (type_of ``\(c:word_to_word$config). c.reg_alg``)); val _ = print "\n";
val _ = print "config_col_oracle_type="; val _ = print (type_to_string (type_of ``\(c:word_to_word$config). c.col_oracle``)); val _ = print "\n";
val _ = show_types := false;
val _ = print "oracle_zero="; val _ = print_term (rhs (concl (EVAL ``next_n_oracle 0 [SOME (sptree$insert 7 9 LN);NONE]``))); val _ = print "\n";
val _ = print "oracle_equal="; val _ = print_term (rhs (concl (EVAL ``next_n_oracle 2 [SOME (sptree$insert 7 9 LN);NONE]``))); val _ = print "\n";
val _ = print "oracle_short="; val _ = print_term (rhs (concl (EVAL ``next_n_oracle 3 [SOME (sptree$insert 7 9 LN);NONE]``))); val _ = print "\n";
val _ = print "oracle_long="; val _ = print_term (rhs (concl (EVAL ``next_n_oracle 1 [SOME (sptree$insert 7 9 LN);NONE]``))); val _ = print "\n";
