load "preamble";
load "word_to_stackTheory";
load "stackPropsTheory";
load "wordConvsTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory stackPropsTheory wordConvsTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "fe_move_1" ``let p = (wordLang$Move 9 [(2,4);(4,2);(6,2)] : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_return_1" ``let p = (wordLang$Return 999 [2;4;6] : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_heap_1" ``let p = (wordLang$OpCurrHeap Add 999 3 : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_set_1" ``let p = (wordLang$Set CurrHeap (Var 999) : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_get_1" ``let p = (wordLang$Get 999 CurrHeap : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_alloc_1" ``let p = (wordLang$Alloc 999 (BS LN () LN,BN LN LN) : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_consts_1" ``let p = (wordLang$StoreConsts 999 3 5 7 [(T,4w);(F,7w)] : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_loc_1" ``let p = (wordLang$LocValue 999 777 : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_install_1" ``let p = (wordLang$Install 999 3 5 7 (BS LN () LN,BN LN LN) : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_code_1" ``let p = (wordLang$CodeBufferWrite 999 3 : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_data_1" ``let p = (wordLang$DataBufferWrite 999 3 : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_ffi_1" ``let p = (wordLang$FFI (implode "ffi") 999 3 5 7 (BS LN () LN,BN LN LN) : 1 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:1 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (0,0,0)))``;
val _ = out "fe_move_32" ``let p = (wordLang$Move 9 [(2,4);(4,2);(6,2)] : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_return_32" ``let p = (wordLang$Return 999 [2;4;6] : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_heap_32" ``let p = (wordLang$OpCurrHeap Add 999 3 : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_set_32" ``let p = (wordLang$Set CurrHeap (Var 999) : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_get_32" ``let p = (wordLang$Get 999 CurrHeap : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_alloc_32" ``let p = (wordLang$Alloc 999 (BS LN () LN,BN LN LN) : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_consts_32" ``let p = (wordLang$StoreConsts 999 3 5 7 [(T,4w);(F,7w)] : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_loc_32" ``let p = (wordLang$LocValue 999 777 : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_install_32" ``let p = (wordLang$Install 999 3 5 7 (BS LN () LN,BN LN LN) : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_code_32" ``let p = (wordLang$CodeBufferWrite 999 3 : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_data_32" ``let p = (wordLang$DataBufferWrite 999 3 : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_ffi_32" ``let p = (wordLang$FFI (implode "ffi") 999 3 5 7 (BS LN () LN,BN LN LN) : 32 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:32 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_move_64" ``let p = (wordLang$Move 9 [(2,4);(4,2);(6,2)] : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_return_64" ``let p = (wordLang$Return 999 [2;4;6] : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_heap_64" ``let p = (wordLang$OpCurrHeap Add 999 3 : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_set_64" ``let p = (wordLang$Set CurrHeap (Var 999) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_get_64" ``let p = (wordLang$Get 999 CurrHeap : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_alloc_64" ``let p = (wordLang$Alloc 999 (BS LN () LN,BN LN LN) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_consts_64" ``let p = (wordLang$StoreConsts 999 3 5 7 [(T,4w);(F,7w)] : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_loc_64" ``let p = (wordLang$LocValue 999 777 : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_install_64" ``let p = (wordLang$Install 999 3 5 7 (BS LN () LN,BN LN LN) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_code_64" ``let p = (wordLang$CodeBufferWrite 999 3 : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_data_64" ``let p = (wordLang$DataBufferWrite 999 3 : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_ffi_64" ``let p = (wordLang$FFI (implode "ffi") 999 3 5 7 (BS LN () LN,BN LN LN) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) F p (Append (List [4w]) (List [7w]),17) (4,1,2)))``;
val _ = out "fe_move_80" ``let p = (wordLang$Move 9 [(2,4);(4,2);(6,2)] : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_return_80" ``let p = (wordLang$Return 999 [2;4;6] : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_heap_80" ``let p = (wordLang$OpCurrHeap Add 999 3 : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_set_80" ``let p = (wordLang$Set CurrHeap (Var 999) : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_get_80" ``let p = (wordLang$Get 999 CurrHeap : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_alloc_80" ``let p = (wordLang$Alloc 999 (BS LN () LN,BN LN LN) : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_consts_80" ``let p = (wordLang$StoreConsts 999 3 5 7 [(T,4w);(F,7w)] : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_loc_80" ``let p = (wordLang$LocValue 999 777 : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_install_80" ``let p = (wordLang$Install 999 3 5 7 (BS LN () LN,BN LN LN) : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_code_80" ``let p = (wordLang$CodeBufferWrite 999 3 : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_data_80" ``let p = (wordLang$DataBufferWrite 999 3 : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_ffi_80" ``let p = (wordLang$FFI (implode "ffi") 999 3 5 7 (BS LN () LN,BN LN LN) : 80 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:80 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (9,999,3)))``;
val _ = out "fe_set_bitmap" ``let p = (wordLang$Set BitmapBase (Var 999) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_set_const" ``let p = (wordLang$Set CurrHeap (Const 9w) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_set_lookup" ``let p = (wordLang$Set (Temp 31w) (Lookup CurrHeap) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_set_load" ``let p = (wordLang$Set CurrHeap (Load (Var 999)) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_set_op" ``let p = (wordLang$Set CurrHeap (Op Add [Var 999;Const 9w]) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = out "fe_set_shift" ``let p = (wordLang$Set CurrHeap (Shift Lsl (Var 999) (Const 9w)) : 64 wordLang$prog) in no_share_inst p /\ no_shmemop (FST (comp (c:64 asm$asm_config) T p (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
