load "bossLib";
load "preamble";
load "word_allocTheory";
open bossLib HolKernel Parse preamble word_allocTheory reg_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = observe "spd_missing_phy" ``sp_default (LN:num num_map) 6``;
val _ = observe "spd_missing_virtual" ``sp_default (LN:num num_map) 7``;
val _ = observe "spd_present_phy" ``sp_default (insert 6 9 LN:num num_map) 6``;
val _ = observe "spd_present_virtual" ``sp_default (insert 7 4 LN:num num_map) 7``;
val _ = observe "spd_present_zero" ``sp_default (insert 6 0 LN:num num_map) 6``;
val _ = observe "spd_raw_bs" ``sp_default (BS LN 5 LN:num num_map) 0``;
val _ = observe "spd_raw_bn_hit" ``sp_default (BN LN (LS 8):num num_map) 1``;
val _ = observe "spd_raw_bn_miss" ``sp_default (BN LN (LS 8):num num_map) 2``;
val _ = observe "spd_large_phy" ``sp_default (LN:num num_map) 36893488147419103232``;
val _ = observe "spd_large_virtual" ``sp_default (LN:num num_map) 36893488147419103233``;
val _ = observe "tc_missing_phy" ``(total_colour (LN:num num_map) 6, ((\x. 2 * x) o sp_default (LN:num num_map)) 6)``;
val _ = observe "tc_missing_virtual" ``(total_colour (LN:num num_map) 7, ((\x. 2 * x) o sp_default (LN:num num_map)) 7)``;
val _ = observe "tc_present" ``(total_colour (insert 6 9 LN:num num_map) 6, ((\x. 2 * x) o sp_default (insert 6 9 LN:num num_map)) 6)``;
val _ = observe "tc_raw" ``(total_colour (BN LN (LS 8):num num_map) 1, ((\x. 2 * x) o sp_default (BN LN (LS 8):num num_map)) 1)``;
val _ = observe "tc_large" ``(total_colour (LN:num num_map) 36893488147419103232, ((\x. 2 * x) o sp_default (LN:num num_map)) 36893488147419103232)``;
