load "preamble";
load "wordPropsTheory";
open bossLib HolKernel Parse preamble wordPropsTheory wordConvsTheory sptreeTheory;
val _ = Globals.linewidth := 1000;
val _ = (print "nic_def=";print_thm no_install_code_def;print "\n");
fun typ label t = (print(label ^ "=");print_type(type_of t);print "\n");
val _ = typ "nic_code_type" ``(code:(num # 'a wordLang$prog) spt)``;
val _ = typ "nic_program_type" ``(p:'a wordLang$prog)``;
val _ = typ "nic_argument_type" ``(n:num)``;
fun out label q = (print(label ^ "=");print_term(rconc(EVAL q));print "\n");
val _ = out "nic_empty_1" ``(case lookup 0 (LN:(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = NONE``;
val _ = out "nic_leaf_zero_1" ``(case lookup 0 (LS (999,wordLang$Skip):(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(999,T)``;
val _ = out "nic_leaf_missing_1" ``(case lookup 7 (LS (999,wordLang$Skip):(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = NONE``;
val _ = out "nic_bad_leaf_1" ``(case lookup 0 (LS (7,wordLang$Install 0 1 2 3 (LN,LN)):(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(7,F)``;
val _ = out "nic_malformed_empty_1" ``(case lookup 3 (BN LN LN:(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = NONE``;
val _ = out "nic_malformed_value_1" ``(case lookup 0 (BS LN (17,wordLang$Skip) LN:(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(17,T)``;
val _ = out "nic_nested_left_1" ``(case lookup 2 (BN (LS (8,wordLang$Tick)) (LS (9,wordLang$Install 0 1 2 3 (LN,LN))):(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(8,T)``;
val _ = out "nic_nested_right_1" ``(case lookup 1 (BN (LS (8,wordLang$Tick)) (LS (9,wordLang$Install 0 1 2 3 (LN,LN))):(num # 1 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(9,F)``;
val _ = out "nic_empty_80" ``(case lookup 0 (LN:(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = NONE``;
val _ = out "nic_leaf_zero_80" ``(case lookup 0 (LS (999,wordLang$Skip):(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(999,T)``;
val _ = out "nic_leaf_missing_80" ``(case lookup 7 (LS (999,wordLang$Skip):(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = NONE``;
val _ = out "nic_bad_leaf_80" ``(case lookup 0 (LS (7,wordLang$Install 0 1 2 3 (LN,LN)):(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(7,F)``;
val _ = out "nic_malformed_empty_80" ``(case lookup 3 (BN LN LN:(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = NONE``;
val _ = out "nic_malformed_value_80" ``(case lookup 0 (BS LN (17,wordLang$Skip) LN:(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(17,T)``;
val _ = out "nic_nested_left_80" ``(case lookup 2 (BN (LS (8,wordLang$Tick)) (LS (9,wordLang$Install 0 1 2 3 (LN,LN))):(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(8,T)``;
val _ = out "nic_nested_right_80" ``(case lookup 1 (BN (LS (8,wordLang$Tick)) (LS (9,wordLang$Install 0 1 2 3 (LN,LN))):(num # 80 wordLang$prog) spt) of NONE => NONE | SOME(n,p) => SOME(n,wordConvs$no_install p)) = SOME(9,F)``;
