load "preamble";
load "word_to_stackTheory";
load "stackPropsTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory stackPropsTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "lh_load_empty" ``let p = (wStackLoad [] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_load_many" ``let p = (wStackLoad [(2,3);(99,0);(2,3)] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_move_zero" ``let p = (stack_move 0 99 7 0 (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_move_many" ``let p = (stack_move 4 2 7 99 (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_aux_zero" ``let p = (copy_ret_aux 0 99 0 : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({},{})``;
val _ = out "lh_aux_many" ``let p = (copy_ret_aux 99 0 4 : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({},{})``;
val _ = out "lh_ret_zero" ``let p = (copy_ret F F (9,0,17) [1;2] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_ret_plain" ``let p = (copy_ret F F (1,0,17) [1;2] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_ret_handler" ``let p = (copy_ret F T (1,7,17) [1;2] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_ret_perf" ``let p = (copy_ret T T (0,7,17) [T;F] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_ret_width_one" ``let p = (copy_ret T F (0,7,17) [T;F] (Call (SOME (LocValue 2 3 6,4,5,6)) (INL 8) (SOME (RawCall 9,7,5))) : 1 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({(8,0);(3,6);(9,1)},{(7,5)})``;
val _ = out "lh_live_zero" ``let p = (FST (wLive (LN,LN) (Nil,99) (0,0,17)) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({},{})``;
val _ = out "lh_live_frame" ``let p = (FST (wLive (LN,LN) (List [8w;2w],1) (0,4,3)) : 64 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({},{})``;
val _ = out "lh_live_width_one" ``let p = (FST (wLive (LN,LN) (List [8w;2w],99) (4,7,3)) : 1 stackLang$prog) in (get_code_labels p, stack_get_handler_labels 7 p) = ({},{})``;

