load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory word_to_stackTheory stackPropsTheory;
val _ = Globals.linewidth := 1000000;
val _ = numLib.temp_prefer_num();
fun theoremRow label th = (if null(hyp th) then () else raise Fail "open premise"; print(label ^ "="); print_thm th; print "\n");
val full = prove(``!c perf p bs frame. perf=F ==> alloc_arg (FST (comp c perf p bs frame))``, metis_tac[word_to_stack_alloc_arg]);
val _ = theoremRow "aac_full" full;
fun emit label q = (print(label ^ "="); print_term(rconc(SIMP_CONV (srw_ss()) [full] q)); print "\n");
val _ = emit "aac_1_must" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (MustTerminate (Seq (Alloc 999 (LN,LN)) Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_1_loop" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (Loop (BN LN LN) (Alloc 999 (LN,LN)) (BS LN () LN)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_1_seq" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (Seq (MustTerminate Tick) (Alloc 999 (LN,LN))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_1_if" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (If Equal 999 (Imm 7w) (Alloc 999 (LN,LN)) (MustTerminate Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_1_tail" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (Call NONE NONE [2;4;6] (SOME(999,Alloc 999 (LN,LN),7,8))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_1_ret" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (Call (SOME([2;4;6],(LN,LN),Alloc 999 (LN,LN),7,8)) (SOME 17) [2;4] NONE) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_1_handler" ``alloc_arg (FST (comp (c:1 asm$asm_config) F (Call (SOME([],(LN,LN),MustTerminate Tick,7,8)) NONE [] (SOME(999,Alloc 999 (LN,LN),9,10))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_must" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (MustTerminate (Seq (Alloc 999 (LN,LN)) Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_loop" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (Loop (BN LN LN) (Alloc 999 (LN,LN)) (BS LN () LN)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_seq" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (Seq (MustTerminate Tick) (Alloc 999 (LN,LN))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_if" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (If Equal 999 (Imm 7w) (Alloc 999 (LN,LN)) (MustTerminate Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_tail" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (Call NONE NONE [2;4;6] (SOME(999,Alloc 999 (LN,LN),7,8))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_ret" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (Call (SOME([2;4;6],(LN,LN),Alloc 999 (LN,LN),7,8)) (SOME 17) [2;4] NONE) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_2_handler" ``alloc_arg (FST (comp (c:2 asm$asm_config) F (Call (SOME([],(LN,LN),MustTerminate Tick,7,8)) NONE [] (SOME(999,Alloc 999 (LN,LN),9,10))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_must" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (MustTerminate (Seq (Alloc 999 (LN,LN)) Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_loop" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (Loop (BN LN LN) (Alloc 999 (LN,LN)) (BS LN () LN)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_seq" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (Seq (MustTerminate Tick) (Alloc 999 (LN,LN))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_if" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (If Equal 999 (Imm 7w) (Alloc 999 (LN,LN)) (MustTerminate Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_tail" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (Call NONE NONE [2;4;6] (SOME(999,Alloc 999 (LN,LN),7,8))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_ret" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (Call (SOME([2;4;6],(LN,LN),Alloc 999 (LN,LN),7,8)) (SOME 17) [2;4] NONE) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_8_handler" ``alloc_arg (FST (comp (c:8 asm$asm_config) F (Call (SOME([],(LN,LN),MustTerminate Tick,7,8)) NONE [] (SOME(999,Alloc 999 (LN,LN),9,10))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_must" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (MustTerminate (Seq (Alloc 999 (LN,LN)) Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_loop" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (Loop (BN LN LN) (Alloc 999 (LN,LN)) (BS LN () LN)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_seq" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (Seq (MustTerminate Tick) (Alloc 999 (LN,LN))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_if" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (If Equal 999 (Imm 7w) (Alloc 999 (LN,LN)) (MustTerminate Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_tail" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (Call NONE NONE [2;4;6] (SOME(999,Alloc 999 (LN,LN),7,8))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_ret" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (Call (SOME([2;4;6],(LN,LN),Alloc 999 (LN,LN),7,8)) (SOME 17) [2;4] NONE) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_64_handler" ``alloc_arg (FST (comp (c:64 asm$asm_config) F (Call (SOME([],(LN,LN),MustTerminate Tick,7,8)) NONE [] (SOME(999,Alloc 999 (LN,LN),9,10))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_must" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (MustTerminate (Seq (Alloc 999 (LN,LN)) Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_loop" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (Loop (BN LN LN) (Alloc 999 (LN,LN)) (BS LN () LN)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_seq" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (Seq (MustTerminate Tick) (Alloc 999 (LN,LN))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_if" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (If Equal 999 (Imm 7w) (Alloc 999 (LN,LN)) (MustTerminate Tick)) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_tail" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (Call NONE NONE [2;4;6] (SOME(999,Alloc 999 (LN,LN),7,8))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_ret" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (Call (SOME([2;4;6],(LN,LN),Alloc 999 (LN,LN),7,8)) (SOME 17) [2;4] NONE) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
val _ = emit "aac_80_handler" ``alloc_arg (FST (comp (c:80 asm$asm_config) F (Call (SOME([],(LN,LN),MustTerminate Tick,7,8)) NONE [] (SOME(999,Alloc 999 (LN,LN),9,10))) (Append (List [4w]) (List [7w]),17) (2,7,9)))``;
