load "bossLib";
load "preamble";
load "word_allocTheory";
open bossLib HolKernel Parse preamble word_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = observe "hc_merge_empty" ``heu_merge_call LN LN = LN``;
val _ = observe "hc_merge_left" ``heu_merge_call (insert 1 () LN) LN = insert 1 () LN``;
val _ = observe "hc_merge_right" ``heu_merge_call LN (insert 2 () LN) = insert 2 () LN``;
val _ = observe "hc_merge_overlap" ``heu_merge_call (insert 1 () LN) (insert 1 () LN) = insert 1 () LN``;
val _ = observe "hc_merge_disjoint" ``heu_merge_call (insert 1 () LN) (insert 2 () LN) = insert 1 () (insert 2 () LN)``;
val _ = observe "hc_merge_raw_left" ``heu_merge_call (BN LN LN) LN = BN LN LN``;
val _ = observe "hc_merge_raw_right" ``heu_merge_call LN (BN LN LN) = BN LN LN``;
val _ = observe "hc_merge_raw_root" ``heu_merge_call (BN LN LN) (LS ()) = BS LN () LN``;
val _ = observe "hc_add_empty" ``add_call (LN : num num_map) (insert 3 () LN) = insert 3 () LN``;
val _ = observe "hc_add_nat" ``add_call (insert 1 18446744073709551616 LN) LN = insert 1 () LN``;
val _ = observe "hc_add_bool" ``add_call (insert 2 F LN) (insert 1 () LN) = insert 1 () (insert 2 () LN)``;
val _ = observe "hc_add_tuple" ``add_call (insert 5 ((2:num),3,5,7,11) LN) (insert 5 () LN) = insert 5 () LN``;
val _ = observe "hc_add_nested" ``add_call (insert 1 F (insert 5 T (insert 6 F LN))) (insert 2 () (insert 6 () LN)) = insert 1 () (insert 2 () (insert 5 () (insert 6 () LN)))``;
val _ = observe "hc_add_raw_bn" ``add_call (BN LN LN : num num_map) LN = BN LN LN``;
val _ = observe "hc_add_raw_bs" ``add_call (BS LN F LN) LN = BS LN () LN``;
val _ = observe "hc_add_raw_overlap" ``add_call (BS LN F LN) (LS ()) = BS LN () LN``;
