load "preamble"; load "word_cseTheory";
open HolKernel Parse bossLib preamble word_cseTheory;
val _ = Globals.linewidth := 1000;
val _ = (print "key_def_wordToNum="; print_thm wordToNum_def; print "\n");
val _ = (print "key_def_shiftToNum="; print_thm shiftToNum_def; print "\n");
val _ = (print "key_def_arithOpToNum="; print_thm arithOpToNum_def; print "\n");
val _ = (print "key_def_regImmToNumList="; print_thm regImmToNumList_def; print "\n");
val _ = (print "key_def_arithToNumList="; print_thm arithToNumList_def; print "\n");
val _ = (print "key_def_memOpToNum="; print_thm memOpToNum_def; print "\n");
val _ = (print "key_def_loadToNumList="; print_thm loadToNumList_def; print "\n");
val _ = (print "key_def_fpToNumList="; print_thm fpToNumList_def; print "\n");
val _ = (print "key_def_instToNumList="; print_thm instToNumList_def; print "\n");
val _ = (print "key_def_OpCurrHeapToNumList="; print_thm OpCurrHeapToNumList_def; print "\n");
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "key_shift_lsl" ``shiftToNum Lsl``;
val _ = out "key_shift_lsr" ``shiftToNum Lsr``;
val _ = out "key_shift_asr" ``shiftToNum Asr``;
val _ = out "key_shift_ror" ``shiftToNum Ror``;
val _ = out "key_op_add" ``arithOpToNum Add``;
val _ = out "key_heap_add" ``OpCurrHeapToNumList Add 7``;
val _ = out "key_op_sub" ``arithOpToNum Sub``;
val _ = out "key_heap_sub" ``OpCurrHeapToNumList Sub 7``;
val _ = out "key_op_and" ``arithOpToNum And``;
val _ = out "key_heap_and" ``OpCurrHeapToNumList And 7``;
val _ = out "key_op_or" ``arithOpToNum Or``;
val _ = out "key_heap_or" ``OpCurrHeapToNumList Or 7``;
val _ = out "key_op_xor" ``arithOpToNum Xor``;
val _ = out "key_heap_xor" ``OpCurrHeapToNumList Xor 7``;
val _ = out "key_mem_load" ``memOpToNum Load``;
val _ = out "key_load_load" ``loadToNumList Load 9 (255w:8 word)``;
val _ = out "key_mem_load8" ``memOpToNum Load8``;
val _ = out "key_load_load8" ``loadToNumList Load8 9 (255w:8 word)``;
val _ = out "key_mem_load16" ``memOpToNum Load16``;
val _ = out "key_load_load16" ``loadToNumList Load16 9 (255w:8 word)``;
val _ = out "key_mem_load32" ``memOpToNum Load32``;
val _ = out "key_load_load32" ``loadToNumList Load32 9 (255w:8 word)``;
val _ = out "key_mem_store" ``memOpToNum Store``;
val _ = out "key_load_store" ``loadToNumList Store 9 (255w:8 word)``;
val _ = out "key_mem_store8" ``memOpToNum Store8``;
val _ = out "key_load_store8" ``loadToNumList Store8 9 (255w:8 word)``;
val _ = out "key_mem_store16" ``memOpToNum Store16``;
val _ = out "key_load_store16" ``loadToNumList Store16 9 (255w:8 word)``;
val _ = out "key_mem_store32" ``memOpToNum Store32``;
val _ = out "key_load_store32" ``loadToNumList Store32 9 (255w:8 word)``;
val _ = out "key_word_1" ``wordToNum (-1w:1 word)``;
val _ = out "key_imm_1" ``regImmToNumList (Imm (-1w:1 word))``;
val _ = out "key_const_1" ``instToNumList (Const 99 (-1w:1 word))``;
val _ = out "key_word_32" ``wordToNum (-1w:32 word)``;
val _ = out "key_imm_32" ``regImmToNumList (Imm (-1w:32 word))``;
val _ = out "key_const_32" ``instToNumList (Const 99 (-1w:32 word))``;
val _ = out "key_word_64" ``wordToNum (-1w:64 word)``;
val _ = out "key_imm_64" ``regImmToNumList (Imm (-1w:64 word))``;
val _ = out "key_const_64" ``instToNumList (Const 99 (-1w:64 word))``;
val _ = out "key_word_80" ``wordToNum (-1w:80 word)``;
val _ = out "key_imm_80" ``regImmToNumList (Imm (-1w:80 word))``;
val _ = out "key_const_80" ``instToNumList (Const 99 (-1w:80 word))``;
val _ = out "key_reg" ``regImmToNumList (Reg 777:8 reg_imm)``;
val _ = out "key_arith_0" ``arithToNumList (Binop Add 99 2 (Reg 3):8 arith)``;
val _ = out "key_inst_arith_0" ``instToNumList (Arith (Binop Add 99 2 (Reg 3)):8 inst)``;
val _ = out "key_arith_1" ``arithToNumList (LongMul 99 98 2 3:8 arith)``;
val _ = out "key_inst_arith_1" ``instToNumList (Arith (LongMul 99 98 2 3):8 inst)``;
val _ = out "key_arith_2" ``arithToNumList (LongDiv 99 98 2 3 4:8 arith)``;
val _ = out "key_inst_arith_2" ``instToNumList (Arith (LongDiv 99 98 2 3 4):8 inst)``;
val _ = out "key_arith_3" ``arithToNumList (Shift Ror 99 2 (Imm 255w):8 arith)``;
val _ = out "key_inst_arith_3" ``instToNumList (Arith (Shift Ror 99 2 (Imm 255w)):8 inst)``;
val _ = out "key_arith_4" ``arithToNumList (Div 99 2 3:8 arith)``;
val _ = out "key_inst_arith_4" ``instToNumList (Arith (Div 99 2 3):8 inst)``;
val _ = out "key_arith_5" ``arithToNumList (AddCarry 99 2 3 98:8 arith)``;
val _ = out "key_inst_arith_5" ``instToNumList (Arith (AddCarry 99 2 3 98):8 inst)``;
val _ = out "key_arith_6" ``arithToNumList (AddOverflow 99 2 3 98:8 arith)``;
val _ = out "key_inst_arith_6" ``instToNumList (Arith (AddOverflow 99 2 3 98):8 inst)``;
val _ = out "key_arith_7" ``arithToNumList (SubOverflow 99 2 3 98:8 arith)``;
val _ = out "key_inst_arith_7" ``instToNumList (Arith (SubOverflow 99 2 3 98):8 inst)``;
val _ = out "key_fp_fpLess" ``fpToNumList (FPLess 99 2 3)``;
val _ = out "key_inst_fpLess" ``instToNumList (FP (FPLess 99 2 3):8 inst)``;
val _ = out "key_fp_fpLessEqual" ``fpToNumList (FPLessEqual 99 2 3)``;
val _ = out "key_inst_fpLessEqual" ``instToNumList (FP (FPLessEqual 99 2 3):8 inst)``;
val _ = out "key_fp_fpEqual" ``fpToNumList (FPEqual 99 2 3)``;
val _ = out "key_inst_fpEqual" ``instToNumList (FP (FPEqual 99 2 3):8 inst)``;
val _ = out "key_fp_fpAbs" ``fpToNumList (FPAbs 99 2)``;
val _ = out "key_inst_fpAbs" ``instToNumList (FP (FPAbs 99 2):8 inst)``;
val _ = out "key_fp_fpNeg" ``fpToNumList (FPNeg 99 2)``;
val _ = out "key_inst_fpNeg" ``instToNumList (FP (FPNeg 99 2):8 inst)``;
val _ = out "key_fp_fpSqrt" ``fpToNumList (FPSqrt 99 2)``;
val _ = out "key_inst_fpSqrt" ``instToNumList (FP (FPSqrt 99 2):8 inst)``;
val _ = out "key_fp_fpAdd" ``fpToNumList (FPAdd 99 2 3)``;
val _ = out "key_inst_fpAdd" ``instToNumList (FP (FPAdd 99 2 3):8 inst)``;
val _ = out "key_fp_fpSub" ``fpToNumList (FPSub 99 2 3)``;
val _ = out "key_inst_fpSub" ``instToNumList (FP (FPSub 99 2 3):8 inst)``;
val _ = out "key_fp_fpMul" ``fpToNumList (FPMul 99 2 3)``;
val _ = out "key_inst_fpMul" ``instToNumList (FP (FPMul 99 2 3):8 inst)``;
val _ = out "key_fp_fpDiv" ``fpToNumList (FPDiv 99 2 3)``;
val _ = out "key_inst_fpDiv" ``instToNumList (FP (FPDiv 99 2 3):8 inst)``;
val _ = out "key_fp_fpFma" ``fpToNumList (FPFma 99 2 3)``;
val _ = out "key_inst_fpFma" ``instToNumList (FP (FPFma 99 2 3):8 inst)``;
val _ = out "key_fp_fpMov" ``fpToNumList (FPMov 99 2)``;
val _ = out "key_inst_fpMov" ``instToNumList (FP (FPMov 99 2):8 inst)``;
val _ = out "key_fp_fpMovToReg" ``fpToNumList (FPMovToReg 99 2 3)``;
val _ = out "key_inst_fpMovToReg" ``instToNumList (FP (FPMovToReg 99 2 3):8 inst)``;
val _ = out "key_fp_fpMovFromReg" ``fpToNumList (FPMovFromReg 99 2 3)``;
val _ = out "key_inst_fpMovFromReg" ``instToNumList (FP (FPMovFromReg 99 2 3):8 inst)``;
val _ = out "key_fp_fpToInt" ``fpToNumList (FPToInt 99 2)``;
val _ = out "key_inst_fpToInt" ``instToNumList (FP (FPToInt 99 2):8 inst)``;
val _ = out "key_fp_fpFromInt" ``fpToNumList (FPFromInt 99 2)``;
val _ = out "key_inst_fpFromInt" ``instToNumList (FP (FPFromInt 99 2):8 inst)``;
val _ = out "key_skip" ``instToNumList (Skip:8 inst)``;
val _ = out "key_mem_inst" ``instToNumList (Mem Load 99 (Addr 2 255w):8 inst)``;
fun typ label q = (print(label ^ "="); print_type(type_of q); print "\n");
val _ = typ "key_type_wordToNum" ``wordToNum``;
val _ = typ "key_type_shiftToNum" ``shiftToNum``;
val _ = typ "key_type_arithOpToNum" ``arithOpToNum``;
val _ = typ "key_type_regImmToNumList" ``regImmToNumList``;
val _ = typ "key_type_arithToNumList" ``arithToNumList``;
val _ = typ "key_type_memOpToNum" ``memOpToNum``;
val _ = typ "key_type_loadToNumList" ``loadToNumList``;
val _ = typ "key_type_fpToNumList" ``fpToNumList``;
val _ = typ "key_type_instToNumList" ``instToNumList``;
val _ = typ "key_type_OpCurrHeapToNumList" ``OpCurrHeapToNumList``;
