load "preamble"; load "word_cseProofTheory";
open HolKernel Parse bossLib preamble word_cseProofTheory word_cseTheory wordSemTheory;
val _ = Globals.linewidth := 2000;
val replay_arith = prove(``  ∀a r w (s:('a,'c,'ffi) wordSem$state).
    can_mem_arith a ∧ ¬MEM r (arithReads a) ⇒
    (evaluate (Inst (Arith a), unset_var r s) =
       (NONE, set_var (firstRegOfArith a) w (unset_var r s)) ⇔
     evaluate (Inst (Arith a), s) = (NONE, set_var (firstRegOfArith a) w s))``,   rpt strip_tac
  \\ Cases_on ‘a’
  \\ gvs [can_mem_arith_def, arithReads_def, firstRegOfArith_def]
  >- (Cases_on ‘r'’ \\ gvs [can_mem_arith_def, arithReads_def]
      >- (gvs [evaluate_def, inst_def, assign_def, word_exp_def, the_words_def,
               get_var_def, set_var_def, unset_var_def, lookup_delete]
          \\ Cases_on ‘lookup n0 s.locals’ \\ gvs []
          \\ Cases_on ‘x’ \\ gvs []
          \\ Cases_on ‘lookup n' s.locals’ \\ gvs []
          \\ Cases_on ‘x’ \\ gvs []
          \\ Cases_on ‘word_op b [c; c']’
          \\ gvs [state_component_equality, insert_eq])
      \\ gvs [evaluate_def, inst_def, assign_def, word_exp_def, the_words_def,
              get_var_def, set_var_def, unset_var_def, lookup_delete]
      \\ Cases_on ‘lookup n0 s.locals’ \\ gvs []
      \\ Cases_on ‘x’ \\ gvs []
      \\ Cases_on ‘word_op b [c'; c]’
      \\ gvs [state_component_equality, insert_eq])
  >- (Cases_on ‘r'’ \\ gvs [can_mem_arith_def, arithReads_def]
      \\ gvs [evaluate_def, inst_def, assign_def, word_exp_def, the_words_def,
              get_var_def, set_var_def, unset_var_def, lookup_delete]
      \\ Cases_on ‘lookup n0 s.locals’ \\ gvs []
      \\ Cases_on ‘x’ \\ gvs []
      \\ Cases_on ‘word_sh s' c' (w2n c)’
      \\ gvs [state_component_equality, insert_eq])
  >- (gvs [evaluate_def, inst_def, assign_def, get_vars_def, get_var_def,
           set_var_def, unset_var_def, lookup_delete]
      \\ Cases_on ‘lookup n1 s.locals’ \\ gvs []
      \\ Cases_on ‘x’ \\ gvs []
      \\ Cases_on ‘lookup n0 s.locals’ \\ gvs []
      \\ Cases_on ‘x’ \\ gvs [state_component_equality, insert_eq]
      \\ Cases_on ‘c = 0w’ \\ gvs [state_component_equality, insert_eq]));
val _ = (if null(hyp replay_arith) then () else raise Fail "open replay premise"; print "del_full_arith="; print_thm replay_arith; print "\n");
val replay_load = prove(``  ∀op r a ofs n w (s:('a,'c,'ffi) wordSem$state).
    ¬is_store op ∧ a ≠ n ⇒
    (evaluate (Inst (Mem op r (Addr a ofs)), unset_var n s) =
       (NONE, set_var r w (unset_var n s)) ⇔
     evaluate (Inst (Mem op r (Addr a ofs)), s) = (NONE, set_var r w s))``,   rpt strip_tac
  \\ Cases_on ‘op’ \\ gvs [is_store_def]
  \\ gvs [evaluate_def, inst_def, word_exp_def, the_words_def, set_var_def,
          unset_var_def, lookup_delete, mem_load_def, get_var_def]
  >- (Cases_on ‘lookup a s.locals’ \\ gvs []
      \\ Cases_on ‘x’ \\ gvs [wordLangTheory.word_op_def]
      \\ IF_CASES_TAC \\ gvs [state_component_equality, insert_eq])
  \\ Cases_on ‘lookup a s.locals’ \\ gvs []
  \\ Cases_on ‘x’ \\ gvs [wordLangTheory.word_op_def]
  \\ TOP_CASE_TAC
  \\ gvs [AllCaseEqs()] \\ gvs [state_component_equality, insert_eq]);
val _ = (if null(hyp replay_load) then () else raise Fail "open replay premise"; print "del_full_load="; print_thm replay_load; print "\n");
fun typ label q = (print(label ^ "="); print_type(type_of q); print "\n");
val _ = typ "del_type_arith" ``(a:'a arith)``;
val _ = typ "del_type_state" ``(s:('a,'c,'ffi)wordSem$state)``;
val _ = typ "del_type_value" ``(w:'a word_loc)``;
val _ = typ "del_type_memory" ``(m:'a word -> 'a word_loc)``;
fun proved label q tac = let val th = prove(q,tac) in if null(hyp th) then () else raise Fail "open application premise"; print(label ^ "="); print_thm th; print "\n" end;
val _ = proved "del_arith_0_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):1 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):1 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):1 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):1 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):1 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):1 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):1 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):1 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):1 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):1 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):1 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):1 arith)),unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):1 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):1 arith)) w (unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):1 arith)) s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):1 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:1 arith)),unset_var (firstRegOfArith (Div 99 3 5:1 arith)) s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:1 arith)) w (unset_var (firstRegOfArith (Div 99 3 5:1 arith)) s))) <=> evaluate (Inst (Arith (Div 99 3 5:1 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:1 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:1 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Div 99 3 5:1 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:1 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):32 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):32 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):32 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):32 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):32 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):32 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):32 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):32 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):32 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):32 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):32 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):32 arith)),unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):32 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):32 arith)) w (unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):32 arith)) s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):32 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:32 arith)),unset_var (firstRegOfArith (Div 99 3 5:32 arith)) s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:32 arith)) w (unset_var (firstRegOfArith (Div 99 3 5:32 arith)) s))) <=> evaluate (Inst (Arith (Div 99 3 5:32 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:32 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:32 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Div 99 3 5:32 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:32 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):64 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):64 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):64 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):64 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):64 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):64 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):64 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):64 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):64 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):64 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):64 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):64 arith)),unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):64 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):64 arith)) w (unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):64 arith)) s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):64 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:64 arith)),unset_var (firstRegOfArith (Div 99 3 5:64 arith)) s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:64 arith)) w (unset_var (firstRegOfArith (Div 99 3 5:64 arith)) s))) <=> evaluate (Inst (Arith (Div 99 3 5:64 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:64 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:64 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Div 99 3 5:64 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:64 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):80 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_0_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_1_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Add 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Add 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):80 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):80 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_2_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_3_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Sub 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Sub 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):80 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):80 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Reg 5):80 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_4_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Reg 5):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Binop And 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_5_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop And 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop And 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):80 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):80 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Reg 5):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_6_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_7_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Or 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Or 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):80 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):80 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_8_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Reg 5):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Reg 5):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_9_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Binop Xor 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Binop Xor 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_10_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsl 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsl 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_11_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Lsr 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Lsr 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_12_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Asr 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Asr 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):80 arith)),unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)) s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)) w (unset_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)) s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_13_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Shift Ror 99 3 (Imm 255w):80 arith)),s) = (NONE,set_var (firstRegOfArith (Shift Ror 99 3 (Imm 255w):80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:80 arith)),unset_var (firstRegOfArith (Div 99 3 5:80 arith)) s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:80 arith)) w (unset_var (firstRegOfArith (Div 99 3 5:80 arith)) s))) <=> evaluate (Inst (Arith (Div 99 3 5:80 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_arith_14_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Arith (Div 99 3 5:80 arith)),unset_var 77 s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:80 arith)) w (unset_var 77 s))) <=> evaluate (Inst (Arith (Div 99 3 5:80 arith)),s) = (NONE,set_var (firstRegOfArith (Div 99 3 5:80 arith)) w s)`` (rpt gen_tac >> match_mp_tac replay_arith >> EVAL_TAC);
val _ = proved "del_load_load_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_99_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_77_1" ``! (w:1 word_loc) (s:(1,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_99_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_77_32" ``! (w:32 word_loc) (s:(32,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_99_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_77_64" ``! (w:64 word_loc) (s:(64,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load8_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load8 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load8 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load16_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load16 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load16 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_99_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 99 s) = (NONE,set_var 99 w (unset_var 99 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
val _ = proved "del_load_load32_77_80" ``! (w:80 word_loc) (s:(80,'c,'ffi)wordSem$state). (evaluate (Inst (Mem Load32 99 (Addr 3 255w)),unset_var 77 s) = (NONE,set_var 99 w (unset_var 77 s))) <=> evaluate (Inst (Mem Load32 99 (Addr 3 255w)),s) = (NONE,set_var 99 w s)`` (rpt gen_tac >> match_mp_tac replay_load >> EVAL_TAC);
