load "word_removeProofTheory";
load "wordPropsTheory";
load "sptreeTheory";
open HolKernel Parse bossLib word_removeProofTheory wordPropsTheory sptreeTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "evaluate_dec_clock_statement="; print_term(concl evaluate_dec_clock));
val _ = print("evaluate_dec_clock_hypotheses=" ^ Int.toString(length(hyp evaluate_dec_clock)) ^ "\n");
val _ = (print "evaluate_dec_clock_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl evaluate_dec_clock));
val _ = (print "compile_state_type="; print_type (type_of ``compile_state``); print "\n");
val _ = (print "compile_state_def_statement="; print_term(concl compile_state_def));
val _ = print("compile_state_def_hypotheses=" ^ Int.toString(length(hyp compile_state_def)) ^ "\n");
val _ = (print "compile_state_const_statement="; print_term(concl compile_state_const));
val _ = print("compile_state_const_hypotheses=" ^ Int.toString(length(hyp compile_state_const)) ^ "\n");
val _ = (print "find_code_map_I_statement="; print_term(concl find_code_map_I));
val _ = print("find_code_map_I_hypotheses=" ^ Int.toString(length(hyp find_code_map_I)) ^ "\n");
val _ = (print "compile_state_update_statement="; print_term(concl compile_state_update));
val _ = print("compile_state_update_hypotheses=" ^ Int.toString(length(hyp compile_state_update)) ^ "\n");
val _ = (print "get_var_compile_state_statement="; print_term(concl get_var_compile_state));
val _ = print("get_var_compile_state_hypotheses=" ^ Int.toString(length(hyp get_var_compile_state)) ^ "\n");
val _ = (print "get_fp_var_compile_state_statement="; print_term(concl get_fp_var_compile_state));
val _ = print("get_fp_var_compile_state_hypotheses=" ^ Int.toString(length(hyp get_fp_var_compile_state)) ^ "\n");
val _ = (print "get_vars_compile_state_statement="; print_term(concl get_vars_compile_state));
val _ = print("get_vars_compile_state_hypotheses=" ^ Int.toString(length(hyp get_vars_compile_state)) ^ "\n");
val _ = (print "set_var_compile_state_statement="; print_term(concl set_var_compile_state));
val _ = print("set_var_compile_state_hypotheses=" ^ Int.toString(length(hyp set_var_compile_state)) ^ "\n");
val _ = (print "unset_var_compile_state_statement="; print_term(concl unset_var_compile_state));
val _ = print("unset_var_compile_state_hypotheses=" ^ Int.toString(length(hyp unset_var_compile_state)) ^ "\n");
val _ = (print "set_fp_var_compile_state_statement="; print_term(concl set_fp_var_compile_state));
val _ = print("set_fp_var_compile_state_hypotheses=" ^ Int.toString(length(hyp set_fp_var_compile_state)) ^ "\n");
val _ = (print "set_vars_compile_state_statement="; print_term(concl set_vars_compile_state));
val _ = print("set_vars_compile_state_hypotheses=" ^ Int.toString(length(hyp set_vars_compile_state)) ^ "\n");
val _ = (print "get_store_compile_state_statement="; print_term(concl get_store_compile_state));
val _ = print("get_store_compile_state_hypotheses=" ^ Int.toString(length(hyp get_store_compile_state)) ^ "\n");
val _ = (print "set_store_compile_state_statement="; print_term(concl set_store_compile_state));
val _ = print("set_store_compile_state_hypotheses=" ^ Int.toString(length(hyp set_store_compile_state)) ^ "\n");
val _ = (print "push_env_compile_state_statement="; print_term(concl push_env_compile_state));
val _ = print("push_env_compile_state_hypotheses=" ^ Int.toString(length(hyp push_env_compile_state)) ^ "\n");
val _ = (print "pop_env_compile_state_statement="; print_term(concl pop_env_compile_state));
val _ = print("pop_env_compile_state_hypotheses=" ^ Int.toString(length(hyp pop_env_compile_state)) ^ "\n");
val _ = (print "call_env_compile_state_statement="; print_term(concl call_env_compile_state));
val _ = print("call_env_compile_state_hypotheses=" ^ Int.toString(length(hyp call_env_compile_state)) ^ "\n");
val _ = (print "flush_state_compile_state_statement="; print_term(concl flush_state_compile_state));
val _ = print("flush_state_compile_state_hypotheses=" ^ Int.toString(length(hyp flush_state_compile_state)) ^ "\n");
val _ = (print "has_space_compile_state_statement="; print_term(concl has_space_compile_state));
val _ = print("has_space_compile_state_hypotheses=" ^ Int.toString(length(hyp has_space_compile_state)) ^ "\n");
val _ = (print "gc_compile_state_statement="; print_term(concl gc_compile_state));
val _ = print("gc_compile_state_hypotheses=" ^ Int.toString(length(hyp gc_compile_state)) ^ "\n");
val _ = (print "alloc_compile_state_statement="; print_term(concl alloc_compile_state));
val _ = print("alloc_compile_state_hypotheses=" ^ Int.toString(length(hyp alloc_compile_state)) ^ "\n");
val _ = (print "mem_load_compile_state_statement="; print_term(concl mem_load_compile_state));
val _ = print("mem_load_compile_state_hypotheses=" ^ Int.toString(length(hyp mem_load_compile_state)) ^ "\n");
val _ = (print "mem_store_compile_state_statement="; print_term(concl mem_store_compile_state));
val _ = print("mem_store_compile_state_hypotheses=" ^ Int.toString(length(hyp mem_store_compile_state)) ^ "\n");
val _ = (print "word_exp_compile_state_statement="; print_term(concl word_exp_compile_state));
val _ = print("word_exp_compile_state_hypotheses=" ^ Int.toString(length(hyp word_exp_compile_state)) ^ "\n");
val _ = (print "assign_compile_state_statement="; print_term(concl assign_compile_state));
val _ = print("assign_compile_state_hypotheses=" ^ Int.toString(length(hyp assign_compile_state)) ^ "\n");
val _ = (print "inst_compile_state_statement="; print_term(concl inst_compile_state));
val _ = print("inst_compile_state_hypotheses=" ^ Int.toString(length(hyp inst_compile_state)) ^ "\n");
val _ = (print "cut_state_compile_state_statement="; print_term(concl cut_state_compile_state));
val _ = print("cut_state_compile_state_hypotheses=" ^ Int.toString(length(hyp cut_state_compile_state)) ^ "\n");
val _ = (print "compile_state_dec_clock_statement="; print_term(concl compile_state_dec_clock));
val _ = print("compile_state_dec_clock_hypotheses=" ^ Int.toString(length(hyp compile_state_dec_clock)) ^ "\n");
val _ = (print "jump_exc_compile_state_statement="; print_term(concl jump_exc_compile_state));
val _ = print("jump_exc_compile_state_hypotheses=" ^ Int.toString(length(hyp jump_exc_compile_state)) ^ "\n");
val _ = (print "get_var_imm_compile_state_statement="; print_term(concl get_var_imm_compile_state));
val _ = print("get_var_imm_compile_state_hypotheses=" ^ Int.toString(length(hyp get_var_imm_compile_state)) ^ "\n");
val _ = (print "push_env_case_handler_statement="; print_term(concl push_env_case_handler));
val _ = print("push_env_case_handler_hypotheses=" ^ Int.toString(length(hyp push_env_case_handler)) ^ "\n");
val _ = (print "word_remove_correct_statement="; print_term(concl word_remove_correct));
val _ = print("word_remove_correct_hypotheses=" ^ Int.toString(length(hyp word_remove_correct)) ^ "\n");
val _ = (print "word_remove_correct_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl word_remove_correct));
val _ = (print "sptree_domain_map_statement="; print_term(concl domain_map));
val _ = print("sptree_domain_map_hypotheses=" ^ Int.toString(length(hyp domain_map)) ^ "\n");
val _ = (print "sptree_map_insert_statement="; print_term(concl map_insert));
val _ = print("sptree_map_insert_hypotheses=" ^ Int.toString(length(hyp map_insert)) ^ "\n");
val _ = (print "sptree_map_fromAList_statement="; print_term(concl map_fromAList));
val _ = print("sptree_map_fromAList_hypotheses=" ^ Int.toString(length(hyp map_fromAList)) ^ "\n");
val _ = (print "sptree_map_union_statement="; print_term(concl map_union));
val _ = print("sptree_map_union_hypotheses=" ^ Int.toString(length(hyp map_union)) ^ "\n");
