load "bossLib";
load "preamble";
load "word_allocProofTheory";
open bossLib HolKernel Parse preamble wordLangTheory sptreeTheory;
val _ = Globals.linewidth := 1000;
val _ = print "mvm_original_statement=";
val _ = print_term (concl (DB.fetch "word_allocProof" "max_var_max"));
val _ = print "\n";
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "mvm_skip" ``let p = (Skip: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_move" ``let p = (Move 99 [(3,17);(23,5)]: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_move_empty" ``let p = (Move 99 []: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_inst64" ``let p = (Inst (FP (FPMovToReg 3 17 99)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_inst32" ``let p = (Inst (FP (FPMovToReg 3 17 99)): 32 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_assign" ``let p = (Assign 11 (Load (Var 17)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_get" ``let p = (Get 7 Handler: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_store" ``let p = (Store (Shift Lsl (Var 5) (Var 17)) 3: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_tail_ignored" ``let p = (Call NONE (SOME 99) [5;17] (SOME (101,Raise 103,7,8)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_tail_empty" ``let p = (Call NONE NONE [] (SOME (101,Raise 103,7,8)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_call_body" ``let p = (Call (SOME ([5],(insert 17 () LN,LN),Raise 23,7,8)) NONE [11] NONE: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_call_cutset" ``let p = (Call (SOME ([5],(LN,insert 47 () LN),Raise 23,7,8)) NONE [11] NONE: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_call_values" ``let p = (Call (SOME ([53],(LN,insert 47 () LN),Raise 23,7,8)) NONE [11] NONE: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_handler_value" ``let p = (Call (SOME ([5],(insert 17 () LN,LN),Raise 23,7,8)) NONE [11] (SOME (37,Raise 29,9,10)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_handler_body" ``let p = (Call (SOME ([5],(insert 17 () LN,LN),Raise 23,7,8)) NONE [11] (SOME (37,Raise 61,9,10)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_seq" ``let p = (Seq (Raise 5) (Raise 17): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_must" ``let p = (MustTerminate (Raise 17): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_if_reg" ``let p = (If Equal 5 (Reg 23) (Raise 17) (Raise 11): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_if_imm" ``let p = (If Equal 5 (Imm 99w) (Raise 17) (Raise 11): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_alloc" ``let p = (Alloc 7 (insert 17 () LN,insert 23 () LN): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_consts" ``let p = (StoreConsts 3 17 23 5 [(T,99w)]: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_install" ``let p = (Install 3 5 7 11 (LN,insert 23 () LN): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_codewrite" ``let p = (CodeBufferWrite 3 17: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_datawrite" ``let p = (DataBufferWrite 23 5: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_ffi" ``let p = (FFI (implode "x") 3 5 7 11 (insert 17 () LN,insert 23 () LN): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_raise" ``let p = (Raise 17: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_heap" ``let p = (OpCurrHeap Add 3 17: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_return" ``let p = (Return 3 [5;17]: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_return_empty" ``let p = (Return 0 []: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_tick" ``let p = (Tick: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_loc" ``let p = (LocValue 7 99: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_set" ``let p = (Set CurrHeap (Load (Var 17)): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_share" ``let p = (ShareInst Load8 3 (Op Add [Var 5;Const 99w]): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_loop_exit" ``let p = (Loop (insert 17 () LN) (Raise 23) (insert 29 () LN): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_loop_body" ``let p = (Loop (insert 17 () LN) (Raise 31) (insert 29 () LN): 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_break" ``let p = (Break 99: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_continue" ``let p = (Continue 99: 64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_width1_huge" ``let p = (Assign 1208925819614629174706176 (Var 7):1 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_inst_load16_ignored" ``let p = (Inst (Mem Load16 999 (Addr 777 3w)):64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_inst_store16_ignored" ``let p = (Inst (Mem Store16 999 (Addr 777 3w)):64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_inst_fp80_from" ``let p = (Inst (FP (FPMovFromReg 999 2 101)):80 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_call_arguments" ``let p = (Call (SOME ([5],(LN,LN),Raise 3,999,999)) NONE [97] NONE:64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_call_nested_handler" ``let p = (Call (SOME ([5],(LN,LN),Raise 3,999,999)) NONE [7] (SOME (11,Loop LN (Return 13 [17]) LN,999,999)):32 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_cutsets_nonwf" ``let p = (Alloc 0 (BN LN LN,BS LN () LN):64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_op_list_nested" ``let p = (Set CurrHeap (Op Add [Var 3;Load (Var 101);Op Sub [Var 17;Const 3w]]):80 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
val _ = out "mvm_inst_fp_ignored" ``let p = (Inst (FP (FPAdd 100 200 300)):64 wordLang$prog) in (max_var p,every_var (\x. x <= max_var p) p,every_var (\x. x < max_var p) p)``;
