load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory sptreeTheory listTheory miscTheory;
val _ = Globals.linewidth := 1000000;
val _ = numLib.temp_prefer_num();
val wf_alist_insert=prove(``∀xs ys z. wf z ⇒ wf (alist_insert xs ys z)``,  ho_match_mp_tac alist_insert_ind \\ rw[alist_insert_def] \\ fs[wf_insert]);
val _ = (if null(hyp wf_alist_insert) then () else raise Fail "open premise"; print "iw_full_wf_alist_insert="; print_thm wf_alist_insert; print "\n");
val wf_fromList2=prove(``∀ls. wf(fromList2 ls)``,  ho_match_mp_tac SNOC_INDUCT>>
  fs[fromList2_def,FOLDL_SNOC,wf_def]>>rw[]>>
  pairarg_tac>>fs[wf_insert]);
val _ = (if null(hyp wf_fromList2) then () else raise Fail "open premise"; print "iw_full_wf_fromList2="; print_thm wf_fromList2; print "\n");
fun emit label q = let val th=EVAL q in print(label ^ "="); print_thm th; print "\n" end;
val _ = emit "iw_insert_num_0_0_0" ``(alist_insert [] ([]:num list) LN, wf (LN:num spt), wf (alist_insert [] ([]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_0_1" ``(alist_insert [] ([3]:num list) LN, wf (LN:num spt), wf (alist_insert [] ([3]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_0_2" ``(alist_insert [] ([3;9]:num list) LN, wf (LN:num spt), wf (alist_insert [] ([3;9]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_0_3" ``(alist_insert [] ([3;9;13;9;3]:num list) LN, wf (LN:num spt), wf (alist_insert [] ([3;9;13;9;3]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_1_0" ``(alist_insert [0] ([]:num list) LN, wf (LN:num spt), wf (alist_insert [0] ([]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_1_1" ``(alist_insert [0] ([3]:num list) LN, wf (LN:num spt), wf (alist_insert [0] ([3]:num list) LN)) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_0_1_2" ``(alist_insert [0] ([3;9]:num list) LN, wf (LN:num spt), wf (alist_insert [0] ([3;9]:num list) LN)) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_0_1_3" ``(alist_insert [0] ([3;9;13;9;3]:num list) LN, wf (LN:num spt), wf (alist_insert [0] ([3;9;13;9;3]:num list) LN)) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_0_2_0" ``(alist_insert [2;0;2] ([]:num list) LN, wf (LN:num spt), wf (alist_insert [2;0;2] ([]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_2_1" ``(alist_insert [2;0;2] ([3]:num list) LN, wf (LN:num spt), wf (alist_insert [2;0;2] ([3]:num list) LN)) = ((BN (LS 3) LN), T, T)``;
val _ = emit "iw_insert_num_0_2_2" ``(alist_insert [2;0;2] ([3;9]:num list) LN, wf (LN:num spt), wf (alist_insert [2;0;2] ([3;9]:num list) LN)) = ((BS (LS 3) 9 LN), T, T)``;
val _ = emit "iw_insert_num_0_2_3" ``(alist_insert [2;0;2] ([3;9;13;9;3]:num list) LN, wf (LN:num spt), wf (alist_insert [2;0;2] ([3;9;13;9;3]:num list) LN)) = ((BS (LS 3) 9 LN), T, T)``;
val _ = emit "iw_insert_num_0_3_0" ``(alist_insert [7;1;0;8;3] ([]:num list) LN, wf (LN:num spt), wf (alist_insert [7;1;0;8;3] ([]:num list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_num_0_3_1" ``(alist_insert [7;1;0;8;3] ([3]:num list) LN, wf (LN:num spt), wf (alist_insert [7;1;0;8;3] ([3]:num list) LN)) = ((BN LN (BN LN (BN LN (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_0_3_2" ``(alist_insert [7;1;0;8;3] ([3;9]:num list) LN, wf (LN:num spt), wf (alist_insert [7;1;0;8;3] ([3;9]:num list) LN)) = ((BN LN (BS LN 9 (BN LN (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_0_3_3" ``(alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) LN, wf (LN:num spt), wf (alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) LN)) = ((BS (BN LN (BN LN (LS 9))) 13 (BS LN 9 (BS LN 3 (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_1_0_0" ``(alist_insert [] ([]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [] ([]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_0_1" ``(alist_insert [] ([3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [] ([3]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_0_2" ``(alist_insert [] ([3;9]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [] ([3;9]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_0_3" ``(alist_insert [] ([3;9;13;9;3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [] ([3;9;13;9;3]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_1_0" ``(alist_insert [0] ([]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [0] ([]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_1_1" ``(alist_insert [0] ([3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [0] ([3]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_1_2" ``(alist_insert [0] ([3;9]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [0] ([3;9]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_1_3" ``(alist_insert [0] ([3;9;13;9;3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [0] ([3;9;13;9;3]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_2_0" ``(alist_insert [2;0;2] ([]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [2;0;2] ([]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_2_1" ``(alist_insert [2;0;2] ([3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [2;0;2] ([3]:num list) (LS 3))) = ((BS (LS 3) 3 LN), T, T)``;
val _ = emit "iw_insert_num_1_2_2" ``(alist_insert [2;0;2] ([3;9]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [2;0;2] ([3;9]:num list) (LS 3))) = ((BS (LS 3) 9 LN), T, T)``;
val _ = emit "iw_insert_num_1_2_3" ``(alist_insert [2;0;2] ([3;9;13;9;3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [2;0;2] ([3;9;13;9;3]:num list) (LS 3))) = ((BS (LS 3) 9 LN), T, T)``;
val _ = emit "iw_insert_num_1_3_0" ``(alist_insert [7;1;0;8;3] ([]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [7;1;0;8;3] ([]:num list) (LS 3))) = ((LS 3), T, T)``;
val _ = emit "iw_insert_num_1_3_1" ``(alist_insert [7;1;0;8;3] ([3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [7;1;0;8;3] ([3]:num list) (LS 3))) = ((BS LN 3 (BN LN (BN LN (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_1_3_2" ``(alist_insert [7;1;0;8;3] ([3;9]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [7;1;0;8;3] ([3;9]:num list) (LS 3))) = ((BS LN 3 (BS LN 9 (BN LN (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_1_3_3" ``(alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (LS 3), wf ((LS 3):num spt), wf (alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (LS 3))) = ((BS (BN LN (BN LN (LS 9))) 13 (BS LN 9 (BS LN 3 (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_2_0_0" ``(alist_insert [] ([]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [] ([]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_0_1" ``(alist_insert [] ([3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [] ([3]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_0_2" ``(alist_insert [] ([3;9]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [] ([3;9]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_0_3" ``(alist_insert [] ([3;9;13;9;3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [] ([3;9;13;9;3]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_1_0" ``(alist_insert [0] ([]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [0] ([]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_1_1" ``(alist_insert [0] ([3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [0] ([3]:num list) (BN LN LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_2_1_2" ``(alist_insert [0] ([3;9]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [0] ([3;9]:num list) (BN LN LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_2_1_3" ``(alist_insert [0] ([3;9;13;9;3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [0] ([3;9;13;9;3]:num list) (BN LN LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_2_2_0" ``(alist_insert [2;0;2] ([]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [2;0;2] ([]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_2_1" ``(alist_insert [2;0;2] ([3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [2;0;2] ([3]:num list) (BN LN LN))) = ((BN (LS 3) LN), F, T)``;
val _ = emit "iw_insert_num_2_2_2" ``(alist_insert [2;0;2] ([3;9]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [2;0;2] ([3;9]:num list) (BN LN LN))) = ((BS (LS 3) 9 LN), F, T)``;
val _ = emit "iw_insert_num_2_2_3" ``(alist_insert [2;0;2] ([3;9;13;9;3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [2;0;2] ([3;9;13;9;3]:num list) (BN LN LN))) = ((BS (LS 3) 9 LN), F, T)``;
val _ = emit "iw_insert_num_2_3_0" ``(alist_insert [7;1;0;8;3] ([]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [7;1;0;8;3] ([]:num list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_num_2_3_1" ``(alist_insert [7;1;0;8;3] ([3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [7;1;0;8;3] ([3]:num list) (BN LN LN))) = ((BN LN (BN LN (BN LN (LS 3)))), F, T)``;
val _ = emit "iw_insert_num_2_3_2" ``(alist_insert [7;1;0;8;3] ([3;9]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [7;1;0;8;3] ([3;9]:num list) (BN LN LN))) = ((BN LN (BS LN 9 (BN LN (LS 3)))), F, T)``;
val _ = emit "iw_insert_num_2_3_3" ``(alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (BN LN LN), wf ((BN LN LN):num spt), wf (alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (BN LN LN))) = ((BS (BN LN (BN LN (LS 9))) 13 (BS LN 9 (BS LN 3 (LS 3)))), F, T)``;
val _ = emit "iw_insert_num_3_0_0" ``(alist_insert [] ([]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [] ([]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_0_1" ``(alist_insert [] ([3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [] ([3]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_0_2" ``(alist_insert [] ([3;9]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [] ([3;9]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_0_3" ``(alist_insert [] ([3;9;13;9;3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [] ([3;9;13;9;3]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_1_0" ``(alist_insert [0] ([]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [0] ([]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_1_1" ``(alist_insert [0] ([3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [0] ([3]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_1_2" ``(alist_insert [0] ([3;9]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [0] ([3;9]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_1_3" ``(alist_insert [0] ([3;9;13;9;3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [0] ([3;9;13;9;3]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_2_0" ``(alist_insert [2;0;2] ([]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [2;0;2] ([]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_2_1" ``(alist_insert [2;0;2] ([3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [2;0;2] ([3]:num list) (BS LN 3 LN))) = ((BS (LS 3) 3 LN), F, T)``;
val _ = emit "iw_insert_num_3_2_2" ``(alist_insert [2;0;2] ([3;9]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [2;0;2] ([3;9]:num list) (BS LN 3 LN))) = ((BS (LS 3) 9 LN), F, T)``;
val _ = emit "iw_insert_num_3_2_3" ``(alist_insert [2;0;2] ([3;9;13;9;3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [2;0;2] ([3;9;13;9;3]:num list) (BS LN 3 LN))) = ((BS (LS 3) 9 LN), F, T)``;
val _ = emit "iw_insert_num_3_3_0" ``(alist_insert [7;1;0;8;3] ([]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [7;1;0;8;3] ([]:num list) (BS LN 3 LN))) = ((BS LN 3 LN), F, F)``;
val _ = emit "iw_insert_num_3_3_1" ``(alist_insert [7;1;0;8;3] ([3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [7;1;0;8;3] ([3]:num list) (BS LN 3 LN))) = ((BS LN 3 (BN LN (BN LN (LS 3)))), F, T)``;
val _ = emit "iw_insert_num_3_3_2" ``(alist_insert [7;1;0;8;3] ([3;9]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [7;1;0;8;3] ([3;9]:num list) (BS LN 3 LN))) = ((BS LN 3 (BS LN 9 (BN LN (LS 3)))), F, T)``;
val _ = emit "iw_insert_num_3_3_3" ``(alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (BS LN 3 LN), wf ((BS LN 3 LN):num spt), wf (alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (BS LN 3 LN))) = ((BS (BN LN (BN LN (LS 9))) 13 (BS LN 9 (BS LN 3 (LS 3)))), F, T)``;
val _ = emit "iw_insert_num_4_0_0" ``(alist_insert [] ([]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [] ([]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_0_1" ``(alist_insert [] ([3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [] ([3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_0_2" ``(alist_insert [] ([3;9]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [] ([3;9]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_0_3" ``(alist_insert [] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_1_0" ``(alist_insert [0] ([]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [0] ([]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_1_1" ``(alist_insert [0] ([3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [0] ([3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_1_2" ``(alist_insert [0] ([3;9]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [0] ([3;9]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_1_3" ``(alist_insert [0] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [0] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_2_0" ``(alist_insert [2;0;2] ([]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [2;0;2] ([]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_2_1" ``(alist_insert [2;0;2] ([3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [2;0;2] ([3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 3) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_2_2" ``(alist_insert [2;0;2] ([3;9]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [2;0;2] ([3;9]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 3) 9 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_2_3" ``(alist_insert [2;0;2] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [2;0;2] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 3) 9 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_3_0" ``(alist_insert [7;1;0;8;3] ([]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [7;1;0;8;3] ([]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (LS 13)), T, T)``;
val _ = emit "iw_insert_num_4_3_1" ``(alist_insert [7;1;0;8;3] ([3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [7;1;0;8;3] ([3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (BS LN 13 (BN LN (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_4_3_2" ``(alist_insert [7;1;0;8;3] ([3;9]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [7;1;0;8;3] ([3;9]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (LS 9) 3 (BS LN 9 (BN LN (LS 3)))), T, T)``;
val _ = emit "iw_insert_num_4_3_3" ``(alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)), wf ((BS (LS 9) 3 (LS 13)):num spt), wf (alist_insert [7;1;0;8;3] ([3;9;13;9;3]:num list) (BS (LS 9) 3 (LS 13)))) = ((BS (BS LN 9 (BN LN (LS 9))) 13 (BS LN 9 (BS LN 3 (LS 3)))), T, T)``;
val _ = emit "iw_fromlist_num_0" ``(fromList2 ([]:num list), wf (fromList2 ([]:num list))) = (LN, T)``;
val _ = emit "iw_fromlist_num_1" ``(fromList2 ([3]:num list), wf (fromList2 ([3]:num list))) = ((LS 3), T)``;
val _ = emit "iw_fromlist_num_2" ``(fromList2 ([3;9]:num list), wf (fromList2 ([3;9]:num list))) = ((BS (LS 9) 3 LN), T)``;
val _ = emit "iw_fromlist_num_3" ``(fromList2 ([3;9;13;9;3]:num list), wf (fromList2 ([3;9;13;9;3]:num list))) = ((BS (BS (LS 9) 9 (BS LN 13 (LS 3))) 3 LN), T)``;
val _ = emit "iw_insert_bool_0_0_0" ``(alist_insert [] ([]:bool list) LN, wf (LN:bool spt), wf (alist_insert [] ([]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_0_1" ``(alist_insert [] ([T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [] ([T]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_0_2" ``(alist_insert [] ([T;F]:bool list) LN, wf (LN:bool spt), wf (alist_insert [] ([T;F]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_0_3" ``(alist_insert [] ([T;F;T;F;T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [] ([T;F;T;F;T]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_1_0" ``(alist_insert [0] ([]:bool list) LN, wf (LN:bool spt), wf (alist_insert [0] ([]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_1_1" ``(alist_insert [0] ([T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [0] ([T]:bool list) LN)) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_0_1_2" ``(alist_insert [0] ([T;F]:bool list) LN, wf (LN:bool spt), wf (alist_insert [0] ([T;F]:bool list) LN)) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_0_1_3" ``(alist_insert [0] ([T;F;T;F;T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [0] ([T;F;T;F;T]:bool list) LN)) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_0_2_0" ``(alist_insert [2;0;2] ([]:bool list) LN, wf (LN:bool spt), wf (alist_insert [2;0;2] ([]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_2_1" ``(alist_insert [2;0;2] ([T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [2;0;2] ([T]:bool list) LN)) = ((BN (LS T) LN), T, T)``;
val _ = emit "iw_insert_bool_0_2_2" ``(alist_insert [2;0;2] ([T;F]:bool list) LN, wf (LN:bool spt), wf (alist_insert [2;0;2] ([T;F]:bool list) LN)) = ((BS (LS T) F LN), T, T)``;
val _ = emit "iw_insert_bool_0_2_3" ``(alist_insert [2;0;2] ([T;F;T;F;T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [2;0;2] ([T;F;T;F;T]:bool list) LN)) = ((BS (LS T) F LN), T, T)``;
val _ = emit "iw_insert_bool_0_3_0" ``(alist_insert [7;1;0;8;3] ([]:bool list) LN, wf (LN:bool spt), wf (alist_insert [7;1;0;8;3] ([]:bool list) LN)) = (LN, T, T)``;
val _ = emit "iw_insert_bool_0_3_1" ``(alist_insert [7;1;0;8;3] ([T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [7;1;0;8;3] ([T]:bool list) LN)) = ((BN LN (BN LN (BN LN (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_0_3_2" ``(alist_insert [7;1;0;8;3] ([T;F]:bool list) LN, wf (LN:bool spt), wf (alist_insert [7;1;0;8;3] ([T;F]:bool list) LN)) = ((BN LN (BS LN F (BN LN (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_0_3_3" ``(alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) LN, wf (LN:bool spt), wf (alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) LN)) = ((BS (BN LN (BN LN (LS F))) T (BS LN F (BS LN T (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_1_0_0" ``(alist_insert [] ([]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [] ([]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_0_1" ``(alist_insert [] ([T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [] ([T]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_0_2" ``(alist_insert [] ([T;F]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [] ([T;F]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_0_3" ``(alist_insert [] ([T;F;T;F;T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [] ([T;F;T;F;T]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_1_0" ``(alist_insert [0] ([]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [0] ([]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_1_1" ``(alist_insert [0] ([T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [0] ([T]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_1_2" ``(alist_insert [0] ([T;F]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [0] ([T;F]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_1_3" ``(alist_insert [0] ([T;F;T;F;T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [0] ([T;F;T;F;T]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_2_0" ``(alist_insert [2;0;2] ([]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [2;0;2] ([]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_2_1" ``(alist_insert [2;0;2] ([T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [2;0;2] ([T]:bool list) (LS T))) = ((BS (LS T) T LN), T, T)``;
val _ = emit "iw_insert_bool_1_2_2" ``(alist_insert [2;0;2] ([T;F]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [2;0;2] ([T;F]:bool list) (LS T))) = ((BS (LS T) F LN), T, T)``;
val _ = emit "iw_insert_bool_1_2_3" ``(alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (LS T))) = ((BS (LS T) F LN), T, T)``;
val _ = emit "iw_insert_bool_1_3_0" ``(alist_insert [7;1;0;8;3] ([]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [7;1;0;8;3] ([]:bool list) (LS T))) = ((LS T), T, T)``;
val _ = emit "iw_insert_bool_1_3_1" ``(alist_insert [7;1;0;8;3] ([T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [7;1;0;8;3] ([T]:bool list) (LS T))) = ((BS LN T (BN LN (BN LN (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_1_3_2" ``(alist_insert [7;1;0;8;3] ([T;F]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F]:bool list) (LS T))) = ((BS LN T (BS LN F (BN LN (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_1_3_3" ``(alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (LS T), wf ((LS T):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (LS T))) = ((BS (BN LN (BN LN (LS F))) T (BS LN F (BS LN T (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_2_0_0" ``(alist_insert [] ([]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [] ([]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_0_1" ``(alist_insert [] ([T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [] ([T]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_0_2" ``(alist_insert [] ([T;F]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [] ([T;F]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_0_3" ``(alist_insert [] ([T;F;T;F;T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [] ([T;F;T;F;T]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_1_0" ``(alist_insert [0] ([]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [0] ([]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_1_1" ``(alist_insert [0] ([T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [0] ([T]:bool list) (BN LN LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_2_1_2" ``(alist_insert [0] ([T;F]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [0] ([T;F]:bool list) (BN LN LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_2_1_3" ``(alist_insert [0] ([T;F;T;F;T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [0] ([T;F;T;F;T]:bool list) (BN LN LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_2_2_0" ``(alist_insert [2;0;2] ([]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [2;0;2] ([]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_2_1" ``(alist_insert [2;0;2] ([T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [2;0;2] ([T]:bool list) (BN LN LN))) = ((BN (LS T) LN), F, T)``;
val _ = emit "iw_insert_bool_2_2_2" ``(alist_insert [2;0;2] ([T;F]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [2;0;2] ([T;F]:bool list) (BN LN LN))) = ((BS (LS T) F LN), F, T)``;
val _ = emit "iw_insert_bool_2_2_3" ``(alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (BN LN LN))) = ((BS (LS T) F LN), F, T)``;
val _ = emit "iw_insert_bool_2_3_0" ``(alist_insert [7;1;0;8;3] ([]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [7;1;0;8;3] ([]:bool list) (BN LN LN))) = ((BN LN LN), F, F)``;
val _ = emit "iw_insert_bool_2_3_1" ``(alist_insert [7;1;0;8;3] ([T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [7;1;0;8;3] ([T]:bool list) (BN LN LN))) = ((BN LN (BN LN (BN LN (LS T)))), F, T)``;
val _ = emit "iw_insert_bool_2_3_2" ``(alist_insert [7;1;0;8;3] ([T;F]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F]:bool list) (BN LN LN))) = ((BN LN (BS LN F (BN LN (LS T)))), F, T)``;
val _ = emit "iw_insert_bool_2_3_3" ``(alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (BN LN LN), wf ((BN LN LN):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (BN LN LN))) = ((BS (BN LN (BN LN (LS F))) T (BS LN F (BS LN T (LS T)))), F, T)``;
val _ = emit "iw_insert_bool_3_0_0" ``(alist_insert [] ([]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [] ([]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_0_1" ``(alist_insert [] ([T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [] ([T]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_0_2" ``(alist_insert [] ([T;F]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [] ([T;F]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_0_3" ``(alist_insert [] ([T;F;T;F;T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [] ([T;F;T;F;T]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_1_0" ``(alist_insert [0] ([]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [0] ([]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_1_1" ``(alist_insert [0] ([T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [0] ([T]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_1_2" ``(alist_insert [0] ([T;F]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [0] ([T;F]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_1_3" ``(alist_insert [0] ([T;F;T;F;T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [0] ([T;F;T;F;T]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_2_0" ``(alist_insert [2;0;2] ([]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [2;0;2] ([]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_2_1" ``(alist_insert [2;0;2] ([T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [2;0;2] ([T]:bool list) (BS LN T LN))) = ((BS (LS T) T LN), F, T)``;
val _ = emit "iw_insert_bool_3_2_2" ``(alist_insert [2;0;2] ([T;F]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [2;0;2] ([T;F]:bool list) (BS LN T LN))) = ((BS (LS T) F LN), F, T)``;
val _ = emit "iw_insert_bool_3_2_3" ``(alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (BS LN T LN))) = ((BS (LS T) F LN), F, T)``;
val _ = emit "iw_insert_bool_3_3_0" ``(alist_insert [7;1;0;8;3] ([]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [7;1;0;8;3] ([]:bool list) (BS LN T LN))) = ((BS LN T LN), F, F)``;
val _ = emit "iw_insert_bool_3_3_1" ``(alist_insert [7;1;0;8;3] ([T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [7;1;0;8;3] ([T]:bool list) (BS LN T LN))) = ((BS LN T (BN LN (BN LN (LS T)))), F, T)``;
val _ = emit "iw_insert_bool_3_3_2" ``(alist_insert [7;1;0;8;3] ([T;F]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F]:bool list) (BS LN T LN))) = ((BS LN T (BS LN F (BN LN (LS T)))), F, T)``;
val _ = emit "iw_insert_bool_3_3_3" ``(alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (BS LN T LN), wf ((BS LN T LN):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (BS LN T LN))) = ((BS (BN LN (BN LN (LS F))) T (BS LN F (BS LN T (LS T)))), F, T)``;
val _ = emit "iw_insert_bool_4_0_0" ``(alist_insert [] ([]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [] ([]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_0_1" ``(alist_insert [] ([T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [] ([T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_0_2" ``(alist_insert [] ([T;F]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [] ([T;F]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_0_3" ``(alist_insert [] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_1_0" ``(alist_insert [0] ([]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [0] ([]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_1_1" ``(alist_insert [0] ([T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [0] ([T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_1_2" ``(alist_insert [0] ([T;F]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [0] ([T;F]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_1_3" ``(alist_insert [0] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [0] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_2_0" ``(alist_insert [2;0;2] ([]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [2;0;2] ([]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_2_1" ``(alist_insert [2;0;2] ([T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [2;0;2] ([T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS T) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_2_2" ``(alist_insert [2;0;2] ([T;F]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [2;0;2] ([T;F]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS T) F (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_2_3" ``(alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [2;0;2] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS T) F (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_3_0" ``(alist_insert [7;1;0;8;3] ([]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [7;1;0;8;3] ([]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (LS T)), T, T)``;
val _ = emit "iw_insert_bool_4_3_1" ``(alist_insert [7;1;0;8;3] ([T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [7;1;0;8;3] ([T]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (BS LN T (BN LN (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_4_3_2" ``(alist_insert [7;1;0;8;3] ([T;F]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F]:bool list) (BS (LS F) T (LS T)))) = ((BS (LS F) T (BS LN F (BN LN (LS T)))), T, T)``;
val _ = emit "iw_insert_bool_4_3_3" ``(alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)), wf ((BS (LS F) T (LS T)):bool spt), wf (alist_insert [7;1;0;8;3] ([T;F;T;F;T]:bool list) (BS (LS F) T (LS T)))) = ((BS (BS LN F (BN LN (LS F))) T (BS LN F (BS LN T (LS T)))), T, T)``;
val _ = emit "iw_fromlist_bool_0" ``(fromList2 ([]:bool list), wf (fromList2 ([]:bool list))) = (LN, T)``;
val _ = emit "iw_fromlist_bool_1" ``(fromList2 ([T]:bool list), wf (fromList2 ([T]:bool list))) = ((LS T), T)``;
val _ = emit "iw_fromlist_bool_2" ``(fromList2 ([T;F]:bool list), wf (fromList2 ([T;F]:bool list))) = ((BS (LS F) T LN), T)``;
val _ = emit "iw_fromlist_bool_3" ``(fromList2 ([T;F;T;F;T]:bool list), wf (fromList2 ([T;F;T;F;T]:bool list))) = ((BS (BS (LS F) F (BS LN T (LS T))) T LN), T)``;
