load "preamble"; load "word_simpTheory"; load "word_simpProofTheory";
open HolKernel Parse bossLib preamble word_simpTheory word_simpProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = Globals.show_types := true;
fun row label theorem = (print(label ^ "="); print_term(concl theorem));
val _ = row "generic_carrier_1" ALOOKUP_LIST_REL_sf_gc_consts;
val _ = print("generic_carrier_1_hypotheses=" ^ Int.toString(length(hyp ALOOKUP_LIST_REL_sf_gc_consts)) ^ "\n");
val _ = row "generic_carrier_2" ALOOKUP_LIST_REL_sf_gc_consts_NONE;
val _ = print("generic_carrier_2_hypotheses=" ^ Int.toString(length(hyp ALOOKUP_LIST_REL_sf_gc_consts_NONE)) ^ "\n");
val _ = row "generic_carrier_3" ALOOKUP_LIST_REL_value_rel;
val _ = print("generic_carrier_3_hypotheses=" ^ Int.toString(length(hyp ALOOKUP_LIST_REL_value_rel)) ^ "\n");
val _ = row "generic_carrier_4" ALOOKUP_ALL_DISTINCT_FST_PERM;
val _ = print("generic_carrier_4_hypotheses=" ^ Int.toString(length(hyp ALOOKUP_ALL_DISTINCT_FST_PERM)) ^ "\n");
val _ = row "generic_carrier_5" ALOOKUP_ALL_DISTINCT_FST_PERM_SOME;
val _ = print("generic_carrier_5_hypotheses=" ^ Int.toString(length(hyp ALOOKUP_ALL_DISTINCT_FST_PERM_SOME)) ^ "\n");
val _ = row "generic_carrier_6" set_vars_move_NONE;
val _ = print("generic_carrier_6_hypotheses=" ^ Int.toString(length(hyp set_vars_move_NONE)) ^ "\n");
val _ = row "generic_carrier_7" all_names_def;
val _ = print("generic_carrier_7_hypotheses=" ^ Int.toString(length(hyp all_names_def)) ^ "\n");
