load "preamble";
load "word_to_stackTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "wts_prog_zero_registers" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 0 0 (List [4w],1) = (stackLang$Seq (StackAlloc 2) Skip,2,(List [4w],1))``;
val _ = out "wts_prog_register_only" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 0 4 (List [4w],1) = (stackLang$Seq (StackAlloc 0) Skip,0,(List [4w],1))``;
val _ = out "wts_prog_exact_register_args" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 4 4 (List [4w],1) = (stackLang$Seq (StackAlloc 0) Skip,0,(List [4w],1))``;
val _ = out "wts_prog_first_stack_arg" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 5 4 (List [4w],1) = (stackLang$Seq (StackAlloc 1) Skip,2,(List [4w],1))``;
val _ = out "wts_prog_three_stack_args" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 7 4 (List [4w],1) = (stackLang$Seq (StackAlloc 1) Skip,4,(List [4w],1))``;
val _ = out "wts_prog_all_stack_args" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 3 0 (List [4w],1) = (stackLang$Seq (StackAlloc 1) Skip,4,(List [4w],1))``;
val _ = out "wts_prog_huge_register_count" ``compile_prog (c:64 asm$asm_config) F (wordLang$Skip) 0 99 (List [4w],1) = (stackLang$Seq (StackAlloc 0) Skip,0,(List [4w],1))``;
val _ = out "wts_prog_var_boundary" ``compile_prog (c:64 asm$asm_config) F (wordLang$Assign 6 (Const 9w)) 0 4 (List [4w],1) = (stackLang$Seq (StackAlloc 0) Skip,0,(List [4w],1))``;
val _ = out "wts_prog_var_first_stack" ``compile_prog (c:64 asm$asm_config) F (wordLang$Assign 8 (Const 9w)) 0 4 (List [4w],1) = (stackLang$Seq (StackAlloc 2) Skip,2,(List [4w],1))``;
val _ = out "wts_prog_var_odd_stack" ``compile_prog (c:64 asm$asm_config) F (wordLang$Assign 9 (Const 9w)) 0 4 (List [4w],1) = (stackLang$Seq (StackAlloc 2) Skip,2,(List [4w],1))``;
val _ = out "wts_prog_vars_exceed_args" ``compile_prog (c:64 asm$asm_config) F (wordLang$Assign 16 (Const 9w)) 5 4 (List [4w],1) = (stackLang$Seq (StackAlloc 5) Skip,6,(List [4w],1))``;
val _ = out "wts_prog_args_exceed_vars" ``compile_prog (c:8 asm$asm_config) F (wordLang$Assign 8 (Const 9w)) 12 4 (List [4w],1) = (stackLang$Seq (StackAlloc 1) Skip,9,(List [4w],1))``;
val _ = out "wts_prog_perf_tick" ``compile_prog (c:64 asm$asm_config) T (wordLang$Tick) 7 4 (List [4w],1) = (stackLang$Seq (StackAlloc 1) Tick,4,(List [4w],1))``;
val _ = out "wts_prog_width_one" ``compile_prog (c:1 asm$asm_config) F (wordLang$Skip) 7 4 (List [4w],1) = (stackLang$Seq (StackAlloc 1) Skip,4,(List [4w],1))``;
val _ = out "wts_prog_list_empty" ``compile_word_to_stack (c:64 asm$asm_config) F 4 ([]:(bool#num#64 wordLang$prog) list) (List [4w],1) = ([],[],(List [4w],1))``;
val _ = out "wts_prog_list_generic" ``compile_word_to_stack (c:64 asm$asm_config) F 4 [(i:'b,7,wordLang$Skip);(j,0,Tick)] (List [4w],1) = ([(i,stackLang$Seq (StackAlloc 1) Skip);(j,Seq (StackAlloc 0) Tick)],[4;0],(List [4w],1))``;
val _ = out "wts_prog_list_duplicates" ``compile_word_to_stack (c:64 asm$asm_config) T 4 [(T,7,wordLang$Skip);(T,0,Tick)] (List [4w],1) = ([(T,stackLang$Seq (StackAlloc 1) Skip);(T,Seq (StackAlloc 0) Tick)],[4;0],(List [4w],1))``;
val _ = out "wts_prog_bitmap_order" ``let (ps,fs,bs)=compile_word_to_stack (c:64 asm$asm_config) F 4 [(0,5,wordLang$Alloc 0 (LN,LN));(1,7,wordLang$Alloc 0 (LN,LN))] (List [4w],1) in MAP FST ps=[0;1] /\ fs=[2;4] /\ append(FST bs)=[4w;2w;8w] /\ SND bs=3``;
val _ = out "wts_prog_bitmap_reverse" ``let (ps,fs,bs)=compile_word_to_stack (c:64 asm$asm_config) F 4 [(0,7,wordLang$Alloc 0 (LN,LN));(1,5,wordLang$Alloc 0 (LN,LN))] (List [4w],1) in MAP FST ps=[0;1] /\ fs=[4;2] /\ append(FST bs)=[4w;8w;2w] /\ SND bs=3``;
val _ = out "wts_prog_bitmap_multiword" ``let (ps,fs,bs)=compile_word_to_stack (c:8 asm$asm_config) F 4 [(0,12,wordLang$Alloc 0 (LN,LN));(1,5,wordLang$Alloc 0 (LN,LN))] (List [4w],1) in MAP FST ps=[0;1] /\ fs=[9;2] /\ append(FST bs)=[4w;128w;2w;2w] /\ SND bs=4``;
val _ = out "wts_prog_bitmap_zero_frame" ``let (ps,fs,bs)=compile_word_to_stack (c:64 asm$asm_config) F 4 [(0,0,wordLang$Alloc 0 (LN,LN));(1,5,wordLang$Alloc 0 (LN,LN))] (List [4w],1) in MAP FST ps=[0;1] /\ fs=[0;2] /\ append(FST bs)=[4w;2w] /\ SND bs=2``;
val _ = OS.Process.exit OS.Process.success;
