load "preamble";
load "word_to_stackTheory";
load "stackPropsTheory";
open bossLib HolKernel Parse preamble word_to_stackTheory stackPropsTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val _ = out "nsh_move_empty" ``no_shmemop (wMoveAux [] (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_move_rr" ``no_shmemop (wMoveAux [(INL 0,INL 1)] (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_move_rs" ``no_shmemop (wMoveAux [(INL 0,INR 99)] (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_move_sr" ``no_shmemop (wMoveAux [(INR 99,INL 1)] (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_move_ss" ``no_shmemop (wMoveAux [(INR 99,INR 88)] (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_move_multi" ``no_shmemop (wMoveAux [(INL 0,INR 9);(INR 8,INL 1);(INR 7,INR 6)] (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_move_width1" ``no_shmemop (wMoveAux [(INR 999,INR 888)] (0,0,999) : 1 stackLang$prog) = T``;
val _ = out "nsh_load_empty" ``no_shmemop (wStackLoad [] Skip : 64 stackLang$prog) = T``;
val _ = out "nsh_load_loads" ``no_shmemop (wStackLoad [(1,0);(9,999)] Tick : 64 stackLang$prog) = T``;
val _ = out "nsh_load_forbidden" ``no_shmemop (wStackLoad [(1,0);(9,999)] (ShMemOp Load 0 (Addr 1 0w)) : 64 stackLang$prog) = F``;
val _ = out "nsh_write1_register" ``no_shmemop (wRegWrite1 (\r. Skip) 0 (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_write1_stack" ``no_shmemop (wRegWrite1 (\r. Tick) 999 (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_write1_forbidden" ``no_shmemop (wRegWrite1 (\r. ShMemOp Load 0 (Addr 1 0w)) 999 (2,0,99) : 64 stackLang$prog) = F``;
val _ = out "nsh_write2_register" ``no_shmemop (wRegWrite2 (\r. Skip) 0 (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_write2_stack" ``no_shmemop (wRegWrite2 (\r. Tick) 999 (2,0,99) : 64 stackLang$prog) = T``;
val _ = out "nsh_write2_forbidden" ``no_shmemop (wRegWrite2 (\r. ShMemOp Load 0 (Addr 1 0w)) 999 (2,0,99) : 64 stackLang$prog) = F``;
val _ = out "nsh_live_zero" ``no_shmemop (FST (wLive (LN,LN) (List [],17) (0,0,999)) : 64 stackLang$prog) = T``;
val _ = out "nsh_live_nonzero" ``no_shmemop (FST (wLive (LN,LN) (List [],17) (2,3,5)) : 64 stackLang$prog) = T``;
val _ = out "nsh_live_width1" ``no_shmemop (FST (wLive (LN,LN) (List [],17) (0,1,999)) : 1 stackLang$prog) = T``;
val _ = out "nsh_stack_zero" ``no_shmemop (stack_move 0 999 0 77 (ShMemOp Load 0 (Addr 1 0w)) : 64 stackLang$prog) = F``;
val _ = out "nsh_stack_positive" ``no_shmemop (stack_move 4 999 0 77 (Skip) : 64 stackLang$prog) = T``;
val _ = out "nsh_stack_forbidden" ``no_shmemop (stack_move 4 999 0 77 (ShMemOp Load 0 (Addr 1 0w)) : 64 stackLang$prog) = F``;
