load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory word_to_stackTheory wordsTheory;
val _ = Globals.linewidth := 2000;
val bits_to_word_bit = prove(``  !bs i.
      i < dimindex (:'a) /\ i < LENGTH bs ==>
      ((bits_to_word bs:'a word) ' i = EL i bs)``,   Induct \\ fs [] \\ Cases_on `i` \\ fs []
  \\ Cases \\ fs [bits_to_word_def,word_or_def,fcpTheory.FCP_BETA,
       word_index,word_lsl_def,ADD1]);
val _ = (if null(hyp bits_to_word_bit) then () else raise Fail "open source context premise"; print "bs_source_bit="; print_thm bits_to_word_bit; print "\n");
val replay_miss = prove(``  !bs i.
      i < dimindex (:'a) /\ LENGTH bs <= i ==>
      ~((bits_to_word bs:'a word) ' i)``,   Induct \\ fs [] THEN1 (EVAL_TAC \\ fs [word_0])
  \\ Cases_on `i` \\ fs [] \\ NTAC 2 strip_tac
  \\ `n < dimindex (:'a)` by decide_tac \\ res_tac
  \\ Cases_on `h` \\ fs [bits_to_word_def,word_or_def,fcpTheory.FCP_BETA,
       word_index,word_lsl_def,ADD1]);
val _ = (if null(hyp replay_miss) then () else raise Fail "open replay premise"; print "bs_full_miss="; print_thm replay_miss; print "\n");
val replay_snoc = prove(`` !bs b.
  bits_to_word (SNOC b bs) =
 (if b then 1w else 0w) ≪ (LENGTH bs) ‖ (bits_to_word bs)``,   Induct
  >> simp[Once $ oneline bits_to_word_def, bits_to_word_def]
  >> qpat_abbrev_tac `bits_to_word_bs = bits_to_word bs`
  >> simp[Once $ oneline bits_to_word_def, bits_to_word_def]
  >> rw[] >> simp[ADD1]);
val _ = (if null(hyp replay_snoc) then () else raise Fail "open replay premise"; print "bs_full_snoc="; print_thm replay_snoc; print "\n");
val replay_prefix = prove(``  LENGTH (xs ++ ys) <= dimindex (:'a) ==>
    GENLIST (\i. (bits_to_word (xs ++ ys):'a word) ' i) (LENGTH xs) = xs``,   fs[Cong GENLIST_CONG,bits_to_word_bit,EL_APPEND1] >>
  fs[GENLIST_EL_MAP]);
val _ = (if null(hyp replay_prefix) then () else raise Fail "open replay premise"; print "bs_full_prefix="; print_thm replay_prefix; print "\n");
fun emit label q = let val th = EVAL q in print(label ^ "="); print_thm th; print "\n" end;
val _ = emit "bs_snoc_0_0_1" ``(bits_to_word (SNOC F []):1 word) = ((if F then (1w:1 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_0_1" ``w2n (bits_to_word (SNOC F []):1 word)``;
val _ = emit "bs_snoc_0_1_1" ``(bits_to_word (SNOC T []):1 word) = ((if T then (1w:1 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_1_1" ``w2n (bits_to_word (SNOC T []):1 word)``;
val _ = emit "bs_miss_0_0_1" ``~((bits_to_word []:1 word) ' 0)``;
val _ = emit "bs_snoc_1_0_1" ``(bits_to_word (SNOC F [F]):1 word) = ((if F then (1w:1 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_0_1" ``w2n (bits_to_word (SNOC F [F]):1 word)``;
val _ = emit "bs_snoc_1_1_1" ``(bits_to_word (SNOC T [F]):1 word) = ((if T then (1w:1 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_1_1" ``w2n (bits_to_word (SNOC T [F]):1 word)``;
val _ = emit "bs_snoc_2_0_1" ``(bits_to_word (SNOC F [T]):1 word) = ((if F then (1w:1 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_0_1" ``w2n (bits_to_word (SNOC F [T]):1 word)``;
val _ = emit "bs_snoc_2_1_1" ``(bits_to_word (SNOC T [T]):1 word) = ((if T then (1w:1 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_1_1" ``w2n (bits_to_word (SNOC T [T]):1 word)``;
val _ = emit "bs_snoc_3_0_1" ``(bits_to_word (SNOC F [T;F;T]):1 word) = ((if F then (1w:1 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_0_1" ``w2n (bits_to_word (SNOC F [T;F;T]):1 word)``;
val _ = emit "bs_snoc_3_1_1" ``(bits_to_word (SNOC T [T;F;T]):1 word) = ((if T then (1w:1 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_1_1" ``w2n (bits_to_word (SNOC T [T;F;T]):1 word)``;
val _ = emit "bs_snoc_4_0_1" ``(bits_to_word (SNOC F [F;T;F;T]):1 word) = ((if F then (1w:1 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_0_1" ``w2n (bits_to_word (SNOC F [F;T;F;T]):1 word)``;
val _ = emit "bs_snoc_4_1_1" ``(bits_to_word (SNOC T [F;T;F;T]):1 word) = ((if T then (1w:1 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_1_1" ``w2n (bits_to_word (SNOC T [F;T;F;T]):1 word)``;
val _ = emit "bs_snoc_5_0_1" ``(bits_to_word (SNOC F [T;T;T]):1 word) = ((if F then (1w:1 word) else 0w) << LENGTH [T;T;T]) || bits_to_word [T;T;T]``;
val _ = emit "bs_value_5_0_1" ``w2n (bits_to_word (SNOC F [T;T;T]):1 word)``;
val _ = emit "bs_snoc_5_1_1" ``(bits_to_word (SNOC T [T;T;T]):1 word) = ((if T then (1w:1 word) else 0w) << LENGTH [T;T;T]) || bits_to_word [T;T;T]``;
val _ = emit "bs_value_5_1_1" ``w2n (bits_to_word (SNOC T [T;T;T]):1 word)``;
val _ = emit "bs_prefix_0_1" ``GENLIST (\i. (bits_to_word ([] ++ []):1 word) ' i) 0 = []``;
val _ = emit "bs_prefix_1_1" ``GENLIST (\i. (bits_to_word ([] ++ [T]):1 word) ' i) 0 = []``;
val _ = emit "bs_prefix_2_1" ``GENLIST (\i. (bits_to_word ([T] ++ []):1 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_3_1" ``GENLIST (\i. (bits_to_word ([F] ++ []):1 word) ' i) 1 = [F]``;
val _ = emit "bs_prefix_6_1" ``GENLIST (\i. (bits_to_word ([T] ++ []):1 word) ' i) 1 = [T]``;
val _ = emit "bs_snoc_0_0_2" ``(bits_to_word (SNOC F []):2 word) = ((if F then (1w:2 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_0_2" ``w2n (bits_to_word (SNOC F []):2 word)``;
val _ = emit "bs_snoc_0_1_2" ``(bits_to_word (SNOC T []):2 word) = ((if T then (1w:2 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_1_2" ``w2n (bits_to_word (SNOC T []):2 word)``;
val _ = emit "bs_miss_0_0_2" ``~((bits_to_word []:2 word) ' 0)``;
val _ = emit "bs_miss_0_1_2" ``~((bits_to_word []:2 word) ' 1)``;
val _ = emit "bs_snoc_1_0_2" ``(bits_to_word (SNOC F [F]):2 word) = ((if F then (1w:2 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_0_2" ``w2n (bits_to_word (SNOC F [F]):2 word)``;
val _ = emit "bs_snoc_1_1_2" ``(bits_to_word (SNOC T [F]):2 word) = ((if T then (1w:2 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_1_2" ``w2n (bits_to_word (SNOC T [F]):2 word)``;
val _ = emit "bs_miss_1_1_2" ``~((bits_to_word [F]:2 word) ' 1)``;
val _ = emit "bs_snoc_2_0_2" ``(bits_to_word (SNOC F [T]):2 word) = ((if F then (1w:2 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_0_2" ``w2n (bits_to_word (SNOC F [T]):2 word)``;
val _ = emit "bs_snoc_2_1_2" ``(bits_to_word (SNOC T [T]):2 word) = ((if T then (1w:2 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_1_2" ``w2n (bits_to_word (SNOC T [T]):2 word)``;
val _ = emit "bs_miss_2_1_2" ``~((bits_to_word [T]:2 word) ' 1)``;
val _ = emit "bs_snoc_3_0_2" ``(bits_to_word (SNOC F [T;F;T]):2 word) = ((if F then (1w:2 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_0_2" ``w2n (bits_to_word (SNOC F [T;F;T]):2 word)``;
val _ = emit "bs_snoc_3_1_2" ``(bits_to_word (SNOC T [T;F;T]):2 word) = ((if T then (1w:2 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_1_2" ``w2n (bits_to_word (SNOC T [T;F;T]):2 word)``;
val _ = emit "bs_snoc_4_0_2" ``(bits_to_word (SNOC F [F;T;F;T]):2 word) = ((if F then (1w:2 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_0_2" ``w2n (bits_to_word (SNOC F [F;T;F;T]):2 word)``;
val _ = emit "bs_snoc_4_1_2" ``(bits_to_word (SNOC T [F;T;F;T]):2 word) = ((if T then (1w:2 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_1_2" ``w2n (bits_to_word (SNOC T [F;T;F;T]):2 word)``;
val _ = emit "bs_snoc_5_0_2" ``(bits_to_word (SNOC F [T;T;T;T]):2 word) = ((if F then (1w:2 word) else 0w) << LENGTH [T;T;T;T]) || bits_to_word [T;T;T;T]``;
val _ = emit "bs_value_5_0_2" ``w2n (bits_to_word (SNOC F [T;T;T;T]):2 word)``;
val _ = emit "bs_snoc_5_1_2" ``(bits_to_word (SNOC T [T;T;T;T]):2 word) = ((if T then (1w:2 word) else 0w) << LENGTH [T;T;T;T]) || bits_to_word [T;T;T;T]``;
val _ = emit "bs_value_5_1_2" ``w2n (bits_to_word (SNOC T [T;T;T;T]):2 word)``;
val _ = emit "bs_prefix_0_2" ``GENLIST (\i. (bits_to_word ([] ++ []):2 word) ' i) 0 = []``;
val _ = emit "bs_prefix_1_2" ``GENLIST (\i. (bits_to_word ([] ++ [T]):2 word) ' i) 0 = []``;
val _ = emit "bs_prefix_2_2" ``GENLIST (\i. (bits_to_word ([T] ++ []):2 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_3_2" ``GENLIST (\i. (bits_to_word ([F] ++ []):2 word) ' i) 1 = [F]``;
val _ = emit "bs_prefix_4_2" ``GENLIST (\i. (bits_to_word ([T] ++ [F]):2 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_6_2" ``GENLIST (\i. (bits_to_word ([T;T] ++ []):2 word) ' i) 2 = [T;T]``;
val _ = emit "bs_snoc_0_0_8" ``(bits_to_word (SNOC F []):8 word) = ((if F then (1w:8 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_0_8" ``w2n (bits_to_word (SNOC F []):8 word)``;
val _ = emit "bs_snoc_0_1_8" ``(bits_to_word (SNOC T []):8 word) = ((if T then (1w:8 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_1_8" ``w2n (bits_to_word (SNOC T []):8 word)``;
val _ = emit "bs_miss_0_0_8" ``~((bits_to_word []:8 word) ' 0)``;
val _ = emit "bs_miss_0_7_8" ``~((bits_to_word []:8 word) ' 7)``;
val _ = emit "bs_snoc_1_0_8" ``(bits_to_word (SNOC F [F]):8 word) = ((if F then (1w:8 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_0_8" ``w2n (bits_to_word (SNOC F [F]):8 word)``;
val _ = emit "bs_snoc_1_1_8" ``(bits_to_word (SNOC T [F]):8 word) = ((if T then (1w:8 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_1_8" ``w2n (bits_to_word (SNOC T [F]):8 word)``;
val _ = emit "bs_miss_1_1_8" ``~((bits_to_word [F]:8 word) ' 1)``;
val _ = emit "bs_miss_1_7_8" ``~((bits_to_word [F]:8 word) ' 7)``;
val _ = emit "bs_snoc_2_0_8" ``(bits_to_word (SNOC F [T]):8 word) = ((if F then (1w:8 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_0_8" ``w2n (bits_to_word (SNOC F [T]):8 word)``;
val _ = emit "bs_snoc_2_1_8" ``(bits_to_word (SNOC T [T]):8 word) = ((if T then (1w:8 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_1_8" ``w2n (bits_to_word (SNOC T [T]):8 word)``;
val _ = emit "bs_miss_2_1_8" ``~((bits_to_word [T]:8 word) ' 1)``;
val _ = emit "bs_miss_2_7_8" ``~((bits_to_word [T]:8 word) ' 7)``;
val _ = emit "bs_snoc_3_0_8" ``(bits_to_word (SNOC F [T;F;T]):8 word) = ((if F then (1w:8 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_0_8" ``w2n (bits_to_word (SNOC F [T;F;T]):8 word)``;
val _ = emit "bs_snoc_3_1_8" ``(bits_to_word (SNOC T [T;F;T]):8 word) = ((if T then (1w:8 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_1_8" ``w2n (bits_to_word (SNOC T [T;F;T]):8 word)``;
val _ = emit "bs_miss_3_3_8" ``~((bits_to_word [T;F;T]:8 word) ' 3)``;
val _ = emit "bs_miss_3_7_8" ``~((bits_to_word [T;F;T]:8 word) ' 7)``;
val _ = emit "bs_snoc_4_0_8" ``(bits_to_word (SNOC F [F;T;F;T]):8 word) = ((if F then (1w:8 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_0_8" ``w2n (bits_to_word (SNOC F [F;T;F;T]):8 word)``;
val _ = emit "bs_snoc_4_1_8" ``(bits_to_word (SNOC T [F;T;F;T]):8 word) = ((if T then (1w:8 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_1_8" ``w2n (bits_to_word (SNOC T [F;T;F;T]):8 word)``;
val _ = emit "bs_miss_4_4_8" ``~((bits_to_word [F;T;F;T]:8 word) ' 4)``;
val _ = emit "bs_miss_4_7_8" ``~((bits_to_word [F;T;F;T]:8 word) ' 7)``;
val _ = emit "bs_snoc_5_0_8" ``(bits_to_word (SNOC F [T;T;T;T;T;T;T;T;T;T]):8 word) = ((if F then (1w:8 word) else 0w) << LENGTH [T;T;T;T;T;T;T;T;T;T]) || bits_to_word [T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_value_5_0_8" ``w2n (bits_to_word (SNOC F [T;T;T;T;T;T;T;T;T;T]):8 word)``;
val _ = emit "bs_snoc_5_1_8" ``(bits_to_word (SNOC T [T;T;T;T;T;T;T;T;T;T]):8 word) = ((if T then (1w:8 word) else 0w) << LENGTH [T;T;T;T;T;T;T;T;T;T]) || bits_to_word [T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_value_5_1_8" ``w2n (bits_to_word (SNOC T [T;T;T;T;T;T;T;T;T;T]):8 word)``;
val _ = emit "bs_prefix_0_8" ``GENLIST (\i. (bits_to_word ([] ++ []):8 word) ' i) 0 = []``;
val _ = emit "bs_prefix_1_8" ``GENLIST (\i. (bits_to_word ([] ++ [T]):8 word) ' i) 0 = []``;
val _ = emit "bs_prefix_2_8" ``GENLIST (\i. (bits_to_word ([T] ++ []):8 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_3_8" ``GENLIST (\i. (bits_to_word ([F] ++ []):8 word) ' i) 1 = [F]``;
val _ = emit "bs_prefix_4_8" ``GENLIST (\i. (bits_to_word ([T] ++ [F]):8 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_5_8" ``GENLIST (\i. (bits_to_word ([T;F] ++ [T]):8 word) ' i) 2 = [T;F]``;
val _ = emit "bs_prefix_6_8" ``GENLIST (\i. (bits_to_word ([T;T;T;T;T;T;T;T] ++ []):8 word) ' i) 8 = [T;T;T;T;T;T;T;T]``;
val _ = emit "bs_snoc_0_0_64" ``(bits_to_word (SNOC F []):64 word) = ((if F then (1w:64 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_0_64" ``w2n (bits_to_word (SNOC F []):64 word)``;
val _ = emit "bs_snoc_0_1_64" ``(bits_to_word (SNOC T []):64 word) = ((if T then (1w:64 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_1_64" ``w2n (bits_to_word (SNOC T []):64 word)``;
val _ = emit "bs_miss_0_0_64" ``~((bits_to_word []:64 word) ' 0)``;
val _ = emit "bs_miss_0_63_64" ``~((bits_to_word []:64 word) ' 63)``;
val _ = emit "bs_snoc_1_0_64" ``(bits_to_word (SNOC F [F]):64 word) = ((if F then (1w:64 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_0_64" ``w2n (bits_to_word (SNOC F [F]):64 word)``;
val _ = emit "bs_snoc_1_1_64" ``(bits_to_word (SNOC T [F]):64 word) = ((if T then (1w:64 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_1_64" ``w2n (bits_to_word (SNOC T [F]):64 word)``;
val _ = emit "bs_miss_1_1_64" ``~((bits_to_word [F]:64 word) ' 1)``;
val _ = emit "bs_miss_1_63_64" ``~((bits_to_word [F]:64 word) ' 63)``;
val _ = emit "bs_snoc_2_0_64" ``(bits_to_word (SNOC F [T]):64 word) = ((if F then (1w:64 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_0_64" ``w2n (bits_to_word (SNOC F [T]):64 word)``;
val _ = emit "bs_snoc_2_1_64" ``(bits_to_word (SNOC T [T]):64 word) = ((if T then (1w:64 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_1_64" ``w2n (bits_to_word (SNOC T [T]):64 word)``;
val _ = emit "bs_miss_2_1_64" ``~((bits_to_word [T]:64 word) ' 1)``;
val _ = emit "bs_miss_2_63_64" ``~((bits_to_word [T]:64 word) ' 63)``;
val _ = emit "bs_snoc_3_0_64" ``(bits_to_word (SNOC F [T;F;T]):64 word) = ((if F then (1w:64 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_0_64" ``w2n (bits_to_word (SNOC F [T;F;T]):64 word)``;
val _ = emit "bs_snoc_3_1_64" ``(bits_to_word (SNOC T [T;F;T]):64 word) = ((if T then (1w:64 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_1_64" ``w2n (bits_to_word (SNOC T [T;F;T]):64 word)``;
val _ = emit "bs_miss_3_3_64" ``~((bits_to_word [T;F;T]:64 word) ' 3)``;
val _ = emit "bs_miss_3_63_64" ``~((bits_to_word [T;F;T]:64 word) ' 63)``;
val _ = emit "bs_snoc_4_0_64" ``(bits_to_word (SNOC F [F;T;F;T]):64 word) = ((if F then (1w:64 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_0_64" ``w2n (bits_to_word (SNOC F [F;T;F;T]):64 word)``;
val _ = emit "bs_snoc_4_1_64" ``(bits_to_word (SNOC T [F;T;F;T]):64 word) = ((if T then (1w:64 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_1_64" ``w2n (bits_to_word (SNOC T [F;T;F;T]):64 word)``;
val _ = emit "bs_miss_4_4_64" ``~((bits_to_word [F;T;F;T]:64 word) ' 4)``;
val _ = emit "bs_miss_4_63_64" ``~((bits_to_word [F;T;F;T]:64 word) ' 63)``;
val _ = emit "bs_snoc_5_0_64" ``(bits_to_word (SNOC F [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):64 word) = ((if F then (1w:64 word) else 0w) << LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]) || bits_to_word [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_value_5_0_64" ``w2n (bits_to_word (SNOC F [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):64 word)``;
val _ = emit "bs_snoc_5_1_64" ``(bits_to_word (SNOC T [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):64 word) = ((if T then (1w:64 word) else 0w) << LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]) || bits_to_word [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_value_5_1_64" ``w2n (bits_to_word (SNOC T [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):64 word)``;
val _ = emit "bs_prefix_0_64" ``GENLIST (\i. (bits_to_word ([] ++ []):64 word) ' i) 0 = []``;
val _ = emit "bs_prefix_1_64" ``GENLIST (\i. (bits_to_word ([] ++ [T]):64 word) ' i) 0 = []``;
val _ = emit "bs_prefix_2_64" ``GENLIST (\i. (bits_to_word ([T] ++ []):64 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_3_64" ``GENLIST (\i. (bits_to_word ([F] ++ []):64 word) ' i) 1 = [F]``;
val _ = emit "bs_prefix_4_64" ``GENLIST (\i. (bits_to_word ([T] ++ [F]):64 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_5_64" ``GENLIST (\i. (bits_to_word ([T;F] ++ [T]):64 word) ' i) 2 = [T;F]``;
val _ = emit "bs_prefix_6_64" ``GENLIST (\i. (bits_to_word ([T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] ++ []):64 word) ' i) 64 = [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_snoc_0_0_80" ``(bits_to_word (SNOC F []):80 word) = ((if F then (1w:80 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_0_80" ``w2n (bits_to_word (SNOC F []):80 word)``;
val _ = emit "bs_snoc_0_1_80" ``(bits_to_word (SNOC T []):80 word) = ((if T then (1w:80 word) else 0w) << LENGTH []) || bits_to_word []``;
val _ = emit "bs_value_0_1_80" ``w2n (bits_to_word (SNOC T []):80 word)``;
val _ = emit "bs_miss_0_0_80" ``~((bits_to_word []:80 word) ' 0)``;
val _ = emit "bs_miss_0_79_80" ``~((bits_to_word []:80 word) ' 79)``;
val _ = emit "bs_snoc_1_0_80" ``(bits_to_word (SNOC F [F]):80 word) = ((if F then (1w:80 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_0_80" ``w2n (bits_to_word (SNOC F [F]):80 word)``;
val _ = emit "bs_snoc_1_1_80" ``(bits_to_word (SNOC T [F]):80 word) = ((if T then (1w:80 word) else 0w) << LENGTH [F]) || bits_to_word [F]``;
val _ = emit "bs_value_1_1_80" ``w2n (bits_to_word (SNOC T [F]):80 word)``;
val _ = emit "bs_miss_1_1_80" ``~((bits_to_word [F]:80 word) ' 1)``;
val _ = emit "bs_miss_1_79_80" ``~((bits_to_word [F]:80 word) ' 79)``;
val _ = emit "bs_snoc_2_0_80" ``(bits_to_word (SNOC F [T]):80 word) = ((if F then (1w:80 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_0_80" ``w2n (bits_to_word (SNOC F [T]):80 word)``;
val _ = emit "bs_snoc_2_1_80" ``(bits_to_word (SNOC T [T]):80 word) = ((if T then (1w:80 word) else 0w) << LENGTH [T]) || bits_to_word [T]``;
val _ = emit "bs_value_2_1_80" ``w2n (bits_to_word (SNOC T [T]):80 word)``;
val _ = emit "bs_miss_2_1_80" ``~((bits_to_word [T]:80 word) ' 1)``;
val _ = emit "bs_miss_2_79_80" ``~((bits_to_word [T]:80 word) ' 79)``;
val _ = emit "bs_snoc_3_0_80" ``(bits_to_word (SNOC F [T;F;T]):80 word) = ((if F then (1w:80 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_0_80" ``w2n (bits_to_word (SNOC F [T;F;T]):80 word)``;
val _ = emit "bs_snoc_3_1_80" ``(bits_to_word (SNOC T [T;F;T]):80 word) = ((if T then (1w:80 word) else 0w) << LENGTH [T;F;T]) || bits_to_word [T;F;T]``;
val _ = emit "bs_value_3_1_80" ``w2n (bits_to_word (SNOC T [T;F;T]):80 word)``;
val _ = emit "bs_miss_3_3_80" ``~((bits_to_word [T;F;T]:80 word) ' 3)``;
val _ = emit "bs_miss_3_79_80" ``~((bits_to_word [T;F;T]:80 word) ' 79)``;
val _ = emit "bs_snoc_4_0_80" ``(bits_to_word (SNOC F [F;T;F;T]):80 word) = ((if F then (1w:80 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_0_80" ``w2n (bits_to_word (SNOC F [F;T;F;T]):80 word)``;
val _ = emit "bs_snoc_4_1_80" ``(bits_to_word (SNOC T [F;T;F;T]):80 word) = ((if T then (1w:80 word) else 0w) << LENGTH [F;T;F;T]) || bits_to_word [F;T;F;T]``;
val _ = emit "bs_value_4_1_80" ``w2n (bits_to_word (SNOC T [F;T;F;T]):80 word)``;
val _ = emit "bs_miss_4_4_80" ``~((bits_to_word [F;T;F;T]:80 word) ' 4)``;
val _ = emit "bs_miss_4_79_80" ``~((bits_to_word [F;T;F;T]:80 word) ' 79)``;
val _ = emit "bs_snoc_5_0_80" ``(bits_to_word (SNOC F [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):80 word) = ((if F then (1w:80 word) else 0w) << LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]) || bits_to_word [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_value_5_0_80" ``w2n (bits_to_word (SNOC F [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):80 word)``;
val _ = emit "bs_snoc_5_1_80" ``(bits_to_word (SNOC T [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):80 word) = ((if T then (1w:80 word) else 0w) << LENGTH [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]) || bits_to_word [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]``;
val _ = emit "bs_value_5_1_80" ``w2n (bits_to_word (SNOC T [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]):80 word)``;
val _ = emit "bs_prefix_0_80" ``GENLIST (\i. (bits_to_word ([] ++ []):80 word) ' i) 0 = []``;
val _ = emit "bs_prefix_1_80" ``GENLIST (\i. (bits_to_word ([] ++ [T]):80 word) ' i) 0 = []``;
val _ = emit "bs_prefix_2_80" ``GENLIST (\i. (bits_to_word ([T] ++ []):80 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_3_80" ``GENLIST (\i. (bits_to_word ([F] ++ []):80 word) ' i) 1 = [F]``;
val _ = emit "bs_prefix_4_80" ``GENLIST (\i. (bits_to_word ([T] ++ [F]):80 word) ' i) 1 = [T]``;
val _ = emit "bs_prefix_5_80" ``GENLIST (\i. (bits_to_word ([T;F] ++ [T]):80 word) ' i) 2 = [T;F]``;
val _ = emit "bs_prefix_6_80" ``GENLIST (\i. (bits_to_word ([T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T] ++ []):80 word) ' i) 80 = [T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T;T]``;
fun typ label q = (print(label ^ "="); print_type(type_of q); print "\n");
val _ = typ "bs_type_word" ``(bits_to_word:bool list -> 'a word)``;
val _ = typ "bs_type_list" ``(bs:bool list)``;
