load "preamble";
load "word_to_stackTheory";
load "wordConvsTheory";
load "stackPropsTheory";
(* Finite unions are evaluated by FOLDR UNION EMPTY, the list form of BIGUNION. *)
open bossLib HolKernel Parse preamble word_to_stackTheory;
fun out label q = (print (label ^ "="); print_term (rconc (EVAL q)); print "\n");
val rhs = ``(a:num#num) INSERT b INSERT (s:num#num->bool) UNION h``;
val grouped = ``(a:num#num) INSERT b INSERT ((s:num#num->bool) UNION h)``;
val _ = out "pl_rhs_group" (if aconv rhs grouped then ``T`` else ``F``);
val _ = out "pl_empty" ``let p = []; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({}, {}, {}, [],5,T)``;
val _ = out "pl_duplicates" ``let p = [(7,0,wordLang$LocValue 0 8);(7,0,wordLang$LocValue 0 9)]; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({(8,0);(9,0)},{8;9},{},[0;0],5,T)``;
val _ = out "pl_spilled" ``let p = [(7,0,wordLang$LocValue 99 8)]; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({(8,0)},{8},{},[47],5,T)``;
val _ = out "pl_owned" ``let p = [(7,0,wordLang$Call (SOME ([],(LN,LN),wordLang$LocValue 0 8,11,12)) (SOME 10) [] (SOME (0,wordLang$LocValue 0 9,7,5)))]; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({(7,5);(10,0);(8,0);(9,0)},{10;8;9},{(7,5)},[0],5,T)``;
val _ = out "pl_wrong_owner" ``let p = [(7,0,wordLang$Call (SOME ([],(LN,LN),wordLang$LocValue 0 8,11,12)) (SOME 10) [] (SOME (0,wordLang$LocValue 0 9,9,5)))]; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({(9,5);(10,0);(8,0);(9,0)},{10;8;9},{},[0],5,F)``;
val _ = out "pl_tail_drop" ``let p = [(7,0,wordLang$Call NONE (SOME 8) [] (SOME (0,wordLang$LocValue 0 9,999,6)))]; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({(8,0)},{8;9},{},[0],5,T)``;
val _ = out "pl_threaded" ``let p = [(7,5,wordLang$Alloc 0 (LN,LN));(8,0,wordLang$StoreConsts 0 0 0 0 [])]; (ps,fs,bm,i) = compile_word_to_stack (c:64 asm$asm_config) F 4 p (Append (List [8w]) (List [2w]),5) in (FOLDR $UNION {} (MAP (stackProps$get_code_labels o SND) ps),FOLDR $UNION {} (MAP (\(n,m,pp).wordConvs$get_code_labels pp) p),FOLDR $UNION {} (MAP (\(n,pp).stackProps$stack_get_handler_labels n pp) ps),fs,i,EVERY (\(n,m,pp).wordConvs$good_handlers n pp) p) = ({(store_consts_stub_location,0)},{},{},[2;0],7,T)``;
