load "bossLib";
load "preamble";
load "word_allocTheory";
open bossLib HolKernel Parse preamble word_allocTheory;
fun observe label term = let val th = EVAL term in print (label ^ "="); print_term (rhs (concl th)); print "\n" end;
val _ = observe "gf_addcarry_riscv" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (AddCarry 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_addcarry_mips" ``get_forced ((c:64 asm_config) with ISA := MIPS) (Inst (Arith (AddCarry 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_addcarry_self" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (AddCarry 1 2 1 1)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_addcarry_x86" ``get_forced ((c:64 asm_config) with ISA := x86_64) (Inst (Arith (AddCarry 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_addovf_riscv" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (AddOverflow 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_addovf_armv8" ``get_forced ((c:64 asm_config) with ISA := ARMv8) (Inst (Arith (AddOverflow 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_subovf_mips" ``get_forced ((c:64 asm_config) with ISA := MIPS) (Inst (Arith (SubOverflow 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_subovf_self" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (SubOverflow 3 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_longmul_armv7" ``get_forced ((c:64 asm_config) with ISA := ARMv7) (Inst (Arith (LongMul 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_longmul_armv7_self" ``get_forced ((c:64 asm_config) with ISA := ARMv7) (Inst (Arith (LongMul 1 1 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_longmul_riscv" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (LongMul 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_longmul_ag32" ``get_forced ((c:64 asm_config) with ISA := Ag32) (Inst (Arith (LongMul 1 2 1 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_longmul_x86" ``get_forced ((c:64 asm_config) with ISA := x86_64) (Inst (Arith (LongMul 1 2 3 4)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_fptoreg_32" ``get_forced ((c:32 asm_config) with ISA := RISC_V) (Inst (FP (FPMovToReg 1 2 0)):32 wordLang$prog) [(9,8)]``;
val _ = observe "gf_fptoreg_32_self" ``get_forced ((c:32 asm_config) with ISA := RISC_V) (Inst (FP (FPMovToReg 1 1 0)):32 wordLang$prog) [(9,8)]``;
val _ = observe "gf_fptoreg_64" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (FP (FPMovToReg 1 2 0)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_fpfromreg_32" ``get_forced ((c:32 asm_config) with ISA := x86_64) (Inst (FP (FPMovFromReg 0 1 2)):32 wordLang$prog) [(9,8)]``;
val _ = observe "gf_fpfromreg_64" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (FP (FPMovFromReg 0 1 2)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_other_inst" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (Div 1 2 3)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_seq" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Seq (Inst (Arith (AddOverflow 1 2 3 4))) (Inst (Arith (AddOverflow 5 6 7 8))):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_if" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (If Equal 0 (Imm 0w) (Inst (Arith (AddOverflow 1 2 3 4))) (Inst (Arith (AddOverflow 5 6 7 8))):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_must" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (MustTerminate (Inst (Arith (AddOverflow 1 2 3 4))):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_loop" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Loop LN (Inst (Arith (AddOverflow 1 2 3 4))) LN:64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_call_return" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Call (SOME ([1],(LN,LN),Inst (Arith (AddOverflow 1 2 3 4)),17,19)) NONE [] NONE:64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_call_both" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Call (SOME ([1],(LN,LN),Inst (Arith (AddOverflow 1 2 3 4)),17,19)) NONE [] (SOME (1,Inst (Arith (AddOverflow 5 6 7 8)),11,13)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_call_tail" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Call NONE NONE [] (SOME (1,Inst (Arith (AddOverflow 5 6 7 8)),11,13)):64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_skip" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Skip:64 wordLang$prog) [(9,8)]``;
val _ = observe "gf_large" ``get_forced ((c:64 asm_config) with ISA := RISC_V) (Inst (Arith (AddOverflow 36893488147419103232 0 36893488147419103233 0)):64 wordLang$prog) []``;
