load "bossLib"; load "preamble"; load "word_cseTheory";
open HolKernel Parse bossLib preamble word_cseTheory;
fun out label q = (print(label ^ "="); print_term(rconc(EVAL q)); print "\n");
val _ = out "cc_skip" ``word_common_subexp_elim (Skip:8 wordLang$prog) = Skip``;
val _ = out "cc_move" ``word_common_subexp_elim (Move 1 [(1,3)]:8 wordLang$prog) = Move 1 [(1,3)]``;
val _ = out "cc_const" ``word_common_subexp_elim (Seq (Inst (Const 1 7w)) (Inst (Const 3 7w)):8 wordLang$prog) = Seq (Inst (Const 1 7w)) (Inst (Const 3 7w))``;
val _ = out "cc_get" ``word_common_subexp_elim (Seq (Get 1 HeapLength) (Get 3 HeapLength):8 wordLang$prog) = Seq (Get 1 HeapLength) (Move 1 [(3,1)])``;
val _ = out "cc_load" ``word_common_subexp_elim (Seq (Inst (Mem Load 1 (Addr 3 0w))) (Inst (Mem Load 5 (Addr 3 0w))):8 wordLang$prog) = Seq (Inst (Mem Load 1 (Addr 3 0w))) (Move 0 [(5,1)])``;
val _ = out "cc_offset" ``word_common_subexp_elim (Seq (Inst (Mem Load8 1 (Addr 3 7w))) (Inst (Mem Load8 5 (Addr 3 7w))):8 wordLang$prog) = Seq (Inst (Mem Load8 1 (Addr 3 7w))) (Move 0 [(5,1)])``;
val _ = out "cc_shift" ``word_common_subexp_elim (Seq (Inst (Arith (Shift Lsl 1 3 (Imm 1w)))) (Inst (Arith (Shift Lsl 5 3 (Imm 1w)))):8 wordLang$prog) = Seq (Inst (Arith (Shift Lsl 1 3 (Imm 1w)))) (Move 0 [(5,1)])``;
val _ = out "cc_load16" ``word_common_subexp_elim (Inst (Mem Load16 1 (Addr 3 7w)):8 wordLang$prog) = Inst (Mem Load16 1 (Addr 3 7w))``;
val _ = out "cc_share" ``word_common_subexp_elim (ShareInst Load 1 (Var 3):8 wordLang$prog) = ShareInst Load 1 (Var 3)``;
val _ = out "cc_loop" ``word_common_subexp_elim (Loop LN (Seq (Get 1 HeapLength) (Get 3 HeapLength)) LN:8 wordLang$prog) = Loop LN (Seq (Get 1 HeapLength) (Move 1 [(3,1)])) LN``;
val _ = out "cc_must" ``word_common_subexp_elim (MustTerminate (Seq (Get 1 HeapLength) (Get 3 HeapLength)):8 wordLang$prog) = MustTerminate (Seq (Get 1 HeapLength) (Move 1 [(3,1)]))``;
val _ = out "cc_if" ``word_common_subexp_elim (If Equal 1 (Imm 0w) (Seq (Get 3 HeapLength) (Get 5 HeapLength)) Skip:8 wordLang$prog) = If Equal 1 (Imm 0w) (Seq (Get 3 HeapLength) (Move 1 [(5,3)])) Skip``;
val _ = out "cc_tail" ``word_common_subexp_elim (Call NONE (SOME 7) [] (SOME(1,Seq (Get 3 HeapLength) (Get 5 HeapLength),2,3)):8 wordLang$prog) = Call NONE (SOME 7) [] (SOME(1,Seq (Get 3 HeapLength) (Get 5 HeapLength),2,3))``;
val _ = out "cc_return" ``word_common_subexp_elim (Call (SOME([], (LN,LN),Seq (Get 3 HeapLength) (Get 5 HeapLength),2,3)) (SOME 7) [] (SOME(1,Inst (Const 5 7w),4,5)):8 wordLang$prog) = Call (SOME([], (LN,LN),Seq (Get 3 HeapLength) (Get 5 HeapLength),2,3)) (SOME 7) [] (SOME(1,Inst (Const 5 7w),4,5))``;
val _ = out "cc_store_barrier" ``word_common_subexp_elim (Seq (Inst (Mem Load 1 (Addr 3 0w))) (Seq (Inst (Mem Store 5 (Addr 7 0w))) (Inst (Mem Load 9 (Addr 3 0w)))):8 wordLang$prog) = Seq (Inst (Mem Load 1 (Addr 3 0w))) (Seq (Inst (Mem Store 5 (Addr 7 0w))) (Inst (Mem Load 9 (Addr 3 0w))))``;
val _ = out "cc_call_barrier" ``word_common_subexp_elim (Seq (Get 1 HeapLength) (Seq (Call NONE (SOME 7) [] NONE) (Get 3 HeapLength)):8 wordLang$prog) = Seq (Get 1 HeapLength) (Seq (Call NONE (SOME 7) [] NONE) (Get 3 HeapLength))``;
