load "word_instProofTheory";
load "wordPropsTheory";
load "miscTheory";
load "sortingTheory";
open HolKernel Parse bossLib;
val _ = Globals.linewidth := 1000000;
val _ = (print "pull_ops_simp_def_statement="; print_term(concl word_instProofTheory.pull_ops_simp_def));
val _ = print("pull_ops_simp_def_hypotheses=" ^ Int.toString(length(hyp word_instProofTheory.pull_ops_simp_def)) ^ "\n");
val _ = (print "binary_branch_exp_def_statement="; print_term(concl word_instProofTheory.binary_branch_exp_def));
val _ = print("binary_branch_exp_def_hypotheses=" ^ Int.toString(length(hyp word_instProofTheory.binary_branch_exp_def)) ^ "\n");
val _ = (print "inst_select_thm_statement="; print_term(concl word_instProofTheory.inst_select_thm));
val _ = print("inst_select_thm_hypotheses=" ^ Int.toString(length(hyp word_instProofTheory.inst_select_thm)) ^ "\n");
val _ = (print "inst_select_Loop_helper_statement="; print_term(concl word_instProofTheory.inst_select_Loop_helper));
val _ = print("inst_select_Loop_helper_hypotheses=" ^ Int.toString(length(hyp word_instProofTheory.inst_select_Loop_helper)) ^ "\n");
val _ = (print "locals_rel_def_statement="; print_term(concl wordPropsTheory.locals_rel_def));
val _ = print("locals_rel_def_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_def)) ^ "\n");
val _ = (print "the_words_EVERY_IS_SOME_statement="; print_term(concl wordPropsTheory.the_words_EVERY_IS_SOME));
val _ = print("the_words_EVERY_IS_SOME_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.the_words_EVERY_IS_SOME)) ^ "\n");
val _ = (print "locals_rel_get_vars_statement="; print_term(concl wordPropsTheory.locals_rel_get_vars));
val _ = print("locals_rel_get_vars_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_get_vars)) ^ "\n");
val _ = (print "locals_rel_alist_insert_statement="; print_term(concl wordPropsTheory.locals_rel_alist_insert));
val _ = print("locals_rel_alist_insert_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_alist_insert)) ^ "\n");
val _ = (print "locals_rel_get_var_statement="; print_term(concl wordPropsTheory.locals_rel_get_var));
val _ = print("locals_rel_get_var_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_get_var)) ^ "\n");
val _ = (print "locals_rel_get_var_simp_statement="; print_term(concl wordPropsTheory.locals_rel_get_var_simp));
val _ = print("locals_rel_get_var_simp_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_get_var_simp)) ^ "\n");
val _ = (print "locals_rel_get_vars_simp_statement="; print_term(concl wordPropsTheory.locals_rel_get_vars_simp));
val _ = print("locals_rel_get_vars_simp_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_get_vars_simp)) ^ "\n");
val _ = (print "locals_rel_get_var_imm_statement="; print_term(concl wordPropsTheory.locals_rel_get_var_imm));
val _ = print("locals_rel_get_var_imm_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_get_var_imm)) ^ "\n");
val _ = (print "locals_rel_get_var_imm_simp_statement="; print_term(concl wordPropsTheory.locals_rel_get_var_imm_simp));
val _ = print("locals_rel_get_var_imm_simp_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_get_var_imm_simp)) ^ "\n");
val _ = (print "locals_rel_word_exp_statement="; print_term(concl wordPropsTheory.locals_rel_word_exp));
val _ = print("locals_rel_word_exp_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_word_exp)) ^ "\n");
val _ = (print "locals_rel_word_exp_simp_statement="; print_term(concl wordPropsTheory.locals_rel_word_exp_simp));
val _ = print("locals_rel_word_exp_simp_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_word_exp_simp)) ^ "\n");
val _ = (print "locals_rel_cut_envs_statement="; print_term(concl wordPropsTheory.locals_rel_cut_envs));
val _ = print("locals_rel_cut_envs_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_cut_envs)) ^ "\n");
val _ = (print "locals_rel_cut_env_statement="; print_term(concl wordPropsTheory.locals_rel_cut_env));
val _ = print("locals_rel_cut_env_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_cut_env)) ^ "\n");
val _ = (print "locals_rel_evaluate_thm_statement="; print_term(concl wordPropsTheory.locals_rel_evaluate_thm));
val _ = print("locals_rel_evaluate_thm_hypotheses=" ^ Int.toString(length(hyp wordPropsTheory.locals_rel_evaluate_thm)) ^ "\n");
val _ = (print "PERM_PART_statement="; print_term(concl miscTheory.PERM_PART));
val _ = print("PERM_PART_hypotheses=" ^ Int.toString(length(hyp miscTheory.PERM_PART)) ^ "\n");
val _ = (print "PERM_PARTITION_statement="; print_term(concl miscTheory.PERM_PARTITION));
val _ = print("PERM_PARTITION_hypotheses=" ^ Int.toString(length(hyp miscTheory.PERM_PARTITION)) ^ "\n");
val _ = (print "PARTs_HAVE_PROP_statement="; print_term(concl sortingTheory.PARTs_HAVE_PROP));
val _ = print("PARTs_HAVE_PROP_hypotheses=" ^ Int.toString(length(hyp sortingTheory.PARTs_HAVE_PROP)) ^ "\n");
val _ = (print "inst_select_thm_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl word_instProofTheory.inst_select_thm));
val _ = (print "inst_select_Loop_helper_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl word_instProofTheory.inst_select_Loop_helper));
val _ = (print "locals_rel_evaluate_thm_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl wordPropsTheory.locals_rel_evaluate_thm));
