import Flapjack.Compiler.Backend.Parmove.Steps

namespace Flapjack.Compiler.Backend.Parmove

/-- Primitive least relation generated by the source six-clause Hol_reln.
The source has no separately named Definition for the generated relation;
its actual rules, induction principle and cases theorem are tagged below.
NoRead is the source local overload ¬MEM register (MAP SND pending). -/
inductive DStep {α : Type} : State α → State α → Prop
  | removeSelf (r : Option α) (μ τ : List (Move α)) :
      DStep ([(r,r)] ++ μ,[],τ) (μ,[],τ)
  | start (d s : Option α) (μ τ : List (Move α)) (distinct : s ≠ d) :
      DStep ([(d,s)] ++ μ,[],τ) (μ,[(d,s)],τ)
  | extend (d r s : Option α) (μ1 μ2 σ τ : List (Move α)) (noRead : d ∉ μ1.map Prod.snd) :
      DStep (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ) (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ)
  | saveEmit (r s d : Option α) (μ σ τ : List (Move α)) (noRead : r ∉ μ.map Prod.snd) :
      DStep (μ,[(r,s)] ++ σ ++ [(d,r)],τ) (μ,σ ++ [(d,none)],[(r,s),(none,r)] ++ τ)
  | emitHead (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)) (noRead : dn ∉ μ.map Prod.snd) (distinct : dn ≠ s0) :
      DStep (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ)
  | emitLast (d s : Option α) (μ τ : List (Move α)) (noRead : d ∉ μ.map Prod.snd) :
      DStep (μ,[(d,s)],τ) (μ,[],[(d,s)] ++ τ)

@[hol "cakeml/compiler/backend/reg_alloc/parmoveScript.sml" "dstep_rules"]
theorem dstep_rules {α : Type} :
    (∀ (r : Option α) (μ τ : List (Move α)),
      DStep ([(r,r)] ++ μ,[],τ) (μ,[],τ)) ∧
    (∀ (d s : Option α) (μ τ : List (Move α)),
      s ≠ d →
      DStep ([(d,s)] ++ μ,[],τ) (μ,[(d,s)],τ)) ∧
    (∀ (d r s : Option α) (μ1 μ2 σ τ : List (Move α)),
      d ∉ μ1.map Prod.snd →
      DStep (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ) (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ)) ∧
    (∀ (d r s : Option α) (μ σ τ : List (Move α)),
      r ∉ μ.map Prod.snd →
      DStep (μ,[(r,s)] ++ σ ++ [(d,r)],τ) (μ,σ ++ [(d,none)],[(r,s),(none,r)] ++ τ)) ∧
    (∀ (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)),
      dn ∉ μ.map Prod.snd ∧ dn ≠ s0 →
      DStep (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ)) ∧
    (∀ (d s : Option α) (μ τ : List (Move α)),
      d ∉ μ.map Prod.snd →
      DStep (μ,[(d,s)],τ) (μ,[],[(d,s)] ++ τ)) := by
  exact ⟨DStep.removeSelf,
    fun d s μ τ h => DStep.start d s μ τ h,
    fun d r s μ1 μ2 σ τ h => DStep.extend d r s μ1 μ2 σ τ h,
    fun d r s μ σ τ h => DStep.saveEmit r s d μ σ τ h,
    fun d0 dn s0 sn μ σ τ h => DStep.emitHead d0 dn s0 sn μ σ τ h.1 h.2,
    fun d s μ τ h => DStep.emitLast d s μ τ h⟩

@[hol "cakeml/compiler/backend/reg_alloc/parmoveScript.sml" "dstep_ind"]
theorem dstep_ind {α : Type} (P : State α → State α → Prop) :
    (∀ (r : Option α) (μ τ : List (Move α)),
      P ([(r,r)] ++ μ,[],τ) (μ,[],τ)) ∧
    (∀ (d s : Option α) (μ τ : List (Move α)),
      s ≠ d →
      P ([(d,s)] ++ μ,[],τ) (μ,[(d,s)],τ)) ∧
    (∀ (d r s : Option α) (μ1 μ2 σ τ : List (Move α)),
      d ∉ μ1.map Prod.snd →
      P (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ) (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ)) ∧
    (∀ (d r s : Option α) (μ σ τ : List (Move α)),
      r ∉ μ.map Prod.snd →
      P (μ,[(r,s)] ++ σ ++ [(d,r)],τ) (μ,σ ++ [(d,none)],[(r,s),(none,r)] ++ τ)) ∧
    (∀ (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)),
      dn ∉ μ.map Prod.snd ∧ dn ≠ s0 →
      P (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ)) ∧
    (∀ (d s : Option α) (μ τ : List (Move α)),
      d ∉ μ.map Prod.snd →
      P (μ,[(d,s)],τ) (μ,[],[(d,s)] ++ τ)) →
    ∀ first second, DStep first second → P first second := by
  intro h first second step
  cases step with
  | removeSelf r μ τ  => exact h.1 r μ τ
  | start d s μ τ distinct => exact h.2.1 d s μ τ distinct
  | extend d r s μ1 μ2 σ τ noRead => exact h.2.2.1 d r s μ1 μ2 σ τ noRead
  | saveEmit r s d μ σ τ noRead => exact h.2.2.2.1 d r s μ σ τ noRead
  | emitHead d0 dn s0 sn μ σ τ noRead distinct => exact h.2.2.2.2.1 d0 dn s0 sn μ σ τ ⟨noRead, distinct⟩
  | emitLast d s μ τ noRead => exact h.2.2.2.2.2 d s μ τ noRead

@[hol "cakeml/compiler/backend/reg_alloc/parmoveScript.sml" "dstep_cases"]
theorem dstep_cases {α : Type} (first second : State α) :
    DStep first second ↔
    (∃ (r : Option α) (μ τ : List (Move α)),
      first = ([(r,r)] ++ μ,[],τ) ∧ second = (μ,[],τ)) ∨
    (∃ (d s : Option α) (μ τ : List (Move α)),
      first = ([(d,s)] ++ μ,[],τ) ∧ second = (μ,[(d,s)],τ) ∧ s ≠ d) ∨
    (∃ (d r s : Option α) (μ1 μ2 σ τ : List (Move α)),
      first = (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ) ∧ second = (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ) ∧ d ∉ μ1.map Prod.snd) ∨
    (∃ (r s d : Option α) (μ σ τ : List (Move α)),
      first = (μ,[(r,s)] ++ σ ++ [(d,r)],τ) ∧ second = (μ,σ ++ [(d,none)],[(r,s),(none,r)] ++ τ) ∧ r ∉ μ.map Prod.snd) ∨
    (∃ (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)),
      first = (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) ∧ second = (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ) ∧ dn ∉ μ.map Prod.snd ∧ dn ≠ s0) ∨
    (∃ (d s : Option α) (μ τ : List (Move α)),
      first = (μ,[(d,s)],τ) ∧ second = (μ,[],[(d,s)] ++ τ) ∧ d ∉ μ.map Prod.snd) := by
  constructor
  · intro step
    cases step with
    | removeSelf r μ τ => exact Or.inl ⟨r, μ, τ, rfl, rfl⟩
    | start d s μ τ distinct => exact Or.inr (Or.inl ⟨d, s, μ, τ, rfl, rfl, distinct⟩)
    | extend d r s μ1 μ2 σ τ noRead => exact Or.inr (Or.inr (Or.inl ⟨d, r, s, μ1, μ2, σ, τ, rfl, rfl, noRead⟩))
    | saveEmit r s d μ σ τ noRead => exact Or.inr (Or.inr (Or.inr (Or.inl ⟨r, s, d, μ, σ, τ, rfl, rfl, noRead⟩)))
    | emitHead d0 dn s0 sn μ σ τ noRead distinct => exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl ⟨d0, dn, s0, sn, μ, σ, τ, rfl, rfl, noRead, distinct⟩))))
    | emitLast d s μ τ noRead => exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (⟨d, s, μ, τ, rfl, rfl, noRead⟩)))))
  · intro h
    rcases h with h | h | h | h | h | h
    · rcases h with ⟨r, μ, τ, rfl, rfl⟩
      exact DStep.removeSelf r μ τ
    · rcases h with ⟨d, s, μ, τ, rfl, rfl, distinct⟩
      exact DStep.start d s μ τ distinct
    · rcases h with ⟨d, r, s, μ1, μ2, σ, τ, rfl, rfl, noRead⟩
      exact DStep.extend d r s μ1 μ2 σ τ noRead
    · rcases h with ⟨r, s, d, μ, σ, τ, rfl, rfl, noRead⟩
      exact DStep.saveEmit r s d μ σ τ noRead
    · rcases h with ⟨d0, dn, s0, sn, μ, σ, τ, rfl, rfl, noRead, distinct⟩
      exact DStep.emitHead d0 dn s0 sn μ σ τ noRead distinct
    · rcases h with ⟨d, s, μ, τ, rfl, rfl, noRead⟩
      exact DStep.emitLast d s μ τ noRead

/-- Flapjack infrastructure rendering the source RTC dstep overload.
There is no separate HOL declaration for this overload. -/
abbrev DSteps {α : Type} : State α → State α → Prop := Relation.ReflTransGen DStep

end Flapjack.Compiler.Backend.Parmove
