import Flapjack.Compiler.Backend.Parmove
import Mathlib.Logic.Relation

namespace Flapjack.Compiler.Backend.Parmove

/-- The primitive relation generated by HOL's six-clause Hol_reln command.
There is no separate named source Definition for this generated constant;
its defining rules, cases and least-relation property are tagged below. -/
inductive Step {α : Type} : State α → State α → Prop
  | removeSelf (r : Option α) (before after active emitted : List (Move α)) :
      Step (before ++ [(r,r)] ++ after, active, emitted) (before ++ after, active, emitted)
  | start (d s : Option α) (before after emitted : List (Move α)) :
      Step (before ++ [(d,s)] ++ after, [], emitted) (before ++ after, [(d,s)], emitted)
  | extend (d r s : Option α) (before after active emitted : List (Move α)) :
      Step (before ++ [(r,d)] ++ after, [(d,s)] ++ active, emitted)
        (before ++ after, [(r,d),(d,s)] ++ active, emitted)
  | save (d s : Option α) (pending active emitted : List (Move α)) :
      Step (pending, active ++ [(d,s)], emitted)
        (pending, active ++ [(d,none)], [(none,s)] ++ emitted)
  | emitHead (d0 dn s0 sn : Option α) (pending active emitted : List (Move α))
      (noRead : dn ∉ pending.map Prod.snd) (distinct : dn ≠ s0) :
      Step (pending, [(dn,sn)] ++ active ++ [(d0,s0)], emitted)
        (pending, active ++ [(d0,s0)], [(dn,sn)] ++ emitted)
  | emitLast (d s : Option α) (pending emitted : List (Move α))
      (noRead : d ∉ pending.map Prod.snd) :
      Step (pending, [(d,s)], emitted) (pending, [], [(d,s)] ++ emitted)

@[hol "cakeml/compiler/backend/reg_alloc/parmoveScript.sml" "step_rules"]
theorem step_rules {α : Type} :
    (∀ (r : Option α) (μ1 μ2 σ τ : List (Move α)),
      Step (μ1 ++ [(r,r)] ++ μ2,σ,τ) (μ1 ++ μ2,σ,τ)) ∧
    (∀ (d s : Option α) (μ1 μ2 τ : List (Move α)),
      Step (μ1 ++ [(d,s)] ++ μ2,[],τ) (μ1 ++ μ2,[(d,s)],τ)) ∧
    (∀ (d r s : Option α) (μ1 μ2 σ τ : List (Move α)),
      Step (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ)
        (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ)) ∧
    (∀ (d s : Option α) (μ σ τ : List (Move α)),
      Step (μ,σ ++ [(d,s)],τ) (μ,σ ++ [(d,none)],[(none,s)] ++ τ)) ∧
    (∀ (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)),
      dn ∉ μ.map Prod.snd ∧ dn ≠ s0 →
      Step (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ)) ∧
    (∀ (d s : Option α) (μ τ : List (Move α)),
      d ∉ μ.map Prod.snd → Step (μ,[(d,s)],τ) (μ,[],[(d,s)] ++ τ)) := by
  exact ⟨Step.removeSelf, Step.start, Step.extend, Step.save,
    fun d0 dn s0 sn μ σ τ h => Step.emitHead d0 dn s0 sn μ σ τ h.1 h.2,
    Step.emitLast⟩

@[hol "cakeml/compiler/backend/reg_alloc/parmoveScript.sml" "step_ind"]
theorem step_ind {α : Type} (P : State α → State α → Prop) :
    (∀ (r : Option α) (μ1 μ2 σ τ : List (Move α)),
      P (μ1 ++ [(r,r)] ++ μ2,σ,τ) (μ1 ++ μ2,σ,τ)) ∧
    (∀ (d s : Option α) (μ1 μ2 τ : List (Move α)),
      P (μ1 ++ [(d,s)] ++ μ2,[],τ) (μ1 ++ μ2,[(d,s)],τ)) ∧
    (∀ (d r s : Option α) (μ1 μ2 σ τ : List (Move α)),
      P (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ)
        (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ)) ∧
    (∀ (d s : Option α) (μ σ τ : List (Move α)),
      P (μ,σ ++ [(d,s)],τ) (μ,σ ++ [(d,none)],[(none,s)] ++ τ)) ∧
    (∀ (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)),
      dn ∉ μ.map Prod.snd ∧ dn ≠ s0 →
      P (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ)) ∧
    (∀ (d s : Option α) (μ τ : List (Move α)),
      d ∉ μ.map Prod.snd → P (μ,[(d,s)],τ) (μ,[],[(d,s)] ++ τ)) → ∀ first second, Step first second → P first second := by
  intro h first second step
  cases step with
  | removeSelf r μ1 μ2 σ τ => exact h.1 r μ1 μ2 σ τ
  | start d s μ1 μ2 τ => exact h.2.1 d s μ1 μ2 τ
  | extend d r s μ1 μ2 σ τ => exact h.2.2.1 d r s μ1 μ2 σ τ
  | save d s μ σ τ => exact h.2.2.2.1 d s μ σ τ
  | emitHead d0 dn s0 sn μ σ τ noRead distinct =>
      exact h.2.2.2.2.1 d0 dn s0 sn μ σ τ ⟨noRead, distinct⟩
  | emitLast d s μ τ noRead => exact h.2.2.2.2.2 d s μ τ noRead

@[hol "cakeml/compiler/backend/reg_alloc/parmoveScript.sml" "step_cases"]
theorem step_cases {α : Type} (first second : State α) :
    Step first second ↔
    (∃ (r : Option α) (μ1 μ2 σ τ : List (Move α)),
      first = (μ1 ++ [(r,r)] ++ μ2,σ,τ) ∧ second = (μ1 ++ μ2,σ,τ)) ∨
    (∃ (d s : Option α) (μ1 μ2 τ : List (Move α)),
      first = (μ1 ++ [(d,s)] ++ μ2,[],τ) ∧ second = (μ1 ++ μ2,[(d,s)],τ)) ∨
    (∃ (d r s : Option α) (μ1 μ2 σ τ : List (Move α)),
      first = (μ1 ++ [(r,d)] ++ μ2,[(d,s)] ++ σ,τ) ∧
      second = (μ1 ++ μ2,[(r,d),(d,s)] ++ σ,τ)) ∨
    (∃ (d s : Option α) (μ σ τ : List (Move α)),
      first = (μ,σ ++ [(d,s)],τ) ∧ second = (μ,σ ++ [(d,none)],[(none,s)] ++ τ)) ∨
    (∃ (d0 dn s0 sn : Option α) (μ σ τ : List (Move α)),
      first = (μ,[(dn,sn)] ++ σ ++ [(d0,s0)],τ) ∧
      second = (μ,σ ++ [(d0,s0)],[(dn,sn)] ++ τ) ∧ dn ∉ μ.map Prod.snd ∧ dn ≠ s0) ∨
    (∃ (d s : Option α) (μ τ : List (Move α)),
      first = (μ,[(d,s)],τ) ∧ second = (μ,[],[(d,s)] ++ τ) ∧ d ∉ μ.map Prod.snd) := by
  constructor
  · intro h
    cases h with
    | removeSelf r μ1 μ2 σ τ => exact Or.inl ⟨r, μ1, μ2, σ, τ, rfl, rfl⟩
    | start d s μ1 μ2 τ => exact Or.inr (Or.inl ⟨d, s, μ1, μ2, τ, rfl, rfl⟩)
    | extend d r s μ1 μ2 σ τ =>
        exact Or.inr (Or.inr (Or.inl ⟨d, r, s, μ1, μ2, σ, τ, rfl, rfl⟩))
    | save d s μ σ τ =>
        exact Or.inr (Or.inr (Or.inr (Or.inl ⟨d, s, μ, σ, τ, rfl, rfl⟩)))
    | emitHead d0 dn s0 sn μ σ τ noRead distinct =>
        exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl
          ⟨d0, dn, s0, sn, μ, σ, τ, rfl, rfl, noRead, distinct⟩))))
    | emitLast d s μ τ noRead =>
        exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr ⟨d, s, μ, τ, rfl, rfl, noRead⟩))))
  · intro h
    rcases h with h | h | h | h | h | h
    · rcases h with ⟨r, μ1, μ2, σ, τ, rfl, rfl⟩
      exact Step.removeSelf r μ1 μ2 σ τ
    · rcases h with ⟨d, s, μ1, μ2, τ, rfl, rfl⟩
      exact Step.start d s μ1 μ2 τ
    · rcases h with ⟨d, r, s, μ1, μ2, σ, τ, rfl, rfl⟩
      exact Step.extend d r s μ1 μ2 σ τ
    · rcases h with ⟨d, s, μ, σ, τ, rfl, rfl⟩
      exact Step.save d s μ σ τ
    · rcases h with ⟨d0, dn, s0, sn, μ, σ, τ, rfl, rfl, noRead, distinct⟩
      exact Step.emitHead d0 dn s0 sn μ σ τ noRead distinct
    · rcases h with ⟨d, s, μ, τ, rfl, rfl, noRead⟩
      exact Step.emitLast d s μ τ noRead

/-- HOL's local overload for RTC step, rendered using the ordinary inductive
reflexive-transitive closure. No named HOL declaration defines the overload. -/
abbrev Steps {α : Type} : State α → State α → Prop := Relation.ReflTransGen Step

end Flapjack.Compiler.Backend.Parmove
