import Flapjack.Compiler.Backend.WordAlloc.Proofs.SSAConventions.Primitives
-- Reuse the native match congruence auxiliaries generated by fun_cases.
import Flapjack.Compiler.Backend.WordAlloc.ProductionSSAMemoryGuard

namespace Flapjack.WordAlloc
open Flapjack Flapjack.Compiler.Backend.WordAlloc

/-- Full original instruction case of the SSA convention theorem. All native
instruction constructors and word-width branches remain in scope. -/
@[hol "cakeml/compiler/backend/proofs/word_allocProofScript.sml"
  "ssa_cc_trans_pre_alloc_conventions" (words_as_type_indexed_bitvec)]
theorem ssaCcTrans_preAllocInst {width : Nat} [NeZero width]
    (instruction : WordLangInst (BitVec width))
    (ssa : Spt Nat) (next : Nat) (tables : List (Spt Nat × Spt Unit × Spt Unit))
    (_h : isAllocVar next ∧ ssaMapOK next ssa) :
    let (output, _, _) : WordLangProgHOL (BitVec width) × Spt Nat × Nat :=
      ssaCcTrans (.inst instruction) ssa next tables
    preAllocConventionsHOL output = true := by
  simp only [ssaCcTrans]
  fun_cases ssaCcTransInst instruction ssa next <;>
    simp_all [nextVarRename, preAllocConventionsHOL, everyStackVarHOL,
      callArgConventionHOL, instArgConvention]

end Flapjack.WordAlloc
