import Flapjack.Compiler.Backend.RegAlloc.Carriers
import Flapjack.Translator.Monadic.MonadBase

namespace Flapjack.RegAlloc

/-- The literal carrier generated by `define_run`: five list fields become
length/element pairs; every other field retains its original type. Lengths
are independent and need not agree with `dim`. The generator's stale comment
reverses the pair, but its type and REPLICATE code use length first. -/
@[hol "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "ira_state"]
structure IraState where
  adj_ls : Nat × List Nat
  node_tag : Nat × Tag
  degrees : Nat × Nat
  dim : Nat
  simp_wl : List Nat
  spill_wl : List Nat
  freeze_wl : List Nat
  avail_moves_wl : List (Nat × (Nat × Nat))
  unavail_moves_wl : List (Nat × (Nat × Nat))
  coalesced : Nat × Nat
  move_related : Nat × Bool
  stack : List Nat
  deriving DecidableEq, Repr

/-- The generated runner expands precisely its five designated arrays. Its
computation, result and exception are arbitrary; no consistency or successful
evaluation premise is imposed. This native runner is proof-side support;
the executed allocator's state correspondence remains on the parent bead. -/
@[hol "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "run_ira_state_def"]
def runIraState {value exception : Type}
    (x : Translator.Monadic.MonadBase.M State value exception)
    (state : IraState) : Translator.Monadic.MonadBase.Exc value exception :=
  Translator.Monadic.MonadBase.run x
    { adj_ls := List.replicate state.adj_ls.1 state.adj_ls.2
      node_tag := List.replicate state.node_tag.1 state.node_tag.2
      degrees := List.replicate state.degrees.1 state.degrees.2
      dim := state.dim
      simp_wl := state.simp_wl
      spill_wl := state.spill_wl
      freeze_wl := state.freeze_wl
      avail_moves_wl := state.avail_moves_wl
      unavail_moves_wl := state.unavail_moves_wl
      coalesced := List.replicate state.coalesced.1 state.coalesced.2
      move_related := List.replicate state.move_related.1 state.move_related.2
      stack := state.stack }

end Flapjack.RegAlloc
